### ISSUE TITLE
More Advanced Tutorials?

### ISSUE THREAD

**Issue by toastonrye** [CyclopsMC/IntegratedDynamics#1000]
So I am trying to learn Integrated Dynamics again, it seems so powerful but I can't find any examples of people using it on Youtube or Reddit for anything besides the basics.... It's so powerful and it seems under used.

I've been playing with it for 4 hours tonight just trying to understand Operators, applying stuff, piping, conjunctions. I don't see how this puzzle fits together. I last played with this year ago and quit for the same reason. I am at a complete loss for how the green operator type works, besides the fact it will probably allow the player to build complex dynamic functions.

**Comment by rubensworks** [comment]
I would suggest joining our Discord server: https://discord.gg/9yDxubB
Plenty of smart people in there that would be happy to explain this to you.

<blockquote><img src="https://cdn.discordapp.com/icons/386052815128100865/68f625b3e17e3b805e762a37a4d4e97f.jpg?size=256" width="48" align="right"><div><img src="/assets/07dca80a102d4149e9736d4b162cff6f.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/9yDxubB">Join the CyclopsMC Discord Server!</a></strong></div><div>Check out the CyclopsMC community on Discord - hang out with 1,177 other members and enjoy free voice and text chat.</div></blockquote>

**Comment by toastonrye** [comment]
FYI - For anyone in the future, the Discord is super helpful. I only got around to checking it out after almost a full year!

Someone helped me with a simple example of operators and piping so I made a few small tutorial videos.
https://youtube.com/playlist?list=PLmdNYPmangZl7jXQfGlWNjavzRkld25rN
