### ISSUE TITLE
Client crash when trying to build a List of Recipes

### ISSUE THREAD

**Issue by lavraleksej** [CyclopsMC/IntegratedDynamics#1001]
#### Issue type:

- :bug: Bug 

____

#### Short description: 

Attempting to construct a List of Recipes using the Logic Programmer causes a client crash
#### Steps to reproduce the problem:

1. Open the Logic Programmer List builder
2. Switch the type to Recipe
3. Press the +

#### Expected behaviour:

The Logic Programmer switches to the Recipe builder or asks for a Recipe Variable Card
____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.5.0-40.jar (dev build) 
- Minecraft: 1.16.5
- Forge: 36.0.39

#### Log file:

[crash-2021-03-02_03.20.33-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6065295/crash-2021-03-02_03.20.33-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Won't crash anymore now, but still buggy because of #641.
