### ISSUE TITLE
Cyclic bag with filter on crashes client.

### ISSUE THREAD

**Issue by cddrury** [CyclopsMC/IntegratedDynamics#1002]
#### Issue type:

- :bug: Bug 

____

#### Short description:

With the cyclic storage bag set to filter items, the minecraft client crashes when a block is broken (i.e. mined).

#### Steps to reproduce the problem:

1. Cyclic bag in hotbar with no filter set -> break block (block goes into inventory)
2. Set cyclic bag to filter (whitelist) -> break block (game crashes)

#### Expected behaviour:

Ideally, the game won't crash.

____

#### Versions:

- This mod: 1.5.3b
- Minecraft: 1.16.5
- Forge: 36.0.43

#### Log file:

[minecraft crash.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6079567/minecraft.crash.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Wrong mod?
I don't see what this has to do with Integrated Dynamics, it's also not mentioned in the crashlog.
