### ISSUE TITLE
Bugs with Materializer

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1004]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Materializer behaves weirdly sometimes:
1. It won't properly materialize card. When you try to click result slot card somehow appears and you can drag it into your inventory. Clicking on empty card makes it disappear and move to output.
![obraz](https://user-images.githubusercontent.com/6943031/110636516-a0f99000-81ac-11eb-9f29-974d0772dc3a.png)
2. I tried to make operator that would end up being Entity->List (list contains Offers.Recipes of librarian villager) but I can't materialize it. Instead I get exceptions in log.
3. This one partially belongs here as exception is the same. It involved my approach to solving problem 2 by using InNBT. InNBT author will be also notified about this.

#### Steps to reproduce the problem:
1. Try to materialize something. I tried 'apply' card.
2.

     1. Create Entity ->NBT operator
     2. Create String, NBT -> NBT operator
     3. Create string card with '.Offers.Recipes'
     4. Apply string card to String, NBT -> NBT card making it NBT->NBT card
     5. Pipe Entity ->NBT and NBT->NBT cards together making it new Entity -> NBT card
     6. Try to materialize newly created Entity->NBT card
3.

     1. Create librarian Entity card
     2. Turn said card into NBT so that NBT Extractor could process it
     3. Use NBT Extractor to get Offers.Recipes path card in operator mode
     4. Create Entity ->NBT operator
     5. Pipe both cards together
     6. Try to materialize said cards

#### Expected behaviour:
1. Card is automatically/properly moved to result slot.
2. Card is properly materialized.
3. Card is properly materialized.

____

#### Versions:

- This mod: 
![obraz](https://user-images.githubusercontent.com/6943031/110641020-c89f2700-81b1-11eb-95a1-1ce3c7207038.png)

- Minecraft: 1.16.5
- Forge: 36.0.46

#### Log file:
https://pastebin.com/hbhenKfd

**Comment by rubensworks** [comment]
Thanks for reporting!
