### ISSUE TITLE
Crash when cables are removed indirectly

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1005]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Game crashes if Ice & Fire dragon decides to fire its breath on InDy network. Error looks like any unexpected damage of the network will cause this problem.

#### Steps to reproduce the problem:
Create InDy network.
Spawn some cows close to the network to help dragons target it.
~50 blocks away spawn few dragons, make sure that large ones that can use breath attacks are spawned.
Wait or spawn some more cows as needed.

#### Expected behaviour:
Network is damaged, but game does not crash

____

#### Versions:

- This mod: 
![obraz](https://user-images.githubusercontent.com/6943031/110796052-d3bc8a80-8277-11eb-887f-c6d2bcadbb7e.png)

- Minecraft: 1.16.5
- Forge: 36.0.46

#### Log file:
https://pastebin.com/SHxHTMaD

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Game crashes if Ice & Fire dragon decides to fire its breath on InDy network.

Can you try reproducing this with pure Vanilla mechanics?
Otherwise I can't be sure that it's not just this mod breaking blocks in the wrong way.

**Comment by Hiranus** [comment]
https://pastebin.com/F5HVzmvK

There is only one vanilla way of replacing blocks - respawning ender dragon and I did that. 
First attempt failed - I didn't use any cards, and nothing special happened, just cables were connected to the bedrock that replaced some of the cables. 
Second attempt succeeded - game crashed. I created item card that contained some dirt and block card that relied on the item card. Item card was placed in the screen that was put  in place that is part of vanilla bedrock fountain/nest and which will be replaced by resurrecting dragon with bedrock. Second card was few blocks away, connected with cable. I placed 4 crystals and started dragon resurrection, which regenerated fountain, which replaced screen with item card with bedrock, which caused crash.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/F5HVzmvK">MultiMC version: 0.6.12-develop-1521Minecraft folder is:G:/MultiMC/insta - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for checking!

Note to self: consider forcefully removing network positions when they are not found during a network tick. A cleaner solution would be to somehow listen to all external block removals.
