### ISSUE TITLE
"Exception in server tick loop" Crash when Audio Writer plays Sound from string with invalid format

### ISSUE THREAD

**Issue by LorefiendElianne** [CyclopsMC/IntegratedDynamics#1006]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Giving the Audio Writer's Sound feature a Variable Card holding a string that doesn't follow the correct naming convention (specifically, one that has a "non [a-z0-9/._-] character" in it) will immediately crash the server.

#### Steps to reproduce the problem:

1. Acquire any string Variable card with non [a-z0-9/._-] characters saved
2. Place it in the "Sound" slot of the Audio Writer.
3. The next time the Audio Writer ticks, the game will crash due to trying to load a sound file with an invalid name.

#### Expected behaviour:

Some kind of validation to make sure the audio writer does not try to play a sound file that would crash the game due to its' invalid name, to prevent the issue happening in case of a missclick or malicious player.
____

#### Versions:

- This mod: 1.6.0 
- Minecraft: 1.16.5
- Forge: 36.0.54

#### Log file:

https://paste.ee/p/wCWG2

**Comment by rubensworks** [comment]
Thanks for reporting!
