### ISSUE TITLE
Attaching crafting interface to crafting table causes server to hang and crash.

### ISSUE THREAD

**Issue by Seceroth** [CyclopsMC/IntegratedDynamics#1008]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Playing Enigmatica 6, version 0.4.3. I am using ID for almost my whole base (which really isn't big at all yet). Storage is done with RFTools modular storage, 11 with 300/500 item stack modules inside. Most are filled. The Storage terminal item crafting tab is very laggy. Using JEI with this tab open causes recipe lookup to take abnormally long (>3 seconds for some recipes and no lag for some other recipes) causing both client and server to hang. Putting a recipe in the terminal and shift clicking it to craft a stack will halt the whole server (but not client) until it's done crafting the stack, which can take up to 10 seconds.
This could also be all RFTools' fault, but I don't know.

![2021-03-18_13 10 56](https://user-images.githubusercontent.com/20866237/111627428-f2c29b80-87e6-11eb-8235-7af7996b3617.png)
![2021-03-18_13 12 59](https://user-images.githubusercontent.com/20866237/111627488-0241e480-87e7-11eb-8708-eca510b703df.png)
![2021-03-18_13 09 37](https://user-images.githubusercontent.com/20866237/111627531-0cfc7980-87e7-11eb-81a8-48f253ab04fc.png)

#### Steps to reproduce the problem:

1. Setup RFTools Modular storage with a lot of items.
2. Attach Item interfaces from ID to them.
3. In the same network, attach a crafting interface to an crafting table.
4. Observe lag.

____

#### Versions:

Modpack Enigmatica 6

- This mod: IntegratedCrafting-1.16.5-1.0.12
- Minecraft: 1.16.5
- Forge: 36.0.45

#### Profiler output:

Using spark while just letting things run, not doing anything results in this (ran for about 10seconds):
https://spark.lucko.me/6T9WkSlL6t

Included crash report from the server when a single tick took over 300 seconds:
[crash-2021-03-18_13.17.17-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6164018/crash-2021-03-18_13.17.17-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Seceroth** [comment]
Update.
So I changed my entire storage from RFTools Storage to Occultism. It's all in one Interdimensional storage block now. Tried to start some autocrafting again and the same thing happened. So it's not the Modular Storage's fault. Seems like ID is unable to handle a large amount of items with the terminals and crafting interfaces. Or TheOneProbe may have something to do with this (since it's mentioned in the crash report)?
Did not have this issue in 1.12, although I may have more items now. Sadly unplayable like this. The Occultism crafting grid works without any lag while the terminals connected to the storage are freezing constantly while doing anything.
Still on the modpack Enigmatica version 0.4.3.

Crash report from the server when attaching a crafting interface to the network:
[crash-2021-03-20_18.48.17-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6176085/crash-2021-03-20_18.48.17-server.txt)

**Comment by Seceroth** [comment]
Spark log, taken over ~15 seconds while no one is online and no chunks should be loaded:

https://spark.lucko.me/Nrlk4n1NYB

Waiting for feedback before I just take down the ID network, maybe you'll want to check out my setup?

<blockquote><img src="https://spark.lucko.me/assets/logo-512.png" width="48" align="right"><div>spark</div><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiling plugin/mod for Minecraft clients, servers and proxies.</div></blockquote>

**Comment by rubensworks** [comment]
Sure, you can tear it down. But could you take a backup so you can confirm it's fixed once I've had time to look into and fix this?

**Comment by Seceroth** [comment]
Yes sir. Backup will be made. Would love to use the mod more!

**Comment by rubensworks** [comment]
Performance should be better in the latest CyclopsCore dev build, feel free to try out that one (see link in readme), or wait on the next release.

Should this still be an issue after the change, please let me know.
