### ISSUE TITLE
mapped list not updating

### ISSUE THREAD

**Issue by quarz12** [CyclopsMC/IntegratedDynamics#1009]
in 1.12 when I map a list of an inventory and take out items via any non player interaction the mapped list does still show that item.

**Comment by rubensworks** [comment]
@quarz12 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by rubensworks** [comment]
Closing this, as 1.12 is not being maintained anymore.
