### ISSUE TITLE
crash server with Exception Java.lang.StackOverflow / less tps  if connected with biggest inventory or mekanism machines and connect/break many network

### ISSUE THREAD

**Issue by DevDyna** [CyclopsMC/IntegratedDynamics#1010]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If created a network with mekanism machines connected with energy exporter / storage drawer drawers with many upgrade (example infinity item upgrade) and item interface and other network with other things , if use on next cables / mono-directional connectors to connect this networks , get crash/ less tps to many items loaded

#### Steps to reproduce the problem:

[example with drawers to describe more simple but is equal with mekanism machines exception that on it is need change item interface with energy exporter and connect with source of energy]
1. place a "biggest inventory" (example drawers with many upgrade)    
2. create a network with item interface on it , a cable and a terminal
3. create many of them
4. start to connect all them
5. on next , all time that add new connection from networks

#### Expected behaviour:

less tps / at end crash
____

#### Versions:

- This mod: Integrated Dynamics 1.5.1 | Integrated Tunnels 1.6.17 | Integrated Terminals 1.1.3
- Minecraft: 1.16.5
- Forge: forge-36.0.45

Modpack where I have found this : Enigmatica 6 v0.4.3

#### Log file:

[I didn't have because it is on server but i have tested on local world and cause less tps = if used more item = crash ]

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by jinkhya** [comment]
Hello!
Server owner here :)
Here's the crash report : https://gist.github.com/jinkhya/6c08b3b2a73d496ddc7f72ef6d12400c

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/jinkhya/6c08b3b2a73d496ddc7f72ef6d12400c">crash-report</a></strong></div><div>crash-report. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
