### ISSUE TITLE
Slightly faulty integration with JEI

### ISSUE THREAD

**Issue by alpharou** [CyclopsMC/IntegratedDynamics#1011]
#### Issue type:

- :bug: BUG

____

#### Short description:

When trying to program a recipe from JEI, the default 'r' (JEI recipe) and 'u' (JEI uses) keys (and all alphabet plus space) are captured by the logic programmer interface (even when the search box is not highlighted) and don't get to JEI. Thus the only option is to use left and right mouse clicks to get to the recipe UI. Once accessed JEI recipe UI, keybinds work normally.

#### Steps to reproduce the problem:

- Open the interface of the logic programmer / portable LP.

- Select the Recipe template

- Search for an item/block in JEI

- Try to use the very well known 'r' key to get the recipe

- BUG. (Suffer when your expectations clash with reality and think "I don't have to do it by hand... right?")

- (Optional) Use left and right click to get the recipe if JEI is not set to cheat mode, in which case it'll give you the item directly.

#### Expected behaviour:

JEI keybinds should just work.

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.6.1
- Minecraft: 1.16.5
- Forge: 36.1.0 (recommended)

- CommonCapabilities-1.16.5-2.5.7
- CyclopsCore-1.16.5-1.11.4

- jei-1.16.5-7.6.1.75

#### Log file:

None.

**Comment by rubensworks** [comment]
Thanks for reporting!
