### ISSUE TITLE
Integrated Dynamics mechanisms in loaded chunks prevent stopping server

### ISSUE THREAD

**Issue by Tander** [CyclopsMC/IntegratedDynamics#1013]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Integrated Dynamics elements (tested with redstone writer and item exporter) in loaded chunks (for example, in spawn chunks) makes dedicated server not shutting down properly (freezes right before it should terminate main process).

It happens on Windows and Linux instances of dedicated server.

#### Steps to reproduce the problem:

1. Start dedicated server
2. Build something like this in spawn chunks (which are always loaded)
![изображение](https://user-images.githubusercontent.com/1059805/113005837-7c764f80-917d-11eb-9c91-7f471acc4dc9.png)

3. Log out
4. Type `stop` in server console
5. See how server is shutting down, but never actually terminate the process

#### Expected behaviour:

Server should shut down correctly

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.6.1
- Minecraft: 1.16.5
- Forge: 36.1.2

Full modlist:
CommonCapabilities-1.16.5-2.5.7
CyclopsCore-1.16.5-1.11.4
IntegratedDynamics-1.16.5-1.6.1
IntegratedTunnels-1.16.5-1.7.0
jei-1.16.5-7.6.1.75

#### Log file:

```
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Stopping the server
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
  <and server freezes here, requiring Ctrl+C to kill process>
```

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce myself unfortunately...

Could you create a world where the problem occurs without any other mods installed, and share it with me here?

**Comment by Tander** [comment]
That's strange, after last update of Integrated mods can't reproduce it on local machine, but on linux server it still persists. May it be because of using Java 1.8.0_181 on server, but 1.8.0_261 on local windows machine?.. I'll let you know if I find a way to reproduce this problem.

**Comment by Tander** [comment]
Aha! Got it! It's an issue with Integrated Tunnels, specifically with Item Interface (like on screenshot). But the issue doesn't disappear right after you break Item Interface, that's why I was mislead with Redstone Writer causing this issue too (in fact it's not).

Anyway, i packed whole server in zip. Use RUN.bat (or run server.jar), wait for loading, then type `stop` and see how it freezes after saving world.

https://drive.google.com/file/d/1-ck_H0zRJ83-zUp35ecKVd6HpQL7aJBm/view?usp=sharing
(let me know if link not working for you, I can just email you or something like that)


<blockquote><img src="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1-ck_H0zRJ83-zUp35ecKVd6HpQL7aJBm/view?usp=sharing&usp=embed_facebook">integrated_issue_server.zip</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Thanks! Will check soon.
