### ISSUE TITLE
[1.16.5] Crash from beehives

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#1014]
#### Issue type:

- :bug: Bug 

____

#### Short description:

 > A crash when Integrated Dynamics display panel is displaying the NBT data of a beehive while a bee inside deposits honeycomb.
> No issue reading bees or comb already inside, only crashes when comb is deposited.

#### Steps to reproduce the problem:

I think the description explains it well enough, let me know otherwise :)

#### Expected behaviour:

To see the NBT of the Beehive (and not crash)

____

#### Versions:

- This mod: 
- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.0
- IntegratedDynamics-1.16.5-1.6.1

#### Log file:

[Crash report](https://gist.github.com/NillerMedDild/b36396e05dfb079ded8348d3bfa5adc3)
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6241204/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
