### ISSUE TITLE
Server can't fully stop after placing battery

### ISSUE THREAD

**Issue by XenonDB** [CyclopsMC/IntegratedDynamics#1015]
#### Issue type:

- :bug: Bug

____

#### Short description:

This bug is found when I playing Direwolf20 1.16 pack with friends. [Here is the issue posted at there](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/247).

After lots of testing, I found a strange thread still alive after stopping the server.
This thread comes from IntegratedDynamics.
![1](https://user-images.githubusercontent.com/58476103/113588047-3bd97300-9662-11eb-811e-b2bdf3cd7792.png)

Then I found this thread is created by Energy Battery in my base after lots of chunk deleting testing.

#### Steps to reproduce the problem:

1. Start a server only have IntegratedDynamics and its library installed.
2. Join the server and take an Energy battery from creative tab.
3. Put the battery in the world and stop the server.
4. JVM can't fully shutdown even though server thread has died.

#### Expected behaviour:

Server and JVM should be fully shutdown.

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.5.1
- Minecraft: 1.16.5
- Forge: 1.16.5_36.0.45

____

#### Additional information:

This bug can be prevented by setting "ingredientNetworkObserverEnableMultithreading" to false in integrateddynamics-common.toml or launching server by OpenJ9.

Moreover, I think the actual reason is "Executors.newFixedThreadPool"
The document indicates "The threads in the pool will exist until it is explicitly shutdown"
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool-int-

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest version, this has been fixed already.
