### ISSUE TITLE
Can't insert logs into squeezer when item in offhand

### ISSUE THREAD

**Issue by RGFTheCoder** [CyclopsMC/IntegratedDynamics#1016]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Having an item in the offhand doesn't allow the player to put a log in the squeezer (observed on Steak) 

#### Steps to reproduce the problem:

1. Put steak in offhand, Logs in mainhand, and place a squeezer.
2. try to place the log in the squeezer (survival mode w/ hunger bar full)

#### Expected behaviour:

The log should go in, since hunger is full and offhand can't be used.

#### Versions:

- This mod: 1.7.1
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by RGFTheCoder** [comment]
I'll do some more testing, as it seems to only happen some times.

**Comment by RGFTheCoder** [comment]
this might've actually been due to the mod https://www.curseforge.com/minecraft/mc-mods/dank-storage when a dank is in the inventory

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/dank-storage">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Can you reproduce this without any other mods installed?
If not, please report this to the offending mod's issue tracker.

**Comment by Xetaxheb** [comment]
Can confirm having a dank in the inventory at all prevents putting a log in (works fine with full hunger and food in offhand otherwise)

**Comment by rubensworks** [comment]
@Xetaxheb Could you open an issue on their issue tracker? Seems like a problem on their end.
