### ISSUE TITLE
Keep getting manual

### ISSUE THREAD

**Issue by Artin-13** [CyclopsMC/IntegratedDynamics#1017]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Everytime i join my server that irritating book (On the dynamics of integration) just keeps flying to me even though i already have one. everybody in my server has the same problem

#### Steps to reproduce the problem:

1. make a server
2. join it
3. get the book once
4. repeat step 3 every time you join

#### Expected behaviour:

not getting the book a million times
____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.4.3
- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.16

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That irritating book should only spawn once per player.
Can you try reproducing without any other mods installed? Because if it's spawning multiple times, then some other mod must be messing with player NBT data.

**Comment by Artin-13** [comment]
> That irritating book should only spawn once per player.
> Can you try reproducing without any other mods installed? Because if it's spawning multiple times, then some other mod must be messing with player NBT data.

where is the nbt data stored? i cant find anything in the playerdata folder/files. maybe i can fix it manually

**Comment by rubensworks** [comment]
It's saved here: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.16/src/main/java/org/cyclops/integrateddynamics/item/ItemOnTheDynamicsOfIntegration.java#L52-L55

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics">CyclopsMC/IntegratedDynamics</a></strong></div><div>A Minecraft mod to take full and automated control of your appliances. - CyclopsMC/IntegratedDynamics</div></blockquote>
