### ISSUE TITLE
World Block Importer is not working if used in claimed chunks (FTB Chunks)

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1019]
#### Issue type:

- :bug: Bug 

____

#### Short description:

World Block Importer doesn't work in claimed chunks (ftb chunks), even if chunk was claimed by player that placed said importer.

#### Steps to reproduce the problem:

![obraz](https://user-images.githubusercontent.com/6943031/114179313-19d04100-993f-11eb-9309-d84a7c767a09.png)
1. build setup like above (remember to fill chest on the right with blocks)
2. Use FTB Chunks to claim chunk in which this machine stands.
3. If chunk is not claimed importer works properly, when claimed it stops working.

#### Expected behaviour:

World Block Importer works correctly with FTB Chunks. In this case it mines block if it was placed by same player that claimed chunk. It would be good if it also complied with FTB Teams too, but that can wait.

____

#### Versions:

- This mod: 
![obraz](https://user-images.githubusercontent.com/6943031/114180062-05d90f00-9940-11eb-86cb-3b19b8092381.png)

- Minecraft: 1.16.5
- Forge: 36.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Hiranus** [comment]
I'm blind, someone else helped me fix it. For all interested - look into allies in FTB Chunks.
