### ISSUE TITLE
Cant create working rotate_3_1_2 operator

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1020]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I am trying to create rotate_3_1_2 operator and I am able to do it and I can even materialize it, but when i want to use it it errors.
You can test it on operator List Get Or Default

#### Steps to reproduce the problem:

![obraz](https://user-images.githubusercontent.com/6943031/114271005-9cc0cc80-9a0f-11eb-9e34-f4d63e0c5a4d.png)

And then try to use it.
#### Expected behaviour:

Input parameters are rotated. 

____

#### Versions:

- This mod: 
![obraz](https://user-images.githubusercontent.com/6943031/114271029-bd892200-9a0f-11eb-930c-6a21f5921631.png)

- Minecraft: 1.16.5
- Forge: 36.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> but when i want to use it it errors.

What's the error?

> You can test it on operator List Get Or Default

Could you share how you use it exactly? (a world share might also be good to have)

**Comment by Hiranus** [comment]
![obraz](https://user-images.githubusercontent.com/6943031/114282444-618cc080-9a44-11eb-965a-00f801df55c2.png)
![obraz](https://user-images.githubusercontent.com/6943031/114282459-6fdadc80-9a44-11eb-8b4b-91c2d0a988e1.png)

This is what happened on my server (different set of mods) and on singleplayer world (mods as in bug report). I was recommended to use it to merge 2 cards -
Entity +NBT => Bool that returns true if librarian enchanted book matches NBT 
Entity -> Bool that returns true if librarian has paper trade

Full tutorial how to merge those was written by @met4000 on InDy discord [Link](https://discord.com/channels/386052815128100865/386054223688630272/830244220533997578)
![obraz](https://user-images.githubusercontent.com/6943031/114282898-0ad4b600-9a47-11eb-88a8-41bda26de188.png)
I would have to create whole setup from scratch and add Quark to the mix (so piston would work on lecterns) but if its needed then I can do it.

**Comment by Hiranus** [comment]
It turned out that this recipe works in haskell to create rotate_3_1_2 but in InDy recipe for it is a bit different. It was heavily tested by one of the users on discord and this modified recipe is working, so this issue can be closed.

**Comment by rubensworks** [comment]
Thanks, I suspected this as well :-)

**Comment by Hiranus** [comment]
@rubensworks I obtained another interesting information - This rotate_3_1_2 operator worked for 1.12.2. I'm not sure if this is bug or just change in logic.

**Comment by rubensworks** [comment]
Might have been a bug in 1.12, not sure.
