### ISSUE TITLE
Using "name" function on delayer list items causes crash on world reload (UPDATE: happens on any list of type "Any")

### ISSUE THREAD

**Issue by MCC900** [CyclopsMC/IntegratedDynamics#1022]
UPDATE: Just tested something else, and you can get an immediate crash without reloading the world just by trying to cast any "Any" value to string using the "name" function. For example:

1: Create a list of type "Any"
2: Fill it with something 
3: Get a value from it using "get" function
4: Cast it to string using "name" function
5: Placing this string on a display panel causes an immediate crash.

ORIGINAL POST:
I just found out if you use the "get" function to get any value from a list created by a delayer, and then try to convert it to string using "name", put that string on a displayer, then save and reload the world, it will cause a crash. Tested on a standalone installation with just the base Integrated Dynamics mod.

Steps to reproduce:

1. Create a network with a delayer, a variable store and a display panel.
2. Use any variable of Named category (integer, block, etc). in delayer to create a historical list. Doesn't matter what, can be just a constant value.
3. Use "get" function to get any value from that list.
4. Use "name" function to convert that variable to a string.
5. Put that string on the display panel.
6. Close the world.
7. Reload the world. A crash should occur.

I actually originally got this on the Sky Factory 4 modpack but after isolating the mod and even with the latest version the problem persists. I was trying to make a cobblestone per tick counter using the delayer... guess I will have to get creative to get around the bug for now ;)

[crash-2021-04-12_01.35.28-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6293958/crash-2021-04-12_01.35.28-server.txt)

Update

**Comment by rubensworks** [comment]
@MCC900 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
