### ISSUE TITLE
Correct FE display

### ISSUE THREAD

**Issue by Seceroth** [CyclopsMC/IntegratedDynamics#1023]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Currently, using version 1.16.5-1.6.1 (modpack Enigmatica 6 v0.4.8), the maximum counted FE stored in the network does not exceed the 32 bit max int, however the maximum total possible FE stored does. Would like it to be able to correctly display how much is stored instead. Using only the ID Energy batteries to store my power at the moment.

Screenshot showing a network reader's output of current energy and a terminal showing the max int:
![2021-04-17_10 37 28](https://user-images.githubusercontent.com/20866237/115107906-14857e80-9f5d-11eb-8921-740e302c0b6e.png)

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Note to self: change `IngredientComponent<Integer, Boolean>` to `IngredientComponent<Long, Boolean>`
