### ISSUE TITLE
Recipes not loading in ftb revelation mp world.

### ISSUE THREAD

**Issue by bobolicious1995** [CyclopsMC/IntegratedDynamics#1024]
Hi,

we added the mod on our mp server that was already running 1.5 weeks of ftb revelation but the recipes of the mod are not shown in JEI. We also added  Cyclops Core and Common Capabilities. 

The only items of ID in the JEI are the buckets with fluid (menril resin bucket & liquid chorus bucket). When i load a sp world all the recipes are shown in the JEI. 

Is there an option we need to change ? 
We did this before and didn't had any problems with it.
MC Version 1.12.2

**Comment by rubensworks** [comment]
Likely another mod in your pack that is breaking things.

I can't give any further support to this otherwise, as MC 1.12 is not supported anymore unfortunately (we're focusing on 1.16 now).
