### ISSUE TITLE
Materialized Item or [Item] cards do not contain the size information

### ISSUE THREAD

**Issue by druidbruce** [CyclopsMC/IntegratedDynamics#1025]
#### Issue type:

- :bug: Bug 

____

#### Short description:

put any `Item` card into the materializer and the `size` information from output card of the materializer is always reset to `1`

#### Steps to reproduce the problem:

- example1
1. put something inside slot 0 of a chest
2. put an inventory over the chest
3. get the slot item aspect card from the reader
4. put the aspect card into a display panel, now the card should show correctly how much the size is
5. to furthur confirm the size, pass the card into operator `size :: Item -> Int`
```haskell
chest_card :: card from the slot item aspect
size_card = apply size chest_card :: Int 
```
6. now `size_card ` should correclty show the `size` information of the `Item` card (`chest_card`)
7. put `chest_card` into a materialiizer input
8. get the output of the materialiizer
```haskell
materialized_card :: card of materializer output
msize_card = apply size materialized_card :: Int
```
9. now put `msize_card` into a display panel, it shows 1 regardless of what `size_card` shows (what the original `Item` card should have)

- example2
1. replace step 1-3 from example1 with an operator that generates item with size
```haskell
Opsize :: Item -> Int -> Item(with size)
item_card :: Item
int_card :: Int
newItem_card = apply2 Opsize item_card int_card :: Item
```
2. simply replace `chest_card` with `newItem_card`, the results will be the same

- example3
do the exact same thing as example 1 or 2, but instead of `Item` use `[Item]`, which turns out in the end the same result as the `Item` looses its `size` info

#### Expected behaviour:
at step 9, `msize_card == size_card` should be `True` (materialized card should keep their `size` information) as tested this works in 1.12, therefore we considered it to be not intentional and is a bug

however, I can confirm that when materializing `Recipe` cards, the `size` does not get reset to 1, as you can do so by checking
```haskell
Recipe_input_ingredients :: Recipe -> Ingredient
Ingredient_items :: Ingredient -> [Item]
size :: Item -> Int
map :: (a -> b) -> [a] -> [b]
size_L = map size :: [Item] -> [Int]
R_iL = pipe Recipe_input_ingredients Ingredient_items  :: Recipe -> [Item]
R_isL = pipe RiL size_L :: Recipe -> [Int]
```
we can find that even a materialized `Recipe` when applied to `R_isL` outputs a correct `[Int]`
____

#### Versions:
- This mod: 
IntegratedDynamics-1.16.5-1.7.2
IntegratedTerminals-1.16.5-1.1.3
IntegratedCrafting-1.16.5-1.0.13
IntegratedTunnels-1.16.5-1.7.0
CyclopsCore-1.16.5-1.11.4
CommonCapabilities-1.16.5-2.5.6

- Minecraft: 
  1.16.5

- Forge: 
  36.1.2

#### Log file:
not required

**Comment by rubensworks** [comment]
Thanks for reporting!
