### ISSUE TITLE
Can't click a Menril log into the Squeezer

### ISSUE THREAD

**Issue by AntonLM** [CyclopsMC/IntegratedDynamics#1026]
I can't get a Menril log into the Squeezer (nanual version) by cR-licking the Squeezer with a Log in my hand. As far as I recall, that's the way I always did it, but now just nothing happens. I've tried other squeezable items (Cactus, Sandstone) but the Squeezer accepts nothing.

Am I doing something wrong?

**Comment by rubensworks** [comment]
@AntonLM Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by AntonLM** [comment]
> @AntonLM Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

Sorry - but I have no idea how I should have submitted the issue differently.

I had another look at the template and I can't see anything that I missed. Please help me.

**Comment by AntonLM** [comment]
Hi Ruben

I did have a good hard look at the template I used (general issues) but I
could not how I should have filled it in any differently.

I'd be really grateful for guidance, please.

Regards

Anton

**Comment by rubensworks** [comment]
"New issue" > "Bug report" > fill in the required fields.
