### ISSUE TITLE
Crash 1.16.5

### ISSUE THREAD

**Issue by Wlnfr** [CyclopsMC/IntegratedDynamics#1028]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft crashes when trying to re-enter the world after leaving it while in nether when a working transfer system is chunkloaded with Integrated Tunnels(a simple chest to chest transfer, battery to battery transfer, tank to tank transfer). After relaunching minecraft, the transfer systems stop working until interfaces/exporters/importers are broken and replaced

#### Steps to reproduce the problem:

1. Create the world
2. Make a working transfer system with any types of interfaces, exporters and importers(item, fluid, energy)
3. Chunkload them
4. Go to nether
5. Quit the world
6. Enter the world again
7. Crash while loading

#### Expected behaviour:
Minecraft doesn't crash, transfer systems continue working

____

#### Versions:

- Minecraft: 1.16.5
- Forge: 36.1.6
- architectury-1.12.145-forge
- CommonCapabilities-1.16.5-2.6.0
- CyclopsCore-1.16.5-1.11.5
- ftb-chunks-1605.2.3-build.75
- ftb-gui-library-1605.2.1.41-forge
- IntegratedDynamics-1.16.5-1.7.2
- IntegratedTunnels-1.16.5-1.7.1

#### Log file:
Crash-report: https://pastebin.com/ujuKxTWA
Log(can't upload to pastebin, exceeded 512kb limit according to it):  [latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/6366168/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I have a fix for this in dev already: b12ebba2cde09fc2d9ad3e4a7ad09271e3d48db4
This will be released soon.
