### ISSUE TITLE
Server Crash: Squeezer

### ISSUE THREAD

**Issue by Darkosto** [CyclopsMC/IntegratedDynamics#103]
Hello o/

When using the Squeezer on a server, we had this crash:

http://pastebin.com/BuEik0AV

Integrated Dynamics Version: 0.6.5
Cyclops Core: 0.8.2
Forge: 2202

Thanks for taking a look at this :)

Darkosto

**Comment by rubensworks** [comment]
Looks like the same problem as #100, which I just fixed yesterday in CyclopsCore :-)

I'll try to release a new version containing this fix soon, either today or tomorrow.
