### ISSUE TITLE
Adding operator parameters to the list resulted in a game crash.

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedDynamics#1031]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:
Add operator parameters to the list

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.7.2
- Minecraft: 1.16.5
- Forge: 36.1.0

#### Log file:
[crash-2021-04-26_18.11.11-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6376214/crash-2021-04-26_18.11.11-client.txt)
https://pastebin.com/xRGmv9NE

**Comment by rubensworks** [comment]
Thanks for reporting!
