### ISSUE TITLE
The channel of omni directional connector can be modified with wrench

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedDynamics#1033]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

The channel of omni directional connector can be modified with wrench
I want to get many omni directional connectors of the same channel, but I always need to prepare an omni directional connector in my backpack to synthesize.
I want to configure omni directional connector by opening an integer input GUI with a wrench.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Something like this may lead to security issues, where one could easily connect to someone else's network. So therefore, I prefer to not support this.

**Comment by GaN8373** [comment]
> Something like this may lead to security issues, where one could easily connect to someone else's network. So therefore, I prefer to not support this.

I hardly ever played on the server. Wouldn't it be the same if I took someone else's Omni-Directional Connector apart to synthesize it?

**Comment by rubensworks** [comment]
> I hardly ever played on the server. 

This mod aims to serve a public as wide as possible, including people that play on servers.
If you have specific needs, you're welcome to submit a PR with other specific features (disabled by default), or create an addon mod.

> Wouldn't it be the same if I took someone else's Omni-Directional Connector apart to synthesize it?

Wouldn't be possible if that chunk is protected.

**Comment by GaN8373** [comment]
> > I hardly ever played on the server.
> 
> This mod aims to serve a public as wide as possible, including people that play on servers.
> If you have specific needs, you're welcome to submit a PR with other specific features (disabled by default), or create an addon mod.
> 
> > Wouldn't it be the same if I took someone else's Omni-Directional Connector apart to synthesize it?
> 
> Wouldn't be possible if that chunk is protected.

Okay, thank you for your reply
