### ISSUE TITLE
Network reader crashes server when reading a corrupted network

### ISSUE THREAD

**Issue by druidbruce** [CyclopsMC/IntegratedDynamics#1034]
#### Issue type:

- :bug: Bug 

____

#### Short description:
when a network becomes corrupted by going in and out of safemode, the reader crashes the server if its reading the corrupted network

#### Steps to reproduce the problem:

1. put a reader against a network to read it, can be the reader's own network
2. (might be optional) expose the recipe/active crafting jobs aspect of the reader onto a card, and display this card
3. (might be optional) pass this card into an operator that does some calculation and put it in a display panel or a tunnel component
4. an example i did in my world: 
```haskell
recipe_in :: Recipe -> Ingredients
Ingr.items :: Ingredients -> [Item]
get_or :: [a] -> Int -> a -> a
item_empty :: Item (an empty item card)
applyTo_2 = pipe flip apply
pipe^2 = expOpRes_2 (pipe_2 pipe pipe)
expOpRes_2 = flipPipe apply2
pipe_2(0) = flip (pipe flipPipe flipPipe)
pipe_2 = expOpRes (pipe_2(0) pipe_2(0) expOpRes)
flipPipe = flip pipe

get_orEmptyi = applyTo_2 get_or item_empty :: [Item] -> Int -> Item
Recipe_Item = pipe^2 recipe_in ingr.items get_orEmptyi :: Recipe -> Int -> Item
```
now make 25 `Int` cards `Int_n :: Int (n = 0 -24)` starting from 0 to 24, and do
```haskell
active_job_list :: [Recipe]
recipe_empty :: Recipe (empty recipe)
firstRecipe = get_or active_job_list 0 recipe_empty 
nItem = apply2 Recipe_Item firstRecipe Int_n :: Item
```
now put `nItem (n = 0 -24)` into 25 different exporters
5. restart the server in safe mode
6. restart the server in normal mode, now all networks should be in the state "corrupted network" (not sure if this is intended as it is extremely tedious to update all your networks everytime after going back from safe mode)
7. updating any corrupted network should make the network work again, so we update the network that has the network reader before we update the network the reader is reading
8. crash 

#### Expected behaviour:

server shouldn't crash in step8
____

#### Versions:

- This mod: 
IntegratedDynamics-1.16.5-1.7.2
IntegratedTerminals-1.16.5-1.1.3
IntegratedCrafting-1.16.5-1.0.13
IntegratedTunnels-1.16.5-1.7.0
CyclopsCore-1.16.5-1.11.4
CommonCapabilities-1.16.5-2.5.6
- Minecraft: 
1.16.5
- Forge: 
36.1.2

#### Log file:
https://pastebin.com/qXJ5eqAz
https://pastebin.com/EDPZnBgY

**Comment by rubensworks** [comment]
Thanks for reporting!
