### ISSUE TITLE
Network Reader aspects return error

### ISSUE THREAD

**Issue by druidbruce** [CyclopsMC/IntegratedDynamics#1035]
#### Issue type:

- :bug: Bug 

____

#### Short description:

as title says, 
![image](https://user-images.githubusercontent.com/61846869/116288515-35b54e80-a757-11eb-8fdc-08de7db18a55.png)
when put in display panel, it says 
![image](https://user-images.githubusercontent.com/61846869/116288640-554c7700-a757-11eb-9191-324c09c81909.png)
several aspects that is related to crafting/network item count.. etc are all giving the same error
#### Steps to reproduce the problem:

1. put down a Logic cable
2. connect a network reader onto the cable
3. put a card into any error aspects
4. you cannot use that card

#### Expected behaviour:

the aspects should be usable
____

#### Versions:

- This mod: 
IntegratedDynamics-1.16.5-1.7.2
IntegratedTerminals-1.16.5-1.2.2
IntegratedCrafting-1.16.5-1.0.13
IntegratedTunnels-1.16.5-1.7.1
CyclopsCore-1.16.5-1.11.5
CommonCapabilities-1.16.5-2.6.0
- Minecraft: 
1.16.5
- Forge: 
36.1.2

#### Log file:
not a crash

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does this always occur? Could you confirm with a new world without any other mods?

**Comment by druidbruce** [comment]
> Does this always occur? Could you confirm with a new world without any other mods?

yes, this happens when in a fresh instance with only the mods mentioned installed, with the same behavior

**Comment by druidbruce** [comment]
something interesting just happened, seems to be related to #1034 by comparing the lines in the crash report (even though the versions are different)
here is the report
[crash-2021-04-27_13.26.59-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6386781/crash-2021-04-27_13.26.59-server.txt)
steps to reproduce
1. setup a network that has cable/variable store/display panel/crafting interface/network reader
2. (optional maybe) make a chest recipe and put it in the crafting interface accessing a vanilla crafting table.
this should be optional as the network reader isn't even reading the network of the crafting interface
3. (optional maybe) 
```haskell
RecipeList_error :: [Recipe]  --(the card that is exposing the Recipe aspect of the network reader, which is error)
display_card = get RecipeList_error 0 :: Recipe
```
put display_card into display panel
4. go into the recipe aspect of the reader and change channel to 1
5. crash
6. new way to crash: load back up the world, place a cable onto the network 
7. crash
report: of step 6/7
[crash-2021-04-27_13.34.08-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6386829/crash-2021-04-27_13.34.08-server.txt)

**Comment by druidbruce** [comment]
some new observations: (done in modpack stacia expert 1.10.2)
sometimes when i relaunch the game, and place down a new network reader and read the network, it doesn't give out the error on these aspects. I can even display the Recipe aspect in a display panel without crashing
However, if I break a part of the network as the Recipe card from the network reader aspect stays inside the display panel, game crashes. Below is the report.
[crash-2021-04-27_21.11.18-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6388687/crash-2021-04-27_21.11.18-server.txt)
Even though its on a different pack with a lot more mods in it, I think the problem is similar.
My assumption is:
updating the network in some way with the error aspects being exposed will cause the game to crash.
which again, seems pretty similar to #1034.
