### ISSUE TITLE
Transfer Rate of -2147483648 in Importers and Exporters

### ISSUE THREAD

**Issue by AHL67** [CyclopsMC/IntegratedDynamics#1037]
Hi, I put a value of **-2147483648** as the _Item Transfer Rate_ of an _Item Importer_ alone on a _Logic Cable_, and the value was kept even hough it is invalid. I tried with other negative values but none was kept, only -2147483648.
Then I put an _Item Interface_ on the _Logic Cable_ and instantly crashed.
I included the crash report but I'm not sure it will be relevant since I was able to reproduce the previous steps without any crash.
Anyway, it is possible with every Transfer Rates of every Item, Fluid and Energy Importers and Exporters.

_Integrated Dynamics_ was in version **1.7.2** in the modpack _Stacia Expert_ 1.10.5 for _Minecraft_ **1.16.5**.

[crash-2021-05-04_18.49.42-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6422756/crash-2021-05-04_18.49.42-server.txt)

**Comment by rubensworks** [comment]
Please update to the latest ID version, this issue has been fixed already.
