### ISSUE TITLE
Solid Facades

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedDynamics#1039]
#### Issue type: 

- :heavy_plus_sign: Feature request 

____

#### Short description:
Facades to be solid so entities do not fall through. Example being Botania petal automation, when the flowers are broken, their random drop sometimes has them land inside the block space around where it was planted, requiring additional world item importers to cover these locations, even when Facades visually fill the space around the exporters / importers

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This was actually a bug that has been recently fixed in dev (f303199388c4c9e9d878b142954b9d548c8231d7).
Will be part of the next release :-)
