### ISSUE TITLE
game crashing in ATM6 when trying to use world block exporter

### ISSUE THREAD

**Issue by kuraishi420** [CyclopsMC/IntegratedDynamics#1040]
#### Issue type:

- :bug: Bug 

____

#### Short description:

game crashing when putting a card in a world exporter connected to a drawer then when removing interface/cables in the network 

#### Steps to reproduce the problem: , then put a blak card in the exporter

1. place a world block exporter towards air
2. connect the world exporter to a drawer with acacia logs in it (did not test with other blocks) (or drawer controller) using an item interface and cables
3. put a blank card in the world exporter

#### Expected behaviour:
the game crashes

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.8.0, IntegratedTerminals-1.16.5-1.2.3, IntegratedTunnels-1.16.5-1.8.0 
- Other mods: StorageDrawers-1.16.3-8.2.2
- modpack: All the Mods 6-1.6.3
- Minecraft: 1.16.5
- Forge: curseforge launcher 0.173.1.4

#### Log file:

https://pastebin.com/mVAAgvJ7
https://pastebin.com/pmC1xLWs
https://pastebin.com/x38VTuX7v
https://pastebin.com/B4x3Zg2Q
https://pastebin.com/xhWvN3Et
https://pastebin.com/aw6G6Q7q

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This has been fixed in dev already (https://github.com/CyclopsMC/IntegratedTunnels/commit/d4de7c1c63a3a29a41052345e245c71ea0860c5d).
A new release will be out soon! 🙂
