### ISSUE TITLE
CTD When Placing/Breaking Components of an Integrated Network

### ISSUE THREAD

**Issue by GMGKenny** [CyclopsMC/IntegratedDynamics#1041]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Playing on the All the Mods 6 pack.
Whenever I try to add or remove anything from my network my game crashes entirely. It is a player simulator attempting to right click on a magmatic dynamo from Thermal Series. Anytime I try to remove or add an item from and Integrated series mod, the whole game crashes. 

#### Steps to reproduce the problem:

1. Place player simulator against magmatic dynamo.
2. Set it to right click with bucket of lava
3. Place chest
4. Connect chest to player simulator with integrated dynamics cables and an importer
5. Game will CTD when the connection is made
6. End.

#### Expected behaviour:

I was expecting the cables to link together without any crashes. Not sure what else to say haha :)

____

#### Versions:

- This mod: Integrated Dynamics 1.8.0/1.8.1 \\ Integrated Tunnels 1.8.0
- Minecraft: 1.16.5
- Forge: 36.1.16

#### Log file:

https://pastebin.com/sUFhFvQN

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Oops, forgot to release the new version in which this has been fixed. Done just now :-)

**Comment by GMGKenny** [comment]
No worries! We all make mistakes sometimes! Thanks for resolving this so quickly! Love your mods and keep up the fantastic work!
