### ISSUE TITLE
If the proxy puts the variable card through the pipeline, it will prompt that it cannot be found

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedDynamics#1042]
#### Issue type:

- :question: Question 

____

#### Question:

versions：
    IntegratedDynamics-1.16.5-1.8.0
    IntegratedTunnels-1.16.5-1.8.0
![image](https://user-images.githubusercontent.com/80253667/118299467-5f21f880-b513-11eb-9f81-0a935dd3b72a.png)
I set up a program to detect the battery capacity. When the battery is fully charged, the variable card in the agent will be automatically removed. When the threshold value is reached, a blank variable card is put in.
But when I put the variable card into the pipeline automatically, sometimes mod will prompt that the variable card cannot be found

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
I guess this is because there may be moments when your proxy does not contain a variable card, and the variable therefore errors.

**Comment by GaN8373** [comment]
> I guess this is because there may be moments when your proxy does not contain a variable card, and the variable therefore errors.

Occasionally, the network component using the proxy variable card can't find that variable card, so I improved the processing method. The variable card is no longer replaced to complete the data change.
If you don't think it's a problem, close it.
