### ISSUE TITLE
Integrated Dynamics CTD on connecting importer to cyclic auto clicker (1.6.5)

### ISSUE THREAD

**Issue by GMGKenny** [CyclopsMC/IntegratedDynamics#1043]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I attempt to place an item importer attached to an auto clicker from Cyclic, the game crashes completely. 

#### Steps to reproduce the problem:

1. Place auto clicker from Cyclic
2. Try to attach item importer to auto clicker without cable first (Important note: Only seems to crash if I place the importer without a cable)
3. game crashes to desktop
4. end

#### Expected behaviour:

Was expecting it to connect :P

____

#### Versions:

- This mod: 1.8.1
- Minecraft: 1.6.5
- Forge: 36.1.16

#### Log file:

https://pastebin.com/wpYNbq36

**Comment by rubensworks** [comment]
Thanks for reporting!
