### ISSUE TITLE
with_fluid operator does not return fluid

### ISSUE THREAD

**Issue by sbenedict** [CyclopsMC/IntegratedDynamics#1044]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The with_fluid operator returns a boolean instead of fluid when used as an input to an operator. Displaying the variable works as expected.

#### Steps to reproduce the problem:

1. Create a variable card `A` for operation `with_amount` passing any fluid and integer.
2. Create a variable card `B` for operation `amount` passing variable `A`.
3. Error shown stating input type is Boolean instead of Fluid.

#### Expected behaviour:

1. Variable card `B` is able to be created and contains the amount of fluid specified in `A`

____

#### Versions:

- This mod: 1.8.0
- Minecraft: 1.16.5
- Forge: 36.1.13

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
