### ISSUE TITLE
Use player simulator to crash the game

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedDynamics#1045]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. set Player Simulator
2. The variable card is set to the specified item mode
3. The item specified in the variable card is tconstruct:cleaver（https://www.curseforge.com/minecraft/mc-mods/tinkers-construct）
4. Player simulator channel set to 999
5. Channel 999 does not have an item interface
6. After putting the variable card into the player simulator, the game starts unresponsive and then crashes
7. After restarting the game, storage terminal / portable storage terminal cannot display items stored in the network. But the maximum capacity can be displayed

#### Expected behaviour:

____

#### Versions:

- This mod: 
    IntegratedDynamics-1.16.5-1.8.0
    IntegratedTerminals-1.16.5-1.2.3
    IntegratedTunnels-1.16.5-1.8.0
- Minecraft: 1.16.5
- Forge: 16.1.0

#### Log file:
[crash-2021-05-18_16.18.11-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6499623/crash-2021-05-18_16.18.11-server.txt)
[crash-2021-05-18_16.12.03-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6499624/crash-2021-05-18_16.12.03-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest Tunnels version.
