### ISSUE TITLE
'Player Simulator' can't use item right click.

### ISSUE THREAD

**Issue by hanxiaoxin778** [CyclopsMC/IntegratedDynamics#1046]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Sorry, my English is not good, I hope you can understand what I am expressing.
My hoe has enchantment 'Nature's Blending'. 'Player Simulator' can't use it against wheat.
'Nature's Blending' in 'Unique Enchantments' mod.
#### Steps to reproduce the problem:

1.The 'Player Simulator' doesn't respond when right clicking on the hoe.

![1](https://user-images.githubusercontent.com/56909786/119573152-764fc880-bde6-11eb-87a2-708daf56d0ae.png)
![2](https://user-images.githubusercontent.com/56909786/119573157-78198c00-bde6-11eb-80bb-727c0eefcfc7.png)

2.Left click can destroy wheat normally,But the right click has no response!

![3](https://user-images.githubusercontent.com/56909786/119573161-78b22280-bde6-11eb-92a7-d0f0b31bdd12.png)
![4](https://user-images.githubusercontent.com/56909786/119573514-f413d400-bde6-11eb-8cda-44659c9298f9.png)
![5](https://user-images.githubusercontent.com/56909786/119573731-405f1400-bde7-11eb-9f3f-bf6627072e7f.png)

3.The "item user" of cyclic mod works normally

#### Expected behaviour:

____

#### Versions:

- This mod: 1.8.2
- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.1.22

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by hanxiaoxin778** [comment]
Thank you very much,This is the best custom net mod I've ever played!
