### ISSUE TITLE
Fluid card also silently stores an integer value to check the level of the fluid

### ISSUE THREAD

**Issue by TacocaTYT** [CyclopsMC/IntegratedDynamics#1048]
#### Issue type:

- :bug: Bug 

____

#### Short description:
the fluid variable card not only checks the fluid type but also the value, despite the fact that measuring fluid levels should be left to an integer card and a totalfluidintank card combined into a boolean.

#### Steps to reproduce the problem:
Make a fluid card with a bucket of lava in the logic programmer and a tank fluid card in the tank reader. 
combine them in a == Boolean card. place the reader into a display.
 Place a bucket of lava into the tank, the variable is now true, place a second bucket to make the amount of lava go up to 2000mb, the variable now says false despite the fluid of lava being in the tank.

#### Expected behaviour:

No matter how much lava is in the tank, it should read as true. anything from 1mb to 64000mb of lava should still return as true.

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.1.6
- IntegratedTunnels-1.12.2-1.6.11
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2854
- whatever other mods are in SF4, although this almost 100% is not a sf4 issue but a variable issue

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This all sounds intentional. Fluid variables also store the fluid amount. There are other ways to compare just the fluid type itself.

**Comment by TacocaTYT** [comment]
how can i just compare the fluid type itself?

**Comment by suzuki-jessy** [comment]
Raw fluid equals -> If the raw fluids are equal
