### ISSUE TITLE
Redstone Writer multipart visual glitch

### ISSUE THREAD

**Issue by Runesmacher** [CyclopsMC/IntegratedDynamics#105]
When placing multiple redsone writers in one block space it creates a visual glitch due to them overlapping

![2017-01-06_18 45 10](https://cloud.githubusercontent.com/assets/979451/21727203/7e5cfe24-d440-11e6-9aaa-e8ddb5f042dc.png)

**Comment by rubensworks** [comment]
I'm aware of this, not sure how to solve this, or if I want to solve this.

The first solution would be to change the model, which I wouldn't do because I like it.

The other solution would be to not allow writers to be placed like that, which doesn't seem very user-friendly either...
