### ISSUE TITLE
Network Reader's "Value" doesn't update after erroring

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1050]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After a network reader's `value` aspect becomes `ERROR`-type it will not update the `value` when the target display changes.

#### Steps to reproduce the problem:

1. Place a cable and display, and set it to some constant value (e.g. `100`)
2. Place a cable and network reader facing into the display (note; you must click on the cable itself to be able to place the reader, and can't shift-rightclick on the display; might be a seperate bug?)
3. Optional: place a displayer on the network reader network, set to the network reader's `value` aspect (makes it easier to see what happens)
4. Remove the variable card from the display from step (1) - the network reader's `value` aspect changes to an `ERROR` value (as expected)
5. Place the variable card (from step (4)) back into the display from step (1) - the network reader's `value` aspect remains `ERROR`-type

Video: https://discord.com/channels/386052815128100865/386054223688630272/850195202026897468

Image of error (from placing `value` card into display panel and hovering over the cross):
![image](https://user-images.githubusercontent.com/15624876/120736489-ebc24400-c51e-11eb-8f30-9d138abb369c.png)

#### Expected behaviour:

After completing step (5) for the network reader's `value` aspect to stop being `ERROR`-type and change to the value of the card in the display panel. (This might require forcing an update in attached network readers when you put a card into a display panel, idk.)

____

#### Versions:

mod | version
--- | ---
MC | 1.16.4
InTu | 1.6.16
InTu Compat | 1.6.16
Cyclops Core | 1.11.1
Common Capabilities | 2.5.5
Forge | 35.1.4
InDy | 1.4.3
InDy Compat | 1.4.3
InNBT* | 1.4.1
InCr | 1.0.11
InTerm | 1.1.1
InTerm Compat | 1.1.1
InREST | 1.1.2

(* InNBT present but unused in this setup)

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> InDy | 1.4.3

You're running quite a lot of versions behind.

Could you try updating to the latest?
Something similar like this was fixed recently.

**Comment by met4000** [comment]
Looks like curseforge launcher is having some problems; it was insisting that those were the latest versions. I manually updated the versions to the latest (see below) and tested again, with "more correct" behaviour; the `value` aspect updates when replacing the card in the display, however the `value` variable card does not update unless the reader's network updates e.g. by placing and breaking a cable or removing and reinserting the card into the display. I assume this is the intended behaviour, as e.g. using `get` on a delayer and restarting the world has the same behaviour.

mod | version
--- | ---
MC | 1.16.4
InTu | 1.8.2
InTu Compat | 1.8.2
Cyclops Core | 1.11.7
Common Capabilities | 2.7.0
Forge | 35.1.4
InDy | 1.8.4
InDy Compat | 1.8.4
InNBT* | 1.4.2
InCr | 1.0.15
InTerm | 1.2.4
InTerm Compat | 1.2.4
InREST | 1.1.3

**Comment by rubensworks** [comment]
Not sure if you're saying the problem is resolved then?

> however the value variable card does not update unless the reader's network updates e.g. by placing and breaking a cable or removing and reinserting the card into the display.

Does this mean that e.g. reading a world time value doesn't continuously update?

**Comment by met4000** [comment]
> Not sure if you're saying the problem is resolved then?
> 
> > however the value variable card does not update unless the reader's network updates e.g. by placing and breaking a cable or removing and reinserting the card into the display.
> 
> Does this mean that e.g. reading a world time value doesn't continuously update?

https://user-images.githubusercontent.com/15624876/120788908-788ef100-c563-11eb-81b6-ba84f8443b77.mp4

This is the current behaviour. I think this is all intended behaviour, so yes; I'm pretty sure it's resolved now.
(Well, it wasn't a problem in this version anyways and was just user error with an outdated version, but you get the idea)

**Comment by rubensworks** [comment]
Indeed, this is the same behaviour as when you for instance get an out of bounds list element.

Thanks for checking!
