### ISSUE TITLE
Rotating display panels broken since >1.12

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1051]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Trying to rotate a display panel in any 1.15 or 1.16 version of the mod results in a wiggle of the display without rotation.

#### Steps to reproduce the problem:

1. Place a cable
2. Attach a display panel to any side
3. Insert a variable card that would display something (integer, text, etc)
4. Right-click the display with the wrench
   →:x: The text only tilts ever so slightly

#### Expected behaviour:

In the latest 1.12 version this used to work properly, it would rotate the display panel 90 degrees. If placed horizontally, it would attempt to face the player on first rotation.

____

#### Versions:

- This mod: 1.8.4
- Core: 1.11.7
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.1.24
- No other mods

ALSO, earliest version I found affected by this:
- This mod: 1.1.6
- Core: 1.7.0
- CC: 2.4.4
- Minecraft: 1.15.2
- Forge: 32.2.0
- No other mods

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Ah, I even forgot that used to be possible.
Probably just forgot to reimplement it in the (massive) 1.15 port.

**Comment by Jack-McKalling** [comment]
Yep, no problem. Actually I didn't mark the latest version as affected, which also does, updated the description.
