### ISSUE TITLE
Lever cannot be placed directly on a Redstone Reader anymore

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1052]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Back in 1.12 it used to be possible to attach a lever directly to a Redstone Reader. This is not possible anymore, it now requires a solid block in between.

#### Steps to reproduce the problem:

1. Place a logic cable on the ground
2. Attach a Redstone Reader on the side
3. Try to attach a lever to the Redstone Reader
    →:x: It will attach to the ground instead

#### Expected behaviour:

A lever should be able to connect to a reader directly, it used to, so a solid block is not needed. Having the block requirement makes the whole design of your setup unnecessarily bulkier.

____

#### Versions:

- This mod: 1.8.4
- CC: 2.7.0
- Core: 1.11.7
- Minecraft: 1.16.5
- Forge: 36.1.24
- No other mods

ALSO, earliest version I found affected by this:

- This mod: 1.1.6
- Core: 1.7.0
- CC: 2.4.4
- Minecraft: 1.15.2
- Forge: 32.2.0
- No other mods

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This seems to be not possible anymore due to how vanilla has implemented levers.
Let's revisit this in 1.17.

**Comment by rubensworks** [comment]
Restored in 94fc780873a6e476447b12af813f01d727132522

**Comment by Jack-McKalling** [comment]
This issue is happening again, in version `IntegratedDynamics-1.20.1-1.23.2`.

Levers cannot be placed on redstone readers, _unless_ they have a cable facade. However, when the cable facade is removed, the lever stays attached without problem (even placing blocks around it or flicking the lever will keep it attached). So I guess it is slightly different circumstances now.

**Comment by Jack-McKalling** [comment]
*Edit: split into new report: #1408
