### ISSUE TITLE
Changing redstone writer strong power option from true to false does not cause redstone update.

### ISSUE THREAD

**Issue by Icoza** [CyclopsMC/IntegratedDynamics#1053]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Attach a redstone writer to a block with redstone dust or components around said block.
2. Insert a variable to cause redstone output.
3. Enable strong power option then disable it.

#### Expected behaviour: Disabling strong power causes redstone that is powered by the strong powered block to stop being powered.

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

Mods Installed; Integrated Dynamics, Integrated Tunnels and required libraries.

#### Log file:

![2021-06-10_17 14 19](https://user-images.githubusercontent.com/997239/121604007-67385f80-ca0f-11eb-982c-535a967338c1.png)
After breaking redstone to cause update: ![2021-06-10_17 14 29](https://user-images.githubusercontent.com/997239/121604026-6e5f6d80-ca0f-11eb-94f7-6d071f156b64.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but 1.12 is not supported anymore. Can you also reproduce it in MC 1.16?

**Comment by Icoza** [comment]
It is reproducible in 1.16 with Forge 36.1.31 and Dynamics 1.8.4.

I'm not sure how big of an issue it is though. It might be possible to abuse this in some ways but I can't personally see how since moving or removing the redstone writer will trigger a block update. It doesn't break functionality as long as you provide a block update to it or remove and reinsert the variable into the redstone writer. I didn't know 1.12 was no longer being supported so I apologize about that. Thank you for all the time you put into your mods.

![2021-06-11_07 31 15](https://user-images.githubusercontent.com/997239/121686792-3eec4780-ca87-11eb-907a-bb8a3b4cf247.png)
![2021-06-11_07 31 57](https://user-images.githubusercontent.com/997239/121686789-3d228400-ca87-11eb-9fec-bd5a06786489.png)
![2021-06-11_07 35 02](https://user-images.githubusercontent.com/997239/121687102-8ffc3b80-ca87-11eb-9813-fb007381e2b9.png)

**Comment by rubensworks** [comment]
Thanks for checking!
