### ISSUE TITLE
Facades cause water to show flowing animation at the sides

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1055]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When a logic cable has been applied a facade, the facaded cable will cause adjacent water to show its flow animation on the adjacent side, see this vanilla report: https://bugs.mojang.com/browse/MC-91224

#### Steps to reproduce the problem:

1. Place a logic cable on the ground
2. Craft a facade with a block (e.g. stone) and then apply it to the cable
3. Make a 1 block hole in the ground, 2 blocks away from the cable
4. Place a water source between the hole and cable, so it flows into the hole
5. Stand inside the hole and press forwards towards the cable so you can see the facade clearly under water
  →:x: Notice that you can see the water's side touching the facade

![Wateranimation facades](https://user-images.githubusercontent.com/14236702/121819466-7e848080-cc8d-11eb-8122-d4548c7041af.png)
![Wateranimation facades underwater](https://user-images.githubusercontent.com/14236702/121819465-7debea00-cc8d-11eb-9a73-b95b97be13f8.png)
(for the screenshot, notice the difference between the facade on the left versus the actual block on the right)

#### Expected behaviour:

I would have expected that if I make the cable a full block by applying a facade, it would not show any water surfaces on its sides. Waterlogged blocks never do of course, that's its definition, but if thay _can_ be waterlogged but just aren't yet, and are also a full block, they shouldn't do it either.

Not sure what is the limitation or intention even. But this is my expectation.

____

#### Versions:

- This mod: 1.8.4
- Core: 1.11.7
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.1.31

**Comment by rubensworks** [comment]
Thanks for reporting!
