### ISSUE TITLE
World Importer Game Crash

### ISSUE THREAD

**Issue by Raeis-Eikr** [CyclopsMC/IntegratedDynamics#1056]
Game crashes when applying variable card to world importer in the "import all items from entities" slot.
Attaching logs.
[Integreated Dynamics Crash.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/6683260/Integreated.Dynamics.Crash.zip)

**Comment by Raeis-Eikr** [comment]
Wrong mod, Issue already tracked in correct mod

**Comment by CyrusCore** [comment]
haha stupid
