### ISSUE TITLE
logic stopped working

### ISSUE THREAD

**Issue by Pultex** [CyclopsMC/IntegratedDynamics#1057]
#### Issue type:

- :question: Question 

____

#### Question:
was in 1.16.5 with IntegratedDynamics-1.16.5-1.8.2

not sure what happened in my world but logic suddenly stopped working

readers did see redstone signals and the variables in a display showed values but exporter and importers did nothing

had a simple setup

list equal to 9 connected with and and condition to a  redstone is active condition

it kept pulsing on redstone even if there was no items in the container the reader was looking at

thought maybe I uesd a not equals or a nand but it was an and gate

breaking cables made it work for a few ticks then stopped again

just wanted to know if  i did something wrong

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
That's not normal behaviour. Some other mod must be breaking things (e.g. Performant). I suggest retrying without any other mods installed.
