### ISSUE TITLE
CTD and other issues with Agricraft added

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1058]
#### Issue type:

- :bug: Bug 

____

#### Short description:
With Agricraft added to your mods it`s impossible to load "old" saves normally. After adding it, if you try to load save game dies. To load them I had to delete data/integrateddynamics_Networks.dat. If that is done then save will load but then placing any cable part (reader,writer,importer etc) places cable instead.
![obraz](https://user-images.githubusercontent.com/6943031/123518905-6d356e00-d6a8-11eb-8f21-3a0493442c60.png)

#### Steps to reproduce the problem:

1. Make new world with your mods only
2. Save it
3. Add Agricraft
4. Try to load previously saved world
5. ..
6. Delete data/integrateddynamics_Networks.dat
7. Load world
8. Try place some cable parts

#### Expected behaviour:
Game loads normally. When placing cable parta they are placed correctly.

____

#### Versions:

- This mod: 1.16.5-1.8.4
- Minecraft: 1.16.5
- Forge: 36.1.2

![obraz](https://user-images.githubusercontent.com/6943031/123519289-8b9c6900-d6aa-11eb-9bb5-705fe772c83d.png)

#### Log file:
Game crash:
https://paste.ee/p/yS8sv
Trying to place inventory reader.
https://paste.ee/p/JL30O

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Hiranus** [comment]
It seems similar to: https://github.com/CyclopsMC/CyclopsCore/issues/159

**Comment by rubensworks** [comment]
Seems to be a problem in AgriCraft: https://github.com/CyclopsMC/CyclopsCore/issues/159#issuecomment-869043682
