### ISSUE TITLE
Crash when working with fluids

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [CyclopsMC/IntegratedDynamics#1059]
#### Issue type:

- :bug: Bug

____

#### Short description:

Integrated dynamics doesn't seem to make the proper checks to make sure a tank is valid.

#### Steps to reproduce the problem:

For mods you will require integrated dynamics and pneumaticraft all running on a server.

Utilize an aerial interface with a dispenser upgrade. (This makes the block contain a fluid).

Hook up a fluid reader up to the interface with the aspect "Total Fluid Capacity"

If whomever owns the aerial interface leaves the server will crash due to the interface no longer containing a tank.

#### Expected behaviour:

Won't crash when doing this.

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- Pneumaticcraft Repressurized: 0.11.15-398

#### Log file:

[crash.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/6720653/crash.txt)

____

I'll poke around the source code of this mod and pneumaticcraft and get back with what I find.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
ID should have the proper checks in place though.
I suspect Pneumaticcraft Repressurized is not modifying the tank count value properly.

In any case, not much I can do about it on my end, as 1.12 is not supported anymore unfortunately.
