### ISSUE TITLE
"Bone -> white dye" recipie supported by squeezer but not by mechanical squeezer

### ISSUE THREAD

**Issue by cookiecan10** [CyclopsMC/IntegratedDynamics#1060]
#### Issue type:

- :question: Question 

____

#### Question:

Question:
The (manual) squeezer allows you to turn bones into white dye, but this recipie is not supported by the mechanical squeezer. 
Is this a bug or a feature?

Mod version: 1.16.5-1.8.2
Modpack: Direwolf20 1.16.5 (Version 1.10.1)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Sounds like a bug indeed.
