### ISSUE TITLE
Logic Programmer search bar cannot be cleared anymore, once a variable card is given a custom name

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1061]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Once you rename a variable card in the logic programmer with the labeller in your inventory, anything you type in the operator search bar cannot be backspaced anymore until you reopen the programmer GUI.

#### Steps to reproduce the problem:

1. Get the portable logic programmer, a blank variable card and the labeller.
2. Use the programmer to open the GUI
3. Choose the String operator and type some value
4. Click the little E button to toggle the rename textfield, and type something in there too
5. Now shift-click the blank variable card in, and take it out fully programmed
6. Now type something (else) in the operator search bar at the top-left and try to backspace it away again because you made a typo
    ❌ Notice it doesn't go away

#### Expected behaviour:

Just after the rename field of the labeller is used, the backspace button should still continue to work (obviously) and allow you to clear the search bar when/if you want to. It does work normally if you didn't use the rename field of the labeller, or didn't have a labeller in the first place.

____

#### Versions:

- This mod: 1.9.0
- Tunnels: 1.8.4
- Core: 1.11.7
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.1.32
- Other mods:
  - JEI: 7.7.0.107

**Comment by rubensworks** [comment]
Thanks for reporting!
