### ISSUE TITLE
Omni crafting issues. 

### ISSUE THREAD

**Issue by User-green** [CyclopsMC/IntegratedDynamics#1062]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Omni-directional connectors can not be assigned to the group via means of crafting.

#### Steps to reproduce the problem:

**Setup**
- Oracle's JRE 8 (Latest)
- Minecraft server
- This mod with integrated tunnels addon

**Howto**
1. Place omni-directional connector on the logic cable
2. Take it to inventory with wranch (ID and group must be saved)
3. Place connector from step 3 into any crafting grid with blank one.
4. Take the crafting result.
5. Observe the issue — connectors are NOT assigned to any group.

#### Expected behaviour:
At step 5 connectors expected to be assigned to a same group. 
____

#### Versions:

- This mod: 
1.8.1
- Minecraft: 
1.16.5
- Forge: 36.1.0

**Mod assembly is used!** 
However, I am shure that any other mods IS NOT responsibe for this issue, because all other mods targets world generation, not crafting or player's GUI.

#### Log file:

None, due to issue been non-faliature.

Aditional logs may be collected if needed

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Isn't that an old Forge and mod version? The latest version is 1.9.0 on Forge 36.1.32.
Also note that for Integrated Tunnels the latest version is not the same number.

**Comment by User-green** [comment]
> 
> 
> Isn't that an old Forge and mod version? The latest version is 1.9.0 on Forge 36.1.32.

Yep, mod is outdated. I'll check this with newest.
Forge, however, is okay, because  36.1.32 ie experemental, meanwhiole  36.1.0 is stable.

> Also note that for Integrated Tunnels the latest version is not the same number.

Yep, I know. But this is ID fault, not IT, so no reson to say about this.

**Comment by User-green** [comment]
BTW, also present on "clear" IntegratedDynamics-1.16.5-1.8.5 + IntegratedTunnels-1.16.5-1.8.3 + CommonCapabilities-1.16.5-2.7.0 + CyclopsCore-1.16.5-1.11.7.
