### ISSUE TITLE
menril wood block

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#1063]
make a menril wood block such as the bark blocks  that were added in 1.13 but for the 1.12.2 version : https://www.google.com/url?sa=i&url=https%3A%2F%2Fminecraft.fandom.com%2Fwiki%2FWood&psig=AOvVaw0gXgznwB9V0mFKpz2YmmVS&ust=1625545634970000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCND21cOLy_ECFQAAAAAdAAAAABAD

**Comment by rubensworks** [comment]
Already exists in 1.16

**Comment by ghost** [comment]
but i need it for 1.12.2

**Comment by ghost** [comment]
> Already exists in 1.16

but ineed it for 1.12.2 skyfactory
