### ISSUE TITLE
The wrench doesn't work while crawling

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1064]
#### Issue type:

- :bug: Bug 

____

#### Short description:

While you're in crawling mode (1-block tall space), you're unable to use the wrench to pick up logic cables or other parts.

#### Steps to reproduce the problem:

1. Place a logic cable on the ground
2. Place a block on top of it
3. Attach a trapdoor to the lower side of the side of the block and then open it
4. Walk up against the trapdoor and close it again (forces you down into crawl mode)
5. Try to shift right-click on the logic cable with a wrench
   →:x: Notice that nothing happens

![Crawling integrated wrench](https://user-images.githubusercontent.com/14236702/125208744-b08d0080-e294-11eb-8156-1054d4e47cd5.png)

#### Expected behaviour:

The logic cable should pop off and drop as an item that you would pick up.

While in crawling mode, nothing happens when you start pressing shift, but the button being pressed should still be recognizable for other functions than crouching. This can be observed from a different mod, a Thermal Expansion Fluxbore with a Radial Enhancement augment set to 3x3 digging mode, and temporarily switching back to 1x1 mode using the shift key. (not installed during this bug testing)

____

#### Versions:

- This mod: 1.9.0
- Tunnels: 1.8.4
- Core: 1.11.7
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.1.32
- Other mods:
  - JEI: 7.7.1.110

**Comment by rubensworks** [comment]
Thanks for reporting!
