### ISSUE TITLE
Allow Dragging and Dropping Items and Blocks into the Logic Programmer from JEI

### ISSUE THREAD

**Issue by RobuxShooters** [CyclopsMC/IntegratedDynamics#1066]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Players should be able to drag and drop items/blocks from JEI into the Logic Programmer for easier programming purposes and to reduce inventory clutter. As of now (when making a List for example), you need to have the block or item you want to add to the list in your inventory before you are allowed to put it into the Logic Programmer. This can clutter the inventory very quickly, especially if there are many different items and blocks.

It also allows the sorting of really difficult-to-acquire items or blocks by using Lists before one even gets the item or block, for instance in an AFK mob farm for a particularly rare drop.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This is implemented in the MC 1.19+ versions.

**Comment by WeaselOnaStick** [comment]
#1398 Seems like this feature only works partially
