### ISSUE TITLE
Inverted behaviour "relational less / greater than"

### ISSUE THREAD

**Issue by Paraxdq** [CyclopsMC/IntegratedDynamics#1067]
#### Issue type:

- :question: Question 

____

#### Question:

I have a question regarding the operators "relational less than" and "relational greater than". I tried to export every item I have in the system with a specified nbt tag into a chest, didn't get it to work at all, except with the full nbt value I extracted at the nbt extractor for the specified item. So I tried another approach and got it to work on the first attempt. I got the operators for item nbt and their respective compound size, piped them together and also piped it with the apply result fromo "relational greather than" and an the integer 3. So as far as I understand this should result in every item with more than 3 nbt tags should be exported.. but it's exact the opposite case, every item with less than 3 nbt tags is exported. So I reverted the "relational greater than" and made a less than out of it, works fine now, but why? Got something similar with filtering by item damage.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
If `A < B` is used, and you apply `A` with the constant `3`, this becomes `3 < B`, so anything you pass as value for `B` will become the inverse of what you'd expect.
