### ISSUE TITLE
Menril etymology

### ISSUE THREAD

**Issue by l4ssc** [CyclopsMC/IntegratedDynamics#1068]
#### Issue type:

- :question: Question 

____

#### Question:

Where did the name for Menril (or the Meneglin biome) come from? I've always been curious because it's obviously not a real material 😛

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
It comes from [Sindarin](https://en.wikipedia.org/wiki/Sindarin).
Menril: Sky+Glitter
Meneglin: Glint of sky
