### ISSUE TITLE
A command that updates all networks

### ISSUE THREAD

**Issue by DraGonFiirE** [CyclopsMC/IntegratedDynamics#1069]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

A command that updates all networks would be greatly appreciated
Pretty much just to fix the "Network Corrupted!" error that appears after mod updates/server restarts seemingly randomly
I know the goal should be that networks wont get corrupted in the first place but It would be a good workaround as the issue seems to be hard to trackdown
For sure easier executing a command than updating all networks manually

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Is this still occurring for you?
AFAIK, this problem has been fully resolved, as there are no open bug reports for it anymore.

> For sure easier executing a command than updating all networks manually

Sure, but implementing such a command is not trivial at all...

**Comment by DraGonFiirE** [comment]
Looks like I didnt update to 1.9.1 before posting this, will give an update if it occured again

**Comment by zoller27osu** [comment]
This issue still happens sometimes on Minecraft 1.16. Attached is a log, although I'm not sure if the networks were already corrupted when the world was loaded this time
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/7775564/latest.log)
a command like this would be massively helpful when it happens, but even better, would allow for i.e. automatic network re-loading on world load, or when a corrupted network is detected?

**Comment by rubensworks** [comment]
@zoller27osu Could you open a bug report for this?

**Comment by rubensworks** [comment]
Closing this in favor of #1121.
