### ISSUE TITLE
Wrench tries to rotate blocks but doesn't succeed

### ISSUE THREAD

**Issue by Runesmacher** [CyclopsMC/IntegratedDynamics#107]
The wrench tries to rotate blocks on right click (visualy it does seem to rotate)
But just after that this change gets reverted (pretty much all blocks that allow rotation)

**Comment by rubensworks** [comment]
Only ID blocks? Or all blocks, e.g. vanilla chests?

**Comment by Runesmacher** [comment]
All blocks including vanilla chests

**Comment by rubensworks** [comment]
Probably also a `!world.isRemote` that should be removed.
Feel free to have a look at this one as well if you're up to it :)
