### ISSUE TITLE
OtDoI book looks buggy since advancements are hidden

### ISSUE THREAD

**Issue by AndreLouisIssa** [CyclopsMC/IntegratedDynamics#1070]
#### Issue type:

- :bug: Bug 

____

#### Short description:

OtDoI (On the Dynamics of Integration) book looks buggy because advancements are hidden until their prerequesites are obtained.

By prerequisites I don't necessarily mean their direct antecedents on the graph, but whatever it is minecraft uses to choose whether to display the advancements in the advancements graph.

Before obtaining the advancement "Logic Programming":
![image](https://user-images.githubusercontent.com/20250183/127806570-e7260ed4-22a5-48fe-8714-72b3cc833b4f.png)

After obtaining the advancement "Logic Programming":
![image](https://user-images.githubusercontent.com/20250183/127806576-50b8653d-28be-4cfb-aa78-c43f7a688adb.png)

#### Steps to reproduce the problem:

1. Have some prerequisites for advancements for some reward in the book yet unobtained
2. Open the book "On the Dynamics of Integration" and visit the page for the rewards in question
3. See that the advancements section is missing the true advancements needed to unlock the rewards.

#### Expected behaviour:

It should show the advancements or placeholders to indicate that it's not bugged out.

____

#### Versions:

- This mod: 1.9.1
- Minecraft: 1.16.5
- Forge: 36.2.2

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by AndreLouisIssa** [comment]
Also this has been an issue on earlier versions, I just didn't notice the cause until now and thought it might just be a rendering bug.
