### ISSUE TITLE
[13:53:15] [Server thread/ERROR] [IntegratedDynamics-Compat]: The compatibility for tconstruct has crashed! Report this crash clog to the mod author or try updating the conflicting mods.

### ISSUE THREAD

**Issue by Aaur1s** [CyclopsMC/IntegratedDynamics#1071]
- Bug
- Short description: Console told me to report it, its not causes crash.
- Versions:
- This mod: 1.1.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- Log file:
https://pastebin.com/LhUwT7Wd
[2021-08-07-1.log](https://github.com/CyclopsMC/IntegratedDynamics/files/6949049/2021-08-07-1.log)

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.12 is not supported anymore.
