### ISSUE TITLE
[1.16.5] Logic Programmer doesn't catch hotkeys when typing in rename field

### ISSUE THREAD

**Issue by CodeGordon** [CyclopsMC/IntegratedDynamics#1073]
#### Issue type:

- :bug: Bug

____

#### Short description:
When typing to name variable cards in the Logic Programmer, hotkeys are still active, so trying to type "feathers", for example, will close the GUI and leave you with a card named "f". This only affects the Logic Programmer; the Renamer used by itself works as expected.

#### Steps to reproduce the problem:

1. Open Logic Programmer (block or portable versions) with Renamer in inventory.
2. Click the "E" button to open the name entry field.
3. Type the key that opens/closes the inventory screen ("e" in my case).

#### Expected behaviour:
Text is properly captured in the name entry field, and the GUI doesn't prematurely and unexpectedly close.
____

#### Versions:

- This mod: 1.9.2
- Minecraft: 1.16.5
- Forge: 36.2.2

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
