### ISSUE TITLE
[1.16.5] Already named cards do not display names in reference section of tooltip

### ISSUE THREAD

**Issue by CodeGordon** [CyclopsMC/IntegratedDynamics#1074]
#### Issue type:

- :bug: Bug

____

#### Short description:
Prenamed variable cards display only by their ID when used in the Logic Programmer to make further cards.

#### Steps to reproduce the problem:

1. Name variable card (A) in Renamer.
2. Set a value of some kind for variable card A in Logic Programmer (block or portable).
3. Use variable card A to create another variable card (B) in Logic Programmer.
4. Check tooltip on variable card B.

#### Expected behaviour:

Name from step 1 above shown on tooltip for variable card B.

____

#### Versions:

- This mod: 1.9.2
- Minecraft: 1.16.5
- Forge: 36.2.2

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
