### ISSUE TITLE
Energy Battery sometimes requires lever to activate over an importer

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1077]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you import energy from an energy battery, the battery sometimes _requires_ a redstone signal before it allows moving any energy out of it, while ignoring the used variable card.

I've figured out this depends on the order in which you place the cable and importer.

#### Steps to reproduce the problem:

1. Place an energy battery (with energy in it)
2. Place a logic cable next to it (it will connect)
3. Insert an energy importer between them by clicking the side of the battery around the cable connection
4. Add an energy interface on the other end of the cable and attach some kind of machine that can accept energy (I used Thermal Expansion's Magma Crucible in the screenshot)
5. Now insert a blank variable card into the top aspect of the importer
  → ❌ Notice the machine is not filling up with energy regardless of the aspect reporting value "true"

Now redo the whole setup but swap step 2 and 3. Place the importer before you do the cable.
  → ✔️ Notice that energy is now automatically transported without having to add a lever

See screenshot (after all is now working):
![Energy transport](https://user-images.githubusercontent.com/14236702/129971387-6a6928fd-641f-41ea-aa16-55bf3d94b467.png)

#### Expected behaviour:

When I place a cable next to a battery that I then later decide to connect to said cable through an energy tunnel, I expect that the initial cable's direct connectivity with the battery itself would get "overridden" in some way, and not get in the way of the tunnel.

However it seems that the direct connection takes precedence over the tunnel, and the tunnel does not get used at all. Because of the dual actor thing of #894, using a lever would effectively workaround it and force send through the importer by act of the battery instead of by the importer itself. But it should not happen that the importer gets ignored in the first place. Normally an importer bridges the gap between cable and block, and having the cable do that already should not affect the importer's function.

A possible fix would be automatically disconnecting a block from a cable's network when a tunnel gets attached between them this way.

____

#### Versions:

- This mod: 1.9.3
- Tunnels: 1.8.5
- Core: 1.11.8
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.2
- Other mods (for testing purposes):
  - Thermal Foundation 1.3.2
  - Thermal Expansion 1.3.0
  - CoFH Core 1.3.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does the same thing happen when you replace the Magma Crucible with another Energy Battery?

**Comment by Jack-McKalling** [comment]
Yes. But then only if the cable is placed before the importer AND interface.

**Comment by rubensworks** [comment]
I just tried the following, and everything works without issues:

1. Place a full and empty battery, separated by an empty block
2. Place a cable in the middle (connects to both batteries)
3. Place energy importer on full battery
4. Place energy interface on empty battery
5. Enable boolean aspect to import all energy

Am I missing something @Jack-McKalling?

**Comment by Jack-McKalling** [comment]
I tried the exact same thing and for me it does not transport any energy.
I don't know what you're doing different from me, but I just retested it with the latest 1.16 versions and I can still reproduce it.
Looking into whether I can capture a video of this.

**Comment by Jack-McKalling** [comment]
Ah I figured out what you're doing different from me. You also have to FACE in the right direction.

Retry the same steps you just posted, but FACE north, and work from left to right. So, full battery on the west of where you're going to place the cable, and the empty one on the east.

**Comment by rubensworks** [comment]
> Ah I figured out what you're doing different from me. You also have to FACE in the right direction.

Still works as intended for me.

Might be better to just share a recording.

**Comment by Jack-McKalling** [comment]
I just finished a recording, but it a bit big sorry. Google drive:
https://drive.google.com/file/d/1rmlr_jcH6AuDqyHGqdYp6vfAcWaTvOvD/view?usp=sharing

<blockquote><img src="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1rmlr_jcH6AuDqyHGqdYp6vfAcWaTvOvD/view?usp=sharing&usp=embed_facebook">Integrated Tunnels no energy transfer.mp4</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the video, I've managed to reproduce it like this! (misunderstood the facing description...)

**Comment by Jack-McKalling** [comment]
My logic was, potentially the logic cable saves some kind of facing direction from how it was placed, and that it is this direction that would cause the doubly connected cable face to malfunction as described above (due to the problem apparently being direction-dependent). A vague obscure idea upon a vague obscure idea, but I'm only trying to make sense of the issue I'm experiencing.

**Comment by rubensworks** [comment]
The problem seems to be that when placing parts on cables like that, the original connection is also kept (which is incorrect).
The reason why the facing matters, is that this this influences the iteration order when moving energy.
The north-based setup will basically cause the energy extracted from the left battery, to be re-inserted into the left battery, and this seems like a no-op for the user.

**Comment by Jack-McKalling** [comment]
Ok, got it. So I was basically correct in my first idea, that there is the cable doubly connecting, and in the second that the facing direction is saved and used. But you explain that differently than my head. I hope you can fix this now that it is understood.
