### ISSUE TITLE
Many formatting issues in the manual

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1078]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The "On The Dynamics of Integration" in-game guide book, has many formatting issues (on 57 pages in total).
The issue is that when a formatting range exceeds a line wrap in the book, the formatting on the next line proceeds to fill the rest of the line, as opposed to end somewhere in the middle. If that's too vague please see this example:

![integrated formatting](https://user-images.githubusercontent.com/14236702/130111750-0edcf7ee-f7db-4774-bd93-6bc626a4f10e.png)

This issue happens all over the book.

#### Steps to reproduce the problem:

1. Open the book
2. Browse
3. Look

I've made screenshots with all the problematic formatting problems encircled and tiled them together. See below

#### Expected behaviour:

When the formatting exceeds a line wrap, it should also properly end in the middle, instead of including the rest of the line.

#### Screenshots:

In order of appearance:
<img src="https://user-images.githubusercontent.com/14236702/130109497-52c12a53-5029-4e74-8d9d-0b29eb5f3455.png" width="250" /> <img src="https://user-images.githubusercontent.com/14236702/130109503-71bef57b-6bfd-421e-8c9d-00473d80cde6.png" width="250" /> <img src="https://user-images.githubusercontent.com/14236702/130109505-ed5c6372-56f4-4ccf-952a-445f1d40ce85.png" width="250" /> <img src="https://user-images.githubusercontent.com/14236702/130109510-63203bfb-5266-41b5-9fd1-f5dc23b0789c.png" width="250" /> <img src="https://user-images.githubusercontent.com/14236702/130109515-c6098b9b-1856-47aa-905a-bf1ee87d4c97.png" width="250" />

____

#### Versions:

- This mod: 1.9.3
- Tunnels: 1.8.5
- Core: 1.11.8
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I had also found this one, and there may be more occurances like this one, but here the issue is almost not noticible due to the only remaining part of the sentence that gets affected is a dot. A then slightly wider dot.
![integrated formatting invisible](https://user-images.githubusercontent.com/14236702/130158002-60108959-d084-4ad5-bd53-ff22dcd324c4.png)
