### ISSUE TITLE
Setting \g in a regular expression

### ISSUE THREAD

**Issue by DraGonFiirE** [CyclopsMC/IntegratedDynamics#1079]
#### Issue type:

- :question: Question

____

#### Question:

Is there a way to set the global regex flag? 
also is this accurate?: `https://github.com/google/re2/wiki/Syntax`

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
No, setting global regex flags is not possible atm.
You could probably get around with setting flags within groups though?

> also is this accurate?: https://github.com/google/re2/wiki/Syntax

Yep, that should be correct!

<blockquote><img src="https://opengraph.githubassets.com/c1a0852001c9735587b8f8d32c9fec8b32ec85c9a03a443eda0bbf93b37102a1/google/re2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/google/re2">Syntax · google/re2 Wiki</a></strong></div><div>RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library. - Syntax · google/re2 Wiki</div></blockquote>

**Comment by DraGonFiirE** [comment]
> You could probably get around with setting flags within groups though? 

Setting the global flag within a group is not supported it seems
![grafik](https://user-images.githubusercontent.com/75578285/130354735-b2202186-6db7-447d-a60a-3ccfbb2c2a8f.png)

**Comment by rubensworks** [comment]
Ah sorry, I thought you meant setting regex flags in the global scope, instead of in a group scope.

Not sure why you'd need the `g` flag. Could you give an example?
The `replace` operator will for instance work in global-mode, so the `g` is not needed there.

**Comment by DraGonFiirE** [comment]
> Ah sorry, I thought you meant setting regex flags in the global scope, instead of in a group scope.

That was my intention at first, I've only posted that picture in respone to:

> You could probably get around with setting flags within groups though?

My use case is matching characters like this:
![grafik](https://user-images.githubusercontent.com/75578285/130356499-3d33332f-fb16-467b-b42a-c9e33acd08f4.png)
Without the global flag the result would just be that:
![grafik](https://user-images.githubusercontent.com/75578285/130356623-331cf693-8822-4a19-ba77-b8e0cf056ad4.png)
And thats exactly the output of the `regex_groups` function ingame since its not using the global flag


The code to test with:
`{"extra":[{"color":"blue","extra":[{"color":"black","text":"\n x1"},{"color":"gray","text":" | 0▤ +1\n"}],"translate":"block.astralsorcery.spectral_relay"},{"color":"blue","extra":[{"color":"black","text":"\n x4"},{"color":"gray","text":" | 0▤ +4\n"}],"translate":"block.astralsorcery.marble_chiseled"},{"color":"blue","extra":[{"color":"black","text":"\n x4"},{"color":"gray","text":" | 0▤ +4\n"}],"translate":"block.astralsorcery.marble_arch"},{"color":"blue","extra":[{"color":"black","text":"\n x1"},{"color":"gray","text":" | 0▤ +1\n"}],"translate":"block.astralsorcery.black_marble_raw"}],"text":""}`

The regex to test with:
`translate...\w+.\w+.\w+|x\d`

The site I tested with:
[https://regex101.com/r/eE6mX3/2](url)

**Comment by rubensworks** [comment]
Could you try with `regex_scan` instead?

**Comment by DraGonFiirE** [comment]
`regex_scan` worked with integer 0 
My error was using `index_of_regex` and assuming the resulting integer is the index of the group that `regex_scan` needs
Thanks a lot for your time! :)
