### ISSUE TITLE
Ore recipes in the Squeezer don't show in JEI

### ISSUE THREAD

**Issue by aaronhowser1** [CyclopsMC/IntegratedDynamics#1082]
#### Issue type:

- :bug: Bug 

____

#### Short description:

JEI shows a bunch of empty pages where there used to be the ore recipes:
![image](https://user-images.githubusercontent.com/15698722/131209499-524e34b1-2bca-494c-b2fe-bdcaf3a87eec.png)
If you scroll through the pages, they eventually go away entirely:
![image](https://user-images.githubusercontent.com/15698722/131209535-16bef516-b042-40c5-b390-53767d6be71c.png)

The recipes actually do still work though
____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.9.3
- Minecraft: 1.16.5
- Forge: 36.2.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by aaronhowser1** [comment]
Just noticed the log is very angry about it, here: 
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/7070304/latest.log)

**Comment by rubensworks** [comment]
Must be a breaking change in JEI, used to work without issues.
