### ISSUE TITLE
Fluid Interfaces not reading maximum fluid storage correctly

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#1083]
#### Issue type:

- :bug: Bug 

____

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3153

#### Short description:

Integrated Dynamics' fluid interfaces do not read the maximum fluid amount/storage available correctly, reporting it always as 2^31mB

#### Steps to reproduce the problem:

1. Set a Fluid Interface next to any tank 

#### Expected behaviour:

For the Fluid Interface to read the correct maximum capacity of the tank

____

#### Versions:

- This mod: [IntegratedDynamics-1.16.5-1.9.3.jar](https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/3425174)
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.2

#### Screenshots:
![blacktank](https://user-images.githubusercontent.com/32048635/131713296-0dfc8b40-996d-4279-a366-ef981908e803.png)
![scorchedtank](https://user-images.githubusercontent.com/32048635/131713305-38c44ca8-1eb0-4909-8598-ecbd80b309ea.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
