### ISSUE TITLE
Using the wrench on a cable part deletes the part and any card inside, when in creative mode

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1084]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you use the wrench in creative mode to pick up a cable part (not limited to those can have a variable card in it), such as Readers, Writers or Item Interfaces, it will delete the part along with any card in it. This is not the behaviour observed with Variable Stores that have cards in them, as it would drop both.

#### Steps to reproduce the problem:

1. Place a Logic Cable
2. Attach a Redstone Reader
3. Insert a Variable Card into the top aspect and take the programmed card out
4. Shift-right click with a Wrench on the Redstone Reader (or any other part attached to a Logic Cable)
   → ❌ Notice that the part disappears and nothing drops as an item
5. Place a Variable Store
6. Insert the card you made in step 3
7. Shift-right click with a Wrench on the Variable Store
   → ✔️ Both the Variable Store as well as the Variable Card in it drop as items

#### Expected behaviour:

For consistency with the Variable Store, I would expect a cable attachment to drop as an item if the wrench was used on it, considering that it would be an item drop with extra data on it. Just like how a shulker box with items in it would drop itself while preserving all items inside when broken in creative mode, and just like how the Variable Store is preserved with all its cards (although they drop as separate items).

Normally the wrench is used to preserve data on a part, as opposed to just mining it sowly with a pickaxe to destroy all its data. But this way doesn't just destroy the data you wanted to preserve, it also destroys the item altogether.

____

#### Versions:

- This mod: 1.9.4
- Tunnels: 1.8.6
- Core: 1.11.9
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!
