### ISSUE TITLE
Strange visual "selection" artifacts when using logic programmer

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1086]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Under many different circumstances strange selections can occur within the logic programmer's GUI, when typing or selecting text in any of the GUI's textfields.

I've found 8 different ways to make this consistently happen, I've categorized these under 4 different results below with a screenshot for each.

#### Steps to reproduce the problem:

Type 1 selection:
1. Open the portable Logic Programmer (with a labeller in inventory)
2. a. (optional) Click on an operator such as Boolean
  b. (optional) Click on the labeller "E" button
  c. Type something in the top left search bar
3. Press CTRL+A to "select all"
   → ❌ Notice that the operator list scrollbar as well as the background around the labeller field (if opened) both turn blue
4. Press the End key to cancel selection
5. Right-click on the text that you typed
   → ❌ Notice that the same selection problem happens
6. Press the End key to cancel selection
7. Press SHIFT+Home to "select line"
   → ❌ Notice that the same selection problem happens once again
![LP selection type1](https://user-images.githubusercontent.com/14236702/132062297-e80d860b-8032-4f8d-8a3d-d0eda583b28e.png)

Type 2 selection:
1. Open the portable Logic Programmer (with a labeller in inventory)
2. Click on any operator such as Boolean
3. Click on the labeller "E" button
4. Type something in the labeller textfield
5. Press CTRL+A to "select all"
   → ❌ Notice that the form element for the operator itself gets a blue background
6. Press the End key to cancel selection
7. Right-click on the text that you typed
   → ❌ Notice that the same selection problem happens
8. Press the End key to cancel selection
9. Press SHIFT+Home to "select line"
   → ❌ Notice that the same selection problem happens once again
![LP selection type2](https://user-images.githubusercontent.com/14236702/132062366-e75ff12a-13dd-4ee7-9044-62fa73b0b6de.png)

Type 3 selection:
1. Open the portable Logic Programmer (with a labeller in inventory)
2. Click on any operator such as Boolean
3. Click on the labeller "E" button
4. Copy/paste "dtghhdthdhdhdfhdhdhdfhdbn" (exact string without quotes) into the labeller textfield
   → ❌ Notice that the form element of the operator itself once again gets a blue background, but the labeller field also gets a weird white end on the right overlapping the final character, eventhough you made no selection yourself
![LP selection type3](https://user-images.githubusercontent.com/14236702/132062459-f70d9337-db29-4a98-849a-3a515692f08d.png)

Type 4 selection:
1. Open the portable Logic Programmer
2. Click on any operator with a textfield, such as Boolean
3. (optional) Right-click the textfield to select the default "false" value to overwrite it (not necessary, it happens either way)
4. Copy/paste "dgfh cgh cgj cc cftjc gjcdtghu cvbg" (exact string without quotes) into the textfield
   → ❌ Notice that this time the last character typed appears to be selected for no reason, eventhough you made no selection yourself and the character doesn't get overwritten if you continue to type
![LP selection type4](https://user-images.githubusercontent.com/14236702/132062469-0ffbd157-dbfd-4d64-8f59-915b90b0538a.png)

#### Expected behaviour:

All these selection artifacts seem to happen outside of the actual textfield or outside the textfield's normal function. I expect only text to appear selected within the textfield, and only if I made the selection myself (by pressing CTRL+A, right-click, SHIFT+Home or some other way).

____

#### Versions:

- This mod: 1.9.4
- Tunnels: 1.8.6
- Core: 1.11.9
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!
