### ISSUE TITLE
Compatibility between ID and CapabilityProxy, and if possible Entangled

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1088]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Compatibility between Block Reader from this mod and CapabilityProxy proxys, and if possible Entangled mod. 
I have many instances of "I cant have reader in there if I want it to look good" but there is simply no way to fit it. Ability to read "source" block data from proxy or entangled block would be amazing.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I would actually be more in favor of offsetatble parts, so I'm closing this in favor of #308.
