### ISSUE TITLE
ic2 machines not recognized as tank

### ISSUE THREAD

**Issue by Daenara** [CyclopsMC/IntegratedDynamics#109]
Me again, I noticed that it is not possible to transfer fluid from ic2 pumps or tanks and investigated a bit. Placing a fluid reader on an ic2 tank gave me the output of isTank false. I'm pretty sure that it is, indeed a tank I'm using, so it should work. Not sure where the problem is, most likely ic2 api but if it is possible, could you fix it?

EDIT: doesn't only concern the ic2 pump and tank, it's all ic2 machines using fluids
Daenara

slightly off topic PS: which mod are the tanks used in the screenshots from?

**Comment by rubensworks** [comment]
I just came across your [IC2 forum post](http://forum.industrial-craft.net/index.php?page=Thread&threadID=13838), so I guess you have your answer there.
I used to support the old fluid handlers back in 1.9, but removed them when porting to 1.10 to avoid having to maintain two separate systems.
If I understood correctly, the IC2 devs will implement the fluid capabilities soon, so this issue should resolve itself then as well.

The tanks are from [EvilCraft](https://minecraft.curseforge.com/projects/evilcraft) by the way, a tech/magic mod I developed.
