### ISSUE TITLE
Grass block used in facade has its top texture glitched

### ISSUE THREAD

**Issue by callmejay758** [CyclopsMC/IntegratedDynamics#1092]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Using a grass block in a facade has a texture error when observed from the top. The item form also has the texture bugged but it can be seen on the sides as well.

#### Steps to reproduce the problem:

1. Place a cable
2. Put a facade and a grass block into a crafting grid.
3. Place the grass block facade on a cable and observe its texture.
https://user-images.githubusercontent.com/37318891/134021257-635e589f-d70f-45cf-a085-ee2bd71b669b.mp4

#### Expected behaviour:

The top face to be the same texture as the block used.

____

#### Versions:

- This mod: 1.9.4
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!
