### ISSUE TITLE
Not recognizing Mystical Agriculture infusion crystal if not full durability

### ISSUE THREAD

**Issue by SirGeremiah** [CyclopsMC/IntegratedDynamics#1096]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Working in a storage terminal, pulling items in (using the JEI interface to request) to craft. First attempt was with a full-durability (1000 uses remaining) infusion crystal, and that worked perfectly. Second attempt was less than full (since I'd done the first one), and the item showed as missing when I tried to request. A quick test at a Tinker's Construct station verified the item pulls properly there, so it seems to be an InDy issue.

#### Steps to reproduce the problem:

1. Place inferium and a full-durability infusion crystal in a chest, linked via item interface.
2. Craft prudentium essence, using JEI to pull the items into the storage terminal.
3. Return items to storage.
4. Request the same recipe again.

#### Expected behaviour:

JEI reports "missing items" and highlights the infusion crystal in red.

____

#### Versions:

- This mod: 1.9.4
- Minecraft: 1.16.5
- Forge: 36.2.4
This was initially noted in the FTB Oceanblock modpack, and was recreated in a custom world using only the Integrated mods (Crafting, Dynamics, NBT, Terminals, and Tunnels), JEI (plus JEI Integration, JE Professions, JE Resources), plus the Mystical Ag mods (Mystical Agriculture and Mystical Agradditions). Of course, includine the mods required by those.

**Comment by rubensworks** [comment]
Thanks for reporting!
