### ISSUE TITLE
Logic Cables have fully black block-break particles

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1097]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you punch a logic cable in survival mode, or when you break one in creative mode, you see block break particles that are fully black (100% hex `#000000`) instead of having a block texture.

#### Steps to reproduce the problem:

1. Place a logic cable
2. Break it with your fist (or just punch a couple of times if in survival mode)
3. Look at the black particles that appear

See these screenshots in creative / survival respectively:
<img src="https://user-images.githubusercontent.com/14236702/135929391-bde9042c-800e-4f8a-8b96-54c0ccf17d56.png" width="300" /> <img src="https://user-images.githubusercontent.com/14236702/135929392-2e095ef2-704b-49ca-ada6-81f831e4713f.png" width="300" />

#### Expected behaviour:

I was expecting the particles to use the texture of the logic cable.

Eventhough you're supposed to "break" cables using the wrench, these particles being 100% black is still wrong.

____

#### Versions:

- This mod: 1.10.1
- Tunnels: 1.8.6
- Core: 1.11.10
- CC: 2.7.1
- Minecraft: 1.16.5
- Forge: 36.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Also, I initially noticed this on a logic cable that had an Item Importer/Exporter/Interface on it, when destroying those parts of the block. However they are all part of the "Logic Cable" block and it occurs on a plain one as shown, too.
