### ISSUE TITLE
Crash with chisel and corrupted texture with Facade

### ISSUE THREAD

**Issue by Tobilike** [CyclopsMC/IntegratedDynamics#1098]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you combinate a Futura Block with a Facade the block has a corrupted texture when you place/use it. When you try to remove the block with a pickaxe the game crash.

#### Steps to reproduce the problem:

1. Place Logic Cable in the World
2. Craft a Facade with a Futura Block
3. Use the Facade and have a look to the corrupted Texture
4. Try with a pickaxe to mine the block
5. Game will crash.

#### Expected behaviour:

1. No Crash
2. Right looking texture

____

#### Versions:

Mod List: 
		forge-1.16.5-36.2.6-client.jar                    |Minecraft                     |minecraft                     |1.16.5              
		IntegratedTunnels-1.16.5-1.8.6.jar                |IntegratedTunnels             |integratedtunnels             |1.8.6               
		CyclopsCore-1.16.5-1.11.10.jar                    |Cyclops Core                  |cyclopscore                   |1.11.10                
		CommonCapabilities-1.16.5-2.8.0.jar               |CommonCapabilities            |commoncapabilities            |2.8.0               
		forge-1.16.5-36.2.6-universal.jar                 |Forge                         |forge                         |36.2.6      
		IntegratedDynamics-1.16.5-1.10.2.jar              |IntegratedDynamics            |integrateddynamics            |1.10.2              
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|DONE      
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    
		IntegratedCrafting-1.16.5-1.0.18.jar              |IntegratedCrafting            |integratedcrafting            |1.0.18              
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           
		IntegratedTerminals-1.16.5-1.2.7.jar              |IntegratedTerminals           |integratedterminals                     

#### Log file:

https://pastebin.com/dJUmBAyi

Screenshot:

https://ibb.co/7krbzHQ

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Tobilike** [comment]
Have forgot to say Thank You. Like the pretty much. I find the mod is much better then xnet and the matching mods for that.
