### ISSUE TITLE
Audio writer doesn't work as noteblocks

### ISSUE THREAD

**Issue by skydark** [CyclopsMC/IntegratedDynamics#1099]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Audio writer doesn't produce any sound, when using as note blocks.

#### Steps to reproduce the problem:

1. A simple setup including audio writer to produce note block sound from redstone strength integer variable (example: [https://imgur.com/a/i5xeeos](https://imgur.com/a/i5xeeos))
2. Use the level and listen, nothing happened.
3. Verified vanilla note block still works.
4. Verified audio writer still works when put a correct string variable (like `block.stone.step`) as "Sound" input. Only note block setups failed.

#### Expected behaviour:

Heard a noteblock sound in a correct setup.
____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.2.jar
- Minecraft: 1.16.5
- Forge: 36.2.8

**Comment by rubensworks** [comment]
Thanks for reporting!
