### ISSUE TITLE
FTB OceanBlock 1.2.0 and big Botany Pots Compact Machine lags immensely

### ISSUE THREAD

**Issue by Lordmau5** [CyclopsMC/IntegratedDynamics#1101]
#### Issue type:

- :snail: Performance issue 

____

#### Steps to reproduce the problem:

1. Get a 13x13x13 (Maximum) Compact Machine
2. Fill it with Integrated Dynamics Logic Cable with Item Interfaces and Hopper Botany Pots on-top
3. Add farmland and seeds
4. Also make sure to adjust the farmland speed to 0.975 (so the seeds grow really fast)
5. Add another Item Interface on a Refined Storage network so the Hopper Botany Pots can export into that inventory (extraction doesn't work, they require an inventory below)
6. See TPS going down

(Filled with Inferium Seeds and Insanium Farmland)
![1633989556-46002](https://user-images.githubusercontent.com/1345036/136864329-d8f402a9-a8f4-4958-a1aa-5e544a0976ed.png)
____

#### Versions:

- This mod: 1.9.4
- Minecraft: 1.16.5
- Forge: 36.2.4
- Modpack: FTB OceanBlock 1.2.0

#### Profiler output:

https://spark.lucko.me/xqD2UbW11Z

____

We did go a bit overkill with this, yes, and reached IDs in the thousands with all those Item Interfaces.
I'm not even sure if the performance on this can be improved or if that's just not the intended use-case, but I thought I'd open an issue anyway. 😁

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Lordmau5** [comment]
Wow, fast reply to this, didn't expect that around this hour 😁

Anyway, as I've mentioned, I *think* we went **quite a bit overboard** with this, but yeah... Maybe some improvements can be done :)
