### ISSUE TITLE
Sapling block reader presumed bug.

### ISSUE THREAD

**Issue by olly1240** [CyclopsMC/IntegratedDynamics#1103]
Hi, I was playing the last version of Integrated Dynamics found on Curseforge, and while I was testing it in creative mode i found what I think it might be a glitch. I used a block reader to read if there is a sapling in the current block. Then with the logic programmer i created a simple `==` with the block type output variable from the block reader and a simple oak sapling block variable. Then i put the resulting boolean variable into a display and everything seems to work well until bone meal is used, that after a random number of use raises the stage counter breaking the boolean check telling me that the sapling block variable and the block reader value don't match anymore. But the block reader still reads sapling. Am I missing something? It seems to change when growth changes from 0 to 1, but I thought that would have been ignored by the reader in the block type variable.  
Here are some screenshots
Before bone meal is applied   
![image](https://user-images.githubusercontent.com/46900833/138493640-e2e15573-24f1-40a8-9a38-f56f4820edee.png)

And then after 
![image](https://user-images.githubusercontent.com/46900833/138494284-ed0e91f8-70de-4a58-a0c4-e88f3e1ba80b.png)

Is this a bug or is that intended behavior?  
Thank you for your time! I love your mods!

**Comment by rubensworks** [comment]
This is intended behaviour, as ID reads blocks together with their blockstate, which here includes sapling age.
There should be an operator to convert a block value to its block type (or name), which could be used to purely compare the block independent of its state.
