### ISSUE TITLE
Move Items of JEI not working

### ISSUE THREAD

**Issue by bloucheur** [CyclopsMC/IntegratedDynamics#1104]
#### Issue type:

- :question: Question 

____

#### Question:

Is it normal that when I choose a craft in Just Enough Items and I click on the move items which detects the items in the network, the items do not move in the crafting window in the terminal?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Are you using the latest version of all mods? If yes, please report it as a bug.
