### ISSUE TITLE
Drying Basin recipes acting weird

### ISSUE THREAD

**Issue by Xaikii** [CyclopsMC/IntegratedDynamics#1105]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Creating a Recipe via Datapacks in 1.16 somehow creates thus recipe, but also not.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.3
- Minecraft: 1.16.5
- Forge: 36.2.4

#### Log file:

Nothing is mentioned in Logs.
Recipe: https://gist.github.com/Xaikii/4ef50b8e1789a129aa00f26ee7b9adc7
To clarify the issue more. The Recipe is recognized by JEI when checking for USAGE on the Snowball, but isnt listed in the total recipes of Drying Basin. 
The Animation is started when the Snowball is inserted, but it is never consumed and the water is never created.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have any other mods installed? If so, could you retry without them?

**Comment by Xaikii** [comment]
sure

**Comment by Xaikii** [comment]
I've been able to replicate it with only IntegratedDynamics, JEI and KubeJS(forge-1605.3.18-build.152).
![image](https://user-images.githubusercontent.com/25128633/139413401-a3b463fc-cd4c-41a7-a288-f1673c10ea84.png)
JEI is recognizing it

**Comment by Xaikii** [comment]
In case it helps, this is the path for the recipe
![image](https://user-images.githubusercontent.com/25128633/139413778-e829a36f-7f64-4489-a1ca-166b85a0a6ab.png)

**Comment by rubensworks** [comment]
Thanks
