### ISSUE TITLE
A block tag for both the menril log & filled variant

### ISSUE THREAD

**Issue by Quezler** [CyclopsMC/IntegratedDynamics#1106]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

well currently both of the menril logs that make up a tree do not share any tag: (annoying when harvesting w/ ftb ultimine)

![2021-11-05_15 03 26](https://user-images.githubusercontent.com/3179271/140524495-908f94e7-7a21-46f3-a31c-2788ca5d6b2c.png)
![2021-11-05_15 03 37](https://user-images.githubusercontent.com/3179271/140524521-335cb717-756b-4713-9a0e-2df32414f666.png)

we ran into it with: https://github.com/NillerMedDild/Enigmatica6/issues/3271 (above screenshots are also made in that modpack)

but we got around it with writing our own tag, but it would be neat if maybe this mod would have its own block tag for both of them: https://github.com/NillerMedDild/Enigmatica6/pull/3272/files

this isn't urgent or anything, it's pretty much fixed on our end, but it might be nice to consider 🙂

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Quezler** [comment]
which is now the tag shared by both log variants? couldn't quite make it out from all the file changes in the [diff](https://github.com/CyclopsMC/IntegratedDynamics/commit/d2b2af69b588fafb54da88e0d7e7ae5f18092c5b) 😅

**Comment by rubensworks** [comment]
@Quezler Just applied some improvements, you should be able to use the `integrateddynamics:menril_logs` tag now.
