### ISSUE TITLE
Modded shears wont drop leaves ID

### ISSUE THREAD

**Issue by benbenlaw** [CyclopsMC/IntegratedDynamics#1107]
#### Issue type:

- :bug: Bug <Modded shears wont drop leaves ID>

____

#### Short description:

Modded shears wont drop leaves ID

#### Steps to reproduce the problem:

Install a mod such as tinkers that adds the kama tool to collect leaves
break leaves destorys the block, should drop as a block
this behaviour is the same with other modded shears like wooden shears and ceramic shears

https://github.com/SlimeKnights/TinkersConstruct/issues/4655#issuecomment-965580240>

1. ...

#### Expected behaviour:

leaves broken are collectable

____

#### Versions:

- This mod: 1.10.4
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by benbenlaw** [comment]
No problem, fix i belive would be to change the loot tables to accept "tag": "forge:shears" instead of "item": "minecraft:shears"
