### ISSUE TITLE
Crafting Jobs are not closed

### ISSUE THREAD

**Issue by Rundas01** [CyclopsMC/IntegratedDynamics#1108]
#### Issue type:

- :bug: Bug

#### Short description:

Crafting Jobs are not closed when the results are brought back into the system via auto output to the Crafting Interface from machines.

#### Steps to reproduce the problem:

-Get a machine which auto outpus (like Gregtech ones)
-auto output into the attached Crafting Interface
-see that after importing, the Job is not closed

#### Expected behaviour:

the crafting job should be closed

#### Versions:

- This mod: Dynamics: 1.1.11, Tunnels: 1.6.14, Crafting: 1.0.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Gregtech: 1.17.1.770

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.12 is not supported anymore. This should be fixed in MC 1.16.

**Comment by Rundas01** [comment]
How unfortunate that 1.12 does not receive fixes anymore.
