### ISSUE TITLE
You can mutate crafting recipes in the Logic Programmer /w JEI

### ISSUE THREAD

**Issue by t0suj4** [CyclopsMC/IntegratedDynamics#1109]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you add the recipe to the Logic Programmer Recipe grid via JEI you can remove ingredients from the actual recipe because it's working with the recipe reference, not the copy! When you remove the items the final result is a recipe without valid ingredients which in the end defaults to ItemStack.EMPTY. You can then use any crafting table with cleared grid to craft unlimited amount of any craftable items. I've tested it only on crafting table results.

Offending line here (needs .copy(), probably):
https://github.com/CyclopsMC/IntegratedDynamics/blob/b621d9c23c086674b48749bb7a5492e534a18500/src/main/java/org/cyclops/integrateddynamics/core/logicprogrammer/ValueTypeRecipeLPElement.java#L210

I did not test it with liquids nor RF, changing output item have no influence.

#### Steps to reproduce the problem:

1. Open Logic Programmer
2. Select Recipe
3. Select desired item in JEI with crafting table recipe
4. Clear any ingredient that does not use ore dictionary from the recipe
5. Close Logic Programmer
6. Open Crafting Table
7. Put any item in the Table
8. Clear the grid
9. Unlimited free crafting
10. ???
11. Profit

I've tested it only on Iron, Diamond block and piston recipes. With piston, I've removed only Iron Ingot from the recipe, I could then craft Pistons without Iron Ingots.

#### Expected behaviour:

The item recipe should not get modified!

____

#### Versions:

- This mod: 1.10.3
- Minecraft: 1.16.5
- Forge: 36.2.8

I've tested it in OceanBlock modpack, without isolating anything.

**Comment by rubensworks** [comment]
Thanks for reporting!
