### ISSUE TITLE
1 damage with player simulator

### ISSUE THREAD

**Issue by linkanred** [CyclopsMC/IntegratedDynamics#1110]
#### Issue type:

- :bug: Bug 

____

#### Short description: 
So no mater what weapon I set in the player simulator or how I set it in there it does just 1 damage and doesn't apply any of the benefits form that weapon like enchantment it has on it. Also with blood magic the sacrificial sword doesn't auto kill or give lp when killed. All right click effects seems to work like watering cans ect but the left click effects of weapons seems to not be working and I have tried every possible combination of values when setting it up. (have not tried with multiple items just single item) 

#### Steps to reproduce the problem:

1. 

#### Expected behaviour:

____

#### Versions:

- This mod:  integrateddynamics 1.10.4
- integrated tunnels 1.8.7
- Minecraft: 1.16.5 
- Forge: 36.2.9

#### Log file:

`

**Comment by rubensworks** [comment]
@linkanred Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by linkanred** [comment]
Oops sorry I think I fixed it this time

**Comment by rubensworks** [comment]
Thanks, could you also include mod (both ID and IT) and Forge version?

**Comment by rubensworks** [comment]
Also, does this also occur with just vanilla weapons?

**Comment by linkanred** [comment]
It seems to be all weapons form my test and what I have seen on YouTube as well.

https://youtu.be/R0gAEX34qjg (about 13 mins in) 

https://youtu.be/9kUpWNX4gEY (about 3mins in)

**Comment by rubensworks** [comment]
And what is your integrated tunnels version?

**Comment by linkanred** [comment]
Add I was testing it on ocean block but in the first YouTube video I shared direwolf20 is playing on direwolf20 modpack news version and running into the seem problem which makes me think it's not just ocean block.

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedTunnels/commit/37c044612caecf2dcd5a7f8b55579f97fdc1a383
