### ISSUE TITLE
Autocrafting seems to freeze up and get stuck with multiple writers and one crafting interface.

### ISSUE THREAD

**Issue by dyc3** [CyclopsMC/IntegratedDynamics#1111]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Autocrafting seems to freeze up and get stuck with multiple writers and one crafting interface.

Screenshots: https://imgur.com/a/EU3diNn

#### Steps to reproduce the problem:

1. Set up a single crafting interface with a crafting table.
2. Attach 2 or more crafting writers.
3. Set up the interface and writers like how the tutorial teaches you for each available crafting writer (all recipes should have mutually exclusive ingredients).
4. It is not necessary for "Ignore storage" to be enabled on the writers.
5. Place a crafting job terminal to monitor crafting jobs.
6. Provide the necessary ingredients to start crafting for both jobs.
7. See that eventually all crafting jobs get stuck on the "Queuing" phase

#### Expected behaviour:

Autocrafting should function as long as necessary ingredients are available.

____

#### Versions:

- This mod: 1.10.4
- Minecraft: 1.16
- Forge: 36.2.9
- Modpack: FTB Oceanblock 1.7.0 (also opened: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/346)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Are you using the latest Integrated Crafting version?
Does this also occur without any other mods installed?

**Comment by dyc3** [comment]
Integrated Crafting: 1.0.20
Modlist: https://www.modpackindex.com/modpack/38362/ftb-oceanblock

**Comment by rubensworks** [comment]
Does this also occur without any other mods installed?

**Comment by Raidobw2** [comment]
Hi! I have a similar bug that causes a deadlock that was reported by another user on the FTB Modpack Tracker. It's linked to autocrafting as well, this could be related.
Would you want a separate issue for it, or is here ok?
I'll interact with you this time so that you can have the information you ask for. Thanks in advance for letting me know!

**Comment by rubensworks** [comment]
@Raidobw2 A new issue would be great, thanks!
