### ISSUE TITLE
Bug Squeezer

### ISSUE THREAD

**Issue by castilio20** [CyclopsMC/IntegratedDynamics#1115]
#### Issue type:
- :bug: Bug 
Squeezer doesnt work like how is supos to work
____

#### Short description:
clicking with a menril log doesnt work

#### Steps to reproduce the problem:
clicking with a menril log 

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.6
- Minecraft:  1.16.5
- Forge: forge-1.16.5-36.2.20

https://user-images.githubusercontent.com/76228548/145690435-c15775a8-2fd6-4f8a-abf7-2ecc7f88a797.mp4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you include some more details on the steps to reproduce the problem? Because what you wrote down is working fine for me.

Also make sure to try without any other mods installed.

Video doesn't work for me.

**Comment by castilio20** [comment]
![2021-12-12_03 06 29](https://user-images.githubusercontent.com/76228548/145709884-97a372f3-75e9-403d-975a-254ed7c53709.png)
i tested on a new world flat and worked but in my survival world doesnt work
somthing wrong with the pic?

**Comment by rubensworks** [comment]
So it looks like another mod in your pack is breaking things, I recommend removing mods from your pack until you have found the offending one.
FYI, the Performant mod is known to break many other mods.

Feel free to comment here once you found the offending mod, as this may help other people in the future.

**Comment by castilio20** [comment]
i found the issue is the dank storage it doesnt let you use the squeezer if you have that in inventory
