### ISSUE TITLE
crashed while making the powered squeezer

### ISSUE THREAD

**Issue by castilio20** [CyclopsMC/IntegratedDynamics#1116]
#### Issue type:
- :bug: Bug 
crashed while making the powered squeezer

____

#### Short description:
i tried to make  the powered squeezer
i think the issue was that the battery had some energy

#### Steps to reproduce the problem:

use a battery with energy ot sure
1. ...

#### Expected behaviour:

not crash?
____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.6
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.20

#### Log file:
[crash-2021-12-11_13.50.34-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/7697794/crash-2021-12-11_13.50.34-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
