### ISSUE TITLE
Squeezer bug bc of dank storage

### ISSUE THREAD

**Issue by castilio20** [CyclopsMC/IntegratedDynamics#1117]
#### Issue type:
Sorry but i wanted to be sure that you know about this so i re post this
- :bug: Bug 

____

#### Short description:
i found the issue is the dank storage it doesnt let you use the squeezer if you have that in inventory
https://www.curseforge.com/minecraft/mc-mods/dank-storage
without that in inventory works normal

#### Steps to reproduce the problem:
to have a dank storage in the inventory

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.6
- Minecraft: 1.16.5
- Forge:  forge-1.16.5-36.2.20
- dank storage dankstorage-3.16

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by castilio20** [comment]
and wanted to know when the next update would be the battery crash is a little annoying i cant craft the energy squeezer and can't place the battery i think you fixed that in dev

**Comment by rubensworks** [comment]
Could you also report it to the dank storage issue tracker? Perhaps it is not fixable on our end.

**Comment by castilio20** [comment]
done
https://github.com/Tfarcenim/Dank-Storage/issues/149

**Comment by rubensworks** [comment]
Seems to be fixed in Dank Storage.
