### ISSUE TITLE
Corrupted Network! (Seemingly Random, but I've got logs)

### ISSUE THREAD

**Issue by DEWSTREAMING** [CyclopsMC/IntegratedDynamics#1121]
#### Issue type:

- :bug: Bug 

____

#### Short description:

All of my networks on a server display "Corrupted Network!" and don't function at all, in order to fix I had to physically break the cables and exporters/readers/simulators and replace them. In some cases it let me use exactly the same variables, in one situation it wouldn't let me reuse the variable cards but it may have been a misplaced reader on my end for that specific case.

#### Steps to reproduce the problem:

1. I am not sure what would cause this. Our server has it's fair share of crashes, and this hasn't happened after any of those in the past, I also don't play 24/7 and not everyone on the server uses networks, so sadly I don't know specifically which logs and crash reports are responsible for causing this. We also frequently update our server. We are playing ATM 6 and have gone through just about all of the updates and never noticed this issue before.

#### Expected behaviour:

The networks should not Corrupt and should continue to work as normal.

____

#### Versions:

- This mod: Not sure if they are all needed or change anything, but I've got a few Integrated mods
IntegratedDynamics- 1.10.6
IntegratedCrafting- 1.0.20
Integratednbt- 1.4.2
IntegratedTerminals- 1.2.11
IntegratedTunnels- 1.8.9

- Minecraft:  1.16.5
- Forge: 36.2.22

#### Log file:
This folder contains crash reports and logs from this new year, I believe on the 2nd (in australia for me) the networks were working, and then I noticed on the 3rd (yesterday) that it was now corrupted, so fingers crossed something in the recent logs show something.
[corrupted logs.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/7805854/corrupted.logs.zip)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by DEWSTREAMING** [comment]
If those logs show nothing helpful, I do have a heap of logs from 2021 it was just I believe the issue never happened in that year. I could somehow be mistaken though. These are also server logs, if you also needed client logs for whatever reason I could do that too.

**Comment by rubensworks** [comment]
This seems to indicate that that for some reason the network data on your server is getting corrupted (like upon a crash). Normally, even after a crash, the network data should still be stored. So I think there may be a mod in your pack that may be causing data storage issues.

In any case, if this occurs, placing/removing just one cable in the network should be sufficient, as this recreates the whole network.

Note to self: we could add a mechanism to let cables self-reset if they detect a corrupted network.

**Comment by DEWSTREAMING** [comment]
Oh wow! Somehow I didn't try that, that is such a time saver, thank you! My dumb brain was breaking every cable
