### ISSUE TITLE
Materialized custom operator does not update value, while non materialized does

### ISSUE THREAD

**Issue by gtokarz** [CyclopsMC/IntegratedDynamics#1123]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. My custom operator filters recipe list by doing simple inventory contents comparision with recipe inputs and get first recipe. On the screenshots below I have 2 displays 1 have this operator non materialized second has it materialized. The moment items enters inventory only non materialized one updates, whilte I have to cause network update i.e via cable placement to get materialized one to update
![image](https://user-images.githubusercontent.com/12443385/148638255-b7191189-2983-4daf-b6b4-89fdb862b549.png)
![image](https://user-images.githubusercontent.com/12443385/148638266-a5e87be5-796e-4515-8a98-a55aa0c4bf2b.png)

#### Expected behaviour:

Materialized one should update as well

#### Versions:

- This mod: 1.10.6, integrated crafting: 1.0.20, integrated tunnels: 1.8.9, integrated terminals: 1.2.11
- Minecraft: 1.16.5
- Forge:  36.2.22

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by gtokarz** [comment]
Small update, narrowed down the problem to this piece:
![image](https://user-images.githubusercontent.com/12443385/148639662-b5747f90-f4d5-4ab2-a122-929e9a01f323.png)
Input Items coming from proxy which has Inventory Reader Items in it from the chest. I have made 2 test variables:
apply(Item, IsCurrentInputItem) and apply(Item, MaterializedsCurrentInputItem), they behave differently (same as in initial report desc)

**Comment by gtokarz** [comment]
Minimal reproduction
Chest with Inventory Reader,
Proxy with Items read from chest

Variable 1: Operator: List Contains 
Variable 2: Proxy Card
Variable 3: apply(Variable2, Variable1)
Variable 4: materialize(Variable3)
Variable 5: Item(Cobblestone)

TestValue1: apply(Variable5, Variable3)
TestValue2: apply(Variable5, Variable4)
![image](https://user-images.githubusercontent.com/12443385/148640813-74a7dd76-60d6-4106-ad36-fb52ebcb146e.png)

![image](https://user-images.githubusercontent.com/12443385/148640765-41892518-cc94-4140-88f3-f71df92229c7.png)

Also I have noticed that eventually materialized test value swtiches to correct one, but after over 1min or so (not sure what caused it)

**Comment by rubensworks** [comment]
So actually the expectation is wrong here.
Since you're materializing a list, it should actually *always* remain static.
The fact that it _sometimes_ changes is actually a bug. Will fix that in a bit.
