### ISSUE TITLE
[1.12.2] IndexOutOfBoundsException when right-clicking a facaded terminal/tunnel/cable

### ISSUE THREAD

**Issue by Desempregago** [CyclopsMC/IntegratedDynamics#1124]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Place the cable/tunnel/terminal
2. Place Facade on the cable
3. Try to right click the facaded block a few times

#### Expected behaviour:

Nothing breaking or exploding on my face

____

#### Versions:

- Integrated Dynamics: 1.1.11
- Integrated Terminals: 1.0.14
- Integrated Tunnels: 1.6.14
- Integrated Crafting: 1.0.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2860

#### Log file:

https://pastebin.com/J4jFYDGm

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Desempregago** [comment]
[Quick "showcase"](https://streamable.com/7gv3ma)

**Comment by rubensworks** [comment]
Unfortunately, the 1.12 versions are not being maintained anymore (1.16 and 1.18 are being worked on atm). I would recommend updating to 1.16.
