### ISSUE TITLE
Advancement triggers broken

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#1125]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

Upon world join, players seem to be given many ID advancements, which is incorrect.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Flanks255** [comment]
they appear to still be broken, this happened upon making a oak plank. 
![image](https://user-images.githubusercontent.com/32142731/151715809-978e6324-924f-4947-9d42-3fd6d237d83f.png)
though before, it was 3 advancements, now its pretty much all of them.
