### ISSUE TITLE
SERVER TPS TOO LOW

### ISSUE THREAD

**Issue by laoguo520140** [CyclopsMC/IntegratedDynamics#1126]
Dear Author:
Hello, I would like to report a question about "Integrated Dynamics", especially "Player Simulator", once used too much, the TPS of the server will become very low, I hope you can optimize it. This is very important for both the server and the client. thanks
Game version 1.16.5
FORGE version: 36.2.23
Mod version: 1.10.6
The following is the SPARK log of my server:
https://spark.lucko.me/8DvPTK3qNo

**Comment by rubensworks** [comment]
<img width="935" alt="Screenshot 2022-01-26 at 14 17 31" src="https://user-images.githubusercontent.com/440384/151169780-d15b9207-c010-4aba-84d9-ab87646fd9b7.png">

The acceleration wand of not enough wands seems to be causing your TPS issues.
