### ISSUE TITLE
Question Facades

### ISSUE THREAD

**Issue by Drackion** [CyclopsMC/IntegratedDynamics#1127]
#### Issue type:

- :question: Question 

____

#### Question:

How do you change the facade texture?
I have tried following the tooltip but haven't been able to set a texture for my facades.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by Drackion** [comment]
Forgot to mention that I am on the 1.16.5 version of the mod

**Comment by rubensworks** [comment]
If the steps from the tooltip don't work, then there's either a bug, or you're doing something wrong.

Can you try without any other mods installed?

**Comment by Drackion** [comment]
Ok I will try that when I have the time

**Comment by Drackion** [comment]
Tested it works once i isolate the integrated dynamics mods, i will try a bug report with the modpack devs of the pack that i am playing, this isn't the first time for MC1.16.5 that facades so there just may be some mod in common that causes this issue across the packs i play

**Comment by rubensworks** [comment]
Thanks! :-)

**Comment by LMelaia** [comment]
Didn't see any fixes or workarounds for this, and the bug isn't very high priority sadly.
So, I went and created a KubeJS script that adds a bunch of recipes to craft facades from common blocks and any other blocks added to the scripts block list. It's not perfect but at least it does make facades usable again, until this gets fixed.
Script Gist: [facade_recipes.js](https://gist.github.com/LMelaia/b93a5b72a2f5d3be417581cb814b4430)
