### ISSUE TITLE
[Question] How to trigger a crafting by redstone pulse

### ISSUE THREAD

**Issue by ryuujo1573** [CyclopsMC/IntegratedDynamics#1128]
#### Issue type:

- :question: Question 

____

#### Question:

Hi, I am a normal player and I was wondering how can I implement that **whenever I push a button, the specified crafting will be performed.**

Here was the case:
![image](https://user-images.githubusercontent.com/16525512/151664325-076e7420-729a-4553-b6d4-103000592a00.png)
// The "machine" to interact with

![image](https://user-images.githubusercontent.com/16525512/151664376-88d0f57b-4c13-4123-a6ab-c8ad636bfedd.png)
// I made it to crafting in a terminal, (like how it goes in the guidebook) (?) in this way.

p.s. Is that a feature in request or some special technique that I am innocent to?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by ryuujo1573** [comment]
Thank you for all your work.

**Comment by rubensworks** [comment]
You can do this using Integrated Crafting: https://www.curseforge.com/minecraft/mc-mods/integrated-crafting
(it also adds a manual section to the book when you install it)

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/integrated-crafting">Attention Required! | Cloudflare</a></strong></div></blockquote>
