### ISSUE TITLE
Crash when breaking network

### ISSUE THREAD

**Issue by MinoCraft** [CyclopsMC/IntegratedDynamics#113]
Hello o/

I'm playing with Integrated dynamics and I've crashing when I breaked the redstone writer. You can see crash report [here](http://pastebin.com/hrNe0Yq0)

Thanks in advance !

**Comment by rubensworks** [comment]
I need more information on how to reproduce this.
The situation that caused the crash, can you reproduce that yourself?
If so, please provide me with more details on that.

**Comment by rubensworks** [comment]
@MinoCraft Could you please provide more information? Closing this issue otherwise because I can't reproduce it.
