### ISSUE TITLE
mc1.18.1-forge39.0.64 ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)

### ISSUE THREAD

**Issue by GodMeowIceSun** [CyclopsMC/IntegratedDynamics#1131]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I try to use map to make a recipe list and map to the input item list, there is an abnormal tick and an abnormal crash

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

When I try to use map to make a recipe list and map to the input item list, there is an abnormal tick and an abnormal crash

____

#### Versions:

- This mod: IntegratedDynamics-1.18.1-1.10.8
- Minecraft: 1.18.1
- Forge: 39.0.64

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by GodMeowIceSun** [comment]
wow, The repair is too fast! :D
