### ISSUE TITLE
[1.18.1] Crash when accessing Block Reader

### ISSUE THREAD

**Issue by enigmaquip** [CyclopsMC/IntegratedDynamics#1133]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crashing when opened while attached to blocks with nbt data. I believe is this related to changes in forge 39.0.45

> 39.0.45 Remove references to the now-broken `BlockEntity#save(CompoundTag)` method (#8235)
https://github.com/MinecraftForge/MinecraftForge/pull/8235

#### Steps to reproduce the problem:

1. Place Block Reader on a block with nbt data (in this crashlog a Brewing Stand)
2. Add cable to put on network
3. Open Block Reader

#### Expected behaviour:

____

#### Versions:

- This mod: 
IntegratedDynamics-1.18.1-1.10.9
CyclopsCore-1.18.1-1.13.0
CommonCapabilities-1.18.1-2.8.2
- Minecraft: 1.18.1
- Forge: 39.0.75

#### Log file:

https://pastebin.com/UR66BQ5A

**Comment by rubensworks** [comment]
Thanks for reporting!
