### ISSUE TITLE
Crash when trying to automate the drying basin with Integrated Crafting.

### ISSUE THREAD

**Issue by AmandaCameron** [CyclopsMC/IntegratedDynamics#1134]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When trying to automate the drying basin with Integrated Crafting using the Crafting Interface, I ended up with a crash on world load, I'm not sure if this is a bug in IC or ID, but since the crash bubbles from ID so I'm filing here.

#### Steps to reproduce the problem:

1. Attach a crafting interface to a drying basin (Note: Not Mechanical Drying Basin)
2. Add a recipe variable card for 1000mB of crystal fluid -> crystal block
3. Reload world
4. Fireworks!

#### Expected behaviour:

The world to at least load with this (invalid?) recipe

____

#### Versions:

- This mod: 1.10.10
- Minecraft: 1.18.1
- Forge: 39.0.75

#### Log file:

https://paste.ee/p/Cli0F

**Comment by rubensworks** [comment]
Thanks for reporting!
