### ISSUE TITLE
Facades are transparent to light even when emulating non-transparent blocks 

### ISSUE THREAD

**Issue by changhe3** [CyclopsMC/IntegratedDynamics#1136]
#### Issue type:

- :question: Question 

____

#### Question:

Is this the intended behavior? Is it possible then to make facades non-transparent?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Sounds like a bug. Could you open a bug report with all required information?
