### ISSUE TITLE
Facades are transparent to light even when emulating a non-transparent block

### ISSUE THREAD

**Issue by changhe3** [CyclopsMC/IntegratedDynamics#1137]
#### Issue type:

- :bug: Bug 

____

#### Short description:
I'm building a mob spawner in a compact machine, where the walls emit light. Facades simply won't block the light.

![2022-02-23_19 49 53](https://user-images.githubusercontent.com/14080480/155314166-510c7fce-03fc-4733-9a72-49842e08d611.png)
![2022-02-23_19 50 01](https://user-images.githubusercontent.com/14080480/155314189-8ddc0cae-035e-4790-a312-7ca01ba87577.png)

____

#### Versions:

- This mod: 1.10.6
- Minecraft: 1.16.5
- Forge: 36.6.26, All the Mods 6

**Comment by rubensworks** [comment]
Thanks for reporting!
