### ISSUE TITLE
Audio Writer TTS Never Stops

### ISSUE THREAD

**Issue by Targren** [CyclopsMC/IntegratedDynamics#1138]
#### Issue type:

- :bug: Bug 

____

#### Short description:

"Text To Speech" output on the audio writer doesn't stop. Ever. Even after closing the world and going back to the main menu. Have to close the game completely. 

First experienced in Stoneblock 1.11, confirmed in test instance with only InDy (w/dependencies) and JEI

#### Steps to reproduce the problem:

1. Attach Audio Writer to a Network
2. Create Crafting card with a simple text string (I used "Alert!" since I was trying to make an alarm for my fission reactor)
3. Place String card into "Text" aspect of Audio Writer
4. After sound plays, remove string card. Continues repeating the string over and over and...

#### Expected behaviour:

Expected it shut up when you take the card out. PLEASE, make it stop!

____

#### Versions:

- This mod: 1.16.5-1.10.7
- Minecraft: 1.16.5
- Forge: 36.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!
