### ISSUE TITLE
Add the ability to change a ready-made list

### ISSUE THREAD

**Issue by DrSigma4164** [CyclopsMC/IntegratedDynamics#1140]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Add the ability to change a ready-made list, that is, if I made a squeak of 23-cell items, so that I can just change it by adding another item to the same list, and not re-create the whole list, especially if it is very long.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I guess this is the same as #357 (or at least a part of it)? Merging it into that one.
