### ISSUE TITLE
Intersection of lists A and B

### ISSUE THREAD

**Issue by DrSigma4164** [CyclopsMC/IntegratedDynamics#1141]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:
Add an operator that will select only the elements common to the two lists. That is, the Intersection of lists A and B.
Or if it will be too difficult to implement then the operator who simply tells whether there is at least one mpilny element in both lists.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by shadow7412** [comment]
I've proposed an implementation of this at #1224.

**Comment by shadow7412** [comment]
This has been completed (cc: @rubensworks)
