### ISSUE TITLE
Crash with Quark on world load

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/IntegratedDynamics#1143]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Run ID with Quark and Quark Oddities
2. Try loading a world
3. Crash

#### Expected behaviour:

World loads and is playable

____

#### Versions:

- This mod: 1.10.7
- Minecraft: 1.16.5
- Forge: 36.2.30

#### Log file:

[Crash Log](https://bytebin.lucko.me/wi3tkyR67i)

**Comment by rubensworks** [comment]
Thanks for reporting!
