### ISSUE TITLE
Network reader `value` aspect erroring on relog

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1145]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Network reader's `value` aspect cannot read from display panels when the server loads/starts (e.g. singleplayer relog). See before/after relog images below.

Issue initially reported on the discord: see [this message](https://discord.com/channels/386052815128100865/386054223688630272/952496429572694066) in `#integratedmods` by `@PlushBean`. The following steps and test were independently developed, so it is possible that the bug reported there is distinct to this one, but it does appear to have the same effects.

#### Steps to reproduce the problem:

1. Create a card that has its value based on some other card, e.g. `base = 100` and `related = identity(base)`. Place `base` in a variable store, and `related` in a display panel connected to the variable store. This is the "source" network.
2. Place a network reader on the source network's display panel. Keeping the network separate to the source network, connect a display panel to the network reader; this is the "display" network. Put a card with the `value` aspect of the reader into the display panel.
3. Relog

Before relog:
![image](https://user-images.githubusercontent.com/15624876/158055261-3349c2af-af46-4f58-a148-d747676f4792.png)
(Left: `100` card in display panel. Right: `100` card in variable store, `identity(100)` in display panel.)

After relog:
![image](https://user-images.githubusercontent.com/15624876/158055350-1bf9c1a0-1472-42ec-a3a1-56bd71aaafe7.png)
(same setup)

Display network display panel UI after relog:
![image](https://user-images.githubusercontent.com/15624876/158055308-a0dfe030-2d12-4312-834a-cde7c4e67bed.png)

Network reader UI after relog:
![image](https://user-images.githubusercontent.com/15624876/158055321-9452fc36-1a01-4f15-9b72-b2cb75a499b5.png)

Additional observations:
Causing a 'network update' (such as attaching/removing a component or cable, or taking the card out and placing it back in) on the display network after the error has occurred resolves the error. Network updates on the source network do not resolve the error on the display network.
Connecting the source and display networks together does not cause the error to occur, possibly because any network updates on the source network now cause the display network to update.

#### Expected behaviour:

No error occurs, or resolves itself. Possibly, network updates on the source network should be registered by the network reader on the display network, and cause a network update on the display network?

____

#### Versions:

mod | version
--- | ---
MC | 1.16.5
InTu | 1.8.9
InTu Compat | 1.8.9
Cyclops Core | 1.12.1
Common Capabilities | 2.8.0
Forge | 36.2.0
InDy | 1.10.7
InDy Compat | 1.10.7
InCr | 1.0.20
InTerm | 1.2.12
InTerm Compat | 1.2.12
InREST | 1.1.5

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
