### ISSUE TITLE
[1.16.5] Recipes added to mechanical squeezer are weird

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1146]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Allow first ingredient in squeezers recipes to not have 100% chance. This makes it impossible to use this machine in modpacks to handle squeezer/centrifuge-like recipes that have only one item output that is not 100% chance. 
Good example would be Wither Bee that produces comb that has 20% of producing Nether Star.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Hiranus** [comment]
There is also this https://github.com/KubeJS-Mods/KubeJS/issues/297 that I created. seems like there is some weird stuff happening with recipes.

**Comment by rubensworks** [comment]
Are you creating these recipes via vanilla json recipe files, or via KubeJS?

**Comment by Hiranus** [comment]
Recipes in KubeJS issue were created by their scripts and there is all sorts of wrong stuff happening.
I think that they wanted to do workaround for the issue I reported here. which backfired. 
About this ticket issues they were created via vanilla datapack. Here is the code for it:
`{
    "type": "integrateddynamics:mechanical_squeezer",
    "item": "minecraft:acacia_leaves",
    "result": {
        "fluid": {
            "fluid": "integrateddynamics:liquid_chorus",
            "amount": 50
        },
        "items": [{
            "item": "minecraft:ender_pearl",
            "chance": 0.400
        },
        {
            "item": "minecraft:ender_pearl",
            "chance": 0.400
        }]
    },
    "duration": 15
}`
![obraz](https://user-images.githubusercontent.com/6943031/158798177-dfc477eb-f406-424c-a899-83ea99545b9d.png)
![obraz](https://user-images.githubusercontent.com/6943031/158798241-b2fc54f4-4074-474d-b682-b04c2c2cbabd.png)

Hopefully this will be easy change for you, that can still be released for 1.16.5 which will, in turn, allow KubeJS team to make their support for your amazing mod work properly.

By the way, if you want some quicker exchange please reach me on your discord, I have nick Hiran there.

**Comment by rubensworks** [comment]
Thanks for the input. Changing this to a bug report.

**Comment by Hiranus** [comment]
Another Update - when I tested it in the actual machine it seems like it's JEI that's telling lies. Same script, and rarely I don't get ender pearl but amount of chorus that is in the tank increases, which means that machine handles recipe properly.

**Comment by rubensworks** [comment]
Looks like it was just a bug with the JEI integration indeed. New release coming soon. Thanks for figuring this all out @Hiranus! :-)

**Comment by Hiranus** [comment]
When new release @rubensworks ?

**Comment by rubensworks** [comment]
First need to fix one other bug, not sure by when that will be done.
