### ISSUE TITLE
Can not set a negative offset in effect writter

### ISSUE THREAD

**Issue by ad9836** [CyclopsMC/IntegratedDynamics#1148]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I am attempting to set a negative offset in the effect writer, but can not as the writer does not accept negative values.

I even tested this in a new modded environment with only Integrated Dynamics. Cyclops Core, and Common Capabilities installed and still had the issue

#### Steps to reproduce the problem:

1. Place an effect writer
2. Go to any effect and modify the properties
3. Attempt to set a negative offset
4. Fail to do so

![image](https://user-images.githubusercontent.com/8286065/159998786-96e7b86f-8672-4f28-85b2-a4691a8d4e5c.png)

#### Expected behavior:

I would expect to be able to use negative offsets since I need the particles in the negative Z direction
____

#### Versions:

- This mod: IntegratedDynamics-1.18.1-1.10.12
- Cyclops Core-1.18.1-1.13.2
- Common Capabilites-1.18.1-2.8.2
- Minecraft: 1.18.1
- Forge: 39.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!
