### ISSUE TITLE
Where to add files for adding json recipes

### ISSUE THREAD

**Issue by auroraveon** [CyclopsMC/IntegratedDynamics#1149]
#### Issue type:

- :question: Question 

____

#### Question:

I was reading the documentation for adding recipes to machines with json and I'm confused as to where I should be putting the files for the recipes. I'm trying to override the magma block recipe from the mechanical drying basin.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
It just follows standard vanilla datapack files: https://minecraft.fandom.com/wiki/Data_pack

<blockquote><img src="https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bc/Wiki.png/revision/latest/zoom-crop/width/200/height/200?cb=20211226202340" width="48" align="right"><div>Minecraft Wiki</div><div><strong><a href="https://minecraft.fandom.com/wiki/Data_pack">Data pack</a></strong></div><div>The data pack system provides a way for players to further customize their Minecraft experience. Data packs can be used to override or add new advancements, dimensions, functions, loot tables, predicates, recipes, structures, tags, world generation settings, and biomes without any code modification. Data packs can be placed in the .minecraft/saves/(world)/datapacks folder of a world. Each data pack is either a sub-folder or a .zip file within the datapacks folder. After it is in the folder, a da</div></blockquote>
