### ISSUE TITLE
1.11.2 Missing Crafting Recipes

### ISSUE THREAD

**Issue by Kriptikz** [CyclopsMC/IntegratedDynamics#115]
Version 1.11.2-0.6.5 
Tested on Forge 2206 & 2216

Missing Recipes: Logic Cable, Variable Store, Drying Basin, Squeezer, Menril Torch.

The blocks/items still exist in game and work but JEI doesn't have a recipe for them. I checked out version 1.10.2 to see what the recipes are, wrote them down, and attempted manual crafting back on version 1.11.2. The blocks/items still didn't craft.

I solved this problem by getting your shaped.xml and shapeless.xml file from here:

https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.11/src/main/resources/assets/integrateddynamics/recipes/

I put shaped.xml into "config/integrateddynamics/"  and all the recipes became visible & craftable except the Menril Torch. I then got your shapeless.xml and also put it in "config/integrateddynamics/" and the Menril Torch recipe still didn't appear or work. Looking over your lastest update to shaped.xml is seems some oredict recipe entries were changed, like the entry stick_wood changed to stickWood but the Menril Torch recipe in shapeless.xml didn't get updated. So I updated it and all these items now have recipes in JEI and are craftable.

**Comment by rubensworks** [comment]
Thanks for bringing this to my attention, I'll look into it.

Related to #108
