### ISSUE TITLE
Can not craft facades

### ISSUE THREAD

**Issue by mayday00** [CyclopsMC/IntegratedDynamics#1151]
once I have the Blue facade block I cannot combine it in a crafting table with any other block to make it look like that block.
![Image2](https://user-images.githubusercontent.com/83885185/162115575-6818fedc-791c-49e2-9f70-6c687e73bc2a.jpg)

Modpack: All The mods 7 version  0.2.42

mod version: IntegratedDynamics-1.18.1-1.10.10

**Comment by rubensworks** [comment]
Could you try without any other mods installed?

Does it occur with all types of blocks? Or just that one?

**Comment by mayday00** [comment]
I have tried it with lots of different blocks. and because its a server I cant uninstall mods

**Comment by mayday00** [comment]
I did  some googling around and found that other people were having the same issue. in mod packs like All The Mods 6

**Comment by rubensworks** [comment]
Can't reproduce this on my end unfortunately.
So it must be caused by another mod in your pack (probably a mod that somehow tweaks recipes).
I would suggest reporting this with your server admin or pack creator.
