### ISSUE TITLE
Huge FPS lag on client - down to single digit

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1155]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Recently I updated my ATM 6 server to version 1.8.22 from 1.8.20 and I noticed that in this latest release I have huge FPS issues with or without optifine. It seems that there are problems when stuff from this mod and EnderChests are close together.

#### Steps to reproduce the problem:

Build this and watch your fps die.
![obraz](https://user-images.githubusercontent.com/6943031/163567382-d9f3a57d-5702-48e8-b7e4-a8f1514655a9.png)

#### Expected behaviour:

No fps lag.
____

#### Versions:

- This mod: 1.10.8
- EnderChests: 1.7.12
- Minecraft: 1.16.5
- Forge: 36.2.31

#### Log file:
Without Optifine: https://spark.lucko.me/YCCRJdhnk2
With Optifine: https://spark.lucko.me/vQRKMJAo2p
Those profiles are from client, it seems like there is no impact on server.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Hiranus** [comment]
And here is how it looks: https://gfycat.com/saltyboringborderterrier

<blockquote><img src="https://thumbs.gfycat.com/SaltyBoringBorderterrier-size_restricted.gif" width="48" align="right"><div><img src="/assets/favicons/favicon-96x96.png" height="14"> Gfycat</div><div><strong><a href="https://thumbs.gfycat.com/SaltyBoringBorderterrier-size_restricted.gif">Unknown 2022.04.15-14.16 GIF | Gfycat</a></strong></div><div>Watch and share Unknown 2022.04.15-14.16 GIFs on Gfycat</div></blockquote>

**Comment by rubensworks** [comment]
Hmm, I was afraid this might happen, probably caused by this change: https://github.com/CyclopsMC/IntegratedDynamics/commit/d2246651e570373700abb8b45ee5de2165709bbc
In any case, the good news is that I know exactly why the performance issue occurs here.
Not sure yet if I should just revert that change, or try to optimize it (which might be tricky, as it gets to the internals of MC rendering).

@Hiranus If I give you a new dev build with some optimizations, would you be willing to test this build in your world?

**Comment by Hiranus** [comment]
Yes, obviously. You will have to wait ~2h for results as I have to do some shopping.

**Comment by rubensworks** [comment]
No worries, I won't have time to prepare a fix at right this instance though, likely later this weekend :-)

**Comment by Hiranus** [comment]
@rubensworks now I also noticed that I get over 500 ms spike when placing/breaking cable, and call stack in spark looks similar.
https://spark.lucko.me/BBR9jpBFew

<blockquote><img src="https://spark.lucko.me/assets/logo-inverted-512.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers and proxies.</div></blockquote>

**Comment by rubensworks** [comment]
Yep, looks like it has the same cause.

**Comment by Hiranus** [comment]
I got even weirder thing that connects to this issue.
![obraz](https://user-images.githubusercontent.com/6943031/163602105-f108111c-39a4-45a2-a794-63d3c56380c0.png)
when I dig and place those 2 dirt blocks I get this:
https://spark.lucko.me/f6fkn56rpz
But if I go somewhere where there are no ID cables in proximity everything seems fine. It seems like that piece of code is executed when I do anything close to ID cables.

<blockquote><img src="https://spark.lucko.me/assets/logo-inverted-512.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers and proxies.</div></blockquote>

**Comment by rubensworks** [comment]
Implemented a fix, and it seems to resolve all issues on my end.
Will make a new release soon. Please let me know if it wouldn't fully resolve the problem on your end.

**Comment by Hiranus** [comment]
It works. It not only fixed areas that had spike lags but also other places that had lower fps than normal. Great job.

**Comment by rubensworks** [comment]
Excellent, thanks for checking.

**Comment by Hiranus** [comment]
Yes, obviously.


pt., 15 kwi 2022, 16:05 użytkownik Ruben Taelman ***@***.***>
napisał:
