### ISSUE TITLE
1.18.2 Bug with Recipes

### ISSUE THREAD

**Issue by enigmaquip** [CyclopsMC/IntegratedDynamics#1158]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://user-images.githubusercontent.com/6134440/165440556-44a1372c-81b3-47cc-86d7-f08619104e75.png)
Recipes using forge tags display errored and are uncraftable

#### Steps to reproduce the problem:

1. ... Add InDy

#### Expected behaviour:

____

#### Versions:

- This mod: 1.10.13    
- Minecraft: 1.18.2
- Forge: 40.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by enigmaquip** [comment]
I believe this is related to the 40.0.18 and 40.0.36 changes, if that helps?

**Comment by rubensworks** [comment]
That is weird, I'm not aware of any tag renames. Will have to have a deeper look into this.

**Comment by enigmaquip** [comment]
Awesome, thanks!
