### ISSUE TITLE
Full block facades don't act as full blocks

### ISSUE THREAD

**Issue by LindaJuffermans** [CyclopsMC/IntegratedDynamics#1159]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using (full) facade blocks, they are not acting as full blocks. Vanilla and other walls do not connect to them like they do with full blocks. On the right is the original Chisels block, on the left is the ID facade which uses the Chisels block:
![image](https://user-images.githubusercontent.com/31929183/165575653-20a2a708-9b60-45d2-9b32-2061dbc02e39.png)

#### Steps to reproduce the problem:

Place some Logic Cables and cover them with facades. Place vanilla walls against them.

1. ...

#### Expected behaviour:

Ideally, the facaded blocks should behave like the block used to craft the facade. Vanilla walls will connect properly to the used block itself but not to the ID facade with the block.
____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.9.jar
- Minecraft: 1.16.5
- Forge: 36.2.34

**Comment by rubensworks** [comment]
Thanks for reporting!
