### ISSUE TITLE
Feature: Operators for manipulating Lists

### ISSUE THREAD

**Issue by shabble** [CyclopsMC/IntegratedDynamics#116]
Currently there doesn't appear to be a way to create a List except through `filter`ing an existing one, or manually creating one in the Logic Programmer.

I think it should be possible to do quite a lot with `Append(List, Any) -> List`, and maybe `Concat(List, List) -> List`, but my FP isn't the best, so discretion advised :-) A `head` and `rest` accessors might be nice, but `get` and `filter` can maybe already do that?

Checked against version 1.10.2-0.6.6, and no obvious features of this sort discovered.

**Comment by rubensworks** [comment]
Will be included in next update. I've also added a fun new operator that allows you to create infinite lists...
