### ISSUE TITLE
1.18.2 Client connection lost when connecting to server

### ISSUE THREAD

**Issue by Legonzaur** [CyclopsMC/IntegratedDynamics#1161]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Me and my friends can't connect to my server, getting Connection Lost : 
`Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location:`

This issue occurs when the only mods installed are IntegratedDynamics, Cyclops Core and CommonCapabilities too.
![image of crash](https://i.imgur.com/3pLZ4jh.png)
#### Steps to reproduce the problem:

1. Install mod on client and server
2. Connect to server

#### Expected behaviour:

____

#### Versions:

- This mod: CommonCapabilities 2.8.2, Cyclops Core 1.13.5, IntegratedDynamics 1.10.14
- Minecraft: 1.18.2
- Forge: 40.1.0

#### Log file:

https://paste.ee/p/mZLNj

**Comment by rubensworks** [comment]
Thanks for reporting!
