### ISSUE TITLE
Recipe issue when creating new world

### ISSUE THREAD

**Issue by Haddadmj** [CyclopsMC/IntegratedDynamics#1162]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A world will not create when integrated dynamics installed. "All Integrated Mods"

#### Steps to reproduce the problem:

1. Install Forge "Latest"
2. Installed Integrated Mods "Dynamic, tunnels, crafting,Terminals"
3. Create World
4. error with datapack related to integrated Mods

#### Expected behaviour:

it should create the world

____

#### Versions:

- This mod: 1.10.13
- Minecraft: 1.18.2
- Forge: 40.1.2

[Mods installed](https://prnt.sc/-0bEINSJtRog)

#### Log file:

[Log File](https://pastebin.com/mZw774r3)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You seem to not be using the latest version. Updating should fix the problem.

**Comment by Haddadmj** [comment]
> You seem to not be using the latest version. Updating should fix the problem.

Forge or the mod ?

**Comment by Haddadmj** [comment]
> You seem to not be using the latest version. Updating should fix the problem.

Curseforge App Didn't listed the latest version to be able to installed it. Needed The site
