### ISSUE TITLE
Integrated Dynamics + Create = Crash

### ISSUE THREAD

**Issue by octylFractal** [CyclopsMC/IntegratedDynamics#1164]
#### Issue type:

- :bug: Bug

____

#### Short description:

In conjunction with mods that create moving machines, e.g. Create, moving Integrated Dynamic's cables causes a crash.

Crash message for searchability: java.lang.IllegalStateException: Could not find a part container at DimPos(level=minecraft:overworld, blockPos=BlockPos{x=-2, y=64, z=33}, worldReference=null)

#### Steps to reproduce the problem:

1. Install Create
2. Add a cable part (e.g. reader, writer, importer, interface, exporter) that will get moved and have it be actively doing something so it's being checked by the network.
3. Start the create contraption.
4. Game crashes as seen in the log.

Setup I used:
Rotary Chassis on top, then Mechanical Bearing (don't forget to apply slimeballs to make it sticky!), and finally a Creative Motor. Chest being read by an Inventory Reader, and variable displayed so it's being used. Right-clicking the Mechanical Bearing will cause the crash.
![repoduction](https://url.octyl.net/krk4-hq6oxsiap8mxtlg)

#### Expected behaviour:
The cable should be moved by Create without crashing.

#### Versions:
- This mod: IntegratedDynamics-1.18.2-1.10.16
- Minecraft: 1.18.2
- Forge: 40.1.19

#### Log file:
https://gist.github.com/octylFractal/1878cd283062a82b72fc393a5d04dc90

#### Additional Information
I tried to fix this myself on Create's end by (re)moving their `world.removeBlockEntity` call, but because Create serializes all block entities, this resulted in item dupe bugs. I believe it is most correct to fix Integrated Dynamics so that it doesn't require the block entity to be present to properly clear itself from the network; instead that should perhaps be done in the block entity's `setRemoved` method to ensure proper clean up in all cases.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
We indeed don't have support yet for frame mods. We have an issue open for this though: #443
So I'm merging this issue here into that one.
