### ISSUE TITLE
squeezer loses recipe for string from wool after 1-2 uses

### ISSUE THREAD

**Issue by Sunekaer** [CyclopsMC/IntegratedDynamics#1166]
#### Issue type:

- :bug: Bug 

____

#### Short description:

after squeezing wool to get string the recipe goes away and the squeezer won't produce string, the recipe also goes away in JEI.

#### Steps to reproduce the problem:

1.  put wool in squeezer
2. squeeze the wool by jumping on it
3. get 2-4 string
4. put wool in squeezer again
5. squeeze the wool by jumping on it
6. get 0-2 string
7. put wool in squeezer again
8. squeeze the wool by jumping on it
9. either get 1 or nothing

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.10.16
- Minecraft: 1.18.2
- Forge: 40.1.19

#### Log file:
https://pste.me/v1/paste/FN1sIat3pvo/raw

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by flarefluffsune** [comment]
I'm actually having the same issue with the Squeezer but with Blaze Rods on the All the Mods 7 pack. I use the squeezer once to get blaze powder from a blaze rod and then the recipe stops working even JEI registers there's no recipe.
![image_2022-05-16_191857984](https://user-images.githubusercontent.com/20187367/168657187-65d381d9-667a-434e-9133-cc3d0c97dae0.png)

I'm using Forge 40.1.19, All The Mods 7 pack version 0.3.22
