### ISSUE TITLE
Crash after attempting to automate a mechanical drying basin

### ISSUE THREAD

**Issue by Maxwell45** [CyclopsMC/IntegratedDynamics#1167]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After trying to automate a mechanical drying basin with a crafting interface the world seems to crash without any way to open it back up. Moreover, this issue seems suspiciously similar to https://github.com/CyclopsMC/IntegratedDynamics/issues/1134 but not patched in the 1.16 version of CyclopsCore

#### Steps to reproduce the problem:

1. Attach a crafting interface to a mechanical drying basin
2. Add a recipe variable card for 1000mB of crystal fluid -> crystal block
3. Attempt to remove the mechanical drying basin with a wrench
4. Crash

#### Expected behaviour:

World continues working.

____

#### Versions:

- This mod: 1.10.10
- Minecraft: 1.16.5
- Forge: 36.2.34

#### Log file:

https://bytebin.lucko.me/McsRGzPcY0

**Comment by rubensworks** [comment]
Thanks for reporting!
