### ISSUE TITLE
IntegratedDynamics crashes server - Crafting Interface

### ISSUE THREAD

**Issue by HeyItzGeo** [CyclopsMC/IntegratedDynamics#1168]
#### Issue type:

- :bug: Bug 

____

#### Short description:

playing on TNP Limitless 5's offical servers and this mod has been noted by admins for crashing the server, the client is crashes randomly when attempting to request a chest to be crafted from inside a terminal

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge: 

#### Log file:
https://pastebin.com/zzzxpDYn

<!--Don't paste contents here directly, but use something like

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by HeyItzGeo** [comment]
log updated*
