### ISSUE TITLE
Energy Battery causes needless block updates while charging/discharging

### ISSUE THREAD

**Issue by codewarrior0** [CyclopsMC/IntegratedDynamics#117]
While in use, the Energy Battery issues up to 20 chunk updates per second, causing a corresponding FPS drop, especially in busy areas where the battery is likely to be used.

The fault can be traced back to unconditional calls to [`world.notifyBlockUpdate`](https://github.com/CyclopsMC/CyclopsCore/blob/master-1.9/src/main/java/org/cyclops/cyclopscore/helper/BlockHelpers.java#L130) via [`CyclopsTileEntity.onSendUpdate`](https://github.com/CyclopsMC/CyclopsCore/blob/master-1.9/src/main/java/org/cyclops/cyclopscore/tileentity/CyclopsTileEntity.java#L125) so this is probably not the only block that causes needless block updates.

```
IntegratedDynamics-1.10.2-0.6.6.jar
CyclopsCore-1.9.4-0.9.0.jar
```

**Comment by rubensworks** [comment]
Thanks for mentioning this, I've been a bit too careless with these `sendUpdate` calls...
I'll go through the different mods that use them to have a look which ones can be removed.
