### ISSUE TITLE
AutoOutput from Iron Furnaces furnace into ID interface voids items

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1170]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Seems like automatic pushing if items into ID cables can cause items deletion.

![obraz](https://user-images.githubusercontent.com/6943031/169689021-9b54fb45-9e52-4040-84cb-5a088e99d25e.png)
For some reason this setup voids outputs from unobtanium furnaces. It seems that automatic pushing of items into ID cables is the problem (cables delete some/most of the items). 
![obraz](https://user-images.githubusercontent.com/6943031/169689114-cd00b6a7-c270-41cb-b552-2dc599340e01.png)
Similar setup but with ender chests instead of cables has no issues.

#### Steps to reproduce the problem:

1. Either build setup shown above or download world with it already built by me (its in ATM6)
    https://www.file.io/QTRc/download/eiZDqVWIlcEh
2. Order large amount of items to be crafted (those furnaces can do stack/tick so go with something like 100k at least)
3. Check RS crafting monitor and you will see that everything went ok.
4. Change output ender chests to ID cables as its on the screenshot above and repeat step 2.
5. Checking crafting monitor will show you that system is waiting for large amount of sand, but crafting will be already finished.

#### Expected behaviour:

Items are not deleted when auto pushed into ID cables.

____

#### Versions:

- This mod: 1.10.10
- Minecraft: 1.16.5
- Forge: 36.2.34

But I recommend that you try to recreate it with ATM6 modpack in version 1.8.24. Save I prepared above also uses this exact version. It is simpler to setup than bunch of mods.

#### Log file:
There is nothing interesting in the log.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Hiranus** [comment]
Some explanation that I forgot to add. Ender Chests are not mandatory here, but its more or less how my setup looks in my main world. In fact setup with netherite barrel works exactly the same, and bug is still there.
![obraz](https://user-images.githubusercontent.com/6943031/169690387-acaee317-f869-4565-813f-87b5dda92134.png)
Applied Energistics 2 also doesn't have any issues with voiding items:
![obraz](https://user-images.githubusercontent.com/6943031/169690487-6fc35b75-41b1-4816-a899-fc9b9a5e5d61.png)

**Comment by Hiranus** [comment]
Update - It seems that raising priority on the item interface that is connected toender chest to be highest in the network fixes this problem.

**Comment by rubensworks** [comment]
Placing the interfaces like that without priorities can cause items to be inserted into any of the other interfaces. So in this case, an item that is ejected from a furnace may be pushed into another furnace.

If items are voided, then it seems like these furnaces accept items as input (on the right-hand side), but they are voided.
(You may be able to test this by placing item exporters directly on the right-hand side of the furnaces, and seeing if they are indeed voided, in which case it's a bug in the furnaces mod you're using)
ID/IT should not be able to void items on their own.

**Comment by Hiranus** [comment]
I will report it to IronFurnaces.
![obraz](https://user-images.githubusercontent.com/6943031/169692620-08f640d3-098a-4f7c-bfcd-163111523052.png)
