### ISSUE TITLE
Recipes using Facade (None) show up in too many jei categories

### ISSUE THREAD

**Issue by rdellison** [CyclopsMC/IntegratedDynamics#1172]
#### Issue type:

- :bug: Bug 

____

#### Short description:

looking up jei recipes for most blocks show that create automated shapeless crafting can combine it with Facade - None to make Facade- None.  So can Minecolonies Assistant cook, farmer, fletcher, glassblower, mechanic, planter, carpenter, and stonemason.
It does not show up in the normal Crafting menu.

#### Steps to reproduce the problem:

1. .lookup jei uses for almost any block (minecraft dirt, integrated dynamics generator, ...)

#### Expected behaviour:

no combining with Facade - None recipes showing up for jei block uses.

____

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.10.17
- Minecraft: 1.18.2
- Forge: 40.1.20
- JEI: 1.18.2-9.7.0.195

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I assume there is a mod in your pack that adds these JEI entries for the ID facade, because ID itself does not add these JEI entries (you can confirm this when you only have ID in your pack).

I would suggest identifying this mod in your pack, and reporting it to the mod author.
