### ISSUE TITLE
Game crashes when entering invalid character for a tag in the logic programmer

### ISSUE THREAD

**Issue by Sanzath** [CyclopsMC/IntegratedDynamics#1173]
#### Issue type:

- :bug: Bug 

____

#### Short description:

In the logic programmer, (mis)typing an invalid character for a tag variant for a recipe ingredient crashes the game.

#### Steps to reproduce the problem:

1. Open the logic programmer
2. Open the Recipe constant menu
3. For one of the ingredients, shift-click to configure
4. Check the "tag variants" box
5. Type "tin ingots"

Since tags aren't supposed to contain spaces, this fails catastrophically and the game crashes with the following error:
```
The game crashed whilst rendering screen
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:tin 
Exit Code: -1
```
The proper tag would have been "ingots/tin", but I forgor 💀

#### Expected behaviour:

The selection box for the tag becomes empty or the input rejects the invalid character.

____

#### Versions:

- This mod: 
  - IntegratedTerminals-1.18.2-1.2.16
  - IntegratedCrafting-1.18.2-1.0.22
  - IntegratedDynamics-1.18.2-1.10.17
  - IntegratedTunnels-1.18.2-1.8.11
- Minecraft: 1.18.2
- Forge: 40.1.20

(This was only reproduced with the ATM7 modpack, however I don't see how any mod conflicts or configurations could have caused it.)

#### Log file:

https://pastebin.com/3REDQFj5

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest ID version, it has already been fixed.
