### ISSUE TITLE
Energy capacity display overflow in Integrated Dynamics batteries

### ISSUE THREAD

**Issue by James103** [CyclopsMC/IntegratedDynamics#1176]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When many Integrated Dynamics batteries are crafted together then stacked, eventually, the energy capacity display in the tooltip may overflow as shown below:

Working (4 batteries, capacity 512 MFE each):
![image](https://user-images.githubusercontent.com/37945304/171957293-22b1f6b3-ca2e-4c2a-a6cb-5320ce99806a.png)

Broken (5 batteries, capacity 512 MFE each):
![image](https://user-images.githubusercontent.com/37945304/171957324-d36cf949-5d7e-4630-873e-f257889178a6.png)

#### Steps to reproduce the problem:

1. Get at least 2,560 (ideally: 4,096) Integrated Dynamics batteries of their base capacity.
2. Craft them, 8 for 1, into at least 320 Integrated Dynamics batteries, each with a capacity of 8 MFE.
3. Craft the batteries again, 8 for 1, into at least 40 Integrated Dynamics batteries, each with a capacity of 64 MFE.
4. Craft the batteries again, 8 for 1, into at least 5 Integrated Dynamics batteries, each with a capacity of 512 MFE.
5. Stack 4 of the resulting batteries in one stack. Notice in the tooltip that the capacity is the correct 2.048 GFE.
6. Add the remaining battery to the stack, making 5 in total. Notice in the tooltip that the capacity has changed to -1.734 GFE instead of the expected 2.560 GFE.

#### Expected behaviour:

Having five or more of those big (512 MFE) batteries in a stack should show the correct energy capacity of 2.560 GFE (displayed as "2,560,000,000 RF" in the tooltip).

____

#### Versions:

- Integrated Dynamics: 1.18.2-1.10.18
- Common Capabilities: 1.18.2-2.8.2
- Cyclops Core: 1.18.2-1.13.6
- Minecraft: 1.18.2
- Forge: 40.1.31

#### Log file:

https://paste.ee/p/BaZ19

**Comment by rubensworks** [comment]
Thanks for reporting!
