### ISSUE TITLE
Lag + invalid variable card when materializing certain operator cards

### ISSUE THREAD

**Issue by Sanzath** [CyclopsMC/IntegratedDynamics#1177]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Materializing certain variable cards, specifically operator cards created from a network reader's aspects, causes the materialized card to have no ID and cause lots of lag.

#### Steps to reproduce the problem:

1. Have a network with a network reader and a materializer. The network reader doesn't need to be pointing at any network.
2. In the network reader, create a variable card with the aspect "Network Count of Item"
3. Place that card in the materializer's top slot and an empty card in the bottom slot

The new card has no variable ID, doesn't seem to be usable, and causes a lot of lag until the card is cleared.

More generally, materializing any operator card which references the operator aspect card will cause the same issue (e.g. if it's used as part of a pipe operator).

#### Expected behaviour:

At least, it shouldn't cause any lag. I feel like the materialized card should simply be a copy of the original, however I can also see a case for the card not being allowed to be materialized if it's an operator aspect.

____

#### Versions:

- This mod: 1.10.17
- Minecraft: 1.18.2
- Forge: 4.1.20

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
