### ISSUE TITLE
Energy Battery bugged.

### ISSUE THREAD

**Issue by JakobYde** [CyclopsMC/IntegratedDynamics#1179]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When the energy battery is crafted, the bar is messed up. But then when it is placed, so is its current energy. This is set to Integer.Max_Value.
Besides this (as can be seen on the images), its textures are very weird. This only happens, when the actual battery is within FOV, also if it's behind other blocks.
You are very welcome to write me, when you find the issue, as I cannot seem to find it and I am curious.

![2022-06-10_17 56 04](https://user-images.githubusercontent.com/44023323/173109231-365a3543-eb9a-41ae-8e2f-37d79cda70db.png)
![2022-06-10_17 56 16](https://user-images.githubusercontent.com/44023323/173109233-a6e09461-5e39-4fcb-9d14-20ed67f2bd24.png)
![2022-06-10_17 56 27](https://user-images.githubusercontent.com/44023323/173109237-9a0f8698-7bdd-4054-8671-d0dc275ca4d9.png)
![2022-06-10_17 56 32](https://user-images.githubusercontent.com/44023323/173109240-1ad5728e-b8c7-4fe7-a401-f0094880091c.png)

#### Steps to reproduce the problem:

1. Craft Energy Battery
2. Place Energy Battery

#### Expected behaviour:

That it has 0 RF and no weird textures.
____

#### Versions:

- This mod: 1.18.2-1.11.0
- Minecraft: 1.18
- Forge: 40.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does this happen without any other mods installed?

**Comment by JakobYde** [comment]
> Does this happen without any other mods installed?

Yes, I just tried installing only integrated dynamics on curseforge and the same happened.

**Comment by Warhand** [comment]
Was just coming to report this same issue, glad to see its already been reported and is on the "to-do" list
