### ISSUE TITLE
"Check Stack Size" ignored when using Import/Export Items Predicate

### ISSUE THREAD

**Issue by Sanzath** [CyclopsMC/IntegratedDynamics#1180]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Item Importers and Item Exporters don't take into account the "Check Stack Size" property when the "Import/Export Items Predicate" aspect is used. Due to this, if an item has a quantity less than the "Item Transfer Rate" value, it will be moved regardless.

#### Steps to reproduce the problem:

1. Create a predicate variable card. A simple always-true one:
    * Create an Operator variable card with the value "General Constant" (`constant`)
    * Create a Boolean variable card with the value "True" (`true`)
    * Create a variable card `apply(constant, true)`, (`pred`)
2. Set up a simple network with 2 chests (one with an item interface, one with an item exporter), + variable store for the variables if needed
3. In the Item Exporter, place the predicate card in the "Export Items Predicate" aspect, then change the properties:
    * Item Transfer Rate = 5
    * Check Stack Size = True
4. Place less than 5 items in the chest connected by the item interface

The stack of less than 5 items will be transferred from the first chest to the destination.

If more than 5 items are in the chest, then 5 _will_ be transferred at a time, up until less than 5 are left, at which point those are moved as well.

The same can be seen with an item importer in place of the item interface, and an interface in place of the exporter.

#### Expected behaviour:

When less than "Item Transfer Rate" items are in the source chest, they are not moved.

____

#### Versions:

- This mod: 
  - IntegratedDynamics: 1.10.17
  - IntegratedTunnels: 1.8.11
- Minecraft: 1.18.2
- Forge: 40.1.20

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
