### ISSUE TITLE
Mechanical Drying basin deleting menril resin 1.18.2

### ISSUE THREAD

**Issue by Staegrin** [CyclopsMC/IntegratedDynamics#1181]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Mechanical drying basin deleting menril resin

#### Steps to reproduce the problem:

1. Have a squeezer outputting menril resin into a mechanical drying basin. 
![2022-06-17_19 24 31](https://user-images.githubusercontent.com/8494635/174350048-0943f94c-75c7-4f0f-b252-6213b828be20.png)

2. The basin will complete a cycle, use up the resin and not produce a block of crystallized menril. 
![2022-06-17_19 25 39](https://user-images.githubusercontent.com/8494635/174350078-a7e1c19c-691f-4fb2-aeb3-75470c0a0654.png)

3. A non mechanical drying basin will produce a block of crystallized menril.
![2022-06-17_19 28 18](https://user-images.githubusercontent.com/8494635/174350115-b8d890f2-2f56-4a05-b2d6-d0e1183a8247.png)

#### Expected behaviour:
For the mechanical drying basin to produce a block of crystallized menril.

____

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.11.2
- Minecraft: 1.18.2
- Forge: 40.1.47

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Staegrin** [comment]
Started a whole new instance with only JEI and Integrated dynamics The mechanical drying base produces one block of crystallized menril and then starts deleting the resin.
![2022-06-17_19 53 41](https://user-images.githubusercontent.com/8494635/174352175-e48981e1-8f83-46f1-bd6e-e98cac39278a.png)
![2022-06-17_19 53 52](https://user-images.githubusercontent.com/8494635/174352189-31ca0138-52b7-44cf-8ab7-27fac345a8f2.png)
![2022-06-17_19 54 38](https://user-images.githubusercontent.com/8494635/174352258-b4d63435-c803-41b3-9262-a293345dcc66.png)
