### ISSUE TITLE
Empty list in recipe crash "Invalid RecipeDefinition input, empty list for minecraft:itemstack"

### ISSUE THREAD

**Issue by Aazh** [CyclopsMC/IntegratedDynamics#1182]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crashes if an empty item list is used in a recipe variable on the input side.
Not quite sure how to describe it.
Came across it while making a chest + materializer based recipe variable making system.

#### Steps to reproduce the problem:

1. make an ingredients variable with one empty item
![image](https://user-images.githubusercontent.com/32171775/174452221-2b9ae652-9166-484b-9488-12e22e683d42.png)
2. make an empty list variable
![image](https://user-images.githubusercontent.com/32171775/174452269-151e0115-42ca-409f-a25d-852789985034.png)
3. make a second ingredients variable with Ingr.with_items using previously made variables
![image](https://user-images.githubusercontent.com/32171775/174452367-9170ec94-d2f7-4202-91d4-e4a61815e1c0.png)
4. make a recipe variable with Recipe.with_io using second ingredients variable in first (input) slot and first ingredients variable in second (output) slot
![image](https://user-images.githubusercontent.com/32171775/174452406-615d5acb-9310-47a1-8075-0a74c0063dbe.png)
5. put the first three variables in a variable store
![image](https://user-images.githubusercontent.com/32171775/174452447-651914d3-fa18-4980-bbc6-0e7bb444bc35.png)
6. put the recipe variable in a display panel connected to the variable store
![image](https://user-images.githubusercontent.com/32171775/174452518-33165bfd-5413-41a7-abb3-39bb0604883f.png)
7. crash
#### Expected behaviour:

Not to crash. Recipe could show up as a red X or empty.
____

#### Versions:

- Integrated Dynamics: IntegratedDynamics-1.18.2-1.11.3
- Integrated Terminals: IntegratedTerminals-1.18.2-1.3.0
- Integrated Tunnels: IntegratedTunnels-1.18.2-1.8.12
- Integrated Crafting: IntegratedCrafting-1.18.2-1.0.23
- CyclopsCore: IntegratedCrafting-1.18.2-1.0.23
- CommonCapabilities: CommonCapabilities-1.18.2-2.8.2
- Minecraft: 1.18.2
- Forge: 40.1.51

#### Log file:
https://pastebin.com/415YCA52

**Comment by rubensworks** [comment]
Thanks for reporting!
