### ISSUE TITLE
[Bug]: Random crash from IntegratedDynamics, IFacadeable.hasFacade()

### ISSUE THREAD

**Issue by TheonlyTazz** [CyclopsMC/IntegratedDynamics#1183]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Issue got reported on the FTB-Modpack issue Tracker and couldnt resolve it, requesting some help from the mod-dev in question.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/958

On seemingly random occasions, my client is crashing while attempting to render an Integrated Dynamics cable just at the edge of my render distance. The cable in question occupies only a single block and is connected to a Fluid Importer (placed on a Sink) and two Fluid Interfaces (connected to a Thermal Evaporation Plant and a Fission Reactor).

From where I'm standing, the cable isn't actually visible because it's completely behind the Thermal Evaporation Plant, so I'm not sure why it's trying to render it in the first place. The cable does not have a facade on it, though that probably wouldn't have stopped it from crashing.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.18-1.11.2
- Minecraft: 1.18.2
- Forge: 40.1.47

#### Log file:
https://github.com/FTBTeam/FTB-Modpack-Issues/files/8904251/crash-2022-06-14_16.19.25-client.txt

**Comment by rubensworks** [comment]
Thanks for reporting!
