### ISSUE TITLE
Could't use CraftTweaker to remove the recipes of Squeezer & MechanicalSqueezer.

### ISSUE THREAD

**Issue by Dark2932** [CyclopsMC/IntegratedDynamics#1185]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I can't use CraftTweaker to remove the recipes of Squeezer & MechanicalSqueezer.

#### Steps to reproduce the problem:

No matter what ZenMethod I use, it is always wrong.

#### Expected behaviour:

Removing the recipes successfully.

#### Versions:

- This mod:  IntegratedDynamics(1.1.11) CraftTweaker(4.1.20.674) 
- Minecraft: 1.12.2
- Forge: 2860

#### Log file:

ZS: https://paste.ubuntu.com/p/tJCbqc7z6T/
Log: https://paste.ubuntu.com/p/cC6XfPzXxJ/

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You're probably looking for `removeRecipesWithOutput`.

You can find more info on https://github.com/CyclopsMC/IntegratedDynamics/wiki/MineTweaker

<blockquote><img src="https://opengraph.githubassets.com/98be06be7b8ff8b807d64b31b32f59060087fa38d18c71c40bf0a19a132e61ec/CyclopsMC/IntegratedDynamics" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics">MineTweaker · CyclopsMC/IntegratedDynamics Wiki</a></strong></div><div>A Minecraft mod to take full and automated control of your appliances. - MineTweaker · CyclopsMC/IntegratedDynamics Wiki</div></blockquote>
