### ISSUE TITLE
Display Panel crash: java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by WestPrime** [CyclopsMC/IntegratedDynamics#1186]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft crashes after few seconds next to display panel

#### Steps to reproduce the problem:

1. Enable Optifine
2. Setup the system with frequently changing value (in my case, it was a sum or 3 block nbt readers with botania flowers)

#### Expected behaviour:

Not to crash
____

#### Versions:

- This mod: 1.16.5-1.10.10
- CyclopsCore: 1.16.5-1.12.4
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.34

#### Log file:

https://pastebin.com/1iF2FTPY

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Enable Optifine

There's your problem :-)

But in any case, a workaround here might be possible.
