### ISSUE TITLE
Recipe Problem 1.18.2

### ISSUE THREAD

**Issue by ShadowSeal5** [CyclopsMC/IntegratedDynamics#1188]
#### Issue type: Recipe Problem

- :question: Question 

____

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by ShadowSeal5** [comment]
like what file do I need to delete in order for it to realize new recipes have been added or what do I need to do

**Comment by rubensworks** [comment]
Not sure I understand the problem.

Are the ore processing recipes unavailable when you load an unmodified version of this mod?
Or do you encounter problems when overriding them via datapacks?
