### ISSUE TITLE
Omni-Directional Connectors wrong groups when crafting

### ISSUE THREAD

**Issue by MirceaZisu** [CyclopsMC/IntegratedDynamics#1189]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crafting omni-directional connectors can give group ID or not, depending on if you Shift + Click the crafting or drag it in a slot with the mouse. 

#### Steps to reproduce the problem:

1. Get 2 omni-directional connectors
2. Reset group by putting them in the same crafting table
3. Shift + Click the crafting output
4. Expected behavior would be that they are assigned to a group. They both keep no group, and assign to a new group each.

#### Expected behaviour:

If you drag the crafting output into a slot in your inventory, then close the crafting table interface, they are assigned to a group. 
____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

This is a test pack created from all Integrated Dynamics add-ons, and JEI.

#### Log file:

No logs, does not cause a crash.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I found the problem, but since 1.12 is not supported anymore, I'll only be able to provide a fix in the 1.16+ versions of ID.

Note to self: rewrite group-handling recipes using `SpecialRecipe`.
