### ISSUE TITLE
Regex groups error

### ISSUE THREAD

**Issue by elias098** [CyclopsMC/IntegratedDynamics#1190]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Using regex groups while having a group inside another optional group errors in console and deletes the display panel its in

#### Steps to reproduce the problem:

1. regex = string(^..((.))?)
2. string = string(11)
3. failingOperator = regexGroups(regex, string)

#### Expected behaviour:

Not console erroring and deleting parts

____

#### Versions:

- This mod: 1.10.11
- Minecraft: 1.16.5
- Forge: 36.2.34

#### Log file:

latest.log: https://pastebin.com/izczHWv7

**Comment by rubensworks** [comment]
Thanks for reporting!
