### ISSUE TITLE
Audio Writer - Custom Sounds

### ISSUE THREAD

**Issue by SteaSteaStea** [CyclopsMC/IntegratedDynamics#1191]
#### Issue type:

- :question: Question 

____

#### Question:

Hello,
I'm trying to use the the audio writer to play custom sounds which are loaded through a resourcepack.
I am able to play the sounds correctly through the /playsound command but when using a variable card with a string and an audio writer I cannot seem to get it to work. Playing a sound from other mods like Quark or vanilla sounds seems to work fine but the custom sounds which are loaded through a resourcepack do not play.

Am I doing something wrong or if they are not supposed to work would it be possible to add support for those? They seem to be loaded into the game and accessible through the /playsound command or certain other mods already which makes me wonder why the writer doesn't recognize them.

1.16.5 btw

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
> They seem to be loaded into the game and accessible through the /playsound command or certain other mods already which makes me wonder why the writer doesn't recognize them.

What mods are you referring to exactly?
Perhaps I can look into how they handle this.

**Comment by SteaSteaStea** [comment]
Ambience Blocks - https://www.curseforge.com/minecraft/mc-mods/ambience-blocks


<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/ambience-blocks">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Note to self:

Ambience blocks: https://github.com/SekaiRed/AmbienceBlock/blob/0f6659b1c73887e30be624a69e1bea3c3c810150/src/main/java/com/sekai/ambienceblocks/client/gui/ambience/ChooseSoundGUI.java#L181-L184
ID: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.16/src/main/java/org/cyclops/integrateddynamics/part/aspect/Aspects.java#L868-L870

<blockquote><img src="https://opengraph.githubassets.com/e1143eee4b5d2a7aac9368b1baf093914b34aff8ea4492832fa7a9c0641ed3e9/SekaiRed/AmbienceBlock" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SekaiRed/AmbienceBlock">AmbienceBlock/ChooseSoundGUI.java at 0f6659b1c73887e30be624a69e1bea3c3c810150 · SekaiRed/AmbienceBlock</a></strong></div><div>Contribute to SekaiRed/AmbienceBlock development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/ea0db3e11721c1e9613f0815713518b7126311a3ea233773ae5df044ae4da8a7/CyclopsMC/IntegratedDynamics" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics">IntegratedDynamics/Aspects.java at master-1.16 · CyclopsMC/IntegratedDynamics</a></strong></div><div>A Minecraft mod to take full and automated control of your appliances. - IntegratedDynamics/Aspects.java at master-1.16 · CyclopsMC/IntegratedDynamics</div></blockquote>

**Comment by rubensworks** [comment]
Should be fixed. Feel free to try out the latest dev build until this is released. (will require the latest CyclopsCore as well)
