### ISSUE TITLE
Config option to disable facades

### ISSUE THREAD

**Issue by Xetaxheb** [CyclopsMC/IntegratedDynamics#1192]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

An added common config to outright disable facades being added as blocks.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Disabling items/blocks is considered bad practise in mods. A better pattern is to disable recipes, which is already possible in this case using datapacks. Hope this helps.
