### ISSUE TITLE
Suggestion: Big Multiblock Display Panel

### ISSUE THREAD

**Issue by WestPrime** [CyclopsMC/IntegratedDynamics#1193]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Add a multiblock screen like here (https://tmonitoring.com/uploads/files/1523887952_492c7180695c.jpg), that acts like a hi-tech sign which can show some information from variables, because one-block display is too small for big numbers

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Duplicate of #273.
