### ISSUE TITLE
Some incompatibility?

### ISSUE THREAD

**Issue by TeKett** [CyclopsMC/IntegratedDynamics#1195]
I have no idea with what, but im 100% sure its not supposed to run this bad. Im playing ragnamod 6 and integrated dynamics runs abysmally slow, to the point its unusable since it makes the server freeze, sometimes infinitely.

Just having a 3 chest network causes 100 millisecond frame drops, and having about 30 or so causes server issues. Id like to have a hundred chests or so in my network, but that would probably just make it outright crash.

From some light testing:
The issue seems to be the logic cable. Adding a logic cable to a chunk adds about 5 ms frame drops, multiplied i some way per side connected, meaning that a 1x8 gives 40ms, 2x4 gives 80ms and 2x2x2 gives 120ms. 

The frame drops only happen if i add or remove anything thats within a 9x9 column to a logic cable. The frame drops are localized to the chunk only, and is also limited in vertical chunks. So it does not affect other chunks, nor more then 16 blocks up/down starting at water level. There seams to be some +1 happening, so the area is in fact overlapping one block into the other chunk, so its 17x17x17 big when comparing coordinates.

**Comment by rubensworks** [comment]
Doesn't sounds right indeed.

Can you give a bit more details on the issue though? It might have been better to use the "Performance" issue template, which provides details on mod versions and profiling logs.
