### ISSUE TITLE
[1.18.2]Game Crash when move cursor to fluid slot

### ISSUE THREAD

**Issue by ajacker** [CyclopsMC/IntegratedDynamics#1197]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

just place the machine and use it

1. ...

#### Expected behaviour:

When I move my cursor to the machine gui, the game crashed

____

#### Versions:

- This mod: 1.3.0
- Minecraft: 1.18.2
- Forge: 40.1.68

#### Log file:

https://pastebin.com/t2VGhY26

**Comment by rubensworks** [comment]
Thanks for reporting!
