### ISSUE TITLE
Squeezer can't handle Deepslate Coal ore 1.18.2

### ISSUE THREAD

**Issue by Staegrin** [CyclopsMC/IntegratedDynamics#1199]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The Mechanical or regular Squeezer can't process Deepslate Coal Ore. While it can handle all other Minecraft ores

#### Steps to reproduce the problem:

1. insert Deepslate Coal Ore into the squeezer
2. nothing happens
![2022-08-07_17 43 16](https://user-images.githubusercontent.com/8494635/183299302-b45c6394-a8b1-4b3d-a0b2-dc4c7b3b090c.png)

#### Expected behaviour:

6 to 7 coal being produced from one ore
____

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.11.7
- Minecraft: 1.18.2
- Forge: 40.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!
