### ISSUE TITLE
Part container could not be found crash

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [CyclopsMC/IntegratedDynamics#120]
http://pastebin.com/6iwL7zsr

Immersive Engineering: 0.10-54
CyclopsCore: 1.9.4-0.9.0

I realise these builds are out of date and the issue may have been fixed, if so could you please tell me where/when it was fixed so I can patch this in the above mod version (restricted by client version).

Thanks

**Comment by rubensworks** [comment]
Please provide me with step-by-step details on how to reproduce this.
This is not the first time I receive a crash report like this, but no one has been able to tell me what exactly caused the crash.

**Comment by rubensworks** [comment]
@Rob5Underscores Any more details?

**Comment by Rob5Underscores-zz** [comment]
Apologies for not responding sooner - saw the email at school and forgot to go back later.

Unfortunately, since this is a public server I have no idea what caused it as there are many players online. Although the issue is a less pressing matter for me as it has not occurred in a while.

Sorry for being of absolutely no help in debugging this.

**Comment by rubensworks** [comment]
Ok, I'm leaving this open for the time being.
If anyone else would experience this issue, please give me detailed instructions on the situation so that I can reproduce it.

**Comment by rubensworks** [comment]
This should be fixed thanks to 74f76a1b2793aaf1905bea2d20038e98ed2691f6.
If anyone else would encounter this issue after version `0.6.10`, please tell me here.
