### ISSUE TITLE
[Bug]: Crash in IntegratedCrafting while editing Recipe in JEI

### ISSUE THREAD

**Issue by TheonlyTazz** [CyclopsMC/IntegratedDynamics#1201]
#### Issue type:

- :bug: Bug 

____

#### Short description:

trying to create a recipe card in the Logic Programmer, to put in the crafting interface of IntegratedCrafting, and there seem to be multiple ways to crash the game while trying to preview a recipe in JEI with the portable logic programmer open and set to accept a new recipe

#### Steps to reproduce the problem:

1. open logic programmer. 
2. click Recipe to set it up to accept a new recipe from jei or dragging items to it
3. search in JEI for the item you want to add to a Recipe variable card
4. click the item in JEI so you can preview its ingredients before adding it to the logic programmer so the card can be programmed with it
#### Expected behaviour:

JEI opens up
____
#### Screenshots:

clicking this recipe will immediately crash the game
![2022-08-10_07 34 49](https://user-images.githubusercontent.com/1612570/183891496-67afe8b8-939b-48c3-b787-8cf5b9641b4d.png)
pressing 'u' to see the Uses of this ingot also immediately crashes the game
![2022-08-10_07 35 00](https://user-images.githubusercontent.com/1612570/183891561-589601ad-f8a0-4426-8ebf-acfa81700780.png)

#### Versions:

Minecraft Version: 1.18.2
Forge Version: 40.1.69

for reference the JEI version is 

- jei-1.18.2-forge-10.1.3.240

and the IntegratedMods versions are 

- IntegratedCrafting-1.18.2-1.0.23
- IntegratedDynamics-1.18.2-1.11.7
- IntegratedTerminals-1.18.2-1.3.0
- IntegratedTunnels-1.18.2-1.8.13

This has been tested with just those mods in a seperate instance, Issue first got reported on the FTB Modpack Issuetracker but can be replicated with just Integrated Dynamics + JEI
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1248

#### Log file:

https://pste.ch/alisacetun.pl
https://pste.ch/oweruhuruw.pl

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by TheonlyTazz** [comment]
Upon further testing, it seems that v10 of JEI removed some features that InDy is using:

met4000:
> (I'm coming from a discussion on the InDy discord server)
> 
> InDy seems to rely on features (in this case `mezz.jei.api.gui.IRecipeLayout.getFluidStacks()`) from v9 that are removed in JEI v10 - see [mezz/JustEnoughItems@530ef6c](https://github.com/mezz/JustEnoughItems/commit/530ef6c8d604370bef850f3656a28beab56cbfba)
> 
> Since there doesn't seem to be a beta or release version for JEI v10 in 1.18 on curseforge yet, I'm wondering if downgrading to the latest JEI release (v9.7.1.232, according to curseforge) would temporarily fix this until there's an official v10 release and mods like InDy update to the v10 API?
> 
> (I have not yet confirmed that this isn't also an issue using JEI v9.7.1.232, but this is the first we've heard of this bug on the InDy discord)

I have tested this with  JEI v9.7.1.232 and it seems to not be crashing anymore
