### ISSUE TITLE
[Bug] Machine crafting recipes are not loading on  v1.11.8

### ISSUE THREAD

**Issue by CKY-** [CyclopsMC/IntegratedDynamics#1204]
#### Issue type: machine crafting recipes no loading 
I have checked with the squeezer the drying basion and both mechanical variants  

there is a config error  but I dont see why that would stop the machines from being able to process items? as its a JEI error. 

- :bug: Bug 
```
 Failed to load: org.cyclops.integrateddynamicscompat.modcompat.jei.JEIIntegratedDynamicsConfig
```
____

#### Steps to reproduce the problem: 

1.update from 1.11.7 to 1.11.8 on Minecraft 1.18.2

#### Expected behaviour:

____

#### Versions:
the machines have the recipes working to craft mineral fluid
 

- This mod: 1.11.8
- Minecraft: 1.18.2 
- Forge: 40.1.68

#### Log file:
https://gist.github.com/CKY-/75f9a66e183db7773a2ecf6c5322a9b2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Are you sure you're using the latest JEI version?

**Comment by CKY-** [comment]
the current released version is 
7/19/2022 jei-1.18.2-9.7.1.232.jar Release 1.18.2
there is a beta version but i dont tend to subscribe to beta's  i will install 
8/17/2022 jei-1.18.2-9.7.1.255.jar Beta 1.18.2

and report back.

**Comment by CKY-** [comment]
```
[21Aug2022 02:58:12.163] [Render thread/ERROR] [mezz.jei.forge.util.AnnotatedInstanceUtil/]: Failed to load: org.cyclops.integrateddynamicscompat.modcompat.jei.JEIIntegratedDynamicsConfig
java.lang.NoClassDefFoundError: mezz/jei/forge/platform/PlatformHelper
	at org.cyclops.integrateddynamicscompat.modcompat.jei.JEIIntegratedDynamicsConfig.<clinit>(JEIIntegratedDynamicsConfig.java:47) ~[IntegratedDynamics-1.18.2-1.11.8.jar%23207!/:1.11.8] 
```
	
same error, using  jei-1.18.2-9.7.1.255

**Comment by rubensworks** [comment]
You'll need to install at least version 10 of JEI. Either that, or downgrade ID to the previous version.
