### ISSUE TITLE
Request certain crafts randomly causes server to hang

### ISSUE THREAD

**Issue by kirjorjos** [CyclopsMC/IntegratedDynamics#1205]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Setup an auto crafting system with multiple some, some chests, and some machines with an item importer.  (I'm not entirely sure if the number maters.)

2. Attempt to calculate a craft that would cause a machine with an item importer to be used. (Item importer may not be necessary, but thus far, I've yet to notice a hang that didn't use it)

#### Expected behaviour: It calculates the craft instead of hanging.

____

#### Versions:

- This mod: 
    Integrated Crafting: 1.0.22
    Integrated Dynamics: 1.10.11
    Integrated Terminals: 1.2.13
    Integrated Tunnels: 1.8.9
- Minecraft: 1.16.5
- Forge: 36.2.34
- Pack: Enigmatica 6 Expert version 1.4.1

#### Log file:
Watchdog crash one of the server moderators provided me: https://pastebin.com/fi9AHXy5
Successful calculation of the failed craft for that specific log: 
![image](https://user-images.githubusercontent.com/35607697/186891411-39ff8a20-edf0-4706-99d8-18240f5f6521.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Is `craftingPlannerEnableMultithreading` set to false on your server?

**Comment by kirjorjos** [comment]
I don't have access to the server files without asking a moderator unfortunately, but the integrated crafting config is blank on both my local world and the default config on the pack github, so more than likely whatever the default is.  I'll confirm if it's on or off when a mod is online.

**Comment by kirjorjos** [comment]
It is set to true.

**Comment by rubensworks** [comment]
There's your problem :)
