### ISSUE TITLE
Update "Crystalized Menril/Chorus" to the correct spelling "Crystallized Menril/Chorus"

### ISSUE THREAD

**Issue by Vorarose** [CyclopsMC/IntegratedDynamics#1206]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Please update the names so that they are the correct spelling as my AE2 search for the affix was coming up short and it was confusing to me. Thank you.

![index](https://user-images.githubusercontent.com/111662017/187049588-41d6faae-7a37-4e71-8149-124f0ea8a80a.png)

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Nevrai** [comment]
“Crystalized” means the same thing as “crystallized.” “Crystalized” is American English, and “crystallized” (or “crystallised”) is British English. https://www.thefreedictionary.com/crystalized

Nevertheless, I do prefer “crystallized” as I use British English, but “crystalized” isn’t incorrect.

<blockquote><img src="http://img.tfd.com/TFDlogo1200x1200.png" width="48" align="right"><div><img src="https://img.tfd.com/favicon.ico" height="14"> TheFreeDictionary.com</div><div><strong><a href="https://www.thefreedictionary.com/crystalized">crystalized</a></strong></div><div>Definition, Synonyms, Translations of crystalized by The Free Dictionary</div></blockquote>
