### ISSUE TITLE
[1.16.5]Objects are not moved

### ISSUE THREAD

**Issue by DrSigma4164** [CyclopsMC/IntegratedDynamics#1207]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I use the following scheme to sort items from one mod:
```
V1 = apply(String String Contains, String Mod_NAME)
V2 = pipe(Item mod, V1)
```
Accordingly, I put V1 and everything needed by V2 in the variable store, and V2 itself in the Filtering Item Interface.
However, if you remove and then put any variable card in the variable store, or unload a chunk, it does not move items there, although everything fits according to the filter.

#### Steps to reproduce the problem:
I tried to record the steps on video, if something is unclear, ask: https://imgur.com/a/PxYHjcv

#### Versions:

- This mod: 1.10.13
- Minecraft: 1.16.5
- Forge: 36.2.39

#### Log file:
Since the files are very large and I can't download them, I only copied from the time I played this bug.
latest: https://pastebin.com/Bj67TLWr
debug: https://pastebin.com/Q1fHytji

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by DrSigma4164** [comment]
I don't know what title to write. You can change it to whatever you want.

**Comment by rubensworks** [comment]
I don't understand the issue, can you clarify?

Does not filtering interface not work for any kind of predicate you put in it? Or just this predicate? Or does it cause issues after chunk unloading?

If it's a question specific to this predicate, it might be better to ask for help in the Discord channel.

**Comment by DrSigma4164** [comment]
This is a problem with any predicate. If I extract from the variable store some component that is needed for the predicate that is in the filter interface, and then insert it again OR unload this chunk / go to the world, then the predicate that is in the filter interface does not work, that is, it does not move objects.
Made another video demonstration, but more clearly. It shows how I tried to re-mark the item that corresponds to the filter, as can be seen in the first case. However, after I moved/drag and put the variable in the variable store it stopped moving the item that was previously moved. However, if you pull out the variable card in the filter interface and insert it again, it will work again.
https://imgur.com/a/JKVm6gV

<blockquote><img src="https://i.imgur.com/p3MkblT.jpg?fbplay" width="48" align="right"><div><img src="https://s.imgur.com/images/favicon-16x16.png" height="14"> Imgur</div><div><strong><a href="https://imgur.com/a/JKVm6gV">imgur.com</a></strong></div><div>Imgur: The magic of the Internet</div></blockquote>
