### ISSUE TITLE
1.18.2 - NBT not getting updated upon non-manual Item-removal

### ISSUE THREAD

**Issue by NerevarNamorax** [CyclopsMC/IntegratedDynamics#1208]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When an Item is removed by someone/something other than the player, the network is not updating the NBT data of the removed item,

#### Steps to reproduce the problem:

This Issue was noticed while I was building a machine to help me sort agricraft seeds.
The Network checks the item in the first slot of a minecraft chest, gets the NBT-data and uses a NBT-path to retrieve a specific value from the agricraft seed. (Here, I looked for the fertility value.)
The retrieved value is turned into an integer and put on a display.
Putting the agricraft seed in the correct slot, the display shows us the correct value for "fertility". It notices when the item is removed by me and updates the nbt accordingly.
The issue is that when the seed is removed by a hopper or InDy's Item Importer (or an another mod's item transportation pipe), the display is still showing the seed's data instead of "0", which it does when I manually remove the seed from the chest.
The network knows that the chest is empty and that there is no item. The NBT data however is not updated.

I tested it in a clean Instance of Minecraft (newly created world, the only mods installed are agricraft and InDy), and I can reliably reproduce the issue. Attached to this post is a zip-file containing the save and mod folders used in my Instance of minecraft.
When spawning into the world, there is a beach straight ahead with my test build. The variable cards should be in one of the two chests.
[TESTCRAFT.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/9440111/TESTCRAFT.zip).

#### Expected behaviour:

I expected the network to update the NBT the same way it does when I remove the seed manually and not by hopper or InDy pipe.

____

#### Versions:

- Involved mods:
	agricraft-1.18.2-3.1.4
	
	IntegratedTerminals-1.18.2-1.3.0
	IntegratedDynamics-1.18.2-1.11.8
	IntegratedCrafting-1.18.2-1.0.23
	integratednbt-1.18.2-1.5.1
	IntegratedTerminals-1.18.2-1.3.0
	IntegratedTerminals-1.18.2-1.3.0
	
	CommonCapabilities-1.18.2-2.8.2
	CyclopsCore-1.18.2-1.16.0
	infinitylib-2.1.4
	
- Minecraft: 1.18.2
- Forge:  40.0.1.0

#### Log file:

No crash happened

**Comment by rubensworks** [comment]
@NerevarNamorax Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
