### ISSUE TITLE
[Bug] [IntegratedCrafting] Capital Letters in "item tag variants" recipe variable crashes client.

### ISSUE THREAD

**Issue by Kanzaji** [CyclopsMC/IntegratedDynamics#1209]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Client crashes when trying to write any Capital letter in "item tag variants" text box of "Recipe" Variable.

#### Steps to reproduce the problem:

1. Open Logic Programer and choose "Recipe" Variable
2. Shift click any item slot.
3. Choose "item tag variants" checkbox
4. Try to write any Capital letter.

#### Expected behaviour:

Game shouldn't crash, and A) not allow to write capital letter B) transform it to non-capital letter C) just allow Capital letter being written.

#### Versions:

- IntegratedDynamics: 1.10.11
- IntegratedCrafting: 1.0.22
- Minecraft: 1.16.5
- Forge: 36.2.34 & 36.2.35
- Modpack: [Enigmatica 6 Expert 1.4.1](https://github.com/EnigmaticaModpacks/Enigmatica6)

#### Log file:

https://paste.ee/p/n22In -> Latest.log
https://paste.ee/p/KpoFV -> Crash log

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You're not using the latest ID version, could you try updating to the latest first?

**Comment by kirjorjos** [comment]
Still happens with InDy 1.10.14, tunnels 1.8.11 and crafting 1.0.22 with the only mods besides the 2 libs being jei

**Comment by kirjorjos** [comment]
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/9467173/latest.log)
[crash-2022-09-01_01.45.00-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/9467176/crash-2022-09-01_01.45.00-client.txt)
meant to upload these in my last comment, hit enter too soon

**Comment by rubensworks** [comment]
Thanks for checking!

**Comment by Kanzaji** [comment]
Ahh I wasn't fast enough 😅 Shouldn't go sleeping 😂
