### ISSUE TITLE
1.11.2-0.6.7 breaks dye crafting and block uncrafting

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/IntegratedDynamics#121]
there are no errors in either the server or client console.

1. install forge build 2224
1. install integrated dynamics and it's dependencies
1. provided it doesn't crash on you at startup (previously reported at https://github.com/CyclopsMC/CyclopsCore/issues/41)
1. try to craft bonemeal (fail, no output)
1. get ingots, make a block, uncraft block (fail, no output)

**Comment by rubensworks** [comment]
I also noticed some special recipes being borked, will have to look into that.
