### ISSUE TITLE
 Plz add forge:books tag to book

### ISSUE THREAD

**Issue by adamkad1** [CyclopsMC/IntegratedDynamics#1211]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Can the book get forge:books tag please, it doesnt fit into a bookshelf from another mod

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Done in #1225, thanks to @shadow7412!
