### ISSUE TITLE
Crash When Access Machine Reader GUI on a Drying Basin

### ISSUE THREAD

**Issue by tdaffin** [CyclopsMC/IntegratedDynamics#1212]
#### Issue type:

- :bug: Bug

____

#### Short description:

When you attach a Machine Reader to a Dying Basin or a Mechanical Drying Basin and then right click it to access the GUI Minecraft crashes

#### Steps to reproduce the problem:

1. Place a Drying Basin or a Mechanical Drying Basin
2. Place a machine reader on top of the machine.
3. Place a single logic cable on the machine reader so that you can right click it to access its GUI
4. Right click the machine reader to access the GUI
The GUI displays but Minecraft crashes shortly after.

#### Expected behaviour:

Minecraft does not crash

____

#### Versions:

- This mod: 1.11.10
- Minecraft: 1.19.2
- Forge: 43.0.8

#### Log file:

(https://pastebin.com/QikNdQh8)

**Comment by rubensworks** [comment]
Thanks for reporting!
