### ISSUE TITLE
Mystical Agriculture autocrafting bug

### ISSUE THREAD

**Issue by BrandonUSMC** [CyclopsMC/IntegratedDynamics#1213]
#### Issue type:

- :bug:

#### Short description:

When auto-crafting essences from mystical agriculture, it does not recognize that I have a master infusion crystal in the system. Instead it only looks to see if I have a normal infusion crystal (which is way less efficient and more costly over-all).

#### Steps to reproduce the problem:

1. Setup a storage system that contains a decent amount of inferium essence and a master infusion crystal.
2. Set up an auto crafting area connected to said storage system.
3. Use a portable logic programmer and set a variable card's recipe to craft Prudentium essence. (This takes 4x Inferium essence and an infusion crystal, regular **_OR_** master.
4. When you slot it in the crafting interface connected to the system and try to craft it, it will only look to see if you have the regular infusion crystal, it does not look to see if you have a master infusion crystal, and such will not craft it. 

#### Expected behavior:

If you try and auto craft the essence, the system should be able to recognize if you have the Master Infusion Crystal and use that for every essence you want crafted. 

____

#### Versions:

- This mod: 1.11.7
- Minecraft: 1.18.2
- Forge: I don't know, but the modpack version is 1.0.4 (All the mods 7 to the sky)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you try without any other mods installed, so we can rule out other mods that may break things?

**Comment by BrandonUSMC** [comment]
I dont know how to do that, im just playing the modpack and realized its not working

**Comment by rubensworks** [comment]
Might be better to first report this to your modpack author then.

Feel free to link back here.

**Comment by jstansel** [comment]
I see this happen on a 1.19.2 test world with only Integrated Dynamics and Mystical Agriculture. But I also had the crafting work as expected with a previous variable recipe card. I think the recipe may have some detail that I could not distinguish. This screen shot shows 2 plain infusion crystals missing even though I had provided a master infusion crystal.

![2022-10-04_23 00 01](https://user-images.githubusercontent.com/727927/193979634-66767b7f-c08f-4706-95be-221ea7369774.png)

Cucumber-1.19.2-6.0.2.jar
CyclopsCore-1.19.2-1.17.0.jar
IntegratedCrafting-1.19.2-1.0.26.jar
IntegratedDynamics-1.19.2-1.11.11.jar
IntegratedTerminals-1.19.2-1.3.3.jar
IntegratedTunnels-1.19.2-1.8.16.jar
jei-1.19.2-forge-11.3.0.262.jar
MouseTweaks-forge-mc1.19-2.23.jar
MysticalAgriculture-1.19.2-6.0.3.jar
Patchouli-1.19.2-76.jar
theoneprobe-1.19-6.2.2.jar

Forge: 1.19.2-43.1.1

**Comment by jstansel** [comment]
Update: I looked a little longer and a single craft is ok. The problem happens for me when requesting to craft 2 or more prudentium essence.

**Comment by rubensworks** [comment]
Has this already been reported to the modpack author? Or tested without other mods installed?
