### ISSUE TITLE
Crafting terminal Freezes my game

### ISSUE THREAD

**Issue by ishanpatil1** [CyclopsMC/IntegratedDynamics#1214]
I have been playing All the mods 7 to the sky modpack for a while now and for as far I can remember I've had an integrated dynamics storage system, but recently after I removed all my chests and added occultism storage and just crafted a powah reactor which successfully crafted  I tried opening my terminal and the game froze indefinitely, so I just restarted the game and tried to open the terminal again and the same result. This has happened almost 6-7 times now and now I am not able to play my world. If I could know what caused the issue I'd be really glad.

**Comment by rubensworks** [comment]
@ishanpatil1 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
