### ISSUE TITLE
Creat cuetsom Squeezer recipe problem

### ISSUE THREAD

**Issue by GalaxyOfZero** [CyclopsMC/IntegratedDynamics#1215]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hello im the Modpack Dev from SkyFriends, i have a problem with the Create a recipe for the Squeezer, for some reason i can not creat a recipe for the Squeezer with a output from fluid and i have no idea if this a code Problem or a Scripe Problem

#### Steps to reproduce the problem:

1.  https://pastebin.com/apW96dt1

#### Expected behaviour:

___

#### Versions:

- This mod: 1.16.5-1.10.15
- Minecraft: 1.16.5
- Forge: 36.2.39

#### Log file:
https://pastebin.com/cunKZqHL

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Probably a script error indeed. If I add your recipe via a regular recipe JSON file, it works just fine:

<img width="470" alt="Screenshot 2022-10-02 at 08 07 02" src="https://user-images.githubusercontent.com/440384/193440469-579229c4-43ed-45ac-8219-9e426f92d254.png">
