### ISSUE TITLE
Omni-Directional Controller doesn't work long distance

### ISSUE THREAD

**Issue by RasputanTheMad** [CyclopsMC/IntegratedDynamics#1219]
#### Issue type:

Error Message "The linked network could not be found"

____

#### Question:

Everything I have read says that when you have an Omni-Directional Controller hooked up to your storage network it will work anywhere, even in other dimensions. Unfortunately, I get the message "The linked network could not be found."

I am trying to figure out why this is happening.
![2022-09-28_12 43 05](https://user-images.githubusercontent.com/88071100/192863461-82911267-e977-455d-ae8e-9490f10a1c36.png)

**Comment by rubensworks** [comment]
Did you right-click with the terminal on your omni-dir connector?
And is your network chunk-loaded?
