### ISSUE TITLE
Player Simulator and Functional storage

### ISSUE THREAD

**Issue by AceDrago** [CyclopsMC/IntegratedDynamics#1227]
#### Issue type:

- :bug: Bug 

____

#### Short description:

when using a player simulator with a a functional storage drawer that has has tool in it say for instance an eternal iesnium fortune 7 pickaxe and the drawer is locked it will just dupe it.

#### Steps to reproduce the problem:

1. setup like modular router system for block placing and collecting
2. place the drawer locked with the enchanted pickaxe in it with no upgrades
3. place the cable for the item interface and player simulator
4. place item interface and player simulator
5. place iesnium ore in the router or a chest to place in front of the player simulator or manually place block

#### Expected behaviour:

The drawer is not suppose to gain a second or more pick upon simulator use and is suppose to let the drawers inventory count update to zero and not do it so fast it actually duplicates the item 
____

#### Versions:

- This mod: 1.11.11
- Minecraft: 1.18.2
- Forge: 40.1.80
- ATM7: 0.4.32

#### Note:
chatted on discord with a member from the modpack and was told to report to the mod authors

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does this mean that every time the player simulator ticks, that you gain an additional pick?

What happens if you remove the drawer lock? Does the problem still occur? If not, then this may be a problem with the functional storage mod, in which case it would be better to report this to their issue tracker (and link back to here).

**Comment by AceDrago** [comment]
i guess it got fixed because it is not doing it now so i tried it with upgrades in and out, for both locked and unlocked. so i guess it got fixed since the pack is now been updated
