### ISSUE TITLE
Mechanical Squeezer insert and extract inconsistencies

### ISSUE THREAD

**Issue by AHL67** [CyclopsMC/IntegratedDynamics#1228]
Hi,

In Integrated Dynamics 1.1.11 for MC 1.12.2, insertion and extraction of items in and from the Mechanical Squeezer are not consistent.
We can insert only from north, west and top, when we extract from these sides it's from input slots instead of output, and we can only extract output slots from south, east and bottom.

**Comment by rubensworks** [comment]
I'm sorry, but the 1.12 version is not being maintained anymore.
