### ISSUE TITLE
Integrated Dynamics 1.18.2 Recipe deleter. [Bug]

### ISSUE THREAD

**Issue by Crysis27** [CyclopsMC/IntegratedDynamics#1230]
I have been playing the All The Mods 7: To the sky modpack, and whenever I teach the Integrated Dynamics crafter a recipe, I can delete items required in that recipe.

How to Replicate: If you i.e. try to teach how to make a fishing rod, then delete one stick from the recipe, and use the R key to see the sticks recipe, then the reciper will erase all the sticks needed, resulting in only 2 string for making a Fishing Rod.

**Comment by rubensworks** [comment]
@Crysis27 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
