### ISSUE TITLE
Crafting Interface Multithreading

### ISSUE THREAD

**Issue by bangplaysgames** [CyclopsMC/IntegratedDynamics#1231]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

A multithreading option to crafting interfaces to allow it to input multiple ingredients into a machine without waiting for the outputs.  Having a "Crafting Threads: " value you can specify would be much more adaptable than the current option of making a recipe card that involves multiple inputs and outputs.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Sounds like the same suggestion in https://github.com/CyclopsMC/IntegratedCrafting/issues/6
