### ISSUE TITLE
Breaking Machines

### ISSUE THREAD

**Issue by Spidermanrm** [CyclopsMC/IntegratedDynamics#1232]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Breaking the machines are painfully slow, would it be possible to add a "breaking with this tool speeds it up" option?

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Which machines exactly? And what version? Sounds like this may be a bug.

**Comment by Spidermanrm** [comment]
The Mechanical Squeezer and Basin in 1.18.2 (ATM 7)

**Comment by Spidermanrm** [comment]
It feels like breaking obsidian with a diamond pickaxe

**Comment by Spidermanrm** [comment]
https://user-images.githubusercontent.com/84689843/202711203-9dfaa706-1de5-4738-97f9-106b4f9817e2.mp4
