### ISSUE TITLE
Rain renders glitchy white in front of cable attachments (any integrated mod) with Fabulous Graphics turned on

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1233]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Rain glitches out in front of cable attachments, it renders white (or inverted colours).
This happens on Fabulous Graphics, but not on Fancy.

#### Steps to reproduce the problem:

1. Turn on Fabulous Graphics in your Video Settings
2. Place a cable
3. Attach a Player Simulator
4. Turn on rain with `/weather rain`
    :x: Notice the rain changes colour in front of the cable attachments

![image](https://user-images.githubusercontent.com/14236702/203866552-9e7161a0-3eec-4a5f-a19d-2daa820d21f3.png)

![integrated glitches](https://user-images.githubusercontent.com/14236702/203866286-62a6c8b4-eae8-4e34-85be-65f4a85e3118.png)

#### Expected behaviour:

Rain is not supposed to render differently in front of non-translucent blocks like these.

____

#### Versions:

- Core:  1.17.0
- CC: 2.8.3
- Dynamics: 1.13.1
- Tunnels: 1.8.17
- Minecraft: 1.19.2
- Forge: 43.1.57

Tested this in a bare modloader setup with _just_ the above mods

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
On my system, I can see that the rain particles are slightly brighter, but not the white from your screenshot.
When scrolling through the MC issue tracker, it looks like there are similar issues in vanilla, so I guess this is a MC issue.
Let's wait until next major MC update, perhaps this is something that resolves itself (as there's not much I can do on my end to fix that atm).

**Comment by Jack-McKalling** [comment]
I'm assuming that it is only as bright white on my screen because I'm under the effects of night vision in the second screenshot. The top simplified setup screenshot shows the issue in an otherwise vanilla scenario without such effect. And there it also isn't quite as bright just like it isn't for you.

It's been said before that issues with the Fabulous Graphics setting in vanilla are special case issues often resolved by lowering the setting. So I seriously doubt whether the next major MC version will resolve this. I'm not entirely sure it is indeed vanilla to blame here. But if you can't fix it, that's understandable.
