### ISSUE TITLE
Display panel's copy button copies only the name portion of an operator, rather than its full signature as displayed

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1234]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you put an operator variable card into a display panel, the display panel's copy button will only copy the operator's name, and not the full text that the display panel is displaying.

It looks like the GUI textfield, which only shows the name of the inserted operator card, is what gets copied instead.

#### Steps to reproduce the problem:

1. Place a cable
2. Attach a display panel
3. Use LP to program a static operator onto a blank card (such as Logical And), using the green "Operator" operator
4. Insert the card into the display panel
5. Observe the display, and then the textfield inside the GUI
6. Click the copy button, and paste into a text editor
    ❌ Notice it says "Logical And"

#### Expected behaviour:

When I click the copy button, I expected it to copy the full signature of the operator, considering that is what the display panel displays as well. The copy button should be the full verbose version of the content, not the abbreviated version as displayed in the GUI textfield.

So it should have copied "Logical And :: Boolean -> Boolean -> Boolean" instead

____

#### Versions:

- Core: 1.17.0
- CC: 2.8.3
- Dynamics: 1.13.1
- Tunnels: 1.8.17
- Minecraft: 1.19.2
- Forge: 43.1.57

No modpack, issue happens in the above bare setup

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I just looked into this, and this actually isn't a bug. (thanks for the nicely written bug report though! :-) )

> The copy button should be the full verbose version of the content, not the abbreviated version as displayed in the GUI textfield.

This is not how the copy button is intended to work.

The verbose representation is rendering-specific logic, just like how items are rendered via their icon instead of their string-based representation.

If the full signature of an operator is desired, then perhaps another mechanism (operator?) needs to be added for this.

**Comment by Jack-McKalling** [comment]
I compared this with the behaviour of inserting an NBT variable card. The GUI textfield displays the _entire_ NBT in a single value. And if you click the copy button, you can see externally exactly what all those tiny pixels represent.

I was only assuming that if the display panel is not displaying NBT but something else, such as an operator signature, it would also do the same.

But I understand that this is not exactly the same, where the former is just a direct value of a card, and the latter is only a rendering of something about the card. Thanks for explaining. Although sad that's how it is, I understand.
