### ISSUE TITLE
"Network Count of Item" and "Network Count of Fluid" aspects of Network Reader have no name translated string, and break operator tooltip

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1235]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The "Network Count of Item" and "Network Count of Fluid" aspects of the Network Reader are missing a translatable string.

The tooltips also show no signature of the operators, namely that they can take an Item or Fluid argument (the Fluid one even doesn't work in the display panel at all and renders a big red cross instead).

I'm unsure whether these two issues are the same issue, but it's reasonable to assume both are at least related. If the name is untranslated, the tooltip might not be able to render the signature.

#### Steps to reproduce the problem:

1. Place a cable
2. Attach a Network Reader
3. Route the same cable to the other side of the Network Reader so the network reads itself
4. Insert a blank variable card into the Network Count of Item aspect and take it out
5. Hover over the card
    ❌ Notice it doesn't mention a signature
6. Attach a display panel to the network and insert the card into it
    ❌ The operator's signature contains a dotted translation resource string as its name

Missing signatures:
![integrated operator display](https://user-images.githubusercontent.com/14236702/204084879-801cdc8a-65d9-4040-99af-41c186bea735.png)
Untranslated string:
![integrated operator displaystring](https://user-images.githubusercontent.com/14236702/204085051-03f29e29-04e8-4b2a-8c46-40722e887ae0.png)

Here you can see that the Fluid variant of the aspectdoesn't function in the display panel. Not sure what that means (might be unrelated)
![integrated operator displaycross](https://user-images.githubusercontent.com/14236702/204084886-06bfb815-0811-4245-9100-5d2b9de50694.png)

#### Expected behaviour:

I expected the operator to display its properly translated name along with signature in the display panel, such as `Network Count of Item :: Item -> Long`.
And also that the tooltip shows the full signature, just like any other static operator card.

____

#### Versions:

- Core: 1.17.0
- CC: 2.8.3
- Dynamics: 1.13.1
- Tunnels: 1.8.17
- Minecraft: 1.19.2
- Forge: 43.1.57

This happens with just the above setup, no modpack.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
FYI, the tooltip part is intentional. The others are bugs indeed.
