### ISSUE TITLE
Machinal drying basen output not working for Refine Storage importer

### ISSUE THREAD

**Issue by 1matto** [CyclopsMC/IntegratedDynamics#1237]
The Machinal drying basin 's input is the same as it output. found when trying to automate rotten flesh into leather with Refine Storage

**Comment by rubensworks** [comment]
@1matto Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by Jack-McKalling** [comment]
Potentially you're extracting the input directly out of the machine without processing it.
Integrated Tunnels can do that for instance, in case you're extracting from the sides of the machine.
If that is what you're doing, you're suggested to move the RS Importer from the side to the bottom for extraction, and insertion on the top.
