### ISSUE TITLE
"Copy" recipe for Omni-Directional Connector takes in 3 connectors but produces only 2

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1238]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using an existing omni-directional connector to create multiples of the same group, using the "copy" recipe which takes 3 connectors (2 mono and the omni), you only get 2 connectors. It even consumes all items in the crafting grid.

Back in 1.12.2 this used to produce 3 connectors.

#### Steps to reproduce the problem:

1. Get one Omni-Directional Connector
2. Get 2 Logic Directors and 2 Mono-Directional Connectors
3. Use this recipe:
![image](https://user-images.githubusercontent.com/14236702/205925748-a5f039a0-452c-4d50-80dc-5427e32e455e.png)
4. Take out the result
    ❌ You now only have 2 Omni-Directional Connectors

![omnidirectional count](https://user-images.githubusercontent.com/14236702/205926551-e99b2ae3-78b0-4e66-8406-f3132196a4cf.png)

#### Expected behaviour:

Each Mono-Directional Connector can be converted into an Omni-Directional one with a 1:1 ratio using the recipe that uses a Logic Cable. So using the above recipe which takes in 3 connectors, I would expect it to also output 3 connectors.

____

#### Versions:

- Core: 1.17.0
- CC: 2.8.3
- Dynamics: 1.14.1
- Tunnels: 1.8.17
- Minecraft: 1.19.2
- Forge: 43.1.65

No modpack, just above mods (despite modpack screenshot).

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The input omni-dir connector for that recipe should not be consumed, and hence give you 3 connectors in total as output.
Can you check if the input connector is consumed on your end? If not, then there is no bug.

**Comment by Jack-McKalling** [comment]
I already mentioned that it does consume the input one in the description

**Comment by rubensworks** [comment]
Ok, thanks for confirming.

**Comment by Jack-McKalling** [comment]
I checked both taking the result out and shift-clicking it.
In both cases all input is consumed.
