### ISSUE TITLE
Variable card name in Logic Programmer isn't updated if backspace was the last key

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1239]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The (labeller's) textfield in the LP GUI conflicts with what is actually used for the variable card's name, if backspace was the last key used.

#### Steps to reproduce the problem:

1. Get a Logic Programmer, Labeller and a Variable Card of any kind
2. Open the Logic Programmer and choose any operator on the left
3. Insert the Variable Card to save the operator on it
4. Click the little "E" to edit the card's name
5. Type "abc", then use backspace
    ✅ The textfield now shows "ab"
6. Take out the variable card and hover on it
    ❌ The card's name is still "abc"

![integrated variable naming](https://user-images.githubusercontent.com/14236702/206913691-bcdb6f10-8fe9-4e0c-971a-c11127fa43d0.png)

#### Expected behaviour:

Using backspace is supposed to work. In the above example, it appears that the backspace is not resolved on the final value for the card, eventhough the textfield shows the result correctly. As if the internal mechanism only uses the valid character sequence typed, rather than the _value_ typed.

____

#### Versions:

- Core: 1.17.2
- CC: 2.8.3
- Dynamics: 1.14.2
- Tunnels: 1.8.18
- Minecraft: 1.19.2
- Forge: 43.2.0

Only the above mods used, no modpack. (testworld included ~Crafting and ~Terminals too though).

**Comment by rubensworks** [comment]
Thanks for reporting!
