### ISSUE TITLE
feature: (Number -> String) format or concat (Str, Num) operator

### ISSUE THREAD

**Issue by shabble** [CyclopsMC/IntegratedDynamics#124]
As far as I can tell, it doesn't appear to be possible to convert an Int/Number type into a string to use with the existing `concat(Str, Str) -> Str`.

A "proper" format/convert would potentially have options like number of decimal places, base, etc, but the simplest thing that would allow `concat("My value is:", $someIntVar)` would be very handy.

Versions:

* IntegratedDynamics-1.10.2-0.6.7.jar
* IntegratedTunnels-1.10.2-1.1.0.jar
* CyclopsCore-1.9.4-0.9.1.jar

**Comment by rubensworks** [comment]
You can use the "Named" operator for this toString conversion.
Granted, the name of this operator is not ideal, I'll change this soon.
