### ISSUE TITLE
[1.19.2]The ability to get blocks has disappeared.

### ISSUE THREAD

**Issue by DrSigma4164** [CyclopsMC/IntegratedDynamics#1240]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After installing your mod, the ability to get blocks using a pickaxe disappears. As I understand it, for some reason the "minecraft:mineable/pickaxe" tag disappears from the blocks, and therefore minecraft does not understand that this is a block, such as a stone, that can be mined with a pickaxe. Details on the screenshot.
By the way, if you go back to version 1.14.1, this bug is gone.

#### Steps to reproduce the problem:

1) Put the version "IntegratedDynamics-1.19.2-1.14.2.jar" or you can put the profiler that I exported from curseapp
2) Look at the stone and see something like in screenshot 1

____

#### Versions:

- This mod: 1.14.2
- Minecraft: 1.19.2
- Forge: 43.1.65

#### Log file:

latest: https://gist.github.com/fd4ab7e13710253cbe0bb398e6901fe3.git
debug: https://gist.github.com/c83d1584a5681883a5e850db8dd4b68d.git

ModPack Profiler: 
[1.19 (1)-Bug.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/10210697/1.19.1.-Bug.zip)

**Comment by rubensworks** [comment]
Thanks for reporting!
