### ISSUE TITLE
Cannot read the manual On the Dynamics of Integration

### ISSUE THREAD

**Issue by dreamyloong2005** [CyclopsMC/IntegratedDynamics#1243]
#### Issue type:

- :bug: Bug

____

#### Short description:

When trying to read On the Dynamics of Integration (Right click), the page of the manual can't be opened. And after trying to use it, if I press E and open my bag then click the manual, it just disappears. However, if I throw it out and pick it up again, I can click it without it disappearing. But I still can't use it. I have loaded quite a lot other mods and I don't know if the problem is caused by the incompatibility of IntegratedDynamics with other mods. I can give you a list of the mods I've loaded to help you fix the bug.

#### Steps to reproduce the problem:

1. Create a world
2. Get the manual
3. Equip it, then right click
4. Fail to open it
5. Press E to open the bag
6. Click the manual in the bag page
7. The manual disappears

#### Expected behaviour:

Open the page of On the Dynamics of Integration successfully

____

#### Versions:

- This mod: 1.10.15
- Minecraft: 1.16.5
- Forge: 36.2.39

#### Log file:

None

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> I have loaded quite a lot other mods and I don't know if the problem is caused by the incompatibility of IntegratedDynamics with other mods.

It might be; could you try without any other mods?

Could you also share the client and server logs? There will probably be some useful information in there.

**Comment by rubensworks** [comment]
Ah wait, I see this is for MC 1.16, which is not supported anymore unfortunately.
