### ISSUE TITLE
Modified the output of the squeezer and the mechanical squeezer and the "count" of the output didn't work now

### ISSUE THREAD

**Issue by SwatOnes** [CyclopsMC/IntegratedDynamics#1244]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I change a recipe with kubejs. The recipe is recipes/squeeze/ore/raw_tin
When I change this recipe with the data of KubeJS, after a reload, all the output is output the right item but the "count" in the file is ignorred. The tin output is 1 even if in the file the output count is 2.

#### Steps to reproduce the problem:

1. Copying the path and the file of the recipe in Kubejs data
2. Change the recipe, I cahnge the output tag into the precise item I want so i change "tag" in "item" and the base output by the item I want using kubejs_hand
3. reload data using /reload
4. Look at recipe in JEI and realise that all the output have a correct chance ouput but the count is not take in account.

#### Expected behaviour:

I expected that the output of this recipe will keep the number of output described by the "count" in the recipe file

____

#### Versions:

- KubeJS mod: kubejs-forge-1902.6.0-build.138
- IntegratedDynamics mod: IntegratedDynamics-1.19.2-1.14.6
- Minecraft: 1.19.2
- Forge: 43.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I don't know how KubeJS works tbh, so not sure why this is an issue with this mod.
Can you try reproducing with just JSON recipe files?
If that does work, then it's a KubeJS issue.
