### ISSUE TITLE
Creative Energy Battery is untextured when Auto-supply is enabled.

### ISSUE THREAD

**Issue by TheRea1Sans** [CyclopsMC/IntegratedDynamics#1246]
Minecraft version : 1.12.2
Mod version : 1.1.6
Title. The text for auto-supply is also missing, but that is an easy fix. How should I go about fixing this, if at all?

**Comment by rubensworks** [comment]
I'm sorry, but the 1.12 version is not maintained anymore.

**Comment by PoolloverNathan** [comment]
If you really wanted to fix it, you could make a texture pack.

**Comment by TheRea1Sans** [comment]
Oh, ok, thanks.
