### ISSUE TITLE
Lag when using JEI in Storage Terminal Crafting Window

### ISSUE THREAD

**Issue by FoundryCove** [CyclopsMC/IntegratedDynamics#1247]
---
name: "🐛 Bug report"
about: If something is not working as expected or crashes

---

#### Issue type:

- :bug: Bug 

____

#### Short description:
When bringing up a crafting recipe that can take different block variants (e.g. wood planks, glass blocks) the game can slow down or outright freeze, depending on how many variants the recipe takes. There is no performance drop for recipes without variations. This only seems to happen on large inventory networks. I've been seeing this issue since at least 30,000 items in inventory, but it may have started with less than that. The multithreading crafting option does not seem to make any difference. My network is Sophisticated Storage multiblock hooked to a storage terminal.

#### Steps to reproduce the problem:

1. Open Storage Terminal, fixed or portable 
2. Switch to crafting tab
3. Select a crafting recipe in JEI that has multiple item variations 
4. If there is a large amount of items in the inventory network the game will slow or even completely freeze. Glass seems to be the worst as it has many variants in ATM 8.
5. Game will continue to run poorly until the crafting preview is closed. 

#### Expected behaviour:

I expected the game to preview crafting recipes without issues. 

____

#### Versions:

- This mod: Integrated NBT 1.6.0
                   Integrated Crafting 1.0.26
                   Integrated Dynamics 1.14.7
                   Integrated Terminals 1.4.2
                   Integrated Tunnels 1.8.18
- Minecraft: 1.19.2
- Forge: 43.2.3

#### Log file:
https://spark.lucko.me/Bfs7wjj0Zb

**Comment by rubensworks** [comment]
@FoundryCove Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by rubensworks** [comment]
Also, please share your profiling log as explained in https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://opengraph.githubassets.com/7b972765a3337bd98faee69bb99ee5536171a77623f12420ee348099df2ded48/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</div></blockquote>

**Comment by FoundryCove** [comment]
I updated the format of the issue. I'm not sure what mod version to put? There's several integrated mods in ATM 8, which one is relevant here? I'm running the mod in All The Mods 8 v1.0.10

BTW I'll have a profile log soon.

**Comment by FoundryCove** [comment]
I linked the spark profile upload. I ran it from just before I opened the portable terminal, to just after I closed the window after it froze up.

**Comment by rubensworks** [comment]
> There's several integrated mods in ATM 8, which one is relevant here? I'm running the mod in All The Mods 8 v1.0.10

Could you add all of them?

**Comment by FoundryCove** [comment]
Added the version numbers for all the Integrated mods in the pack

**Comment by rubensworks** [comment]
I just pushed a fix which will significantly boost performance.
However, I noticed a deeper problem thanks to this issue, which I will look into next, but will take a bit more time.
So if you still get some performance issues after this change (perhaps on networks with many changes per second), then the next upcoming update might help with things.

**Comment by FoundryCove** [comment]
[crash-2023-02-18_04.01.06-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/10774279/crash-2023-02-18_04.01.06-client.txt) This update seems to cause a crash on load with ATM 8. No other mods where changed.

**Comment by rubensworks** [comment]
That crashlog seems to have nothing to do with this mod, but with some kind of model-fixing mod.

> java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @6fe04f2a; net.mehvahdjukaar.modelfix.ModelFix is in

**Comment by FoundryCove** [comment]
![image](https://user-images.githubusercontent.com/119443577/219873330-ec0818ee-8d96-41a5-b6a5-018a0fdf215d.png)
From what I saw in the issues page for this mod(https://beta.curseforge.com/minecraft/mc-mods/model-gap-fix), something about it messes with the crash log, but it was just an issue with other integrated mods in the pack being outdated

<blockquote><div><strong><a href="https://beta.curseforge.com/minecraft/mc-mods/model-gap-fix">Just a moment...</a></strong></div></blockquote>

**Comment by FoundryCove** [comment]
I updated the mods and it still let me join the server I've been playing on without them doing anything, but there wasn't any difference in performance. Would they need to update for me to see a difference?

**Comment by FoundryCove** [comment]
@rubensworks I got the server world and ran it in singleplayer with the newest version of the mod. This issue does not seem to have been resolved. I tested it ~2000, ~100,000, and ~400,000 items in the network. All showed the same freezing issue.

**Comment by rubensworks** [comment]
This is what I said before:

> So if you still get some performance issues after this change (perhaps on networks with many changes per second), then the next upcoming update might help with things.

In any case, a new profiling log can definitely help.

**Comment by FoundryCove** [comment]
@rubensworks I didn't change anything since last time, but besides a hang on opening the recipes, it doesn't lag while viewing them now.

**Comment by rubensworks** [comment]
Ok, that's what the fix intended to do.
The hang on opening will be fixed in a later version (as it requires some more invasive changes).

**Comment by rubensworks** [comment]
@FoundryCove Just published new releases of CC, ID, and ITerminals. It should significantly improve performance.
Could you let me know how it works out on your end?
There's still one more improvement I can do if it's still not enough, but I'd want to avoid taking that road until absolutely necessary.

**Comment by FoundryCove** [comment]
Will I just need these just on my client, or will the server need to be updated?

**Comment by rubensworks** [comment]
Just a client update might be sufficient in your case.
But the changes cover more than just this issue, so you should also see generally better performance server-side as well when applying these changes server-side.

**Comment by FoundryCove** [comment]
With my inventory at 4.17 million items there's a 5-10 sec hang when opening the storage terminal. Still getting a freeze condition with some item's crafting recipes. The interface freezes every time an item is added to a network.

**Comment by rubensworks** [comment]
> With my inventory at 4.17 million items there's a 5-10 sec hang when opening the storage terminal. Still getting a freeze condition with some item's crafting recipes. The interface freezes every time an item is added to a network.

And is there any improvement compared to the previous version? (there should be ...)

**Comment by FoundryCove** [comment]
I'm not sure, I switched servers in the meantime and didn't use integrated dynamics on the new one.

**Comment by rubensworks** [comment]
Could you send me a new profiling log in that case?

**Comment by glektarssza** [comment]
Just wanted to chime in. Still seeing this using the latest version of FTB Skies with the latest version of IntegratedDynamics, IntegratedTerminals, IntegratedTunnels, IntegratedCrafting, Integrated NBT, and CyclopsCore.

My profiling log can be found here: https://spark.lucko.me/W43Fsfi5BQ

<blockquote><img src="https://spark.lucko.me/thumb/W43Fsfi5BQ.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers, and proxies.</div></blockquote>

**Comment by glektarssza** [comment]
Relevant area of the profiling output appears to be here:

![image](https://user-images.githubusercontent.com/94402525/235015681-dbe57b02-5808-45ab-aa19-11e954de7b75.png)

**Comment by rubensworks** [comment]
Thanks @glektarssza!

**Comment by rubensworks** [comment]
@glektarssza or @Snonky, could you try out the latest CyclopsCore release, to see if this improves performance on your end?
The previous optimization had a flaw where it would not apply in some cases, which is why performance was horrible on your end. The latest release may fix this.

@Snonky With this optimization, our temporary cache workaround may not be needed anymore.

There's also a chance that this improves performance, but is still too laggy. In this case, I have another improvement in mind.

**Comment by P3rf3ctXZer0** [comment]
I will also test this update as I believe my issue to be at least 25% due to network systems as lag didn't exist until I used variables.

**Comment by Snonky** [comment]
@rubensworks Very good improvement. No more freezing, just low frames. With the cache the frames are more stable. I think having both improvements is viable to make it work with even bigger storages and to be kind to the client's CPU usage ^^

CyclopsCore 1.18.4:

https://user-images.githubusercontent.com/47639380/235488827-7b46ef7b-abce-42bf-ac1f-1da18796b6be.mp4


CyclopsCore 1.18.4 + cache:

https://user-images.githubusercontent.com/47639380/235488119-b01e1e0d-52a7-46d6-8ebb-217680979874.mp4

**Comment by glektarssza** [comment]
@rubensworks I will test shortly and report back!

**Comment by glektarssza** [comment]
Significantly better! Previously I was dropping below one frame per second. Now I lose about fifteen frames per second, so dropping from sixty to forty five. I'm not sure if one of this family of mods is responsible for that, though, or if it's just a normal performance hit from being in a UI. I have noticed a performance hit to being in any UI so I'm inclined to think this family of mods is not at fault for that.

**Comment by rubensworks** [comment]
Excellent, thanks for checking @Snonky  and @glektarssza.
Closing this issue then.

@Snonky I'll try to review your PR in https://github.com/CyclopsMC/IntegratedTerminals-Compat/pull/8 later this week!
