### ISSUE TITLE
Two Prong Crash. 1. Crafting Job Dependency Crash CAUSES 2. Entity Ticking World Corruption (with Immersive Engineering)

### ISSUE THREAD

**Issue by BlindTM** [CyclopsMC/IntegratedDynamics#1249]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Auto-Crafting random items (only one item I've been able to find does it everytime) at times will crash my game. This in turn will lead about 75% of the time to a world corruption for entity ticking.

Theory:
I think there is an interaction between Immersive Engineering's multiblock structure 'Tank' that stores fluids and the 'Fluid Filter' I have attached to the bottom of the multiblock. At least I believe that's what is causing the Entity Tick error that corrupts the world save. For the crafting dependency issues I'm not entirely sure.

#### Steps to reproduce the problem:

1. Autocraft more than one fluid reader, I think it has to do with the water buckets. Again, other items appear to cause the crash randomly.
2. Crash, Load up world, attempts to load, crashes until either world backup is restored or removing Integrated Dynamic additionals from modloader.

#### Expected behaviour:

Autocraft as normal.

____

#### Versions:

- This mod: 1.15.2
- Minecraft: 1.19.2
- Forge: 43.2.6

#### Log file:

[crash-2023-03-13_16.41.29-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/10962910/crash-2023-03-13_16.41.29-server.txt)
[crash-2023-03-13_16.44.49-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/10962911/crash-2023-03-13_16.44.49-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Is there a vanilla-only recipe using which you can reproduce the bug?

**Comment by BlindTM** [comment]
Hey Ruben, yes actually, most recently it crashed while crafting sticks of all things (Pretty sure the first crash report is actually from this event). For that error I can't reliably recreate it everytime but I can certain do some experimenting. I'm assuming the network must be reading something else while it's happening and just bugging out? I know I run into issues quite a bit where the crafting job will stop halfway and I have to go cancel all jobs before I can restart it. (This happens in particular when starting a crafting job where the item will automatically be pulled from the network as the item is crafted but that seems like it would be a seperate issue.)

**Comment by rubensworks** [comment]
> recently it crashed while crafting sticks of all things

Was this a sticks-only recipe? Or were sticks a sub-component of another recipe?

> but I can certain do some experimenting

Thanks, that would be great!

**Comment by BlindTM** [comment]
That time I'm fairly certain I had only been crafting sticks. 

Haven't had time to really start experimenting to crash on purpose with vanilla recipes but will do so this evening.

**Comment by BlindTM** [comment]
I think I'm getting a case of Car Mechanic's syndrome, where I'm unable to reproduce the problem when I need to lol 
Even crafting multiple fluid readers no longer crashes automatically.

Making a couple notes for my testing:
Crafting Planner Multithreading: On
Crafting Planner CPU Threads: 4
Packet Max: 1024

Situations tested:
Step in this case refers to the amount of crafting steps needed to get to the item. ie. Log -> Plank -> Stick = (2) Steps
Vanilla Items - 
- (1) Step, Single Item Crafting
- (1) Step, Many Same Item Crafting
- (1) Step, Many Different Item Crafting (Recipes On Same Crafting Terminal)
- (2) Step, Single Item Crafting
- (2) Step, Many Same Item Crafting 
- (3) Step, Single Item Crafting
- (3) Step, Many Same Item Crafting

Mod Items (Integrated Dynamics) -
- Same run as Vanilla

Mod Items (Immersive Engineering) - 
- Same run as Vanilla

Mod Items (Create) - 
- Same run as Vanilla


Background Scenarios:
- For part of Vanilla testing 
    - Fluid being pumped into Immersive Engineering multiblock tanks with Integrated Dynamics network. Fluid levels also being read by another reader.

- For all Situations:
   - Custom Elevator script from ComputerCraft running on loop using input from Integrated Dynamics (Essentially a combination of redstone, entity, and block reader input with redstone writer output to Create mechanisms) I add this because it runs on my world 24/7 BUT the crashes were happening before I had created this.

   - Various automatic Integrated Dynamic checks for item smelting and processing with Immersive Engineering machines.

Results: Inconclusive

Worthwhile Observations: CPU Spike during network opening/access and when beginning crafting job.

**Comment by BlindTM** [comment]
Okay, got another crash. Roughly 40min into my session, not bug finding, just playing as normal. 

Crafted (2) 'Gearbox' from Create mod. Had crafted this item many other times during session with no problems.
[crash-2023-03-16_20.39.01-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/10997648/crash-2023-03-16_20.39.01-server.txt)

This time I was able to load the world after crash without it corrupting. Consistent issue of having to break one network cable and place it back to 'reset' network still occurred however. Upon checking network, only (1) gearbox was crafted successfully.
