### ISSUE TITLE
Abnormal lag spikes. Somtimes crashing server.

### ISSUE THREAD

**Issue by jaynotgay** [CyclopsMC/IntegratedDynamics#1252]
Hello,
Forge IntegratedDynamics-1.19.2-1.16.2
ATM8
![333333333](https://user-images.githubusercontent.com/30220126/227712566-1c0713b4-b5a0-44d1-9731-80b4012cf722.png)
Abnormal lag spikes.

**Comment by rubensworks** [comment]
@jaynotgay Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by icha-senpai** [comment]
"New issue" > "Bug report" > fill in the required fields.
