### ISSUE TITLE
Abnormal lag spikes. Somtimes crashing server.

### ISSUE THREAD

**Issue by jaynotgay** [CyclopsMC/IntegratedDynamics#1253]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:
After some time the mod on the server thread goes to extreme high tick lengths causing to freeze the server.

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:  Forge IntegratedDynamics-1.19.2-1.16.2 On the modpack ATM8

#### Log file:
![image](https://user-images.githubusercontent.com/30220126/227803253-9d103006-8a2e-452a-8707-1a11b881582f.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share the profile log instead of a screenshot of it?

**Comment by maca134** [comment]
Sorry to reopen issue but this is still happening.
Here is profiler: https://spark.lucko.me/KDsShrcFOr
It is happening with any wrench. I tried latest version on CF, still happening.
