### ISSUE TITLE
Displaying large NBT causes disconnect

### ISSUE THREAD

**Issue by natedogith1** [CyclopsMC/IntegratedDynamics#1255]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Placing a variable with a large NBT compound disconnects client with a message about the NBT being too large.

#### Steps to reproduce the problem:

1. Create large NBT value (I accomplished this by getting the NBT of a player)
2. Place value in a display panel

#### Expected behaviour:

The client shouldn't be disconnected.

____

#### Versions:

- This mod: 1.18.2-1.11.8
- Minecraft: 1.18.2
- Forge: 40.1.73
- Modpack: Encrypted_ R 2.1.3

**Comment by rubensworks** [comment]
Could you share that message, together with the server logs?

**Comment by natedogith1** [comment]
I don't have access to the server for a couple days. I'll recreate the situation and gather the logs on Monday.

**Comment by natedogith1** [comment]
Server logs: https://gist.github.com/natedogith1/669c7285ef9cff588c564fb39ee7d759
I didn't see anything relevant in the client log.
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big: tried to allocate: 2097205bytes where max allowed: 2097152


<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/natedogith1/669c7285ef9cff588c564fb39ee7d759">server log</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
