### ISSUE TITLE
Materialized entity variable needs manual refresh

### ISSUE THREAD

**Issue by natedogith1** [CyclopsMC/IntegratedDynamics#1256]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Materializing an entity variable references the in-world entity (#528), but using the materialized variable doesn't refresh unless something triggers it.

#### Steps to reproduce the problem:

1. Materialize an entity value of a player
2. Use the armor inventory operator
3. Place the armor inventory operator in a display panel
4. Remove player armor and watch the display remain unchanged
5. Remove and re-insert the variable
6. See updated display
7. Re-equip armor and see display update

We managed to get it to update live by doing `choice(redstone_clock, materialized_player, materlalized_player_copy)`, though `constant(materialized_player, redstone_clock)` didn't seem to work.

#### Expected behaviour:

Value should either be constant or update live, not need triggering.

____

#### Versions:

- This mod: 1.18.2-1.11.8
- Minecraft: 1.18.2
- Forge: 40.1.73
- Modpack: Encrypted_ R 2.1.3

**Comment by rubensworks** [comment]
It seems to be working fine on my end though.
Can you try reproducing without any other mods installed?

If it doesn't work due to the materialized player not being online, then this is normal of course.
