### ISSUE TITLE
Placing network component without cable causes Part Enhancement: Offset to drop

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedDynamics#1259]
#### Issue type:

- :bug: Bug

____

#### Short description:

Network components placed without a cable in the same block produce a Part Enhancement: Offset as an item drop.
Issue discovered in [FTB One](https://www.feed-the-beast.com/modpacks/97-ftb-one) pack; linking issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3019

#### Steps to reproduce the problem:

1. Place an Item Interface (per [CyclopsMC Discord conversation,](https://discord.com/channels/386052815128100865/386054223688630272/1094443556833329182) may occur with other parts) somewhere where there isn't a cable.

____

#### Versions:

- Integrated Dynamics: 1.16.2
- Minecraft: 1.19.2

**Comment by rubensworks** [comment]
Thanks for reporting!
