### ISSUE TITLE
Repeated crash after materialising a predicate function

### ISSUE THREAD

**Issue by shabble** [CyclopsMC/IntegratedDynamics#126]
Previously unreported because I lost a lot of the context of what was in the network because I ended up NBTEditing out to get the world to load, but the following crashlogs are all from the same root cause.

I *think* I was trying to define a predicate for a Tunnel importer that would accept items with durability < 50% max durability, and as part of that, tried to 'squash' a long sequence of apply(apply(apply(thing, foo1), foo2), foo3)... to see if it would work.

Main error seems to be:
```
java.lang.IllegalArgumentException: Value "operator.operators.integrateddynamics.virtual.flipped.name[integer]" could not be parsed to an operator.
```

[crash-2017-01-28_14.57.39-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/737598/crash-2017-01-28_14.57.39-client.txt)
[crash-2017-01-28_15.03.31-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/737596/crash-2017-01-28_15.03.31-client.txt)
[crash-2017-01-28_15.16.00-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/737597/crash-2017-01-28_15.16.00-client.txt)
[crash-2017-01-28_15.29.29-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/737600/crash-2017-01-28_15.29.29-client.txt)
[crash-2017-01-28_16.17.59-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/737599/crash-2017-01-28_16.17.59-client.txt)

(Note that the final resolution involved nuking both the materialiser block, and the card it had produced, which was in my player inventory. The first 2 crashes were checking it still happened, the next were after removing some of the blocks and variable store, and finally cards in my inventory.

I *might* have a backup with some of the original network/vars if there's anything useful I can provide from there

**Comment by rubensworks** [comment]
This looks like something going wrong while trying to render the variable item after reading its NBT data, which consists of a dynamically built operator.

Thanks for reporting, I should be able to reproduce this myself.

**Comment by rubensworks** [comment]
It appears this is part of a larger problem, an edge-case I haven't taken into account at all. I have to rewrite some parts of the materialization process, so this might take some time.
