### ISSUE TITLE
Block NBT operator

### ISSUE THREAD

**Issue by DasBrain** [CyclopsMC/IntegratedDynamics#1263]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Add an operator Block NBT (NBT()) that works similar to Item NBT (NBT()), Entity NBT (NBT()) or Fluid NBT (NBT()).

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I may be misunderstanding this issue, but blocks don't have NBT in Minecraft.
Could you clarify your needs?

**Comment by DasBrain** [comment]
In short, I want to get the NBT of the Tile Entity of the Block I am looking at.

**Comment by rubensworks** [comment]
There's an aspect in the block reader for this.
Tile entities are obtained by position; blocks don't contain this information.

**Comment by DasBrain** [comment]
Thanks. How do I point a Block Reader dynamically to the block I am looking at?

**Comment by rubensworks** [comment]
The new offset functionality can probably help with this, but only for a limited range.

What you probably want instead, is a new operator that reads the tile entity NBT of what an entity is looking at.
Feel free to open a new issue for this, or to rewrite this issue to focus on that instead.
