### ISSUE TITLE
Report (Not Sure What Kind) - 1.19.2 Integrated Dynamics Lagging Up a Storm (Report Assisted by Forge Dev Team Discord)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedDynamics#1264]
Forge Version 43.2.8
``ColossalChests-1.19.2-1.8.4.jar``
``CommonCapabilities-1.19.2-2.9.0.jar``
``CyclopsCore-1.19.2-1.18.3.jar``
``IntegratedCrafting-1.19.2-1.1.1.jar``
``IntegratedTunnels-1.19.2-1.8.18.jar``

Spark Report
https://spark.lucko.me/biJ0zxnIlU

![daXbSaJ 1](https://user-images.githubusercontent.com/10351221/232832007-ba01e4be-3e87-4ea2-9ddf-b06cf83246f3.png)

Debug (Was too big)
Latest Log https://gist.github.com/P3rf3ctXZer0/e88956f88bbca2b9af58a67ad49c26ed

Usage Case
I have a large level (11) obsidian chest and it is pulling in pushing items out using a dynamic network using
variable cards to various machines. Apparently it is lagging really bad across server.

What my machine looks like.

![2023-04-18_11 03 20](https://user-images.githubusercontent.com/10351221/232836731-fd06eedc-59a1-4263-b2eb-22406880902e.png)
![2023-04-18_11 03 30](https://user-images.githubusercontent.com/10351221/232836734-88076c1e-50ee-4680-91de-bd66f2d24743.png)
![2023-04-18_11 03 36](https://user-images.githubusercontent.com/10351221/232836740-7e4b110c-a6b6-4ec1-98a3-451a7a478618.png)
![2023-04-18_11 04 03](https://user-images.githubusercontent.com/10351221/232836743-58c063bf-aa08-4762-bafd-451fcd745f31.png)
![2023-04-18_11 04 09](https://user-images.githubusercontent.com/10351221/232836746-c7627608-e43e-49cc-af4b-1577711486e9.png)
![2023-04-18_11 04 19](https://user-images.githubusercontent.com/10351221/232836748-7430309d-a00c-4a63-b53a-e7246b43f6f1.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The spark logs don't really give enough information to pinpoint the problem.
Could you enable the ID network diagnostics tool (as admin; see the `\integrateddynamics` command)?
That should allow you to see which parts of the network cause the most lag.

**Comment by P3rf3ctXZer0** [comment]
I am no longer testing but if you want to test you could always add the mod to my modpack or talk to xfact on Forge Dev Discord https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon


<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon">Just a moment...</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Ok, will close this issue then until new information becomes available.

**Comment by Twisted-Code** [comment]
I was also having performance issues because of the mod, though I doubt it's the EXACT same issue as the spark report I have looks different than the one P3rf3ct provided: 
https://spark.lucko.me/ZV7GEqdkyF
I also don't have anything particularly interesting set up at this time, all I have at my base is and energy cell (yours can be made much more compact than most of the other energy storage options in this pack) and mechanical drying basin. How the hell am I managing to set off a performance death spiral with just 2 blocks?

**Comment by Twisted-Code** [comment]
While trying to diagnose my issue when it happened again today, I came across the /integrateddynamics command and decided to —since I was the only one playing on the server at the time, and the issue was affecting playability, anyway— see if the crash command would produce anything useful. I'm not sure it did, but here's the crash report anyway
[crash-2023-05-05_14.10.32-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/11407215/crash-2023-05-05_14.10.32-server.txt)

**Comment by Twisted-Code** [comment]
(I also tried the network diagnostic tool first, the one mentioned above, but I can't visit the HTTP page at localhost since this isn't my hardware. The server is rented from Akliz)

**Comment by Twisted-Code** [comment]
https://spark.lucko.me/OXcZ0MpdoJ
Here's a nice LONG profile. The first performance improvement was IMMEDIATELY after I broke the Mechanical Drying Base and that was at my base. The next performance drop was still by your mod, but probably from a tile entity someone else has at their base? Honestly not sure, but please fix this as it's making the mod unusable.

<blockquote><img src="https://spark.lucko.me/thumb/OXcZ0MpdoJ.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers, and proxies.</div></blockquote>

**Comment by rubensworks** [comment]
@macks2008 I think you're experiencing a problem that has already been fixed. See https://github.com/CyclopsMC/IntegratedDynamics/issues/1266

**Comment by Twisted-Code** [comment]
but I didn't have a wrench in my hand @rubensworks? Or does it happen for other reasons than the one described in the referenced issue's title?

**Comment by rubensworks** [comment]
@macks2008 Someone else on your server could have been holding a wrench.
Have you tried modifying the config as linked in the issue?

**Comment by Twisted-Code** [comment]
Good point, but I don't think I was holding a wrench when I was the only one on, either. Also, everyone else claims they are not using the mod. Does it happen with any wrench? 
Nonetheless, I will try the config change suggested, as I could be wrong about one or both of the above (the verbs in my first two sentences are both rather circumstantial). Besides, it would be ridiculous to ignore a possible solution, however unlikely I feel it is...

**Comment by Twisted-Code** [comment]
I'm going to do something people on the Internet rarely do: admit I'm wrong. Apparently holding ANY item registered as a wrench triggers the TPS to tank. 
...why does this happen when NOTHING from the mod is nearby? No items, no blocks, no trees, no networks, NOTHING? Do you just have some code running every tick waiting for someone to hold a wrench, and how in the world does it cause the TPS to tank this badly?
Like, I'm glad to know it's fixed and that there is a workaround until we can update our server.. but why does this happen. How?
