### ISSUE TITLE
Annoying Dark shadow!

### ISSUE THREAD

**Issue by LunaSapphie** [CyclopsMC/IntegratedDynamics#1265]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics (ATM8)
- Minecraft: 1.19.2
- Forge: 1.0.15

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Duplicate of #1254
