### ISSUE TITLE
TPS Spikes When Wrench In Hand

### ISSUE THREAD

**Issue by maca134** [CyclopsMC/IntegratedDynamics#1266]
#### Issue type:

- :bug: Bug 
____

#### Short description:

When any player has a wrench in there hand, server TPS spikes.
https://spark.lucko.me/KDsShrcFOr

#### Steps to reproduce the problem:

1. Equip a wrench.

#### Expected behaviour:

____

#### Versions:

- This mod: 1.16.2 and 1.16.4
- Minecraft: 1.19.2 (1.0.6 FTB Skies)
- Forge: forcecraft-1.19.2-3.2.6.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by maca134** [comment]
Here is video https://dl.dropboxusercontent.com/s/u42zbd9752w01oz/idgrNnc1q458bioiUm8E.mp4

**Comment by rubensworks** [comment]
Duplicate of #1261.

I assume you have from 1.16.3 to 1.16.4. In that case, you'll need to manually lower the `partOffsetRenderDistance` value from 64 to 16.
