### ISSUE TITLE
Crash on hover over jei items when the recipe page is open on the programmer

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [CyclopsMC/IntegratedDynamics#1267]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you try to make a recipe in the programmer and open the recipe section, hovering over items to the left or right causes the game to crash.

#### Steps to reproduce the problem:

See above
#### Expected behaviour:

Not to crash but to be able to hover and autofill recipes as jei permits

____

#### Versions:

- This mod: IntegratedDynamics-1.19.4-1.16.2.jar
- Minecraft: client-1.19.4-20230314.122934-srg.jar
- Forge: net.minecraftforge:45.0.55

No mods other than Integrated dynamics, jei and required core stuff

#### Log file:

https://pastebin.com/iCee14fd

**Comment by rubensworks** [comment]
Thanks for reporting!
