### ISSUE TITLE
Unnecessary offsets menu in several blocks

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [CyclopsMC/IntegratedDynamics#1268]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The extradimensional reader
World reader
Crafting writer (I know its not base but I didn't want to write a duplicate issue)
have unnecessary offset menus.

#### Steps to reproduce the problem:

No steps, just an interface

#### Expected behavior:

No offsets where it wouldn't make sense

#### Versions:

- This mod: IntegratedDynamics-1.19.4-1.16.2.jar 
- IntegratedCrafting-1.19.4-1.1.1.jar
- Minecraft: 1.19.4
- Forge: 45.0.55

Doesn't depend on other mods
#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This is not really a bug IMO. Other mods could decide to add aspects to these readers that _do_ use positional offsets, so I don't think adding a workaround for hiding the offsets menu is a good idea.
