### ISSUE TITLE
Why do the variable ids need to be unique

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [CyclopsMC/IntegratedDynamics#1270]
#### Issue type:

- :question: Question 

____

#### Question:

Some very simple testing on a throwaway world shows that copied variables still function in writers. This may be a more technical question but why do variables need (or should they) have unique ids? I feel like the evaluation tree would remain consistent even if you had duplicates.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Indeed, duplicate variable id's for variables that are _only_ used for writing shouldn't be a problem.

The problem only occurs for variables that are used as input to other operator-based variables, as the network would have to choose between multiple variables with equal id's during input argument resolution.
