### ISSUE TITLE
[1.18.2]Add delay functionality to Redstone Writer  like vanilla Redstone Repeaters

### ISSUE THREAD

**Issue by karikusa** [CyclopsMC/IntegratedDynamics#1271]
I'd like a delay item on the Redstone Writer, like the vanilla Redstone Repeater.
There may already be a way to give arbitrary delays individually, but I haven't been able to find it.
I think that it is an effective function when you want to shift the input timing of the redstone signal.

**Comment by rubensworks** [comment]
This behaviour can already be achieved using the Delayer block, which was added for exactly this purpose.
