### ISSUE TITLE
[1.18.2]Unable to load list via Delayer after loading world

### ISSUE THREAD

**Issue by karikusa** [CyclopsMC/IntegratedDynamics#1272]
I was able to find a delay method using Delayer the other day,
I found a bug regarding that.
When the world is loaded, the list created by Delayer cannot be retrieved with the GET function.
It is possible to fix it by moving cards in and out of the variable store.
As a trial, I tested using a list with 1, 10, 100, 1000, 10000, but this one worked normally even if the GET function sandwiched the world load.
[Error message
]Index out of bounds.
Tried to get element 0 of a list of length 0.
Use the getOrDefault operator to provide a default when an index is out of bounds.

**Comment by rubensworks** [comment]
Using the `getOrDefault` operator is the solution indeed.
