### ISSUE TITLE
Integrated Dynamics storage terminal erroring when Blue Skies installed, causing hangs and lag

### ISSUE THREAD

**Issue by D3SL** [CyclopsMC/IntegratedDynamics#1273]
#### Issue type:

- :bug: Bug 

____
#### Short description:

With Integrated Dynamics/Terminals and Blue Skies both installed trying to browse recipes via JEI in the Storage Terminal's crafting interface causes extreme lag and basically hangs the game for several seconds. 

#### Steps to reproduce the problem:

1. Install Integrated Dynamics and Terminals
2. Install Blue Skies
3. View the recipes for basically anything, stripped logs works

#### Expected behaviour:

JEI recipe searching to simply function as normal like it does outside of the storage terminal.

____

#### Versions:

- This mod: 
- -Dynamics: 1.16.4
- -Terminals: 1.4.6
- Blue Skies: 1.3.20
- Minecraft: 1.19.2
- Forge: 43.2.6

#### Log file:

[Relevant excerpt](https://pastebin.com/QRQ4ES7v). This exact error floods the console for about 20,000 lines.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@D3SL Could you report this to the issue tracker of Blue Skies?
It looks like that mod may be incorrectly registering their `TransmuteRecipe` into JEI's `RecipeTypes.CRAFTING`, while it does not extend `CraftingRecipe`.

**Comment by D3SL** [comment]
Posted it over on [their gitlab](https://gitlab.com/modding-legacy/blue-skies/-/issues/166).
