### ISSUE TITLE
Possible Memory Leak Issue

### ISSUE THREAD

**Issue by Aiidoneus** [CyclopsMC/IntegratedDynamics#1274]
#### Issue type:

- :snail: Performance issue

____

#### Short description:
Hello,
Since we updated to the latest version of FTB Skies, we have been hit with a memory leak issue. I took a heapdump and analyzed it and came up with `org.cyclops.integrateddynamics.core.blockentity.BlockEntityMultipartTicking` spawning hundreds of thousands of objects. 

#### Steps to reproduce the problem:

Not 100% how to reproduce this for you but I believe the issue started with when FTB Skies updated to 1.2.1 and IntegratedDynamics updated to 1.19.2-1.16.5
![](https://i.imgur.com/WFgTxCc.png)

If you need any additional information, please let me know and I will be happy to provide it. 
____

#### Versions:

- This mod: IntegratedDynamics-1.19.2-1.16.5.jar
- Minecraft: 1.19.2
- Forge: forge-1.19.2-43.2.11

#### Profiler output:

Not sure what more I can give you but maybe this helps? 
![](https://i.imgur.com/M9FQkFB.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Aiidoneus** [comment]
I just wanted to add this to the report to help narrow down the issue. 
![](https://i.imgur.com/fBAk9k3.png)

**Comment by rubensworks** [comment]
Could you share your profiling log as explained in https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail ?

<blockquote><img src="https://opengraph.githubassets.com/f9dcb526b4638d723c97a0bef73e1076a698c89afd95d9679205530c1e1f0f20/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</div></blockquote>

**Comment by Aiidoneus** [comment]
> Could you share your profiling log as explained in https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail ?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1686f718ed60eb392c2886fdc21de2b6756ff571ed10d0ad8abeb5ae19b7640e/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f663964636235323662343633386437323363393761306265663733653130373661363938633839616664393564393637393230353533306331653166306632302f4379636c6f70734d432f4379636c6f7073436f7265"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore](https://github.com/CyclopsMC/CyclopsCore)**Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore

Yes, I ran a spark heap summary here. https://spark.lucko.me/cmHrDu9ZQ9 or https://spark.lucko.me/cthU8vcsGH

**Comment by rubensworks** [comment]
@Aiidoneus Could you try comparing versions `1.15.2`, `1.16.0`, `1.16.1`, to see from which one the problem occurs on your end?

**Comment by Aiidoneus** [comment]
I will try comparing if these version make a difference. I can tell you that the issue became apparent when we updated the server's modpack version from `1.1.0` to `1.2.0`

This pack update include mod update for IntegratedDynamics from `1.19.2-1.16.4` to `1.19.2-1.16.5`

I will see if I can reproduce on the versions you mentioned above though. It might take me a day or two to get it to reproduce properly on these versions.

**Comment by rubensworks** [comment]
Ah, but if the version increment was on those versions, then the versions I mentioned will probably unrelated. Will reply once I had time to look at this more closely.

**Comment by rubensworks** [comment]
FYI, the only thing that changed in that update is this: https://github.com/CyclopsMC/IntegratedDynamics/commit/7f95ea79b623d9287cfc0f4c6cb8154da72db0aa
And since that change seems unrelated, I think the issue is coming from somewhere else.
But feel free to downgrade to an earlier version, if you want to be sure.

Could you try turning on ID's network diagnostics? Perhaps there are some (new) parts that are causing issues.

It may be possible that your world just has _a lot_ of cables?

**Comment by Aiidoneus** [comment]
OK. Let me see if I can narrow this down. No promises but I will do my best to rip this apart.
