### ISSUE TITLE
Mechanical squeezer recipe not recognised by crafting interface

### ISSUE THREAD

**Issue by Blockguy24** [CyclopsMC/IntegratedDynamics#1275]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Make a system similar to the one shown
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/b8f42233-2fbc-4217-ac31-40c18e4ea74b)
2. Make a recipe variable like this (I used the [+] in JEI)
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/bbccc3b8-8207-4abb-9e41-5ad6d8eef647)
3. Put the variable card into the crafting interface and observe the issue
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/f8f83533-57a0-463d-bafb-ecb128f921ae)

#### Expected behaviour:

The recipe should be accepted as it is a valid recipe for the mechanical squeezer.
____

#### Versions:

- This mod: 1.16.6
- Minecraft: 1.19.4
- Forge: 45.0.66

#### Log file:
Not applicable I think

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Oops, looks like recipes were being validated against the regular squeezer...
