### ISSUE TITLE
Dynamic light panels are broken

### ISSUE THREAD

**Issue by Blockguy24** [CyclopsMC/IntegratedDynamics#1276]
#### Issue type:

- :bug: Bug 

____

#### Short description:

- The light output from a dynamic light panel can only be set once and then does not respond to changes
- A block with id `integrateddynamics:invisible_light` is placed in front of the light panel, which cannot be destroyed or removed in any way except with `/setblock`
  - Pushing this invisible block with a piston results in a crash, however the block is successfully pushed after the world is reloaded.
  - Dropping a block affected by gravity on it results in the gravity block being dropped as an item

#### Steps to reproduce the problem:

1. Make a simple setup like this:
![2023-06-02_10 31 03](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/d06819e0-3b86-4c76-85cf-502098c35330)

2. Insert an integer card with value > 0:
![2023-06-02_10 32 22](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/97cdb27f-4f40-4de1-9265-4ea79e5f1f00)

3. Remove the card and insert a card with value 0 (or any other value):
![2023-06-02_10 33 30](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/0f4f1da0-2255-426b-ac17-311d0f38a983)

4. Observe that the light value has not updated:
![2023-06-02_10 35 13](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/8634cf06-330e-4dbb-832d-61ca407fb382)

#### Expected behaviour:

- The light value emitted from the panel should be updated according to the value in the variable card.
  - No variable card present should emit 0 light
- The invisible light block should be able to be replaced by any block, removing the light
- The game should not crash after attempting to move the light with a piston

____

#### Versions:

- This mod: 1.16.6
- Minecraft: 1.19.4
- Forge: 45.0.66

#### Log file:

Piston crash: https://paste.ee/p/UPly2

**Comment by rubensworks** [comment]
Thanks for reporting!
