### ISSUE TITLE
every single block is a non transparent menril torch

### ISSUE THREAD

**Issue by Mass1milian0** [CyclopsMC/IntegratedDynamics#1278]
#### Issue type:

- :bug: Bug 

____

#### Short description:

every single item is an menril torch

#### Steps to reproduce the problem:

place any block from integrated dynamics

1. ...

#### Expected behaviour:

the blocks to have the proper texture

____

#### Versions:

- This mod: 1.13.5
- Minecraft: 1.18.2
- Forge: 40.2.9

![javaw_ENY9IcaCxa](https://github.com/CyclopsMC/IntegratedDynamics/assets/20503622/98ea8a7c-0140-40ab-8fb4-e20be3e88ac2)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm guessing something is corrupting your modpack 😅 
I recommend removing mods from your pack to determine the offending mod.
