### ISSUE TITLE
Cannot remove text from Recipe constant

### ISSUE THREAD

**Issue by Blockguy24** [CyclopsMC/IntegratedDynamics#1280]
#### Issue type:

- :bug: Bug 

____

#### Short description:

It is not possible to remove text from some text boxes then creating a Recipe constant

#### Steps to reproduce the problem:

1. Open the logic programmer
2. Select "Recipe"
3. Type text in one of these four boxes
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/1ae8a7d4-6c7d-4c25-85f3-0e0e7ecf40c7)
4. Try to remove it with backspace or delete

#### Expected behaviour:

Text gets removed from the boxes after using backspace or delete
____

#### Versions:

- This mod: 1.16.7
- Minecraft: 1.19.4
- Forge: 45.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!
