### ISSUE TITLE
Unformatted strings when displaying variable types

### ISSUE THREAD

**Issue by Blockguy24** [CyclopsMC/IntegratedDynamics#1281]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When looking at the tooltips for some variable cards or the operators in the logic programmer, some things are displayed as `%s`
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/73d13d8d-d46c-4632-ad66-54353dd5c89a)
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/06a70013-e331-4e14-a4ba-7062c34309e8)

*Maybe* this only affects input types but I'm not sure.

#### Steps to reproduce the problem:

1. Open the logic programmer
2. Hover over certain operators such as And (&&), Subtraction (-) or Increment (++)

#### Expected behaviour:

For the text to look more like it did previously:
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/21016331/352ea938-8417-429e-99e9-b45064efce57)

____

#### Versions:

- This mod: 1.16.7
- Minecraft: 1.19.4
- Forge: 45.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!
