### ISSUE TITLE
Game Crash in Debug World "Cannot get property IntegerProperty"

### ISSUE THREAD

**Issue by DinnerBeef** [CyclopsMC/IntegratedDynamics#1287]
#### Issue type:

- :bug: If you make a debug world and fly around in it, your game will crash.

____

#### Short description:

If you make a debug world and fly around in it, your game will crash.

#### Steps to reproduce the problem:

1. Make debug world and fly around
2. Game Will crash

#### Expected behavior:

Game not to crash

____

#### Versions:
- This mod: 1.16.9
- Minecraft:  1.19.29
- Forge:  43.2.14

#### Log file:

https://s.dinnerbeef.com/gOXe5/heziKElU15.txt

**Comment by rubensworks** [comment]
Thanks for reporting!
