### ISSUE TITLE
Tabs shift

### ISSUE THREAD

**Issue by castilio20** [CyclopsMC/IntegratedDynamics#1288]
#### Issue type:
- :bug: Bug 
It seems id does some wierd logic with the tab system
it move the vanilla tabs

- This mod: IntegratedDynamics-1.20.1-1.16.9
- Minecraft: 1.20.1
- Forge: 47.1.3
![Screenshot_2](https://github.com/CyclopsMC/IntegratedDynamics/assets/76228548/73366a23-d97a-4209-a87a-88d37c81af08)

![Screenshot_4](https://github.com/CyclopsMC/IntegratedDynamics/assets/76228548/41303904-9ada-449f-b089-e4ec770e3fdf)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Might be related to https://github.com/CyclopsMC/IntegratedTerminals/issues/107
