### ISSUE TITLE
Malformed input slots in LP

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1289]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Various slot inputs in the LP appear visually malformed. Numerical/text inputs etc. don't seem to be changed.

#### Steps to reproduce the problem:

Not an exhaustive list, but applies to many different types of things with 'item' inputs:

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/2d8f307c-bb99-440a-8298-1eb1bd000399)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/782815fd-16fc-4e30-8add-d074c39e475c)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/abd5b729-ed2b-4746-87cb-ea46ecea00c9)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/1b696d55-a3c6-4483-a343-5e4b6206637e)

Does not seem to apply to 'non-item' inputs:

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/b4ff5db9-df6a-4453-860c-c9a08790ed94)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/53f2e043-7713-41ff-8576-c5938aaafea6)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/e88e9e4b-94a6-4501-9883-5fdefce91e7d)

#### Expected behaviour:

Inputs render as normal slots, e.g. screenshot from 1.19:

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/937075db-4f98-4a1d-9226-7b81e649da46)

____

#### Versions:

- Minecraft: 1.20.1
- Forge: 47.1.0

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/a8f0b830-ac67-40f3-9d08-e6f65ffba8d4)

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
