### ISSUE TITLE
[1.20] Mismatch between JEI recipes and recipes for 'Auto-Planking' advancement

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1290]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

'Setup Autocrafting' tutorial (specifically the 'Auto-Planking' advancement) requires a recipe with specifically oak logs as input and oak planks as output. If you use JEI to fill this recipe, then you get one with oak logs/wood or stripped oak logs/wood as possible inputs. This can make it confusing for people who expect JEI to work given that the mod has JEI support.

Ideally, the advancement (and any other relevant advancements, I'm not sure if there are any) would support this sort of recipe from JEI. Since this may be difficult to achieve, given the recipe may be arbitrary with other mods added in as well, could some reference to not using JEI be added to that tutorial (and any others)?

**Comment by rubensworks** [comment]
Thanks for the suggestion!
