### ISSUE TITLE
Arithmetic Cast Precedence Tests

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1292]
#### Issue type:

- :question: Question 

____

#### Question:

In #1285 (implementing #1284), I forgot to add any tests for that ordering. In particular checking Integer -> Long, Integer -> 
Double, and Long -> Double, but maybe also Integer -> Integer etc. (that final type could probably be done by iterating over the list of all the types). The tests would flag if this ordering gets inadvertently changed, and the final test type would also catch if something breaks in e.g. `getLowestType` and suddenly all arithmetic operators cast to only one output type.

Would you accept a PR adding these tests - and if so, would any of those specific tests be redundant?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Adding tests for that definitely makes sense, a PR is definitely welcome!
