### ISSUE TITLE
Wrong error message for type error of partial application done by "apply"?

### ISSUE THREAD

**Issue by cyb0124** [CyclopsMC/IntegratedDynamics#1293]
#### Issue type:

- :bug: Bug 

____

#### Short description:
This error message essentially shows "operator expected but got operator", which doesn't make sense.
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/38105706/3bb1f236-c0cf-4543-85c0-55ecaf9cde49)

Possible cause:\
https://github.com/CyclopsMC/IntegratedDynamics/blob/8b9a2b67815b3335dcedcce2d6d7209784c25561/src/main/java/org/cyclops/integrateddynamics/core/evaluate/OperatorBuilders.java#L209C21-L209C21
This here, shouldn't it be `input.getVariables()[1]` instead of `input.getVariables()[0]`?

#### Steps to reproduce the problem:
1. Make a operator card set to "apply"
2. Make a const int card set to 0
3. Make a apply card taking the above cards as input

#### Expected behaviour:
Error message should show "operator expected but got int", but it shows "operator expected but got operator"

____

#### Versions:

- This mod: IntegratedDynamics-1.18.2-1.13.7
- Minecraft: 1.18.2
- Forge: 40.2.9

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> This here, shouldn't it be input.getVariables()[1] instead of input.getVariables()[0]?

Aha, that seems to be wrong indeed. Good catch!
