### ISSUE TITLE
Delayer overwriting values in list

### ISSUE THREAD

**Issue by Arochio** [CyclopsMC/IntegratedDynamics#1295]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using delayer all outputs are updating to the same value instead of making a list of different values on 1.20.1

#### Steps to reproduce the problem:

1. Set a variable card to a slot item 
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/12322161/latest.log)
value
2. Use the variable card in a delayer to make a list
3. Delayer updates all entries on list instead of just the next in line

#### Expected behaviour:

The delayer should output a list of values that differ over time instead of the same value being updated over each entry
____

#### Versions:

- This mod: 1.17.0
- Minecraft: 1.20.1
- Forge: 47.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Just tested, and everything is working fine on my end.
You might want to try increasing ticktime.
