### ISSUE TITLE
Book bug

### ISSUE THREAD

**Issue by castilio20** [CyclopsMC/IntegratedDynamics#1296]
overlapthis issue bc the  book not defining their screen size properly.

to not overlap with emi
#### Steps to reproduce the problem:
install emi and id or evilcraft

![2023-08-17_12 11 29](https://github.com/CyclopsMC/IntegratedDynamics/assets/76228548/29d1d96a-095e-4e19-80b8-0c7e3a636a26)
![2023-08-17_12 11 27](https://github.com/CyclopsMC/IntegratedDynamics/assets/76228548/951c20d3-e2df-44b2-b065-11f84ed7eb9c)
same for evilcraft to if you want i can add a issue there to

**Comment by rubensworks** [comment]
This has always worked fine with JEI though.
Why do you think this is an issue with this mod, and not with EMI?

**Comment by castilio20** [comment]
bc i already reported https://github.com/emilyploszaj/emi/issues/284#issue-1855100398
and it seems a bug on the book side

**Comment by rubensworks** [comment]
@emilyploszaj Do you have any insights on this? Any clue why this works fine with JEI, but not EMI?

**Comment by emilyploszaj** [comment]
EMI's conception of a valid screen is any screen that supports slots (`HandledScreen` in yarn), which has fields for the screen's position and width/height. JEI must ignore certain screens that don't meet certain conditions? Either way, the overlap is caused by the book not actually specifying its dimensions through vanilla's fields.

**Comment by rubensworks** [comment]
@castilio20 Could you share add mod and minecraft versions as requested in the issue template?

**Comment by castilio20** [comment]
@rubensworks minecraft ver 1.20.1 CyclopsCore-1.20.1-1.18.9  EvilCraft-1.20.1-1.2.27  IntegratedDynamics-1.20.1-1.17.0
