### ISSUE TITLE
LP interface problems with labelling

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1297]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Two problems with using the labeller within the LP:
1. The title of the tab does not disappear when you open the label input by pressing the 'E', instead remaining on top of the input and making it difficult to read
2. When the current tab has a text input (e.g. the 'operators' tab, also tested with the NBT, double, and string tabs), selecting one input doesn't guarantee that the input will go to that input - e.g. even after selecting the label input, the operator search input may still be the thing that gets updated, and vice versa

Potentially related: all cursors seem to visually remain in inputs after they have selected at least once, rather than disappearing once a different input has been selected (or otherwise when they would be expected to have been deselected).

Potentially related to #1298.

#### Steps to reproduce the problem:

Not always consistent - see the video below.
General steps to reproduce are to utilise any tab of the LP with multiple inputs, while you have the labeller and the label input is open in the LP.

https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/22cb9d65-3db8-4794-bb22-9370fca50732

#### Expected behaviour:

Only the last input that was pressed is the one that accepts the key inputs.

____

#### Versions:

- Minecraft: 1.20.1
- Forge: 47.1.0

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/ae723ece-6bac-40f4-92b0-f5cdec304cf5)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by met4000** [comment]
There appears to be similar behaviour in the settings ui for item interfaces (and probably elsewhere as well - edit: and delayers) - the cursor visually remains after you select an input, and when typing it isn't guaranteed to go to the input that was selected last.

It is _slightly_ less of a problem there though, because none of the inputs are selected by default, unlike in the LP.
