### ISSUE TITLE
Cannot backspace within delayer inputs

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1298]
#### Issue type:

- :bug: Bug 

____

#### Short description:

It is impossible to backspace within either of the inputs for a delayer.
Adding new characters and using e.g. arrows to increment/decrement is still possible.

#### Steps to reproduce the problem:

1. Place a delayer
2. Try to backspace within an input

Note: similarly to #1297, after pressing an input, the cursor visualy remains even after pressing a different input.

#### Expected behaviour:

Backspace removes the character immediately preceding the cursor.

____

#### Versions:

- Minecraft: 1.20.1
- Forge: 47.1.0

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/5cd6111a-adf9-4e03-8231-b094e9828d94)

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Sounds related to https://github.com/CyclopsMC/IntegratedDynamics/commit/cf719e76e3670fad496baf9b553958ae577a4cb7
