### ISSUE TITLE
Unreliable crash when removing/replacing InDy network with commands

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1299]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft can crash when deleting an InDy network via e.g. replacing it with air via `/fill`.

#### Steps to reproduce the problem:

Unable to reproduce reliably. Involved `/fill`ing the network in the world attached below, although other (not connected) networks were present at the time of the original crashes that were deleted and so I haven't been able to add back to the world.

Feel free to wontfix or close given the lack of information and irreproducibility - I'm mostly reporting in the off-chance you spot something in the crash reports that makes sense and can be fixed.

World:
[FillCrash.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/12385384/FillCrash.zip)

#### Expected behaviour:

Weird network behaviour at worst, nothing at best. At the very least, not a crash.

____

#### Versions:

- Minecraft: 1.20.1
- Forge: 47.1.0

![261781221-5cd6111a-adf9-4e03-8231-b094e9828d94](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/ce504a0d-3a13-426c-9bf9-257d37706241)

#### Log file:
https://pastebin.com/XgL1LW3r - initial crash
https://pastebin.com/EUwsxDMV - second crash (probably the same reason as the first)
Unable to reproduce since then.

**Comment by rubensworks** [comment]
Thanks for reporting!
