### ISSUE TITLE
random crash on server

### ISSUE THREAD

**Issue by alex450** [CyclopsMC/IntegratedDynamics#1302]
#### Issue type:

- :bug: Bug 

____

#### Short description:
[

#### Steps to reproduce the problem:

](https://pastebin.ubuntu.com/p/bB36cHNsBR/)

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
CyclopsCore-1.20.1-1.18.9.jar
IntegratedTunnels-1.20.1-1.8.21.jar
IntegratedDynamics-1.20.1-1.17.0.jar

- Minecraft: 1.20.1
- Forge: 47.1.44

#### Log file:
https://pastebin.ubuntu.com/p/bB36cHNsBR/
not only this file,a lot of RANDOM CRASH happens and look like this and says its  a memory bug

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by alex450** [comment]
also : CommonCapabilities-1.20.1-2.9.0.jar
running on mohist1.20.1 build 356
