### ISSUE TITLE
Menril trees replace grass with dirt even when they're prevented from placing logs.

### ISSUE THREAD

**Issue by derram** [CyclopsMC/IntegratedDynamics#1304]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

Plant saplings in a cross shape, the trees will not replace the saplings with logs.

![2023-09-01_04 42 50](https://github.com/CyclopsMC/IntegratedDynamics/assets/5730335/36bafaba-c248-457e-b557-884f4197194f)

Grow tree.

![2023-09-01_04 43 28](https://github.com/CyclopsMC/IntegratedDynamics/assets/5730335/b603fce7-494d-463e-8102-3c02aceaf33f)

#### Expected behaviour:

The grass under the saplings should remain as grass. 
____

#### Versions:

- This mod: 1.14.0
- Minecraft: 1.18.2
- Forge:  40.2.9

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: might just be some block tag missing, method override, or block property.
