### ISSUE TITLE
[1.20.1] - Crash when attempting to launch

### ISSUE THREAD

**Issue by ToxinZangoose** [CyclopsMC/IntegratedDynamics#1305]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Hello, I ran into a bug with Integrated Terminals that says it couldn't be loaded because it tried to initialize after registry.

#### Steps to reproduce the problem:

1. Launch Minecraft 1.20.1 

#### Expected behaviour:

To use the full suite of the InDy mods.

____

#### Versions:

- This mod: IntegratedTunnels-1.4.11
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:

[crash-2023-09-04_15.37.36-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/12516652/crash-2023-09-04_15.37.36-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I see a bunch of registry-related errors from different kinds of mods in your log, so I believe this is an issue with your Forge installation.
I recommend retrying with a new clean install.
Please let me know if you can reproduce the problem on a clean setup without any other mods installed besides ID.

**Comment by ToxinZangoose** [comment]
Good news, the fresh reinstallation solved my issue! Thank you for checking it out.
