### ISSUE TITLE
[Non-issue] Thank you for Safe Mode!

### ISSUE THREAD

**Issue by s5bug** [CyclopsMC/IntegratedDynamics#1307]
I accidentally created a net that continuously crashed the server I was playing on; it would have been incredibly hard to recover if not for `config/integrateddynamics-common.toml`'s `safeMode` option. I was so incredibly relieved to find it searching the configuration, not expecting it to exist.

I wanted to both offer thanks and help lost souls and/or search indexers by putting this here: if you're experiencing crash-loops after an ID change (large distances between Omni-Directional Connectors, etc), or `ServerHangWatchdog detected that a single server tick took 60.00 seconds`, set the `safeMode` option in `config/integrateddynamics-common.toml` to `true` and undo the change that started the issue.

Again, thank you!

**Comment by rubensworks** [comment]
Glad to hear the safeMode helped :-)
