### ISSUE TITLE
When closing the GUI of parts, the item held by the cursor will disappear.

### ISSUE THREAD

**Issue by UraraChiya** [CyclopsMC/IntegratedDynamics#1308]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When closing the GUI of parts, the item held by the cursor will disappear.

#### Steps to reproduce the problem:

1. Open a part's GUI, taking Redstone Reader as an example. (It also occurs in other parts such as the item interface.)
2. Click on something in your inventory to hold it up.
3. Press E or ESC to close the GUI.
4. The item you were holding disappeared.

![gif](https://github.com/CyclopsMC/IntegratedDynamics/assets/47343409/5fbd2787-ae30-4a7d-bd17-760f38be8c5e)

#### Expected behaviour:

The item does not disappear.

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.19.0
- Minecraft: 1.20.1 (Also occurs in lower versions.)
- Forge: 47.2.0

#### Log file:

none

**Comment by rubensworks** [comment]
Thanks for reporting!
