### ISSUE TITLE
[1.20.1] Integrated Dynamics fails to find Common Capabilities

### ISSUE THREAD

**Issue by Zeentch** [CyclopsMC/IntegratedDynamics#1309]
#### Issue type: Minecraft Fails to find Common Capabilities as loaded.

- :bug: Bug 

____

#### Short description:

Loading minecraft with only Integrated Dynamics and the required libraries it fails to find Common Capabilities

#### Steps to reproduce the problem:

1. Make a new Minecraft 1.20.1 profile on Curseforge
2. Download Integrated Dynamics
3. Press play

#### Expected behaviour:

I expected minecraft to load with the mod installed.

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.19.1 / CommonCapabilities-1.20.1-2.9.0
- Minecraft: 1.20.1
- Forge: 47.2.0

#### Log file:

https://pastebin.com/tYmS9JpE

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It looks like something is wrong with your installation.
Could you try re-installing? Or using the vanilla launcher, perhaps the CF launcher has a bug.

**Comment by Zeentch** [comment]
The installation i posted the crash log was a brand new installation, and i doubt CF launcher has the issue since i can still play on other modpacks on other versions as well, Integrated dynamics works well with forge-47.1.47 without issues so i have no idea what is causing the issue, thought i'd post it since i did an install with only Integrated with it's required libraries.

**Comment by rubensworks** [comment]
It looks like your CommonCapabilities jar file somehow doesn't contain the mod itself. So either the downloaded jar is corrupted, or the launcher itself is failing somehow. I doubt this is a problem on my end, since everything works fine here, and the last CommonCapabilities release is from several months ago already.

**Comment by Zeentch** [comment]
Yeah i noticed that too, it's weird that when i updated the forge version that the mod just stopped working, because i just updated the forge and then i started getting issues, i'm glad i made a copy of the profile before i updated ^^, but yeah i'll look into it more later, thanks for looking into it tho, i'll let you know if i solve it or find the cause.

**Comment by rubensworks** [comment]
Are you seeing any other errors in the full forge logs by any chance?

**Comment by Zeentch** [comment]
Not that i can recall of the top of my head no
