### ISSUE TITLE
Duplication Glitch, Logic Programmer

### ISSUE THREAD

**Issue by SilverScythe64** [CyclopsMC/IntegratedDynamics#1310]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. https://www.youtube.com/watch?v=3b05RRcAcKY
Simply open up a logic programmer, either portable, or block variant. Select the "Recipe" tab. Pick up a stack of at least 2 of the same item, and drag it across the crafting grid of the logic programmer. Repeat multiple times to increase the size of the stack you are holding. I have confirmed this to work in multiplayer, and singleplayer. I have tested it standalone with no other mods installed, as shown in the video example.

#### Expected behaviour:

I expect the items to not be duped when I drag them across the logic programmer's crafting grid.

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.20.0.jar
- Minecraft: 1.20.1
- Forge: 47.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!
