### ISSUE TITLE
Arithmetic operators from PR#1291 not in book

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1311]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The operators added in PR #1291 (i.e. arithmetic modulus, increment, and decrement) don't turn up in the list of all operators on the page for the LP in the book, although the older (and still currently existing) integer versions are present.

#### Steps to reproduce the problem:

1. Load https://integrateddynamics.rubensworks.net/book/manual/logic_programming.html
2. Search for 'modulus' on the page

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/344f13bf-e58a-4227-a197-5c83f1a11e71)

#### Expected behaviour:

Both versions of the operators are listed.

I wouldn't be surprised if this is because I forgot to do something in that PR. Some sort of collision between the pairs of arithmetic/integer operators (as they're named the same thing) comes to mind, particularly as the integer versions are after the arithmetic versions and could be overwriting them. I had a quick look at the operators.java to see if I could notice what I might have missed, but I noticed there are other operators (e.g. the sets of parse, cast, and (item/fluid/entity etc.) mod operators) that have identical names but still have individual entries in the operator list so I'm not sure if there's something else going on as well.

____

#### Versions:

> This Web book was generated with the following mods:
>> CommonCapabilities-1.18.1-2.8.2
    CyclopsCore-1.18.1-1.13.1
    IntegratedCrafting-1.18.1-1.0.21
    IntegratedDynamics-1.18.1-1.10.11
    IntegratedREST-1.18.1-1.1.5
    IntegratedTerminals-1.18.1-1.2.15
    IntegratedTunnels-1.18.1-1.8.11

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by met4000** [comment]
Hm, I didn't think to properly check the version numbers until I was rereading this after making the issue, and that might be the answer - looking at the git blame, I see the arithmetic operators being added in InDy 1.18.2-1.14.0, whereas the web book is on 1.18.1-1.10.11. Feel free to close if that's meant to be like that, otherwise this might be more of a question about the web book's version; I always assumed it auto updates to latest (at the very least, the latest for a particular mc version e.g. 1.18, if not the latest main branch i.e. 1.20), but does it use cherry picked versions instead?

Edit: yep, checked in-game on 1.18.2-1.17.0 and both versions of the operators are in the book as expected.

**Comment by rubensworks** [comment]
> I always assumed it auto updates to latest (at the very least, the latest for a particular mc version e.g. 1.18, if not the latest main branch i.e. 1.20), but does it use cherry picked versions instead?

Indeed, the website does not auto-update (yet). This file requires a manual update: https://github.com/CyclopsMC/infobook-html-integrateddynamics/blob/master/modpack.json
Making it fully automatic is still on my wishlist, but the difficulty there is regenerating icons using IconExporter in the CI, so I haven't gotten around to it.

But if you want, you're welcome to update the versions in https://github.com/CyclopsMC/infobook-html-integrateddynamics/blob/master/modpack.json via a PR to make the CI update.
However, sometimes there are breakages in https://github.com/CyclopsMC/infobook-html when Forge/MC updates...
