### ISSUE TITLE
JEI does not consider liquids as inputs for drying basins

### ISSUE THREAD

**Issue by underscorched** [CyclopsMC/IntegratedDynamics#1312]
#### Issue type:

- :bug: Bug 

____

#### Short description:

JEI doesn't consider Menril Resin and Liquid Chorus an input in the Drying Basin and mechanical counterpart.

#### Steps to reproduce the problem:

1. Attempt to enter the Uses menu for Menril Resin or Liquid Chorus in JEI (pressing U)
2. Uses menu does not appear.

#### Expected behaviour:

The uses menu to appear and show the uses of Menril Resin in producing Menril Glass and Menril Blocks, as well as the uses of Liquid Chorus in Chorus Glass and Crystalized Chorus blocks

____

#### Versions:

- This mod: 1.20.0
- Minecraft: 1.20.1
- Forge: 47.2.1
- JEI 15.2.0.27

**Comment by rubensworks** [comment]
Thanks for reporting!
