### ISSUE TITLE
Crashed when entering the save.Maybe a bug with DraconicEvolution

### ISSUE THREAD

**Issue by NEFirefox** [CyclopsMC/IntegratedDynamics#1313]
#### Issue type:

- :bug: Bug 
someting that happenes when draconicevolution and this mod are installed at the same time
JVM will sometimes throw NullPointerException when enter the saves
____

#### Steps to reproduce the problem:
1.enter some save and load
2.get crashed

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: [ID]IntegratedDynamics-1.12.2-1.1.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2860

#### Log file:
[ID]IntegratedDynamics-1.12.2-1.1.11

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by NEFirefox** [comment]
https://pastebin.com/GHMWe6fn

**Comment by NEFirefox** [comment]
oh no the log:https://pastebin.com/GHMWe6fn

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/GHMWe6fn">---- Minecraft Crash Report ----WARNING: coremods are present:  IELoadingP - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Looks like a crash in DraconicEvolution, best to report it to their issue tracker.
Also, it's 1.12, so it probably won't be supported anymore.
