### ISSUE TITLE
Recipes produced by machine reader are not compatible with Integrated Crafting crafter

### ISSUE THREAD

**Issue by LyraelRayne** [CyclopsMC/IntegratedDynamics#1316]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Recipes produced by machine reader are not compatible with Integrated Crafting crafter

#### Steps to reproduce the problem:

1. Attach machine reader to crafting table
2. Attach crafting interface to crafting table
3. Get variable card with "recipe by output" operator from the machine reader
4. Create an ingredients containing one block of quartz item in the logic programmer ("quartz out")
5. Apply "quartz out" to "recipe by output" ("quartz recipe list")
6. Head "quartz recipe list" in the logic programmer ("quartz recipe")
9. Put "quartz recipe" in one of the slots of the crafting interface
10. Put all other variables in a variable store
11. Check the crafting interface. Big red X and "Recipe is not acceptable by target"

#### Actual behaviour:
Quartz recipe has a recipe with 4 ingredients, which does not work in the crafting interface
<img width="284" alt="image" src="https://github.com/CyclopsMC/IntegratedDynamics/assets/11632412/f35a7c00-6e24-40bf-8c18-0157e16cc16c">
Left recipe is "quartz recipe" from the machine reader, right recipe is from JEI

Crating interface rejects the recipe
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/11632412/af05102d-52de-47bb-bd21-318fdaf24f58)

Crafting interface accepts the recipe from JEI
<img width="798" alt="image" src="https://github.com/CyclopsMC/IntegratedDynamics/assets/11632412/42bb784f-e6a6-44d2-a4fa-f94ab6a01ec8">

#### Expected behaviour:
"quartz recipe" should contain a recipe which is usable by the crafting interface
____

#### Versions:

- This mod: 1.20.3
- Integrated Crafting: 1.1.6
- Minecraft: 1.20.1
- Forge: 4.2.16

#### Log file:

EDIT: I realised "not correct" probably doesn't describe the recipe which comes out of the machine reader. The recipe can be placed anywhere in the crafting grid, so a 4 ingredient recipe is certainly valid, but I would expect that the machine reader would produce recipes which are usable in the only interface which actually accepts recipes.

**Comment by rubensworks** [comment]
Thanks for reporting!
