### ISSUE TITLE
Causing crashes on server

### ISSUE THREAD

**Issue by SirTrev** [CyclopsMC/IntegratedDynamics#1318]
#### Issue type:

- :bug: Bug 

____

#### Short description:

For the past few days, we have been experiencing a crash caused by Integrated Dynamics. We are not using any part of this mod in our FTB One modpack server, but it is the sole reason for each crash. I was AFK not interacting with anything and the server was still crashing. I have attached the pastebin link at the bottom that describes the crash. 

#### Steps to reproduce the problem:
Unsure, as I can be AFK'ing in the server with nothing around and the server crashes. I have attached the crash logs. 

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.20.2
- Minecraft: 1.19.2
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you check what the value of `partOffsetRenderDistance` is in your server config?
It should be 16.
If it already is at that value, could you try lowering it to 8 for example?
