### ISSUE TITLE
Block reader is delayed when following the player

### ISSUE THREAD

**Issue by MofumofuChan** [CyclopsMC/IntegratedDynamics#1320]
#### Issue type:

- :bug: Bug

____

#### Short description:

The target block of the block reader is delayed 1 block when its offset follows the player. For convenience, the block the player is stepping on.

https://github.com/CyclopsMC/IntegratedDynamics/assets/20257717/4f2cb8e6-94be-4191-95e4-12d0d821c85f

#### Steps to reproduce the problem:

1. Get a player's X, Y and Z by extracing the Pos NBT key
2. Make so the offset is floor(player's coordinates - block reader's coordinates). I also added an extra offset to the Y value of -0.5 so that it reads the block the player is standing on instead.

#### Expected behaviour:

The block reader should output exactly the block the player is standing on.

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.20.4 released in Dec 27, 2023 on Curseforge.
- Minecraft: 1.20.1
- Forge: 47.2.20

#### Log file:

None.

____

If it helps, here's the list of mods used and the world I did it in
[Mods and World.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/13978842/Mods.and.World.zip)

**Comment by rubensworks** [comment]
Thanks for reporting!
