### ISSUE TITLE
Variable offset doesn't update on world load even after updating the network

### ISSUE THREAD

**Issue by MofumofuChan** [CyclopsMC/IntegratedDynamics#1321]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The offset of the block reader (possibly spanning to other blocks that accept variable offsets) doesn't update after loading up the world when the offset is set to the block the player is standing on, even after updating the network by adding/breaking a logic cable. It only updates the offset when you go see its offset, which can be a nuisance if you have a system with at least a few of these.

https://github.com/CyclopsMC/IntegratedDynamics/assets/20257717/3f5bf478-ddac-4220-b9fd-e2c8057b64cb

#### Steps to reproduce the problem:

After having the same configuration as [Issue #1320](https://github.com/CyclopsMC/IntegratedDynamics/issues/1320), leave the world and then log into the world.

#### Expected behaviour:

It would be understandable if it didn't update without physically updating the network by adding or breaking a logic cable, but it should update if at least that is done.

____

#### Versions:

Refer to [Issue #1320](https://github.com/CyclopsMC/IntegratedDynamics/issues/1320)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The offset going into error-state is normal, since your player may not be in the world in the first tick, which errors your ID variable. So a logic-based workaround should be created for that.

But the error not going away after a network reset is a bug indeed.
