### ISSUE TITLE
[Shader issue] Issue with ComplementaryUnbound shaders

### ISSUE THREAD

**Issue by ArsiTheFox** [CyclopsMC/IntegratedDynamics#1322]
#### Issue type:

- :bug: Bug

____

Modpack: ATM9 1.20.1
Modloader: Forge 47.2.19

____

#### Issue:

I am using the ComplementaryUnbound shaders and I don't know if I would consider this a bug or not.... but it seems from many tests that the Display panel fails to render the text unless very close to it.

Vid of the issue: https://puu.sh/JZJ99.mp4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you try increasing `partOverlayRenderdistance` in the ID config file?

If that doesn't help, I'd suggest reporting it at the issue tracker of this shader, as I suspect there will be nothing I could do about this from my end.

**Comment by ArsiTheFox** [comment]
Will check later today

**Comment by ArsiTheFox** [comment]
No such thing shows of that parameter except from the mod config... I did try the mod with many other shaders and it does seem it is an issue with the Complementary shaders so I guess this isn't a bug with the mod....

Maybe the rendering of the text is angry with their shader pipeline

**Comment by ArsiTheFox** [comment]
New development, found out the text doesn't immediately vanish
https://puu.sh/JZMXw.mp4

**Comment by rubensworks** [comment]
> No such thing shows of that parameter except from the mod config... I did try the mod with many other shaders and it does seem it is an issue with the Complementary shaders so I guess this isn't a bug with the mod....

I see. Best to take up with the Complementary shaders then I guess.

Happy to make changes here if the mod author would deem it necessary! :-)

Closing this issue here in the meantime.
