### ISSUE TITLE
[Item Frame Reading] Can't get Item Frame entity to reveal item data.

### ISSUE THREAD

**Issue by ArsiTheFox** [CyclopsMC/IntegratedDynamics#1323]
#### Issue type:

- :question: Question

____

#### Question:

Can't get the Entity Reader to read Item Frames as an Item Frame. Basically the entity is read but doesn't have the Item rotation, Item in the frame or any thing like that. I may be the dumb

![javaw_DHgMzpNpmL](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/dd7cae74-26ff-454f-9c83-c7af89f1865b)
![javaw_qbgSXoTiDP](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/9c70092c-bbd4-41c9-816a-d469d5c820a5)
![javaw_1BOGwEMuwY](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/f3afd03c-528c-4655-84d0-cb55d12ec361)
![NBcwKIsDI9](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/23a3233c-b316-4d30-9454-7481b68b30e3)
![javaw_HVrD5kXToV](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/4f1e32fc-e9a2-4570-9782-12653574fb02)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Could you try putting the item frame directly onto the reader?

**Comment by ArsiTheFox** [comment]
Game won't allow me to place Item Frame on front of Entity Reader

**Comment by ArsiTheFox** [comment]
Opening up instance with only the mod, this may be a compat issue gib few

**Comment by ArsiTheFox** [comment]
Welp looks like we have a bug.... I only have Integrated Dynamics installed and can't place Item Frame on Entity Reader and it still doesn't read item in item frame or rotation

Video: https://puu.sh/JZNiU.mp4

**Comment by rubensworks** [comment]
Aha, good catch. Could you open a bug report as new issue?

**Comment by ArsiTheFox** [comment]
Can't convert this one hecc ok give a few
