### ISSUE TITLE
[Entity Reader] Not revealing Item data from Item Frame or rotation

### ISSUE THREAD

**Issue by ArsiTheFox** [CyclopsMC/IntegratedDynamics#1324]
#### Issue type:

- :bug: Bug

____

#### Short description:

Item Frame is not revealing data from Item Frames. I talked more about this here: https://github.com/CyclopsMC/IntegratedDynamics/issues/1323
I did also test with only the mod inside a new instance

#### Steps to reproduce the problem:

1. Place Item Frame next to Entity Reader
2. Place item in Item Frame
3. Open reader and see rotation data and item data do not exist .

#### Expected behaviour:

Item Data and Rotation data should be displayed

____

#### Versions:
- Mod Version: IntegratedDynamics-1.20.1-1.20.4.jar
- Minecraft: 1.20.1
- Forge: Forge 47.2.19

___

Video of issue: https://puu.sh/JZNiU.mp4

![300398485-4f1e32fc-e9a2-4570-9782-12653574fb02](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/a6ad028f-2df1-41b7-bd48-6d1c438d23b1)
![300398483-23a3233c-b316-4d30-9454-7481b68b30e3](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/3d6ffc0d-5c21-4b12-ac7e-41b47aa31d3e)
![300398480-f3afd03c-528c-4655-84d0-cb55d12ec361](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/4c6a8795-ba9e-4000-82cb-e96c22804e47)
![300398477-9c70092c-bbd4-41c9-816a-d469d5c820a5](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/e80b5733-2180-4c9f-b5e5-48f2c2f8bbef)
![300398473-dd7cae74-26ff-454f-9c83-c7af89f1865b](https://github.com/CyclopsMC/IntegratedDynamics/assets/24835664/600b97a7-3910-4eaf-99f5-78582ef7dadc)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by ArsiTheFox** [comment]
?
