### ISSUE TITLE
World Reader "TPS" Value not responding to current dimension/server TPS

### ISSUE THREAD

**Issue by ConnorMiner** [CyclopsMC/IntegratedDynamics#1325]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using a World Reader in a world suffering from TPS lag, the "TPS" value outputted by World Readers don't respond accordingly.

#### Steps to reproduce the problem:

1. Place a World Reader and get it's "TPS" value
2.  (Optional) Use a Display Panel to show the value graphically
3. Create a bunch of TPS lag
4. World Reader still reports a "TPS" value of "20.0"
![2024-02-09_23 17 27](https://github.com/CyclopsMC/IntegratedDynamics/assets/32756365/efc9b8e2-be00-4bc0-b7ed-de3219b390ac)

#### Expected behaviour:

The World Reader's "TPS" value should correspond to the dimension/server's actual TPS.

____

#### Versions:

- This mod: 1.21.1
- Minecraft: 1.20.1
- Forge: 47.2.19

#### Log file:

https://pastebin.com/DtRVVPgc

**Comment by rubensworks** [comment]
Thanks for reporting!
