### ISSUE TITLE
It is not possible to pipe items from mechanical_squeezer

### ISSUE THREAD

**Issue by gjmhmm8** [CyclopsMC/IntegratedDynamics#1328]
#### Issue type:

- :bug: Bug 

____It is not possible to pipe items from mechanical_squeezer

#### Steps to reproduce the problem:

1. ...It is not possible to pipe items from mechanical_squeezer

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@gjmhmm8 Could you fill in the mod and minecraft versions? And a concrete way to reproduce the problem?

**Comment by gjmhmm8** [comment]
1.20.1

**Comment by gjmhmm8** [comment]
pipez

**Comment by gjmhmm8** [comment]
pipe can't but hopper can

**Comment by rubensworks** [comment]
There's not much I can do without any details to reproduce the problem.
I suggest you open a bug report on the pipez issue tracker.

**Comment by gjmhmm8** [comment]
I checked, only the output is supported below, the other faces are not supported, it's better you ...

**Comment by gjmhmm8** [comment]
I checked, only the output is supported below, the other faces are not, it would be better to optimize this issue
