### ISSUE TITLE
Constant / K - Should have only one argument, and  a different name?

### ISSUE THREAD

**Issue by void-spark** [CyclopsMC/IntegratedDynamics#1329]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:
There is a 'Constant / K' in the logic programmer.
It takes two arguments, and it's output is the first argument.
The second argument seems to be ignored.
Since it's unused, it would be nice if the second argument could be removed, or at least documented why it's there :)
Also the name seems wrong.
A constant would be a unchanging value, like actually the 'Integer'/'Double' etc are.
But this is more like a Reference?, it points to the value of another variable card.

Note that I use these a lot actually, if I want a variable card that always matches a variable card in the variable store,
to use in a display for example, and that will keep matching it even if I change the 'source' card :)
It's not the same as a copy, since those don't change with the original card.
It's a little bit like a proxy I guess, with far less parts and restrictions :)

Maybe there is a better way of doing the same, I could not find it :)
Or maybe there should be a better way of doing the same :D

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I have no intention to change the name. It's a well-known name in combinatory logic :-)
See here for example: https://en.wikipedia.org/wiki/Combinatory_logic#Examples_of_combinators

<blockquote><div><strong><a href="https://en.wikipedia.org/wiki/Combinatory_logic#Examples_of_combinators">Combinatory logic - Wikipedia</a></strong></div></blockquote>

**Comment by void-spark** [comment]
Ok, I guess I don't do functional languages a lot, what about the 2 arguments? :)

**Comment by void-spark** [comment]
Ahh, right, ID is the one that has one argument and does the same, I thought it gave the variable id.. :)

**Comment by void-spark** [comment]
And I guess with constant you can bind the first argument, which leaves you with a operator with one input, which ignores its input and always outputs the value you bound. Can use that as the start of a pipe or so I guess? But you could also have a constant which does that without having to bind it, set the value directly when you put constant in a value card :)
