### ISSUE TITLE
Generator doesnt work

### ISSUE THREAD

**Issue by Oddvin** [CyclopsMC/IntegratedDynamics#1330]
#### Issue type:

- mod malfunction

____

#### Short description:

Generator doesnt work with any fuel

#### Steps to reproduce the problem:

Place generator
Insert Fuel

#### Expected behaviour:

Generator produce FE

____

#### Versions:

IntegratedDynamics-1.20.1-1.21.2.

**Comment by rubensworks** [comment]
What fuel are you trying exactly?

**Comment by Oddvin** [comment]
Coal, charcoal, planks, logs, sticks. Tried pretty much everything that
could come to mind

tir. 5. mars 2024, 08:55 skrev Ruben Taelman ***@***.***>:

**Comment by rubensworks** [comment]
Did you connect it with anything that can consume the enery, such as a battery?

**Comment by Oddvin** [comment]
Yes, I did. I tried to connect it to a battery, i also went into my old
world where i have a setup i know work. But that was also a no go, The
battery had somewhat of a charge. But generator wouldnt run no matter the
fuel

tir. 5. mars 2024, 12:28 skrev Ruben Taelman ***@***.***>:

**Comment by rubensworks** [comment]
Ok, thanks checking!

**Comment by Oddvin** [comment]
no problem :)

**Comment by rubensworks** [comment]
Seems to be working just fine here on my end.
I guess some other mod in your pack is breaking things.
I'd suggest finding what mod it is, and reporting the issue to that mod's issue tracker.
