### ISSUE TITLE
placing logic cables using a Dank Storage in construction mode deletes the dank and all it's contents 1.19.2

### ISSUE THREAD

**Issue by Old-Man-D** [CyclopsMC/IntegratedDynamics#1332]
I am using Integrated Dynamics 1.19.2-1.20.2 and Dank Storage 1.19.2-5.1.6 (the modpack is ATM8, version 1.1.0).  

I placed some redstone writers, redstone readers, facades, and logic cables in a dank storage in construction mode and attempted to place a redstone writer.  It deleted the dank and all it's contents.  It did not crash.

I have been told by a source that this can be traced back to this line https://github.com/CyclopsMC/IntegratedDynamics/blob/release-1.19/src/main/java/org/cyclops/integrateddynamics/item/ItemBlockCable.java#L98

**Comment by rubensworks** [comment]
Thanks for reporting!
