### ISSUE TITLE
Achievement does not complete after fix error

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1335]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I fix error then the achievement is not occured

#### Steps to reproduce the problem:

1. Open in-game manual book and try the part "The Value of Operators"

2.1 Open Logic Programmer
2.2 Find "Integer", create a Variable Card "4" with Integer 4, put it to inventory
2.3 Create a Variable Card "9" with Integer 9, put it to inventory
2.4 Find "Operator", type "Add...", create a Variable Card "+" with Arithmetic Addition Operator, put it to inventory
2.5 Find "apply", put cards "+" and "4", create a Variable Card with result "4+", put it to inventory
2.6 Put cards "4+" and "9", create a Variable Card with result "4+9", put it to inventory

3.1 Put card "4+9" to Display Panel, can see error message, because other cards are still in the inventory
3.2 Put cards "4", "9", "+", "4+" to Variable Store in the same network
3.3 There is no achievement
3.4. Go to Display Panel, remove card "4+9" and put it in the slot again
3.5 There is achievement

#### Expected behaviour:
There should be achievement notification on the step 3.3

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.21.2.jar 
- Minecraft: 1.20.1
- Forge: forge-1.20.1-47.1.100-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This is how it's supposed to work. The advancements will only trigger upon completing a chain of operators by inserting the final part into the display panel.
