### ISSUE TITLE
Wrong alignment of item in the slot for "Ingredients" operation

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1336]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Small cosmetic issue: alignment of item is wrong, see the screenshot

![sshot](https://github.com/CyclopsMC/IntegratedDynamics/assets/96169906/5d3afdef-d33b-47fd-bae5-a65f8607b4fa)

#### Steps to reproduce the problem:

1. Open Logic Programmer
2. Select "Ingredients"
3. Select "Item"
4. Press "+"
5. Try to put Chest to slot

#### Expected behaviour:

Center of item should be centered in the slot, but in fact the left border of item is centered

Other issues:
"Storage Terminal Filtering" part of in-game manual: "To do this, open up a Logic Programmer go to the Predicate type"
-- expected: not "Predicate" but "Operator"
"Challenges" part of in-game manual: hover on "Smart Pressure Plate"
-- expected: hint does out of screen and should be split to several lines 

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.21.2.jar 
- Minecraft: 1.20.1
- Forge: forge-1.20.1-47.1.100-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!
