### ISSUE TITLE
Wrong URL-s in the in-game manual

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1338]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Looks like some URL-s in the manual is invalid

#### Steps to reproduce the problem:

1. Open Manual, go to page "Clock with sword"
2. Click "Web Version" icon
Invalid URL is
https://integrateddynamics.rubensworks.net/book/tutorials/tutorials/click_sword.html
Valid URL is
https://integrateddynamics.rubensworks.net/book/tutorials/tutorials/integratedtunnels/click_sword.html

#### Expected behaviour:

Add "integratedtunnels" or similar part here and on the other similar pages

____

#### Versions:

Versions:
- This mod: IntegratedDynamics-1.20.1-1.21.2.jar
- Minecraft: 1.20.1
- Forge: forge-1.20.1-47.1.100-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!
