### ISSUE TITLE
No transfer of items in functional storage Not sure if bug

### ISSUE THREAD

**Issue by Pultex** [CyclopsMC/IntegratedDynamics#1339]
#### Issue type:

- :question: Question 

____

#### Question:

Is there a limit on the size of a list or is there a read limit on a active list from a inventory reader?

I have a functional storage controller that is read by a inventory reader some items are output fine others are not dispensed.

Odd part is if you crouch to look at the output tunnel you can see it shows the items in jade 
All 2000 items are shown but none can be extracted until a new set of the same item larger than the amount that was there prior 
So taking out 200 and putting it back will do nothing

I don't think I understand how Functional storage addresses it inventory I always thought it had a list of all items and a value to report how many are there 
So the list would be as large as the amount of individual items in the system

Now I think it is just acting like one MASSIVE chest and tracks each stack interdependently forcing ID to create a HUGE list and past its limit, but how does jade show that ID can see the items in the system just not get to them

It is sending them out an world output but tried a items export to barrel vanilla and it did not work either till I took and added more of the same items to the system

Stranger still the ID system is in control of  production of these Items and will make more if some are removed so it does know how many are there

I just wish I could show what it happening but now it is working and have no idea how to reproduce

Maybe it is a access limit with functional storage and ID item interface part as that is how it all works with Omnidirectional connectors linking it all

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Should work, but there may be some performance issues depending on how you use that list.
