### ISSUE TITLE
The system does not like barrels

### ISSUE THREAD

**Issue by Umber0010** [CyclopsMC/IntegratedDynamics#134]
While playing Skyfactory 3.0 I noticed that if used an item importer to put perishables into I wooden barrel it would, rather than consume the shackles the item there with a red 0, and after that mouse tweaks could be used to pull out items and send the number to the negative, so basically infinite leaves, Apple's, beef Wellington, aka anything that that can be composted, I believe that this is because the barrel doesn't have a true inventory, rather importing items gives it metadata.

**Comment by rubensworks** [comment]
The importer is just using the standard item handler capability, so it sounds like the barrels may have an issue with their implementation.
Could you report that on their issue tracker first?

**Comment by rubensworks** [comment]
@Umber0010 Any updates? I'm closing this issue otherwise.
