### ISSUE TITLE
JEI Sync mode bug for Terminal

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1340]
#### Issue type:

- :bug: Bug 

____

#### Short description:

No sync on opening

#### Steps to reproduce the problem:

1. Open Terminal
2. Set mode "JEI Search Sync"
3. Select "Item Crafting" tab
4. Write something in the search string, right JEI panel will be filtered
5. Close Terminal
6. Re-open Terminal
7. JEI panel will NOT be filtered according to current search string

#### Expected behaviour:

If the ("JEI Search Sync" mode is ON) and (search string is not empty) and (tab is "Item Storage or "Item Crafting) then on opening Terminal JEI must be re-filtered.

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.21.2.jar
- Minecraft: 1.20.1
- Forge: forge-1.20.1-47.1.100-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!
