### ISSUE TITLE
Wrong work of facade with slabs

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1342]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Wrong view and placing of facades/slabs

#### Steps to reproduce the problem:

1. Create Facade
2. Combine Acacia Slab with Facade
3. Make floor with acacia slabs (upper half), make hole. put vertical cable line to the hole
4. Try set Acacia slab-facade. I could set it only to lower half and it is visible only from below and transparent from above

#### Expected behaviour:

Either ban facades with half-block items or make placing/view of them similar to usual slabs

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.21.2.jar
- Minecraft: 1.20.1
- Forge: 47.1.100

**Comment by rubensworks** [comment]
Thanks for reporting!
