### ISSUE TITLE
No Text when GUI is open logic programmer

### ISSUE THREAD

**Issue by Marcox2111** [CyclopsMC/IntegratedDynamics#1343]
#### Issue type:

- :question: Question 

____

#### Question:

Guys do you have any clue of why the GUI might not have text when i open the logic programmer

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/119309168/e79d5220-55fd-4715-831d-284d22979fb0)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
I heard a rumour in Discord that REI might be causing it. Do you have REI installed? If yes, could you try disabling it to see what happens?

**Comment by Marcox2111** [comment]
> I heard a rumour in Discord that REI might be causing it. Do you have REI installed? If yes, could you try disabling it to see what happens?

Fixed, so i can disable it when I'm using it, in particular just when you have a favorite item on the left top section

**Comment by rubensworks** [comment]
Could you report this to the REI issue tracker? Because it shouldn't be happening of course.
