### ISSUE TITLE
[1.19.2] After latest mod updates, lists are no longer importing more than 1 item at a time.

### ISSUE THREAD

**Issue by Saereth** [CyclopsMC/IntegratedDynamics#1349]
#### Issue type:

- :bug: Bug 

____

#### Short description:
After upgradeing to the lastest verion of Integraded dynamics mods and cyclopse core lists no longer trasnfer more than 1 item at a time.

#### Steps to reproduce the problem:
This video shows it most accurately.

https://youtu.be/1sGwvTlP5UY

#### Expected behaviour:

I would expect list filters to still transfer an entire stack when set to 64
____

#### Versions:

- This mod: IntegratedDynamics-1.19.2-1.22.0.jar
- Minecraft: 1.19.2
- Forge: 43.3.8

- integratednbt-1.19.2-1.6.0.jar
- IntegratedTerminals-1.19.2-1.4.13.jar
- IntegratedTunnels-1.19.2-1.8.26.jar
- CyclopsCore-1.19.2-1.19.1.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: see if this is related to https://github.com/CyclopsMC/IntegratedTunnels/commit/7e71f9dd149d9460568f6d91354418348521c51c
