### ISSUE TITLE
Bug: Redstone Reader, and Redstone

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#135]
When placing a T of redstone, and the repeater at the top of the T, the signal is not read, even when the redstone appears to branch out a bit to the reader.

Shots are [Here](https://InfinityCommunicationsGateway.net/pub/Minecraft/Shots/#files%2FIntegrated%20Dynamics)

**Comment by rubensworks** [comment]
I fixed all the cases, except for the reader that is placed on top of a repeater, because you could argue that the redstone value is encapsulated in the repeater there, and is not meant to be read from that side.

**Comment by BiatuAutMiahn** [comment]
Thank you, and good job!
