### ISSUE TITLE
Autocrafting for Create Crushing Wheels

### ISSUE THREAD

**Issue by djmattyg007** [CyclopsMC/IntegratedDynamics#1350]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I want to be able to autocraft Create Crushing Wheels with Integrated Dynamics. Ideally I'd be able to make anything that can be made with Create's Mechanical Crafters. This requires support for recipes that are larger than a 3x3 grid. Some modpacks have mechanical crafting recipes that can go to 9x9 grids.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Recipes can be of any size. It's just the UI that only supports a fixed 3x3 grid.
If you want to create larger recipes, you can use the operators for recipes in the logic programmer.
