### ISSUE TITLE
Ingr.with_item and Ingr.with_fluid do not convey size/amount informations

### ISSUE THREAD

**Issue by RuelYasa** [CyclopsMC/IntegratedDynamics#1351]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using Ingr.with_item, the inserted item's amount is always 1, no matter what the second input is. The Ingr.with_fluid shows similar behaviours, where the amount of the fluid is always 1000mB.

Besides, applying these operators to empty Ingredients always produce an empty Ingredients.

#### Steps to reproduce the problem:

1. Create an Ingredients, an Integer and an Items by logic programmers.
2. Use Ingr.with_fluid with the cards to create a new varible.
3. Put it in a display panel and check the output.

#### Expected behaviour:

The inserted item's amount isn't 1.
____

#### Versions:

- This mod: 1.21.3
- Minecraft: 1.20.1
- Forge: 47.1.105 (NeoForge)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I followed your exact steps, and I am able to successfully create an ingredient with items/fluids that keep their given amounts.

**Comment by RuelYasa** [comment]
Sorry for late reply! I tried it again recently, and the issue still occurred. Here are the variable cards:
![1](https://github.com/CyclopsMC/IntegratedDynamics/assets/172525184/96cdc615-2586-44fc-ab19-e004f7d4394f)

![2](https://github.com/CyclopsMC/IntegratedDynamics/assets/172525184/b9be1da8-9a65-40d9-80cc-e9390f8766d5)

![3](https://github.com/CyclopsMC/IntegratedDynamics/assets/172525184/8435023f-46c3-4612-858d-d33064297d91)

![4](https://github.com/CyclopsMC/IntegratedDynamics/assets/172525184/eef622fd-2f30-466c-b0ec-52c71cbb4cb9)

Did I wrongly used the operators? Thank for your consideration!

**Comment by rubensworks** [comment]
I see you used the value 23 as integer.
Are you aware that this is the _index position_ in the ingredient, and not the amount for the item?
For specifying the amount of the item, you need to encode the amount when creating the item itself.
