### ISSUE TITLE
Inconsistent behavior of Labeller for non-variable items.

### ISSUE THREAD

**Issue by markuskoeppen** [CyclopsMC/IntegratedDynamics#1353]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using the Labeller to rename initialized variables, the name field is updated to the current name of the variable upon adding it. However, this isn't the case for non-variable items, which can also be renamed using the Labeller.

#### Steps to reproduce the problem:

1. Get a programmer and a labeler.
2. Create a Boolean false variable and name it "Named" in the programmer.
3. Get a stone sword. Rename it "Also named" in an anvil or a Labeller.

4. Open a Labeller and add the variable card. The name field will now read "Named".
5. Remove the variable card.
6. Add the stone sword. The name field will still be empty.

#### Expected behaviour:

The name field contains the string "Also named" in step 6.

____

#### Versions:

- This mod: 1.22.0
- Minecraft: 1.20.1
- Forge: 47.3.0

First found in ATM9 NF, then reproduced in raw forge install.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by markuskoeppen** [comment]
Correction: Only happens in connection with #1352.
