### ISSUE TITLE
Variable Cards lose name when being copied.

### ISSUE THREAD

**Issue by markuskoeppen** [CyclopsMC/IntegratedDynamics#1354]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When copying a named variable card, the name is transferred to the new card and the original card loses its name.

#### Steps to reproduce the problem:

1. Get a Labeller.
2. Get a Logic Programmer.
3. Get 2 Variable Cards.
4. Using the Programmer, create a Boolean false variable. Use the built-in labelling function to call it "Named". Write it to one of the variable cards.
5. Combine the created variable card with the uninitialized variable card in a crafting table.
6. The new variable card is now named "Named". The original variable card is now named "Variable Card" (due to having a new ID).

#### Expected behaviour:

Both variable cards are named "Named".

____

#### Versions:

- This mod: 1.22.0
- Minecraft: 1.20.1
- Forge: 47.3.0

Originally found in ATM9 NF. Confirmed in raw forge install.

**Comment by rubensworks** [comment]
Thanks for reporting!
