### ISSUE TITLE
Player simulator block positions are completely broken

### ISSUE THREAD

**Issue by Vectrobe** [CyclopsMC/IntegratedDynamics#1357]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When attempting to use the player simulator for any "item place" events, such as with using lava buckets, the placement position is completely broken and doesnt seem to follow any logical behavior regarding where the module itself is facing.

North facing seems to work normally?
Up facing places to the north and down one tile.
East, West, South and Down facing will all try to place at the most south tile possible, seems like the range is 3 blocks?

#### Steps to reproduce the problem:

test with a player simulator facing in each direction and with something like lava or water buckets

#### Expected behaviour:

It should either place at the furthest distance possible in the correct direction the module is facing, or not at all

For blocks that item placing will interact with, say bonemeal on a sapling or a lava bucket onto a create blaze burner, it should *only* interact with the target block directly in front and not try to place somewhere around it instead like its current behavior, currently only modules facing north follow this, if you have a module facing up it ignores the target and places the lava/water/etc on the tile one north and one down to it.

____

#### Versions:

- This mod: 1.22.1
- Minecraft: 1.20.1
- Forge: neo 47.1.106

#### Log file:
none generated/not applicable

**Comment by rubensworks** [comment]
Thanks for reporting!
