### ISSUE TITLE
Performance issue for Storage Terminal

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1359]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Since some size of storage opening of storage terminal with several seconds lag

#### Steps to reproduce the problem:

1. Just open/close storage terminal when number of items is a bit more than one full screen 
storage is 2 colossal chests 5x5x5 with item interface
- it's not important, is it portable or fixed storage terminal
- size of grid is not important (lag is the same for smallest size)
- no lags with use grid of Refined Storage mod for the same chests
- no lags with interface of the chests (instant open/close)
- no lags in the world when terminal is closed
- some lags during moving mouse over grid
- it's not important, if there are animated items in visible part
- there are some machines working, but insertion to storage is not very big (1-10 items per second)
- there are no crafting tasks
- no lags during change search filter text and update grid
- but lags between clicks to insert several stack of items from inventory to storage

I made 2 profiles for spark them opening/closing interface multiple times
____

#### Versions:

- This mod: 1.20.1-1.22.1
- Minecraft: 1.20.1
- Forge: 1.20.1-47.1.100

#### Profiler output:

Using
https://spark.lucko.me/
![integrated](https://github.com/CyclopsMC/IntegratedDynamics/assets/96169906/ed159dde-b24c-4783-8e82-ce9f8a7a03ba)
[spark.zip](https://github.com/user-attachments/files/16102795/spark.zip)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Notes to self:

- Lag is caused server-side during init and on updates.
- Some of this logic can probably be moved off the main server thread.
- Just to some profiling myself with a huge network (I can simulate one with Colossal Chests).

<img width="1501" alt="Screenshot 2024-07-16 at 16 36 20" src="https://github.com/user-attachments/assets/5d3f17fc-ad7e-4e32-a2c4-eae15d28e9e9">
