### ISSUE TITLE
[Feature] Special Comparison Operator

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#136]
Now I don't know what this would be called but it would be useful in some cases:
If Variable A is true Then output would be Variable B

For example:
```
If $VarA {
    Return $VarB
}
```
```
If Contains(EntityList(),Entity("Chicken")) {
    Return Len(EntityList())
}
```

**Comment by rubensworks** [comment]
The problem is that you'll also need a value that is returned when A is false. In that case, the difference with the choice operator is minimal, so you should be using that one then.
