### ISSUE TITLE
Cosmic ray bug in startup: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Fuyukai** [CyclopsMC/IntegratedDynamics#1360]
#### Issue type:

- Bug

____

#### Short description:

Game crashes on startup

#### Steps to reproduce the problem:

I really don't know. Sorry.

#### Expected behaviour:

Game doesn't crash.

#### Versions:

- This mod: 1.22.1
- Minecraft: 1.20.1
- Forge: (Neo) 47.1.106

#### Log file:

Crash & Latest.log: https://gist.github.com/Fuyukai/50c584ffca487ef3a90506f01d444f47

#### Additional

I've named this a "cosmic ray" bug as it happened randomly once in the space of about three hundred launches, and fixed itself without any change on the next boot, so it's 50/50 on being an actual bug or a DRAM error.

**Comment by PoolloverNathan** [comment]
Nice, the Java builtins broke!
