### ISSUE TITLE
var prog not showing names

### ISSUE THREAD

**Issue by MCBEModder2020** [CyclopsMC/IntegratedDynamics#1362]
#### Issue type:

- :bug: Bug 

____

#### Short description:
"A Picture says a thousand words" - idk who
![image](https://github.com/user-attachments/assets/e41ec0e2-bddc-4ba2-8432-ef456b4fcc6a)

#### Expected behaviour:

____

#### Versions:

- This mod: 1.22.1
- Minecraft: 1.20.1
- NeoForge: 47.1.106

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MCBEModder2020** [comment]
also can i tag onto this; rei recipe fill does not fill in the crafting area in the storage terminal

**Comment by rubensworks** [comment]
Can you try without rei installed?
Also, can you share your client logs?

**Comment by MCBEModder2020** [comment]
it says smth abt cant cast some type related to rei crafting table filling
it seems reipc does not make your jei plugin work perfectly

**Comment by rubensworks** [comment]
Could you share the logs?
