### ISSUE TITLE
No Fluid Sounds

### ISSUE THREAD

**Issue by Natanaelel** [CyclopsMC/IntegratedDynamics#1363]
#### Issue type:

- :bug: Bug 

____

#### Short description:
LiquidChorus and MenrilResin fluids/buckets has no sound when picking up fluid blocks with empty bucket or when interacting with tanks.
Basically FluidType.getSound(SoundAction) is null for the fluids.

#### Steps to reproduce the problem:

1. Place liquid chorus from a bucket.
2. Pick it up with an empty bucket.

#### Expected behaviour:

There being a sound when picking it up.

____

#### Versions:

- This mod: 1.21-neoforge-1.21.5
- Minecraft: 1.21
- NeoForge: 21.0.103-beta

**Comment by rubensworks** [comment]
Thanks for reporting!
