### ISSUE TITLE
[1.20.4] startup server crash

### ISSUE THREAD

**Issue by MSandro** [CyclopsMC/IntegratedDynamics#1364]
#### Issue type:

- :bug: Bug 

____

#### Short description:
can't start server with Cyclope & Integrated Dynamics
It might be a compatibillity issue. I've tried to add the mods to my Modpack.
https://www.curseforge.com/minecraft/modpacks/stonefactory/files/5301385

#### Steps to reproduce the problem:

1. add Integrated Dynamics & Tunnels + Dependencies to the Modpack.
2. start the server
3. crash

#### Expected behaviour:
the server should start with the mods as usual.
____

#### Versions:

- This mod: Cyclope 1.19.2
- Minecraft:  1.20.4
- NeoForge: 20.4.237

#### Log file:
https://pastebin.com/s2s1kmHm

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MSandro** [comment]
after starting the server a few times, it worked.
weird...

**Comment by MSandro** [comment]
will this fix be backproted to 1.20.4?
Just noticed the CyclopeCore Update for 1.21 on Curseforge

**Comment by rubensworks** [comment]
I wasn't planning to, since I'm not actively maintaining 1.20.4 anymore.
But I'll look into pushing a quick fix for it.

**Comment by MSandro** [comment]
thank you very much.
