### ISSUE TITLE
Silk touch effect on despawning or breaking Enriched Menril Log and Menril leaves.

### ISSUE THREAD

**Issue by valipopescu** [CyclopsMC/IntegratedDynamics#1365]
#### Issue type:

- :bug: Bug 

____

#### Short description:
1.21 Minecraft neoforge without any other mods installed.
The enriched menril logs and menril tree leaves drop as if mined with silk touch. 

#### Steps to reproduce the problem:
Install the latest version of neoforge on 1.21 with the latest version of Integrated Dynamics. Find a menril tree or grow one from a cheated in sapling. Try to mine the logs and leaves or leave the leaves decay naturally.

1. ...

#### Expected behaviour:

Expecting the logs to be dropping the crystalized menril chunks, meanwhile leaves to drop menril sapling and menril berries along with sticks. The current behaviour should be only when using silk touch or shears in the case of leaves. 

____

#### Versions:

- This mod:  Integrated Dynamics
- Minecraft:  1.21
- Forge:  neoforge latest (21.0.98)

#### Log file:
There is nothing related to be found in the logs and no log entries are produced even with debug active.
.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by jstansel** [comment]
Confirmed. Mod versions:
Neoforge 21.0.98
Integrated Dynamics: 1.21.5
Cyclops Core: 1.19.2

Also, the issue persists with other Neoforge versions:
 * 21.0.86
 * 21.0.112
