### ISSUE TITLE
[Bug] offset enhancement not working on servers (1.21)

### ISSUE THREAD

**Issue by micrwvae** [CyclopsMC/IntegratedDynamics#1367]
#### Issue type:

- :bug: Bug 

____

#### Short description:

seems to be a multiplayer issue

effect of the offset enhancement doesnt get applied to the part its right clicked on

-bug didnt occur in singleplayer with only integrated dynamics related mods
-bug didnt occur in singleplayer w the modpack
-bug did occur in multiplayer of the modpack
-unfortunately i dont have a server available to test only id related mods in multiplayer

#### Steps to reproduce the problem:

1. place a cable and a part that can be offsetted
2. right click the enhancement on the cable part
3. pop up text above the hotbar says the offset has been increased to 0

#### Expected behavior:

offset gets increased by the value that the enhancement displayed

____

#### Versions:

![image](https://github.com/user-attachments/assets/11fa4f01-76e5-416c-98c7-68a0d1dae150)

- This mod: 1.21.9
- Minecraft: 1.21
- Forge: neoforge 21.0.114-beta
- Modpack: AllTheMods 10 version 0.17 with id and other mods in the screenshot updated

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This seems to be working fine in SMP with just ID mods installed.
There may be another mod in your pack that influences/breaks offset application.

I suggest you report this to your modpack's issue tracker, and link back here.
Happy to make changes on my end if this would be needed.

**Comment by reddi1** [comment]
the recipe in `enhancement_offset.json` is wrong for 1.21
```
"result": {
    "id": "integrateddynamics:enhancement_offset",
    "nbt": {
      "value": 4
    }
  }
```
should be
```
"result": {
    "id": "integrateddynamics:enhancement_offset",
    "components": {
    	"integrateddynamics:part_enhancement": 4
	}
    }
  }
```
