### ISSUE TITLE
2 Advancements are broken | 1.21 | Found in ATM10 v0.18 | v1.21.8

### ISSUE THREAD

**Issue by john13210** [CyclopsMC/IntegratedDynamics#1368]
#### Issue type:

- :bug: Bug 
      **2 Advancements are broken
        Crafting² Interface
        Crafting² Writer**
 
 **as soon as you craft something these 2 quests are completed**

#### Versions:

- This mod: IntegratedDynamics-1.21-neoforge-1.21.8.jar
- Minecraft: 1.21
- Forge: Neoforge-21.0.115

**It was spotted on atm10 modpack , im too lazy to test things out like that**

**Comment by rubensworks** [comment]
Thanks for reporting!
