### ISSUE TITLE
Menril Glass can not be produced.

### ISSUE THREAD

**Issue by valipopescu** [CyclopsMC/IntegratedDynamics#1369]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Menril glass can not be created.

#### Steps to reproduce the problem:

1. Squeeze or bucket into the drying basin a bucket of menril resin liquid, while the basin has a piece of glass inside.
2.  Wait for the drying to occur
3. Observe a crystalized menril in the basin instead of menril glass.

The bug does happen with the mechanical basin where it doesn't consume the glass but it ignores it.
#### Expected behaviour:

The menril glass should be there instead. 
____

#### Versions:

- This mod:  1.21-neoforge-1.21.9 (latest)
- Minecraft: 1.21
- Forge: Neoforge 21.0.133 (latest)

#### Log file:

Does not seem to produce any logs even with debug on.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by pikminman13** [comment]
would like to add that this also applies to the latest 1.20.4 version used in ftb neotech (1.21.5)

**Comment by rubensworks** [comment]
I couldn't reproduce this exact problem (probably due to recipes loading in a different order), but I encountered another possibly related problem that will probably fix this as well. Please let me know if the next release does not fix the problem on your end.
