### ISSUE TITLE
Refrencing another variable card causes repeated game crash and loss of acess to world

### ISSUE THREAD

**Issue by BrandonThomas02** [CyclopsMC/IntegratedDynamics#1370]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Referencing another variable card in a network causes crash to desktop

#### Steps to reproduce the problem:

1. place variable store connected to a cable with a block reader facing a furnace (works with any block or tile entity)
2. in the block reader, get the nbt data of the block (id 0)
3. create a variable string with the value "id" (without quotations) (id 1)
4. create a variable using the NBT.getTag() with the nbt data being the data obtained from the block reader and the tag being the id string (id 2)
5. add a Display Panel to the cables connected to the furnace and variable store
6. place variables id 0 and 1 (steps 2 and 3) into the variable store
7. place the variable id 2 (step 4) into the display panel
8. game crashes

#### Expected behaviour:

id "minecraft:furnace" should appear on the display panel (or whatever block the block reader is facing)
____

#### Versions:

- This mod: IntegratedDynamics-1.20.4-neoforge-1.21.5
- Minecraft: 1.20.4
- Forge: neoforge 20.4.237

#### Log file:
https://pastebin.com/gheUtNuT

**Comment by rubensworks** [comment]
Thanks for reporting!
