### ISSUE TITLE
Terminal Storage not working properly on SMP

### ISSUE THREAD

**Issue by Dvginkel** [CyclopsMC/IntegratedDynamics#1375]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Contents of chests / drawers randomly not showing up when using the (portable)  storage Terminal on multiplayer (server)

#### Steps to reproduce the problem:

1. Place multiple chests / drawers (from my tests it seem to happen with more then ~ 10 (double) chests / drawers connected). 
2. Connect Item Interface's to the chests or to the storage controller if you test / try with functional storage.
3. open Terminal Storage gui items are shown, then closing GUI and trying to reopen often causes the error on this line  https://mclo.gs/vSt4nYo#L668

#### Expected behaviour:

Expectation is to have same experience as in singleplayer, where I tested this aswell and there it works fine without any problems. 
Might be something about the enchantment registery could have something to do with it :-) (I was told by kroeser on discord)

Also if anything is unclear or I messed up something don't hessitate to contact me on discord or here, I'll keep an eye out comming days :-)
____

#### Versions:

- This mod: ATM 10 modpack (V 0.27)
- Minecraft: Minecraft 1.21.1
- Forge: Neoforge (version 21.0.151)

#### Log file:

https://mclo.gs/vSt4nYo

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: wrap nbtops with registry access holder in ingredient serializers and ingredient collection serializers (will introduce some breaking changes). Test this myself with some enchanted items in the network.
