### ISSUE TITLE
Crash when using the world item importer

### ISSUE THREAD

**Issue by micrwvae** [CyclopsMC/IntegratedDynamics#1376]
#### Issue type:

- :bug: Bug 

____

#### Short description:
crashed after trying to pull a unenchanted diamond helmet from my player using the world item importer
![2024-08-08_22 57 30](https://github.com/user-attachments/assets/209b08ef-305e-4a10-a9d3-c96f0afba692)
![2024-08-08_22 57 20](https://github.com/user-attachments/assets/ff4d511b-5281-4864-81fb-4c7c7b02def9)

#### Steps to reproduce the problem:

1. place the blocks shown in the screenshot
2. configure a variable card to the item that is to be pulled
3. step in the world importer range

#### Expected behaviour:
armor gets pulled from the player without crash

____

#### Versions:

- This mod: 
![image](https://github.com/user-attachments/assets/49617c09-11f1-4ba6-9168-371b299116a8)

- Minecraft: 1.21
- Forge: neo 21.0.151

#### Log file:
single player with the allthemods 10 modpack v0.27
https://mclo.gs/7gzLTb5

recreated with only id series mods
https://mclo.gs/Erp7UOC

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by micrwvae** [comment]
of course
