### ISSUE TITLE
Redstone writer don't change signal when variable changes value in mc1.21.1

### ISSUE THREAD

**Issue by arghaan** [CyclopsMC/IntegratedDynamics#1377]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Redstone writer does not change the signal when the variable value changes in 1.21.1. However, it works fine in 1.20.1.

#### Steps to reproduce the problem:

1. Just a chest, an inventory reader, a redstone writer, and redstone.
![image](https://github.com/user-attachments/assets/075ffa6b-fec6-4fb8-84bb-19e37b217da9)
2. Write variable e.g. "Inventory not empty" and place to writer. When the inventory changes, writer see the variable value but output signal not changes. If replace redstone the signal is on.
![image](https://github.com/user-attachments/assets/4e337a66-43fc-4e9f-bbfb-5553270e44e2)

I checked its behavior in 1.20.1 and writer works normal
I think there is some issue with the block update.
____

#### Versions:

- This mod: 1.23.2
- Minecraft: 1.21.1
- NeoForge: 21.1.4

Installation is clean
![image](https://github.com/user-attachments/assets/e3a4247a-b825-42f4-8f98-70e89cca8998)

**Comment by rubensworks** [comment]
Thanks for reporting!
