### ISSUE TITLE
Regex Scan causing conflicting display panel results

### ISSUE THREAD

**Issue by kirjorjos** [CyclopsMC/IntegratedDynamics#1378]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://github.com/user-attachments/assets/60e9531e-edd4-45b7-85d7-bca227b5d5f1)
![image](https://github.com/user-attachments/assets/ea4a5675-4b5d-4963-bdad-8533b98b0e60)

#### Steps to reproduce the problem:

1. Make 2 string cards in the LP: "(?:.*?([^\(\s]*\([^\(]*?\)).*?)?" and "test1(test2(test3, test4), test5(test6, test7))"
2. Make an int 1 card
3. Use them in the regex scan operator "tab"
4. Put the result in a display panel and the references in a variable store

#### Expected behaviour:

The display panel behaves consistently and shows only a check or x, not both
____

#### Versions:

- This mod: Cyclops Core: 1.19.5
- CommonCapabilities: 2.9.2
- IntegratedDynamics: 1.23.0
- Minecraft: 1.19.2
- Forge: Client: 43.3.5
Server: 43.4.2

#### Log file:
Nothing mentioned in any logs or server console

**Comment by rubensworks** [comment]
Thanks for reporting!
