### ISSUE TITLE
FTB NeoTech 1.6.0 Crashed because of IntegratedDynamics

### ISSUE THREAD

**Issue by dev-cyprium** [CyclopsMC/IntegratedDynamics#1379]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:
1. Make a really simple network
2. Add a redstone reader
3. Add 3 redstone writters
4. Using the logic programmer make a simple logic 5 < 9
5. Insert the card into the redstone writter

It crashes... `network is null`

#### Expected behaviour:

____

#### Versions:
- This mod: 
  IntegratedDynamics-1.20.4-neoforge-1.21.5.jar
- Minecraft: 
  1.20.4
- Forge:
   Neoforge
 
Contacted FTB already, they didn't do anything. Please help my world is corrupted! I can't load.

#### Log file:

[latest.log](https://github.com/user-attachments/files/16575800/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You're not using the latest version, please try again with 1.21.7.

**Comment by dev-cyprium** [comment]
Sorry! Didn't notice there was a more recent version, updating

**Comment by dev-cyprium** [comment]
Thank you so much, I've never had my issue resolved so quickly, even with premium and paid supported software. Appreciate your work man
