### ISSUE TITLE
Feature: More animal/plant commands

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#138]
How about canShear, canBreed (is ready and/or can breed), Age (animals/plants), and canPlant

**Comment by rubensworks** [comment]
Note to self:

* [x] `IShearable#isShearable(ItemStack item, IBlockAccess world, BlockPos pos)`

* [x] `EntityLiving#getAge()`
* [x] `EntityAgeable#isChild()`
* [x] `EntityAgeable#getGrowingAge() == 0` can breed
* [x] `EntityAnimal#isInLove() == 0` is in love

* [x] `EntityAnimal#isBreedingItem(@Nullable ItemStack stack)`
* [x] `IPlantable#getPlantType(IBlockAccess world, BlockPos pos)` (on an `Item`)
* [x] `IPlantable#getPlant(IBlockAccess world, BlockPos pos)`
* [ ] `Block#canSustainPlant(IBlockState state, IBlockAccess world, BlockPos pos, EnumFacing direction, IPlantable plantable)` (Not possible)

* [x] Make custom wrapper for plant age. With Block Capabilities (introduce in CommonCaps: `BlockCapabilities#getCapability(IBlockAccess world, BlockPos pos, EnumFacing side) : T`). AGE capability.
