### ISSUE TITLE
Client Crash with productive trees wood as facade

### ISSUE THREAD

**Issue by micrwvae** [CyclopsMC/IntegratedDynamics#1380]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Client Crash when trying to render a facade made with the purple spiral wood from productive trees

#### Steps to reproduce the problem:

1. place a cable and make a facade with the purple spiral wood
2. place it on the cable
3. crash
3e. the purple spiral log worked fine, havent tried other blocks from productive trees

#### Expected behaviour:
not crashing

____

#### Versions:

- This mod: 
![image](https://github.com/user-attachments/assets/d898834e-c97a-40c3-bcef-180a3c1c1224)

- Minecraft: 1.21
- Forge: neo 21.0.114-beta
- discovered in atm10 v o.30 but recreated with the above mentioned mods

#### Log file:
https://mclo.gs/venz3yn

**Comment by rubensworks** [comment]
Thanks for reporting!
