### ISSUE TITLE
Redstone Writer doesn't update block status properly.

### ISSUE THREAD

**Issue by Ayrtonno** [CyclopsMC/IntegratedDynamics#1382]
#### Issue type:
- :bug: Bug 

____

#### Short description:
Redstone Writer doesn't update block status properly until the block that is pointing to is force-updated by replacing it or placing something adjacent to it.

#### Steps to reproduce the problem:
1. Place a redstone writer facing the block you want to give the redstone signal to (example: redstone lamp).
2. Place a boolean card set to 'TRUE' inside the first slot of the redstone writer that would turn on the lamp. 
3. Since the lamp is still ofo, place any block (exampe: cobblestone) adjacent to it to turn it on.

#### Expected behaviour:
Turning the redstone lamp on and off without forcefully updating the block status.

____

#### Versions:

- This mod: IntegratedDynamics-1.20.4-neoforge-1.21.7
- Minecraft: 1.20.4
- Forge: 20.4.237

____

#### Additional informations:
Same issue persists on latest mc versions (from 1.20 to 1.21), on different ID versions (1.21.2 to 1.21.7 for mc 1.20 and up to 1.23.2 for mc1.21)
Clean pack with only ID and dependencies installed.
Tried also using different neoforge versions, with no results.

**Comment by rubensworks** [comment]
Thanks for reporting!
