### ISSUE TITLE
Infobook crashing Server

### ISSUE THREAD

**Issue by Blacksmith-Sarec** [CyclopsMC/IntegratedDynamics#1383]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The Infobook cant find crafting recipes for the mod and its causing the server to crash

#### Steps to reproduce the problem:

1. Install Create Arcane Engineering V1.9 Server Pack onto a shockbyte Server
2. Attempt to start server

#### Expected behaviour:

The infobook will look for recipes for Integrated Dynamics items, fail to find them, and the server will crash
____

#### Versions:

- This mod: 1.18.2-1.17.0
- Minecraft: 1.18.2
- Mod loader version: Forge 40.2.9

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.18 is not being maintained anymore.

But I see only warnings in your log, not a real crash. Are you sure the game is actually crashing?

**Comment by Blacksmith-Sarec** [comment]
The server isnt starting, yes im sure its actually crashing.

**Comment by rubensworks** [comment]
Could you share the crashlog?

**Comment by Blacksmith-Sarec** [comment]
[latest.log](https://github.com/user-attachments/files/16688612/latest.log)

**Comment by rubensworks** [comment]
According to those logs, there is no crash, and the server started successfully:

> [21Aug2024 08:27:16.196] [Server thread/WARN] [ModernFix/]: Dedicated server took 79.252 seconds to load
