### ISSUE TITLE
EMI doesn't highlight missing ingredients for recipes in Storage Terminal

### ISSUE THREAD

**Issue by gold-me** [CyclopsMC/IntegratedDynamics#1384]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When crafting using the Storage Terminal, EMI does not highlight items that are missing for the craft. See screenshots below for comparison.

Crafting with Crafting Table:
![2024-08-20_17 58 31](https://github.com/user-attachments/assets/9bd0e6c7-b2c5-4b92-8ba5-824b25a6a273)

Crafting with Storage Terminal:
![2024-08-20_17 58 38](https://github.com/user-attachments/assets/772ba0a2-d7ca-47be-a176-f2e51329e681)

#### Steps to reproduce the problem:

1. Attempt to craft an item that you don't have all the items for in the Storage Terminal.

#### Expected behaviour:

Missing items should appear highlighted.

____

#### Versions:

<html><body><ul>
	<li>Just Enough Items [17.3.1.3]</li>
	<li>IntegratedDynamics [1.21.5
]</li>
	<li>IntegratedTerminals [1.4.13
]</li>
	<li>IntegratedTunnels [1.8.26
]</li>
	<li>IntegratedCrafting [1.1.7
]</li>
	<li>EMI Trades [1.3.0+mc1.20.4]</li>
	<li>EMI [1.1.10+1.20.4+neoforge]</li>
	<li>Cyclops Core [1.19.3
]</li>
	<li>CommonCapabilities [2.9.1
]</li>
</ul></body></html>

- Mod loader version: NeoForge 20.4.237

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This mod does not have explicit support for EMI, only JEI.
So if EMI does not follow JEI's API, then explicit support must be coded in.

**Comment by VozDeOuro** [comment]
Hello, I'm with the same issue, is there some fix on the way or not ATM ?

**Comment by weirdchildren** [comment]
> This mod does not have explicit support for EMI, only JEI. So if EMI does not follow JEI's API, then explicit support must be coded in.

Would it be possible to add support to EMI through the JEI compact. EMI is meant to be installed along JEI so they can work together so it is supposed to be easy to support when you already have JEI support. With that said you know more than me I'm just hoping for EMI support because it is the best recipe viewer IMO at the moment.

**Comment by rubensworks** [comment]
This will be fixed in the next update.
