### ISSUE TITLE
v1.23.0 and up - IntegratedDynamics-Compat (integrateddynamicscompat) has failed to load correctly

### ISSUE THREAD

**Issue by TryHackX** [CyclopsMC/IntegratedDynamics#1385]
All modifications updated. Forge stable (recomended) latest.

#### Issue type:

- :bug: Bug 

____

#### Short description:

Error loading mods

1 error has occurred during loading

IntegratedDynamics-Compat (integrateddynamicscompat) has failed to load correctly

java.lang.ExceptionInInitializerError: null

#### Steps to reproduce the problem:

1. ... Fix bug

#### Expected behaviour:

____

#### Versions:

- This mod: 1.23.2
- Minecraft: 1.20.1
- Mod loader version: Forge - 47.3.7

#### Log file:

Crash:
https://pastebin.com/Tj1HEtPx
Latest:
https://pastebin.com/ugKcjvdm

**Comment by rubensworks** [comment]
Thanks for reporting!
