### ISSUE TITLE
1.20.1 Neoforge Crash on Dedicated Server Start (Compat issue with Terrablender and Integrated Dynamics) claims NULL config

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedDynamics#1388]
#### Issue type:

- :bug: Bug 

- It crashes on dedicated server

____

#### Short description:

- A crash on startup

#### Steps to reproduce the problem:

1. Updated mods.

#### Expected behaviour:

1. No crashes
____

#### Versions:

- This mod: 1.23.2
- Minecraft: 1.20.1
- Mod loader version: 47.1.106 

#### Log file: 
Crash Log https://mclo.gs/v20QYHs
Log File https://mclo.gs/AtIf5H2
Debug File https://mclo.gs/ccUmNle

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest version. This has been fixed already.

**Comment by P3rf3ctXZer0** [comment]
There is no update beyond what I posted. https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/5658029

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/49/396/256/256/636077266568975656.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/integrated-dynamics/files/5658029">Integrated Dynamics</a></strong></div><div>A mod to take full and automated control of your appliances.
75.6M Downloads | Mods</div></blockquote>

**Comment by P3rf3ctXZer0** [comment]
Did you mean to release a version that was not made public? @rubensworks

**Comment by P3rf3ctXZer0** [comment]
Yeah 1.20.1 fix please :D

**Comment by rubensworks** [comment]
Ah, I misread, I thought this was for MC 1.21.
Looks like this also needs to be fixed on MC 1.20.1.

**Comment by Nevatalysa** [comment]
Also occurs on 1.19.2

This mod: 1.23.1
Minecraft: 1.19.2
Mod loader: Forge 43.3.5
Terrablender: 2.0.1.166

Crash log: https://mclo.gs/GJfwIWa

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/GJfwIWa">Forge 1.19.2 Crash Report [#GJfwIWa]</a></strong></div><div>1042 lines</div></blockquote>
