### ISSUE TITLE
Feature: Utility/Machine in use

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#139]
The ability to detect if a player is currently using a Machine/Utility block may be useful. As in, the player is accessing the Block's menu/interface. (inUse)

**Comment by rubensworks** [comment]
I'm not sure if that would be possible, but I can look into it.

**Comment by BiatuAutMiahn** [comment]
I must apologize, i feel like I'm giving you a lot of work, I just have a lot of ideas for automation.

**Comment by rubensworks** [comment]
@BiatuAutMiahn No worries, the aspects/operators you suggest should be fairly simple to implement, because this mod has been designed in such a way that makes it very easy for me to add them. I still have a lot of other plans for ID that _do_ require a lot of work though :)

**Comment by BiatuAutMiahn** [comment]
Ah ok, may I ask what your planning?

**Comment by rubensworks** [comment]
@BiatuAutMiahn My list is quite long, so I won't share it all. But the first things I'll be working on will be in-game documentation and wireless networks, which will be for version 0.7.0.

**Comment by BiatuAutMiahn** [comment]
ah ok, looking forward to it. However, and this is my personal opinion, I would prefer not to have wireless capabilities, with the following exceptions of course, it should be range limited without some kind of booster/repeater, and/or the ability to completely disable it in the configs. You could make it work like actual Wifi, Only information to/from things like readers/writers, but not item/fluid transfer, I think energy transfer is ok, but limited and upgradable.

Now, i suggest this because it can make the game too easy.

**Comment by rubensworks** [comment]
@BiatuAutMiahn Don't worry, I have some ideas to make it balanced ;) And as most things in this mod already are, wireless networks will be disableable.

**Comment by BiatuAutMiahn** [comment]
Right, with #17 I noticed that mostly when I was trying to move too fast, such as running, or using a boat
