### ISSUE TITLE
menril sapling not growing in atm9 to the sky

### ISSUE THREAD

**Issue by Yuuki-Shino** [CyclopsMC/IntegratedDynamics#1391]
#### Issue type:

- :question: Question 

____

#### Question:

hey guys wondering if im doing something wrong but i cant seem to grow menril trees in my atm9 to the sky world. ive spent tons of bone meal, and crouched a lot. all i can think is that im doing something wrong or its broken. does anyone have any ideas?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Can you try without any other mods installed?
