### ISSUE TITLE
Placing a Proxy or Materializer on a dedicated server causes client to crash

### ISSUE THREAD

**Issue by NioXen** [CyclopsMC/IntegratedDynamics#1392]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When running a dedicated server, placing a Materializer or a Proxy causes the client to crash with a Null Pointer Exception:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.registryAccess()" because the return value of "net.neoforged.neoforge.server.ServerLifecycleHooks.getCurrentServer()" is null
```

The server remains up and only reports a disconnection error.
```
[Netty Server IO #1/ERROR] [minecraft/Connection]: Exception caught in connection
java.net.SocketException: Connection reset
```

Interestingly this issue **does not** occur when running a single player game, or running a LAN game directly from the client - it only occurs when using a dedicated server.

If a world that already has these blocks placed is loaded on the server, then no client can connect to the server (but the server does not crash).

#### Steps to reproduce the problem:

1. Download the FTB Unstable 1.20 (MC 1.21) server files
2. Remove all mods except Integrated Dynamics, Integrated Terminals, Integrated Crafting, Integrated Tunnels, Common Capabilities, and CyclopsCore
3. Download the FTB Unstable 1.20 (MC 1.21) client files through FTB App
4. Remove all mods except those listed in step 2
5. Run the dedicated server with `run.bat` and a fresh world
6. Connect to the server
7. Try to place a Proxy or Materializer
8. Client crashes to desktop with a Null Pointer Exception

#### Expected behaviour:

I am able to place a Materializer or Proxy in the world

____

#### Versions:

- This mod: 1.23.1
- Minecraft: 1.21
- Mod loader version: Neoforge 21.0.167

Have reported the same issue on [FTB Modpack Issues](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5773) but have reproduced the problem here with only this mod installed (and thought it might be useful!)

#### Log file:

https://pste.ch/cezamepele.pl

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by NioXen** [comment]
Thank you for sorting this out and for the great mod! 🎉
