### ISSUE TITLE
Enriched menril logs are not logs?

### ISSUE THREAD

**Issue by halvalla01** [CyclopsMC/IntegratedDynamics#1393]
#### Issue type:

- :question: Question 

____

#### Question:

Whenever I play with integrated dynamic (amongst other mods), when I get some treecapitation tool, the enriched menril logs seems to not wanna join the bunch, and they stay in place in stead of being chopped down. They also aren't recognised as menril logs by veinminers like FTB Ultimine. What if enriched logs got removed entirely in favour of random crystallized menril drop chance from any menril log?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
You'll have to ask the mod author of your treecapitation tool to add support for these logs. I know other mods (I don't remember the names) have done similar things in the past.
