### ISSUE TITLE
How do I enable networkdiagnostics

### ISSUE THREAD

**Issue by Gogo64pro** [CyclopsMC/IntegratedDynamics#1396]
#### Issue type:

- :question: Question 

____

#### Question:
I am playing the modpack "Create:Arcane engineering and I have a giant network with 800000 items, the game lags a lot, because of this. I couldn't figure out how to enable networkdiagnostics, even though I traced a command /networkdiagnostics in the code, the curseforge's page said to use /integrateddynamics networkdiagnostics. Both of them didn't exist. I used the logging in the common config, but that only showed updates in real time and didn't say how much time each one was taking, Thanks v1.18.2 minecraft v1.17.0 mod"

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
You need to have op permissions (since the diagnostics allow teleporting).
That might be your problem here.

**Comment by Gogo64pro** [comment]
After opening to LAn with cheats on it still, doesn't show up? Does it have to be on a server?

**Comment by rubensworks** [comment]
If you can execute the `/op` command, you should also be able to access the diagnostics.

**Comment by Gogo64pro** [comment]
Even on a server with op, I don't have access to that command

**Comment by rubensworks** [comment]
Either another mod in your pack is breaking things, or the command is simply broken.
I don't have the bandwidth to maintain the MC 1.18.2 version of this mod anymore unfortunately, so I'm afraid I can't help you further.

I do recommend updating to a more modern MC version though, as many performance improvements have been implemented in this mod since then.
