### ISSUE TITLE
Can't place down a creative battery it seems

### ISSUE THREAD

**Issue by Jmpp2909** [CyclopsMC/IntegratedDynamics#1397]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash when placing down a creative battery
#### Steps to reproduce the problem:

Place down creative battery

#### Expected behaviour:

Not crash ig
____

#### Versions:

- This mod:  IntegratedDynamics-1.21.1-neoforge-1.23.5.jar
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.51

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share the crashlog?

**Comment by Jmpp2909** [comment]
Oh im very sorry, completely forgot 
Here it is
https://mclo.gs/03ebbrI


<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/03ebbrI">NeoForge 1.21.1 Crash Report [#03ebbrI]</a></strong></div><div>480 lines</div></blockquote>
