### ISSUE TITLE
Dragging ghost items/fluids/etc. from JEI/EMI into a logic programmer works only partially

### ISSUE THREAD

**Issue by WeaselOnaStick** [CyclopsMC/IntegratedDynamics#1398]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Dragging items from JEI/EMI into the logic programmer doesn't work everywhere, meanwhile dragging items from actual inventory works. This inconsistentcy doesn't look intentional.

You can see in the recording below I can successfully use a ghost JEI item (water bottle) for the Item() function, but I can't use the same technique when adding it as an item in a list (or any other operator that takes "Item" input). But I can do both normally if the item is in my inventory

https://github.com/user-attachments/assets/f2def07c-08b8-4eb6-902a-8f14cfc76098

____

#### Versions:

- This mod:  1.23.2
- Minecraft: 1.19.2
- Mod loader version: Forge 43.4.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by WeaselOnaStick** [comment]
Furthermore, operators that accept Item/Fluid variables, don't accept dragging in actual/ghost items at all, which I find very unintuitive

**Comment by Spontini** [comment]
> Thanks for reporting!

Can this fix please be pushed for 1.20.4?

**Comment by Jack-McKalling** [comment]
We never released a 1.20.4 version for Forge. There's only a release on 1.20.4 for NeoForge, but we don't support that one anymore.

**Comment by Spontini** [comment]
> We never released a 1.20.4 version for Forge. There's only a release on 1.20.4 for NeoForge, but we don't support that one anymore.

The same issue exist in 1.20.4 NeoForge. I tried to compile the code myself but wasn't successful due a lot of missing libraries.

**Comment by rubensworks** [comment]
I'm sorry, but 1.20.4 is not supported anymore. I recommend upgrading to 1.21, as many mods are a lot more stable there.
