### ISSUE TITLE
Battery autosupply mode isnt work for inventory items

### ISSUE THREAD

**Issue by Saereth** [CyclopsMC/IntegratedDynamics#1399]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Integrated Dynamics battery does not allow you to Shift + Right click to Auto supply power in inventory.

#### Steps to reproduce the problem:

1. Create energy battery
2. Give Battery Power
3. Place in hand and Shift + Right click.
4. Energy Battery does not give shimmer showing active.

#### Expected behaviour:

tooltip should change to show autosupply is enabled and power provided to inventory items
____

#### Versions:

- This mod: IntegratedDynamics-1.21.1-neoforge-1.23.6.jar
- Minecraft: 1.21.1
- Mod loader version: 
Neoforge 21.1.6

**Comment by rubensworks** [comment]
Thanks for reporting!
