### ISSUE TITLE
The wrong cable part data is exposed to The One Probe, showing different parts than targeted

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1401]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When looking at a cable part that is attached to a cable with more cable parts, The One Probe receives the data from the cable part that is on the side of the cable that is being targeted, regardless of what cable part is actually at the target. This shows conflicting information in the HUD.

![integrated probe part sides](https://github.com/user-attachments/assets/4eb129e5-ef82-4b8d-836a-b9d8d823f835)

In other words, the "targeted side" of the block you're looking at, is not enough to determine at what cable part you're looking, since the hitbox isn't a full block and each side has multiple faces that don't all belong to the same cable part.

#### Steps to reproduce the problem:

1. Place a cable
2. Attach a mono-directional connector to it
3. Also attach an omni-directional connector to it
4. Look at the side of the mono-directional one that is the same side as where the omni-directional one is attached to
5. The group ID from the omni connector is shown, but you're looking at the mono connector

#### Expected behaviour:

When looking at any cable part, the part you're looking at should be the one rendered data from in the HUD.

____

#### Versions:

- Dynamics: neoforge-1.23.6
- Core: neoforge-1.23.0-601
- CC: neoforge-2.9.4
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.51
- Other mods:
   - theoneprobe-1.21_neo-12.0.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
This also applies to 1.20.1. So if you need more version numbers, let me know.
