### ISSUE TITLE
Biome aspect of Block Reader is broken; its variable is self-referring

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1403]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The Biome aspect of the Block Reader shows "ERROR" as its current value, and when used, its card displays the error that the variable is referring to itself.

![integrated dynamics biome aspect setup](https://github.com/user-attachments/assets/830300ef-ac62-4226-a221-f9300106ea4c)

Considering that the aspect itself is already showing "ERROR" in its value render, the technical implementation of the aspect itself must be broken and not my variable/logic.

#### Steps to reproduce the problem:

1. Place a logic cable, and attach a block reader as well as a display panel to it
2. Open the block reader and insert a new **blank variable card** into the Biome aspect (notice the aspect's error value here already)
3. Put the variable card into the display panel and immediately notice the big red evaluation error in the UI

I also tested if the same thing happens when there is a partial or full block in front of the reader, and it seems that doesn't affect the issue.

#### Expected behaviour:

I expected the name of the current biome (in the case of the world I encountered the issue; "Forest", or as in the screenshot; "Beach") to be displayed on the display panel, without any errors happening in the reader.

____

#### Versions:

- Dynamics: 1.23.4
- Tunnels: 1.8.31
- Core: 1.19.5
- CC: 2.9.3
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.10 
- Other mods:
  - configured-forge-1.20.1-2.2.3
  - jei-1.20.1-forge-15.20.0.104
  - theoneprobe-1.20.1-10.0.2

Also tested with NeoForge for 1.21.1, but in that version the issue does NOT occur. Might be either due to the modloader used, or just the newer version of the mod. If you need the precise (NeoForge) version that the issue last occurred in, let me know.

**Comment by rubensworks** [comment]
Thanks for reporting!
