### ISSUE TITLE
Server crash.

### ISSUE THREAD

**Issue by Derek1256** [CyclopsMC/IntegratedDynamics#1404]
#### Issue type:

- :bug: Bug 

____

#### Short description:

World crash on Server: i am unsure if this is ID directly due to not being able to reproduce myself in SP but according to logs, im assuming its due to ID possibly having a compat issue with terrablender.

#### Steps to reproduce the problem:

not sure what to put as steps considering the above.

#### Expected behaviour:
The server to not crash when loading new chunks.

____

#### Versions:
Full mods list: https://pastebin.com/9hnXemwn
Dynamics: 1.23.9
core: 1.25.1
tunnels: 1.8.28
craft: 1.1.10
- This mod: 1.23.9
- Minecraft: 1.21.1
- Mod loader version: Neoforge 21.1.58

### Log file:
https://pastebin.com/Dt9mubjX 

```java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / integrateddynamics:meneglin]=net.minecraft.world.level.biome.Biome@56f919b9}]``` makes me believe its due to ID.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Derek1256** [comment]
not sure why i didnt try this before reporting, but putting it on my test server seems to have fixed whatever crash i was experiencing :D.
