### ISSUE TITLE
Lever cannot be placed directly on a Redstone Reader anymore (again)

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1408]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Back in 1.12 it used to be possible to attach a lever directly to a Redstone Reader. This is not possible anymore, it now requires a solid block in between, or a cable facade on the Reader. Eventhough the facade is not required to keep the lever attached.

This is a clone of #1052, was fixed, but now under these circumstances occurs again.

![image](https://github.com/user-attachments/assets/d3d552a9-bf33-41d2-bc5a-636e52f48dcd)

#### Steps to reproduce the problem:

1. Place a logic cable on the ground
2. Attach a Redstone Reader on the side
3. Try to attach a lever to the Redstone Reader
   → ❌ It will attach to the ground instead
4. Attach a Cable Facade to the Redstone Reader, remove lever and repeat step 3
   → ✔️ It will attach to the Redstone Reader

#### Expected behaviour:

If adding a facade to the cable/reader accepts a lever, _and_ if removing said facade afterwards doesn't detach the lever, the lever should also be able to attach to the reader directly without help of a facade.

____

#### Versions:

This mod: 1.23.3
Core: 1.19.5
CC: 2.9.3
Minecraft: 1.20.1
Forge: 47.3.7
Other mods: Tunnels, Terminals, JEI & TheOneProbe

I tested it on **NeoForge 1.21** too:

This mod: neoforge-1.23.1
Core: neoforge-1.19.10
CC: neoforge-2.9.2
Minecraft: 1.21
NeoForge: 21.0.167
No other mods

And on **NeoForge 1.21.1**:

This mod: neoforge-1.23.4
Core: neoforge-1.22.0
CC: neoforge-2.9.4
Minecraft: 1.21.1
NeoForge: 21.1.46
No other mods

**Comment by rubensworks** [comment]
Thanks for reporting!
