### ISSUE TITLE
Unable to insert variable card into part offset

### ISSUE THREAD

**Issue by BlueSonic27** [CyclopsMC/IntegratedDynamics#1409]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Unable to insert Variable card into part offset

#### Steps to reproduce the problem:

1. Place cable
2. Attach any reader/writer/importer/exporter
3. Apply Part Enhancement
4. Create a Variable Card with an Integer Value
5. Attempt to insert Variable Card into part offset

#### Expected behaviour:

The Variable Card should be stored in the part offset. The below screenshot is from a client with the following installed mods and their versions:
- Integrated Dynamics: 1.23.1
- Integrated Tunnels: 1.8.27
- Common Capabilities: 2.9.2
- Cyclops Core: 1.19.10
- Minecraft: 1.21
- Mod loader version: NeoForge 21.0.167

![Screenshot 2024-10-21 172656](https://github.com/user-attachments/assets/eb06a96a-a1a5-45ae-9fa4-f84351ad30dd)

____

#### Versions:

- Integrated Dynamics: 1.23.9
- Integrated Tunnels: 1.8.28
- Common Capabilities: 2.9.5
- Cyclops Core: 1.25.1
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.27

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> The below screenshot is from a client with the following installed mods and their versions:

But the screenshot shows a variable being inserted, so it did work somehow?
Or am I misunderstanding something?

**Comment by BlueSonic27** [comment]
The screenshot is from a different instance with it working as intended. Using Minecraft 1.21

**Comment by rubensworks** [comment]
Ah I see, thanks for the clarification.

**Comment by BlueSonic27** [comment]
Just tried with the same versions as the MC 1.21 and the variable card can be inserted into the part offset using MC 1.21.1. So somewhere between ID 1.23.1 and 1.23.9. Part offsets no longer accept variable cards

**Comment by BlueSonic27** [comment]
Okay after some testing. It seems part offsets were broken as of ID 1.23.2

**Comment by rubensworks** [comment]
Thanks for determining the version, this will definitely help me with debugging :-)
