### ISSUE TITLE
1.21.1 Neo - Integrated Dynamics Crash when transported with AE2's Spatial IO

### ISSUE THREAD

**Issue by Jmpp2909** [CyclopsMC/IntegratedDynamics#1410]
#### Issue type:

- :bug: Bug 

____

#### Short description:

2 distinct Crashes

Playing ATM10
Have a room with Integrated Dynamics stuff, mostly logistics and stuff that interacts with world.
Needed to move the room to another dimension due to new base location
Decided to use AE2's SpatialIO stuff

**1st crash:**
The moment the room was moved to SpatialIO cell (diff dimension), server crashed with:
"org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(level=minecraft:overworld, blockPos=BlockPos{x=152, y=91, z=-235}, worldReference=null) side north was found."
Which is this crash log: https://mclo.gs/upna6aV
After server restarted, everything was fine, and the room was effectively transported to SpatialIO

**2nd "crash" instance:**
Trying to pull the room out of SpatialIO
The moment i click to do that, the server hangs
Log is as follows: https://mclo.gs/PnR5J1q
Increasing watchdog wont do anything
After server restart, its rolled back to the moment before attempting to pull the room out of spatialIO.

As per Technici4n suggested, the tag:  
> #c:relocation_not_supported
Will make it so that block/blockEntity wont be transported to SpatialIO

#### Steps to reproduce the problem:

Try to move working ID parts into SpatialIO

#### Expected behaviour:

Not crash or hang, or those specific parts being left untouched.

____

#### Versions:

- This mod: IntegratedDynamics-1.21.1-neoforge-1.23.9
- Minecraft: 1.21.1
- Mod loader version: Neoforge 21.1.72

#### Log file:

https://mclo.gs/upna6aV -> 1st crash
https://mclo.gs/PnR5J1q -> server hang

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Related to #443.
But the `#c:relocation_not_supported` tag is definitely something I can add until we have proper frames (and related) support.

**Comment by Jmpp2909** [comment]
Is there a way to somehow "disable"/turn off any running ID networks? If there was, maybe i could still save that room lol

Thanks for the response and attention

**Comment by rubensworks** [comment]
There sure is, you can do this using the `safeMode` config option.

However, networks should automatically go into a network-specific safe-mode after such a crash, and only work again after breaking/replacing at least one cable. Was this not the case in your game? Because if not, then this would not work as it should.

**Comment by Jmpp2909** [comment]
Not sure
After the 1st crash the server started fine
But i dont know whats the reason for the server to hang on the 2nd instance when pulling it out of the dimension

**Comment by rubensworks** [comment]
> But i dont know whats the reason for the server to hang on the 2nd instance when pulling it out of the dimension

If it's caused by ID, then I'm definitely interested in hearing about it :-)

**Comment by rubensworks** [comment]
Hmm, the `#c:relocation_not_supported` may actually not be needed.
There was a security mechanism in place for these cases, but it was broken.
The next release should fix this.

(if the problem would still occur, please let me know, and then I'll add the `#c:relocation_not_supported`)
