### ISSUE TITLE
Add support for Jade

### ISSUE THREAD

**Issue by rhullah** [CyclopsMC/IntegratedDynamics#1413]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

When using a mod like Jade to have a HUD of what you're looking at, when focused on sub parts that connect to Logic Cables the HUD only shows the Logic Cable instead of the sub-part you're looking at like interfaces, importers, exporters, terminals, etc...all of them.  I often don't remember the color scheme for each part and don't remember which one is which.@@

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
ID should have Waila support already. Doesn't it work for you? (if so, please report this as a bug issue)
AFAIK, Hwyla uses the same API, so that should then also work.

TOP is also already supported.

I didn't know yet about Jade. I guess that's the new kid on the block?

**Comment by rhullah** [comment]
Yeah, Jade seems to be used in more modern modpacks. I'm not sure how support for each is implemented, but I though Jade was supposed to be like a drop-in replacement of Waila. If this should be a bug instead, could you just change it's type as a bug? Otherwise, I can create a new one as a bug.

Here's what I see for Jade:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/a3f9536d-0de7-4e57-a11c-928c77a0937a">

**Comment by uhloin** [comment]
OK, I see

Just FYI

Mentioned WAILA is discontinued after 1.11.2
https://www.curseforge.com/minecraft/mc-mods/waila

HWYLA is discontinued after 1.11.2
https://www.curseforge.com/minecraft/mc-mods/hwyla

Don't remember what's TOP

Also WTHIT is Fabric only
https://www.curseforge.com/minecraft/mc-mods/wthit

Jade is the main player for modern versions (92 millions downloads)
So, it would be very useful to support it
https://www.curseforge.com/minecraft/mc-mods/jade


<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/17/140/256/256/635658524720529782.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/waila">Waila</a></strong></div><div>Waila (What Am I Looking At) is a UI improvement mod aimed at providing block information directly ingame.
37.9M Downloads | Mods</div></blockquote>
<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/63/499/256/256/636143286314870563_animated.gif" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/hwyla">Hwyla</a></strong></div><div>Hwyla (Here's What You're Looking At) is a UI improvement mod aimed at providing block information directly in-game. It is also a fork of Waila.
87.0M Downloads | Mods</div></blockquote>
<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/337/208/256/256/637474424546110191.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/wthit">WTHIT</a></strong></div><div>What the hell is that? A fork of Hwyla which is a fork of Waila.
12.0M Downloads | Mods</div></blockquote>
<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/207/323/256/256/636965628804677340.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/jade">Jade 🔍</a></strong></div><div>Shows information about what you are looking at. (Hwyla/WAILA fork for Minecraft 1.16+)
92.8M Downloads | Mods</div></blockquote>

**Comment by rhullah** [comment]
Is this in the 1.24.0 release of the IntegratedDynamics mod? If so, what does the change look like because I'm not noticing a difference.

**Comment by rubensworks** [comment]
Should look like this: https://x.com/kroesermc/status/1864943611017634226?s=46&t=rWZfjp59dfZ7fPZKIz1z2Q

**Comment by rhullah** [comment]
Oh, I like that. But yeah, I'm still not seeing the subpart information.  I still see the same info I did in my [previous comment](https://github.com/CyclopsMC/IntegratedDynamics/issues/1413#issuecomment-2449869500).

I'm running ATM10 v2.3:
Integrated Dynamics: v1.24.0

**Comment by rubensworks** [comment]
Could you open a bug report for this (can be very brief), so it's added to my maintenance backlog?

**Comment by rhullah** [comment]
Sure thing.
