### ISSUE TITLE
Deepslate Dark Ore from Evil Craft cannot be put in either of the squeezers

### ISSUE THREAD

**Issue by pr0saic** [CyclopsMC/IntegratedDynamics#1414]
#### Issue type:

- :bug: Bug

____

#### Short description:

You can put other gem creating ores in the squeezers, deepslate or otherwise, but not deepslate dark ore.
The tags for the dark gem ores are c:ores/dark_gem

#### Steps to reproduce the problem:

![image](https://github.com/user-attachments/assets/a1b2d4cb-a67b-43ec-b0c9-e4a8d4943b74)

#### Expected behaviour:

Expected to be able to put deepslate dark ore in the squeezers, but you can only put regular ore in them.
![image](https://github.com/user-attachments/assets/b757ec0e-132c-468b-9ba3-8c7788ee1d14)

____

#### Versions:

- This mod: 1.23.14
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.73

**Comment by rubensworks** [comment]
Thanks for reporting!
