### ISSUE TITLE
Variable is not properly updated

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedDynamics#1416]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://github.com/user-attachments/assets/26fe7a61-46cd-469c-bdcc-277801ddc0e7)
Left is the uname of the right
I destroyed the grass block in front of the reader to make the offset line visible.
Pulling any variable out and putting it back in properly updates it.

#### Steps to reproduce the problem:

1. Build a network as is in the image, with grass in front of the reader.
2. Change the offset of the reader.
3. Wonder why the glass has uname of grass

#### Expected behaviour:

Variable is properly updated.

____

#### Versions:

- This mod: 1.23.14
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.73

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Hiranus** [comment]
Adding to it, It seems like using a script to get uname is also bugged and will result in the same behavior as shown above,

**Comment by Hiranus** [comment]
This issue seems bigger than earlier. 
![image](https://github.com/user-attachments/assets/4d8638b1-09c6-4777-af10-6aec50774ffb)
![image](https://github.com/user-attachments/assets/c0832225-5429-4ff1-9ca4-ff3d0bf98519)
Delayer should show amount of books in glass chamber, and its not. If I pull card in display panel and put it back in items are updated and now both Delayer shows correct amount of books and display panel shows correct item.
