### ISSUE TITLE
Add a way to separate "stacked" part offsets

### ISSUE THREAD

**Issue by AlisonHuang777** [CyclopsMC/IntegratedDynamics#1418]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

When breaking parts with a pickaxe (instead of uninstalling them with a wrench), the installed part offsets (if any is installed) will drop. Currently this is the only way I know to retrieve offsets from a part. However, when doing so, the dropped offsets are always in a "stacked" form (e.g. if I insert 3x 4-blocks-offsets into a part, breaking it will yield me a single 12-blocks-offset), and there seems to be no way to separate them back into their original form (4-blocks-offsets which I will get from crafting). These can cause inconvenience for storing them, because they won't stack with the original form. It's especially true for AE2 users as that means wasting extra types. So I wish there could be a way to do that, either by adding a crafting recipe that separates it, or just make them dropped as original form when I break the part.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Jack-McKalling** [comment]
I think this may actually be a bug, but I don't know much about the offsets implementation. It seems logical for them to drop as separate items rather than a single merged one, but this may be limited by the internal mechanic.

**Comment by rubensworks** [comment]
I'll prioritize this one, as it's borderline between feature and bug indeed.
