### ISSUE TITLE
Pipez & Integrated

### ISSUE THREAD

**Issue by MrEizy** [CyclopsMC/IntegratedDynamics#1419]
#### Issue type:

- :question: Question 
So pulling energy from generators dont work unless it goes straight to a touching battery,
And using pipez it wont allow you to export energy from the battery
____

#### Question:
It it meant to be like this or is it a bug?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by Jack-McKalling** [comment]
The generator works exactly like a furnace, so you need to pull from the bottom face. If you're also using Integrated Tunnels, you can use energy interfaces and energy importers/exporters to pull from the generator and transfer it into the battery, and again from there to where you want it to go.

I'm sure Pipez should also be able to interact with the generator this way. Are you sure you're pulling from the bottom? If your space is tight, using Tunnels you can even configure the part to interact with a different side than you're attached to. As also mentioned above, you can ask for more detailed help from ID-experts on the discord server if you can't get it to work for you.

But if that still isn't solving your problem then indeed maybe there's a bug. But we'd need more info about your scenario and setup to make sure.

**Comment by Jack-McKalling** [comment]
The bug from this question is now being tracked at #1420, so I'm now closing this question. Feel free to ask more or additional questions on discord, or to post them here on github.
