### ISSUE TITLE
Idea: XP Attractor and Collector

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#142]
How adding a machine that will attract XP, like the player attracts XP when nearby. Could be powered by RF? And an XP collector, basically a Hopper-like device that would store the XP Orbs in the form of a fluid maybe? And can only be retrieved via another machine that will spit out the orbs.

Say you have a machine that will smelt ore, normally when collecting the items will give you XP, but when automating the process XP is lost. Same goes for an automated animal farm.

Of course this would end up overriding how MC generates the XP Orbs. Separate mod maybe?

Anyway, just a thought.

**Comment by rubensworks** [comment]
This is way out of scope for Integrated Dynamics. I do however have similar plans for EvilCraft...
