### ISSUE TITLE
Pipez not working with integrated

### ISSUE THREAD

**Issue by MrEizy** [CyclopsMC/IntegratedDynamics#1420]
#### Issue type:

- :bug: Bug 

____

#### Short description:
So pulling energy from a Battery doesnt work unless you use integrated pipes. other mods cant. tried with several machines.
It works directly from generator but if you put the Battery as a gate it wont allow you to extract the energy from it with Pipez.

#### Steps to reproduce the problem:

1. Get energy into a battery then try to use Pipez mod to extract
2. It wont extract
#### Expected behaviour:

____
For it to extract
#### Versions:

- This mod: 1.21.16
- Minecraft:  1.21.1
- Mod loader version:  21.1.73

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
You're mentioning the wrong mod version, but I see what you mean now, it indeed doesn't work as expected / as should.

Allow me to provide my own steps and versions:

**Steps to reproduce the problem:**
1. Place a 1M battery
2. Place a generator next to it, and feed it some coal
3. Battery is now filling with energy from adjacent machine
4. Place another 1M battery 2 blocks away from the previous one, so there is a single blockspace in between
5. Place a Pipez energy pipe in between
6. Use the Pipez wrench on the pipe at the filled battery side, to put it into extract mode
7. Energy _should_ now be moving from the auto filled battery into the empty one, but it's not

I also tested whether the side matters. It appears not to be transfering any energy from the side, nor from the bottom.

**Versions:**
- This mod: neoforge-1.23.16
- Core: neoforge-1.25.2-634
- CC: neoforge-2.9.6
- Minecraft: 1.21.1
- NeoForge: 21.1.77
- Other mods: pipez-neoforge-1.21.1-1.2.19

**Comment by Jack-McKalling** [comment]
Considering that universal cables from Mekanism do actually work, this may be an issue with Pipez. If you report the issue there, you can mention this report. I'll leave this open just in case they cannot fix it and it is actually a problem on our end.

**Comment by Jack-McKalling** [comment]
Providing new information, it turns out that it is possible to get the energy transfer going through Pipez pipes, if you send a redstone signal to the energy battery in between the generator and destination.

The signal only needs to "wake up" the battery and doesn't need to stay on.

I'm on the fence about whether that means this is a problem on our side, or on Pipez' still.

**Comment by Jack-McKalling** [comment]
@henkelmax would you like to look into this, if you can? Maybe you could provide with some input about this issue.
