### ISSUE TITLE
Creative energy battery doesn't provide any energy (eventhough it is full with it)

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1421]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The creative energy battery doesn't seem to be exposing its energy for anything.

#### Steps to reproduce the problem:

1. Place a creative battery
2. Place a mechanical squeezer next to it
3. Watch how it doesn't get powered
4. Even if connected through energy interfaces/importer from Tunnels

#### Expected behaviour:

Like in previous versions, the creative battery should still power machines that are adjacent to it. But also through other energy transfer methods.

____

#### Versions:

- This mod: neoforge-1.21.8
- Core: neoforge-1.19.3
- CC: neoforge-2.9.2
- Tunnels: neoforge-1.8.26
- Minecraft: 1.20.4
- Mod loader version: NeoForge 20.4.237

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Note that normal batteries do still provide energy transfer as described above.
