### ISSUE TITLE
Inventory Reader List Variable Causing Progressive Lag Until Crash

### ISSUE THREAD

**Issue by N1ghthauq** [CyclopsMC/IntegratedDynamics#1422]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Using an inventory reader on a chest, grabbing the list variable and in any way observing the variable causes progressively worse server and client lag. Tanking FPS until game crash and causing server TPS to spike 1000% above average.

#### Steps to reproduce the problem:

1. Place chest
2. Attach inventory reader to chest
3. Attach logic cable to back of inventory reader
4. Attach display panel to logic cable
5. Create a list variable from within inventory reader
6. Insert variable into display panel
7. Wait... Patiently...
8. Game stutters, server stutters, game crashes.

Note: removing the variable card from the display panel resolves the issue and has no lasting impact afterwards.

I suspect even hovering the mouse over the list variable card in the inventory of the player has some negative performance impact as well, just not as noticeable as the display panel.

#### Expected behaviour:

Inventory list without slow painful crash

____

#### Versions:

- This mod: 1.23.17
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.80

#### Log file:

Trying to paste the latest.log file crashes pastebin... it is 89 MB :)

Edited the logs to get it into pastebin:
https://pastebin.com/yiL3V8nZ

I will attach a spark profile I grabbed demonstrating the functions that take up the most tick time.
There was not a better way to display the information. You can extract the file and upload it to https://spark.lucko.me/
Look at the profile by mod, and expand the integrated / CyclopsCore tree. 
This profile was taken early on in the bugs lifecycle but is enough to display the functions that are causing issues.
[Integrated Lag.zip](https://github.com/user-attachments/files/17840133/Integrated.Lag.zip)

Image of what I am referencing with the spark profile
https://imgur.com/a/LAQBfAI

**Comment by rubensworks** [comment]
Thanks for reporting!
