### ISSUE TITLE
Ars Nouveau and ID crash Server

### ISSUE THREAD

**Issue by OldDonald** [CyclopsMC/IntegratedDynamics#1423]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Placing Ars Nouveau Scibe's Table next to Crafting Terminal and selecting a glyph to produce on the Table causes Server crash

#### Steps to reproduce the problem:

1. Have a ID storage System ( I had rouhgy 16 Double Diamond chests 18 normal, about 200 Variable Cards, I also made a crafting "Spire" 4 terminals on 1 pipe)
2. Place Ars Nouveau Scribe's Table directly next to a crafting Terminal. 
3. Open Scribe's Table with Spellbook
4. Select Glyph to be made (so the ingredients hover over Table)
5. Click Select.
6. Crash as well as unable to join the server after restarting it.  (Had to use Backup)

#### Expected behaviour:

Not crash

____

#### Versions:

- This mod: 1.23.16
- Minecraft: 1.21.1
- Mod loader version: Neoforge 21.1.77
- Ars Nouveau: 5.2.6
- All the Mods 10 - ATM 10 1.20 (MODPACK)

#### Log file:

[crash-2024-11-21_20.45.01-server.txt](https://github.com/user-attachments/files/17867111/crash-2024-11-21_20.45.01-server.txt)
[crash-2024-11-21_21.05.26-server.txt](https://github.com/user-attachments/files/17867112/crash-2024-11-21_21.05.26-server.txt)
[crash-2024-11-21_21.08.48-server.txt](https://github.com/user-attachments/files/17867113/crash-2024-11-21_21.08.48-server.txt)
[crash-2024-11-21_20.33.29-server.txt](https://github.com/user-attachments/files/17867114/crash-2024-11-21_20.33.29-server.txt)
[crash-2024-11-21_20.36.29-server.txt](https://github.com/user-attachments/files/17867115/crash-2024-11-21_20.36.29-server.txt)
[crash-2024-11-21_20.38.53-server.txt](https://github.com/user-attachments/files/17867116/crash-2024-11-21_20.38.53-server.txt)
[crash-2024-11-21_20.41.45-server.txt](https://github.com/user-attachments/files/17867117/crash-2024-11-21_20.41.45-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I don't really understand what you're doing with the other mod, since I don't have experience with Ars Nouveau.

Could you try to reproduce the basic setup that causes the issue, in a blank environment with just Integrated Terminals/Crafting and Ars Nouveau installed (with dependencies), and show a screenshot of your setup?

**Comment by rubensworks** [comment]
I already see what's going wrong. Will push a fix in a minute.
