### ISSUE TITLE
Recipe for resetting facade texture

### ISSUE THREAD

**Issue by AlisonHuang777** [CyclopsMC/IntegratedDynamics#1424]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

As the title described. For now after a facade has crafted with another block and turns into its texture, there's no way for the facade to return to its original no-texture form. This feature will be useful for storing disassembled facades. Such recipe might be as simple as putting a single facade into the crafting grid.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
