### ISSUE TITLE
Texture pack - what am I doing wrong?

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1427]
#### Issue type:

- :question: Question 

____

#### Question:

I'm attempting to make a texture pack 64x64 for ID, but even change of pixels in the picture invalidates squeezer frames.
Here is a resource pack still 16x16 with test of change Mech Squeezer texture, and similar look I get if scale images by 400%.
What am I doing wrong?

![2024-11-28_19 33 38](https://github.com/user-attachments/assets/13289d1f-3990-40ac-9e79-394cd78e8e20)
[Integrated Textures 64.zip](https://github.com/user-attachments/files/17950009/Integrated.Textures.64.zip)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by Jack-McKalling** [comment]
Are you using minecraft version `1.21.1`? Or an older version? The pack format version of your pack is only supported for `1.21.1` _specifically_.
Also, what version of the mod are you using?

**Comment by uhloin** [comment]
MC 1.21.1
IntegratedDynamics-1.21.1-neoforge-1.23.19.jar

**Comment by rubensworks** [comment]
Not sure what's going wrong there.
Here's the model of the squeezer: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.21/src/main/resources/assets/integrateddynamics/models/block/squeezer.json
It may be possible to change that one as well when changing the texture.

<blockquote><img src="https://opengraph.githubassets.com/ca2d5dbbe73e475341221c9cff4fcf404157634335ea69b9a43e3fdbf6091833/CyclopsMC/IntegratedDynamics" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.21/src/main/resources/assets/integrateddynamics/models/block/squeezer.json">IntegratedDynamics/src/main/resources/assets/integrateddynamics/models/block/squeezer.json at master-1.21 · CyclopsMC/IntegratedDynamics</a></strong></div><div>A Minecraft mod to take full and automated control of your appliances. - CyclopsMC/IntegratedDynamics</div></blockquote>

**Comment by Jack-McKalling** [comment]
I think you're supposed to include (a copy of) the mcmeta file for that image in your pack, for it to understand that the image is animated. With this in mind, I'll close this question. If you have further issues I suggest to create a new report.

If you would like more help with creating resource packs in general, I suggest you join the Minecraft Commands discord server, where they can provide technical support about all things Java Edition.
