### ISSUE TITLE
Portable Interface Replicator

### ISSUE THREAD

**Issue by bangplaysgames** [CyclopsMC/IntegratedDynamics#1429]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

A great QOL feature would be an item that functions as a Portable Interface Replicator.

This item would copy the configuration and variable in an interface/writer/exporter/importer and replicate them onto parts of the same type.  For instance, if you have 16 world block exporters, you could setup one, copy the config and variables with the replicator by shift + right-clicking it, and then, provided you have blank variable cards in your inventory, right-clicking the same type of interface would use your variable cards to replicate the config and variable card creating an exact replica setup.  This can be further expanded by using offset cards in your inventory to match  the offset values, as well.  For example:  If the copied interface uses an offset of Y + 5 and you have the necessary offset cards, then it will apply the offset cards and set the offset of replicated interfaces to Y + 5 as well.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Jack-McKalling** [comment]
This suggestion is already tracked by #687, so I'll close this one. But if you want, I suggest you add your additional thoughts regarding the offsets as a comment over there, since offsets were added after that suggestion was made.
