### ISSUE TITLE
Opening Inventory Reader GUI Crashes Game

### ISSUE THREAD

**Issue by PetersonE1** [CyclopsMC/IntegratedDynamics#143]
If anyone, both on singleplayer and multiplayer, opens the GUI of the Inventory Reader, the game crashes or the server goes down.

Integrated Dynamics 0.6.8
Minecraft 1.11.2
Forge-13.20.0.2228

[Mod List](http://dannyandson.com/unreal-tech-modpack/)

**Comment by rubensworks** [comment]
I can't do anything without a crashlog.
if it's Refined Storage-related, that has been fixed in the dev version.
