### ISSUE TITLE
Vanilla Furnace not accepting iron ore/raw iron to iron ingot recipes.

### ISSUE THREAD

**Issue by Yuuva124** [CyclopsMC/IntegratedDynamics#1432]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The recipes for raw iron/iron ore to iron ingot shows as not acceptable when put into a crafting interface aimed at a vanilla furnace. The same recipes can work for the Thermal Series Redstone Furnace.
![2024-12-07_06 17 18](https://github.com/user-attachments/assets/61321ae6-74e6-410d-8581-23a1bed54419)
![2024-12-07_06 17 22](https://github.com/user-attachments/assets/db463c5b-cecf-4c37-8d02-962694b61ff9)
![2024-12-07_06 20 14](https://github.com/user-attachments/assets/349d42dc-3a05-4198-85e5-e45fceb1b43a)
![2024-12-07_06 20 17](https://github.com/user-attachments/assets/b096b637-5e6d-4104-b83d-93db370152f4)

#### Steps to reproduce the problem:

1. Place a crafting interface aimed at any side of a furnace.
2.  Put a recipe for iron ore/raw iron to iron ingots into the crafting interface.

#### Expected behaviour:

The recipes should be acceptable and the furnace should start smelting ore with a crafting writer.
____

#### Versions:

- This mod: Dynamics: 1.23.0 Crafting: 1.1.8 Tunnels: 1.8.28
- Minecraft: 1.19.2
- Mod loader version:  Forge 43.3.9

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
What happens when you connect the crafting interface at the top of the furnace? 
I'm not saying that it should work like that instead, but I want to see if it influences the result.

Also, could you screenshot the error that shows when you hover over the red X ?

**Comment by Yuuva124** [comment]
![2024-12-07_06 40 09](https://github.com/user-attachments/assets/ca848c7a-42f5-4e03-9ca0-a0202924d7ed)
From what I remember from yesterday, it shows the same on every side of the furnace.

**Comment by Jack-McKalling** [comment]
> it shows the same on every side of the furnace.

OK, thanks.

That screenshot is for the tooltip of the variable card, but I mean the one from the big red ❌ below it, which shows the error itself if you hover over it.

**Comment by Yuuva124** [comment]
Oh sorry.
![2024-12-07_06 48 21](https://github.com/user-attachments/assets/46c911ca-7150-4ea1-99df-13472f84b672)

**Comment by Minerofmillions** [comment]
What happens if you make the recipe so that its tooltip reads `Iron Ingot <- Raw Iron` by putting the raw iron in the first input slot?

**Comment by Yuuva124** [comment]
The recipe runs perfectly line like that. Weird that the recipe worked both ways for the Redstone Furnace.

**Comment by Minerofmillions** [comment]
My _guess_ is that the redstone furnace counts as a general machine but the furnace doesn't, meaning that the furnace recipes check that there's exactly one input type and one output type, which the empty slots would make fail.
