### ISSUE TITLE
Unable to read NBT Type or Data from path

### ISSUE THREAD

**Issue by N1ghthauq** [CyclopsMC/IntegratedDynamics#1436]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When trying to use the NBT path variable cards to read NBT data or NBT type it throws null or nothing.

#### Steps to reproduce the problem:

1. Following the guide from On the Dynamics of Integration
2. Place a lectern with a book in it
3. Place a block reader on the lectern
4. Attach the block reader to a network with a variable store via logic cables
5. Pull the Tile Entity NBT data from the Block Reader
6. Attach a display panel to the same network as the other connected parts
7. Place NBT card into display panel (Observe NBT intact and coherent)
8. Create new string variable card with ".id" NBT path
9. Apply variable card with string and variable card with NBT to NBT path test
10. Place resulting card into a display panel, this will return a value of true, indicating the path exists
11. Apply String and NBT data to a NBT{}.Type card
12. Place resulting card into a display panel, this returns a Null, indicating there is nothing there
13. Any other attempt to pull data either by listing NBT Keys, the NBT data itself, grabbing compound tags, all result in nothing or null

#### Expected behaviour:

Display the NBT values when attempting to get Type, Strings, Keys, etc.

____

#### Versions:

- This mod: 1.24.0
Cyclops Core: 1.19.5
Common Capabilities: 2.9.4
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.12 

#### Log file:

https://imgur.com/a/J5XJ44t

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This works fine on my end.
I'm guessing you used the `.id` string in the NBT{}.Type operator, while this one does not accept NBT paths, but direct keys, so you should use `id` here.
