### ISSUE TITLE
Jade not showing sub-part information

### ISSUE THREAD

**Issue by rhullah** [CyclopsMC/IntegratedDynamics#1438]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Even running the latest version of Integrated Dynamics, sub-part information is still not showing in Jade. What is shown is the same in the [original issue](https://github.com/CyclopsMC/IntegratedDynamics/issues/1413#issuecomment-2449869500).

#### Steps to reproduce the problem:

Place a network cable and then a sub-part on that cable. Hover over the sub-part and notice the Jade tooltip.

#### Expected behaviour:

Jade should show sub-part information when targeted with the mouse cursor as demonstrated in [this X post](https://x.com/kroesermc/status/1864943611017634226).

____

#### Versions:

- This mod: 1.24.0
- Minecraft: 1.21.1
- Modpack: ATM10 v2.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I can reproduce this with a narrower environment footprint:

- This mod: 1.24.0-974
- Core: 1.25.5-671
- CC: 2.9.7-183
- Minecraft: 1.21.1
- Neoforge: 21.1.89

See also:
![image](https://github.com/user-attachments/assets/dcc71311-3f54-4393-bc0f-434bfebffe6f)

**Comment by rhullah** [comment]
Thanks for doing that @Jack-McKalling, I created the ticket on my phone away from my computer so wasn't really able to narrow it down.

**Comment by rhullah** [comment]
This is working now and it's great! Thanks!
