### ISSUE TITLE
Feature: some more list operators

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#144]
-If List A contains entries in List B return bool (if List A contains at least preexisting entries in list B)
-If List A equals List B then return Bool
-Dedup List entries, return list.
-List combine, return list.

**Comment by rubensworks** [comment]
- Already possible using the reduce operator
- This is the equal operator
- Not possible yet, might implement is as the `uniq` operator
- This has been implemented in-dev as the `concat` operator.
