### ISSUE TITLE
Offset enhancement bugs

### ISSUE THREAD

**Issue by LindaJuffermans** [CyclopsMC/IntegratedDynamics#1448]
#### Issue type:

- :bug: Bug 
____

#### Short description:

- Max offset is 28, yet the enhancement claims it's at the limit of 32
![image](https://github.com/user-attachments/assets/7e14b319-bb5c-4e6f-adba-db32e746e631)
![image](https://github.com/user-attachments/assets/d38ab90e-94f7-463e-9b07-749defe34447)

- Trying to apply enhancements past the limit reduces the count of the stack on the client; taking the stack and putting it back refreshes the count

- Picking up the connector doesn't drop the enhancements, they remain part of the connector item. There appears to be no way to get the enhancements back, if you place the connector in your crafting grid to take out the result it just voids the enhancements.
![image](https://github.com/user-attachments/assets/08dc414e-a978-49dd-9865-ff19fd7938ec)
![image](https://github.com/user-attachments/assets/b8ef337b-e2c8-49a8-81e7-7e4313d00b73)

#### Steps to reproduce the problem:

1. Place a connector (e.g. World Block Importer)
2. Right-click the connector with a lot of Part Enhancement: Offset items
3. Observe the ToP tooltip and the message when trying to add an enhancement past 28 blocks
4. Observe the stack count decreasing even if no more enhancements are accepted
5. Take the connector, observe the tooltip in your inventory also reads 28

#### Expected behaviour:

I expect the maximum offset to be 32, not 28.
I expect the count of the stack to not decrease on the client if the enhancement is not accepted.
I expect the enhancements to drop either when picking up the connector or through crafting.
____

#### Versions:

- This mod: 1.24.2
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
The offset items not dropping, might be related to the fix of #1418.

**Comment by rubensworks** [comment]
> Picking up the connector doesn't drop the enhancements, they remain part of the connector item. 

They only drop when broken with a pickaxe, not with a wrench.
