### ISSUE TITLE
Tooltip Lines Operator

### ISSUE THREAD

**Issue by pippinsmith** [CyclopsMC/IntegratedDynamics#1449]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

**Idea:** an operator of the following signature: _Item -> List(String)_; Taking an item and returning a list composed of the lines of the tooltip of the input.

Tooltips are already a "first class citizen" in IntegratedTerminals for search purposes, but can't be used in filters etc.

My reason for needing/wanting this: reading tooltip for the existence of emc values provided by ProjectE, the possibility of parsing the value with regex.

From a quick look at the code, it looks straightforward to implement the functionality of this, so **I'm willing to attempt a PR** if this is something you'd merge, though I'm not yet sure which item I can easily use in the test suite (energy battery maybe?) since my gut feeling doesn't trust the dynamic nature of "<Shift for info"> (which is probably a translation string as well, so maybe harder to test? idk, I'm bad at tests)

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Good idea, a PR is definitely welcome!

I believe tools such as pickaxes also show some tooltip lines, those could be good testing items.

If you would make a PR, could you target the `master-1.19-lts` branch? I can upmerge it to higher MC versions when releasing.

**Comment by pippinsmith** [comment]
initial attempt: 
![image](https://github.com/user-attachments/assets/05c22aea-70af-4fb9-9fa2-19ee65bcc379)

![image](https://github.com/user-attachments/assets/ff0d456c-d0f9-459b-86c4-23123c28365d)

question: should I remove the item name and/or empty lines or just leave those in for the player to handle (ingame it's only a `slice` or `tail` away)

gonna start writing tests now

**Comment by rubensworks** [comment]
Nice!

> question: should I remove the item name and/or empty lines or just leave those in for the player to handle (ingame it's only a slice or tail away)

I think keeping it as-is is fine. The player will have to do post-processing anyways if they want to do anything useful with it.
