### ISSUE TITLE
Subnetworks

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#145]
-Allow isolated networks to use same variable store and remain isolated. (using variable store faces)

**Comment by rubensworks** [comment]
Something exactly like this won't be implemented, but perhaps subnetworks with proxy-able variables could be doable.

**Comment by BiatuAutMiahn** [comment]
Or your channel method previously mentioned?

**Comment by rubensworks** [comment]
Related, yes, but still different, I'm just thinking about a proxy method between subnetworks/channels.

**Comment by josephcsible** [comment]
Possibly related: CyclopsMC/IntegratedTunnels#18

**Comment by josephcsible** [comment]
Actually, as I think about this, I can't think of any reason to ever need isolation between Integrated Dynamics networks other than for Integrated Tunnels, so perhaps this issue should be closed in favor of the other one.

**Comment by rubensworks** [comment]
Indeed, I'll close this one.

But the actual implementation of subnetworks should still become part of ID.
