### ISSUE TITLE
Crash breaking logic cable with pick

### ISSUE THREAD

**Issue by shabble** [CyclopsMC/IntegratedDynamics#148]
Crash occurred when breaking a cable while dismantling a small ID network

Context:

* network shouldnt' have been active (had removed cards from display panel which was only output in network)
* was connected to a variable store wth some cards (including RS Item List aspect), but I think I'd already removed the Inventory Reader on the RS thing.
* cable being broken *might* have been facaded (or I might have already removed facade to investigate lighting glitch I'll report separately).
* adjacent cable was almost certainly still facaded

* tool used to break was I think a ActAdd AIOT with silk-touch

Crashlog: https://gist.github.com/shabble/820ac006c3cf8f85b3e279faf09a31bd

* MC 1.10.2
* IntegratedDynamics-1.10.2-0.6.7.jar

**Comment by rubensworks** [comment]
@shabble Can you reproduce this when using the AA silk touch tool?

**Comment by shabble** [comment]
no, I can't seem to reproduce it (I've since torn down the original thing that was doing it, and trying various combinations of cables, facades and tools (with and without silk touch) doesn't seem to do it.

I did notice that breaking a facade with a cable inside doesn't appear to drop the cable, only the facade. Separate bug?

**Comment by rubensworks** [comment]
@shabble If you can reproduce it, that also sounds like a separate bug, yes.

**Comment by rubensworks** [comment]
Note to self: this is probably a multithreading issue because of the cable breaking that happens within the world thread, and the network ticking happening in the server thread. This explains the non-determinism Add proper locks to solve this.
