### ISSUE TITLE
Feature: Single Item conversion/crafting utility.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#151]
-A utility block than can perform simple/single item crafts?

Examples:
-Block of Coal<>9 Coal
-Bone>3 Bonmeal
-Menril Block<>9 Menril Chunks
-etc

Edit: I did try something like this with Item Exporters, and a crafting table, but it does not work.

**Comment by rubensworks** [comment]
Not sure if I want to add this, perhaps to the Tunnels extension.
In the meantime, you can use another mod of mine: https://minecraft.curseforge.com/projects/structured-crafting

**Comment by BiatuAutMiahn** [comment]
Your structured crafting mod is surely useful, however it spawns blocks rather than items that can be stored.

**Comment by rubensworks** [comment]
I'm working on an ID addon that will make this possible (not for the near future though...)
