### ISSUE TITLE
Bug: Redstone Writer and Comparator

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#152]
-When a redstone writer is sending a signal to the side of a Comparator, the signal is not output properly.

Shots: [here](https://infinitycommunicationsgateway.net/Pub/Minecraft/Shots/#files%2FIntegrated%20Dynamics%2FRedstone%20Writer)

**Comment by rubensworks** [comment]
Was not really a bug, since the comparator expects strong power, but this is supported as well since the last commit.
