### ISSUE TITLE
Feature: Fluid Storage Tanks.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#153]
-I can see that Evil craft has Fluid storage tanks, and I was wondering if you would be able to separate that tank into it's own mod, or include it in this one? The reason I ask is because there are no other simple tanks out there for 1.11.2, and EvilCraft would add alot more than necessary.

Thank you

**Comment by rubensworks** [comment]
No, I won't be separating that. And this really doesn't have anything to do with ID...

You can disable large parts of EC if you want to.

**Comment by BiatuAutMiahn** [comment]
I mention this because Integrated Tunnels has the Fluid Interface/Importer/Exporter, and the Squeezer produces a liquid Menril.
