### ISSUE TITLE
[1.11.2-0.6.8] forestry compitability

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/IntegratedDynamics#154]
It's listed in the fml client log as a thread/ERROR and the text calls it a crash. But the client runs so it's not a crash.

https://gist.github.com/kreezxil/7313b72041c9de98e37dc2dfcf55240d

the entire fml client log

https://gist.github.com/kreezxil/6475448742f4466372318c98bdbafe9f

**Comment by Nedelosk** [comment]
There is an problem with the backpacks too.You register the backpacks items with the false backpack uid. You have to use the uids from the BackpackManager.

**Comment by mezz** [comment]
I think I changed the backpack UIDs in 1.10 or 1.11
