### ISSUE TITLE
[1.11.2-0.6.8] Cant craft the squeezer

### ISSUE THREAD

**Issue by Gayanfalor** [CyclopsMC/IntegratedDynamics#155]
All is said on tittle, when i put recipe to craft the squeezer i can see the result but cant take it out it stay on the result box :s

**Comment by rubensworks** [comment]
@Gayanfalor The recipe must be somehow disabled then, because I can craft it myself just fine.

**Comment by Gayanfalor** [comment]
Yep i dont know from what its coming i have the same problem for crafting a block from another mod.

So the problem is not from IntegratedDynamics
