### ISSUE TITLE
Feature: Operator to read variable in network?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedDynamics#158]
How about two operators to get a Variable Type and a variable's Value. Example:

Get a variable's Value:
`Value( Get( List("Variable Store Inventory"), 0))`

**Comment by rubensworks** [comment]
I haven't thought of this before, but that would definitely be a useful thing to have.
It would be a more expressive proxy method.

**Comment by rubensworks** [comment]
I had another look at it, and unfortunately this is not possible without a massive rewrite of the variable system.
So I won't implement this.

Alternatively, you can use the variable proxy block with a little bit less flexibility.
