### ISSUE TITLE
Facade stair blocks don't work as expected

### ISSUE THREAD

**Issue by ShelLuser** [CyclopsMC/IntegratedDynamics#163]
I recently started a (new) survival game which also included Integrated Dynamics and I seriously love it.

Now, I discovered the facade blocks and I love the concept, also because it really fits a mod which mentions "integrated" :)  But I noticed 2 things: if you place a facade block on top of a chest then this will block the chest from opening. Somewhat understandable because full blocks do that, but also peculiar because this facade block basically masquerades the network (in my case a logic cable & display) and those by themselves don't block a chest.

So then I tried the "stairs trick" (= place a block of stairs on top with their flat side facing to the front and it will look as if a solid block is above the chest while in fact it isn't, so nothing blocks it from opening). The only problem is that the facade system allows me to craft a facade stairs block, but the moment I place it it changes back into a full block and prevents my chest to open again.

I think this is a bug.

**Comment by rubensworks** [comment]
Not a bug, just a not-yet-implemented feature :-)

**Comment by rubensworks** [comment]
I just looked at it, and I would have to extend the facade system too much to support this.
I won't implement this because McMultiPart allows you to do exactly this and much more.

I don't want to reinvent the wheel :-)
