### ISSUE TITLE
Integrated Dynamics battery charges from ender IO system but doesn't output.

### ISSUE THREAD

**Issue by PenguinMan98** [CyclopsMC/IntegratedDynamics#165]
Hey guys. I built the battery and plugged it into my ender IO conduit system and it charged up to full quick enough.  It says it contains 100,000 RF.  I took it with me to an alternate dimension from the RFtools mod and am trying to use it to power the dialing device/matter transmitter to take me home but it's not powering the devices. I know the answer is probably mod incompatibility but maybe you can shine some light on this for me.

**Comment by rubensworks** [comment]
The batteries only output energy when a redstone signal is supplied, are you doing this?

**Comment by PenguinMan98** [comment]
Ah, that's the trick. Sorry to bother you!
