### ISSUE TITLE
Server crash after breaking block reader during lag

### ISSUE THREAD

**Issue by Pandemoneus** [CyclopsMC/IntegratedDynamics#168]
I am not sure whether the issue described in the title is the exact way to reproduce the bug. Basically what I was doing: I was trying to access the block reader, however it was not online (no power). It did not show so in TOP though. So I broke it, and after that the server crashed.

Here's the crash log:
https://pastebin.com/Lp5vcPtY

**Comment by rubensworks** [comment]
Are you able to reproduce the crash?

**Comment by Pandemoneus** [comment]
I didn't try to, as the server population would be very pissed. It also seems to be a special situation.
But when looking at the log, I see you are working with weak references. Since that happened during player interaction, maybe you should add a check whether the block/part is really there?

**Comment by rubensworks** [comment]
That check is already happening. The block isn't there according to the game, which is why I make it crash, because something is going horribly wrong.

Could it be possibly that the part was placed by you only shortly before you opened the gui?
