### ISSUE TITLE
Redstone Writer not automatically updating when set on strong signal

### ISSUE THREAD

**Issue by donoya** [CyclopsMC/IntegratedDynamics#170]
I  am using version 0.6.11 for minecraft 1.11.2. I have it set up to power a comparator through a stone block with a power of 7 when there is not an empty array of players standing on a connected entity reader.

**Comment by rubensworks** [comment]
@donoya Is it the comparator that doesn't update? Or the writer itself? i.e., is the writer showing the correct value when opening its gui?

**Comment by donoya** [comment]
When I break or place a block next to the comparator, it updates. I'd have to check whether the gui displays the correct value, but since updating the comparator updates the signal, I don't think that's the problem.

Edit: I checked and the writer does update. It's just the comparator. It also happens with redstone dust, redstone torches, and repeaters. It does work if you put the dust/comparator/repeater directly in front of the redstone writer.

**Comment by rubensworks** [comment]
Ok, then it must be a block-update related issue. I'll look into it.
