### ISSUE TITLE
Generator can't be piped into

### ISSUE THREAD

**Issue by mrlamb** [CyclopsMC/IntegratedDynamics#174]
I'm sure most people play without the power requirements so maybe this was missed. I can't hopper or dropper into the Generator block. Haven't tried other methods of "piping" items as the mod pack I'm using has most of them tech gated, but it seems like these vanilla methods should work if any of them do.

I seem to remember the interface 'iSided' being bandied about at some point in the past by mod peoples. Generator can has?

**Comment by rubensworks** [comment]
I must have missed that, will add it in the next update.
