### ISSUE TITLE
In love!   LP replacement roadmap.

### ISSUE THREAD

**Issue by BrewingCoder** [CyclopsMC/IntegratedDynamics#177]
I just found your mod, first off let me say I love the shit out of this!

I'm still working my way through some of the finer details, but I see this as a totally viable replacement for logistics pipes.

When you combine this with the tunnels mod cit an replace most of the functionality of LP. 

I think the only big tickets that are missing are crafting, some sort of interface to reach into the network, and the concept of a default route or default item storage.

I know what I'm talking about is probably more related to the tunnels mod, but I see that as just an extension of this mod.

Are there roadmap plans for future functionality?

**Comment by rubensworks** [comment]
I'm glad you're enjoying the mod! :-)

Regarding the roadmap, I still have many plans for IT and ID, which includes (auto)crafting and something like terminals. I can't give any estimates when I'll be able to implement this though.

Default routes for storage should already be possible by tweaking the interface priorities (e.g. setting it on a very high number to make it the default).
Unless you mean something else by this?
