### ISSUE TITLE
Game Crash when trying to read ExU2 Scanner

### ISSUE THREAD

**Issue by davqvist** [CyclopsMC/IntegratedDynamics#179]
MC 1.10.2
Forge 2297
ID 0.7.0
ExU2 1.4.1

https://pastebin.com/hk7c38CN

How to replicate:
1.) Place ExU2 Scanner
2.) Place Redstone Reader on Scanner
3.) Connect Redstone Reader with cables to full ID Battery
4.) Right click Redstone Reader
5.) Crash

Not sure if ExU2's fault or yours, but first guess was to post here. Let me know if this is a problem of ExU2, then I post on its github.

**Comment by rubensworks** [comment]
I don't see any reason why it should crash on my end, perhaps you should report it to ExU2's issue tracker as well.
