### ISSUE TITLE
Suggestion/Question re: proxies and the new tutorial

### ISSUE THREAD

**Issue by mrlamb** [CyclopsMC/IntegratedDynamics#181]
Absolutely loving this mod and especially the new tutorial! Fantastic work with that. One thing that I stumbled over when running through it was that in the section regarding Operators, it's not immediately obvious how to use the "drop down box". Perhaps changing the instructions to something like "Type 'Arithmetic Addition' in the text field and select from the list that appears" might be more clear.

On to the question. I'm sure there is a reason why proxies don't stack. I had never noticed this since I'd only ever built 1 before but the tutorial gives you five. If they haven't been used yet and therefore not been assigned an ID it seems intuitive that they should be stackable. Is it possible they could be? If it is in fact possible, a crafting recipe to clear an ID from a no longer used proxy might be a good idea too.

Love your work, keep it up!

**Comment by rubensworks** [comment]
Thanks!

You're right, the operator creation instructions aren't clear from the text, will rephrase.

Regarding the proxy stacking, this should indeed be improved. Variables can also have ID's, but can stack when their ID is cleared, so this should also consistently be possible with proxies (and delays).
