### ISSUE TITLE
Can't find part with ID #

### ISSUE THREAD

**Issue by mrlamb** [CyclopsMC/IntegratedDynamics#182]
Hey guys me again. 

https://www.dropbox.com/s/hzg0l1vozfnr62y/Screenshot%202017-05-23%2021.54.39.png?dl=0

Screenshot for ya to show the setup.

I loaded up single player tonight and the display screen on the right in the screenshot could not find the inventory reader shown on the left until I wrenched and replaced the cable. Working fine after that.

Let me know if you need any other information.

**Comment by rubensworks** [comment]
Are you using the latest ID version?
What exactly is the TOP tooltip and display gui saying?
Does anything special come up in the logs?

**Comment by mrlamb** [comment]
I'm using the latest version available via the twitch/curse client.

I tried loading up just now to see if I can get this info for you and naturally it didn't happen this time. I'll keep my eyes peeled.

The tooltip had your normal error line for when a part id isn't found in the network but I don't remember the wording. The display gui had the red X and the same message.

Further info: The display screen on the left in the screenshot is using a variable card reading a single slot's item from the apiary (the queen slot) when the problem happened that slot was empty. The display screen on the right in the screenshot is using the list of items from the apiary, this showed the big red X on the screen and the back of the screen was red. 

I don't know if WHAT I was using it for matters but there you go!

I'll try to get more info as soon as/if it happens again.

**Comment by rubensworks** [comment]
Ok, if you (or anyone else) has the same issue, be sure to send me as many details as possible. including *full* the forge log as there might be some useful debug information in there.

**Comment by rubensworks** [comment]
Considering this resolved.
