### ISSUE TITLE
NPE Crash when evaluating operator

### ISSUE THREAD

**Issue by tommyTT** [CyclopsMC/IntegratedDynamics#185]
**Issue Description:**
I'm trying to use Integrated Dynamics and Integrated Tunnels to solve the following problem: Take all items from a chest that are damageable and damaged and put them in another chest. I start out playing around with the different parts, so the first thing I'm doing is filter the list of items in a chest, so only damageable items are output on a display panel.

**What happens:**
After programming a variable card and putting it in the display panel the game crashes with a NPE. In a single player test world I'm able to log back into the world, but on my server it keeps crashing.

**What you expected to happen:**
If there is a problem with the program it should give a normal error, but there is no problem reported. In any case, the game cannot crash.

**Steps to reproduce:**
See http://imgur.com/a/W9gvO

1. Put down a chest and attach an inventory reader. Attach cables, a display panel and a variable store to form a valid network. (Picture 1)
2. Programm Variable Card 1 with the Item List Aspect from the Inventory Reader. (Picture 2)
3. Programm Variable Card 2 with the Operator "Item Damageable". (Picture 3)
4. Programm Variable Card 3 with the "filter" Method that applies the "is damageable" to the item list. (Picture 4)
5. Put Card 1 and 2 into the variable store. (Picture 5)
6. Put Card 3 into the display panel. (Picture 6)
7. Game crashes.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2310
Mods:
CyclopsCore-1.11.2-0.10.4
CommonCapabilities-1.11.2-1.3.3
IntegratedDynamics-1.11.2-0.7.2
IntegratedTunnels-1.11.2-1.2.2
jei_1.11.2-4.3.6.282.jar

**Your most recent log file where the issue was present:**
https://gist.github.com/tommyTT/02de2a1fe1fa0ad54203c8dcbe1813dd

**Comment by rubensworks** [comment]
Thanks for the detailed bug report, will look into it.
