### ISSUE TITLE
Crash tesselating cable

### ISSUE THREAD

**Issue by katecw** [CyclopsMC/IntegratedDynamics#191]
I experienced a client crash (NullPointerException: Tesselating block in world) while approaching my base (SMP) with the following report. This is the first time I've seen the error and Im not sure how to repeat it. The only thing I was doing differently this time is that I'd just exited a nether portal.

My current setup is quite simple. 3 ID generators (with energy importers) connected to 3 menril batteries (energy interfaces) and a fairly long cable which connects to a Refined Storage controller (energy exporter).

https://gist.github.com/katecw/9b720a8b3eb1d69c4483268d613e96f1

**Comment by rubensworks** [comment]
So the crash only occured once? Restarting the game fixed it?

**Comment by katecw** [comment]
Yes. When I logged back in after restarting my client I didnt get the crash again and havn't seen it again so far.

**Comment by rubensworks** [comment]
I don't see how this could possibly crash there...

I'll leave this issue open in case someone else manages to reproduce this.

Maybe some other mod is ASM'ing stuff and breaking it.
