### ISSUE TITLE
[1.10.2] Menril tree chance config option doesn't work or is explained backwards.

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedDynamics#202]
`    # The chance at which a Menril Tree will spawn in the wild, the higher, the lower the chance.
    I:general.wildMenrilTreeChance=5`

There should be trees everywhere but I can't even find one.

Also you should reword the comment similar to the filled logs. Its easier to understand then.

**Comment by rubensworks** [comment]
@Claycorp Are you sure you can't find any? Can you find wild trees with the default value?

**Comment by Claycorp** [comment]
Originally I started with RTG and was using that as the generator. I was finding trees but they seemed to be kinda rare for what I wanted. I changed the value thinking it would make them more common but I never saw them again.

Then when Open Terrain Control came out I switched to OTC and Biome Bundle. It took us a while to realize trees weren't spawning. So again, I made the spawn chance higher. Still no trees. I thought it might be an OTG issue and opened a report PG85/OpenTerrainGenerator#38 . Someone else said they get trees but I still don't.   

This is where I tested with 5 at this rate trees should be super easy to find and be spawning almost anywhere they can. I few around for 5 minutes and still found no trees. I flew through a few biomes too so it wasn't just one. I thought it was an issue with the OTG and Biome Bundle. Thus I started a vanilla world I spawned in near a roofed forest and flew around, I went over a plains and some swamp, with nothing to be found. I then flipped the number to 500 thinking the math was backwards and no trees spawned.  

If you need me to test something let me know. I can also give you the pack to test with if needed.

**Comment by rubensworks** [comment]
@Claycorp If you use vanilla worldgen with your custom value, do you see any trees spawn then?

**Comment by Claycorp** [comment]
"Thus I started a vanilla world I spawned in near a roofed forest and flew around, I went over a plains and some swamp, with nothing to be found. I then flipped the number to 500 thinking the math was backwards and no trees spawned."

OTG doesn't edit vanilla worldgen. I can try without out it but I highly doubt that would be the issue.

**Comment by rubensworks** [comment]
I just generated a world with `I:general.wildMenrilTreeChance=5`, and I see wild Menril Trees everywhere. So it must either be caused by your world generator, or you are incredibly unlucky.

I've improved the config descriptions as suggested.
