### ISSUE TITLE
Age of Engineering v1.0.3 - PartStateException Crash

### ISSUE THREAD

**Issue by LXGaming** [CyclopsMC/IntegratedDynamics#204]
https://pastebin.com/cxxdHMyW

**Comment by rubensworks** [comment]
Can you give any more details on what happened before/during/after the crash?

**Comment by LXGaming** [comment]
Not 100% sure on what happened, The server crashed a total of four times, this is the first crash - https://pastebin.com/7xUBi1bX - My best guess is a player placed something which crashed the server then when it start backup it crashed again when the player joined.

**Comment by rubensworks** [comment]
That second log is more useful, will look into it.

**Comment by rubensworks** [comment]
Can't reproduce this without additional information unfortunately.

Will add additional debug information in the next update, so if someone else would run into this issue in the future, please report all steps that were followed to cause the crash.

**Comment by rubensworks** [comment]
Another clue: Random crash when a wireless connector pointed to the nether: https://paste.ee/p/xvNGE
