### ISSUE TITLE
[1.12] Opening the manual renders the world transparent

### ISSUE THREAD

**Issue by fampat** [CyclopsMC/IntegratedDynamics#205]
When opening the Manual-Book the World gets "Transparent", like in noclip, i can see ores laying under the surface.

After closing the book it gets back to normal, see the images.

Minecraft 1.12
Forge 14.21.1.2406

Bug:
http://imgur.com/CC9fFg2

Normal:
http://imgur.com/osV0wUA

**UPDATE**
It seems that this only happens if there are animated recipes on the pages

**Comment by rubensworks** [comment]
I can't reproduce it with just ID+IT+CC(+ComCap) installed.
Can you try do reproduce it with just these mods on your end?

It could be another mod hooking into item rendering and forgetting to reset some rendering flags.

**Comment by fampat** [comment]
Hi, 
with just these mods there is no issue, so its another mod i guess.

**Comment by rubensworks** [comment]
Ok, my suggestion is to add/remove mods until you find the one that causes the issue, and report it to their issue tracker.
That mod will likely cause other related rendering issues as well.
