### ISSUE TITLE
Materializer doesn't stack after placing in world

### ISSUE THREAD

**Issue by Epic428** [CyclopsMC/IntegratedDynamics#206]
SkyFactory 3.0.13
Integrated Dynamics 0.7.3
Cyclops Core 0.10.5

Placing a materializer in the world then breaking it makes it no longer stackable. Not sure if this an intended feature or bug. It doesn't appear to get an ID that can be cleared in a crafting grid either. This occurs on the latest version of SkyFactory 3 while playing on a server. 

Let me know if you need more info.

Thanks,
James

**Comment by rubensworks** [comment]
They *should* stack, so something must be broken.

**Comment by linuxmant** [comment]
It seems they don't get an ID when placed (as seen with TheOneProbe)
playing latest Age of Engineering pack

**Comment by rubensworks** [comment]
Materializers shouldn't get an ID, so that's intended at least, but they should stack.
