### ISSUE TITLE
Redstone Writer achievement not completing

### ISSUE THREAD

**Issue by EricBuist** [CyclopsMC/IntegratedDynamics#207]
The Redstone Writer achievement is not detected as completed although I think I did it correctly. I connected a Redstone Reader and a Redstone Writer to a logic cable. I created a Variable and used the Redstone Reader to bind it to a boolean Redstone value. I installed the Variable in the slot of the Redstone Writer to emit a maximal strength signal when the boolean is true and also configured the property "strong" to true. If I use a lever to emit a redstone signal on the Redstone Writer, the signal is correctly propagated to the writer. No matter the strength of the input signal (tested with a Potentiameter), the signal out of the writer (tested with a redstone dust) is 15. Despite this, the achievement doesn't mark as completed. All other achievements I tried completed.

Integrated Dynamics 0.7.3
Sky Factory 3.0.13

**Comment by rubensworks** [comment]
The achievement requires you to use the Integer aspect, not the Boolean aspect. I see that's not mentioned in the description, will clarify that in the next update, thanks for bringing this to my attention.
