### ISSUE TITLE
Readers and writes disabled

### ISSUE THREAD

**Issue by Ironcanon** [CyclopsMC/IntegratedDynamics#210]
On Age of Engineering I was following the tutorial in the book but when I got to the Aspects page and tried to place the redstone reader and right click it nothing happened and in the info from The One Probe it said it was disabled. I then tried the other readers I had made, the block reader and the inventory reader, but they were also disabled.
How can I fix this?

**Comment by rubensworks** [comment]
It appears that AoE enabled power requirements in ID, so you'll have to hook up at least one Energy Battery.

**Comment by Ironcanon** [comment]
Thank you :)
