### ISSUE TITLE
Get block/item variables without said blocks/items

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#212]
It would be nice to have a way to get a variable card corresponding to a block or item without actually needing that block or item in your inventory. I remember an old item transport mod that let you set item filters by selecting items from NEI/JEI, even if you didn't have them and weren't in cheat mode. Perhaps we could either do that, or just add an operator to get an item from a string (e.g., "minecraft:quartz_ore" -> Nether Quartz Ore).

**Comment by rubensworks** [comment]
You actually _can_ use JEI for exactly this, by clicking on the `+` symbol on recipes.

But an operator like `get_block_from_id` or `get_item_from_id` might indeed be useful, will look into it.

**Comment by josephcsible** [comment]
Ah, I didn't know about that button, but I agree that having those operators would still be nice.
