### ISSUE TITLE
List Concatenation

### ISSUE THREAD

**Issue by deadly990** [CyclopsMC/IntegratedDynamics#215]
We've got the ability to append to lists,
I'm using this to try to read all of the contents of multiple chests, and I've been unable to find/create functions that will work to concatenate multiple reader item lists together.

This functionality might be useful when creating a list of items from one or more inventory that satisfies a predicate.

Is this something already do-able and I'm just missing it?

**Comment by rubensworks** [comment]
Oh, that doesn't exist yet?
I'll implement that for next release, as that is indeed quite essential.

**Comment by rubensworks** [comment]
Implemented in f0cebea81beb24e16f7166ccdfc73acf2caf75d6
