### ISSUE TITLE
Bitwise operators for integers appear twice in the book

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#218]
The following bitwise operators for integers are each listed twice in the Logic Programming section of the book:
* Or (|): page 6 and page 20
* Left Shift (<<): page 7 and page 22
* And (&): page 7 and page 20
* Xor (^): page 8 and page 21
* Complement (~): page 8 and page 21
* Right Zero Shift (>>>): page 9 and page 23
* Right Shift (>>): page 9 and page 22

**Comment by rubensworks** [comment]
What mod/MC version are you using?

**Comment by josephcsible** [comment]
Minecraft 1.12
Forge 14.21.1.2420
CyclopsCore 0.10.9
CommonCapabilities 1.3.4
IntegratedDynamics 0.8.1
