### ISSUE TITLE
Squeezer wont squeeze logs into liquid.

### ISSUE THREAD

**Issue by dahjin** [CyclopsMC/IntegratedDynamics#22]
Squeezer wont squeeze logs into liquid.

**Comment by rubensworks** [comment]
Last time I checked it worked just fine.
Are you jumping on it?
Are you certain that you are using the logs and not the planks?

**Comment by dahjin** [comment]
Yes. I jump on it. It goes all the way down. Nothing happens.
It also seems that there is another recipe getting registered that makes logs do nothing when squeezed.
http://i.imgur.com/XwFws6I.jpg

**Comment by rubensworks** [comment]
That might be the problem indeed. Could you send me your mod list? I'll look into it.

**Comment by dahjin** [comment]
http://i.imgur.com/9Em4XSO.png

**Comment by rubensworks** [comment]
@dahjin Could you the following dev build?: https://bintray.com/cyclopsmc/dev/IntegratedDynamics/1.8.9-0.3.3-190/view
This might be a fix for your issue, if not, please let me know and I'll have another look at it.
