### ISSUE TITLE
Subtraction Seems Reversed

### ISSUE THREAD

**Issue by bcrotty** [CyclopsMC/IntegratedDynamics#222]
When I did a Slots Filled - Slots, I got a negative number. Seems like it should switch back the operands.

**Comment by rubensworks** [comment]
Why do you think this would be a bug? Works as intended as far as I can see.

**Comment by bcrotty** [comment]
@rubensworks  81 (slots filled) - 32 (slots) should equal 49 not -49. It's switching the order to 32 - 81, which is wrong.

**Comment by rubensworks** [comment]
What inventory are you using? The total number of slots will always be larger than the number of filled slots.

**Comment by bcrotty** [comment]
You're right, I was mixing up which value indicated what. Sorry!
