### ISSUE TITLE
Make it easier to use custom operators

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#225]
Currently, the only way to directly use custom operators is to call ”apply” on them one operand at a time, creating an intermediate variable card each time. It would be nice to have a slot in the logic programmer where you can put a custom operator and then call it just like you would a built-in operator, with all of its operands at once.

**Comment by rubensworks** [comment]
Something like this is planned for the custom operator creation feature.

But in the meantime, I can easily add some more convenience apply operators with more parameters (apply 2, apply 3, ...), the code already supports it, there is just no visual interface for it yet.

**Comment by rubensworks** [comment]
Implemented in 2b1c32142abcfa99906cec2022285e925f2cd592

The LP slot is future work.
