### ISSUE TITLE
1.12 Meneglin Discovery advancement - How do you get this?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [CyclopsMC/IntegratedDynamics#228]
How do you achieve this advancement? I've chopped down a number of menril trees, and have no advancement popping up for me. Do I need to find the biome? Is there a specific amount I need?
Playing ATM3 v1.6 on 1.12 on a server.

**Comment by rubensworks** [comment]
Hmm, that might be a bug then...
Will look into it.
