### ISSUE TITLE
Get() returns wrong data

### ISSUE THREAD

**Issue by Vaevictusnet** [CyclopsMC/IntegratedDynamics#229]
1.) put a block reader on a block (is saying true)
2.) put variable card for has_block into delayer, see [true,true] (frequency 100, capacity 2)
3.) initialize integer card for 1 (or 0, same result)
4.) program get for delayer, 1
5.) in display panel, see "false", expecting true.

Using IntegratedDynamics-1.10.2-0.7.8.jar, no other mods other than ID dependencies. (common capabilities, cyclops core)

**Comment by rubensworks** [comment]
Seems to work just fine here based on the provided information.
If the issue persists, a minimal world copy demonstrating the problem would be nice :-)
