### ISSUE TITLE
[1.10.2] Drying basin minetweaker recipes don't work?

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedDynamics#233]
`mods.integrateddynamics.DryingBasin.addRecipe(<ore:plankWood>, <liquid:creosote> * 100, <immersiveengineering:treatedWood>, 250);
`
throws this error
`[SERVER_STARTED][SERVER][ERROR] DryingBasin.zs:6 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry, minetweaker.liquid.ILiquidStack, minetweaker.item.IItemStack, int)
This is usually an error in your script, not in the mod
addRecipe(Optional ZenTypeNative, Optional ZenTypeNative, Optional ZenTypeNative, Optional ZenTypeNative, ZenTypeInt )`

**Comment by rubensworks** [comment]
Your first argument needs to be an item, not an oredict entry.
I think you can iterate over all entries in an oredict key for that, but you'll have to check the MT manual for that.

**Comment by Claycorp** [comment]
Still doesn't work.

` DryingBasin.zs:6 > a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.liquid.ILiquidStack, minetweaker.item.IItemStack, int)
This is usually an error in your script, not in the mod
addRecipe(Optional ZenTypeNative, Optional ZenTypeNative, Optional ZenTypeNative, Optional ZenTypeNative, ZenTypeInt )`

`mods.integrateddynamics.DryingBasin.addRecipe(<minecraft:planks>, <liquid:creosote> * 100, <immersiveengineering:treatedWood>, 250);
`

**Comment by rubensworks** [comment]
This is the method signature: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.10/src/main/java/org/cyclops/integrateddynamics/modcompat/minetweaker/handlers/DryingBasinHandler.java#L30-L31
Looks like you forgot a nullable output fluid.

**Comment by Claycorp** [comment]
According to the error everything but the INT is optional. I'll throw it in there though give me a second.

**Comment by Claycorp** [comment]
And that fixed it.... Not sure why it says optional in the error when they are required.... Thanks for the help!

**Comment by rubensworks** [comment]
They are indeed optional, but MT probably only allows parameters to be left out only if there are no mandatory parameters after that.
