### ISSUE TITLE
Game Crash With Null Pointer

### ISSUE THREAD

**Issue by natedogith1** [CyclopsMC/IntegratedDynamics#234]
Here's the code I had built.  The game crashed as soon as I placed the `new_need` inside of the delay block that `need` references.  This was on the SkyFactory 3 modpack.
```
block_history = delay of block_reader.block, frequency=1, length=2
change        = size(uniq(block_history)) > 1
have          = proxy of static item
need          = delay of new_need, frequency=1, length=1
new_need      = change ? true : ( (need & have) ? false : get(need,0))
```
[crash-2017-08-07_03.27.54-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1204146/crash-2017-08-07_03.27.54-server.txt)

**Comment by rubensworks** [comment]
Your pack is using an outdated ID version, this was fixed in version 0.7.8.
