### ISSUE TITLE
[Request] NBT as List function

### ISSUE THREAD

**Issue by XenoStone1009** [CyclopsMC/IntegratedDynamics#237]
Would love to see an implementation where you can call for a list of NBT data as a list. It would really help for some instances of comparisons and automation in some aspects (like the Astral Sorcery crystal growth, which would require the a part of the NBT "size")

**Comment by rubensworks** [comment]
I've been thinking about this lately. I can probably do it by adding a new NBT value type with some operators around it.

**Comment by josephcsible** [comment]
I think this is done, so it can be closed now.
