### ISSUE TITLE
Meneglin biome too common?

### ISSUE THREAD

**Issue by BBoldt** [CyclopsMC/IntegratedDynamics#24]
I seem to get it at extreme amounts:

http://i.imgur.com/8LeXtMJ.png

**Comment by rubensworks** [comment]
It's possible that this can occur by pure chance, due to the way biomes are grouped.

If you go out a few thousand blocks, does it still spawn that frequently? If so, which biome-tweaking mods are you using?

**Comment by BBoldt** [comment]
I've been seeing it in every single test world i've generated. I'll do some further testing later this week. I was using BiomesOPlenty worldtype there. RWG is also installed, but not active on that world.

**Comment by rubensworks** [comment]
I haven't tested it with BOP yet, maybe I should do some additional tweaking to make it work decently there as well. I'll look into it as soon as I find some time :)

**Comment by rubensworks** [comment]
Reports have come in that it still spawns too much.
