### ISSUE TITLE
Add agreement with ProjectE

### ISSUE THREAD

**Issue by Blatts12** [CyclopsMC/IntegratedDynamics#242]
has EMC
how much EMC

is that possible?
thanks you in advance

**Comment by rubensworks** [comment]
I'm not really familiar with ProjectE.
I would assume they have a config file where you can enter your own values?

**Comment by Blatts12** [comment]
Yes, they have.

**Comment by rubensworks** [comment]
I suggest you configure the values using that config file, as adding support for that mod is a bit out-of-scope here. I only add compat for mods that can be read or written to using ID logic.
