### ISSUE TITLE
Tutorial Quests don't complete properly

### ISSUE THREAD

**Issue by Lumindia** [CyclopsMC/IntegratedDynamics#243]
Using Integrated Dynamics 1.12-0.8.4, and while going through the tutorial quests and completing an advancement, it triggers in the vanilla minecraft GUI, but the book sometimes refuses to acknowledge the fact that I actually completed it.

**Comment by Gayanfalor** [comment]
yep got the same thing on the  modpack i'm playing, i have made it worked by relaunching the game.

**Comment by rubensworks** [comment]
It can take up to three seconds for the client to sync with the player's advancement state on the server, did you wait this long?

**Comment by phlaxyr** [comment]
I have the same problem, however I waited waaay longer than 3 seconds. Even saving/quitting the world didn't fix it, I had to relaunch a new instance of Minecraft.

**Comment by rubensworks** [comment]
@phlaxyr Duplicate of #385. If you have any additional information you can give me (like in #261), please report it there.
