### ISSUE TITLE
Materializer Texture Issues

### ISSUE THREAD

**Issue by z64555** [CyclopsMC/IntegratedDynamics#244]
v. 1.12-0.8.2
Terms: Writer/materializer slots: the slots which variable cards are written to with the value of the reference card
Reference card: The variable card in the top slot of the GUI

Issue: The materializer's input/output port for the writer cards is currently the side that has a + on it, or at least it looks like it was supposed to be so. Currently, this is opposite of the side that has the actual I/O, which is confusing.

Additionally, the + marked side does not appear on the top or bottom, but the I/O port is in its expected spot.

**Comment by z64555** [comment]
Ooookay. Seems to be more wierdness to what I originally thought. I'll experiment a bit more and will compile some sort of report

**Comment by z64555** [comment]
Ok. So the materializer just flat out ignores the direction that you place or wrench it to, it'll look like you did something but the piping durections are absolute. (This is the same problem with the proxy)

Piping sides for the materializer and proxy are:
North: nothing
East: Write input slot (push+pull)
South: Read slot (push+pull)
West: Write output slot (pull only)
Top: Read slot (Push+pull)
Bottom: Read slot (Push+pull)

Again, this ignores the direction you place the machine to face.

**Comment by rubensworks** [comment]
Related to #245, will follow up there.
