### ISSUE TITLE
[1.12.1] Menril battery not exporting power

### ISSUE THREAD

**Issue by Gayanfalor** [CyclopsMC/IntegratedDynamics#246]
Hello, im plying the modern skuyblock 2 modpack nd have made a big menril battery but when i put redstone signal and energy exporter its not outputing energy  there is a rock cleaner out of power linked with energy interface but not getting energy

https://puu.sh/xcj4V/67e25e2821.png

**Comment by rubensworks** [comment]
On that screenshot it looks like you are inserting energy inside the battery, no extracting. You probably mixed up the importers/exporters.

**Comment by Gayanfalor** [comment]
hmm normal y bettery can extract just with redstone signal right ? the exporter is optional ?

btw i just moved the exporter on the rock cleaner and it seems working :s  sry for that.

Ps: i have found another bug too with the entity reader and to get advancements like what block i'm looking or the what modname is the item on the entiity reader. for this one each item i put on the entity reader saying its from minecraft mod while i have put the dagger from evilcraft and even the logic cable from Id.


thanks for quick response

**Comment by rubensworks** [comment]
The exporter is for _exporting_ energy from the network to a target. In this case, you made an infinite energy loop.

Please open a separate issue for any other bugs. And explain in detail what you do, and what you expect to happen, as I don't fully understand your explanation.
