### ISSUE TITLE
Network corruption due to chunk unloading

### ISSUE THREAD

**Issue by dahjin** [CyclopsMC/IntegratedDynamics#25]
http://pastebin.com/gAp3Uhf5

**Comment by codewarrior0** [comment]
I caused this crash by doing the following, roughly:

Placed a variable store and a block reader facing a Stone block.  Loaded the reader's Block aspect into a variable card. Used the programmer to create a `breaksound` card from it. Placed a sound writer and put the card into it. The sound played constantly until I removed the card.

Some minutes later (after leaving to harvest logs and returning, base was likely unloaded), I placed the same card in the sound writer. The server immediately went down.

After the server was restarted, right-clicking on the sound writer caused the server to go down again.

Breaking the sound writer did not drop the card, only the sound writer itself.

**Comment by rubensworks** [comment]
Thanks for reporting this, I'll look into it.

**Comment by rubensworks** [comment]
@codewarrior0 It looks like this issue was caused by a network that got corrupted.
Do you by any chance remember if you did anything else to the network except for unloading it?

**Comment by codewarrior0** [comment]
Don't think I did anything else. I set it up as described, then left to go harvest menril logs. When I came back, my buddy was in the base so I said "hey come look at this" and put the card back into the sound writer, crashing the server.

**Comment by rubensworks** [comment]
In that case this will probably be part of a larger issue, which I have to debug some further.

Do you remember what your network looked like? (Which readers/writers were part of it and how they were connected through variable cards)

In the meantime, you should be able to reset your network(s) by simply placing/removing one cable from the network, this should make everything work again.
The sound writer not dropping its variable card is part of a build-in safety for corrupted parts/networks.

If you were to run into a similar issue again, be sure to let me know.
