### ISSUE TITLE
[Request] Config to disable RF requirement

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#250]
It'd be great if there was a config option to turn of the RF dependence, and everything related to producing and providing the network with RF. If not this, then a way to configure power consumption and production would achieve the same ends for me (so long as 0 was a valid option).

**Comment by rubensworks** [comment]
Not sure what you mean, but with the `energyConsumptionMultiplier` config option (which defaults to 0), you can change the power consumption rate of networks. So power consumption is disabled by default.
