### ISSUE TITLE
Minecraft 1.12.1 Drying Basin bug

### ISSUE THREAD

**Issue by Realever** [CyclopsMC/IntegratedDynamics#252]
Hi,
i think i have a bug with the Drying Basin.I can not colored Terracotta change to normal Terracotta.here i have make a screenshot ttp see that nothing happend: 
![2017-08-21_13 37 26](https://user-images.githubusercontent.com/21349241/29517704-8e2452d8-8676-11e7-9f5b-b27bd70e55ef.png)

**Comment by rubensworks** [comment]
Ah, the stained clay has a new name now. Recipes will need to be updated.
