### ISSUE TITLE
Add IC2 Nuclear Reactor Support

### ISSUE THREAD

**Issue by nosyliam** [CyclopsMC/IntegratedDynamics#255]
Inventory Readers apparently can't read what's inside a nuclear reactor chamber and instead returns an error. IC2 reactor support would enable some great, cheap, and simple automation with Integrated Dynamics.

**Comment by rubensworks** [comment]
What MC and mod version are you using?

What aspects give an error? List and/or item reading?

**Comment by rubensworks** [comment]
@nosyliam Any further information you can give me?

**Comment by rubensworks** [comment]
Closing this one. If anyone can give me further comments on this error, be sure to comment here.

**Comment by MaxGivno** [comment]
Have same issue with Age of Engineering 1.1.0 pack. MC version 1.10.2, Integrated Dynamics 0.7.10 (tried 0.7.12 with same result).
Inventory Reader on filled IC2 reactor multi block shows this info:
Inventory Full: true
Inventory Empty: true
Inventory Not Empty: false
Is Inventory: false
Inventory Count: 0
Slots: ERROR
Slots Filled: 0
Fill Ratio: ERROR

**Comment by rubensworks** [comment]
> Is Inventory: false

This means that ID couldn't not detect any kind of inventory on the block.
I assume piping systems such as hoppers are also not working?

I haven't used IC2 reactors myself before, but perhaps one 'core' block _does_ allow you to interact with it?

**Comment by MaxGivno** [comment]
EnderIO item conduits working.

IC2 reactor has a kind of 'core' block - reactor itself, but it has to be surrounded with 6 chambers, so when structure is complete user have not direct access to reactor block. Instead any surrounding block can be used to access reactors inventory.

I understand what you mean by 'core' block, but I don't think IC2 reactor has it.

**Comment by rubensworks** [comment]
The only thing I can still think of then is that IC2 is not using the item handler capability on its reactor.

I won't be implementing support for non-capability item handling in 1.10 as I mainly work on the latest 1.12 version now, in which most mods have probably already moved to the new capability system.

**Comment by MaxGivno** [comment]
I see. It seem so. Will try my luck on IC2 forum ;)
Thanks for help :)
