### ISSUE TITLE
Place cable against cable crashes

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [CyclopsMC/IntegratedDynamics#26]
in creative when i click on a cable with an cable in right hand> game crush
clicking on emty block near cable, cable is placed correctly 

Mc 1.9 forge 65, CyclopsCore-1.9-0.5.6.jar;IntegratedDynamics-1.9-0.3.4.jar

**Comment by rubensworks** [comment]
@MUHAKLorTheDorfTrottel4Github Thanks for the issue, but could you also provide a link to the crashlog?

**Comment by rubensworks** [comment]
@MUHAKLorTheDorfTrottel4Github I'm not able to reproduce your crash, please provide a detailed description on how to reproduce this crash and most importantly: a crash log.

**Comment by rubensworks** [comment]
Closing this issue, since it is outdated and no new reports on this came in.
