### ISSUE TITLE
Crash when reading an entities inventory in the nether

### ISSUE THREAD

**Issue by wesserboy** [CyclopsMC/IntegratedDynamics#260]
I tried to read the inventory of a minecart with chest in the nether and it crashed.

This is the crashlog:
https://gist.github.com/wesserboy/2d4e6fae023ca07f407764242f2de4eb

I had a quick look at the code, and i thought it might have something to do with the nether having world id -1? not sure though ;)

**Comment by rubensworks** [comment]
Indeed, not sure why I thought that could ever work...
