### ISSUE TITLE
Quests doesn't give rewards; exception

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#261]
Clicking the quest complete buttons complete the quests but no reward is given. Instead, exception shows in server log.

All The Mods v3.02
Integrated Dynamics 1.10.2-0.7.9

[exception.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1266115/exception.txt)

**Comment by rubensworks** [comment]
Duplicate of #243

But thanks for the log, that's exactly what I needed! :-)

**Comment by ouroborus** [comment]
I saw that and wasn't entirely sure it was the same issue. Glad to help.
