### ISSUE TITLE
Minecraft unresponsive when Delayer set to 0 capacity

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#263]
If the value listed in the capacity field of a Delayer ever becomes `0`, Minecraft becomes unresponsive. There are several ways this can happen: Intentionally, by entering "0" into the field, or unintentionally, by editing a value that contains zeros such that at any time the remaining value is `0`. Emptying the field and then clicking the increase value button also causes this value to be `0`.

This has caused the world to be unloadable at least once for me. To recover, I used MCEdit to delete the problem Delayer.

I'd recommend adjusting it such that any value less than `1` is treated as `1` for this field.

**Comment by rubensworks** [comment]
I thought I recently fixed something similar to this, will look into it.
