### ISSUE TITLE
[Suggestion] Forestry support for Menril trees

### ISSUE THREAD

**Issue by Lykrast** [CyclopsMC/IntegratedDynamics#264]
While this is probably not worth the effort, being able to breed Menril trees using Forestry in order to get bigger trees that yield even more berries (or any other genetic stuff that tree breeding allows) would be a nice addition.

On a simpler note, being able to make fireproof Menril planks using Refractory Wax (just like Forestry planks) would also be nice.

**Comment by rubensworks** [comment]
Good idea, but this is out of scope for this mod, other mods/addons would be ideal for something like this.
