### ISSUE TITLE
[1.12.1][Minor]Version checker isn't up to date

### ISSUE THREAD

**Issue by TheSaucyWelshman** [CyclopsMC/IntegratedDynamics#269]
I just updated ID to version 1.12-0.9.0 and the update checker is saying a new version (0.8.7) is available. I'm getting the same thing with Everlasting Abilities 1.3.3 saying 1.3.2 is newer, I can open a separate issue there if you want but I assume this is an easy fix for both of them.

**Comment by rubensworks** [comment]
CyclopsMC/CyclopsCore#70
