### ISSUE TITLE
Tinkers stone torches turning into menril torches 1.12.1

### ISSUE THREAD

**Issue by DingoX3** [CyclopsMC/IntegratedDynamics#270]
https://imgur.com/oUrwXPJ
If you watch my hot-bar at the bottom you can see them change as i close my inventory.
MC: 1.12.1
modpack: Stella (twitch launcher)
Integrated Dynamics: 0.8.7
forge: 2474

**Comment by rubensworks** [comment]
Please report this to the pack author first, this sounds like a recipe conflict caused by changed recipes, as you should only be able to craft Menril Torches using Menril Berries.

**Comment by DingoX3** [comment]
Im not crafting menril torches. If you look at the gif i posted it shows me crafting tinkers torches, and the output is in fact tinkers torches but an id change happens when i close and re-open my inventory. I will mention this the the modpack author though.

**Comment by josephcsible** [comment]
I looked into this myself, and I found it was caused by [InstantUnify](https://minecraft.curseforge.com/projects/instantunify). It was removed from Stella 1.2, so the problem doesn't occur there anymore.
