### ISSUE TITLE
Restrict NBT reading

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#271]
Some mods put data in NBT that players aren't supposed to be able to see. Most other mods that offer ways to look at items don't show NBT at all, so this isn't a concern for them. To fix this, I propose adding an NBT blacklist, which would prevent blacklisted tags from being readable (or used in comparisons with the NBT equals test).

**Comment by rubensworks** [comment]
Could you give some examples of which things shouldn't be read?

**Comment by josephcsible** [comment]
I can't find a good example right now. I'll post it as soon as I think of it. (I did find http://ocdoc.cil.li/component:database and https://openmods.info/faq.html#op-integration-0 that talk about this very concern, but neither of them give a specific example either.)

**Comment by PaulMurrayCbr** [comment]
Astral Sorcery will not permit a user to view a crystal's stats untill they have reached a certain level of advancement. However, this seems to be coded in rather than configured.

**Comment by josephcsible** [comment]
@PaulMurrayCbr What specifically are you asking us to do?

**Comment by PaulMurrayCbr** [comment]
I'm saying that there's no feasible way for Integrated Dynamics to do what the OP is asking. If it's wired into the code for each mod, then ID would have to know about the details for each mod. There's also the point that Minecraft is multiplayer - should an integrated dynamics object work or not work depending on who is looking at it? It's not feasible.

Regrettably, this means that ID is necessarily going to be somewhat "cheaty", and there's no way to address that.

**Comment by josephcsible** [comment]
It doesn't necessarily have to be cheaty. You could easily just set it to never be able to read crystal stats via NBT.

**Comment by PaulMurrayCbr** [comment]
Didn't know that. Don't know most things about minecraft programming, really. I code java, but I haven't coded minecraft mods or anything like that.

Maybe I shouldn't be using github issues like a chat forum :)
