### ISSUE TITLE
Drying basin only works once

### ISSUE THREAD

**Issue by novasolarius** [CyclopsMC/IntegratedDynamics#28]
Trying to make menril blocks. Sadly, the drying basin seems bugged. It made the first menril block just fine, but subsequent attempts have only resulted in the basin filling, keeping the resin inside for a bit, then emptying all of a sudden. Breaking and replacing doesn't help. Making a new basin does, but only for one block.

I'm not sure how relevant this is, but a used basin has eleven NBT tags, if JEI is to be believed.

**Comment by rubensworks** [comment]
1.9 or 1.8.9?
Which mod version are you using?

**Comment by novasolarius** [comment]
1.9. I'm running ID 0.3.6, of course.
