### ISSUE TITLE
[1.10.2] Forestry Squeezer in Machine Reader causes Server Crash

### ISSUE THREAD

**Issue by Column01** [CyclopsMC/IntegratedDynamics#281]
**Hello Developer Team,**

Recently, we have discovered an issue with the Machine Reader in version: IntegratedDynamics-1.10.2-0.7.10. If you put the Forestry Squeezer in the Machine Reader, and open the GUI, it causes the server to crash. We are aware that we are running an outdated version of the mod, but nothing in your change-log indicates a fix to this issue. 

**Mod Versions:**
CyclopsCore-1.9.4-0.10.8
IntegratedDynamics-1.10.2-0.7.10
forestry_1.10.2-5.2.17.386

The crash report can be found [here](https://gist.github.com/Aiidoneus/585cb9e9d07710333ed6ef9a69320226).
Thanks for reading!
**-Colin**

**Comment by rubensworks** [comment]
Seems related to an outdated CommonCapabilities integration, will look into it.

**Comment by Column01** [comment]
Keep me posted.
-Colin

**Comment by rubensworks** [comment]
New CommonCapabilities release with this fix is coming soon.
