### ISSUE TITLE
Server crash after breaking cable

### ISSUE THREAD

**Issue by phit** [CyclopsMC/IntegratedDynamics#282]
Crashlog: https://gist.github.com/phit/09e7af7cead0046efbcc1acb1f0cc6b2
Mod version: IntegratedDynamics-1.12-0.8.7.jar 

Description from the player:

> It was a block that had a cable, redstone reader, redstone writer in it. I broke the reader then the writer dissapeared and the cable disconnected from surrounding things
> then I tried to break it and it wouldnt break so I tried relogging

when he relogged the server crashed, and crashed every time thereafter the player loaded the chunk
had to remove it manually via mcedit to stop the crashing

**Comment by rubensworks** [comment]
Note to self: `updateableElementsTicks` is not being initialized correctly if the part was not loaded initially.
