### ISSUE TITLE
Servercrash while finish the chanllege (sponge step sound)

### ISSUE THREAD

**Issue by yuanjie000** [CyclopsMC/IntegratedDynamics#285]
forge server version 2422
mc version 1.10.2
IntegratedDynamics-1.10.2-0.7.12
IntegratedTunnels-1.10.2-1.2.5
[crash](http://paste.ubuntu.com/25577437/)
![1111111111111](https://user-images.githubusercontent.com/20902900/30626876-78793b60-9dff-11e7-8bad-33616c1bafce.png)
once put this card in audio writer, the server crash!
also tried in single game, but everything is fine. maybe a server side crash?
**screenshot of the setup**
![setup](https://user-images.githubusercontent.com/20902900/30627014-46c46a62-9e00-11e7-97d1-e15970f76c62.png)

**Comment by rubensworks** [comment]
That crash should not be possible, will have to investigate.

In the meantime, could you check if you can reproduce it without any other mods installed?

**Comment by yuanjie000** [comment]
I just put IntegratedDynamics in server and reproduce this [crash](http://paste.ubuntu.com/25578118/)
