### ISSUE TITLE
Bug in a TE writeToNBT() method

### ISSUE THREAD

**Issue by maruohon** [CyclopsMC/IntegratedDynamics#286]
There seems to be either a failed copy & paste, or some left-over debug remnant here:
https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/java/org/cyclops/integrateddynamics/core/tileentity/TileMultipartTicking.java#L108

This is potentially quite bad, because if that `markDirty()` is or calls the vanilla `TileEntity#markDirty()`, then it can cause block updates (via `World#updateComparatorOutputLevel()`) and even new adjacent chunks to get loaded while the chunk this tile is in is being saved. And of course it also always marks the chunk as dirty while it's being written... which shouldn't really do anything but still.

We are currently investigating several TileEntity NBT reset related issues on the ATC server, and this is one possible cause for at least some of the issues we are seeing.

**Comment by rubensworks** [comment]
That should not be there indeed.

Looks like it has been there [for a long time](https://github.com/CyclopsMC/IntegratedDynamics/commit/b00a45ad751c29a1d24e7ab950ecebac39f79e63#diff-57ff494ba131861f348e3d514d141955R53) though...

Will look into removing it for the next update.
