### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by yuanjie000** [CyclopsMC/IntegratedDynamics#288]
[Crash](http://paste.ubuntu.com/25605834/)
I want to export honey comb (from foresty) through oredictionary _beeComb_
so I create a string type variable card named _beeComb_
![bee](https://user-images.githubusercontent.com/20902900/30780945-a2e059b4-a148-11e7-8a57-aa0303ea174d.png)
then use `oredictionary value (oredict)` to get this variable card 
![crash](https://user-images.githubusercontent.com/20902900/30780913-3c447e38-a148-11e7-9450-5c9487a2cb2b.png)
Once put this variable card into _display panel_ or _item exporter_ (from IntegratedTunnels)
it crash.

IntegratedDynamics-1.10.2-0.7.13
IntegratedTunnels-1.10.2-1.2.5
forestry_1.10.2-5.2.17.388
forge-1.10.2-12.18.3.2422

**Comment by rubensworks** [comment]
Fixed in the dev version. Won't be able to release a new build on curseforge in the next coming 2 weeks, so feel free to use the dev version in the meantime.
You can find a link to the dev builds on the README page of this repo.

**Comment by yuanjie000** [comment]
thanks for the work：)
