### ISSUE TITLE
Conflicting squeezer recipe

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#29]
"
I tried to play with "Integrated Dynamics" and wanted to get "Menril Resin" so i build a Squeezer, placed a Menril Log inside and started jumping on it.
Instead of the Resin i got a piece of "Mithril Blend" from Base Metals.
"

**Comment by Insufficient-Charge** [comment]
Just accidentally made a dupe of this issue, please ignore it D: Also in JEI the recipe for the mithril blend inside a squeezer is "nothing" ... so yea.
![2016-05-03_21 52 37](https://cloud.githubusercontent.com/assets/13188566/15004257/59a23d12-117a-11e6-898d-86da06e58285.png)

**Comment by rubensworks** [comment]
(Probably) fixed in CyclopsMC/CyclopsCore@d02db80d6d55757c0cd35268ceacda4465f31372
Currently preparing a new release.
