### ISSUE TITLE
Item/Block/Fluid from JEI can not be inserted into List

### ISSUE THREAD

**Issue by Timeslice42** [CyclopsMC/IntegratedDynamics#292]
You can use JEI to fill an Item, Block, or Fluid, but you can't use it to fill an Item, Block, or Fluid when adding an entry to a List. It would be nice to be able to do so.

**Comment by rubensworks** [comment]
Last time I checked this was possible. What versions are you using?

**Comment by Timeslice42** [comment]
Integrated Dynamics 1.12-0.9.2
Integrated Tunnels 1.12-1.3.2
CyclopsCore 1.12-0.10.19
JEI 1.12.2-4.7.11.102

What else might be relevant?

**Comment by rubensworks** [comment]
That should do, thanks.
