### ISSUE TITLE
Clarify itembyname and get item registry name

### ISSUE THREAD

**Issue by Timeslice42** [CyclopsMC/IntegratedDynamics#293]
Much to my suprise the output of the "name" operator does not give an Item when piped into the "itembyname" operator.

What is the expected format for the name of the item in "itembyname"?

**Comment by rubensworks** [comment]
The name operator returns the localized name of an item, as shown to the player ingame. The itembyname operator expects the _unique_ identifier of an item, like `minecraft:stone` and `minecraft: pumpkin_seeds`.

**Comment by Timeslice42** [comment]
Could you put that information into the tooltip description of "itembyname"?

**Comment by rubensworks** [comment]
Sure.

**Comment by josephcsible** [comment]
I wonder if it's also worth making an operator that gives the registry name of an item.

**Comment by rubensworks** [comment]
@josephcsible Good point, will incorporate that in this issue.
