### ISSUE TITLE
[1.12]Bug? Proxy not work

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#295]
![image](https://user-images.githubusercontent.com/23412916/31305230-2be3e37a-ab67-11e7-907e-b95b7d9e56e4.png)
![image](https://user-images.githubusercontent.com/23412916/31305221-e4f81e54-ab66-11e7-9a05-74f027c5efa4.png)
![image](https://user-images.githubusercontent.com/23412916/31305227-03c2d504-ab67-11e7-8b2f-c3d9ddb9e467.png)
Fix it!

**Comment by rubensworks** [comment]
Are you sure that the variable with ID 29 is still inside your proxy?

**Comment by Flithor** [comment]
Yes.

**Comment by Flithor** [comment]
Oh, Sorry. Not bug, I removed variable ID 29 in proxy with ID 0.
But I think must put variable card in proxy block is very waste of space.

**Comment by rubensworks** [comment]
> But I think must put variable card in proxy block is very waste of space.

Well, that's simply how a proxy works.

**Comment by Flithor** [comment]
Oh, I see...

**Comment by josephcsible** [comment]
A while late, I think I realize what's actually being asked here. Instead of making the proxy hold an actual variable card in its input, could it hold a "ghost" of a variable card like the logic programmer does while building expressions (actually storing it by ID), and have the actual variable card be in a variable store on the network?

**Comment by rubensworks** [comment]
@josephcsible Not a bad idea, I don't see a reason why that could cause any problems. This would be a breaking change though, so perhaps something for a next MC update.

**Comment by Flithor** [comment]
At that time, I also found this problem, variable cards in the proxy & delay are cannot be identified in the network.

**Comment by josephcsible** [comment]
Do you mean that if you have a variable card in a proxy or materializer, you want other things in the network to be able to see it, as if it were in a variable store?

**Comment by Flithor** [comment]
yes
