### ISSUE TITLE
[Suggestion]Add line break char/Bigger screen pls

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#296]
Long strings will not be displayed clearly.
And want to display string like

```
Need Craft
   true
```
on screen.

**Comment by rubensworks** [comment]
So you want to make something like `\n` automatically convert to a newline in a Display Panel?

**Comment by josephcsible** [comment]
If we're going to make `\n` be a newline, we should also make `\\` be a literal backslash so that it's possible to display a literal `\n`.
