### ISSUE TITLE
[1.12]Variable Card(or anything) Copy Bug

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#297]
1.**Mark** a variable card in logical programmer GUI any operator card mark cell
![image](https://user-images.githubusercontent.com/23412916/31305487-4994d87e-ab6d-11e7-9da6-32d47a129c73.png)
2.Double click marked card in package
3.The **Mark** will become a real card in your package
![image](https://user-images.githubusercontent.com/23412916/31305492-5c0337a8-ab6d-11e7-84aa-6025c2cdf502.png)
~~Blank or assigned card~~ Any items are can trigger this bug,
![image](https://user-images.githubusercontent.com/23412916/31305503-b28efe0e-ab6d-11e7-9be9-a9ae1bb0209a.png)
![image](https://user-images.githubusercontent.com/23412916/31305517-1c85e386-ab6e-11e7-92f0-1704d24980df.png)
![image](https://user-images.githubusercontent.com/23412916/31305533-844b564a-ab6e-11e7-8958-fcbe82e6ac18.png)
![image](https://user-images.githubusercontent.com/23412916/31305535-9aece404-ab6e-11e7-9b81-31e95bc3a4b7.png)
 
------------------------------
apply3 can copy 4 card once!
![image](https://user-images.githubusercontent.com/23412916/31305574-9bd4eb90-ab6f-11e7-95c9-c47088ab68bf.png)
![image](https://user-images.githubusercontent.com/23412916/31305579-b56cf8c2-ab6f-11e7-9a6b-5e5fb4ffc274.png)

**Comment by rubensworks** [comment]
I assume these copied variable cards disappear from the moment you close the LP gui?

**Comment by Flithor** [comment]
No, closed GUI still exist.
I said, "become a real" items.

**Comment by rubensworks** [comment]
I can't reproduce this. Did you have any other mods installed?
If so, please try reproducing this without any other mods installed.

I assume mods like mouse tweaker messing with this behaviour.

**Comment by Flithor** [comment]
No, I checked if ID only, this bug still exist.
![image](https://user-images.githubusercontent.com/23412916/31571138-c9b979d6-b0bf-11e7-8c7b-2bccf1ebf876.png)
Gif here
![bug](https://user-images.githubusercontent.com/23412916/31571128-b85a88ce-b0bf-11e7-8b35-15c039d04eec.gif)
Cannot stack item can't be copy.

**Comment by rubensworks** [comment]
Ah ok, you double click on the item inside your inventory, that wasn't clear to me.
