### ISSUE TITLE
Proxy (x,z) dependence bug

### ISSUE THREAD

**Issue by immortaleeb** [CyclopsMC/IntegratedDynamics#3]
1. Place a proxy on (x1, y1, z1) in a network
2. Bind a proxy card and put it in a screen in the same network: it will correctly output any variables in the top proxy slot.
3. Break the proxy with a wrench (shift+rightclick)

If you place that proxy on a position (x2, y2, z2) in the network where (x1, z1) == (x2, z2) then any values in the top proxy slot will correctly be shown on the screen.

If you however place the proxy on a position where (x2, z2) != (x1, z1), then the proxy will be unable to find the variable in the network.

**Comment by rubensworks** [comment]
Apparently it was independent of the (x,z) coordinates after all.
The problem was that the cable connections were saved into the item and not reset after placement.
