### ISSUE TITLE
[1.12]To String get Operation name fail

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#304]
Easy to understand
![image](https://user-images.githubusercontent.com/23412916/31339198-a4673a76-ad34-11e7-97b3-ce509b5f09f0.png)

**Comment by rubensworks** [comment]
> Easy to understand

No, can you provide more information?

**Comment by Flithor** [comment]
If you have a operator variable card, and use To String operator to get it name, will get this language file field set string rather than the operator name.
![image](https://user-images.githubusercontent.com/23412916/31364722-3d4889f2-ad99-11e7-9d4d-1721d2afe1ba.png)
by the way, how to rename the variable card?

**Comment by rubensworks** [comment]
> how to rename the variable card?

Use the labeller
