### ISSUE TITLE
Generator consumes buckets

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#305]
When a lava bucket is placed in a generator, it is consumed entirely instead of leaving behind an empty bucket like furnaces do. Tested on Minecraft 1.12.2, Forge 14.23.0.2512, CyclopsCore 0.10.20, CommonCapabilities 1.4.0, and IntegratedDynamics 0.9.2.

**Comment by rubensworks** [comment]
This used to work correctly in the past, so must be a regression.

**Comment by MissPotato** [comment]
This bug is happening again.

**Comment by josephcsible** [comment]
I can't reproduce it on 0.10.0. Can you post your versions and mod list?

**Comment by MissPotato** [comment]
https://pastebin.com/xNydf5AL

This includes the mod list and versions, but:
This mod: 0.10.0
CyclopsCore: 0.11.0
Minecraft: 1.12.2
Forge: 2587

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/xNydf5AL">AppleCore-mc1.12.2-3.1.0.jar  Aroma1997Core-1.12.2-2.0.0.0.b135.jar  Aroma1997s- - Pastebin.com</a></strong></div></blockquote>

**Comment by josephcsible** [comment]
Are you playing single-player or on a server? Also, can you reproduce the problem with just ID and its dependencies installed?

**Comment by MissPotato** [comment]
I can not reproduce with just those two mods, and it happens in multiplayer.

**Comment by josephcsible** [comment]
That's quite a long mod list then. Can you try to narrow down which other mod makes it happen? Also, can you reproduce it at all in single player?

**Comment by MissPotato** [comment]
I'll try single player, I'm currently streaming tho, so the search will have to wait. Sorry.

**Comment by MissPotato** [comment]
I can't seem to produce this on it's own, and I'm having a hard time narrowing it down.

**Comment by rubensworks** [comment]
@MissPotato The best test would be to check if it occurs in Vanilla Furnaces is well. My assumption is that that will be the case for you.
