### ISSUE TITLE
[Suggestion] Adjust Facade recipe to use slimeball oredictionary entry

### ISSUE THREAD

**Issue by jeffreyheinen** [CyclopsMC/IntegratedDynamics#306]
Allowing any type of -slimeball would be greatly helpful for skyblock maps, where we may not always have a slime chunk in the nearby area.

**Comment by rubensworks** [comment]
Oh, it's not using the oredict key? That needs to be changed indeed.

**Comment by jeffreyheinen** [comment]
Forgive me, I should have put this info. I did not doublecheck the current release version compared to what is in the modpack. I did not see anything in the issue list however.

Modpack: Sky Factory 3, version 3.0.15
Minecraft Version: 1.10.2
Mod Version: 0.7.12

**Comment by rubensworks** [comment]
No problem, no open issues for this exist.

I won't be implementing this for 1.10.2 anymore though. 1.12.2 is out main release target now, 1.10.2 is only maintained for major bugs.
