### ISSUE TITLE
[Suggestion]Consider the attachments of I.D compatible with TD pipes?

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#307]
Someone suggest Thermal Dynamics add Custom Attachments.
https://github.com/CoFH/Feedback/issues/561
Consider the attachments of I.D compatible with TD pipes?

**Comment by rubensworks** [comment]
The (capability-based) ID API should already allow this to be done. Furthermore, our API also would allow for TD parts to be attached to ID cables.

I won't be implementing this myself though, I have many more other more urgent things to implement. But feel free to send a PR or implement it as a separate mod, or anyone else reading this.

**Comment by rubensworks** [comment]
Won't implement.
