### ISSUE TITLE
Offsettable readers

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#308]
In some cases, I tried to get the required data from the NBT data of a block, but it only saved the coordinates of the other block. The coordinates may be dynamic, 
have a solution?
Or suggest this.

**Comment by rubensworks** [comment]
I don't understand your question.

You can only get data from the reader's target area.

**Comment by Flithor** [comment]
@rubensworks 
The RFTools screen module uses a wireless way to read the fluid or RF data of a block, and I want to read the data from the module located in the screen, but it actually the module stores only the target block coordinates without actual data.

**Comment by rubensworks** [comment]
So you want a way to read data from an RFTools screen?

Or do you want a way to change the target area of any kind of reader?

(The latter is something that is a planned long-term feature)

**Comment by Flithor** [comment]
Try add a "Target Block Proxy".
Put 3 Integer variable card to determine a coordinate, The Block Reader can read it as the target block.
(Perhaps a more eclectic way, not too OP)

**Comment by rubensworks** [comment]
A way to read any kind of block anywhere seems a bit too OP IMO.

Having (restricted) offset parameters in readers on the other hand would be better, and is something that is planned. That way it is not limited to only block reading.

**Comment by Flithor** [comment]
Some of the more complex and compact institutions have few spare positions to place ID cables.
I think the higher cost of the target proxy is a better choice.
Moreover, the target proxy can also have a entity proxy.

**Comment by rubensworks** [comment]
Offset parameters on readers can achieve the same thing, are more expressive, and easier to balance.

**Comment by Flithor** [comment]
Are you planning to use variable cards or constants to set offset??

**Comment by rubensworks** [comment]
They will be regular part settings, just like the priority and frequency settings.

But just like aspect parameters, they will become dynamically configurable using variable cards (#197)

**Comment by Flithor** [comment]
@rubensworks 
Block Reader=>
=>Target block Var Card=>
=>Target block coordinate=>
(Calculate the offset value with the known coordinates)
=>Offset=>
**=>Use Copy to copy offset as constant var card=>**
=>Set Block Reader Offset=>
=>Block Reader Target block change=>
~=>Target block coordinate change=>
(Calculate the offset value with the known coordinates)
=>Offset=>
=>Block Reader Target block change=>
=>Dead loop~
=>Safe

~So I think you need to add a new "Offset target block" list item in Block Reader GUI instead of simply changing the faced block target list item.~
~↑There is still a risk, if not use copy, it may even lead to the game to stop or crash.~
~↑You can ask for player only use constant variable cards to set offset.~
↑It will cause can't dynamic offsetting.

**Comment by Flithor** [comment]
↑Do you have any idea of these?

**Comment by rubensworks** [comment]
Yes, I know how to implement it, it will just take a while before I will have time to implement it. As mentioned before, it's a long-term planned feature.

**Comment by ByteZ1337** [comment]
When will this be implemented? I really need something like this.

**Comment by rubensworks** [comment]
Done in 8ff347cbbaf37adb3f921246dad774e866bd12d2

**Comment by Flithor** [comment]
Oh~ that's really loooooooong term feature.
