### ISSUE TITLE
Moving a reader with a piston causes a crash.

### ISSUE THREAD

**Issue by ConnorMiner** [CyclopsMC/IntegratedDynamics#309]
When I was trying to make a system to launch items, the slime blocks moved by the sticky piston remained in their positions due to the pulse being too long. When I made the sticky piston extend and retract again, the slime blocks took a cable with an Entity Reader on it with them as they were pulled towards the sticky piston. The game crashed right after the retraction was complete. Upon re-entering the world, the Entity Reader was gone.
[crash-2017-10-12_20.30.48-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1381258/crash-2017-10-12_20.30.48-server.txt)

**Comment by rubensworks** [comment]
Cables are not movable by pistons or slime blocks, so I suspect another mod in your pack is changing things. The mod that is causing this must be moving blocks in a way ID is not expecting. If you can identify this mod, please let me know.

**Comment by ConnorMiner** [comment]
I remember Quark allowing TileEntities to be moved by pistons, and that was in the pack at the time the issue occured.

**Comment by rubensworks** [comment]
@ConnorMiner Thanks, I'll have a look to see what Quark is doing for that.

**Comment by rubensworks** [comment]
Quark has a `Tile Entity Movement Blacklist` property, please add `integrateddynamics:cable` to that.
