### ISSUE TITLE
Menril trees not spawning in already existing worlds

### ISSUE THREAD

**Issue by Insufficient-Charge** [CyclopsMC/IntegratedDynamics#31]
As #23 shows that there usually is lots of Menril trees around...this made me wonder, because I could not find a single menril tree in my singleplayer world. Even in newly generated chunks.

However, in my modpack I added many mods to my modpack AFTER I generated my world, which is normally a bad idea... but yea, just saying.

**Comment by Insufficient-Charge** [comment]
I also live in a forest, and also searched a forest that was generated with Integrated Dynamics installed.

**Comment by rubensworks** [comment]
Last time I tested this, this worked just fine.
What mod and MC version are you using?

**Comment by Insufficient-Charge** [comment]
What is it with your issues section that aalways makes me go back on my word ;/ second time in 10 hours... Just found a menril tree... sorry for wasting your time D:
