### ISSUE TITLE
[1.12]Chinese list item not display bug inspected

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#310]
I check my mod list, and find the culprit.
JustEnoughCharacters mod
This mod by a Chinese moder produced. It can be able to make a variety of search box support pinyin search Chinese.
![image](https://user-images.githubusercontent.com/23412916/31555683-8f5dca9e-b074-11e7-889e-52c7022bb2ef.png)
![image](https://user-images.githubusercontent.com/23412916/31555672-82c148a6-b074-11e7-9c45-8c8d4498393c.png)
Try to get in touch with him to solve this problem.
https://github.com/Towdium/JustEnoughCharacters

**Comment by Towdium** [comment]
This issue should be on my side. I'll handle it.

**Comment by rubensworks** [comment]
@Towdium Thanks!

**Comment by Flithor** [comment]
@rubensworks 
Unfortunately, your modified code does not solve the problem, and JEC has also appeared in the bug that the game can not start, it seems that when the problem is completely resolved before I have to use a period of time in English list
