### ISSUE TITLE
[1.12.2]NetWork Reader not wrok

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#314]
![](https://user-images.githubusercontent.com/23412916/31668596-3522d826-b385-11e7-9c11-c6e745668c38.png)
I tried AE2 network; TF-RF/Logistics network; IC2 network
(Near by pipes, cables, machines, energy batteries)
Are can't discern.
PLS fix it!

**Comment by rubensworks** [comment]
> I tried AE2 network; TF-RF/Logistics network; IC2 network

The network reader only reads **ID networks**.

> PLS fix it!

This comes across very hostile, please don't write like this again.
