### ISSUE TITLE
[1.12.2] Tree replaces block when growing

### ISSUE THREAD

**Issue by boop5** [CyclopsMC/IntegratedDynamics#316]
Just tried automating the menril trees. Problem is that the trunk replaced the industrial foregoing plant gatherer. 

Not sure if issue or intended. But either don't grow a log at this place or don't grow at all. But don't replace blocks. imo

Playing on ATM3 4.2 with IntegratedDynamics-1.12-0.9.2

**Comment by rubensworks** [comment]
That should indeed not be happening, will look into it.

**Comment by rubensworks** [comment]
It looks like this bug must have existed since the initial implementation, thanks for reporting!
