### ISSUE TITLE
[1.12.2]Redstone clock has a bug. Specal pulse setting will not outout pulse.

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#318]
You can try to modify the pulse interval & pulse length like this. (3,2),(7,5),(10,5),(12,6)...
If pulse interval is less than or equal to two times of pulse length, will always out put true.

**Comment by rubensworks** [comment]
Actually, this is not a bug.

Pulse length can at most be half of the pulse interval, because both a true and false pulse of that length must fit in the interval.

This will be clarified in the next update.

**Comment by Flithor** [comment]
Please inform me here when you had updated the document(language file).

**Comment by rubensworks** [comment]
What document? The language file? That has been updated in the commit mentioned above.
Will be included in next update.

**Comment by josephcsible** [comment]
There's no reason that this can't work. #344 will make it work.
