### ISSUE TITLE
[Question]Can you talk about the meaning of "Menril"?

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#321]
It seems to be a coinage.
Current Chinese is a direct transliteration, looks very strange and hard to pronounce.

**Comment by rubensworks** [comment]
Menril is actually a word from the fictional Sindarin language, in which it means "sky"+"glitter".

Feel free to change it if you feel like you would have a better translation for it.

**Comment by Flithor** [comment]
Does the word describe the stars?

**Comment by rubensworks** [comment]
Not really, it actually doesn't really have a meaning.

I simply chose that word because it's the combination of sky and glitter in Sindarin.
Which makes sense, because Menril is blue and a bit shiny.

But feel free to change it to another (potentially meaningless) word in Chinese that also sounds nice.

**Comment by Flithor** [comment]
I can't find this word in Sindarin dictionary...

**Comment by rubensworks** [comment]
It's a combination of two words. I don't remember exactly how I combined them though.

**Comment by Flithor** [comment]
menel(sky) + ?-ril(glitter)
But I can't find any words end with "-ril" meaning glitter....

**Comment by Flithor** [comment]
Try to translate to the"星域", meaning is "the region of the stars".

From Sindarin word "menel" meaning:
> menel - n. sky, high heaven, firmament, the region of the stars

The star is light & glitter, and region of stars is the sky.
~How is it?~
But it seem not contains the meaning of sky blue...
