### ISSUE TITLE
Logic cables invisible after breaking and replacing

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#325]
Minecraft 1.12.2
Forge 14.23.0.2491
Cyclops Core 0.10.21.7
Common Capabilities 1.4.0-140
Integrated Dynamics 21fb09f

Steps to reproduce:
1. Place a reader (or something else that a cable connects to)
2. Place a cable on it
3. Remove the cable
4. Place the cable again

The cable now won't be visible (except for its hitbox) until you place another cable next to it, at which point both of them will appear. If you again break and replace it, it will again be invisible until another neighboring change.

![ezgif com-optimize 2](https://user-images.githubusercontent.com/16061266/32138569-b5cbb8c8-bc02-11e7-82a3-3d3b041d5617.gif)

**Comment by rubensworks** [comment]
I've been seeing some issues related to this as well.

This is probably a regression due to a recent (can't remember exact commit) change that reduced the number of chunk re-renders for parts, which was related to an issue where display panels would trigger a chunk re-render for each value change.

**Comment by rubensworks** [comment]
Note to self: also can occur when placing an Energy Battery next to a cable.

Possibly a model caching issue.
