### ISSUE TITLE
[1.12.2(0.9.3)]Total Fluid Amount bug

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#328]
![total fluid amount bug](https://user-images.githubusercontent.com/23412916/32141832-77998a58-bcc5-11e7-9d43-724e9f21230c.gif)
It's 2 "Total Fluid Amount item" in fluid reader GUI list.
And it not "Amount", is "Capacity".
And fluid reader not fit for TE Tank(can't find linked multiple tank)

**Comment by rubensworks** [comment]
It looks like two fluid aspect names were conflicting, will fix.

**Comment by Flithor** [comment]
First "Total Fluid Amount" display in fluid reader is amount, but in screen display "Total Fluid Capacity"

**Comment by rubensworks** [comment]
Yes, their internal name is the same, which causes these issues. It's already fixed here locally, will push soon.

**Comment by Flithor** [comment]
Fluid reader can't recognize linked multiple TE tank will fix in next version?

**Comment by rubensworks** [comment]
This seems to work just fine in your GIF. Or are you demonstrating another tank?

**Comment by Flithor** [comment]
I create a new issue
