### ISSUE TITLE
[1.12.2(0.9.3)]Fluid reader can't recognize linked multiple TE tank

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#329]
![cant rec](https://user-images.githubusercontent.com/23412916/32142016-a213a328-bcc9-11e7-9a99-c1ac910fb66d.gif)
Screen displayed the Tanks(tank amount).

**Comment by rubensworks** [comment]
This is not a bug. The reader will simply read the tanks in front of it, which is in this case only one. If a mod has several tanks in _the same block_, then your display will show a number higher than 1.
