### ISSUE TITLE
Huge FPS drop when using variables.

### ISSUE THREAD

**Issue by Amperthorpe** [CyclopsMC/IntegratedDynamics#33]
I go from a solid 60 FPS to around 20 when I put my variable card in a display screen. I got 3 RF stored cards, used sub on 2, then used sum on that variable card with my other rf storage card. I put the result variable card in a display screen and the rest of the modules in storage, and it get a huge FPS drop for as long as the variable card is in the screen.

**Comment by rubensworks** [comment]
Do you experience the same FPS drops when inserting other variables in the displays?

**Comment by Amperthorpe** [comment]
Nope, I summed the slots of 2 chests and it works fine.

**Comment by Amperthorpe** [comment]
I also just did another multi level deep comparison and it's fine with that too.

**Comment by Amperthorpe** [comment]
Oh, I found another case for the lag. It's a very simple Ent reader giving the ent name right into a screen. It works, but as long as the card is in the screen I get 20 FPS.

**Comment by rubensworks** [comment]
You can try lowering the tick rate of the display, this will reduce the frequency at which the variable will be evaluated. You can change this rate by clicking on the icon on the top right on the display gui.
This _should_ increase tick rate.

In the next version, I will try to do some optimization to try reducing lag.

**Comment by rubensworks** [comment]
Fixed with the latest performance improvements.
