### ISSUE TITLE
[1.12.2(0.9.3)]Fluid reader can't recognize linked multiple TE tank

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#330]
Ok I misunderstand "Tanks" meaning
![mult](https://user-images.githubusercontent.com/23412916/32142103-c2c123b4-bccb-11e7-81db-a34580002de1.gif)
But it's really cant recognize linked multiple TE tank.

Or fluid reader just can read one block fluid tank????
Can not recognize multi-block structures?????

**Comment by rubensworks** [comment]
Not a bug. It looks like TE is simply _merging_ the two tanks as one. This is just the information that is provided by TE, which is just one big tank in this case.

**Comment by Flithor** [comment]
That's said, TE just "link" tank, not be a "multi-block structures" big tank?
