### ISSUE TITLE
NPE if a model .json is missing

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#331]
If a model .json is missing for an aspect (such as if you delete https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/resources/assets/integrateddynamics/models/aspect/read/integer/network/energy/max.json), Minecraft will crash with a NullPointerException when you try to look at it. We should handle this more gracefully, just showing the magenta-and-black "missing" checkerboard or something.

**Comment by rubensworks** [comment]
I actually force a crash during init when a model is missing. But due to some of the more recent Forge changes, these errors are being caught by Forge, so we'll have to find a way to work around that.
