### ISSUE TITLE
Bug with the equals operator and armor stands.

### ISSUE THREAD

**Issue by Zolithen** [CyclopsMC/IntegratedDynamics#338]
I have been making an automated squezeer with an armor stand, but one bug trolled me at the end. At the start, the automation has been good, except for the reset of an materialized (constant) variable to an empty variable with the entity type. The variable has the armor stand value, to send some redstone signal to some pistons moving it. I have remaked the network to make it good, but the bug trolled me. I have a variable that the value is an entity reader with and armor stand, and some others entity readers to read the position of the armor stand. The variable that indicates if is the same entity that is on a piston, is every time false except if there are no entity in any of the entity readers. I don´t now any other way to automate that squezeer with making some vanilla or integrated dynamics and without attracting an entity that is slipping away every time or making some stupid timing.

**Comment by rubensworks** [comment]
Please clarify the problem clear and concisely, it's hard to understand you.

**Comment by Zolithen** [comment]
The problem is that something is wrong with the equals operator and armor stands. Happened that a variable that equals to a equals operator is making something wrong because their two values (the values that needed to be equal to make the variable true) are the same but the variable is false. This thing only passed me with the armor stands entity.

**Comment by rubensworks** [comment]
Are you certain that the entity actually remains the same? Because if you for example respawn an entity, this will be a different entity. The equals operator will check the internal unique ID of the entity.

**Comment by Zolithen** [comment]
I don´t know that fact, but with the materialized variable, what happens to make the value disappear when one redstone writer in the network is working? Im playing on a modpack: FTB Horizons III

**Comment by rubensworks** [comment]
I don't understand your question.

**Comment by Zolithen** [comment]
The variables that is from a materializer is supposed to be constants, but why one constant can be changed to a null entity value?

**Comment by rubensworks** [comment]
In the case of materializing entity values, this will store the internal ID of an entity.
However, when the entity with that ID is removed from the world (by killing or dying), the materialized variable will still contain a reference to that entity, but there will be no way of showing what entity it was.

It's clear that this is a confusing part, I'll see if I can clarify this in the mod.
