### ISSUE TITLE
[DEV] Localization does not work when dev-built

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#339]
When building an ID jar locally, localizations don't work when running the mod elsewhere in a dev environment.

**Comment by rubensworks** [comment]
Ok, the problem seems to be caused by language file names being mixed case. It looks like Forge doesn't handle this consistently.

In any case, it's probably a good idea to make all language file names (in all CC mods) completely lowercase.

**Comment by rubensworks** [comment]
Resolved in ef70d565ebbb02c1fa77c84be268c79e90d441e1

Also applied on all other CC mods.

**Comment by josephcsible** [comment]
If those are lowercase now, I think we need to add a pack.mcmeta too.

I added it to ID in CyclopsMC/IntegratedDynamics#424; can you add it everywhere else?
