### ISSUE TITLE
Crash when placing C&B bit in a cable block.

### ISSUE THREAD

**Issue by Amperthorpe** [CyclopsMC/IntegratedDynamics#34]
http://pastebin.com/UuwER4dj

**Comment by rubensworks** [comment]
Please provide more information as to what caused this crash.
This looks like a C&B crash, so it might be best to post it on their issue tracker as well.

**Comment by Amperthorpe** [comment]
Sure, I'll put it over there. I just had a grass bit, I right clicked the ground in the block of a cable and it crashed.

**Comment by AlgorithmX2** [comment]
This is a C&B issue, you can close this issue.

**Comment by rubensworks** [comment]
@AlgorithmX2 Thanks!
