### ISSUE TITLE
Make the input of round and floor number

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedDynamics#341]
Just to make sure this is not a bug, but when I tried to do any math with a divided number, for instance, I wanted to modulate it, I tried rounding, I tried using a floor, to no avail the screen simply read a big red x,  is this supposed to work this way, or not.

**Comment by darkshadow543** [comment]
Could you make round or floor an number input, rather than a double, it might make a lot of peoples lives easier.  In case your wondering, I am working on a eclipse timer, which happens every 36 days.  so I was trying to turn a modulate a division output.

**Comment by rubensworks** [comment]
Please clarify what you are asking. 

> Make the input of round and floor number.

Is it this?

**Comment by darkshadow543** [comment]
yes, that is what I am asking, because when I divide something, it becomes a number variable.

**Comment by rubensworks** [comment]
Makes sense, I'll look into it.
