### ISSUE TITLE
Facade rendering issue

### ISSUE THREAD

**Issue by Amperthorpe** [CyclopsMC/IntegratedDynamics#35]
http://i.imgur.com/nn1rZPs.png
Texture has wrong rotation, and clouds render through it.

**Comment by rubensworks** [comment]
How did you achieve this? Is there something special about this (facaded) block? Or are you somehow standing inside that block?

**Comment by Amperthorpe** [comment]
Nothing special, just a stone facade. I just right clicked the cables, I'm standing in front of the blocks.

**Comment by rubensworks** [comment]
Can't reproduce in latest dev version, assume fixed with the latest rendering changes.
