### ISSUE TITLE
Z-fighting on variable cards

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#353]
Whenever you're looking around or moving while holding a variable card in your hand, its overlay will Z-fight with the underlying blank card.
![ezgif com-optimize 1](https://user-images.githubusercontent.com/16061266/32529341-04ba3c56-c406-11e7-8c4c-01b9a742fa8e.gif)

Versions:
Minecraft 1.12.2
Forge 14.23.0.2531 (I also tried with 14.23.0.2497 thinking that MinecraftForge/MinecraftForge#4332 or MinecraftForge/MinecraftForge#4448 may have introduced, but it happened there too)
CyclopsCore 0.10.22
CommonCapabilities 1.4.0
IntegratedDynamics 0.9.4

**Comment by rubensworks** [comment]
Yes, it has been like that for a long time.

Overlaying should be tweaked, possibly similar as to how the Forge bucket handles overlay textures: https://github.com/MinecraftForge/MinecraftForge/commit/b5e88dd07b4aa7a719c5c44a89aa735b6ca891ce
