### ISSUE TITLE
Part spontaneously becomes logic cable

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#354]
When you place a reader in one block (with no cable), then try to place another reader facing the opposite direction in the block behind the first reader, the second reader will disappear, and a logic cable will appear in the first reader's block.

![ezgif com-optimize 2](https://user-images.githubusercontent.com/16061266/32582433-d0f30d00-c4bc-11e7-94b7-ec7b417960d6.gif)

Versions:
Minecraft 1.12.2
Forge 14.23.0.2532
CyclopsCore 0.10.22
CommonCapabilities 1.4.0
IntegratedDynamics 0.9.4

**Comment by rubensworks** [comment]
May be related to #93 and its fix.
