### ISSUE TITLE
entity reader changes

### ISSUE THREAD

**Issue by LeChuckXIV** [CyclopsMC/IntegratedDynamics#358]
not sure if this is intended, but with the new entity system it has broken systems that rely on item/entity name, for example i had a system that would read the entity name sand and emit a redstone signal if it was there, now this is impossible as the entity id constantly changes, if this is not a bug, how would i go about getting the entity's name?

**Comment by rubensworks** [comment]
Hmm, I didn't take this case into account when making the entity name change. I'll make sure to add something in the next update that will make it possible to fix your system.

In the meantime you should be able to work with the NBT operators.

**Comment by rubensworks** [comment]
Note to self: related to this, player names are always "null (...)"
