### ISSUE TITLE
Can't Create/Loads World -- Netty Local Client

### ISSUE THREAD

**Issue by Haddadmj** [CyclopsMC/IntegratedDynamics#364]
#### Issue type:

- :bug: Bug
- :snail: Performance issue
- :question: Question

____
#### Short description:

when i add the mod to my modpack with it required mods...

i can't create world

#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedDynamics-1.12.2-0.9.5
- CyclopsCore: CyclopsCore-1.12.2-0.10.22
- Minecraft: Minecraft 1.12.2
- Forge: forge-14.23.0.2538
-CommonCapabilities: CommonCapabilities-1.12-1.4.0

#### Log file:
https://pastebin.com/7kHcbJYv

**Comment by josephcsible** [comment]
Minecraft Forge 2538 made some changes to Netty that were followed up in 2539 and 2540. See if you have the problem with Forge 2537 (before the change) and/or with 2540 (after the follow-ups).

**Comment by rubensworks** [comment]
@Haddadmj Can you try reproducing with only this mod (and its requirements) installed?

It looks like IC2 is the only mod that is mentioned in the stacktraces, perhaps you should report it there.

**Comment by Haddadmj** [comment]
I Will Try :D

**Comment by Haddadmj** [comment]
with only this mod (and its requirements) installed
forge-14.23.0.2538 to forge-14.23.0.2540 ... I can't create/load the world...

but forge-14.23.0.2537
it work fine :D

**Comment by josephcsible** [comment]
I suspect that reverting https://github.com/CyclopsMC/CyclopsCore/commit/6131a3f95d1c3197dbcba79a579d3a8725a8bb10 will fix this. The leak that you thought was your fault was apparently Forge's fault.

EDIT: Tested and confirmed. CyclopsMC/CyclopsCore#94
