### ISSUE TITLE
Crash and world corruption upon use of looping variables.

### ISSUE THREAD

**Issue by Nagshell** [CyclopsMC/IntegratedDynamics#369]
#### Issue type:

- :bug: Bug

#### Short description:

Crash and world corruption upon use of looping variable.

#### Expected behaviour:
 
I'm not sure, the actual method doesn't look intended.

#### Steps to reproduce the problem:

1. Make two int variables with value 1 (variables A and B)
2. Make third variable with their sum (variable C = A+B)
3. Input sum of B and C into logic programmer, put variable A in slot of output and take it out.
- Situation now should look like: A = B+C ; B = 1 ; C = A+B
4. Copy variable C onto fourth variable.
5. Put A,B and C into variable store, 
6. Put copy of C into display to start calculation

Done. Instance crashes, and crashes instantly on each reload

____
#### Versions:

- integrateddynamics 0.9.5 
- integrateddynamicscompat 1.0.0                
- integratedtunnels  1.3.5

- CyclopsCore:  0.10.22
- Minecraft: 1.12.2
- Forge:  14.23.0.2532

#### Log file:

https://pastebin.com/1PYFZTFs

**Comment by rubensworks** [comment]
Thanks for reporting this.

A safeguard should already be in place against such recursion, but it looks like it misses this case.
