### ISSUE TITLE
[1.9] Crash placing Inventory Writer against an Advanced Generators Item Input port

### ISSUE THREAD

**Issue by b0bst3r** [CyclopsMC/IntegratedDynamics#37]
http://pastebin.com/BcLTJ6Yr

Quite why it's throwing up a malisis's error I dunno.

**Comment by rubensworks** [comment]
This has been fixed at malisis' side: Ordinastie/MalisisCore@a5892d21fa950c5ce472dde7ae7feeb651c4535d
