### ISSUE TITLE
Unable to place logic cables under Water

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedDynamics#373]
#### Issue type:

- :bug: 
- :heavy_plus_sign: 
- :question: 

____
#### Steps to reproduce the problem:

1. Try and place logic cable underwater

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2.0.9.6
- CyclopsCore: 1.12.2.0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

**Comment by rubensworks** [comment]
Sounds like a bug indeed, thanks for reporting.
