### ISSUE TITLE
When a proxy value changes, variables more than one step removed from it don't update

### ISSUE THREAD

**Issue by rakslice** [CyclopsMC/IntegratedDynamics#374]
#### Issue type:

- :bug: Bug

____
#### Short description:

When the value of a proxy changes, variables that are functions of the proxy more than one step removed don't update

#### Expected behaviour:

All variables with functions that depend on the proxy value either directly or indirectly update automatically when the proxy value changes.

#### Actual behaviour:

Variables with functions that depend indirectly on the proxy value  (e.g. they are the result of a function of a function of the proxy value) continue to act as if they have their previous calculated values when the proxy value changes, until you manually remove & replace any of the variable cards those functions depend on in the variable store

#### Steps to reproduce the problem:

1. In the logic programmer, create variables with integer constants 1, 2, 5, and 7
2. Set up a network with a Proxy, a Variable Store, and a Display Panel.
3. Put the constant 2 in the proxy
4. Put a blank variable card through the Proxy to get a proxy result variable
5. In the logic programmer, create a variable that is the Addition of the proxy result and the 7 constant
6. In the logic programmer, create a variable that is the Multiplication of that Addition and the 1 constant
6. Put the proxy result, the 7 constant, the Addition and the 1 constant in the Variable Store
7. Put the Multiplication in the Display Panel. It will show 9.
8. Take the constant 2 out of the Proxy and put in the constant 5. The Display Panel still shows 9.

____
#### Versions:

This mod: 1.12.2-0.9.5
CyclopsCore: 1.12.2-0.10.22
Minecraft: 1.12.2
Forge: 14.23.0.2547

**Comment by rubensworks** [comment]
Thanks! Will look into it.

**Comment by rakslice** [comment]
Tested fixed in 1.12.2-0.9.9. Cheers.
