### ISSUE TITLE
Variable transfer rate with network-attached Energy Battery

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#376]
#### Issue type:

- :bug: Bug

It appears that the Energy Battery has poor and variable transfer rates.

![2017-11-16_15 00 16](https://user-images.githubusercontent.com/392047/32920987-84ab03f6-cae0-11e7-8964-10a67c9a3dd4.png)

In this annotated screenshot, we have several numbered power transfer testing harnesses. All applicable connectors are set to transfer 10MRF/t. Power storage are creative types except where they are acting as a buffer (as in 1 and 8). "Works as expected", below, means that the power transfer rates are at the full capacity of the system.

1. Works as expected.
2. **No power transfer**. Appears to require a buffer. Based on how item tunnels work, I would expect to not require a buffer. (I realize that this is specific to Integrated Tunnels as it doesn't involve an Energy Battery.)
3. Works as expected.
4. Works as expected.
5. **No power transfer**. The energy interface seems unwilling to push/pull on conductors. Not sure if this is working as intended. (Also an Integrated Tunnels thing.)
6. **1.0kRF/t**.
7. Works as expected. (I had neglected to update the transfer rate in the exporter before taking the screenshot so it shows the default rate of 1.0kRF/t. After fixing it, it transfers at system capacity.)
8. **2.0kRF/t**. Adding an energy interface to the connection attached the energy battery bumps this up to **4.0kRF/t**. Adding a redstone signal has no effect. The buffer had been upgraded to 12.8MRF capacity.
9. Works as expected.
10. Works as expected.

____
#### Versions:

- Integrated Dynamics: 1.12-0.9.4
- Integrated Tunnels: 1.12-1.3.4
- CyclopsCore: 1.12.2-0.10.22
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

**Comment by josephcsible** [comment]
This mod isn't designed to transfer directly from importers to exporters. It's designed to transfer from importers to interfaces, and from interfaces to exporters. (An energy battery hooked directly to the network counts as an interface.) That seems to explain a good bit of what you're seeing.

Also, this should be classed as a bug, not a performance issue. A performance issue refers to the game lagging or running slowly.

**Comment by ouroborus** [comment]
Issue type updated.

I guess that just leaves 8 and possibly 5 as issues.

**Comment by rubensworks** [comment]
@ouroborus Could you double-check the transfer rates for 8?

Because if no buffer is attached to the network using an energy interface (or a direct battery), that setup should not be able to transfer energy at all. With that buffer the transfer rate should be 1kRF/t.

**Comment by ouroborus** [comment]
2k without energy interface:
![2017-11-16_16 24 45](https://user-images.githubusercontent.com/392047/32923169-efbdf6e4-caea-11e7-8dca-2607d96e3a94.png)

4k with energy interface:
![2017-11-16_16 24 59](https://user-images.githubusercontent.com/392047/32923172-f6a769f4-caea-11e7-9223-f5e6d8b6279d.png)

I would've expected 8 to run at max capacity, at least when using the energy interface. Scenario 1 is the same setup with a different device acting as a buffer and it runs at capacity.

**Comment by rubensworks** [comment]
Ah, like that you mean.

Both cases should run at 1kRF/t because that is the (configurable) transfer limit of the battery, so that indeed sounds like something that should be looked into.

Note to self: the battery may somehow get registered to the network multiple times using an energy interface.

**Comment by rubensworks** [comment]
I can't seem to reproduce the issue. Everything I try results in a transfer rate of 1kRF/t.

Note that I tried this with a RF/t calculator using the ID delayer, so perhaps DE calculates this in a different way.

The low transfer rates will be taken care of in #377.
