### ISSUE TITLE
Increase transfer limt of energy battery

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#377]
#### Issue type:

- :heavy_plus_sign: Feature request

The energy battery is upgradable but this only changes its capacity. Its fixed transfer limit of 1kRF/t renders upgrades increasingly pointless as more are applied.

I propose having the transfer limit increase with capacity, possibly as a separate NBT value or as a certain fraction of the capacity.

**Comment by rubensworks** [comment]
Makes sense, will think about a good way of implementing this.

Note to self: also increase default limit of network energy transfer.
