### ISSUE TITLE
Inconvenient to set multiple properties on the same aspect

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#379]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

When you're setting multiple properties on an aspect, after each one, you need to press Write, then scroll back down to the aspect and reopen the properties view. Instead, you should be able to set them all at once and only have to press Write once.

**Comment by rubensworks** [comment]
Agreed, I've noticed this myself as well lately. Perhaps the Write button could even be removed, and an auto-save could be added when you exit the (properties) gui.

**Comment by rubensworks** [comment]
Some suggestions by @ZeekDaGeek:

#### Suggested ways to fix some of the clunkyness:

* When you hit write or "<<" it should save what you've searched so when you go back the search is maintained.
* There are two ways to fix the write button:
  * When you tab through the settings on each property are maintained, at the moment when you switch properties the property you're switching away from will be set back to the saved one. If the write button is going to take you back to the property list then it would be nice if it allowed you to save all of them at once.
  * The write button could be disabled by default until the option has been changed and then when you hit with a valid value it saves and goes back to disabled. Pressing write doesn't bring you back to the aspect list, it just writes the changed property. Pressing "<<" would be the way to get back to the aspect list then.
  * When it comes to the options it comes down to developer preference, I personally like the second option more, but either one would be smoother then the current system when it comes to things like Integrated Tunnels where you're changing a lot more properties, especially with a player simulator. A combination of both could be even better.
