### ISSUE TITLE
Add the K combinator

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#381]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

We should add the K combinator from lambda calculus (K = λxy.x).

**Comment by rubensworks** [comment]
@josephcsible Small note: Make sure to add a clear description for this operator though, either in the tooltip or the book. Because most people probably won't be able to understand this with just the lambda form.

**Comment by josephcsible** [comment]
I don't think I'm going to do this until #352 or #387 are fixed.

**Comment by DasBrain** [comment]
K = apply if true

Could help, maybe you need some casts...

**Comment by josephcsible** [comment]
The second and third arguments to "if" have to be the same type, though. (Although this is something I've wanted to change.)

**Comment by DasBrain** [comment]
Yeah, add some casts or "useless" calculations to get the desired type.
