### ISSUE TITLE
Shift+clicking variables into the argument slots in the logic programmer destroys them

### ISSUE THREAD

**Issue by moonheart08** [CyclopsMC/IntegratedDynamics#382]
#### Issue type:

- :bug: Bug

____
#### Short description:
Shift+clicking variables into the argument slots destroy them.

#### Expected behaviour:
Variables shift clicked into the argument slots should be removable

#### Actual behaviour:
They get deleted

#### Steps to reproduce the problem:

1. try and shift+click a variable into the arg slot (first it goes into the result slot, shift click it again)
2. try and remove it
3. cry that a 50+ variable network just got ruined

____
#### Versions:

- This mod: 0.9.6
- CyclopsCore: 0.10.23 
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

#### Log file:

No crash. I reviewed the log file for about 10 minutes trying to find errors from the mod or related to the deletion. Found none. Wont post unless requested.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by moonheart08** [comment]
Why wouldn't I? I just lost a moderately large project to deleting one of the most commonly used variables thanks to it :P ( ): )
