### ISSUE TITLE
Growing Menril Saplings with .grow call crashes

### ISSUE THREAD

**Issue by HellFirePvP** [CyclopsMC/IntegratedDynamics#390]
Cross-post from AS' IssueTracker: https://github.com/HellFirePvP/AstralSorcery/issues/364

#### Issue type:

- Bug

____
#### Short description:

Calling .grow() on a Menril sapling-block crashes the game.

#### Expected behaviour:

That it should cycle the growth-state or otherwise show some growth progress.

#### Actual behaviour:

Go figure.

#### Steps to reproduce the problem:

Since this has happened in conjunction with AS' Tree-Beacon, however it seemingly not being connected to it directly:

1. Place down a TreeBeacon of AS
2. Grow it with bonemeal or wait for it to grow
3. RIP.

As additional information: The TreeBeacon listens to the tree-growth and once the event is fired in a its range, it'll cancel the event and attempt to have the tree re-grow to capture the resulting blocks beforehand as that is required for the mechanic of the treebeacon to function properly. However, canceling the growth event shouldn't be connected to the sapling now being in a corrupt state, nor should calling .grow on it repetitively cause anything either as you can achieve the same effect with bonemeal or wateringcans or w/e.

So. have at it.

____
#### Versions:

- This mod: 0.9.5
- CyclopsCore: 0.10.22
- Minecraft: 1.12.2
- Forge: 14.23.0.2532

#### Log file:

https://gist.github.com/HellFirePvP/c63e3a7c1e485c587eb697632459ca78

**Comment by rubensworks** [comment]
Thanks! Will look into it. It indeed looks like I'm not properly overriding the `grow()` method.

**Comment by josephcsible** [comment]
When I try to reproduce this, I don't get a crash; instead, the server thread seems to freeze.

**Comment by josephcsible** [comment]
Okay, so CyclopsMC/CyclopsCore#97 fixes our bug, but this wouldn't have happened except for two Astral Sorcery bugs: see HellFirePvP/AstralSorcery#379 and HellFirePvP/AstralSorcery#380 for their fixes.

**Comment by rubensworks** [comment]
Great, thanks for looking into this @josephcsible!
