### ISSUE TITLE
Getting/Writing the Step Sound of Air causes a crash.

### ISSUE THREAD

**Issue by ConnorMiner** [CyclopsMC/IntegratedDynamics#392]
#### Issue type:

- :bug: Bug

____
#### Short description:
Upon setting an Audio Writer to play the step sound of a block that a Block Reader detected (which was air), the server crashed.

#### Expected behaviour:
A stone stepsound, an invalid stepsound that causes nothing to play, or no sound at all from the Audio Writer (supposedly) playing Air's stepsound.

#### Actual behaviour:
The server crashes instantaneously.

#### Steps to reproduce the problem:

1. Place Block Reader on network with only Air in front of it.
2. Create a variable to get the stepsound of the block the Block Reader sees.
3. Put the Variable card for the Block Reader's detected block in a Variable Store.
4. Put the stepsound Variable Card into an Audio Writer on the same network.
5. ~~Profit!~~ Crash!

____
#### Versions:

- This mod: 0.9.6
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

#### Log file:

https://drive.google.com/file/d/1QI3kGSS8N_T_Avm3NcC4q3LhP3e3FnTQ/view

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by ConnorMiner** [comment]
I just found out that the crash occurs with any block in front of the block reader when the stepsound is supposed to be determined.
