### ISSUE TITLE
Code never runs

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#393]
https://github.com/CyclopsMC/IntegratedDynamics/blob/01219b22e199834b677766f1b3e866bc42d03456/src/main/java/org/cyclops/integrateddynamics/core/evaluate/variable/ValueTypeListProxyEntityBase.java#L34-L44

This code never runs. This is an abstract class, and both of its concrete subclasses override these methods without calling super.

**Comment by rubensworks** [comment]
Haven't seen any bug reports related to this yet. But looks like something that needs fixing in any case.
