### ISSUE TITLE
uniq and uniq_p don't work as intended

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#397]
https://github.com/CyclopsMC/IntegratedDynamics/blob/f025d16240d2b715abe7a1ab4084f6b5bae697f9/src/main/java/org/cyclops/integrateddynamics/core/evaluate/operator/Operators.java#L748-L756
https://github.com/CyclopsMC/IntegratedDynamics/blob/f025d16240d2b715abe7a1ab4084f6b5bae697f9/src/main/java/org/cyclops/integrateddynamics/core/evaluate/operator/Operators.java#L772-L774

~~Two~~Three problems are apparent with the above code:
1. If two objects have the same hash code, they'll be treated as equal whether or not they actually are.
2. It's possible that two objects that the predicate considers equal will have different hash codes. This means that even discounting problem 1, this isn't a total order, so the set may misbehave.
3. The order of elements isn't preserved.

**Comment by rubensworks** [comment]
Not sure where my mind was when I wrote that...
