### ISSUE TITLE
Support reading items, fluids and energy from entities

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#403]
#### Issue type:

- :heavy_plus_sign: Feature request

Operators should be added for this, based on capabilities.

**Comment by josephcsible** [comment]
For items, what functionality do we want besides what the "inventory" and "armorinventory" operators already give us?

**Comment by rubensworks** [comment]
I think "inventory" and "armorinventory" only work on players at the moment, operators should be added that work purely using capabilities, so it works on all entities.

**Comment by josephcsible** [comment]
Ah yes, that is indeed the case.
