### ISSUE TITLE
Crash during List creation

### ISSUE THREAD

**Issue by matthiasmetzen** [CyclopsMC/IntegratedDynamics#404]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
The game crashes when I click the "+"-Button while trying to create a list of fluids in the (Portable) Logic Programmer.
If I press one of the arrows to cycle between the list types first, and then cycle back  to fluids it works just as intended. Before using this workaround, the GUI will also not show the red X or the green checkmark that indicates weather the list is valid.

#### Expected behaviour:
Update the GUI to let me add a new fluid.

#### Actual behaviour:
Game crashes.

#### Steps to reproduce the problem:

1. Open the Logic Programmer
2. Go to "list"
3. Click on the "+" before clicking on any of the arrows 

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedDynamics-1.12.2-0.9.6
- CyclopsCore: CyclopsCore-1.12.2-0.10.32
- Minecraft: 1.12.2
- Forge: forge-14.23.0.2531

#### Log file:

https://pastebin.com/bXBC6HuZ

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Gayanfalor** [comment]
Yep got the qame issue playing atm 3 v5.3, the fun fact is if you move arrows and get back to fluid and hit the  + its working
