### ISSUE TITLE
Fluid reader is misleadingly named

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#405]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
- :heavy_plus_sign: Feature request

The fluid reader sounds like it can read fluids directly from the world, but it can't do this (it can only read from tanks). We should either let it do this, or rename it to "tank reader" or "fluid tank reader" or something.

**Comment by rubensworks** [comment]
I would keep the name as it is, but perhaps we can add an aspect that can read a fluid (block) from the world as a fluid value.
