### ISSUE TITLE
Mod integration with something like Dimensional Transceiver or tesseract [solved]

### ISSUE THREAD

**Issue by masonpinder** [CyclopsMC/IntegratedDynamics#417]
#### Issue type: :heavy_plus_sign: Feature request

Would it be possible to make the system connect through wireless, so that I can control different circuits far apart, or different dimensions?

I don't know the code and whether it's possible to even work between different dimensions, with what you've got, but would it be too impossible, so I could do something like applied energistics and quantum tangled networks?
I'd also really love if it could work with something like integrated dynamics, and go through to the other dimension in it.

Thank you for your time and consideration!

**Comment by josephcsible** [comment]
Do the mono- and omni-directional connectors not work for your use case?

**Comment by masonpinder** [comment]
Wait, do mono- and omni-directional connectors work through dimensions?! I feel dumb to not have tried it
