### ISSUE TITLE
Write Button occasionally not working

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#42]
After an extended period of playtime all instances of the write button fail to perform any form function. Reloading Minecraft completely appears to fix this.

**Comment by rubensworks** [comment]
Do you see any errors in the console when this happens?

**Comment by squirrelkiller** [comment]
I do not see any errors in the console. No.

**Comment by rubensworks** [comment]
I'm unable to reproduce this in MC 1.9.4. It's very likely that it may have been related to an MC bug which is fixed by now.
