### ISSUE TITLE
Make cable connections side aware

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#420]
Certain mods, such as Compact Machines require cable and path element capability retrieval to be sided.
So some internal (backwards-compatible) refactoring is required to make this work.

Note that some NBT serialization changes to networks will be required, due to only positions of path elements being stored, and not the side they are connected by.

More information: #419

**Comment by rubensworks** [comment]
@thraaawn I just did some changes to make all ID network handling sided. Do you have deobfuscated (dev) builds available for Compact Machines that would allow me to test this a bit in a dev environment?

**Comment by davenonymous** [comment]
Not automatically, no, sorry.
Have this: 
[compactmachines3-1.12.2-3.0.5-deobf.jar.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/1649952/compactmachines3-1.12.2-3.0.5-deobf.jar.zip)

Edit: I needed to zip that for github to accept the file upload.

**Comment by rubensworks** [comment]
Thanks, seems to work great!
