### ISSUE TITLE
Server crash 1.12.2

### ISSUE THREAD

**Issue by unstablecraft** [CyclopsMC/IntegratedDynamics#421]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

server crashes after player pickaxe's an display pannel from your variable store

#### Expected behaviour:
that server does not crash

#### Actual behaviour:
server go's belly up

#### Steps to reproduce the problem:

1. place store
2. put display panel on it
3. wack it with pick axe
4. crashes server after 4 tries

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod:  IntegratedDynamics-1.12.2-0.9.6.jar
- IntegratedTunnels-1.12.2-1.3.5.jar
- CyclopsCore:  CyclopsCore-1.12.2-0.10.23.jar
- Minecraft: 1.12.2
- Forge: 2531

#### Log file: https://pastebin.com/MnPxz1bG

_Don't paste contents here directly, but use something like http://pastebin.com/_

**Comment by rubensworks** [comment]
> 2. put display panel on it

Is this with or without a cable?

**Comment by unstablecraft** [comment]
without
 also insta crash  with D evolution exacher
same crashlog

**Comment by rubensworks** [comment]
> also insta crash with D evolution exacher

Please clarify

**Comment by unstablecraft** [comment]
if display is broken  with Draconic Evolution exachanger results in same crash as above
but then it happens instand and not after a few tries

**Comment by rubensworks** [comment]
Will be fixed in the next version. If this is not the case, please let me know.

**Comment by unstablecraft** [comment]
will do
