### ISSUE TITLE
Crystalized Menril (Brick) Stairs are listed as fuel.

### ISSUE THREAD

**Issue by KingLemming** [CyclopsMC/IntegratedDynamics#426]
Just a simple thing I noticed - the Crystalized Menril Stairs (regular and brick versions) have a fuel value, as if they were wood.

That feels like a mistake to me, but it may be intended. Apologies if it is.

**Comment by rubensworks** [comment]
That seems to be a mistake indeed, thanks for reporting!

**Comment by josephcsible** [comment]
Noting that this happens with both variants of chorus stairs too.
