### ISSUE TITLE
Group ID of omni-directional connector not synced to client

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#429]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
When crafting an omni-directional connector, its group ID isn't immediately synced to the client.

#### Expected behaviour:
A newly-crafted omni-directional connector should immediately have its group ID visible.

#### Actual behaviour:
A newly-crafted omni-directional connector does not have its group ID visible until you force the server to tell the client about the item again, such as by moving it around.

#### Steps to reproduce the problem:

1. Craft (or reset) an omni-directional connector, and place it in your inventory
2. Mouse over it, and note the lack of a group ID
3. Move it to a different slot in your inventory
4. Note that its group ID is now visible

____
#### Versions:

Git revision c5ed8ac, with all of the dependencies pulled by gradle for it

#### Log file:

Nothing relevant

**Comment by josephcsible** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/blob/edef106c1bfc26d0dc775144ffefee150aff87a0/src/main/java/org/cyclops/integrateddynamics/part/PartTypeConnectorOmniDirectional.java#L171

This is the cause. Is there a reason for only doing this on the server?

**Comment by rubensworks** [comment]
@josephcsible Because only the server knows of these IDs, and stores them.

Not sure if this issue can be easily resolved though, due to how crafting works in 1.12 (completely server-side).

**Comment by josephcsible** [comment]
https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/src/main/java/org/cyclops/cyclopscore/persist/world/GlobalCounters.java#L10 seems to indicate otherwise.

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>CyclopsCore - Minecraft coremod for EvilCraft, Integrated Dynamics and others.</div></blockquote>

**Comment by rubensworks** [comment]
Not sure if that description is accurate, I don't remember ever implementing server-client syncing, and I also don't think vanilla does this out-of-the-box for WorldStorage.

**Comment by Fatmice** [comment]
This remains a problem in 1.12.2-0.11.17

**Comment by rubensworks** [comment]
Won't fix.
