### ISSUE TITLE
Doesnt Run On new Forge :(

### ISSUE THREAD

**Issue by AOWGaming** [CyclopsMC/IntegratedDynamics#435]
Kicks you off the server when loading in

#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
- :heavy_plus_sign: Feature request
- :snail: Performance issue
- :question: Question

~~DELETE THIS LINE AFTER READING: If this is not a bug report, you can remove the remainder of this template.~~

____
#### Steps to reproduce the problem:

1. ...

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 
- CyclopsCore: 
- Minecraft: 
- Forge: 

#### Log file:

_Don't paste contents here directly, but use something like http://pastebin.com/_

**Comment by josephcsible** [comment]
Please fill out the template properly; there's not enough information here to start trying to fix this. (I can load worlds fine on the latest version of Forge.)
