### ISSUE TITLE
Creeper Taming Challenge - Success not registering

### ISSUE THREAD

**Issue by Banedon** [CyclopsMC/IntegratedDynamics#437]
Issue type: Bug/Question

#### Steps to reproduce the problem:
1.  Create an entity variable card from an entity reader.
2.  Using the Logic Programmer, created a "Health" card using the entity card as a reference.
3.  Put the entity card in the variable store, and the health card in the display panel.
4.  Set up the entity reader in a hole and trap a creeper in the hole.
5.  Display panel displays 20.0 for the health of the creeper, but no achievement is triggered.
____
#### Versions:

- This mod: 0.7.4
- CyclopsCore: 1.9.4-0.10.10
- Minecraft: 10.2
- Forge: 12.18.3.2511

Age of Engineering modpack version 1.1.2 through Twitch/Curse Client.

**Comment by rubensworks** [comment]
Ah, this is 1.10.

I'm only doing major bugfixes for 1.10, as 1.12 is the main target now.
As this isn't crashing anything or is game breaking, I won't be fixing this.

**Comment by TomyLobo** [comment]
I thought this bug still existed on 1.12, but then I figured it out.

For anyone looking for this, here's a hint:
The game has to know that *you* completed the advancement, not just some random person.
It cannot trigger the advancement unless you're actively doing something.

**Comment by TomyLobo** [comment]
@rubensworks I don't know if you want (me) to disclose the solution here, so I kept it vague :).

**Comment by Ozzymud** [comment]
@TomyLobo I was able to "do something" to get this to display by using "target entity" health... while this displayed the target creepers health, this did not trigger it, was this not the path your hint suggested?

![2020-11-09_01 31 19](https://user-images.githubusercontent.com/6426344/98523883-52061300-222b-11eb-830f-b4274dd916fc.png)
