### ISSUE TITLE
Squeezer Tweaks

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#44]
As things stand the squeezer allows items to be pumped in and out, but I can see no way to automate the jumping on it. I would like to propose a new block that is placed beside an existing squeezer and allows its automation, simulating 1 jump per redstone pulse. You could instead use a coal or RF design, but those sound boring. I feel like an attachment block which automates the system based on redstone signals would be enough, it would allow players to automate the operation of the squeezer with Integrated Dynamics and Hoppers alone. Hoppers to move items in and out, integrated dynamics detecting when to give the reset pulse, and providing the clock signal when an item is in the squeezer.

Another tweak, can you do something about the corners? I always end up standing on those and can't jump on the actual plate I need to to operate the squeezer.

Final tweak, add operating instruction when shift is held while mousing over it. I am thinking "Squeezes blocks and items, jump on it."

**Comment by rubensworks** [comment]
1. You can automate it. I have already seen 4 different designs. Remember: Other entities may also jump/fall on it :-)
2. There are sticks in the model there, so it makes sense to have a bounding box there. Once you're centered on the block, you should be able to continue jumping just fine.
3. I already planned on doing this, I have to admit that it is not very clear how the squeezer has to be used atm.
