### ISSUE TITLE
Bug: Portable Logic Programmer overwrites last slot on toolbar when adding an item from JEI

### ISSUE THREAD

**Issue by Drakkim** [CyclopsMC/IntegratedDynamics#441]
~~DELETE THIS LINE AFTER READING: :tada: Thanks in advance for this issue, you're awesome! :tada: Please fill in the following template and make sure your title clear and concisely summarizes the issue.~~

#### Issue type: Bug

~~DELETE THIS LINE AFTER READING: If this is not a bug report, you can remove the remainder of this template.~~

____
#### Steps to reproduce the problem:

1. Open the Portable Logic Programmer (may work on non-portable version, haven't tested)
2. Choose List as a type
3. Pick item in the top
4. click the item box in the + button
5. click an item, any item in JEI, then click + to add it to the programmer list
6. Sometimes, the item shows up in the middle of the Logic Programmer UI AND replaces the last item in your toolbar. Once it happens once, it seems to happen every time.

Extra notes: picking fluid in step 3 crashes my client.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- Direwolf20 1.12.2 mod pack, version 1.3.0
- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 11.12.2 
- Forge: 14.23.1.2555

#### Log file:

Nothing useful in the logs...

**Comment by josephcsible** [comment]
If picking a fluid crashes your client, please upload a crash log of that.

**Comment by Drakkim** [comment]
[crash-2017-12-09_02.19.03-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1544465/crash-2017-12-09_02.19.03-client.txt)
