### ISSUE TITLE
Machine reader max capacity

### ISSUE THREAD

**Issue by FallenRecruit** [CyclopsMC/IntegratedDynamics#444]
#### Issue type: Bug
- :bug: Bug
____
#### Expected behaviour:
It is working as expected 

#### Possible addition: add second FE values as long
____
#### Versions:

- This mod: 0.9.6
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

**Comment by rubensworks** [comment]
This is normal, because the FE interface works with ints. What are you trying to read that should be having a capacity of more than the max int value?

**Comment by FallenRecruit** [comment]
Draconic Evolution energy core its max capacity is 64-bit long

**Comment by josephcsible** [comment]
RF is signed 32-bit, so only supports energy values up to 2,147,483,647. If Draconic Evolution lets you store more than that, it should be using TESLA, which is 64-bit. If you want this to be fixed, report it to their issue tracker.

**Comment by FallenRecruit** [comment]
Is it possible to read the stored and capacity as long with minimal code additions?

**Comment by rubensworks** [comment]
@FallenRecruit No, it is not. Simply because the stored and capacity values are exposed by the FE interface as ints. We can't magically make it expose more bytes. Another interface should be used for that, such as the Tesla interface (which we also support).

**Comment by josephcsible** [comment]
It might be possible to add a special case for this, but Draconic Evolution recently [changed from the free and open-source MIT license to the completely non-free (not much better than All Rights Reserved) CoFH DBaJ license](https://github.com/brandon3055/Draconic-Evolution/commit/3e293fc16e3a22e10f9fa7486ef791d9fed99a1e). As such, unless and until this is undone, I have no desire to even begin looking into it.
