### ISSUE TITLE
Items behave weirdly when being made into a list

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#446]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
When making a list of items in the logic programmer, the items you add behave weirdly, jump all around, appear, and disappear, seemingly at random.

![ezgif com-optimize 3](https://user-images.githubusercontent.com/16061266/33808143-5c61f8aa-ddaf-11e7-99a1-2315a4ed81ba.gif)

(Changing from 9 items to 7 and 3 items is just where the video loops. Everything else weird is the bug that I'm talking about.)

____
#### Versions:

Development version b0d601b with all of its dependencies from Gradle

#### Log file:

Nothing relevant

**Comment by rubensworks** [comment]
May be caused by 39cdb353e67b7f1a05898e1f5233f4af4f2922cc
