### ISSUE TITLE
Allow variables to referenced from non-variable stores

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#448]
https://github.com/CyclopsMC/IntegratedDynamics/commit/7bb04f5200dfddbe6b5041361cf5f6a9a7518b36 changes some things related to variable references in networks, which may make it possible for non-variable stores to act as variable store.

This might make it possible to for example place a variable in a display panel or writer, and allow other variables to operate on this variable without it having to be present in a variable store.

**Comment by josephcsible** [comment]
Duplicate of #348

**Comment by rubensworks** [comment]
I thought I remembered there was an issue like this open already, couldn't find it...
