### ISSUE TITLE
Crash when Integrated Dynamics is performing comparator operations on a transfer node

### ISSUE THREAD

**Issue by thejims** [CyclopsMC/IntegratedDynamics#450]
#### Issue type:
:bug:

#### Short description:
Crash when Integrated Dynamics is performing comparator operations on a transfer node

#### Expected behaviour:
Return comparator level of the transfer node, vanilla comparators return 0 regardless of items in the node.

#### Actual behaviour:
When attempting to read 'comparator' levels of a transfer node using Integrated Dynamics Redstone Reader, game crashes in SP/server crashes in MP.

#### Steps to reproduce the problem:
Place Extra Utilities 2 transfer node, place a Redstone Reader and cable, open Redstone Reader -> game crashes

#### Versions:
Modpack: ATM3 v5.2
IntegratedDynamics-1.12.2-0.9.6.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
CyclopsCore-1.12.2-0.10.23.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
Minecraft: 1.12.2
forge-1.12.2-14.23.1.2560.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |

#### Log file:
https://pastebin.com/8PEQEvCw

**Comment by thejims** [comment]
ExtraUtils2 bug/issue raised: https://github.com/rwtema/extrautilities/issues/1802

**Comment by josephcsible** [comment]
Looks like ExU's fault, as I explained there, but it will be easy to work around this if they refuse to fix it.

**Comment by rubensworks** [comment]
There is a `Block#hasComparatorInputOverride`, which we apparently don't check, while we should. This should resolve this issue.
