### ISSUE TITLE
Document new part settings

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#452]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

We should add documentation to the in-game manual describing what the channel and expose capabilities settings do.

**Comment by josephcsible** [comment]
I'll write this once #451 merges.

**Comment by rubensworks** [comment]
The new target side setting (52227dab6278e2775878e0e69190062cad9515bd) should also be mentioned.
