### ISSUE TITLE
Hovering over number field buttons doesn't work right

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#453]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
The mouse location that makes number field buttons glow purple when you hover isn't where the number field buttons actually are:

![snapshot62](https://user-images.githubusercontent.com/16061266/34084671-90025f8a-e352-11e7-99fb-9b22d95f2876.png)

![snapshot63](https://user-images.githubusercontent.com/16061266/34084673-919f402e-e352-11e7-81f6-2ab0f218fb5a.png)

____
#### Versions:

Development version 3fbd6fe with all of its dependencies from Gradle

#### Log file:

Nothing relevant

**Comment by rubensworks** [comment]
Same problem as 82896a5f33ee57e72dfef66922657d51e877237b, easy fix.
