### ISSUE TITLE
Extra-Dimensional Reader "Tick time"

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#463]
#### Issue type:
- :bug: Bug?
- :question: Question

____
#### Description:
What does the "Tick time" value in the Extra-Dimensional Reader actually show? Its description says "The average tick time in milliseconds for the server" which, to me, seems like it should be around 50. However, the number shown is ~18,000,000 ± 2,000,000.

![image](https://user-images.githubusercontent.com/392047/34319302-2a287b82-e793-11e7-88d7-735d8f62c327.png)

____
#### Versions:

- IntegratedDynamics: 1.12.2-0.9.8
- CyclopsCore: 1.12.2-0.10.24
- Minecraft: 1.12.2
- Forge: 14.23.1.2570

**Comment by rubensworks** [comment]
The description is wrong indeed, the unit is nanoseconds. This has actually been just fixed in the latest version.

**Comment by ouroborus** [comment]
@rubensworks One tick would be 50,000,000ns, about 2.5 times what I'm getting. What is it actually measuring? Is it the time taken to actually process a tick that's being measured (as opposed to the usual measurement of time between the beginning of one tick and the next)?

**Comment by rubensworks** [comment]
Yes, it's the actual time to process a single tick. So in your case, you have a lot of server processing power left until you reach that limit of 50ms per tick, after which you would encounter server lag.
