### ISSUE TITLE
Block reader breaks OpenComputers

### ISSUE THREAD

**Issue by prozacgod** [CyclopsMC/IntegratedDynamics#464]
#### Issue type:

- :bug: Bug
____
#### Short description:
Stick a reader on an OpenComputers chassis block, it stalls the computer/prevents it from working

#### Expected behaviour:
Would get back data on the computers block info nbt etc..  And NOT block the behavior of the target block.

#### Actual behaviour:
Strangely stalls out the actively running lua instance.  The computer will not power on, or work until you remove the actively accessed variable card.

#### Steps to reproduce the problem:

1. build a computer ( I built a tier 3 ) 
2. build a small ID network consisting of display panel, and block reader.
3. program a variable card via the block reader to read tile entity nbt
4. place it in the display panel.

The computer will cease all activity until you remove the card.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.9.6
- CyclopsCore:  1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2542

#### Log file:

No errors logged

**Comment by rubensworks** [comment]
Can you report this to the OC issue tracker as well? It sounds like they stop some processes when the tile is written to NBT (which shouldn't happen).

**Comment by rubensworks** [comment]
Closing this, as there's not much we can do on our end, this is for OC to fix.
