### ISSUE TITLE
Inventory Count Error

### ISSUE THREAD

**Issue by Adaaaaam** [CyclopsMC/IntegratedDynamics#467]
Can't display a variable that consists of a Inventory Count + Integer
E.g. Inventory of a chest with 10 blocks in + 10, comes up with an error

**Comment by josephcsible** [comment]
Please use [the issue template](https://raw.githubusercontent.com/CyclopsMC/IntegratedDynamics/master-1.12/.github/ISSUE_TEMPLATE.md). There's not enough information there to begin trying to fix this.

**Comment by Adaaaaam** [comment]
I'm sorry but that is all the information I have other that the Error read: This current variable can not be used in this aspect. This probably isn't enough to bug fix but i was told to come here with this bug :/

**Comment by josephcsible** [comment]
Can you explain the exact sequence of steps you followed? Also, what versions are you using?

**Comment by Adaaaaam** [comment]
#### Issue type:

- :bug: Bug

____
#### Short description:
Inventory count and a Integer do not add up at all it just comes with an error. 


#### Expected behaviour:
Inventory count = 5
Integer = 5
Inventory count + Integer = 10
#### Actual behaviour:
Error: This current variable can not be used in this aspect


#### Steps to reproduce the problem:

1. Inventory reader on a chest
2. Get variable for inventory count
3. Get a integer variable = to 5
4. Use the programmer thing to get a variable that adds them together
5. Put that variable into display block
6. Put both the integer and inventory reader variables in a variable store
7. Error in display block
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 
- CyclopsCore: 
- Minecraft: 1.10.2
- Forge: 12.18.3.2551

#### Log file:

**Comment by josephcsible** [comment]
It works fine for me when I try it. Can you upload a video of exactly what you're doing?
