### ISSUE TITLE
Squeezer inventory model distorted

### ISSUE THREAD

**Issue by LemmaEOF** [CyclopsMC/IntegratedDynamics#471]
#### Issue type: 🐛 

____
#### Short description:
Inventory model for squeezer is distorted.

#### Expected behaviour:
Squeezer in-inventory model has the standard size, shape, and placement of a typical block.

#### Actual behaviour:
![](https://cdn.discordapp.com/attachments/290916642232336394/397319324492365824/unknown.png)

#### Steps to reproduce the problem:
N/A

#### Versions:

- This mod: 0.10.0
- CyclopsCore: 0.11.0
- Minecraft: 1.12.2
- Forge: 14.23.1.2582

#### Log file:
N/A

**Comment by LemmaEOF** [comment]
Hm. I'm finding the exact same distortion with the tank from OpenBlocks and the seared tank from Tinkers, so it may be something with my modpack? *very* weird that it's only happening with these three blocks, and that they've all got tank-related stuff.

**Comment by LemmaEOF** [comment]
Ok, looking at source code, I have no idea what's going on, because none of the three affected blocks have any display code in their model JSON. It's probably something my side.

**Comment by rubensworks** [comment]
I've noticed this as well in the DW20 pack. There must be some (core?) mod in the pack that modifies these models for some reason. Nothing I can do from my end unfortunately...
