### ISSUE TITLE
[Minor Bug] Crash when removing blocks with fill/setblock

### ISSUE THREAD

**Issue by BloodWorkXGaming** [CyclopsMC/IntegratedDynamics#472]
#### Issue type: Minor Bug when changing the world with non standard methods
- :bug: Bug
____
#### Short description:
When having ID stuff in a area and then removing it with a /fill command causes the game to crash a few seconds afterwards.
____
#### Versions:
- This mod: 0.10.0
- CyclopsCore: 0.11.0 
- Minecraft: 1.12

#### Log file:
https://gist.github.com/BloodWorkXGaming/c59d6d38db41802341357270bb62f57c

**Comment by josephcsible** [comment]
Possibly a reoccurrence of #240
