### ISSUE TITLE
Dynamic light panel changes value of adjacent panels to true

### ISSUE THREAD

**Issue by Drakkett** [CyclopsMC/IntegratedDynamics#475]
- :bug: Bug

#### Short description:    
When one dynamic light panel changes to true or positive integer, all adjacent dynamic light panels change.

#### Expected behaviour:  
Each panel will display according to the variable it is linked to and not respond to adjacent panel.

#### Actual behaviour:
I created a "Status board" that is using adjacent dyanamic light panels to indicate status of variables within the system.    It seems to work if all variables are false but when one switches to true, all of the adjacent panels also light up.   When the variable returns to false, none of the panels turn off.  I have to take out the variable card of each one and replace it in order for them to reset.

#### Steps to reproduce the problem:

1. Make a simple system with 2 or more adjacent dynamic light panels
2. Insert "False" Boolean variables into each.
3. Change one of the variables to "True"

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.10.2-0.7.12
- CyclopsCore: 1.9.4-0.10.9
- Minecraft: 1.10.2
- Forge: 12.18.3.2477

**Comment by rubensworks** [comment]
Oh, that's strange.
So the display panels have to be adjacent for the issue to occur? Or can they be anywhere in the (same) network?

**Comment by Drakkett** [comment]
No, I just tested and it does the same thing if they are not adjacent.    In the screenshot below, all of them were set to false and I changed just the one with cursor on it to true.  All of them lit up. 
  
https://imgur.com/a/cJe1F

**Comment by rubensworks** [comment]
Alright, thanks for checking. Will look into it soon!
