### ISSUE TITLE
Server crash when importing from non existent inventory slot

### ISSUE THREAD

**Issue by JelleSteinmetz** [CyclopsMC/IntegratedDynamics#480]
#### Issue type: Game/Server crash

- :bug: Bug

____
#### Short description:
I placed an importer onto a [farmer](https://ftb.gamepedia.com/Farmer_(Actually_Additions)), and tried to import items from slot 12. Since Integrated dynamics starts counting at 0, this slot was out of bounds and the server crashed. 

#### Expected behaviour:
The network would ignore the slot or give an error message

#### Actual behaviour:
Server crash

#### Steps to reproduce the problem:
1. Place down anything with an inventory
2. Add an importer (an exporter will probably cause the same problem)
3. Add an Variable card (with a value that is equal or higher than the number of inventory slots) in the 'import item slot' aspect. (or set the item slot property to this value on any of the other aspects)
4. Game/server will crash, and the world will crash again on loading.

____
#### Versions:

- This mod: 
IntegratedDynamics-1.12.2-0.9.6
IntegratedTunnels-1.12.2-1.3.5
- CyclopsCore: 
1.12.2-0.10.23
- Minecraft: 
1.12.2
- Forge:
14.23.1.2555 

#### Log file:
Server crashlog: https://pastebin.com/7qsWB5nc

**Comment by rubensworks** [comment]
Please try with the latest version of ID, this should have been fixed.

**Comment by rubensworks** [comment]
Assuming fixed.
