### ISSUE TITLE
Setting to disable network ticking and value sending/displaying

### ISSUE THREAD

**Issue by mrlamb** [CyclopsMC/IntegratedDynamics#486]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request
- :snail: Performance issue
- :question: Question

So I done messed up. I was attempting to set up a type of tunnels/logic system to automatically analyze forestry trees and I overloaded a display panel. 

Step 1: put way too many forestry saplings with all their juicy nbt data into an actually additions medium storage crate.
Step 2: Attach an inventory reader and get an item list aspect
Step 3: Put item list into display panel and instantly get kicked out with the dreaded "Payload may not be greater then 32k bytes" message.

Soooo, suggestions on what I can do to recover this world? World edit is an obvious choice, removing the panel should fix it, but it's on a server and with my crappy internet downloading it all to remove the block would take awhile.

I tried editing the config on the server, setting the power multiplier to 100, thinking without a battery hooked up it would instantly shut off, but after restarting the server I still get kicked.

Lastly: the feature request. Perhaps some kind of config setting that disables the mods workings/payload sending while keeping the mod in play. Would allow you to turn config on, remove the offending items then turn it back off instead of say, removing the mod completely, breaking every system you've built and then loading the mod back in, probably with different block id's and ruin your world. Just spitballing on this last part, but it seems like it could be useful. Accidental overflows can't only happen to me right?

:sheepishgrin:

**Comment by rubensworks** [comment]
Something like that might indeed be useful for debugging things. (Safe-mode)

In the meantime, you might be able to recover your world with the latest dev build (link in readme), which should solve the packet overflows.

**Comment by mrlamb** [comment]
Excellent! I went ahead and did the MCEdit thing for the server, but I'll be pushing for us to update forthwith!
