### ISSUE TITLE
Working with operators earned me a crash (Crash log included)

### ISSUE THREAD

**Issue by mrlamb** [CyclopsMC/IntegratedDynamics#487]
#### Issue type:

- :bug: Bug
____
#### Short description:
While playing around with custom operators, piping and a slew of things I'm barely understanding I triggered a crash. Crashes immediately on world load as well.

#### Expected behaviour:
Honestly, I kinda expected this. I'm terrible at this mod and it seems like all I can do is break things lately.

#### Actual behaviour:
Single player world crashes to launcher.

#### Steps to reproduce the problem:
I deleted the display panel with MCEdit and got back in so I can tell you exactly what variables I was using. I'll put the numbers on the cards as they are on mine, not that that matters but that hopefully you can follow along more easily in the recreation.

157 - string > "forestry"
158 - operator relational equals
159 - operater mod (item) > string
160 - operator apply (159 & 157)
161 - pipe (159 & 158)
162 - Item List (from inventory reader on a crate)

Then in the display panel, I believe I had 
164 count_p (162 & 161)

effectively trying to get a count of all the itemstacks from the forestry mod. Pretty sure the logic was wrong, but was trying to figure out how the things worked.

____
#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.9.6
- CyclopsCore: CyclopsCore-1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

#### Log file:

https://pastebin.com/PmBWFaKs

**Comment by rubensworks** [comment]
Note to self: also check how this is related to #468
