### ISSUE TITLE
Dandelions Squeezable into Bone Meal

### ISSUE THREAD

**Issue by ConnorMiner** [CyclopsMC/IntegratedDynamics#491]
#### Issue type:

- :bug: Bug

____
#### Short description:
In JEI, Dandelions are shown as giving Bone Meal in both squeezers, and when squeezing one, Bone Meal is given.

#### Expected behaviour:
Dandelions give Dandelion Yellow when squeezed in a Squeezer.

#### Actual behaviour:
Dandelions give Bone Meal when squeezed in a Squeezer.

#### Steps to reproduce the problem:

1. Check JEI uses for Dandelions in a Squeezer or Mechanical Squeezer.
2. Find that they give Bone Meal
3. ACTUALLY try and squeeze a Dandelion in a Squeezer or Mechanical Squeezer.
4. Get Fresh Dandelion Bone Meal™!

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.10.0
- CyclopsCore: 1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 14.23.1.2587

#### Log file:

Unavailable.

**Comment by josephcsible** [comment]
#492
