### ISSUE TITLE
Don't keep NBT when block is broken with a pickaxe

### ISSUE THREAD

**Issue by DasBrain** [CyclopsMC/IntegratedDynamics#493]
#### Issue type:

- :heavy_plus_sign: Feature request

When a block is broken with a pickaxe, it should not keep it's id. This could help do dismantle networks and not fill up your inventory.

**Comment by rubensworks** [comment]
This actually used to be like this, but I intentionally made the behaviour consistent with wrenching.

I'll think about it, not sure if I want to change it again. Maybe I'll add a config option.
