### ISSUE TITLE
Disabling Mechanical Squeezer in configs also disables Squeezer's JEI compat

### ISSUE THREAD

**Issue by KAfable** [CyclopsMC/IntegratedDynamics#496]
#### Issue type: 

- :bug: Bug
____
#### Short description:
Disabling the mechanical squeezer in the configs seems to turn off the JEI compatability for BOTH the mechanical squeezer and the  regular squeezer.

Same applies to the drying basin and its mechanical counterpart.

#### Expected behaviour:
Leaves JEI recipes and descriptions for the regular squeezer intact.

#### Actual behaviour:
Disables the squeezer outright, no recipes can be viewed in JEI.

#### Steps to reproduce the problem:

1. Disable the mechanical squeezer in configs (set to false), leave Squeezer configs at true.
2. Start the game, try to look in JEI for the Squeezer recipes, squeezer should still be craftable, but you cannot check its uses. Even look at the recipes for squeezer outputs results in nothing. 
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.10.1
- CyclopsCore: 1.12.2-0.11.1
- Minecraft: 1.12.2
- Forge: 2584

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedDynamics-Compat/commit/e57063268374ccc49a0b211b1579c79096b84b69
