### ISSUE TITLE
Nether Quartz dupe with Mechanical squeezer

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedDynamics#499]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Steps to reproduce the problem:

1. Throw some nether quartz in the mechanical squeezer and then smelt it (with actually additions installed presumably).

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.0.10.2
- CyclopsCore: 1.12.0.11.1
- Minecraft: 1.12.2
- Forge: 14.23.1.2587

#### Log file:

N/A

I can produce a recording of the issue if needed.

**Comment by rubensworks** [comment]
Yeah, that's not supposed to happen indeed.
