### ISSUE TITLE
Achievement Redstone Observement, Constant Definition, and Arithmetic Addition not recognized

### ISSUE THREAD

**Issue by Rixxaw** [CyclopsMC/IntegratedDynamics#500]
#### Issue type:
- :bug: Bug
____
#### Short description:
Achievement Redstone Observement, Constant Definition, and Arithmetic Addition not recognized, in game.  Multiple attempts to gain these achievements and restarts have not resolved the issue.  I have now created a new world and same result in a new world.

#### Expected behavior:
Unlock the achievement : Redstone Observement, Constant Definition, and Arithmetic Addition, when you follow the procedure I will describe below.

#### Actual behavior:
Achievements are not Unlocked:

#### Steps to reproduce the problem:
For **Redstone Observement**:
I am testing this in a Brand new world.
The Book seems to describe using a Redstone Integer Card, but the Achievement describes just a normal Integer Card.  I have tried both Redstone Integer from a Redstone Reader to a lever that i can flip on off and the display shows the value change.  I have also tried writing a constant integer using a Logic Programmer.  Neither seem to activate the achievement.
[Screenshot](https://i.imgur.com/C8RNgIo.jpg)

For Constant Observement and Arithmetic Addition
1. Proceed up achievement path to Logic Programming, gaining that achievement.
2. Open Logic Programming Interface and select Integer.
3. Enter a numaric value
4. Place variable card into the integer slot to write the constant integer variable.
5. Repeat step 4.
6.  In the Logic Programming Interface select the addition with name +, put both of your constant integer cards into the main interface, and then a blank variable card in the output slot.
7. Create a Variable Store attach a cable and a display.  Place the constant int variable cards in this store.
8. Place the Addition Variable in the display.  You will see the resulting Math working, but no achievement.

____
#### Versions:

- This mod: 1.12.2-0.10.0
- CyclopsCore: 1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 8.0.99.99

#### Log file:
[Pastebin of Log](https://pastebin.com/embed_js/ZMvNqxbE)

**Comment by Rixxaw** [comment]
This is the current DireWolf20 1.5.0 on FTB, there seems to be an update to it, I'll test again.

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it.

(The new update of the pack is unlikely to change the situation though, as nothing has been changed regarding advancements)

**Comment by Rixxaw** [comment]
I did try to do all the testing in Survival as I wanted to make sure that I reproduced it how my player first experienced it and not testing with some creative item that is somehow different than the book.  So I crafted all the items to test.  I did pull basic materials from creative like Stone / Redstone / iron etc.

**Comment by Rixxaw** [comment]
Confirmation - Still doesn't work after update.
