### ISSUE TITLE
Allow variable type Number to be cast to String

### ISSUE THREAD

**Issue by ncaycedo** [CyclopsMC/IntegratedDynamics#504]
#### Issue type:

- :bug: Bug
- :heavy_plus_sign: Feature request
____
#### Short description:
In order to manipulate numbers and format them or make them more legible, one must be able to use them as strings. 

#### Expected behaviour:
The Name operator (toString) should cast variables of type Number to String.

#### Actual behaviour:
The Logical Programmer states:
"The operator name received an input with the type Number at position 1 while the type To String was expected."

#### Steps to reproduce the problem:

1. Make a Variable of type Number.
2. Try to pass it as an argument to the Name Operator.

____
#### Versions:

- This mod: 0.10.0
- CyclopsCore: 0.11.0
- Minecraft: 1.12.2
- Forge: 14.23.1.2583

#### Log file:

There's nothing relevant in the log file.

**Comment by rubensworks** [comment]
The problem only occured on values with the actual number datatype. Until this fix is released, you should be able to get around by just casting to an integer, double or long.
