### ISSUE TITLE
Use long to represent FE energy values

### ISSUE THREAD

**Issue by ncaycedo** [CyclopsMC/IntegratedDynamics#505]
#### Issue type:

- :heavy_plus_sign: Feature request

When used with machines with massive capacity (Mekanism's induction matrix in this case, with capacity of 3,2GFE but I would guess it happens with other similar batteries) the integer overflows and displays a negative value.

**Comment by rubensworks** [comment]
Duplicate of #444.

If Mekanism supports Tesla, you should be able to read the values as longs using the Tesla unit. FE only supports ints, no way around that.
