### ISSUE TITLE
Crash in 1.9.4 with only this mod

### ISSUE THREAD

**Issue by archonsd** [CyclopsMC/IntegratedDynamics#51]
- Minecraft 1.9.4 w/ Forge forge-1.9.4-12.17.0.1910-1.9.4-universal.jar
- CyclopsCore-1.9.4-0.6.1.jar
- IntegratedDynamics-1.9.4-0.3.10.jar
- mcjtylib-1.9.4-1.8.6.jar
  No other mods present.

Run forge with " java -jar forge-1.9.4-12.17.0.1910-1.9.4-universal.jar nogui"

Output:  http://pastebin.com/cM7FNk9f

**Comment by rubensworks** [comment]
I knew I forgot something, I didn't test this newest release on a server yet.
I'll look into it tomorrow.

**Comment by archonsd** [comment]
Thanks a lot.  It works great Single player.  It only does this in server mode.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@890d99b5e2c89b13677aca841fea8a080bfbe62f
New release of CyclopsCore coming later today.
