### ISSUE TITLE
Missing NBT listDouble, listFloat and listString operators

### ISSUE THREAD

**Issue by jjcurry812** [CyclopsMC/IntegratedDynamics#510]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: Integrated Dynamics 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2559

____
#### Description

I used an Entity Reader to get a Variable Card with my Static Player Entity.
Using Entity NBT Operator created a Card with the NBT data for my Player.
I'm trying to read the Entity NBT Pos tag which is a list of 3 doubles, but there doesn't appear to be any function NBT.listDouble, only listTAG, listByte and listInt.
Motion and Pos are lists of 3 Doubles for X,Y,Z, while Rotation is a list of 2 Floats for heading and elevation as shown from the NBTExplorer screencap below

![image](https://user-images.githubusercontent.com/35882960/35478562-706d322c-03ae-11e8-8ab3-a6223d4d9d23.png)

**Comment by josephcsible** [comment]
NBT has special support for byte arrays, int arrays, and long arrays, and everything else just goes in lists. In your example, "Motion" is a list. Confusingly, Integrated Dynamics seems to lump arrays and lists together.

**Comment by jjcurry812** [comment]
NBT data structure confusingly has separate structures for lists vs arrays.  See below research int array vs seenConstellations string list.  They may be logically similar, but obviously different data structures in this format.

Perhaps adding NBT.listString might be useful too.  Thank you for looking into this addition.

![image](https://user-images.githubusercontent.com/35882960/35482126-996716ca-03fe-11e8-89cf-73bd588566b3.png)

**Comment by rubensworks** [comment]
As reported in #822, also `listString`.
