### ISSUE TITLE
crash on startup. model baking error.

### ISSUE THREAD

**Issue by kain184** [CyclopsMC/IntegratedDynamics#513]
hello i am looking to find out where this issue is coming from. it seems from what i can see to be from your turn page ogg file but i could be wrong any help would be appreciated. 
https://pastebin.com/cWRkafbe

**Comment by josephcsible** [comment]
This looks to me like a Botania crash. Why do you think it's related to integrated Dynamics?

**Comment by kain184** [comment]
It was a null point exception. And in some line that errored. It said integrated dynamics/nextpageflip. Ogg or something to that effect could not be loaded. It was the best I had to go on. Figured if I was wrong someone else would see it. What line told you it's Botanica?

**Comment by josephcsible** [comment]
> It said integrated dynamics/nextpageflip

I don't see that anywhere in your log. What line number do you see it on? Anyway, here's why I think it's Botania:
```
java.lang.NullPointerException: Initializing game
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at vazkii.botania.client.model.GunModel.<init>(GunModel.java:46)
    at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:112)
```

**Comment by kain184** [comment]
i did more reasurch and found i was missing connected textures mod. however after fixing that issue i found this. 
B#355]  [12:51:34] [Immersive Engineering Contributors Thread/INFO] [immersiveengineering]: Attempting to download special revolvers from GitHub
[B#355]  [12:51:34] [Client thread/WARN] [Integrated Dynamics]: Invalid item integrateddynamics:variableTransformer
[B#355]  [12:51:34] [Client thread/WARN] [Integrated Dynamics]: Invalid item integrateddynamics:variableTransformer
[B#355]  [12:51:34] [Client thread/ERROR] [IntegratedDynamics-Compat]: The compatibility for immersiveengineering has crashed! Report this crash clog to the mod author or try updating the conflicting mods.
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.component.ItemStackRecipeComponent.equals(ItemStackRecipeComponent.java:34)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.component.ItemStackRecipeComponent.equals(ItemStackRecipeComponent.java:30)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.component.ItemAndFluidStackRecipeComponent.equals(ItemAndFluidStackRecipeComponent.java:52)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.RecipePropertyMatcher.matches(RecipePropertyMatcher.java:22)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.RecipeRegistry.findRecipe(RecipeRegistry.java:127)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.recipe.custom.RecipeRegistry.findRecipeByOutput(RecipeRegistry.java:102)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.integrateddynamicscompat.modcompat.immersiveengineering.ImmersiveEngineeringRecipeManager.register(ImmersiveEngineeringRecipeManager.java:22)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.integrateddynamicscompat.modcompat.immersiveengineering.ImmersiveEngineeringModCompat.onInit(ImmersiveEngineeringModCompat.java:22)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.modcompat.ModCompatLoader.onInit(ModCompatLoader.java:61)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.init.ModBase.callInitStepListeners(ModBase.java:234)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.cyclopscore.init.ModBase.postInit(ModBase.java:324)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at org.cyclops.integrateddynamicscompat.IntegratedDynamicsCompat.postInit(IntegratedDynamicsCompat.java:132)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#355]  [12:51:34] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#355]  [12:51:34] [Client thread/WARN] [Integrated Dynamics]: Could not find an achievement by id 'integratedtunnels.exporterItem'

**Comment by rubensworks** [comment]
Yep, Botania crash.

I'm leaving this issue open for the other issues that are in the mentioned part of the logs.

**Comment by kain184** [comment]
Had botania disabled for that run immersiveengineering is the error in the log chunk I just posted  going to try downgrade to previous versions for a fix.

**Comment by rubensworks** [comment]
Oh dear, that's 1.11 (please include this in the issue in the future), lots of things were broken back then. The issues in the logs don't apply anymore.
