### ISSUE TITLE
Operator claims its type is number

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#514]
Originally reported at https://www.reddit.com/r/feedthebeast/comments/7tx01z/integrated_dynamics/

> I have been trying to make a complex operator, where I can apply a few inputs and have all my auto-crafting-variables for a single station set up.
> 
> I have found a roadblock with the Pipe (,) operator. It seems like I cannot apply inputs to both parts of the Pipe.
> 
> With `(Integer Increment) (ID 373), (Integer Increment) (ID 374), (Pipe (373, 374)) (ID 375), (Integer 0) (ID 376), (Apply (375, 376)) (ID 377)` I get 2 as expected.
> 
> With `(Integer Increment) (ID 378), (Arithmetic Addition) (ID 379), (Pipe (378, 379)) (ID 380), (Integer 0) (ID 381), (Integer 0) (ID 382), (Apply2 (380, 381, 382)) (ID 383)` however I get `Virtual Operator Piped Operator [integer;] (Operator)` whatever that means.
> 
> Does anyone know how I can make an operator like the second one, where I can apply 2 or more variables to make it "concrete"?

I can confirm this in latest Gradle dev. I did some poking around, and if instead of Apply2, I just use Apply twice, I get the error "This aspect expects Operator, but Number was given." Further investigating reveals that the curried operator from the first Apply returns number when you call getType() on it, even though it is in fact an operator.

**Comment by rubensworks** [comment]
It was a simple limitation of the pipe implementation, which is fixed now.
