### ISSUE TITLE
[1.12.2] [The One Probe] Error: integrateddynamics:partData shown on every block

### ISSUE THREAD

**Issue by wamc2017** [CyclopsMC/IntegratedDynamics#522]
#### Issue type:

- :bug: Bug
____
#### Short description:
Updated to 1.12.2-0.11.0 and every block shows the following The One Probe error:
![top](https://user-images.githubusercontent.com/33242447/35641273-02bc415e-06c0-11e8-96bd-00908757efbb.png)

1.12.2-0.10.4 works fine. If this is a TOP error, I will report it there... 

#### Expected behaviour:
No error in TOP :smile:

#### Actual behaviour:
Error is shown...

#### Steps to reproduce the problem:

1. Install 1.12.2-0.11.0 together with TOP and look at any block.
____
#### Versions:

- This mod: 1.12.2-0.11.0
- CyclopsCore: 1.12.2-0.11.2
- CommonCapabilities: 1.12-1.4.0
- TheOneProbe: 1.12-1.4.19
- Minecraft: 1.12.2
- Forge: 14.23.1.2607

#### Log file:
Tested it with only the mods above installed, nothing in the log shows any error/warning/info what could be wrong... 

Best regards
wamc

**Comment by rubensworks** [comment]
Ah yes, I did some changes to the ID interfaces which may have broken TOP integration. Will look into it.
