### ISSUE TITLE
Predicate has wrong type

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#523]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
Predicates occasionally claim that they have a type other than their correct type, giving spurious type errors.

#### Steps to reproduce the problem:

1. Build the following predicate: pipe(Item Damage, apply(Greater Than, 10))
2. Place the predicate in an item exporter

#### Expected behaviour:
All items that have taken less than 10 damage will be exported

#### Actual behaviour:
The exporter errors with the message "This aspect expects Item -> Boolean, but Number -> Boolean was given."

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.11.0
- CyclopsCore: 0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.1.2605
- Integrated Tunnels: 1.5.0

#### Log file:

_Don't paste contents here directly, but use something like http://pastebin.com/_

Nothing relevant

**Comment by rubensworks** [comment]
The additional type checking that was introduced recently might be too strict in some cases.

**Comment by josephcsible** [comment]
This seems to be quite prevalent.
