### ISSUE TITLE
Strange problem with the one probe after updating id

### ISSUE THREAD

**Issue by digi-tal-it** [CyclopsMC/IntegratedDynamics#526]
#### Issue type: :bug: 
____
#### Short description:
Today I updated the version of integrated dynamics and get this weird display in the one probe anywhere I look:

https://imgur.com/SmJre7F

I posted this to McJty, too

#### Expected behaviour:

TOP should not display the error ;)

#### Actual behaviour:

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.11.0
- CyclopsCore: 0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.1.2601
- TOP: 1.4.19

**Comment by nigrum-dente** [comment]
Same result here

**Comment by rubensworks** [comment]
Please check open issues before reporting, duplicate of #522.
