### ISSUE TITLE
[bug] [crash] Energy Battery render -> client crash

### ISSUE THREAD

**Issue by IceSelkie** [CyclopsMC/IntegratedDynamics#529]
#### Issue type: 
:bug: (Crash)

#### Short description:
Crash caused by Energy Battery being broken with block lag (tries to reappear and render, but to render, it needs to know how full it is, and when it does that, it typecasts the block to Energy Battery, but it is actually air, so the game crashes).

#### Expected behaviour:
No crash.

#### Actual behaviour:
Crash.

#### Steps to reproduce the problem:
1. join laggy server (block lag)
2. Mine an Energy Battery
3. When block lag happens, and it reapears...
4. Be sad that it crashed. 😢

#### Versions:
_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.10.3
- CyclopsCore: 1.12.2-0.11.1
- Minecraft: 1.12.2
- Forge: 14.23.1.2584

#### Log file:
https://pastebin.com/kVyJ48e2

**Comment by IceSelkie** [comment]
Other thing to note:
Crash happened while:
1) connected to a Signilum Flux-Duct (Thermal Something)  <<---- This seems to (maybe) be the cause (possibly)
2) using smelting Diamond Pickaxe (smelt effect from Astral Sorcery)

**Comment by IceSelkie** [comment]
Yup. Flux-Duct seems to cause. (But the crash is still IntegratedDynamics/Cyclops sided.)

**Comment by rubensworks** [comment]
Thanks for reporting, should be an easy fix.

**Comment by IceSelkie** [comment]
:D
