### ISSUE TITLE
Display name/Display output

### ISSUE THREAD

**Issue by acoolghuy** [CyclopsMC/IntegratedDynamics#530]
- :question: Question

#### Short description:
Cant find name to compare with.
EXAMPLE:
My username is acoolguy yet when i look at the entitie name it says acoolguy (asdfg...) and theerfore i cant create a string for my name so i can compare if the entitie in front of the entitie reader is me or someone else to trigger a action.

#### Steps to reproduce the problem:

I( don't know how to recreate this situation.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 
- CyclopsCore-1.12.2-0.11.2 
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2604

**Comment by rubensworks** [comment]
Have a look at the unique_name operator, that allows you to do what you need.

**Comment by acoolghuy** [comment]
Ok thanks and how do i get the unique_name to a string to compare it to so if i am in front of a entity reader it will output true and if i am not in front of a entity reader it will output false?

**Comment by josephcsible** [comment]
When I call Unique Name on myself, I get my UUID followed by "(null)". This doesn't seem correct/useful.

**Comment by rubensworks** [comment]
That may be incorrect then, will have a look at it.
