### ISSUE TITLE
Placing mystical petals with Integrated dynamics

### ISSUE THREAD

**Issue by stenno** [CyclopsMC/IntegratedDynamics#536]
#### Issue type:

- :question: Question

I cannot place mystical petals from Botania into dirt ("planting" it) with Integrated Dynamics.
I tried the following:
Using a world item exporter, place item block (note that this worked fine with oak saplings)
Using a player simulator (this worked with neither oak sapling nor mystical petal)
Placing a petal with a Mechanical User from ExtraUtils2 in the mode 'use item on block' works fine, too. 
What am I doing wrong?

**Comment by josephcsible** [comment]
Try a Player Simulator instead.

**Comment by stenno** [comment]
I mentioned that i tried using a player simulator already ^_^"

**Comment by josephcsible** [comment]
Oh, I missed that. Did you have it set to right-click, to use the right item, and had it facing downward?

**Comment by stenno** [comment]
I used a "item" variable card with the following configuration:
Right click -> true
Left hand -> false
Continuous click -> true
Sneak -> false
Check stack size -> true
Check damage -> true
Check NBT -> true
item transfer rate -> 1
Entity Index -> -1
Offset x,y,z -> 0.5

I had facing it sidewards, i will try downwards now
[EDIT] Note that it worked sidewards with the mechanical user

**Comment by stenno** [comment]
Sorry, it didn't work downwards either.

**Comment by stenno** [comment]
I have it now:
I switched Target side from 'north' to 'south'. For some reason, it was pointing in the wrong direction... sorry for wasting your time.
