### ISSUE TITLE
[Request] Dimension blacklist/whitelist for world generation

### ISSUE THREAD

**Issue by Rosethorns** [CyclopsMC/IntegratedDynamics#541]
#### Issue type:
- :question: Question

As the title implies it would be really helpful to have a dimension blacklist for the purposes of controlling what dimensions Integrated Dynamics world generation will appear in.

Thanks for reading my request.

**Comment by josephcsible** [comment]
What does this mod have to do with Rustic?

**Comment by Rosethorns** [comment]
@josephcsible Sorry I had Rustic on my mind :P I meant Intergrated Dynamics

**Comment by josephcsible** [comment]
> controlling what dimensions **Rustic** world generation will appear in

**Comment by rubensworks** [comment]
Probably a typo, I assume this concerns the Menril Tree generation.
