### ISSUE TITLE
Relational Operators of live-updating Block-NBT values does not update.

### ISSUE THREAD

**Issue by Timetech01** [CyclopsMC/IntegratedDynamics#545]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

Attempting to control networks and general Minecraft systems using Relational Operators that receive at-least one of their input values from actively updating NBT values causes invalid behavior.

#### Expected behaviour:

When BurnTime would become less than 50 or equal-to-or-greater-than 50, I would expect the Redstone Writer and its monitoring Display Panel to switch between True and False or vise-versa, depending on the current state of BurnTime.

#### Actual behaviour:

Once the Less Than Operator has determined its current Boolean value, it does not update unless a change to the components of the network is made, apparently forcing a refresh of the system.

#### Steps to reproduce the problem:

Using the Block Reader on a Furnace, I gained the Tile Entity NBT.
I then found the NBT Value Integer of the "BurnTime" String inside the Tile Entity NBT data.
I then used the Relational Operator < "Less Than" to compare the current "BurnTime" Integer to the constant Integer 50.
I then put this Relational Operator in the Redstone: Boolean slot of a Redstone Writer, and a copy of it inside a Display Panel for convienence.  [I was also tracking the entire NBT of the Furnace, as well as its BurnTime on Display Panels.]

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.11.5
- CyclopsCore: 1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

#### Log file:

https://pastebin.com/2046uYUX

Log File edited to preserve anonymity.

**Comment by rubensworks** [comment]
Note to self: similar to #539.

**Comment by rubensworks** [comment]
I can't seem to reproduce this myself, I also tried similar variants of your described steps.

Are you sure that you're using version 1.12.2-0.11.5?
If yes, could you describe a detailed step-by-step guide to consistently reproduce the problem? (please double check if you can reproduce the problem yourself using these steps)

(If possible, a video showing the problem and how to set it up would be great!)

**Comment by rubensworks** [comment]
@Timetech01 Any updates on this?

**Comment by Timetech01** [comment]
@rubensworks Working out how to record video and audio of my setup.

**Comment by Timetech01** [comment]
@rubensworks https://www.youtube.com/watch?v=oM2MtlysFoM

**Comment by rubensworks** [comment]
@Timetech01 I only quickly scrolled through the video (will check in more detail later), but it looks like you are copying variables incorrectly. You should copy them using the crafting grid.

If you end up with multiple variable cards with the same ID (which is only possible in creative-mode), then things can go horribly wrong. I should probably add a safety that blocks this kind of copying...

**Comment by rubensworks** [comment]
@Timetech01 Could you check if you can reproduce this problem without creatively copying variable cards?

**Comment by rubensworks** [comment]
Ok, just checked the video in detail. This is definitely because you copy the cards through middle-clicking. If you can reproduce this problem without doing this, please let me know.

I'll include a warning in the item tooltip regarding this for next release.
