### ISSUE TITLE
Squeezer XML Chance Bug

### ISSUE THREAD

**Issue by ElvenChaos** [CyclopsMC/IntegratedDynamics#548]
#### Issue type:

- :bug: Bug
- :question: Question
____
#### Short description:

The Squeezer (and Mechanical Squeezer) does not display the chance for the second output if three (or more) item outputs have been defined. This is visible with the default Lapis Lazuli ore processing recipe provided by this mod, as well as any custom configurations that do this action.

Also, if a fourth item is declared, either the second or third output declaration is not displayed. Is this intended? If no liquid outputs are define, is a fourth item output allowed? Could it be?
____

#### Expected behaviour:

Squeezer (and Mech Squeezer) recipes display chance correctly on all valid output slots.

Ability to use all four available output slots for items when no liquids are defined.
____

#### Actual behaviour:

Bugged recipe view on either of the two above actions.
____

#### Steps to reproduce the problem:

1. Look at Lapis Lazuli Squeezer recipe or Sunflower --> dye Mech Squeezer recipe.

2. Mouse over second output slot

3. ???

4. _Profit!_

On second part of issue:

1. Define squeezer recipe with four item outputs in xml.

2. View recipe.

____
#### Versions:

- This mod: 0.11.4
- CyclopsCore: 0.11.4
- Minecraft: 1.12.2
- Forge: 2611
____

#### Log file:
Not a crash, so here is my [squeezer override xml](https://gist.github.com/ElvenChaos/1df3af03ebf4f7cb2e95b78ef8d93f3b).

**Comment by rubensworks** [comment]
It's merely a display issue, the machines should be able to work just fine.
