### ISSUE TITLE
Variable labels

### ISSUE THREAD

**Issue by PaulMurrayCbr** [CyclopsMC/IntegratedDynamics#549]
#### Issue type:
:heavy_plus_sign: Feature request

Please let me label my variables. As far as I can see - I have just started playing with the mod - this is a reasonably simple fix that would make life so much easier.

This relates to issue #367 . When displaying the full expression for a variable, the expansion of the expression should stop when it hits a variable that has been labelled, and that label displayed instead.

**Comment by rubensworks** [comment]
Doesn't the labeller work for you?

**Comment by PaulMurrayCbr** [comment]
Please mark this as "oops, this person didn't know about the variable labeller" and close it. Sorry for wasting eveyone's time.
