### ISSUE TITLE
Squeezer doesn't recognize Nether Quartz Ore.

### ISSUE THREAD

**Issue by onyxism** [CyclopsMC/IntegratedDynamics#550]
#### Issue type:
- :bug: Bug
____
#### Short description:
When i place the nether quartz ore into the Squeezer, nothing happens. It's not on the recipes list either.

#### Expected behaviour:
It should process the Nether Quartz Ore into Nether Quartz

#### Actual behaviour:
Nothing happens.

#### Steps to reproduce the problem:

1. place and power the Squeezer
2. interact and open the squeezer's interface
3. place Nether Quartz Ore into the appropriate slot.
4. observe that nothing happens.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.11.5
- CyclopsCore: 1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2607

#### Log file:
N/A

**Comment by rubensworks** [comment]
Please follow the template...

**Comment by onyxism** [comment]
I click on something when I switching windows so it saved before i finished filling it out. Should be good/updated now.
