### ISSUE TITLE
Squeezer to recognize Bauxite from Immersive Engineering.

### ISSUE THREAD

**Issue by onyxism** [CyclopsMC/IntegratedDynamics#551]
#### Issue type:
- :bug: Bug
- :heavy_plus_sign: Feature request
____
#### Short description:
When i place the Bauxite Ore into the Squeezer, nothing happens. It's not on the recipes list either. The squeezer works with all other ores from Immersive Engineering.

#### Expected behaviour:
Like all the other ores in Immersive Engineering It should process the Bauxite Ore into Aluminium Grit

#### Actual behaviour:
Nothing happens.

#### Steps to reproduce the problem:
1. place and power the Squeezer
2. interact and open the squeezer's interface
3. place Bauxite Ore into the appropriate slot.
4. observe that nothing happens.

____
#### Versions:
- This mod: 1.12.2-0.11.5
- CyclopsCore: 1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2607
- Immersive Engineering: 0.12-77
#### Log file:
N/A

**Comment by rubensworks** [comment]
Looks like this was already suggested in #68, thanks for bringing it to my attention anyways!
