### ISSUE TITLE
Dupe bug with SpongeForge

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#560]
#### Issue type: Hardcore duping

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

https://files.pudding.tk/wgh6cl2lvq.mp4 show this video... u understand it

#### Expected behaviour:

dismantle and put without dupe

#### Actual behaviour:

show video

#### Steps to reproduce the problem:

show video

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedDynamics-1.12.2-0.11.5
- CyclopsCore: CyclopsCore-1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2619 
- Modpack: Modern Skyblock 3 v3.1.4, Emerald Meteors v1.2.1
- Server: Spongeforge v1.12.2-2611-7.1.0-BETA-2931

**Comment by rubensworks** [comment]
Can you try reproducing this without spongeforge installed?

**Comment by ghost** [comment]
without works fine but with not <.<

**Comment by rubensworks** [comment]
@xILikepuddingx Could you report this to the spongeforge issue tracker? You can link back to this issue, in case something needs to be changed on my end.

**Comment by ghost** [comment]
I can not, because I do not know how to write this>. <. I would be glad if you could do that ....

**Comment by rubensworks** [comment]
@xILikepuddingx Could you try using the latest SpongeForge version? I just tried this myself with 8.0.0-BETA-2959, and I don't seem to have any issues myself.

Also, make sure to mention any SF plugins you are using.

**Comment by ghost** [comment]
ok with the version 7.1.0-BETA-2963 now everything works as it should. thank you for the effort
