### ISSUE TITLE
Item variable JEI integration failing

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedDynamics#561]
#### Issue type:

- :bug: Bug

____
#### Actual behaviour: The variable clears after exiting the programmer gui WHEN USING JEI, it works with lists of items however. 

Provided video :  https://youtu.be/83CjbjAaWHM

#### Steps to reproduce the problem:

1. Use JEI to shift click into an item variable,
2. Exit gui, or manually drag the variable out of the programmer.

____
#### Versions:

- This mod:  0.11.6
- CyclopsCore: 0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2613
- JEI: 4.8.5.147

**Comment by rubensworks** [comment]
What JEI version are you using?

**Comment by bpwhelan** [comment]
Ah, twould make sense to include that. I am using 4.8.5.147

Edited on original post for reference.
