### ISSUE TITLE
[1.12.2] CT support doesn't work with latest CT version

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/IntegratedDynamics#563]
#### Issue type:
- :bug: Bug

#### Short description:
 With the latest version of CraftTweaker, the CraftTweaker integration doesn't work.

#### Expected behaviour:
 The CT support to work.

#### Actual behaviour:
 The CT support doesn't work.

#### Steps to reproduce the problem:
1. Add a recipe for an ID machine with CT
2. Load up a world

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.8
- CyclopsCore:  CyclopsCore-1.12.2-0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- CraftTweaker: CraftTweaker2-1.12-4.1.6

#### CT Log file:
https://pastebin.com/RZQPvnQb

**Comment by rubensworks** [comment]
Could you also report this to the CT issue tracker? Any breakage with only changes on CT's side seems like an issue on their end. In any case, they should not be making API-breaking changes without changing the major release version.

**Comment by TheLimePixel** [comment]
Well, seeing that only your CT support broke (out of the 15 mods in my pack that have CT support) and knowing that Soot had to change its CT support, something ID uses in its CT integration has surely changed.

**Comment by rubensworks** [comment]
Indeed, but nothing _should_ have changed.

Could you report it anyways? As the stacktrace seems to give no hints to _what_ has changed.

**Comment by TheLimePixel** [comment]
I'm on my tablet right now so reporting issues is a bit awkward

**Comment by TheLimePixel** [comment]
Yeah, this wasn't fixed:
![image](https://user-images.githubusercontent.com/25333164/38171751-19b5c6b4-35a0-11e8-956b-bf9531d0a0f9.png)

**Comment by rubensworks** [comment]
Apparently I forgot one CT method: https://github.com/CyclopsMC/IntegratedDynamics-Compat/commit/f756b87b5d7e5241fe32eba98693520680e242c0

Will be fixed in the next update.
