### ISSUE TITLE
Excessive log output due to use with Funky Locomotion

### ISSUE THREAD

**Issue by Aedda** [CyclopsMC/IntegratedDynamics#564]
#### Issue type:
- :bug: Bug
- :snail: Performance issue
____
#### Short description:
Attempting to move ID cables with Funky Locomotion results in a multiple GB log file of errors being created, approx 2gb per hour, 9gb in 4.5 hours before the problem was noticed.

I'm aware (now) via #443 #476 #533 that use with frames is not supported, which is not surprising. However the log spam was not expected. Additionally after removing all ID blocks and items from world, and clearing player inventory errors continued to flood log.

#### Expected behavior:
1. Either an outright crash with or without re-loadable world, or normal operation.
2. Problem to be resolved once ID blocks and items were removed from world.

#### Actual behavior:
No visible error other than display panel showing old value despite variable change. Actual problem apparently persisted despite no sign outside of log file.

#### Steps to reproduce the problem:

1. Place line of ID logic cable (used display panel and block reader also in testing) on Funky Locomotion frame.
2. Test block reader and display panel with common block (used coal ore in testing).
3. Move network using frames, display panel will continue to show old value.
4. Watch as errors begin to flood log.
5. Chang block and display panel continues to display old value.
6. Break and replace one piece of network cable.
7. Observe that display panel now shows correct block.
8. Change block and note that display panel again updates with new block.
9. Break and remove all ID blocks and items from world, and player inventory.
10. Observe that errors continue to flood log, this will continue until the host disk is full or world is reloaded.
____
#### Versions:

- This mod: 1.12.2-0.11.8
- CyclopsCore: 1.12.2-0.11
- Minecraft: 1.12.2
- Forge: 14.23.2.2631

#### Log file:

I've only included a small snip of the actual errors being produced, there are billions of these: https://gist.github.com/Aedda/d9640b16954ee382b4b8f895b53186eb

**Comment by rubensworks** [comment]
My preference would be to just add support for frames (#443). If this will would however take me too much longer, I can add a temporary measure for this logging issue.

**Comment by rubensworks** [comment]
Muting logs doesn't seem like the proper solution here. I will try to add proper support in #443 soon. Until then, don't use frames with ID networks :-)
