### ISSUE TITLE
Duping glitch (Cyclic automated user, Integrated Dynamics drying basin, evilcraft condensed blood, and hopper)

### ISSUE THREAD

**Issue by Xetaxheb** [CyclopsMC/IntegratedDynamics#565]
- :bug: Bug

Pack is single player FTB Horizons III

Cyclic-1.12.2-1.10.12.jar
IntegratedDynamics-1.12.2-0.10.3.jar
EvilCraft-1.12.2-0.10.45.jar

Pretty easy reproduce: Auto user with 1 (or more, it will empty down to 1) condensed blood pointing at a drying basin, basin over a hopper pointing at a chest. After it hits 1 blood left, that last blood never disappears but the user keeps putting one in the basin which the hopper also pulls one out of. Infinite item that's otherwise exclusively from dungeon chests.

edit: actually bigger problem I just noticed, anything put in the basin with specific timing while this glitch is going on will just disappear entirely

**Comment by Lothrazar** [comment]
I have some GIFS uploaded and ive explored a few edge cases, two where there is no bug, and one where it is. PrinceOfAmber/Cyclic#757

Feel free to ask anything there, check my source code, or dm me on twitter/discord.

**Comment by rubensworks** [comment]
It looks like this has been fixed in Cyclic.
