### ISSUE TITLE
RS crafting Nonfunctional?

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedDynamics#567]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Steps to reproduce the problem:

1. Hook up inventory writer to RS system capable of autocrafting
2. Place item variable in inventory writer to try and trigger the autocrafting of said item.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.11.9
- CyclopsCore: 0.11.5
- Minecraft: 12.2.2
- Forge:  14.23.2.2641
- Refined Storage: 1.5.32

As always, I can post a youtube video showing my setup in case it's needed.

Thanks for all your awesome work on this awesome mod.

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it soon.
