### ISSUE TITLE
Menril trees grow differently in superflat worlds

### ISSUE THREAD

**Issue by Lykrast** [CyclopsMC/IntegratedDynamics#571]
#### Issue type:

- :bug: Bug

____
#### Short description:

In standard superflat worlds, Menril trees grow their leaves in an unusual way.

#### Expected behaviour:

Menril trees should grow the same in normal worlds, standard superflat worlds and superflat worlds with the Overworld preset.

#### Actual behaviour:

Menril trees in normal worlds and in superflat worlds with the Overworld preset grow like this:
![image](https://user-images.githubusercontent.com/8684850/39360121-37774cea-4a1d-11e8-9e34-4e4e6a8be4c5.png)

Menril trees is standard superflat worlds grow like this:
![image](https://user-images.githubusercontent.com/8684850/39360134-439bf570-4a1d-11e8-8b28-2b29607b2efc.png)

#### Steps to reproduce the problem:

1. Make a superflat world on the default preset
2. Place a Menril Sapling
3. Bonemeal it
4. Observe
5. Repeat on a normal world or a superflat world with the Overworld preset

____
#### Versions:

- This mod: 1.12.2-0.11.10
- CyclopsCore: 1.12.2-0.11.15
- Minecraft: 1.12.2
- Forge: 14.23.2.2654

**Comment by rubensworks** [comment]
Oh, those look _interesting_...
