### ISSUE TITLE
Tutorial rewards not claimable

### ISSUE THREAD

**Issue by Jomeaga** [CyclopsMC/IntegratedDynamics#572]
- :bug: Bug

#### Short description:
Completed the first tutorial section's required advancements, they all have a check in the tutorial book and are completed in the advancement tab. Cannot claim the rewards from the book however. Additionally, the advancements past the first 4 are not showing up at all (both in advancements and other tutorials). This is on the Enigmatica 2: Expert pack, version 1.22

#### Expected behaviour:
Complete advancements, click rewards (when you hover it says claim), receive rewards.

#### Actual behaviour:
Complete advancements, click rewards (when you hover it says claim), nothing happens.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.11.11
- CyclopsCore: 1.12.2-0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

**Comment by rubensworks** [comment]
Can you reproduce this with just ID installed?

Are you experiencing this on a server? If so, what about singleplayer?

Do you see anything in the server or client logs?

**Comment by Jomeaga** [comment]
The issue did not occur with a fresh install with only ID (same forge version).

Issue was in singleplayer. Tried a fresh world in the modpack, issue persisted.

This is the log from the fresh world https://pastebin.com/8xdvakdd

Here are some screenshots:
ID only
https://puu.sh/Aiqbp/08e7a11c3e.png
https://puu.sh/Aiqb5/3448105ab8.png

Enigmatica 2: Expert
https://puu.sh/AiqsA/badf54dc16.png
https://puu.sh/AiqrV/109abd1e16.png

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/8xdvakdd">[12:41:06] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Jomeaga  - Pastebin.com</a></strong></div></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by rubensworks** [comment]
Ah, I see what's wrong. It looks like one of the advancement has been disabled.

**Comment by Jomeaga** [comment]
Is that something the modpack developer needs to fix? If so how can they fix that?

**Comment by rubensworks** [comment]
Well, it kind of breaks the whole tutorial progression...

To make sure it has actually been disabled, could you double check what happens in Enigmatica when you pick up a Crystalized Menril Block?

**Comment by Jomeaga** [comment]
Nothing happens when I do that

**Comment by rubensworks** [comment]
Ok, then the best solution would be if you report this to the modpack author. The advancements need to be enabled for the book tutorials to work. (Feel free to link to this issue here)

If the author has a good reason for disabling it, I can look into providing a way to change the tutorials as well (as they depend on it).

If the author did not change anything to it, then a mod in the pack must be breaking the advancement somehow.

**Comment by NielsPilgaard** [comment]
Hey, I'm the pack dev :)

Advancements have not been disabled.

**Comment by rubensworks** [comment]
@NillerMedDild Any idea what mod in the pack may be messing with advancements? As ID advancements work just fine outside of the pack.

**Comment by NielsPilgaard** [comment]
The only mod I know off in the pack that could influence it is Better Advancements, but I think that only alters the Advancements GUI. Could it be changed by Integrated Tunnels?

**Comment by rubensworks** [comment]
> The only mod I know off in the pack that could influence it is Better Advancements

It's possible, but I doubt it. The best way of checking would be to remove the mod and test :-)

> Could it be changed by Integrated Tunnels?

No, I develop IT as well, and that has been made to work together nicely.

**Comment by NielsPilgaard** [comment]
I can confirm it still happens without Better Advancements.

**Comment by rubensworks** [comment]
Too bad :/

I guess the only remaining method of identifying the conflicting mod is through binary search, and that's always a pain to do...

**Comment by Jomeaga** [comment]
Can we try granting the advancement to a player and see if that triggers it
to fix itself.

**Comment by NielsPilgaard** [comment]
I won't have time to do a binary search for a while, but I'll get around to it eventually :)

**Comment by NielsPilgaard** [comment]
I stumpled across this during some debugging: 
https://gist.github.com/NillerMedDild/507ad8a7a69866420475c68f50774079
It seems related to this issue.

<blockquote><img src="https://avatars2.githubusercontent.com/u/21295394?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/NillerMedDild/507ad8a7a69866420475c68f50774079">gist:507ad8a7a69866420475c68f50774079</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>

**Comment by rubensworks** [comment]
@NillerMedDild Are you using the latest ID version? Did you disable any of the default ID recipes?

**Comment by NielsPilgaard** [comment]
Yes I am on IntegratedDynamics-1.12.2-0.11.13, and yes, I have removed and redone recipes for
* Menril Planks
* Generator
* Mechanical Drying Basin
* Mechanical Squeezer
Apologies for the lack of information.

**Comment by rubensworks** [comment]
@NillerMedDild Ok, then these loading errors are normal. If recipe rewards from advancements are unavailable, the advancement will fail to load (vanilla behaviour). So if you want the advancements to work, you'll have to create a resource pack to override these advancement, and remove the recipes that have been disabled.

Be sure to let me know if there's anything else you need.

**Comment by NielsPilgaard** [comment]
I see, thanks for the help :)

**Comment by Cyprex** [comment]
I can't find any information on how to add advancements to resource packs in 1.12, how does this work?
I've been able to override the advancement via the data/advancements folder in a world, is there a way to do this without having to edit each world individually? Modifying the jar would likely work, but that does seem messy. I'd be interested in fixing this in Enigmatica 2.
