### ISSUE TITLE
Networks sometimes fail irrepairably

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#575]
#### Issue type:

- :bug: Bug

____

#### Short description:

Once in a while a network will spontaneously stop operating. Anything less than completely breaking all the parts and re-placing them has no effect. 

This seems like it happened more frequently in the past, now we're down to rarely. However, I can't really differentiate between this specific issue and past fixed issues that also presented as a non-functional network.

Could be related to omni-directional connectors. I use those a bit, both inter- and intra-dimensionally, and the one network that seems to have this problem more than the others has several of these attached.

I'll be posting more details as I can collect them.

#### Steps to reproduce the problem:

Have some networks. Maybe one will stop functioning eventually.

#### Expected behaviour:

Continue functioning

____

#### Versions:

- All The Mods 3: 5.9.3b
- Integrated Dynamics: 1.12.2-0.11.10 (This issue has also happened in earlier versions.)
- Integrated Tunnels: 1.12.2-1.5.5
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2669

#### Log file:

No crash, no logs.

**Comment by ouroborus** [comment]
![2018-05-16_13 51 05](https://user-images.githubusercontent.com/392047/40144021-fbb708cc-5911-11e8-9303-3e170a091a62.png)

This is the network I typically have problems with. The far right omni-directional connector is bound to this other network in another dimension (both sides are chunk loaded):

![2018-05-16_13 17 01](https://user-images.githubusercontent.com/392047/40144292-f8bbbf86-5912-11e8-9e74-4f5d6fa919f4.png)

I've lost track of what the center and left one are connected to. They may even be connected to nothing. They still have group IDs though.

Good news: The import connection stopped functioning today. The rest of the network seemed fine. Breaking a single wire was enough to get the network to re-initialize (as you had mentioned in that other ticket). This isn't the "normal" issue with this network, just pointing out that the fallback does work. Normally, the whole segment fails and breaking everything is the only working solution.

**Comment by rubensworks** [comment]
Thanks for reporting!

This feels like murder mystery without any clear clues... But the omni- and mono-directional connectors might indeed hint towards the problem. I'll play around with them a bit when I find time.

If anyone would experience similar issues with this, be sure to comment here.

**Comment by ouroborus** [comment]
Seems like I had another instance of this. I turned on ftbu's scheduled restarts so the server would restart nightly. I had been on periodically and nothing had been wrong. Then I was off for a few days or so and decided to upgrade ATM3 today. When I got on, the farm connection was operating fine but there was a ton of stuff lying around indicating that it had broken sometime in the last few days. (The particular harvester spits stuff out if it happens to be full when gathering.)

The farm is in an RFTools dimension. I know there was an issue before where it would break because RFTools loaded it's dimensions after IR had initialized. This was fixed but I wonder if it's a remnant of that, where the omni-directional connectors still have a race condition during server load.

**Comment by rubensworks** [comment]
If I understand correctly, the connection was fully functional when you got on your server the last time, and you did nothing to reset/repair the network?

It's indeed possible that there is some kind of race condition left, and some magical auto-repairing of networks.

More likely to me would be that this is simply a chunk-loading effect, where the farm was somehow being chunkloaded, but the IT network only partially. This could cause the IT network to not accept any items, and the farm would therefore just emit items into the world.

**Comment by ouroborus** [comment]
The particular gatherer has about a chest's worth of internal storage. To fill that and dump about another chest's worth of items would take maybe 5-10 minutes. The farm is forcably chunkloaded.

**Comment by rubensworks** [comment]
Ok, it sounds like my last explanation regarding chunk-loading is very likely to be true then.

**Comment by ouroborus** [comment]
I'm not sure I understand. Is this a thing I need to account for when building something using ID?

**Comment by rubensworks** [comment]
ID does not do chunkloading on its own, so if your networks span large distances, then you have to make sure that all (relevant) parts are chunkloaded. If certain parts of the network are not loaded, then they will be unavailable, until they become loaded.

**Comment by ouroborus** [comment]
Alright. The segments are what you see in the screenshots and those are each entirely contained in their own chunks. All involved chunks are chunkloaded. I understand the issue with having any network cross chunk boundaries and so prefer to keep them contained within single chunks.

**Comment by randomlypickedname** [comment]
I'd like to add in my issue with network failure here if that's alright... I've had networks fail after a server restart with the network entirely within a loaded chunk (with one network fitting into one block space). Any more detail I can provide for this?

This is on the Enigmatica 2: Expert modpack, version 1.29.

**Comment by rubensworks** [comment]
@randomlypickedname What exactly was the _network failure_? Parts stop working? Parts not being clickable? Errors being shown?

Do you see anything abnormal in the console?

What can you do to fix the network again?

**Comment by randomlypickedname** [comment]
Items stop being imported into the network chest (an ME interface in this case to be specific, but I've had it happen with drawer controllers as well) from an ender chest for one network, and from a compacting drawer to another for a separate one. The network looks normal, the importer shows true/false when I toggle a redstone lever, but nothing happens. I broke the network cable and replaced it and the variable card in the item importer to fix it. Nothing abnormal appears in the console either.

**Comment by rubensworks** [comment]
I'm in the process of rewriting some significant parts of IT, so once that's out, let's see if the problem still occurs.

**Comment by rubensworks** [comment]
Is anyone still encountering this bug in release 0.11.15? The fix for #611 might be related to this.
