### ISSUE TITLE
The accurately meaning about this mod name

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#576]
#### Issue type:

- :question: Question

____

#### Question:

I noticed that the Chinese name of this mod was translated as "集成动力".
集成=>Integrated
动力=>Dynamics
But the word "动力" in Chinese is generally related to something can moving, but there is nothing can moving in this mod.

Because Zh-En translation sometimes has ambiguous, I think this is very likely a wrong translation.
Word "Dynamics" also has the meaning of “动态” in Chinese.
“动态” meaning "something can change", and this mod content most is related to "variable".

So, what's the accurately meaning about this mod name?

**Comment by rubensworks** [comment]
Indeed, the 'Dynamics' part applies more to the variable changes through time. So I trust you that '动态' is a better translation. (Feel free to submit a PR for this!)

**Comment by Water-Moon** [comment]
It might be necessary to make the change but that might be something difficult to get an acceptance on, since most Chinese player would still prefer "集成动力" over "动态联合" as the Chinese name of the mod.

**Comment by rubensworks** [comment]
@Water-Moon I don't speak Chinese, so I don't really have an opinion on this.
@Flithor would you agree with this change?

**Comment by Flithor** [comment]
I want say nothing.
they think now the name still not the best, and community in China still use the old name in normal.
If they want, they can submit a PR to rename it.
