### ISSUE TITLE
Is there a way to implement caching?

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#578]
#### Issue type:

- :question: Question

____

#### Question:

I need to monitor a value, which 0 for a long time, but occasionally a non-zero value, and only stays 1 tick, I need to record and keep this value until it changes next time.
Current operations can do it?

**Comment by rubensworks** [comment]
Hmm, that might be a tricky one. I would say, use the delayer with a long history, but that might not be very efficient for your server.

Maybe you can ask it on our discord server, some smart people on there might be able to help as well.

**Comment by rubensworks** [comment]
Otherwise, you can do some magic using the materializer by continuously piping variables in and out.

**Comment by Flithor** [comment]
I implemented this magic!
![](https://media.discordapp.net/attachments/386054223688630272/447736642233565193/ok.gif)
But it seems that there is a bug about materializer.
It only inputs and outputs from the specified side.
I post a new issues
