### ISSUE TITLE
Regex_groups operator output wrong

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#579]
#### Issue type:

- :bug: Bug

____

#### Short description:

Regex_groups operator describe or behave incorrectly

![image](https://user-images.githubusercontent.com/23412916/40276657-5997a75c-5c42-11e8-8a2e-1577abc1627f.png)
In regex_groups operator describe its output type is "string"
but acuturely output type is list
![image](https://user-images.githubusercontent.com/23412916/40276670-b1688096-5c42-11e8-96e3-f5f3a88e0b5b.png)

____

#### Versions:

- This mod: 0.11.11
- Minecraft: 1.12.2
- Forge: 14.23.3.2678

#### Log file:

no log file

**Comment by rubensworks** [comment]
Hah, that's wrong indeed. Thanks for reporting!
