### ISSUE TITLE
Machine input/output side mapping

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#581]
#### Issue type:

- :bug: Bug

____

#### Short description:

Meterializer just support input/output at specified side

#### Steps to reproduce the problem:

Materializer can only input variable card by east side, and ouput assigned variable card by west side.
North side cannot input but will output the assigned/source variable card
Independent of the orientation when materializer  put down(Not associated with the block side)

#### Expected behaviour:

Materializer should can input/output the variable card(need to assign or assigned) by any side
Bottom can only output assigned variable card (hopper can work)
Only can input/output source variable card by top

____

#### Versions:

- This mod: 0.11.11
- Minecraft: 1.12.2
- Forge: 14.23.3.2678

#### Log file:

No any log file

**Comment by rubensworks** [comment]
Note to self: also look into side mapping of other machines.
