### ISSUE TITLE
Allow addition/removal of chance-based recipes with CraftTweaker

### ISSUE THREAD

**Issue by Fireztonez** [CyclopsMC/IntegratedDynamics#582]
I try to remove some Squeezer recipes, but I can't make it work. I look the syntax in your Wiki, but I think there is miss somes informations for help remove or make special advance recipe.

For make it more clear, the first thing I try to do is remove the squeezer recipe for sugar from sugar cane...
I try to do :
`mods.integrateddynamics.Squeezer.removeRecipe(<minecraft:reeds>);`
`mods.integrateddynamics.Squeezer.removeRecipe(<minecraft:reeds>,<minecraft:sugar>*3, null);`

But that 2 tests doesn't delete the recipe.

Other thing I want to know is how can I make a recipe giving multiple output or chance to have more... By example, the default sugar recipe is 2 + 50% chance to output one more... how I can do that with CraftTweaker??

Versions:
Minecraft : 1.12.2
Forge: 14.23.3.2678
Integrated Dynamics: 0.11.12

Thank's
Fireztonez

**Comment by rubensworks** [comment]
The CT integration indeed does not support the chance-based outputs, and this also causes the problem of the recipe not being removable, as you can not define its [chance output](https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/resources/assets/integrateddynamics/recipes/squeezer_convenience.xml#L548-L558).

I will look into improving this integration at some point in the future.

In the meantime, you can use our [XML recipe system](https://github.com/CyclopsMC/IntegratedDynamics/wiki/Recipe-XML) that allows you to override recipes.

**Comment by Fireztonez** [comment]
Thank's for the reply!
Perfect I will look the XML system, but for sure it will be great to improved the CT integration to support everithing.... CT have a big potential for making recipe I think!

Fireztonez

**Comment by rubensworks** [comment]
Irrelevant, now that we are using JSON recipes.
