### ISSUE TITLE
Is mcmultipart support disabled?

### ISSUE THREAD

**Issue by Trinsdar** [CyclopsMC/IntegratedDynamics#583]
#### Issue type:

- :question: Question

____

#### Question:

I am unable to place bits in the same block space as the cables and other parts. has mcmultipart support been disabled?
Integrated dynamics:0.11.11.
Minecraft 1.12.2
MCMultiPart-2.5.1
chiselsandbits-14.16
Forge 14.23.3.2678

It's occuring it the atm 3 pack, if that might affect it somehow. I haven't tested with the above mods alone.

**Comment by rubensworks** [comment]
Yep, support for MCMP has not yet been added in 1.12. See #157
