### ISSUE TITLE
1.12 lag on Mechanical Squeezer

### ISSUE THREAD

**Issue by Zygus42** [CyclopsMC/IntegratedDynamics#584]
Using the LagGoggles mod to profile the machinery in my base brings up the Mechanical Squeezer as one of the highest lag items:
![2018-05-31_15 46 59](https://user-images.githubusercontent.com/20757445/40779708-8ea9463e-6508-11e8-8ec6-b7be90336df1.png)

even though it's just sitting there, not actually doing anything:
![2018-05-31_15 47 04](https://user-images.githubusercontent.com/20757445/40779757-b476321e-6508-11e8-827a-825378a9f96e.png)

- This mod: 
           IntegratedDynamics-1.12.2-0.11.12
           IntegratedDynamics-CommonCapabilities-1.12-1.4.0
           IntegratedDynamics-CyclopsCore-1.12.2-0.11.6
           IntegratedTunnels-1.12.2-1.5.6
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2703-installer-win

LagGoggles mod as profiling tool.

**Comment by rubensworks** [comment]
Please use the appropriate issue template, and report profiling logs as explained here: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>CyclopsCore - Minecraft library mod for EvilCraft, Integrated Dynamics and others.</div></blockquote>
