### ISSUE TITLE
Missing NBT.tag() constant operator

### ISSUE THREAD

**Issue by Minyguy** [CyclopsMC/IntegratedDynamics#586]
#### Issue type:

- :bug: Bug

____

#### Short description:
I need to filter a list of items in a chest by their nbt-tag. the tag im looking for is nested within other tags

#### Steps to reproduce the problem:
Open portable logic programmer (or the block version)
click operator.
search nbt
1. ...

#### Expected behaviour:
All the operators that either output or have nbt as an input should be in the list.
____

#### Versions:

- This mod:  integratedDynamics-1.12.2-0.10.3.jar
- Minecraft:  1.12.2
- Forge: not sure if this is the one, but there is a "Forgelin-1.6.0.jar" in my mods folder.

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it soon.

**Comment by rubensworks** [comment]
Works for me:
<img width="521" alt="screen shot 2018-06-21 at 17 25 19" src="https://user-images.githubusercontent.com/440384/41728858-1fa48bf6-7578-11e8-8903-fe13ef57288b.png">

Note that the left-hand side only shows shorthands for the operators (for space reasons), you can see the full name by hovering over them.

**Comment by Minyguy** [comment]
I'm not talking about the operator there.
I'm taking about the constant.
The version you use with the apply modifier.

**Comment by rubensworks** [comment]
What is the exact (full) name of the operator you are talking about? (The name as it is shown in the left-hand bar tooltip)

**Comment by Minyguy** [comment]
I'm talking about when you make an operator, but give it variables later, by using the apply operator.

I want to use the "Operator: NBT Value NBT" in a "Type: Operator"

**Comment by rubensworks** [comment]
Ok, then I understood correctly. If you have a look at the screenshot above, you can see that this is available for me both in the left-hand side _and_ the right-hand side (where the constant operator screen has been selected, as you requested)

**Comment by Minyguy** [comment]
Hmm, I thought it would appear when I just typed NBT. Going to check the modpack I was playing when I posted the issue.

**Comment by rubensworks** [comment]
Did you type `nbt` or `NBT`? Because that might cause a difference.

Be sure to let me know how it goes when you try again.

**Comment by Minyguy** [comment]
It seems that I misunderstood the list.
May I suggest that when the list has unshown results that the bottom one just has "..." on it so that you know there are more results.

**Comment by rubensworks** [comment]
That's a good suggestion, could you open a separate issue for it? (it's easier for me to track that way)

**Comment by Minyguy** [comment]
Oh well, it won't load for some reason, but now I know what I was doing wrong.
Thank you 😊

**Comment by Minyguy** [comment]
I think I wrote it uncapitalized, but I don't think that should matter, since there were other results.

**Comment by Minyguy** [comment]
Will do
