### ISSUE TITLE
Mechanical Squeezer energy overflow

### ISSUE THREAD

**Issue by ManIkWeet** [CyclopsMC/IntegratedDynamics#587]
![image](https://user-images.githubusercontent.com/4006814/41549797-3ccae958-7327-11e8-8fdb-25bcbf4f7ded.png)

.jar version:
IntegratedDynamics-1.12.2-0.11.5

Mechanical squeezer and Draconic Evolution energy core with Cryo-Stabilized Fluxducts from Thermal Dynamics number overflow the energy buffer of the mechanical squeezer, resulting in negative values and instant loss of any power inside the DE energy core.

Cost me about 25GRF in a few minutes to figure this out :(

**Comment by rubensworks** [comment]
Thanks for reporting, will look into this soon.
