### ISSUE TITLE
"Skipped loading part from network" spam during server startup when cables are moved with Quark

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#589]
#### Issue type:

- :bug: Bug

____

Log spam towards end of server startup sequence.

The location reported in the logs is the isolated cable adjacent to the piston in this screenshot:

![2018-06-20_21 22 01](https://user-images.githubusercontent.com/392047/41697976-63807e3c-74d0-11e8-8393-db6b78d041bb.png)

____
#### Versions:

- This mod: 0.11.12
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Log file:

[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/2122015/latest.log) (spam starts at line 8591, towards the end of the file)

**Comment by rubensworks** [comment]
Are you by any chance using Quark? Because movement by pistons is unsupported at the moment: #309.

In any case, the console spam should not be happening.

**Comment by rubensworks** [comment]
Actually, this looks like the same problem as #564, so I'll be tracking this there.

**Comment by ouroborus** [comment]
ATM3 which includes Quark.

**Comment by ouroborus** [comment]
Any chance that there's a way to get networks to re-update after the server calms down, after start-up? That's the reason for even trying this thing with the pistons. The white block toggles the piston every 30 seconds to get the network to reconfigure. Seems like ID doesn't handle startup all that well when loading alongside other mods.

**Comment by rubensworks** [comment]
So you basically want an automatable _network reset_ feature? Sounds useful for debugging. Could you make an issue for it?

**Comment by ouroborus** [comment]
Well, there's #574. I think ideally, a broken network should try resetting itself automatically every few minutes. Sure, spam the log with whatever is breaking as well as auto-repair notices. That way it'll get reported more often and maybe be easier to diagnose as well as actually keeping failed networks working in situations where failure is intermittent.

**Comment by rubensworks** [comment]
> Well, there's #574.

Ha, forgot about that one. The list of feature requests is getting way too long...

> I think ideally, a broken network should try resetting itself automatically every few minutes.

That would be a good fallback. Ideally, it shouldn't break if the first place though :-)
