### ISSUE TITLE
Cables moved by piston do not update model

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/IntegratedDynamics#590]
#### Issue type:

- :bug: Bug

____

#### Description:

Cables moved by piston do not update model (though any stationary, adjacent cables do update).

![2018-06-20_21 22 36](https://user-images.githubusercontent.com/392047/41698235-12887492-74d2-11e8-85a7-219fd51a6f49.png)

____

#### Versions:

- This mod: 0.11.12
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by rubensworks** [comment]
I'm surprised that this even works, it used to crash (#309). In any case, this is unsupported behaviour for now, so only use this at your own risk, major problems may arise with this until we officially support it.

I'll be tracking this in #443 instead.
