### ISSUE TITLE
Suggestion: indication for more results than shown

### ISSUE THREAD

**Issue by Minyguy** [CyclopsMC/IntegratedDynamics#592]
I had a problem where I was unable to make the NBT.tag() constant operator because I misunderstood the list. I thought it wasn't there, while in reality it was just not shown because there were too many results.

I suggest that when there are more results than shown, the bottom "result" will be labeled "..." Without " " to inform the player to search more specific.

Alternatively, you could add a scroll bar on the side, which will allow players to access the unshown results without specifying the search.

The best solution in my opinion would be the scroll bar, but the "..." Is likely easier to implement.

**Comment by rubensworks** [comment]
FYI, you can use the arrow buttons to scroll through the results. (That should be made clear with the `...` though)

**Comment by Minyguy** [comment]
I wasn't aware of that, the player could be informed of that in the text box that appears when you hover over it.
