### ISSUE TITLE
Crash when evaluating operator

### ISSUE THREAD

**Issue by stewbeef** [CyclopsMC/IntegratedDynamics#593]
#### Issue type:

- :bug: Game crashed when I was putting a complicated variable card into the display to try to debug what was going on.

____

#### Short description:

I am afraid I can't remember the exact setup.  But I was trying to figure out why an operator that I thought would return an item wasn't (display seemed to show an item).  I put the result of that operator through something, and it caused a crash.

#### Steps to reproduce the problem:
This was using factory tech and rftools stuff, but I don't think it matters.
1. Had card C for the # of cupernickle in a crafter
2. Used an operator card for >= for 6 >= C boolean.  We'll call this Cg
3.  Same with redstone # card (R), but 4 >= R, we'll call this Rg
4.  Comparison with main storage for number of heating elements, 20 >= H, denote this Hg
5.  Made choice chain
 Rc: If Rg, then Redstone item, otherwise Integrated Dynamics Book*
 Cc: If Cg, then Cupernickel item, otherwise Rc
 Hc: if Hg, then Rc, otherwise Integrated Dynamics Book

I think all these choices were Operators, but since I can't load the game, I am not sure.  So I think I set this up wrong.
Cupernickel would show up in the display from this.  It wouldn't pull it.  I tried an ==, and it wasn't equal to the  Cupernickel item card.  I then tried something else to figure out exactly how this wasn't an item.  I was tired and don't remember (my apologies).  It crashed my game when placed into the display.  My last backup is from before I started any of this (several days old).

I am hoping the crash report will make it clearer what happened.

*I don't know how to do a nil item, when I did an empty item, it just pulls anything.  So I did this.

#### Expected behaviour:

Not to crash!
Also, it is confusing when something displays as an item but isn't an item.  But I didn't have time to delve into that more.  (Also dealing with my minecraft continuing to use more and more memory until it crashes).

____

#### Versions:

- This mod: integrateddynamics: 0.11.13
- Minecraft:  1.12.2
- Forge: 14.23.4.2725

#### Log file:

https://pastebin.com/6CC0Jgzg

**Comment by rubensworks** [comment]
The internals of operators are quite complex, it looks like I must have missed an edge-case.
