### ISSUE TITLE
Use \n in strings to define a new line

### ISSUE THREAD

**Issue by Shovinus** [CyclopsMC/IntegratedDynamics#595]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Use of \n (or other placeholder) to create new lines in strings for the display so you can create better looking output descriptions

**Comment by rubensworks** [comment]
You can already do this. Isn't this working for you?

**Comment by Shovinus** [comment]
Oh I have tried a few different ways, \n and /n, is it a different placeholder?

**Comment by rubensworks** [comment]
You should use `\n`.

What happens if you display strings with this in the display panel?

Are you sure you're using the latest version?

**Comment by Shovinus** [comment]
latest released, yes, I will retry, 1 second

**Comment by Shovinus** [comment]
haha wierd I must have done something wrong, works fine, was 3am last night so I blame that, thank you

**Comment by Shovinus** [comment]
![2018-07-04_10 26 19](https://user-images.githubusercontent.com/15085445/42268941-bb6fc996-7f74-11e8-8087-40b63f181f0f.png)
Perfect :)

**Comment by rubensworks** [comment]
Nice 😄

**Comment by Shovinus** [comment]
Awesome mod, would like nested searching for a tag too, will add as request though.

**Comment by Shovinus** [comment]
Using it to make 900 size crystals have 12 900,100,100 crystals now :)
