### ISSUE TITLE
Nested searching for a nbt tag

### ISSUE THREAD

**Issue by Shovinus** [CyclopsMC/IntegratedDynamics#596]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I had to find a deeply nested NBT value for something, unfortunately this meant defining a string for every tag and getting each layer 1 at a time ending up with 12 different variables. Could you make it so you can use a path via a string list to find nested tags, this would have meant defining only 2 variables on top of the entity tag. Thank you very much.

**Comment by rubensworks** [comment]
That might be an interesting feature to add.

I could look into adding suppport for JSONPath (or something similar) for navigating through NBT tags. So you could do something like `$.rootTag.elements[0].name`.

**Comment by Shovinus** [comment]
![edited_li](https://user-images.githubusercontent.com/15085445/42270547-0e61623c-7f79-11e8-85a6-836bb6e5a667.jpg)

this was the amount of variables I ended up with the 8 highlighted was just to get to the right tag :)
Btw would also be nice if you could add string builder i.e. "asdasd {0} rterwr {1} {2}" and pass in the string variables, would also simplify a lot.

**Comment by rubensworks** [comment]
> Btw would also be nice if you could add string builder

It's best to create a separate feature request for that.

**Comment by Shovinus** [comment]
yeh will do.

**Comment by rubensworks** [comment]
Semi-implemented, but this will require breaking changes to work, see #729. So expect this in 1.13/1.14.

**Comment by Shovinus** [comment]
Thank you for your work :)
