### ISSUE TITLE
Squeezer recipe tweaking

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#60]
I think that the squeezer could serve as an interesting piece in an alternate progression modpack. Unfortunately, as best as I can tell there is no way to tweak the recipes for the squeezer without repackaging the jar. If it's not too difficult it would be lovely to have a recipe xml file in the configs folder (like Ender IO does), or perhaps minetweaker/API support.

**Comment by rubensworks** [comment]
The recipes can in fact be changed/added using a similar XML recipe system.
I forgot to document this before, but I just created a wiki page here: https://github.com/CyclopsMC/IntegratedDynamics/wiki/Recipe-XML

If you need any further information, just let me know.

**Comment by ghost** [comment]
Awesome. Is there any support for overriding or removing recipes? Just for the sake of testing I tried to change the coal ore recipe to 8 coal instead of 4, but the original recipe had priority when I tested it out.

![untitled](https://cloud.githubusercontent.com/assets/16395640/16813099/c1d8328a-48f5-11e6-9555-0fb96f3ad41f.png)

**Comment by rubensworks** [comment]
Yes, you definitely can! Apparently, I did not document this feature anywhere.
I just updated the wiki with an explanation on how to _change_ existing recipes.
This should allow you to do exactly what you want.

**Comment by ghost** [comment]
I don't think the behavior is working quite as intended. When I posted the above screenshot I had already done exactly as the wiki says now that you have updated it. In the file config/integrateddynamics/squeezer_ores.xml I had the following

[squeezer_ores.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/362342/squeezer_ores.txt)
Attached as a txt file so that it can be uploaded to github (apparently xml files can't)

**Comment by rubensworks** [comment]
I'll try it out myself tomorrow, maybe I broke something during one of the updates.

**Comment by rubensworks** [comment]
I fixed the problem in CyclopsCore. I'll release a new version soon, in the meantime you can download the latest dev version (build 372) here: https://bintray.com/cyclopsmc/dev/CyclopsCore
Note that you now have to place your override xml files in an `_override` folder inside the `integrateddynamics` folder.
