### ISSUE TITLE
GL Render-bug with book

### ISSUE THREAD

**Issue by MrDvD** [CyclopsMC/IntegratedDynamics#601]
**Issue type:**

🐛 Bug

**Short description:** 
When I go to the page with the crafting recipe of any mechanism and point the cursor to any place **EXCEPT THE CRAFTING RECIPE,** I get this: https://bit.ly/2KJ1PBM

**Versions:**

This mod: **0.11.13**
Minecraft: **1.12.2**
Forge: **14.23.4.2725**

**Comment by rubensworks** [comment]
Putting this on hold, as I have a couple of internal things in the works, which will probably fix this issue in any case.

**Comment by rubensworks** [comment]
This should be fixed in CyclopsCore 1.0.0. (Please let me know if you would still encounter this issue)
