### ISSUE TITLE
Text goes beyond the book

### ISSUE THREAD

**Issue by MrDvD** [CyclopsMC/IntegratedDynamics#603]
**Issue type:**

❓ Question

**Question:**
I'm trying to translate your mod, and often my text goes to another page, or even outside the book. In some cases I can simply shorten the text, but sometimes it is impossible, otherwise the meaning will be lost. Is there any way to keep the text on it's page?

**Comment by rubensworks** [comment]
> I'm trying to translate your mod

Cool!

> often my text goes to another page, or even outside the book

Can you show an example/screenshot? Because the book system _should_ automatically wrap text.

**Comment by MrDvD** [comment]
Okay, [here](https://bit.ly/2Lcxs67) are the screenshots.

**Comment by rubensworks** [comment]
Ok, so the index sections. Scaling doesn't happen there yet indeed.
