### ISSUE TITLE
"On The Dynamics of Integration" cannot be placed in a Oak Bookcase

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#604]
#### Issue type:

- :bug: Bug
![2018-07-13_15 55 09](https://user-images.githubusercontent.com/7958470/42717355-28dd02f4-86b5-11e8-8f10-c9bc2a6d635d.png)
![2018-07-13_15 45 21](https://user-images.githubusercontent.com/7958470/42717328-031bad54-86b5-11e8-956b-a285a739389f.png)

#### Short description:

Unlike most all other mod books in SevTech V3.0.8, the "On the Dynamics of Integration" book cannot be place in a Bibliocraft _Oak Bookcase_.

#### Steps to reproduce the problem:

1. Obtain the "On the Dynamics of Integration" book
2. Obtain an Oak Bookcase
3. Attempt to place the book in the bookcase.

#### Expected behaviour:

The book should appear in the inventory of the bookcase and appear on the rendered version of the bookcase block.

#### Versions:

SevTech V3.0.8
Integrated Dynamics V1.12.2-0.11.12
Minecraft V1.12.2
Minecraft Forge 14.23.4.2707
Forge Mod Loader 8.0.99.99

**Comment by rubensworks** [comment]
AFAIK, this is something that should be coded/configured into bibliocraft. You should report this to the pack author. Nothing I can do about that on my end, sorry.

**Comment by ghost** [comment]
Cross linking to issue on Bibliocraft github.

https://github.com/Nuchaz/BiblioCraft/issues/597

**Comment by rubensworks** [comment]
Great! Let's follow it up there.
