### ISSUE TITLE
Operator of Thaumcraft bug

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#605]
#### Issue type:

- :bug: Bug

____

#### Short description:

Mark item in operators of Thaumcraft input cell will game crash

![image](https://user-images.githubusercontent.com/23412916/42720520-06b8f092-875b-11e8-9181-90bdcb60d9a7.png)

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.11
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2678
- Thaumcraft: Ver 6 Beta 17
#### Log file:

https://pastebin.com/BPc3dXim

**Comment by rubensworks** [comment]
Which items did you try?

**Comment by Flithor** [comment]
Variable card

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedDynamics-Compat/commit/6031bf4e4a2dc82dadb265c21a7368520a14db45
