### ISSUE TITLE
Try Input "*" in Logic Programmer filter and game crash

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#606]
#### Issue type:

- :bug: Bug

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.11
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2678

#### Log file:

https://pastebin.com/Aq1JN1Ei

**Comment by rubensworks** [comment]
The JechCore mod is messing with regex calls in ID, and breaking them. Please report it to the mod author or remove the mod.
