### ISSUE TITLE
String.Join?

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#607]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Same as this:
https://msdn.microsoft.com/en-us/library/57a79xd0%28v=vs.110%29.aspx

Oh, Java 8 was add this method
https://stackoverflow.com/a/22577565/6859121

**Comment by josephcsible** [comment]
Why does this need to be a built-in function? It's already possible to use the existing higher-order functions to build something that does this: `(separator, value) => reduce(pipe(concat, apply(pipe, apply(concat, separator))), tail(value), head(value))`

**Comment by rubensworks** [comment]
Most people often avoid higher-order logic, because of its complexity. So I agree that it should be added as a simple `list<string> => string` operation.
