### ISSUE TITLE
What's the Invisible Light?

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#608]
#### Issue type:

- :question: Question

____

#### Question:

I've found this name in language file, but I haven't seen it in game anymore.
https://github.com/CyclopsMC/IntegratedDynamics/blob/5cf0431d8db551a251dfc588c4ef8d18bee55355/src/main/resources/assets/integrateddynamics/lang/en_us.lang#L84
What's this?

**Comment by rubensworks** [comment]
It's a dummy block that is used to emit light from the light panel. It probably doesn't need a translation though.
