### ISSUE TITLE
Incomplete apply does not produce working operator

### ISSUE THREAD

**Issue by bsngardner** [CyclopsMC/IntegratedDynamics#609]
#### Issue type:

- :bug: Bug

____

#### Short description:

According to the book, applying fewer inputs than an operator needs creates an operator with the leftover inputs.  This doesn't appear to be working properly.

#### Steps to reproduce the problem:

1. Create getOrDefault operator
2. Flip the inputs in a new operator
3. Apply an integer to that operator
4. Flip the inputs again
5. Place the last card in a display panel and the rest in a variable store

#### Expected behaviour:

This should show an operator with signature any->List->any.  Instead there is an error: "The given config render pattern with 0 slots is not compatible with the number of input types 2 for :flip:"

--- Partially applied operator ---
![2018-07-20_21 49 51](https://user-images.githubusercontent.com/10689176/43031928-0fd3e28c-8c69-11e8-9487-c40fb98348d6.png)

--- Flip card ---
![2018-07-20_21 50 52](https://user-images.githubusercontent.com/10689176/43031929-0feb1a7e-8c69-11e8-8c40-8cf0fd5d2351.png)

--- Flip card error message ---
![2018-07-20_21 50 55](https://user-images.githubusercontent.com/10689176/43031930-1004c00a-8c69-11e8-9466-afe07445b726.png)

____

#### Versions:

- Integrated Dynamics:  0.11.13
+ Integrated Tunnels: 1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.4.2708

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by bsngardner** [comment]
This may be unrelated, but previously I had an issue where two predicates applied to a choice did not work in the predicate slot of an integrated tunnels player simulator or item exporter. But filtering a list with that same card and putting that in the list slot did work.  
1. Make two predicates (in my case, they gave true for certain items)
2. Apply a redstone reader boolean card and the two predicates to a choice operator.  
3. Put the card in the predicate slot of an item exporter on a network with both predicate items in it
4. Put an inventory on the output of the exporter. 
The redstone signal should control which item is exported, but nothing happens.  There is no error message in the item exporter. Putting the predicates in the slot individually does work, as does filtering a list from an inventory reader and putting it in the list slot.

Sorry if this is unrelated to the original bug; it seems similar from my point of view.
