### ISSUE TITLE
Can you give variables a name?

### ISSUE THREAD

**Issue by adamk33n3r** [CyclopsMC/IntegratedDynamics#614]
#### Issue type:

- :question: Question

____

#### Question:

Is it possible to give variables a name? Especially for operators, it would be very useful to give a descriptive name. I can't tell what the operator is actually comparing without looking up the variables by ID.

**Comment by rubensworks** [comment]
Yes, you can use the _Labeler_! :-)

**Comment by adamk33n3r** [comment]
Oh I feel silly 😆 It looked like a hammer so I didn't even consider it. Thanks!
