### ISSUE TITLE
ServerHangWatchdog catching on IntegratedDynamics because of PositionsIterator

### ISSUE THREAD

**Issue by ThatGuy435** [CyclopsMC/IntegratedDynamics#617]
I'm not 100% sure this is Integrated Dynamics, but ID is what is put into the log after the ServerHangWatchdog catches skipped ticks and crashes out the server. I've also run a copy of this server and map without ID/IT for 2 days without a hang, and the version with ID/IT hangs about every 8-16 hours as near as I can tell.

Full crash log is here: https://gist.github.com/ThatGuy435/c4412858a2e1536f08d6f7faee524227

**Comment by rubensworks** [comment]
Not sure what could be going wrong, I'd have to look into it.

**Comment by ThatGuy435** [comment]
I can say that I've tried running the server on both the 32 and 64 bit java executables, with between -Xmx 1024MB and -Xmx 8192MB for memory allocation. Behavior is pretty much identical across all of that spectrum. on Ubuntu 16.04 with OpenJDK 1.8.0_171. I've also tried it across multiple pieces of hardware, both with 16GB phys RAM.

If the map + config files would be helpful I'm more than happy to send them to you. I use the Minecraft Server Control Script to run the server, but that shouldn't have any effect either way.

**Comment by rubensworks** [comment]
This issue shows that there is a fundamental problem in how round-robin transfer mode is implemented in Integrated Tunnels (which is probably what is going on on your server as well).

I'm in the process of rewriting IT significantly, including round-robin mode. I'm putting this issue on hold until the rewrite is done.
