### ISSUE TITLE
[1.12.2][0.11.15] Mechanical squeezer accepting charcoal for pulverized coal

### ISSUE THREAD

**Issue by Kazzamkablam** [CyclopsMC/IntegratedDynamics#618]
#### Question:

Is it intended that mechanical squeezer/squeezer accepts charcoal for making pulverized coal (dustCoal). Every other mod recipe only allows use of regular coal? 

This basically makes it possible to turn charcoal to regular fuel which is usually only allowed to be turned to biofuel or similiar for balance reasons?

**Comment by rubensworks** [comment]
It is intended, but as you say, perhaps I should change this for balancing reasons.
