### ISSUE TITLE
RBE Crash: Omni Directional Part

### ISSUE THREAD

**Issue by artdude543** [CyclopsMC/IntegratedDynamics#619]
#### Issue type:

- :bug: Bug

____

#### Short description:

Heyo! SevTech: Ages dev here! One of our beta tester players was moving from a GC Dimension back to the Overworld, then the game went _blue_ and crashed out. (With the report logged below) If you need more data about their world or what not. I can get the data. But I belive the report contains enough info to track down the hinderence.
____

#### Versions:

- This mod: 0.11.15  
- Minecraft: 1.12.2
- Forge: 14.23.4.2749

#### Log file:

Crash: https://gist.github.com/artdude543/4e063a8657860fff802ffbf038cbfda6

**Comment by artdude543** [comment]
Seems to be related to an update of one of the mods in Beta 2 of the modpack. This is an image of what is at the position of the crash

![](https://i.gyazo.com/9bf2dfb3e16b49c1b0d208b7e4a22d4c.png)

**Comment by rubensworks** [comment]
That's an odd crash. The only reason I can think of that this crash could occur is if the two dimensions (by chance) have non-equal ID parts at exactly the same positions, and dimension-switching causes the issue.

I'll look into it, thanks for reporting.

**Comment by artdude543** [comment]
Yeah, what makes it even weirder. When the player drops back to Beta 1 (of the pack) it does not crash. So either something changed in one of the mods which the ItD blocks are talking too. Or it bugs out when updating the world.

Checking the diff on the mod updates nothing jumps at me, which could have caused the issue. Here is the changelog diff in-case something jumps out at you in regards. https://www.diffchecker.com/z6PeGzdr

<blockquote><img src="https://www.diffchecker.com:20840/static/images/fb-image.png" width="48" align="right"><div><strong><a href="https://www.diffchecker.com/z6PeGzdr">Diff Checker</a></strong></div><div>Diff Checker is an online diff tool to compare text to find the difference between two text files</div></blockquote>
