### ISSUE TITLE
Offset does not work

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedDynamics#620]
#### Issue type:

- :bug: Bug

____

#### Short description:
i try to put offset to -1, so it is offseted down. it writes X

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

just to work.

____

#### Versions:

- This mod: 0.11.16
- Minecraft: 1.12.2
- Forge: 14.23.4.2757

**Comment by rubensworks** [comment]
I need more information, I have no idea what you are referring to.

**Comment by matyklug18** [comment]
I try to offset on player simulator to -1. it errors. But the same occurs in other offsets.

**Comment by rubensworks** [comment]
> it errors

Ok, so what's the error?

**Comment by matyklug18** [comment]
I am not now with the computer,after i come back (after 2 days) i can tell you exact error. Only thing i coud say is that is that big red cross in gui in page with that offset.
