### ISSUE TITLE
Crash with ID 0.11.15

### ISSUE THREAD

**Issue by gchpaco** [CyclopsMC/IntegratedDynamics#621]
#### Issue type:

- :bug: Bug

____

#### Short description:

I was trying to get a visual of a percentage double, and multiplied it I think by an integer and then rounded.  I ought to have used a double, I suspect, but even still.

#### Steps to reproduce the problem:

1. Use ID to read present ember and maximum ember capacity from an Ember Rekindled 1.5 Crystal Cell.
2. Attempt to scale resulting percentage (a double between 0.0 and 1.0) by multiplying by 100 (*not* 100.0) and rounding.
3. Put resulting artifact in a display panel.

#### Expected behaviour:

Red X and a type error at the worst.
____

#### Versions:

- This mod: 0.11.15
- Minecraft: 1.12.2
- Forge: 14.23.4.2718

#### Log file:

[crash-2018-08-22_20.58.16-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/2313153/crash-2018-08-22_20.58.16-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

Another number type error it seems, I thought those were a thing of the past...
