### ISSUE TITLE
crash on stopping crafting job.

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedDynamics#622]
#### Issue type:

- :bug: Bug

____

#### Short description:

crash

#### Steps to reproduce the problem:

1. made RefinedStorage network
2. connect it to integrated dynamics network with inventory writer
3. put empty card to cancel all crafting jobs

#### Expected behaviour:

to do not crash

____

#### Versions:

- This mod: 0.11.16
- Minecraft: 1.12.2
- Forge: 14.23.4.2757
- Refined Storage: 1.6.3

#### Log file:
https://pastebin.com/sxiWMDNb

**Comment by matyklug18** [comment]
using any of things in inventory writer cause same crash.

**Comment by rubensworks** [comment]
It's getting really hard for me to maintain this RS integration. Raoul keeps breaking API compat.
Perhaps I should just remove the integration...

**Comment by matyklug18** [comment]
is there way to integrated it insetad with AE2?

**Comment by rubensworks** [comment]
Yes, but it required implementation effort. It has been on my todo-list for almost two years.
