### ISSUE TITLE
Rendering crash, client.

### ISSUE THREAD

**Issue by Beelzaboss** [CyclopsMC/IntegratedDynamics#623]
#### Issue type:

- :bug: Rendering

____

#### Short description:

Client crashes as soon as it comes near the specific location.

#### Steps to reproduce the problem:

Basic setup build

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: latest
- Minecraft: 1.12.1
- Forge: Latest

#### Log file:

https://pastebin.com/index/3pjL7iyi

**Comment by rubensworks** [comment]
Please fill in the issue template properly, and don't refer to mod version _latest_.

**Comment by rubensworks** [comment]
Also, you are clearly not using _latest_, you are using 0.11.12, while 0.11.16 is already out.
