### ISSUE TITLE
IsNull on Any will crash (and corrupt) world

### ISSUE THREAD

**Issue by 8uurg** [CyclopsMC/IntegratedDynamics#625]
#### Issue type:

- :bug: Bug

____

#### Short description:

Applying IsNull to the head of the list generated by an empty delayer, will crash the game and corrupt the world. 
It seems like an arbitrary type (Any) does not have the IsNull interface implemented for it.

#### Steps to reproduce the problem:

1. Have a delayer, a variable store and a display.
2. Create a variable for the delayer.
3. Create a variable that takes the head of the list of this delayer.
4. Create a variable that checks if this head is null.
5. Placing this last variable - given that all the other variables are in a variable store in the network - in the display will crash the game.

#### Expected behaviour:

Detects when it has an 'error' value, or atleast gives an error and does not crash the game.

____

#### Versions:

- Modpack (Sevtech Ages): 3.0.8
- This mod: 0.11.12 (?)
- Minecraft: 1.12.2
- Forge: forge-14.23.4.2707

#### Log file:

Partial, only with the crash relevant (including exception and stacktrace) to this mod in it. Other stuff starts failing creating an 
Reproducing caused a 3.17 MB log (after manually stopping, it grows quite rapidly with a lot of the same exception over and over again):

https://gist.github.com/8uurg/a09ee61935334a3853b282b6f2021141

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
FYI, you can start ID in safe-mode via a config-file setting, to remove the offending block.

**Comment by 8uurg** [comment]
The modpack has backups set up, and I did that after idling for a while.
I recovered the backup and barely lost anything (just crafting a few items), so no worries about that.
