### ISSUE TITLE
Proxy stops working when picked up and placed 

### ISSUE THREAD

**Issue by Aquahatsche** [CyclopsMC/IntegratedDynamics#626]
#### Issue type:

- :bug: Bug

____

#### Short description:

Proxy isn't working anymore when picked up and replaced. The Network doesn't recognize the placed Proxy. 

I checked out the repo and made some tests:

- NBT has correct proxy ID
- In org.cyclops.integrateddynamics.core.network.PartNetwork.proxyPositions are the positions for proxies but incremented.

Going up the stack trace, it looks like the id is correctly written to the chunk but after it is read from 
the world in org.cyclops.cyclopscore.helper.TileHelpers.getSafeTile the id is incremented.

#### Steps to reproduce the problem:

1. Place a Proxy, a cable, a display panel and a Redstone-Reader
2. Encode a Variable Card to read the value from the Redstone-Reader
3. Create a Proxy from the previously encoded card
4. place the new card in the display panel -- it works --
5. dig up the proxy and place it
6. place the dropped card in the proxy

Also re-encoding doesn't help

#### Expected behaviour:

The Proxy works as expected like the other parts from the mod.
____

#### Versions:

- This mod: 0.11.14 & 0.11.16 (at least. I tested only those)
- Minecraft: 1.12.2
- Forge: 14.23.1.2555 & 14.23.4.2739

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
