### ISSUE TITLE
Crash when looking at a display panel

### ISSUE THREAD

**Issue by ComplainingSkelzie** [CyclopsMC/IntegratedDynamics#627]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I look at a display panel, the entire screen goes sky blue for a while and then the game crashes.

#### Steps to reproduce the problem:

1. Place down some logic cable.

2. Place a display panel on the cable.

3. Crash.

#### Expected behaviour:

I expected not to crash when using a display panel.

____

#### Versions:

- This mod: 0.11.16
- Minecraft: 1.12.2
- Forge: 14.23.4.2760

#### Log file:

https://pastebin.com/Y5eBzgQ9

**Comment by rubensworks** [comment]
This appears to be the same (strange) problem as #624.

Does this always happen?

Can you try reproducing this without any other mods installed?

**Comment by ComplainingSkelzie** [comment]
It does always happen, I've tried multiple times on the same world and multiple times on multiple fresh saves. I cannot reproduce without any other mods installed.

**Comment by rubensworks** [comment]
Really strange...

I'll try to look into it later this week.

**Comment by Suiadan** [comment]
Encountering the same problem, and it seems to go away when I disable integrated tunnels. Tried backdating integrated tunnels a few versions, crash still occurred with same stack trace. Disabling integrated tunnels entirely seems to fix the problem...

Log file:
https://pastebin.com/3vvq9KMj

Integrated Dynamics: V0.11.16
Integrated Tunnels: V1.5.2, V1.5.3, V1.5.4, V1.5.5, V1.5.6
Minecraft: 1.12.2
Forge 14.24.4.2758



<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/3vvq9KMj">---- Minecraft Crash Report ----  // Shall we play a game?    Time: 2018-09-08 1 - Pastebin.com</a></strong></div></blockquote>

**Comment by wesserboy** [comment]
I encountered the same problem. I have tried to reproduce it with the least amount of mods installed, and it seems to happen when both FoamFix and the one probe are installed. Disabling either one of those mods fixed it in my test instance. 

The log: https://pastebin.com/4KxXfzjr

**Comment by Ruukas97** [comment]
Glad to see this has been fixed (It was really gamebreaking for me, and I was already worrying how I could open the world to fix it without crashing).

Updating now!

**Comment by rubensworks** [comment]
@Zerotiger Be sure to let me know if this fix has undesired side-effects, as I wasn't able to reproduce this problem myself.
