### ISSUE TITLE
Tileable Display Panel

### ISSUE THREAD

**Issue by ModestTG** [CyclopsMC/IntegratedDynamics#629]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I think it would be very beneficial to allow the Display Panel to tile across multiple blocks when placed adjacent to each other on a logic cable. This would be helpful for being able to see lists of items, Large NBT tags, make nice displays, ect. 

A long term feature request would be to edit some display features on the Display Panel. For example, changing text option (position, size, color, font, ect.).

Love the mod and appreciate the continued development!

**Comment by rubensworks** [comment]
Thanks for the issue. However, this has been suggested a while ago already (#273), and has been on my todo-list ever since. I hope to one day actually implement it, but there are a bunch of more pressing issues to be resolved.

I'm closing this in favor of #273.
