### ISSUE TITLE
cant't find exist ID in network

### ISSUE THREAD

**Issue by zomb-676** [CyclopsMC/IntegratedDynamics#631]
- :bug: cant't find exist ID in network

____
![snipaste_2018-10-03_21-32-04](https://user-images.githubusercontent.com/26162862/46413788-4d212c00-c754-11e8-9c26-bf0c4fc96239.png)

![image](https://user-images.githubusercontent.com/26162862/46413808-5a3e1b00-c754-11e8-925e-ff46ffd79807.png)

#### Versions:
- This mod: IntegratedDynamics-1.12.2-0.11.17
- Minecraft: 1.12.2
- Forge:-1.12.2-14.23.4.2760

**Comment by zomb-676** [comment]
![image](https://user-images.githubusercontent.com/26162862/46414301-6d051f80-c755-11e8-8854-9a0fc823059d.png)

**Comment by rubensworks** [comment]
It sounds like your reader and part are not in the same network.

Could you show one screenshot showing both of them as part of the same network?

What happens when you reset the network (=add+remove a random cable)?

**Comment by zomb-676** [comment]
![image](https://user-images.githubusercontent.com/26162862/46420292-4b5e6500-c762-11e8-9e24-fed15bb10e74.png)

this happened after the sever restart
this will be fine after the Block reader is replaced
the picture is intercepted after that
but this is troubing

**Comment by rubensworks** [comment]
> this happened after the sever restart

Ah, that's important information. I'll do some investigation soon.

**Comment by rubensworks** [comment]
I've had no luck in reproducing this unfortunately.

Were you able to see anything special pop up in your (server) console when encountering this issue?

Do you also have the same problem on other locations in your world?

Be sure to let me know if there's anything else you could tell me.
