### ISSUE TITLE
Menril leaves not displaying a texture as an item

### ISSUE THREAD

**Issue by bloorocksDotD** [CyclopsMC/IntegratedDynamics#633]
#### Issue type:

- :bug: Bug

____

#### Short description:

Menril leaves that are picked up no longer display a texture in the inventory, any that were in chests still have a texture, and they have a texture when placed.
#### Steps to reproduce the problem:

1. ... Break a menril leaf w/ silk touch

#### Expected behaviour:

For it to have a texture
____

#### Versions:

Stoneblock modpack, up to date as of 10/5/2018 6pm EST
- This mod: 1.12.2-0.11.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2760

**Comment by rubensworks** [comment]
I fixed this a long time ago for #76. Perhaps something has changed in Forge...

Are you sure you're not using a third-party mod to break the leaves? If so, that might be the problem.

**Comment by bloorocksDotD** [comment]
Sorry for the late reply, forgot to check my notifs this morning. The leaves were broken with an Emerald All-In-One-Tool with silk touch, soulbound, eff 5, unbreaking 3, and mending enchantments on it. I will re-launch modded shortly and see if I can replicate the issue today as well. There was also another person on "Modded Minecraft" discord server who was experiencing the same issue as of yesterday, I will try to contact them and see if I can get their version information + what they were breaking their leaves with.

**Comment by crayzeedude** [comment]
Also had this happen. Broken with the Actually Additions Drill, Speed 1, Speed 2, and Silk Touch upgrades installed. Minecraft 1.12.2, Forge 14.23.4.2760, Integrated Dynamics 1.12.2-0.11.17, as well as Actually Additions 1.12.2-r140 if that matters

**Comment by bloorocksDotD** [comment]
Update: So I can't figure out what caused the block id to change(still trying some stuff), but the leaves that become texture-less are 7690:2 instead of the normal 7690:0 that they should be

Edit: Update 2(5 minutes later) from what I can see in my testing the issue stems from breaking one of the blocks with a tool that has silk touch on it(not only modded tools, got it to occur with vanilla minecraft pickaxe w/ just silk touch on it) 
step 1: place a line of menril leaf blocks that are touching one-another
step 2: Break one of the blocks on the end of the line with a tool that has silk touch on it
step 3: Look at the next block in line and see that its blockdata has not changed yet
step 4: break that next block in line (still w/ silk touch tool) and it becomes textureless and the blockdata changes from 7690:0 to 7690:2

Extra notes: It seems to be a problem just with breaking two menril leaf blocks in a row that were touching one another with a silk touch tool.
If you break one block on either side of the line neither of them will be glitched, but if you then break the leafs that were touching those blocks those ones will be.
If you break the first block with a silk touch tool and the second block with shears the second block is perfectly fine.
Placing a glitched leaf block will turn all other adjacent leaf blocks into the same glitched 7690:2 id & texture
Placing a glitched leaf block and then breaking it with shears will revert it to the normal texture & 7690:0 block ID

**Comment by rubensworks** [comment]
> (not only modded tools, got it to occur with vanilla minecraft pickaxe w/ just silk touch on it

Ok, if it occurs with vanilla, then it's clearly a problem in ID. Will try to fix it soon. Thanks for the info.

**Comment by bloorocksDotD** [comment]
:D <3
