### ISSUE TITLE
Snow settles on cables

### ISSUE THREAD

**Issue by DaedalusGame** [CyclopsMC/IntegratedDynamics#634]
#### Issue type:

- :bug: Bug

____

#### Short description:

![grafik](https://user-images.githubusercontent.com/9559216/46565661-d6319200-c911-11e8-8123-f62306944f6b.png)
Cables don't appear to implement `Block::getBlockFaceShape`. This means that they default to all sides being solid, causing numerous funky artifacts like torches, levers and snow being placeable on them, with a massive airgap, naturally.

#### Steps to reproduce the problem:

1a. Place cables in a snowy biome in a snowstorm
1b. Place cables
2b. Place torch on cables

#### Expected behaviour:

Snow to not settle on cables in a particularly ugly fashion

____

#### Versions:

- This mod: 0.11.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2760

#### Log file:

N/A

**Comment by rubensworks** [comment]
Oh, is `getBlockFaceShape` a new thing? Never heard of it before.

**Comment by rubensworks** [comment]
Actually, I remember there being another method for that. Because I'm pretty sure you could not place levers on cables before, unless that cable had a part on that side.

**Comment by DaedalusGame** [comment]
`getBlockFaceShape` was added either in 1.11 or 1.12, and yeah a lot of mods seem to have missed it. Before levers and such looked for `isSideSolid`. FaceShape actually handles even more than just what you can place on a block, it's also for connecting fences, walls and panes together.
