### ISSUE TITLE
Generator eats buckets

### ISSUE THREAD

**Issue by AggressivePear** [CyclopsMC/IntegratedDynamics#635]
#### Issue type:

- :bug: Bug

____

#### Short description:

When putting an empty bucket into the Generator and the Generator is attatched to an energy network and not currently producing power, the bucket disappears. 

#### Steps to reproduce the problem:

1. Set down generator and battery 1 block away from each other.

2. Connect them with any power cable.

3. Put bucket in the generator.

#### Expected behaviour:

What does happen: The bucket dissapears

What should happen: The bucket stays in the inventory, allowing players to take it out.

____

#### Versions:

- This mod: 0.11.17
- Minecraft: 1.12.2
- Forge: 2760

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
