### ISSUE TITLE
Interface to make lists of operators is broken

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#641]
#### Issue type:

- :bug: Bug

____

#### Short description:

When making lists of operators in the logic programmer, the GUI looks all wrong, and things you need to click on are often covered up.

#### Steps to reproduce the problem:

1. Go to "List" in the logic programmer
2. Set the type of the list to "Operator"
3. Click `+`.
4. Type in the name of some operator and pick it from the dropdown.
![2018-11-03_19 21 53](https://user-images.githubusercontent.com/16061266/47958233-e5057600-df9d-11e8-8aea-4942ca0722fc.png) Note that the operator's name is completely obscured.
5. Click `+` again.
6. Type in the name of some other operator and pick it from the dropdown.
![2018-11-03_19 21 59](https://user-images.githubusercontent.com/16061266/47958241-05353500-df9e-11e8-99df-28e1e7a47a3f.png) Note that although the operator's name is now visible, the `+` button and the buttons to navigate between list elements are now completely obscured.

#### Expected behaviour:

All elements should remain fully visible while creating a list of operators.

____

#### Versions:

- This mod: Git version 7efc56d
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

#### Log file:

Contains nothing relevant

**Comment by rubensworks** [comment]
As discovered in #739, also occurs for lists of recipes.

**Comment by ReiDaTecnologia** [comment]
It's a shame 1.12.2 is doomed to have this nasty bug for eternity as 1.12.2 is probably not supported anymore :'(

**Comment by Jack-McKalling** [comment]
Retested with same results for:

#### Versions:



- This mod: 1.9.4
- Core: 1.11.9
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
This one took my only nearly 5 years 😅
