### ISSUE TITLE
With what mods machine,entity and inventory writer?

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedDynamics#643]
#### Issue type:

- :question: Question

____

**Comment by rubensworks** [comment]
* Forestry
* IC2
* IE
* RS
* Signal
* TCon
* Thaumcraft

**Comment by matyklug18** [comment]
i installed all of them and it still says on machine writer no aspects avalibe.

**Comment by matyklug18** [comment]
btw what these writers does to what blocks?

**Comment by rubensworks** [comment]
It's possible that the machine writer has no aspects as the moment. There might be at some point in the future.

> btw what these writers does to what blocks?

I don't understand you question.

**Comment by matyklug18** [comment]
With what blocks to use it? For example, rs writer is used with redstone.

**Comment by rubensworks** [comment]
You can see that in the description of each aspect.

**Comment by matyklug18** [comment]
What is aspect?
