### ISSUE TITLE
Omni directionally connected network breaks up into disparate networks when modifying/extending the same network upon world reload

### ISSUE THREAD

**Issue by Fatmice** [CyclopsMC/IntegratedDynamics#646]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. Create a new omni-directionally connected network, say for energy.  Make sure it is working so that the sources and sinks are pushing and pulling energy.
2. Have some extra omni connectors created with the same id.  Save world and leave
3. Reload world.
4. Existing omni-directionally connected network should still be functioning.
5. Add a new node to this network with the omni connectors crafted from before.
6. Observe that this new node is all by itself and disconnected from the rest of the omni-directionally connected network even though the new one shared the same id.
7. Break and replace the omni connector serving the energy sources.
8. Observe that the sources are now all alone and soon all of the sinks will run out of power when they are all on the same network id...

#### Expected behaviour:
This really shouldn't happen?

____

#### Versions:

- This mod: 1.12.2-0.11.17
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

#### Log file:
Can provide world + config + mods on request where this is happening.

**Comment by rubensworks** [comment]
That shouldn't happen indeed, will look into it.

**Comment by rubensworks** [comment]
I can't seem to reproduce this on the latest release (1.0.1). I tried multiple things, including your steps, but I can't seem to make it break.

@Fatmice Could you retry it with the latest version and see if you can reproduce it? (preferably with only ID (and optionally IT) installed)

Btw, how did you obtain your extra omni connectors? Did still they show the same group id in the tooltip after copying?

**Comment by Fatmice** [comment]
I will try later today.  Extra connectors were created by copying the source.  Yes they had the same group id in the tooltip.

**Comment by rubensworks** [comment]
> Extra connectors were created by copying the source.

In creative-mode? Or via the crafting table copy recipe?

(both _should_ work, but just to make sure I replicate it correctly)

**Comment by Fatmice** [comment]
I remember I did both methods.  The results were stackable.

**Comment by Fatmice** [comment]
Okay I've tested it in several ways, your new version fixed the problem...whatever you did.

**Comment by rubensworks** [comment]
Great!

Be sure to let me know if you (or anyone else) would encounter this problem in the future.
