### ISSUE TITLE
"NETWORK CORRUPTED!" breaks all networks on server restart

### ISSUE THREAD

**Issue by Unbox101** [CyclopsMC/IntegratedDynamics#648]
- :bug:
Most of the time when rejoining a public server after it's restarted all of my integrated dynamics networks become corrupted.

-Description
I haven't been able to consistently repeat this bug on a private server but it appears to happen 75-85% of the time on a public server only after a restart. The server restarts and then every integrated dynamics network is corrupted and not functioning. They can be in multiple or just one chunk, it doesn't matter.

-Steps
On a public server all it takes is a restart. This bug happens every time the public server that I played on restarted.

-Expected Behavior
What I expected to happen is to rejoin the server and have all of my integrated dynamics networks to be working as I left them but they are all shut off. The only way to fix the corruption is to break and replace a cable for every network.

-Version info
The version of Integrated Dynamics is 0.11.18
The version of Minecraft is 1.12.2
The version of Forge is 14.23.5.2768

-Log
I can't repeat this bug on a private server so i don't have a log

**Comment by rubensworks** [comment]
Thank you for your issue, but could you use the proper issue template instead please?

Any server (crash) logs you have would help as well.

**Comment by Unbox101** [comment]
> 
> 
> Thank you for your issue, but could you use the proper issue template instead please?
> 
> Any server (crash) logs you have would help as well.

**Comment by Unbox101** [comment]
I hope I updated the issue more to the format of the template? Sorry for the closing of the issue and opening. I am new to this website, I'm not sure how it works, but I'm just trying to help? I'm trying to get a log.

**Comment by rubensworks** [comment]
> I can't repeat this bug on a private server so i don't have a log

Yeah, I can't do much without a log though.

**Comment by rubensworks** [comment]
Let's wait and see until someone else has a log.

**Comment by comical-uk** [comment]
I have this issue also. It has occurred on 2 different server networks. I believe they are both using sponge and some plugins which is why I am unable to replicate it on an 'as is' download.

They are unfortunately unwilling  to give out their logs, which, while I completely understand their position as they may contain some sensitive information, it is frustrating in this instance

it only seems to affect networks with ticking interfaces (eg import/export) and for me it occurs every time the server is restarted. 

however, I have not been able to test it on any versions newer than 0.11.18 &  1.5.6

**Comment by rubensworks** [comment]
> they are both using sponge and some plugins which is why I am unable to replicate it on an 'as is' download.

That is useful information to have. Spongeforge is probably changing/breaking some things we rely on during network serialization. Not sure if I'll be able to fix this on my end then.

> They are unfortunately unwilling to give out their logs

That's too bad indeed. No chance on giving out anonymized logs?

**Comment by zyojv** [comment]
So I played on a german server network called MyFTB.de and the same issue occurred. I fixed it by just replacing the variable storage block.

**Comment by dannyr-git** [comment]
Confirm this happens on Skyfactory 4 4.2.0 and 4.2.2 across multiple public servers.  Very hard to reproduce purposefully ... but it happens ALL the time.

**Comment by rubensworks** [comment]
@Orichlol As mentioned multiple times before in this issue, there's nothing I can do without logs.

**Comment by Hapseleg** [comment]
Here's what I'm getting (enigmatica 2 expert)
ID is newest version for 1.12.2 so thats "IntegratedDynamics-1.12.2-1.1.11"

`[01:18:42] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_321]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.NullPointerException
	at org.cyclops.integrateddynamics.core.inventory.container.ContainerPartSettings.onUpdate(ContainerPartSettings.java:145) ~[ContainerPartSettings.class:?]
	at org.cyclops.cyclopscore.network.packet.ValueNotifyPacket.actionServer(ValueNotifyPacket.java:67) ~[ValueNotifyPacket.class:?]
	at org.cyclops.cyclopscore.network.PacketHandler$HandlerServer.lambda$onMessage$0(PacketHandler.java:156) ~[PacketHandler$HandlerServer.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

I got it working again but I had to remove everything, and by everything I mean even the cables :(

**Comment by CynderR** [comment]
This happened to me right after my actual server ran out of storage.
