### ISSUE TITLE
Crash: Entity into Item NBT via Get or Default.

### ISSUE THREAD

**Issue by VT-14** [CyclopsMC/IntegratedDynamics#652]
#### Issue type:

- :bug: Bug

____

#### Short description:

I accidentally used "Get or Default" to feed an Entity into the Item NBT command, and crashed when putting that variable card into a Display Panel.  The Default option given actually was an Item.  I replicated this crash in a single player test instance with only Integrated Dynamics and JEI (and dependencies).

#### Steps to reproduce the problem:

1. Place an Entity Reader, Variable Store, and Display Panel
2. Get a list of Entities from the Entity Reader (I dropped a single Stone in front of it)
3. Use a Logic Programmer to make an Item Variable Card (I used Stone).
4. Use a Logic Programmer to make an Integer 0 variable card.
5. Use "Get or Default" (List Get Or Default).  Input the List, the 0, and the item (stone).
6. Use Item "NBT()" (Item Item NBT) with the above's output.  Place this card in the Display Panel and the rest in the Variable Store.

#### Expected behaviour:

My silly mistake to get an error rather than a crash.  (sidenote; my spellchecker is saying there isn't a "u" in behavior).

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.18
- Minecraft: 1.12.2
- Forge: 14.23.5.2784

#### Log file:

Crash: https://gist.github.com/VT-14/0329ef53bb3a18040ecc80cf1586ae8d

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
This will be fixed in the next release thanks to ec049fb7f28e6a6f28be44b9d5d3976cbb84f7be.
