### ISSUE TITLE
 Ore dictionary chest in recipes

### ISSUE THREAD

**Issue by LemADEC** [CyclopsMC/IntegratedDynamics#658]
#### Issue type:
- :bug: Bug

____

#### Short description:
recipes are forcing vanilla chest, preventing integration with other mods.
Consider using 'chest' or 'chestWood' ore dictionary entries instead to support other mods.

#### Steps to reproduce the problem:
Craft with chests from Quark.

#### Expected behaviour:
Compatibility!
____

#### Versions:
- This mod: 1.12.2-0.11.18
- Minecraft: 1.12.2
- Forge: n/a

**Comment by rubensworks** [comment]
Huh, I thought we already did this,
but it looks like the variable transformers are indeed forced to use the vanilla chest instead of the oredict.
