### ISSUE TITLE
Craftweaker Support Potentially Does Not Allow NBT Data?

### ISSUE THREAD

**Issue by Darkosto** [CyclopsMC/IntegratedDynamics#659]
Hey Kroeser!

I'm having some trouble with my custom Squeezer recipes working properly. I have a set of outputs that are determined via NBT tags and the recipes look correct in JEI but the Squeezer only produces the result of the very first entry no matter the item used. The first link is my scripts, Resource Hogs is the recipe set with the issue: https://pastebin.com/PakAvD8h starting on line 12. Any Resource Hogs Bacon inserted into the Squeezer produces Prismarine, the top entry.

This next file is the zenClass script we use to simplify our recipe scripts a bit: https://pastebin.com/k8r6Hgvi

MC: 1.12.2
Forge: 2796
Integrated Dynamics: 1.12.2-0.11.18
Cyclops Core: 1.12.2-0.11.11

Thanks for checking into this, cheers!
Darkosto

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
Ok, this should be fixed now, the following scripts are examples that will work:

```
mods.integrateddynamics.DryingBasin.addRecipe(<minecraft:potion>.withTag({Potion:"minecraft:swiftness"}), null, <minecraft:prismarine_crystals> * 1, <liquid:water> * 100, 10);
mods.integrateddynamics.DryingBasin.addRecipe(<minecraft:potion>.withTag({Potion:"minecraft:night_vision"}), null, <minecraft:soul_sand> * 1, <liquid:water> * 100, 10);
```

This fix will be part of the next release that should come out in a couple of days.
