### ISSUE TITLE
nuclearcraft error integrated dynamics:part Data

### ISSUE THREAD

**Issue by TamePeak** [CyclopsMC/IntegratedDynamics#662]
#### Issue type:

Bug

#### Short description:

When trying to use Nuclear Craft ports, i get an error saying integrateddynamics:partData.
From AllTheMods 3

#### Steps to reproduce the problem:

Reproduced when i place a reactor port block

#### Expected behaviour:

Hoping to not have this error and be able to use the port

#### Versions:

- This mod: Integrated Dynamics 0.11.9 ,NuclearCraft 2.12c
- Minecraft: 1.12.2
- Forge: 14.23.1.2560221

#### Log file:
Can not get log file from server

**Comment by rubensworks** [comment]
Where do you get this error? If you can't get the logs, can you show a screenshot of the error?

**Comment by rubensworks** [comment]
Also, try updating ID to 0.11.18, the bug may already be resolved.

**Comment by TamePeak** [comment]
Yah i can send you a screen shot but may take a minute.

**Comment by TamePeak** [comment]
![capture](https://user-images.githubusercontent.com/46401701/50726512-e81efe80-10d3-11e9-9708-94f9cab7ce3a.PNG)

**Comment by TamePeak** [comment]
I updated cyclops core and integrated dynamics and still having the same issue.

**Comment by TamePeak** [comment]
I found the issue i had to update NuclearCraft to the 2.12k Version. Thanks for the help tho and recommendations.

**Comment by rubensworks** [comment]
Ok, thanks for letting me know!
