### ISSUE TITLE
Item exporters stop working

### ISSUE THREAD

**Issue by Maximal-am** [CyclopsMC/IntegratedDynamics#663]
#### Issue type:

- :bug: Bug
____

#### Short description:

I have a lot of short networks that consist of one item interface and one or several item exporters.
Some exporters sometimes stop exporting items or do it with a very big delay (tens of seconds). Adding or removing a cable usually helps.

#### Steps to reproduce the problem:

I don't know reliable way to reproduce it but it happens quite often and in different networks.

____

#### Versions:

- This mod: 1.12.2 - 0.11.18
- Minecraft: 1.12.2
- Forge: 14.23.5.2784

**Comment by rubensworks** [comment]
This will be the same problem as CyclopsMC/IntegratedTunnels#138.

I have rewritten IT item transfer, which should solve this issue. So expect a new release very soon :-)
