### ISSUE TITLE
Multi-variable proxy

### ISSUE THREAD

**Issue by yurikus** [CyclopsMC/IntegratedDynamics#667]
#### Issue type:

- :heavy_plus_sign: A proxy block that could hold more than one variable, would be appreciated. Maybe introduce a ProxyStore block or change Proxy to hold variables linearly in similar fashion as aspects are displayed. Arrange variable slots horizontally and put them in a list. Have each list entry be conceptually a proxy.

**Comment by rubensworks** [comment]
Thanks for the suggestion. This has however been suggested before already, so I'm closing this in favor of #667.
