### ISSUE TITLE
Suggestion: Add way to get difference in a variable over an amount of ticks.

### ISSUE THREAD

**Issue by white-matter** [CyclopsMC/IntegratedDynamics#67]
For measuring the rate at which you get items or generate power, if this is already a feature then I apologize.

**Comment by rubensworks** [comment]
I've been tinkering with an idea that would enable things like this. This will probably be for next release! :-)

**Comment by scollenburg** [comment]
FWIW, in my Reactor control LUA I use a "fast" slope estimation algorithm that uses fixed coefficients to estimate slope using 1 add & 1 multiply per sample & 1 divide. It's not a precise as the classic least squares algorithm, but it's very fast & the estimates are close enough to build useful logic.

My specific use is to watch the reactor & wait for delta RF/tick to stabilize, so I actually run the estimate twice -- once to get the slope, and once to get the acceleration. Once acceleration drops below 0.25% of the slope I consider it stable.

**Comment by josephcsible** [comment]
Is this resolved by the Delayer?

**Comment by rubensworks** [comment]
Ah yes, this was exactly the reason why I implemented that. So this issue can be closed now. Thanks for bringing it to my attention @josephcsible :-)
