### ISSUE TITLE
1.0 Issues

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/IntegratedDynamics#671]
#### Issue type:

- :bug: Bug

#### Short description:
- [ ] The Generator uses fuel, but doesn't generate power
- [ ] The progress bars instantly fill up when the recipe is done
- [ ] The power bar looks empty until the machine is completely full on power (probably connected to the previous one)

#### Steps to reproduce the problem:
1. Place down a Generator
2. Put fuel in it
------------------------------------------
1. Place down a Mechanical Squeezer
2. Power it
3. Put Cobblestone in it
(of course it works for all recipes and the Mechanical Drying Basin as well

#### Expected behavior:
- The Generator to generate power as it uses fuel
- The progress bars to steadily fill up as the recipe is being done
- The power bar to steadily fill up as the machines gain power

#### Versions:
- This mod: 1.0.0
- Common Capabilities: 2.0.0
- Cyclops Core: 1.0.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2806

**Comment by rubensworks** [comment]
Strange that the generator broke, will look into it.

**Comment by rubensworks** [comment]
The first thing was caused by an API change in ID, and the two other issues were due to rounding errors in CyclopsCore. Will prepare new releases for them in a bit.
