### ISSUE TITLE
Question - Does this work for transferring items to Colossal 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedDynamics#672]
#### Issue type:

I want a way to take items from and to colossal chest with ducts or hoppers

____

**Comment by P3rf3ctXZer0** [comment]
In the future adding colossal chests as an optional dependency is a dead giveaway.

**Comment by GreyMario** [comment]
With only _Integrated Dynamics_, no. Add _Integrated Tunnels_ to provide powerful pipe-like functionality to _Integrated_'s potential.

The _Integrated_ suite is modular, so users can add only those extra feature sets they want to use.


Colossal Chests expose their inventory capability through an Interface block in the chest's construction or through the Core block. You can use any mod to push or pull to them, but to use an _Integrated_ solution, you need _Integrated Tunnels_.

**Comment by rubensworks** [comment]
Indeed, like @GreyMario, you'll need to have Integrated Tunnels installed for this.

FYI, Colossal Chests has even been optimized to work well together with IT.
