### ISSUE TITLE
Button/checkbox for meta/ore/nbt in logic programmer for recipes

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedDynamics#675]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Make a set of buttons or checkboxes that allows the player the use of OreDict, meta, or nbt in a recipe, instead manually going and selecting each square.  This would make it simple for the player and less prone to crash. 

Kind of like this
Button/Checkbox:Match OreDict       Button/Checkbox: Match Meta           Button/Checkbox:  Match NBT

**Comment by rubensworks** [comment]
Should be done in the latest version
