### ISSUE TITLE
Recipe making Crash

### ISSUE THREAD

**Issue by Fortist** [CyclopsMC/IntegratedDynamics#676]
I was adding a simple crafttweaked recipe and got this crash
https://pastebin.com/jEc8fTD4

I had set every input slot into the oredict slot, added the four sticks in a 2x2 and then went to add the output item where it crashed on clicking it in.

Version 1.0.1

**Comment by rubensworks** [comment]
Ah, it looks like empty slots will crash when the oredict type is set. Should be an easy fix.

**Comment by rubensworks** [comment]
Fixed in 32573a26f79434ca60c6510df942c2ea12a226bd
