### ISSUE TITLE
Energy Battery dosent output correctly when full

### ISSUE THREAD

**Issue by Freebi85** [CyclopsMC/IntegratedDynamics#678]
#### Issue type:

- :bug: Bug

____

#### Short description:

The problem with a full loaded energy battery is that when a source is connected, it doesn't let out more than it can get. If you disconnect input, the battery will output at maximum speed.
#### Steps to reproduce the problem:

1. Use a Full Energy Battery 
2. put a low voltage solar panel on it (or quivalent) (4RF/FE/t)
3. try to trasnfer energy in a empty battery

#### Expected behaviour:

____

#### Versions:

- This mod: 1.0.2
- Minecraft: 1.12.2
- Forge: .2807

**Comment by rubensworks** [comment]
I don't fully understand the issue.

What transfer rate do you experience when the battery is full vs non-full?

**Comment by Freebi85** [comment]
For example, if there is an 8FE/t solar Flux reborn solarpanel on the battery and the battery is full then only 8 FE/t will be output. Without an incoming energy source, 2000 will be output or what you specify in the configs.

**Comment by rubensworks** [comment]
Yeah, I can't reproduce this at all, transfer rate is 2000 fe/t at all times, independent of the input rate.
I tried by exporting energy using IT and by applying a redstone signal, both work fine.

Could you share a more detailed step-by-step guide to reproduce this, preferably with just ID+IT installed. (A video would even be better :-) )
