### ISSUE TITLE
missing ores support for the Squeezer

### ISSUE THREAD

**Issue by 0Navis0** [CyclopsMC/IntegratedDynamics#68]
It seems that the Squeezer doesn't support all the ores. It would be nice if it added a support for Substratum, TechReborn, Mekanism ores like Zinc, Aluminium, Chromium, Osmium, Tungsten, Titanium, Bauxite, Galena... and BiomeOPlenty gems like Ruby, Sapphire, Peridot...

**Comment by rubensworks** [comment]
True, I should update the list of supported ores, many new mods have been updated to 1.8+ since I first created that list.

**Comment by fullforceofpower** [comment]
I can't squeeze sandstone for some reason.

**Comment by rubensworks** [comment]
@fullforceofpower Do you see the recipe in JEI?

**Comment by Barhandar** [comment]
>True, I should update the list of supported ores, many new mods have been updated to 1.8+ since I first created that list.

It would be welcome if it was automatically generating list. Something like "if this block is oreX and X is not blacklisted, search the mod the block is from for dustX, if not found use the first item in that oredict".

**Comment by ShelLuser** [comment]
Just sharing my 2 cents: I'm not a fan of this system, for the simple reason that it doesn't add up from a gameplay perspective. Squeezing wood (which is a softer material than stone) to get some kind of fluid out of it actually makes sense; it could even be doable in real life (to a certain extend). But it doesn't really make sense for (stone) ores; you can't squeeze stone get dust out of it, though you could grind it.

I know the mechanic adds up from a tech perspective, but I think gameplay balance should be important too, and right now I think this is a little bit overpowered.

So I'd like to add to this suggestion: why not require an upgrade for the squeezer? Maybe to change it from a squeezer into a squasher? Nothing too excessive (I.D. is pretty low-tier accessible afterall), so maybe craft some kind of extension using a combination of stone with an iron ingot which can then be applied to the squeezer to turn it into a squasher?

As said: just my 2 cents.

**Comment by rubensworks** [comment]
@ShelLuser I don't think the ore recipes are too overpowered. The Squeezer is still a manual process, which is quite intensive for the player, and automation is not trivial.

What I _could_ do though, is making the ore recipes more difficult, which would require the player to jump more on the Squeezer, which would also be more realistic.
I won't make any promises if I'll implement this, I have a lot of other more interesting things I'd like to implement first.

**Comment by ShelLuser** [comment]
Fully understandable, as said: just my 2 cents :)  thanks for your comment!

**Comment by rubensworks** [comment]
Should be resolved now
