### ISSUE TITLE
Server crash after update from 0.11.18 to 1.0.2

### ISSUE THREAD

**Issue by xoxfaby** [CyclopsMC/IntegratedDynamics#680]
#### Issue type:

- :bug: Bug

____

#### Short description:

Server crashes on startup. If set to safe mode it will launch but after turning safe mod off there were some issues I couldn't figure out yet with fluids not going where they should. Upon relaunching it crashed again the same way. 

____

#### Versions:

Before:
ID: 0.11.18
IT: 1.5.6

After:
ID: 1.0.2
IT: 1.6.2

- Minecraft: 1.12.2
- Forge: 14.23.5.2781

#### Log file:

https://gist.github.com/75e848b0749713e972fa4232edb68ee0

This is the latest crash report, I can add more if required.

**Comment by rubensworks** [comment]
I just did a small change that may resolve your issue: 96a4532a9b135124217cf2cb4cf55bcc57637326

If you want, feel free to try out the latest dev build that contains this fix: https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1263/

(Note: this dev build is still building at the time of writing)

<blockquote><div><strong><a href="https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1263/">Index of libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1263</a></strong></div></blockquote>

**Comment by xoxfaby** [comment]
It launched this time but I am getting the console horribly spammed with this

```java
[16:56:01] [pool-5-thread-134/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:02] [pool-5-thread-137/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:03] [pool-5-thread-140/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:04] [pool-5-thread-141/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:05] [pool-5-thread-143/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:06] [pool-5-thread-138/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:07] [pool-5-thread-144/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[16:56:08] [pool-5-thread-146/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
```

**Comment by rubensworks** [comment]
@xoxfaby Is that all you get? I'd have to see the full stacktrace to see what is going wrong.

**Comment by xoxfaby** [comment]
This was all that was shown in console. It was running but performance was awful. I was just restarting to install LagGoggles again to see where the awful performance was from. 

Is there anything I can do to get more information to you?

**Comment by rubensworks** [comment]
The exception spam probably causes the performance problem.

> Is there anything I can do to get more information to you?

@xoxfaby Can you check if the exceptions show full stacktraces in any of the forge log files?

**Comment by xoxfaby** [comment]
```java
[16:57:13] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]```

This is all I could fine, in-between some of the short versions.

**Comment by rubensworks** [comment]
@xoxfaby Can you send me the full log? There should be more information there...

**Comment by xoxfaby** [comment]
https://gist.github.com/e901dae92bda602c7c376fc131982951

Sorry, should've thought it through and gone to the beginning of when it was done loading, which is what I did to find this. 

<blockquote><img src="https://avatars0.githubusercontent.com/u/998173?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/xoxfaby/e901dae92bda602c7c376fc131982951">Hp5w.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by rubensworks** [comment]
No worries, I have enough information now :-)

@xoxfaby Is it ok if I send you a new dev-build once I make a new change to this? (It's a tricky one to reproduce myself)

Note to self: same problem as before, but in `IngredientObserver`. Make sure to implement pos skipping here as well, but make sure it doesn't mess up the diff.

**Comment by xoxfaby** [comment]
Of course. I mean I'm currently at your mercy as far as it comes to playing minecraft again so I'm very willing to test your builds. 

As for trying to reproduce, my network is spanning multiple dimenions so that might have something to do with it, most of which should be chunkloaded but I can't guarantee they still are, especially if not being fed power by the broken ID network.

**Comment by rubensworks** [comment]
@xoxfaby Pushed a new change, could you try the following when you have time?

https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1265/

(still building atm)

(If this doesn't fix the problem for you, I'll have a closer look at trying to reproduce this issue)

<blockquote><div><strong><a href="https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1265/">Index of libs-release/org/cyclops/integrateddynamics/IntegratedDynamics/1.12.2-1.0.2-1265</a></strong></div></blockquote>

**Comment by xoxfaby** [comment]
https://gist.github.com/xoxfaby/804451f06fc42e42a8072d0bfbbfa26b

<blockquote><img src="https://avatars0.githubusercontent.com/u/998173?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/xoxfaby/804451f06fc42e42a8072d0bfbbfa26b">ejve.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by xoxfaby** [comment]
This is the error I got, but the network did not appear to work correctly and I wasn't able to open the menu to a fluid interface,

If I can do anything else to help you, please let me know.

**Comment by rubensworks** [comment]
@xoxfaby Did you try resetting the network by breaking/replacing a cable? It's possible that the error is a remainder of the initial problem.

**Comment by rubensworks** [comment]
If that doesn't change anything, could you send the the _full_ forge log?

**Comment by xoxfaby** [comment]
```java
[19:41:12] [Server thread/INFO] [minecraft/DedicatedServer]: [XoX1337: Teleported XoX1337 to -185.5, 63.0, -46.5]
[19:41:12] [Server thread/WARN] [Integrated Dynamics]: A corrupted part state was found at, repairing...
```

I assume that's a good sign. I am now restarting the server to see if anything pops up at boot.

**Comment by xoxfaby** [comment]
Yeah, it seems that once I loaded the chunk by going there, it did update and get fixed, but it did boot without crashing even before then, so that's good. 

Nothing that I could see and no error and the network is working *mostly*. I'm having a bug with fluids but I should probably make a separate issue for that.

**Comment by rubensworks** [comment]
Great! I'm considering this fixed then, be sure to create separate issues for any other problems you may have. Thanks for the help!
