### ISSUE TITLE
Translate strings into integers for channel id's automatically

### ISSUE THREAD

**Issue by xoxfaby** [CyclopsMC/IntegratedDynamics#681]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

~~The basic idea is to translate aspect options into the correct format if possible, I can see at least 2 options where this would apply.~~ 

~~The first is simple, simply converting 1 and 0 into true and false respectively for boolean aspect options.~~  
It appears this is already implemented and I somehow missed it? I swear I had tried this before. 

The idea would be to convert strings into numbers for channels ( could be useful for others maybe? ).
The idea would be that you can type in a string format channel name, which would be easier to remember, which is then translated into an integer to actually be used as the channel id. what algorithm is used to convert the strings to numbers doesn't really matter as long as it's consistent and the same string always gives the same result. That way, instead of trying to remember all the numbers, you can just set the channel id to "lava channel" and ID translates it a number.

**Comment by rubensworks** [comment]
Hmm, I don't really like this idea.

What you describe is hashing. An inherent property of hashing is that the range of this function will always contain clashes. Furthermore, this function can not be reversed. As such, I think this feature would cause more confusion and problems than it would do good.

Thanks for the suggestion though :-)
