### ISSUE TITLE
switch drying basins to standardized forge input-output slots instead of storage

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedDynamics#682]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

the drying basin currently stores its item as a storage slot. this means that any form of automation has to have some sort of filter, because you can't simply extract the output.

**Comment by rubensworks** [comment]
I'm not sure I understand your request.

Drying basins already support Forge's `IItemHandler` capability, so this should already work out-of-the-box with any kind of item transfer system (such as hoppers). Doesn't this work for you?

**Comment by antrobot1234** [comment]
it's not that it's not working with transfer systems, but that it's not acting as a machine. it's working as a chest, so any extraction tool can pull anything out at any time instead of pulling only the output of the craft.

**Comment by rubensworks** [comment]
Ah, now I get it. The way it works now is intentional, it encourages more interesting automation logic. If you want an easier automatable machine, you can use the mechanical variant. I won't be changing the way the current drying basin works, sorry.
