### ISSUE TITLE
Way to copy the settings, aspect options and variable cards of a part. 

### ISSUE THREAD

**Issue by xoxfaby** [CyclopsMC/IntegratedDynamics#687]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Basically, some way to copy and paste the settings. Even better if you could have it automatically copy variable cards in the part as well, using blank cards from the inventory, but this is secondary. Applying the same settings to many parts is very tedious, especially when you are changing multiple aspect options on 20+ parts.

**Comment by Hapseleg** [comment]
Could this please become a thing? It takes so much time to set multiple interfaces to a different channel for example :)

**Comment by rubensworks** [comment]
Sure, pull requests for this are welcome!

**Comment by rubensworks** [comment]
Closing in favor of #859
