### ISSUE TITLE
Item List Count (itemlistcount) is not an Operator

### ISSUE THREAD

**Issue by LostOfThought** [CyclopsMC/IntegratedDynamics#689]
#### Issue type:

- :bug: Bug
- :heavy_plus_sign: Feature request

____

#### Short description:

Item List Count (itemlistcount) is not an Operator

#### Steps to reproduce the problem:

1. Operator -> Item List Count

#### Expected behaviour:

Item List Count be a first class Operator useable by Operator
____

#### Versions:

- This mod: 1.0.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2796

#### Log file:

Irrelevant

**Comment by rubensworks** [comment]
What do you mean exactly? What happens if you try to create an operator from itemlistcount?

**Comment by LostOfThought** [comment]
I do apologise, A relog cleared the issue.
