### ISSUE TITLE
Drying Basin Dosent dry blood from Evil Craft as per JEI

### ISSUE THREAD

**Issue by Morpheus1101** [CyclopsMC/IntegratedDynamics#69]
Since the blood drying thing shows in JEI as a valid option to use blood to dry to make solid blood blocks, i thought it would work, unfortunately it dosent, however being that this relates to EvilCraft i'll also shove it over on there github since i cant be sure as if its ID or EC fault to why it isnt working as JEI sais its meant to.

https://github.com/CyclopsMC/EvilCraft/issues/483

**Comment by rubensworks** [comment]
That's strange, since I tried this myself very recently.

Are you sure you are inserting exactly 1000 mB of blood, and there is no other item inside the basin?
Are you seeing any particles on the drying basin after inserting the blood?
Are any other recipes broken as well?

**Comment by Morpheus1101** [comment]
I've been waiting for hrs on the MMD-Dev server with a few completely full of Blood and i see no particles.  At this stage i havent used ID for anything else.

![mmd](https://cloud.githubusercontent.com/assets/10524952/18830730/5176dda0-8425-11e6-9268-cc6d03f71bfa.png)

**Comment by rubensworks** [comment]
Ah, I see. I assume the blood in those basins are TCon's blood?
EC's blood is not the same fluid as TCon's blood (for historical reasons...), so EC recipes won't work with that.
You can however pipe TCon's blood through a Blood Infuser and it will automatically convert it to EC's blood.

Note that the MMD dev server should have Fluid Converters installed, so you could use a blood converter as well.

**Comment by Morpheus1101** [comment]
Ahhh, well that explains things quite a lot, as i have the blood form there pumped into an infuser etc ... i'll have to use a converter then an see how i go, this explains everything, so its just a derp on my side lol.

Now if only the converter had a recipe shown in JEI ... time to hitup its github
