### ISSUE TITLE
Slotless source crash

### ISSUE THREAD

**Issue by Yamza** [CyclopsMC/IntegratedDynamics#696]
#### Issue type:

- :bug: Bug

____

#### Short description:

Server crashes with this error: `java.lang.IllegalStateException: Slotless source to destination movement failed due to inconsistent insertion behaviour by destination in simulation and non-simulation: org.cyclops.integrateddynamics.core.network.IngredientChannelIndexed@6d90d74e. Lost: 15797`

#### Steps to reproduce the problem:

Unsure exactly, one player has a very extensive network of ID pipes.
Crash was initially found on ID 1.0.3 with IT 1.6.2.
Updated ID to 1.0.4 and IT to 1.6.5 but the issue was not resolved.

#### Expected behaviour:
Working
____

#### Versions:

- This mod: both 1.0.3 and 1.0.4
Tunnels: both 1.6.2 and 1.6.5
- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- Modpack: ATM3 Remix 1.0.3

#### Log file: https://www.dropbox.com/sh/w17ci5l7gg2r3za/AABNPaVvVwIMfDxh0v0D27sua?dl=0
The last report shows the updated mod versions.

**Comment by rubensworks** [comment]
> Unsure exactly, one player has a very extensive network of ID pipes.

I'll need more information. I won't be able to do much without it unfortunately...

**Comment by Yamza** [comment]
What else can we get for you?

**Comment by rubensworks** [comment]
> What else can we get for you?

I need steps to reproduce this problem myself.

**Comment by Yamza** [comment]
Is there anything that is saying that could narrow down what I'd be looking for? I'm not exactly familiar with ID myself and the player has used it to automate all parts of their base including a variety of mods/machines. We're working on loading a backup from before the issue began in which I hopefully can investigate further but I really have no idea where to even begin. Other than the generic "it didn't happen before 1.0.3, and didn't actually happen for a few days after updating" I'm not really sure what else I can give you. The player in question hasn't actually been on for roughly a week either.

**Comment by Yamza** [comment]
I've got this spark report from several hours prior to the crash occouring where you can see some interaction between IC2 and ID taking roughly 10% of the servers CPU, might be related? This had been going on for a few days. https://i.imgur.com/CUHrnf0.png
https://sparkprofiler.github.io/#GbBA1gYASx

<blockquote></blockquote>
<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>

**Comment by Yamza** [comment]
Just want to leave a bit of a progress report: After loading the backup we are trying to remove the network in question but after removing a number of pieces of cable the server will crash. Also the spark report seems to suggest that the network was incorrectly supplying Tech Reborn machines with IC2 energy. Could suggest an incompatibility with tatw.
New spark from backup: https://sparkprofiler.github.io/#NmRyKIBMd0
Crash report from removing cable: https://gist.github.com/Yoosk/2603d4a83d9e533e210d6777a7503097

**Comment by Yamza** [comment]
Removal of the "main" part of the players network solved the issue of crashing while removing more cable. And with it gone now I guess the issue is resolved. Seems like somehow the power network got corrupted. Will have to be sure not to have more than a few simple transfers on a single power network going forward.
