### ISSUE TITLE
micro blocks not working

### ISSUE THREAD

**Issue by mindcloud69** [CyclopsMC/IntegratedDynamics#698]
#### Issue type:

- :bug: Bug

____

#### Short description:

micro parts i.e. mcmultiparts are not working at all. You cant place them in the same space as any block from the mod.

#### Steps to reproduce the problem:

1. Try to place a microblock in the same place as a cable or other block from the mod.

#### Expected behavior:

According to the description from the curseforge page it should be compatible with mcmultipart.

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.0.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2781

#### Log file:

Nothing in the log replated

**Comment by rubensworks** [comment]
This has not been implemented after MCMP has been rewritten for 1.11+. Feature request for that is here: #157.

Will update the Curseforge description to reflect this.
