### ISSUE TITLE
Facade rendering in F5 mode shows cables

### ISSUE THREAD

**Issue by nzhook** [CyclopsMC/IntegratedDynamics#70]
When a facade is placed over a cable it disappears as it should. However in F5 mode some cables are still rendered as shown on the below image.

![7weqyro](https://cloud.githubusercontent.com/assets/4828036/18901149/0b7da032-85a5-11e6-95ba-6ab5aaa19dbd.png)

Version: IntegratedDynamics-1.9.4-0.5.1.jar
Forge version: 12.18.1.2088
Minecraft Version: 1.10.2
Modpack: Avant 3

**Comment by rubensworks** [comment]
Thanks for reporting this, I already knew about this issue, but having this here again will put some more pressure on me to finally fix it :-)
