### ISSUE TITLE
CraftTweaker Wiki Entries

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#700]
#### Issue type:

- :bug: Bug

#### Short description:

The MineTweaker section of the wiki, https://github.com/CyclopsMC/IntegratedDynamics/wiki/MineTweaker, is outdated, the addRecipes take other parameters than specified.

**Comment by rubensworks** [comment]
Does it though? I don't remember changing this recently.

What problems are you running into with the wiki's examples?

**Comment by NielsPilgaard** [comment]
It does yes. According to the wiki, `Squeezer.addRecipe` can only take `inputStack, outputStack, outputFluid`, but it actually has 4 different parameter options.

`inputStack, outputStack`
`inputStack, outputStack, outputFluid`
`inputStack, outputStack, int chance, secondaryOutputStack`
`inputStack, outputStack, outputFluid, int chance, secondaryOutputStack`

The same goes for the mechanicalSqueezer. The duration parameter does not seem to exist.

**Comment by rubensworks** [comment]
You're right, I'll have to look into that.

Note to self: chance variants are not documented yet: https://github.com/CyclopsMC/IntegratedDynamics-Compat/blob/master-1.12/src/main/java/org/cyclops/integrateddynamicscompat/modcompat/minetweaker/handlers/SqueezerHandler.java

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics-Compat">CyclopsMC/IntegratedDynamics-Compat</a></strong></div><div>Integrated Dynamics compatibility with other mods. - CyclopsMC/IntegratedDynamics-Compat</div></blockquote>

**Comment by NielsPilgaard** [comment]
Thanks :) Luckily the error is fairly descriptive.

**Comment by rubensworks** [comment]
Updated the wiki page. Also added some new convenience CT variants while I was at it. These will be included in the next update.

**Comment by NielsPilgaard** [comment]
After updating to `IntegratedDynamics-1.12.2-1.0.7`, all my scripts using the syntax ` inputStack, outputStack, int chance, secondaryOutputStack` are broken. They also throw errors if I change the int chance to float or double. They worked prior to updating.

**Comment by rubensworks** [comment]
Is your issue the same as https://github.com/CyclopsMC/IntegratedDynamics-Compat/issues/21?
If so, it has been fixed. (will try make a new release somewhere next week)

**Comment by NielsPilgaard** [comment]
Yep that's it, sorry for the duplicate :)

**Comment by rubensworks** [comment]
@NillerMedDild I'll make a new release with this fix in a bit. It _may_ be possible that you'll have to change your scripts slightly to `inputStack, outputStack, int chance, secondaryOutputStack, secondaryOutputStackChance`.

The reason for this is that I removed some `@Optional` annotations because CT seems to be randomly breaking things when they are used in multiple equal-named methods. You can just use `1` for these chances if they are not important though.

**Comment by NielsPilgaard** [comment]
Sounds reasonable, thank you :)
