### ISSUE TITLE
Selection is off by one when tabbing through the Operator type in the Logic Programmer.

### ISSUE THREAD

**Issue by hinchy34** [CyclopsMC/IntegratedDynamics#701]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. If you search through the entire selection list for Operator type in the Logic Programmer (by searching a single space " " and using the keyboard TAB key, the selection is off by one after the first entry, "Logical And".

2. Selecting the second entry, "Logical Or" will result in the third entry "Logical Not".

3. The off by one bug only occurs when using the TAB key.

There is a video of someone showing off the bug. https://www.youtube.com/watch?v=Rbb7mIB6JCI&t=630 (10:30 if the timestamp url doesn't work).

____

#### Versions:

- This mod: 1.12.2-0.11.18
- Minecraft: 1.12.2
- Forge: 14.23.5.2772

FTBPresentsDirewolf20112-2.4.0-1.12.2.zip

**Comment by rubensworks** [comment]
Oh, interesting...
