### ISSUE TITLE
Unloading a chunk causes power drainage through logic cables

### ISSUE THREAD

**Issue by MrSpencerRecor** [CyclopsMC/IntegratedDynamics#702]
#### Issue type:

- :bug: Bug  Even in a loaded chunk area power drainage happens through logic cables

____

#### Short description:

 So, if I leave the area where my logic cables are hooked up to a machine, all the machines will drain and the logic cables don't receive power anymore. Even while FTB Utils chunk loaded 

#### Steps to reproduce the problem:

1. ... Set up a energy battery system going to a machine through logic cables. Chunk load the area. Run or fly away from that area a few chunks, come back. You'll notice that your machine is draining power and your logic cables aren't pulling power from the energy battery.

#### Expected behaviour:

I expected the cables to maintain power going to the machines I have set up. Even once I chunkloaded I thought that would fix it. The only thing that fixed it was a right click of a wrench on the logic cables.
____

#### Versions:

- This mod:  IntegratedDynamics-1.12.2-1.0.3, IntegratedTunnels-1.12.2-1.6.2
- Minecraft: 1.12.
- Forge: 1.12.2 (modded)
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/2883294/latest.log)
 14.23.5.2808

**Comment by MrSpencerRecor** [comment]
Just an update, posted in the IntegratedTunnels sections, found out more about how it happened/what exactly is causing it. Still don't know how to fix it though.

**Comment by rubensworks** [comment]
Related to CyclopsMC/IntegratedTunnels#157.

Putting this issue on hold in favor of CyclopsMC/IntegratedTunnels#157.

**Comment by rubensworks** [comment]
@MrSpencerRecor Now that CyclopsMC/IntegratedTunnels#157, this issue may also be fixed. Could you try out the latest ID+IT dev builds to see if this issue stil occurs for you?

**Comment by rubensworks** [comment]
Assuming this is fixed, please let me know if this is not the case.
