### ISSUE TITLE
Labels don't seem to persist after server restart.

### ISSUE THREAD

**Issue by hinchy34** [CyclopsMC/IntegratedDynamics#703]
#### Issue type:

- :bug: Bug

____

#### Short description:

I started building a moderately complex sorting system last night, so I was labeling every card with a meaningful name. However this morning, (I shut down the server when I'm done playing) when I loaded up the world all the labels were gone.

#### Steps to reproduce the problem:

1. Label Variable Cards with Labeller
2. Stop server /stop
3. Start server, cards have no labels

#### Expected behaviour:

Card labels persist through play sessions.

____

#### Versions:

- This mod: 1.12.2-0.11.18
- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- Modpack: FTBPresentsDirewolf20112-2.4.0-1.12.2.zip

#### Log file:

Checked crash-reports, empty folder!

**Comment by rubensworks** [comment]
Can you reproduce this with the latest version of the mod without any other mods installed?

**Comment by hinchy34** [comment]
Well I can't seem to even replicate my issue in the DW20 pack anymore. After a few server restarts the labels are working fine. I'll be messing around a lot with the mod still, see if I can figure out what I did..

**Comment by rubensworks** [comment]
I would assume something else went wrong what caused some world NBT data not to be stored properly (like a crash from another mod). If you (or anyone else) would run into this problem again, be sure to comment here so I can reopen the issue.
