### ISSUE TITLE
Variable Store keeps chunk it's in loaded.

### ISSUE THREAD

**Issue by farigiss** [CyclopsMC/IntegratedDynamics#705]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

Here's a video of it. https://www.youtube.com/watch?v=sygiJU2lMYk
Here's what I'm doing:
1. I've created a fresh Forge server with *only* ID and its dependencies.
2. Made a redstone contraption that puts items into a chest to show the chunk is processing while away.
3. Place variable store in same chunk.
4. teleport away 1000 blocks, execute "/save-all" to unload any chunks that should no longer be loaded, wait a while, then teleport back.
5. Repeated process with variable store removed for comparison.

#### Expected behaviour:

The chunk should be unloaded in *both* cases and therefore the redstone should not continue as there are no chunkloaders around.
I know this has happened on our live server with other ID or possibly Integrated Tunnels blocks, but I couldn't replicate that so easily on the test server used in the video. The variable store does it every time however.
It's a problem because players are building lag-heavy contraptions thinking it's under control because it'll only work while they're there (not unreasonable). 
Also, cleaning up loaded chunks by players who have become inactive on the server becomes a lot harder when you need to find and break all their ID stuff in order to stop their chunks loading, as opposed to unloading their chunks in FTBUtilities or simply breaking their one chunkloader block.

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.18.jar (also CommonCapabilities-1.12-1.4.0.jar, CyclopsCore-1.12.2-0.11.11.jar)
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2772-universal.jar

**Comment by rubensworks** [comment]
You seem to be using an outdated ID version. Can you reproduce this with the latest versions of all Cyclops mods?

**Comment by Sir-Will** [comment]
Happens with the latest versions too. After a chunk gets unloaded it instantly loads again because of ID.

CommonCapabilities-1.12.2-2.0.4 CyclopsCore-1.12.2-1.0.5 IntegratedDynamics-1.12.2-1.0.7

**Comment by rubensworks** [comment]
Thanks for checking @Sir-Will, I'll look into it soon.
