### ISSUE TITLE
TunnelConnection performance issue

### ISSUE THREAD

**Issue by Sir-Will** [CyclopsMC/IntegratedDynamics#707]
#### Issue type:

- :snail: Performance issue

____

#### Short description:

See profile output below, I currently don't know more about the issue.
____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.0.7

#### Profiler output:

![](https://i.imgur.com/YFnmvdI.jpg)

**Comment by rubensworks** [comment]
Something is definitely going wrong there, networks should be compared by identity, not by containing values.
