### ISSUE TITLE
error: integrated dynamics:partData

### ISSUE THREAD

**Issue by Trixz2018** [CyclopsMC/IntegratedDynamics#708]
![image](https://user-images.githubusercontent.com/8538100/54721195-513cdc80-4b2f-11e9-8cf6-4aa6b48ed691.png)

updated all your mods and got this everytime i look a something

**Comment by Yoghurt4C** [comment]
also having this issue with TOP and ID 1.0.9
![image](https://user-images.githubusercontent.com/11313954/54725285-8d982900-4b7f-11e9-93a5-db5d5be57ca5.png)

**Comment by Staegrin** [comment]
Sadly having the same problem after updating to 1.0.9
![2019-03-21_00 21 43](https://user-images.githubusercontent.com/8494635/54725481-89640f80-4b6f-11e9-95ea-070d5c996613.png)

**Comment by rubensworks** [comment]
That's weird, something probably went wrong while packaging ID-Compat.

**Comment by rubensworks** [comment]
Will be fixed in 1.0.10
