### ISSUE TITLE
Logic Programmer Variable Labelling

### ISSUE THREAD

**Issue by nzhook** [CyclopsMC/IntegratedDynamics#71]
Couple of issues with using the Logic Programmer to name variables:
- The 'E' is used to set a card's name, however this only enables the textbox. Pressing it again does not save the entered name to the card (instead it acts as Cancel ignoring anything that was entered which is unexpected)
- After entering a name for the label of a card, pulling the card out does not always set the variable cards name. This results in the previously entered name or 'Variable Card'. Putting the card back in and pulling it out again works fine. 

It would also be nice to be able to use the labeller to rename an existing card.

Version: IntegratedDynamics-1.9.4-0.5.1.jar
Forge version: 12.18.1.2088
Minecraft Version: 1.10.2
Modpack: Avant 3

**Comment by rubensworks** [comment]
"It would also be nice to be able to use the labeller to rename an existing card."
This should be possible already. Are you able to insert the existing card into the labeller? Or what happens exactly when you try it?
