### ISSUE TITLE
Crash with Integrated Dynamics after loading world

### ISSUE THREAD

**Issue by Fireztonez** [CyclopsMC/IntegratedDynamics#710]
#### Issue type:

- :bug: Bug

____

#### Short description: My game completly crash just after I open my world, I didn't get any Crash report, but I have the log with a lot of Integrated Dynamics Java error, so you can  forsure look the log. I'm not 100% sure the crash is caused by integrated Dynamics, but, this is the last anormal thing I can see in the log file... 

This doesn't appen all the time, because I have play in that world before, I have leave the world to open another one and when I go back to this firts world, the game have crash...

If you think is caused by other mod, can you please tell me what mod you think is in caused, because crash like that is not really clear for me... 

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.0.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2823

#### Log file:
https://gist.github.com/Fireztonez/45ef4a12ad3abb0d524eab400c920c3a

**Comment by rubensworks** [comment]
I don't see any crashes related to ID in your logs, so I'm pretty sure your crash (of which I see no proof) is caused by ID.

**Comment by Fireztonez** [comment]
What do you mean by caused by ID?? I never eared something like that... An ID is a number, so, how a number can caused a crash?? And what proof do you need for a crash... For me, if a game close by itself when I try to open a world this is a crash... If you need to see the crash, I can send you the link to my VOD Twitch, because it's happen when I'm Live, so you will see the game stopping by itself, but I don't think.

I like how you close an crash issue soo fast and say you didn't have any proof.

So you can see the crash appending just there https://www.twitch.tv/videos/400163249?t=07h11m

And, I saw the Interuption Code is not in the Log File, so if it can help you, the Process Interruption Code is: `-805306369` (this number is show at the end of the console on MultiMC after the game close..). If the game close because I have close it normally the number is 0, so this is a second proof for the crash...

<blockquote><img src="https://static-cdn.jtvnw.net/s3_vods/75e097471432f71c4db7_fireztonez_33346975088_1152823218/thumb/thumb0-640x360.jpg" width="48" align="right"><div><img src="https://static.twitchcdn.net/assets/favicon-75270f9df2b07174c23c.ico" height="14"> Twitch</div><div><strong><a href="https://www.twitch.tv/videos/400163249">[FRA/ENG] Same-Dev PatCraft 1.4.3! Tests & Fixes sur l'update de PatCraft!
#BSo7 #FRo7 - Vos points? : !evil</a></strong></div><div>Fireztonez - Minecraft - Twitch</div></blockquote>

**Comment by Fireztonez** [comment]
:O sorry, I'm tired... I have miss understood your message... when you talk about ID, you talk about Integrated Dynamics, so, your mod... But, on that case, if you are pretty sure the crash is caused by Integrated Dynamics, why do you close the issue, this doesn't have any sens...

**Comment by rubensworks** [comment]
Sorry, typo, I meant that I'm pretty sure that the crash is _not_ caused by ID. Crashlogs like yours typically indicate a corrupted Java installation or RAM issues.

**Comment by Fireztonez** [comment]
Ok, thank's for the informations rubensworks... In that case the problem is probably due to a Memory Leak issue... I still try to find what mod can be the caused of that memory leak issue, but diagnose a similar problem is not always easy...
