### ISSUE TITLE
Redstone Writer Achievement bugged

### ISSUE THREAD

**Issue by shadoxxhd** [CyclopsMC/IntegratedDynamics#713]
#### Issue type:

- :bug: Bug

____

#### Short description:

The redstone writer achievement does not complete, even when using the integer value card. I even tried a MAX_INT value integer card (manually entered the value), and it still did not work.

#### Steps to reproduce the problem:

1. Use All The Magic 1.3 Modpack
2. Build lever-redstone reader-cable-cable-redstone writer-redstone circuit
3. get a variable card for integer value in redstone reader
4. put variable card in integer redstone slot of writer
5. turn lever on
6. try turning 'strong power' on
7. try inserting a MAX_INT value integer card

#### Expected behaviour:

the achievement completes

____

#### Versions:

- This mod: 1.12.2-1.0.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2808 (FML 8.0.99.99)

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
The advancement actually works fine, just the description was wrong (the value that you write needs to be read by a Redstone Reader). Will be fixed.
