### ISSUE TITLE
Value 'Burn-In' Effect

### ISSUE THREAD

**Issue by shadoxxhd** [CyclopsMC/IntegratedDynamics#714]
#### Issue type:

- :bug: Bug

____

#### Short description:

**Sometimes** when the dependencies of a dynamic value did not change for a while, it stops updating regularily.
In my case, I extracted the heat value of an aetherium forge (double) from its NBT and compared it to a fixed proxied double value (target heat). The heat display was updating as soon as the heat NBT changed, but the result of this comparison was stuck (this cost me my aetherium forge by overheating it explosively :disappointed:).

#### Steps to reproduce the problem:

1. Extract a double value like the current heat of the aetherium forge from some block.
2. Compare it with a (in my case proxied) fixed double value.
3. Output the dynamic value (eg. heat level) and the comparison result ("heat<=target") on display screens.
4. Turn on the block in a way that makes the extracted value change (eg. turn on the aetherium forge heater).
5. Observe the dynamic double value being shown in real time, but the comparison value being stuck.
6. To fix the issue, manually extract and replace the comparison value card just before its result will change - since in my scenario this resulted in the heat oscillating around the target heat value, the comparison result was constantly changeing and therefore 'keeping awake' the display.

#### Expected behaviour:
As soon as the inequality changes (eg. heat becomes greater than target heat) the display or redstone writer should update its output, just like with the value output display.

____

#### Versions:

- This mod: 1.12.2-1.0.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2808 (FML 8.0.99.99)
- Environment: All the Magic 1.3

____
When my forge blew up, I had the network set up without any battery attached (energy consumption is disabled in this pack). After rebuilding I attached a charged battery, and when testing it again (with exactly the same logic) it worked fine - though I think I remember noticing the bug once shortly after adding the battery. This might or might not be related to the old block update issue (#436 #356).

**Comment by rubensworks** [comment]
You're a couple of versions behind. Can you try updating to the latest version to see if the problem still occurs?

**Comment by shadoxxhd** [comment]
After updating I did not notice the bug again, though my network has been connected to a battery since then.
I'll try to reconstruct the original situation in a creative world when I have time,
