### ISSUE TITLE
Facades have abnormal lighting

### ISSUE THREAD

**Issue by Dimentive** [CyclopsMC/IntegratedDynamics#715]
#### Issue type

- :bug: Bug

#### Short description
Facades are too bright and thus out of place. They seem to not be affected by lighting and therefore do not look like actual blocks.

![2019-04-09_11 46 38](https://user-images.githubusercontent.com/34230933/55790747-4eddfa80-5abd-11e9-9516-a53f3b2e9e3b.png)

The two bright stone blocks are Integrated Dynamics stone facades.

#### Steps to reproduce

1. Place a cable.
2. Place a facade.
3. Witness the facade.

#### Expected behaviour

Facades should conform to Minecraft’s lighting and should look like regular blocks. This is how facades from other mods, such as Applied Energistics 2, Refined Storage, Ender IO, and Chisels & Bits, behave.

____

#### Versions

* **Minecraft:** 1.12.2
* **Integrated Dynamics:** 1.0.10
* **Integrated Tunnels:** 1.6.8
* **Cyclops Core:** 1.1.1
* **Common Capabilities:** 2.1.1
* **Forge:** 14.23.5.2781

**Comment by rubensworks** [comment]
Thanks for the issue! This has actually already been reported in #180, so I'm going to close this in favor of that issue.
(The issue has been open for a while, but I hope to get to it soon)
