### ISSUE TITLE
CT Integration for Mechanical Drying Basin ignores input quantity

### ISSUE THREAD

**Issue by pyure** [CyclopsMC/IntegratedDynamics#716]
#### Issue type:

- :bug: Bug

#### Short description:
CraftTweaker integration for Mechanical Drying Basin seems to ignore number of items in inputstack.

#### Steps to reproduce the problem:
```
var pulpedBiomass = <thermalfoundation:material:816>;
mods.integrateddynamics.MechanicalDryingBasin.addRecipe(pulpedBiomass * 8, null, <minecraft:dirt>, <liquid:methane> * 240, 620);
```

Machine will produce 240mb output (good) but consume a single pulpedBiomass (bad).

#### Expected behaviour:
Should consume 8 pulpedBiomass rather than 1.

#### Versions:
- This mod: IntegratedDynamics-1.12.2-1.0.11.jar
- Minecraft: 1.12.2
- Forge: 2815

#### Possible Interest:
JEI visibly reflects the correct recipe (8 pulped biomass), but clicking the "+" button automatically places just 1 pulped biomass into the input slot.

**Comment by rubensworks** [comment]
This might even be a restriction in the Mechanical Drying Basin's code, will have to implement some new things for that.

**Comment by pyure** [comment]
Thx kindly sir.  We have workarounds for now, don't feel rushed.

**Comment by rubensworks** [comment]
Closing this, as this has become irrelevant as we now have JSON recipes.
