### ISSUE TITLE
Feature: Is Null/Not Null comparison

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedDynamics#718]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

A card `Any -> Boolean` which returns whether an input value is "null" i.e. has no value; an undefined entity, item, list of length 0, et cetera.

Replaces the sequence of "create typed variable with no value, write Relational Equals/Not Equal to valueless typed variable".

I'm writing this from bed and haven't touched the mod in quite a while, but I'm fairly certain this isn't a thing yet.

**Comment by GreyMario** [comment]
My pea brain has just remembered that there is an `empty` function for Lists. Could still hold value in including Lists in this card.

**Comment by rubensworks** [comment]
There are `isnull` and `isnotnull` operators, and indeed the `empty` operator for lists, so everything should be available already.
I don't really see the value in creating a combined operator for those, so I'm going to close this issue (but feel free to try to convince me of the potential value :-) ).

**Comment by GreyMario** [comment]
Huh, there are? I guess I never noticed them in all this time. Oh well.
