### ISSUE TITLE
[1.10.2][0.5.1] Crash involving RFTools Endergenic Generator and Integrated Dynamics

### ISSUE THREAD

**Issue by Aedda** [CyclopsMC/IntegratedDynamics#72]
Steps to reproduce:
1) Connect an Integrated Dynamics (ID) Machine Reader to an RFTools Energenic Generator
2) Connect ID Logic Cable, followed by ID Display Panel
3) Right click ID Machine Reader to open GUI. Click scroll bar or attempt to scroll.

Game should crash at this point.

I successfully connected ID to other RFTools machines including the Crafter Tier 1 and Matter Beamer. Versions of mods used:
Minecraft 1.10.2
Forge 2093
RFTools 5.24
Integrated Dynamics 1.9.4-0.5.1

Crash report:
https://gist.github.com/Aedda/8d5b81ac6d8d06c4383ddb0b928fd805

I originally reported this to the RFTools tracker [#763](https://github.com/McJty/RFTools/issues/763) but it was suggested I do here as well, as the source of the problem is not clear.

**Comment by rubensworks** [comment]
I encountered the same crash recently, this has been fixed here: a9e7b3ec43c71eb1d485e617c15bdb55c29cf68f
Thanks for reporting anyways! :-)
This fix will be included in next update.
