### ISSUE TITLE
Log spam ValueTypeListProxyPositionedInventory

### ISSUE THREAD

**Issue by Tazmondo** [CyclopsMC/IntegratedDynamics#721]
#### Issue type:

- :bug: Bug

____

#### Short description:

After spending a lot of time getting to grips with ID and learning how it worked (as well as testing it out with Integrated Tunnels), it seemed that my inventory interface had broken. I couldn't throw items, couldn't craft anything in the 2x2 grid and any changes I made seemed to be reset after opening a chest or crafting table. However the inventory that appears when looking in a chest/crafting table works completely fine. It also works when looking at my inventory through a portable logic programmer.

#### Steps to reproduce the problem:

Honestly not entirely sure, I only noticed after I had messed around in the interfaces for a while. Sorry.

#### Expected behaviour:

My player inventory interface to fully replicate and save it's new state whenever I made a change.

____

#### Versions:

- This mod: 1.0.8
- Minecraft: 1.12.2
- Forge: Not sure how to find out, but I'm playing on the Sky Factory 4 modpack that recently released.

#### Log file:

Log file reached about 99000 KB so it's way too large to fully put on pastebin, however I have uploaded the error that kept repeating and filled up the majority of the log. Something to do with "deserialize"
https://pastebin.com/GAJfGdgs

**Comment by rubensworks** [comment]
Your logs do indeed seem to indicate an issue that I will fix. However, that is not related at all to the inventory problem you are describing. ID does not change the player's inventory in any way, so it seems unlikely that ID is causing that problem, I highly suspect that some other mod is causing that.
