### ISSUE TITLE
Crash when opening Machine Reader

### ISSUE THREAD

**Issue by maham** [CyclopsMC/IntegratedDynamics#722]
When I'm opening a Machine Reader the game crashes with this log:

https://pastebin.com/8mP8XMzn

It's only the last part as pastebin won't allow me to post all of it.

Pack: Sky Factory 4

Versions:
- Integrated Dynamics: 1.12.2-1.0.11
- Integrated Tunnels: 1.12.2-1.6.7
- Cyclops Core: 1.12.2-1.1.1
- Common Capabilities: 1.12.2-2.2.0

**Comment by rubensworks** [comment]
What block/machine were you reading from?

**Comment by maham** [comment]
The manual squeezer

**Comment by rubensworks** [comment]
Thanks for the info, will look into it soon!
