### ISSUE TITLE
Logic Programmer gets broken texture when silk touched

### ISSUE THREAD

**Issue by WebDragon** [CyclopsMC/IntegratedDynamics#728]
#### Issue type: Broken Texture

- :bug: Bug
____

#### Short description:

Silk touching a Logic Programmer produces a block with a broken texture

#### Steps to reproduce the problem:

 if you silk touch an Integrated Dynamics Logic Programmer instead if with a normal pick, to pick it back up with, it gets a broken (neon purple) texture. if you put that back down again it goes back to normal and you can break it with a normal pick and not get the problem

#### Expected behaviour:

breaking the block with either a normal or silk touch pick should produce the block

____

#### Versions:

- This mod: 1.12.2-0.11.12
- Minecraft: 1.12.2
- Forge: 8.0.99.99

**Comment by sam-kirby** [comment]
Reproduced this issue in a minimal instance using current latest mod release:
* Integrated Dynamics 1.0.11
* Minecraft 1.12.2
* Forge 14.23.5.2831
