### ISSUE TITLE
Slot 1 not in valid range crash loop

### ISSUE THREAD

**Issue by braingkk** [CyclopsMC/IntegratedDynamics#730]
#### Issue type:

server crash loop

____

#### Short description:
attempting to remove from a nonexistent slot topples server into crash loop

#### Steps to reproduce the problem:

place an importer, and filter it to a specific slot not contained in the block it is on.

#### Expected behaviour:

some sort of error and not extracting w/o killing the server

____

#### Versions:
- This mod: 1.12.1-1.0.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:
https://gist.github.com/cjm721/3250af535f85b58ef352b1ba1f78de71

seems like this has been previously reported, but that was for an older version
https://github.com/CyclopsMC/IntegratedDynamics/issues/480

**Comment by rubensworks** [comment]
What kind of storage are you using?

**Comment by braingkk** [comment]
was trying to pull honey from the side of a rustic apiary, seems like you were supposed to pull from the bottom. [sorta like mc furnaces] but in the process of trying to pull from slot1 from the side i sent the server into a crash loop

**Comment by braingkk** [comment]
easy enough to do with a minecraft chest, just set a card to say slot55 and place it in the slot space in an importer. pardon the ancient java version on my pc, but the server is running a recent version of java so that isnt it https://pastebin.com/qVTB0Qq5

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/qVTB0Qq5">---- Minecraft Crash Report ----    WARNING: coremods are present:    AppleCore  - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Hmm, I'm surprised ID is not checking the slot validity yet. Anyways, should be an easy fix.
