### ISSUE TITLE
with Energy usage config set to 1 or more makes networks not accept power

### ISSUE THREAD

**Issue by reddler97** [CyclopsMC/IntegratedDynamics#731]
#### Issue type:
- :bug: Bug

____

#### Short description:
when the config "I:general.energyConsumptionMultiplier=1" is set to 1 or more (as seen), will, when loaded, makes any cable part not function and display "No Power" at the bottom of their GUI's. even when supplied with power

#### Steps to reproduce the problem:

1. Load a world with said config set to 1 or more
(skip to 3 if a network already exist in the world}
2. Place a charged battery, cable, and any part (connected to said cable)
3. Open the GUI of the part (of the said part if step 2 was used)
4.  Recognize that any function said part is supposed to do, will not work and that at the bottom of the Gui it displays "NO POWER"

#### Expected behavior:
when said config is set to 1 or more, I would expect a network to function the same except it consumes power (at a rate based on the config). and thus requires power upkeep to continue to function and only displays no power when there isn't enough power supplied.

____

#### Versions:

- Integrated Dynamics: 1.0.13(latest)
- Cyclops Core: 1.3.0 (latest)
- Common Capabilities: 2.4.0 (latest)
- Just enough Items: 4.15.0.279 (for ease of access)
- Minecraft: 1.12.2
- Forge: 14.23.5.2838 (latest for 1.12.2)

**Comment by rubensworks** [comment]
That's not good, probably a regression since the last major rewrite of energy networks.
