### ISSUE TITLE
Make interfaces accept fluid flow

### ISSUE THREAD

**Issue by AssB0ys** [CyclopsMC/IntegratedDynamics#732]
- :heavy_plus_sign: Feature request

____

#### Short description:

I've been playing Enigmatica 2 Expert and I've been using Integrated Dynamics and Tunnels for automation. I've made a IC2 heat reactor and I've been trying to figure out how to extract the "superheated steam" from the IC2 boilers. I've come to the conclusion that you cannot demand an extraction instead you can only accept if the fluid is pushed to the container(or a pipe mechanism). The Integrated Dynamics fluid reader doesn't recognize the superheated steam container part of the boiler(only the water part) so the extractor doesn't extract fluid because there is no fluid on demand. I hope you can understand what I am saying. Basically the steam gets pushed out of the boiler and if it is not accepted it disperses into the void - there is no temporary container for the steam in the IC2 boiler, that's why the extractor cannot extract the steam from it, I suppose. If I first put a fluid tank from the other mod(that can accept fluids if pushed into) and then extract from a tank it works. Also the Immersive Engineering pipes work but of course they are not as configurable as Integrated Dynamics network.
I mean, there is a workaround for MY specific problem, but it would be nice if this mod had means to accept pushed fluids. Maybe not an extractor but another interface - a funnel. This is my suggestion, thank you.

**Comment by GreyMario** [comment]
I'd like to properly examine this situation myself. I'll update my E2E instance and see if there's something being done wrong, as I'm not familiar with the function of the IC2 machines in question.

**Comment by rubensworks** [comment]
Importers already support fluids being pushed into them iff the importers have an active aspect. For example, by just placing a fluid importer with an active boolean aspect.

@AssB0ys Does this work for you?

**Comment by AssB0ys** [comment]
I am sorry, I am not that advanced user it seems... I don't know what are the aspects. I tried just exporting in **all fluids** mode with just an empty variable card and then the specific fluid(import fluid) mode with the superheated steam variable card. Both work with regular tanks(for example, TE fluid tank) but don't work with the IC2 steam boiler.
I will have to look into the aspects then, it will take me a couple of hours I think and then I will report back.

**Comment by rubensworks** [comment]
What are you using? An exporter or an importer? It sounds like you should be using an importer (which imports fluids from something else into the ID network).

**Comment by AssB0ys** [comment]
Here's the setup, I will explain it in color-codes:
![2019-05-27_11 03 27](https://user-images.githubusercontent.com/49584508/58405150-7c800280-806f-11e9-977a-203853988906.png)
Green - interfaces in question,
red - IC2 boilers, pink -IC2 liquid heat exchanger.
Now, here's what I think what the problem is. If you look at the IC2 liquid heat exchanger GUI, you can see that it has 2 physical tanks for each liquid that I am extracting and exporting, and I don't have any problem with that.
![2019-05-27_11 06 08](https://user-images.githubusercontent.com/49584508/58405248-a802ed00-806f-11e9-8ff4-87b0acf61e08.png)
And If you look at the IC2 Steam Boiler GUI, you can see that it has only one physical tank for the Distilled water, which I do not have any problem exporting and importing. But the Superheated Steam, in other hand, only has a notification on the top of the GUI if it is being generated or not, so I assume that it does not have any physical tank(internal temporary buffer) present. And that is what I am trying to extract and fail to do so with the Integrated Dynamics means.
![2019-05-27_11 03 52](https://user-images.githubusercontent.com/49584508/58405394-fc0dd180-806f-11e9-98fd-7cb97ebd4a18.png)
Note that I can export/import the distilled water from the same machine.
Previously I have said that I was using exporters, I am actually using interfaces on these machines because I need to import(to the machine) the distilled water and then export(from the machine) the Superheated steam, which are both fluids, by the way, not gas.
In the first sceenshot you can see the temporary workaround I was telling about - the Immersive engineering pipes and the tank, which is working, but I think using only the Integrated Tunnels cables will be a more elegant solution, especially, since they can both export and import simultaneously.
Here's the other end of the system where the fluids are exported and imported:
![2019-05-27_11 03 38](https://user-images.githubusercontent.com/49584508/58405627-8e15da00-8070-11e9-8dab-771ce26b2e4e.png)
I am using IE pipes+a tank for the same reason, because the condenser and the steam turbine work better if they can push fluids on their demand rather than wait for other systems to drain it. That way they don't have any leftovers in the system because they push it all away. If I didn't explain well, please tell, I will try to explain better, maybe visualize it, because I don't speak english natively.

**Comment by rubensworks** [comment]
It's been ages since I've used IC2 myself, so I'm not sure what is going on there.
It's possible that these machines don't expose the proper capabilities for making fluid interaction possible.
Perhaps @GreyMario will be able to determine if this is the case.

**Comment by GreyMario** [comment]
After tinkering with it for a little while, I've come to the following conclusions:

- The underlying mechanism of this is related to https://github.com/CyclopsMC/IntegratedTunnels/issues/163 (and therefore https://github.com/CyclopsMC/IntegratedTunnels/issues/75). This is important.
- The IC2 `Steam Boiler` will automatically output steam to any valid fluid receiver. As such, a `Fluid Interface` is sufficient in this case.
- When a fluid is pushed to a `Fluid Interface`, it will seek other `Fluid Interfaces` on the network, __but only on channel 0.__ This is by the current design; the feature allowing pushed resources to seek the appropriate channel is not yet correctly implemented.

Therefore, your best option to build this, currently:
- Supply `Distilled Water` from whatever source you may be using, and connect it using a `Fluid Importer` using a channel __that is not channel 0.__
- Attach `Fluid Interfaces` on the _same channel_ as your `Distilled Water` source to input fluid to your `Steam Boilers`.
- Attach `Fluid Interfaces` on __channel 0__ to a receptacle for your `Superheated Steam`. I recommend a tank which you can lock/filter to one specific fluid; for example, the Thermal Expansion `Portable Tank`.
- Deliver the `Superheated Steam` to any destination through your method of choice.

The `Steam Boiler` only cares that it can _try_ to export the `Superheated Steam`, and will simply void it if it has a target to export to... even if that target is full.

**Comment by rubensworks** [comment]
Thanks for investigating this @GreyMario!

@AssB0ys Does the described solution work for you? If so, this issue can be closed.
I'll try to give CyclopsMC/IntegratedTunnels#163 a higher priority in any case.

**Comment by AssB0ys** [comment]
I've set the interfaces which are connected to IC2 boilers and the corresponding exporters importers to work on channel 0, the importers which are importing water from a regular tank are still working as they were, but the interface still doesn't accept superheated steam from the IC2 boilers. https://github.com/CyclopsMC/IntegratedTunnels/issues/163 here exporters are mentioned, in my case it is the interfaces that couldn't accept the fluid flow. I edited the issue title because previously I wrongly stated that I was using extractors on IC2 boilers, I am actually using the interfaces. The exporters can accept fluid from an interface connected to a regular tank(for example TE fluid tank filled with superheated steam) no problem. This may seem like a problem on IC2 side, but I think it is the problem with any machine without the internal(output) buffer.

**Comment by GreyMario** [comment]
It's by design that machines, pipes, etc. are allowed to push directly into an Interface or an activated Importer, or to pull from an activated Exporter. This allows other mods (and Integrated subnetworks) to interact on their own terms, enables certain Crafting Interface functions to work, and even provides a way to search all networked resources using programmed cards.

Unfortunately, it currently only sends pushed resources to channel 0. The recent rise in valid use cases for this feature will likely lead to the start of making this feature more robust.
