### ISSUE TITLE
Crashes with storage drawer controller.

### ISSUE THREAD

**Issue by AssB0ys** [CyclopsMC/IntegratedDynamics#734]
#### Issue type:

- :bug: Game crash

____

#### Short description:

I was trying to make a transport system for my storage system which is storage drawers mod with a drawer controller. I used Omni-Dimensional transmitters from the integrated dynamics and couldn't figure out why my setup doesn't work. I am designing my system based on suggestions in this https://github.com/CyclopsMC/IntegratedDynamics/issues/732#issuecomment-496318624 post.
I tested the setup is working when instead of a storage drawer controller I use a regular chest. So I thought the omni-dimensional aren't functioning as I supose them to be. So I attached the cables temporarily for a test like this:

#### Steps to reproduce the problem:

[storage drawer controller] <- ID network one:([ID item interface with id 0] [ID cable] [ID item interface with id 1]) <- ID network two:([ID item importer which imports at id 1] [ID cable] [ID item interface with id 1] -> regular chest
I put test item in the storage drawer system(menril chunks) set the variable cart to this item in the logic programmer and then put this card into the importer(ID network two). Was about to check if this has worked, when I right clicked the chest the game froze.

#### Expected behaviour:
Considering my issue, I want the game not to crash or freeze.
____

#### Versions:

- This mod:  IntegratedDynamics-1.12.2-1.0.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:
crash log.txt
https://gist.github.com/AssB0ys/a044848d4f410065bf82e37792ef9241
latest log.txt
https://gist.github.com/AssB0ys/b25b298af333dcc43bc30804a4ab2e46

**Comment by rubensworks** [comment]
This doesn't seem to be related to storage drawers, but it seems to be crashing due to a self-reference in the ID network. Those should be caught though, so something is going wrong...

**Comment by AssB0ys** [comment]
I'll make a visualization, hope it helps. The schematic is color coded and the color descriptions is in the schematic. Additionally the number on the _interface_ indicates what channel this _interface_ is set to, the number on the _importer_/_exporter_ indicates which channel this _importer_/_exporter_ imports/exports to, the number on the _omni-directional connector_ indicates which group this _omni-directional connector_ belongs to.
Scheme 1. - freezes the game with the results provided above.
Scheme 2. - does not work, the items which are set in the item list variable.
Scheme 3. - Works. This setup is basically the same as two preceding but it doesn't include the storage drawer controller, that's why I assume the storage drawer controller was the cause for the crash in the first scenario and why the second scenario doesn't work.
![aitled](https://user-images.githubusercontent.com/49584508/58630298-a5123180-82e7-11e9-84cc-2d2d7c8c84f0.png)

**Comment by rubensworks** [comment]
@AssB0ys Thanks for your detailed schema! However, I'm not able to reproduce the crash in schema 1 unfortunately. Would it be possible to share your test world where the crash happens? That would make it easier for me to debug it. (preferably without any other mods installed)

**Comment by rubensworks** [comment]
@AssB0ys Actually, I just looked at the code again, and discovered something that could potentially cause a crash like this. I wasn't able to reproduce your crash, so could you try out the latest dev build (IT build 328, see readme) and see if this change fixes your problem?

**Comment by AssB0ys** [comment]
With the dev build(328) the game doesn't crash when I use Scheme 1 anymore. And the Scheme 2 works but I had to replace the id 0 interface for three exporters for each machine set to the corresponding channels. Also the interface which was used for item inputs(Scheme 2. middle column) to the network one(storage system) from other networks(in this case network 2) has to be set to the same channel as the interface attached to the drawer controller, I supposed this was a fix for https://github.com/CyclopsMC/IntegratedTunnels/issues/163 .
As for providing the environment where the crash happened - I was playing Enigmatica 2 Expert 1.64d modpack. I don't understand, do you need a backup of my game world?

**Comment by rubensworks** [comment]
@AssB0ys Thanks for checking, considering this issue fixed then :-)

The unusual log output seems like an unrelated thing, could you open a new issue for this?
