### ISSUE TITLE
Inventory reader: Slot Item slot per variable card

### ISSUE THREAD

**Issue by JJSax** [CyclopsMC/IntegratedDynamics#736]
#### Issue type:
- :heavy_plus_sign: Feature request
Slot Item in the inventory reader sets all variables in a network to the slot currently selected.

____

#### Short description:
If you need to get info about slot 0 and slot 1, currently you need to have 2 inventory readers attached to the inventory, one to read slot 0 and another for 1.  I'm unsure if this is intended or a bug.  I propose that each variable read the slot that was selected in the inventory reader at the time of setting the variable.  

I am aware you can do this with a list, but I found it less intuitive than setting the slot per variable card and causes more variable cards to be needed for the same operation.

P.S. Loving the mod by the way, keep it up!

**Comment by rubensworks** [comment]
Thanks for the issue!

> I propose that each variable read the slot that was selected in the inventory reader at the time of setting the variable.

This would require all aspect settings to be encoded into the variable card as well. While this would be possible to do, it would require massive changes in the ID internals. Additionally, I think this would be too confusing, it makes more sense IMO to have settings stick with the part itself, not the variable card. So I'm going to close this issue.

The list-based solution is indeed more verbose, but still a better solution IMO.
