### ISSUE TITLE
Many Strange behavior of Constant definition List

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#739]
#### Issue type:

- :bug: Bug

____

#### Short description:

1. Ingredients type GUI error
![image](https://user-images.githubusercontent.com/23412916/59550774-85def980-8fa1-11e9-9e21-f6903e7eaecc.png)
2. Recipe type GUI error
![image](https://user-images.githubusercontent.com/23412916/59550786-d9514780-8fa1-11e9-9b14-9c6e648c50be.png)
3. Strange behavior when reselect constant definition List(watch the Steps)
4. Item slot did not disappear, switch type still not disappear
![image](https://user-images.githubusercontent.com/23412916/59550889-6fd23880-8fa3-11e9-95e5-4b7d2a405514.png)
5. Operator type GUI error
![image](https://user-images.githubusercontent.com/23412916/59550916-10285d00-8fa4-11e9-9481-68248a67a4c3.png)

#### Steps to reproduce the problem:

3.1 select the constant definition List
![image](https://user-images.githubusercontent.com/23412916/59550805-26cdb480-8fa2-11e9-95ce-fcabc70a29c5.png)
3.2 add item into list
![image](https://user-images.githubusercontent.com/23412916/59550853-ce4ae700-8fa2-11e9-89d9-5b8e69d17666.png)
3.3 abandon edit list
![image](https://user-images.githubusercontent.com/23412916/59550859-e3277a80-8fa2-11e9-8f97-8adadec8d0dc.png)
3.4 re-select it and try to build fluid list
![image](https://user-images.githubusercontent.com/23412916/59550867-03efd000-8fa3-11e9-9911-0cd09ded79de.png)
Ah, oh...

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.0.14
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2823

**Comment by josephcsible** [comment]
Can you see if this happens with the language set to English (US) and Unicode fonts turned off?

**Comment by rubensworks** [comment]
Related to #641
