### ISSUE TITLE
Unique Name Operator not works

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#741]
![image](https://user-images.githubusercontent.com/23412916/59551881-ae232400-8fb2-11e9-804a-eee3b8b3b7d6.png)
and description is incorrect
![image](https://user-images.githubusercontent.com/23412916/59551901-1c67e680-8fb3-11e9-9f2b-baf0f4af3d63.png)

**Comment by josephcsible** [comment]
I'm not sure why you expect this to work. What do you expect the unique name of a string to be?

**Comment by Flithor** [comment]
uhh, so, how does this operator works?

**Comment by rubensworks** [comment]
This operator returns the unique name of something, like the unique string id of an entity or item.

Does this solve your problem?

**Comment by Flithor** [comment]
so, it only work for entity or Item?

**Comment by rubensworks** [comment]
Also for blocks and fluids I think, there may be others as well that I forgot about.

**Comment by Flithor** [comment]
but this input type name is not clear
