### ISSUE TITLE
"Name" operator input type description is incorrect

### ISSUE THREAD

**Issue by Flithor** [CyclopsMC/IntegratedDynamics#742]
![image](https://user-images.githubusercontent.com/23412916/59551891-f3475600-8fb2-11e9-87c2-dea4011911ae.png)
And cannot work on List type
![image](https://user-images.githubusercontent.com/23412916/59551922-710b6180-8fb3-11e9-9e8c-285a01e8a492.png)

**Comment by rubensworks** [comment]
What is incorrect about it according to you? A list can not be converted to a string, so the error description looks correct to me.

**Comment by Flithor** [comment]
well... so, how about the #607?
And the input type "To String" is a confusing name.

**Comment by rubensworks** [comment]
So your request is to make this operator return a list joined as string and to rename the type "To String"?

**Comment by Flithor** [comment]
yes 
I think “To String” type name should be a valid type list.

**Comment by rubensworks** [comment]
> I think “To String” type name should be a valid type list.

Since the choice of implementation of this non-obvious, I've decided to not make this change. A string.join (#607) would be a better solution.

**Comment by Flithor** [comment]
🤔hmmm...
I still think it should be renamed like" Number, Block, Item, Fluid, Entity", a type list, not just a word "named", "named" still not clear enough and make people feel puzzled.
And the "ToString" function in any program language are can process any type of data and returning a string. A "ToString" that limits the input type looks very strange and counterintuitive.
