### ISSUE TITLE
Energy Battery doesn't supply adjacent Mechanical Squeezer if the Squeezer contains energy

### ISSUE THREAD

**Issue by codewarrior0** [CyclopsMC/IntegratedDynamics#743]
#### Issue type:

- :bug: Bug

____

#### Short description:

The feature of Mechanical Squeezers which draws power from adjacent (or rather, contiguous with other ID blocks) Energy Batteries stops working if the Squeezer has any amount of power in it. This usually happens after disconnecting a direct energy connection to the Squeezer and attempting to power it through the Battery.

#### Steps to reproduce the problem:

1. Place Generator adjacent to Squeezer
2. Insert fuel into Generator
3. Break Generator and put a charged Energy Battery in its place
4. Insert Menril Logs into Squeezer

#### Expected behaviour:

The Squeezer should begin drawing power from the Battery after its internal reserve is exhausted. However, if the internal reserve has a small amount of energy (less than the Squeezer's per tick usage?), the Squeezer will not draw power from the Battery.

I suspect the Mechanical Drying Basin to have the same problem.

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.0.14
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
