### ISSUE TITLE
Random number, Random List element, Absolute

### ISSUE THREAD

**Issue by eadgbear** [CyclopsMC/IntegratedDynamics#744]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I was trying out your mod and realized that I wanted to be able to pick a random element from a list. Seeing that there wasn't any random functionality at all I decided to do my part and add a few functions. It's available at slyons/IntegratedDynamics@0c1afed for your perusal. I tried my best to follow the project coding requirements, but let me know if there's anything I need to add.

* `rand` -> Random from zero to any number type
* `rand2` -> Random from any number to any number (result is type of the second)
* `randElem` -> Random element from a list
* `randBool` -> Random boolean
* `abs` -> Absolute value of a number type

**Comment by rubensworks** [comment]
@slyons Those definitely look useful! They may need some polishing, but feel free to open a PR for these.

**Comment by rubensworks** [comment]
PR in #745.
