### ISSUE TITLE
using count_p on a infinite lazy list crashes the game

### ISSUE THREAD

**Issue by moonheart08** [CyclopsMC/IntegratedDynamics#748]
#### Issue type:

- :bug: Bug

____

#### Short description:
Using count_p on a infinite lazy list (In my case, it counted from 1 to Infinity) crashes the game. 

#### Steps to reproduce the problem:

Use the following setup of cards, and place the last card in a display (Or possibly other things).

1. Integer (1)
2. Operator Increment
3. Lazy List (# 1, # 2)
4. Operator General Not Null
5. count_p (# 3, # 4)

#### Expected behaviour:

The game should not trigger the server watchdog.
____

#### Versions:

- This mod: 1.12.2-1.0.14
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

As it's not a server crash, just a hang, all that's in the logs is the watchdog error. If this is actually needed, @ me

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
