### ISSUE TITLE
menril trees - how do you automate or chop these down more efficiently?

### ISSUE THREAD

**Issue by DoomSquirter** [CyclopsMC/IntegratedDynamics#75]
Silent gems lumber axe, mekanism atomic disassembler in vein mode, eio farming station, none of these grab the tree as a whole, or more than one block at a time.  Using latest in 1.10.2.  

My google-fu failed me and couldn't see any others with same problem so thus I'm probably missing something obvious?

**Comment by rubensworks** [comment]
I probably forgot to add an oredict entry for the second block type that exists within a Menril Tree, which makes some mod think parts of the tree are a different log type.

**Comment by Debonairesnake6** [comment]
Also, the progressive automation chopper does not work with the trees, nor does the forestry farm, also on the 1.10.2 version

**Comment by rubensworks** [comment]
@Debonairesnake6 Please report this to the respective mod's issue trackers.

This issue can actually be closed, as we Menril Tree blocks are registered the proper way in the oredict for them to be handled by treefarms.
