### ISSUE TITLE
Client crash when interacting with Machine Reader on Mechanical Squeezer

### ISSUE THREAD

**Issue by Frikkle** [CyclopsMC/IntegratedDynamics#750]
#### Issue type:

- :bug: Bug

____

#### Short description:

When placing a Machine Reader against a Mechanical Squeezer and interacting with its interface, the client will crash.

Encountered in Enigmatica 2: Expert modpack by a user, reproduced by me. Reproducable in both the modpack as well as just `IntegratedDynamics`, `CommonCapabilities` and `CyclopsCore`.

For more info: see https://github.com/NillerMedDild/Enigmatica2Expert/issues/1259

#### Steps to reproduce the problem:

1. Place a Mechanical Squeezer.
2. Place a Machine Reader against one of its sides.
3. Place a piece of Logic cable against the reader.
4. Open the reader interface.
5. Crash.

#### Expected behaviour:

I would expect the client not to crash :-)

____

#### Versions:

- This mod: `1.12.2-1.0.11`
- Minecraft: `1.12.2`
- Forge: tested both `14.23.5.2836` and `14.23.5.2838`

**Only** other mods present:
- `CyclopsCore-1.12.2-1.2.0.jar`
- `CommonCapabilities-1.12.2-2.2.1.jar`

#### Log file:

See logs [here](https://paste.dimdev.org/acacunezuc.mccrash)

**Comment by rubensworks** [comment]
This has been fixed a while ago, please update to the latest mod versions for CC, CommonCaps and ID, as you're running multiple versions behind.

**Comment by Frikkle** [comment]
Thanks for the update and sorry for that. I couldn't find this in the issue tracker but apparently I haven't looked far enough. We'll update.

**Comment by rubensworks** [comment]
No worries, I'd rather have duplicate bug reports than unreported bugs :-)
