### ISSUE TITLE
Stack Size Lost for Recipe Ingredients set to Ore Dictionary Match-Mode

### ISSUE THREAD

**Issue by JHawkley** [CyclopsMC/IntegratedDynamics#752]
#### Issue type:

- :bug: Bug

____

#### Short description:

When creating a recipe where an input ingredient is set to, "Match by Equivalent Ore Dictionary values," the resulting recipe card fails to record the stack-size of the ingredient.  This problem only seems to arise when Ore Dictionary matching is used.  All other modes seem to work correctly.

#### Steps to reproduce the problem:

1. Create a recipe in the Logic Programmer that requires at least one input ingredient with an ore dictionary entry.  Ensure the recipe specifies a stack-size greater than 1 for the ingredient.
2. Set the ore-dictionary-compatible item to "Match by Equivalent Ore Dictionary values".
3. Create a card with the recipe and observe the "value" entry in the tool-tip.

#### Expected behaviour:

The recipe card should correctly reflect the stack-size of the item specified in the recipe.

____

#### Versions:

- This mod: 1.0.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2836 (Enigmatica 2: Expert)

#### Log file:

Have [some annotated screenshots](https://imgur.com/a/n5dBRWe), instead.

**Comment by rubensworks** [comment]
Please update to the latest mod version, you're running a few behind, and let me know if the problem still occurs.
This has probably been fixed already in https://github.com/CyclopsMC/IntegratedCrafting/issues/33.

**Comment by JHawkley** [comment]
I was able to update to version 1.0.16 (Enigmatica 2: Expert made a new release with a new version of ID, finally), but a quick test shows that the issue seems to still affect that version as well.

I should also note that my pack does not have Integrated Crafting installed, at the moment.  This issue affects only Integrated Dynamics and the creation of recipes in the Logic Programmer; nothing related to making use of the recipe elsewhere.

All I'm doing is creating the recipe and inspecting the resulting variable card from the Logic Programmer.

Also, I believe you have all the information you need to verify the issue yourself.  I'm not sure what information you feel you lacked; steps to reproduce and verify the issue were provided.  Were you unable to follow them?

**Comment by rubensworks** [comment]
> I should also note that my pack does not have Integrated Crafting installed

Ah ok, my bad then, I thought this was related to IC.

In that case this is indeed an issue with ID, and more specifically the encoding of oredict-based recipe entries.

**Comment by rubensworks** [comment]
This will be fixed in the next update. Thanks for reporting, and my apologies for the confusion before.
