### ISSUE TITLE
Value input method that doesn't involve manipulating cards

### ISSUE THREAD

**Issue by moonheart08** [CyclopsMC/IntegratedDynamics#753]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

As of now, there is no good way for a string, integer, long, list, or double to be entered via a UI. What i'd like to see is a block or network component that provides a way to input these data types easily, without having to modify a card or use some other roundabout method.

**Comment by rubensworks** [comment]
> a block or network component that provides a way to input these data types easily

How do you suggest to do this then? If not with a UI and variable cards?

**Comment by moonheart08** [comment]
The idea was to use a UI, not do it without. a UI is probably the best way to do it.

**Comment by rubensworks** [comment]
Not sure if I'm following then. How would this be different to the existing logic programmer where you can create values for these primitive types?

**Comment by moonheart08** [comment]
It would be a user friendly input, essentially, like a prompt, instead of having to use the logic programmer to edit cards.

**Comment by rubensworks** [comment]
Ok, you talk about a block or network component to open such a prompt. How do you suggest connecting these values with operators/writers then, if not via variable cards?

**Comment by moonheart08** [comment]
It would be done with variable cards. I'm suggusting that it shouldn't be done by modifying a constant.

**Comment by rubensworks** [comment]
I'm sorry, but I really don't understand what you are suggesting. This sounds exactly like the existing logic programmer functionality to me.

Could you try re-explaining the whole thing with a motivating use-case, e.g., where you use your idea in a in-game build?

**Comment by moonheart08** [comment]
What i am looking for is a placeable block that functions as a way to input arbitrary values into ID, functioning as a string, int, etc input.

The purpose of it in realworld builds would be to provide a nice interface that doesn't involve directly manipulating cards to input data, and instead only having to type the data into a UI.

This would allow for, say, inputting a target player's name into a network that retrieves information about a player.

**Comment by rubensworks** [comment]
Ok, so if I understand correctly, you want to have some kind of terminal that acts as a proxy, and variables can be bound to this proxy?

Does #213 sum up your feature request? If so, I'll close this one.

**Comment by moonheart08** [comment]
Yes it does. Closing in favor of #213
