### ISSUE TITLE
Clearing Variable IDs

### ISSUE THREAD

**Issue by Furious1964** [CyclopsMC/IntegratedDynamics#759]
How do I clear this as I had to redo everything and now my variable IDs are up to 50. I want to make them start at 1 please.

**Comment by rubensworks** [comment]
That's not possible, and should not be possible either. Why do you want to have specific variable IDs?

**Comment by Furious1964** [comment]
Because I goofed up some stuff automating Astral Sorcery Crystal Growth and ended up with a lot of the variables either not working or out of sequence. I'm an OCD sufferer and it would help if I can clear the list and have the variable IDs start again from 0.

**Comment by rubensworks** [comment]
Well, you could delete the `data/integrateddynamics_GlobalCounterData.dat` file in your world at your own risk, this should reset the counter. But I'm not going to add a feature to easily reset that counter, as that would cause more problems than it would solve.

**Comment by Furious1964** [comment]
Thank you, Sir.

**Comment by GreyMario** [comment]
I'd like to mention, though it's a fair month late, that you can overwrite a Variable Card which already has an ID number with any other programming, and it will keep that ID number.

This means you won't have to scrap a card and make an entirely new one and by doing so incrementing the ID number.
