### ISSUE TITLE
Crash on inserting variable card on item importer

### ISSUE THREAD

**Issue by Tri-eDge17** [CyclopsMC/IntegratedDynamics#760]
#### Issue type:

- :bug: Bug

____

#### Short description:

I'm experiencing a crash when inserting variable cards to system. The system involves reading aspects inside a thaumcraft warded jar.

#### Steps to reproduce the problem:

1. I use a block reader to read current aspect count of a thaumcraft jar from nbt list.
2. Output of that variable card is shown as an integer in a display panel.
3. I setup a chest to hold item to fill that specific aspect.
4. I check when the aspect is less than 250 this value is checked with another value. (5)
5. I have an alembic that will melt the item from the chest. Variable cards are used to check whether the alembic already holds a single item, or aspect.
6. With 4 and 5, cleared, a new item is inserted.
7. This pattern is repeated for different aspects. Only 2 alembics are present with separate channels.
8. Import buses from the mod are used to insert the item to the item interface once 4 and 5 is true. Buses are set to only transfer 1 item, and set to the specific channel.
9. Upon insertion of card in the import bus, second card from a different bus usually crashes the game.
10. Upon restarting the world, the whole system does not work anymore at all.
11. Variables are throwing random errors like variable not being boolean/string, display panels still showing last value even after removing the variable card, etc.

#### Expected behaviour:

Each bus will be handle the card. No crashes
____

#### Versions:

- This mod: 
IntegratedDynamics-1.12.2-1.0.17
IntegratedTunnels-1.12.2-1.6.10
CommonCapabilities-1.12.2-2.4.4
Thaumcraft-1.12.2-6.1.BETA26
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2836
modpack is Enigmatica2Expert

#### Log file:

https://pastebin.com/b1gMivX4

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by Tri-eDge17** [comment]
I've narrowed the issue down further. Seems like it crashes everytime the variable I made, the one that checks if Aspect Count < 250 is used with another variable to form an AND operation. Maybe that would help.

**Comment by Tri-eDge17** [comment]
I think I pin pointed more why its crashing. The variable outputs an integer when the expected value is a boolean. That is why it crashes at an importer. Weirdly enough, when I insert this same variable in a display panel it shows the actual boolean value

![image](https://user-images.githubusercontent.com/53266496/61932182-4bf80e80-afb5-11e9-9c48-77839c56185a.png)

**Comment by rubensworks** [comment]
@ronaldjan17 Could you share some more details on the exact setup of the first step?

> I use a block reader to read current aspect count of a thaumcraft jar from nbt list.

I suspect you are using an aspect to get the NBT of the block, getting a list from a certain tag by a certain string key, and grabbing a certain list element. But I don't see how you do this exactly, so I can't see where things are going wrong.
