### ISSUE TITLE
Crash when changing out mesh in Auto Sieve attached to IT/ID network

### ISSUE THREAD

**Issue by FlameofChaos** [CyclopsMC/IntegratedDynamics#761]
#### Issue type: Crash

- :bug: Bug

____

#### Short description:

Changing out the mesh in an auto sieve hooked up to an item interface --> logic cable --> item exporter system causes crash. Upon reloading, the ID/IT network needs to be broken then replaced to continue functioning again.

#### Steps to reproduce the problem:

1. Let an auto-sieve run with a mesh.
2. Replace mesh with enchanted mesh.
3. Crash
4. Have to replace ID/IT network.

#### Expected behaviour:

1. Let an auto-sieve run with a mesh.
2. Replace mesh with an enchanted mesh.
3. That's it.

____

#### Versions:

- This mod: No clue (Playing E2:E Skyblock)
- Minecraft: 1.12.2
- Forge:  No clue (playing E2:E Skyblock)

#### Log file:

https://pastebin.com/v86ZtTiM

**Comment by rubensworks** [comment]
You're running quite a few versions behind on the Common Capabilities mod. Could you try updating?
