### ISSUE TITLE
Crafting book-quest drying basin in RFTools Modular Storage doesn't count.

### ISSUE THREAD

**Issue by Moleculor** [CyclopsMC/IntegratedDynamics#764]
#### Issue type:

- :bug: Bug

Integrated Dynamics 1.0.16, so, sorry if this has been fixed between then and now?

____

#### Short description:

The book has 'quests' you can do for rewards. Crafting a drying basin in an RFTools Modular Storage block doesn't count as 'crafting' the item, which means it isn't checked off in the book.

#### Steps to reproduce the problem:

1. Get the Integrated Dynamics book. 
2. Look on page 6/6 of Menril Basics. See the 'Advancements' listed. 
3. Construct a Drying Basin using a Modular Storage block from RFTools. 

#### Expected behaviour:

The drying basin should get checked off. It doesn't.

#### Versions:

- This mod: 
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

Enigmatica 2: Expert 1.67.

#### Final note:

I did test by crafting it in a regular crafting table, and the advancement was awarded as expected. I did not try other crafting methods.

**Comment by rubensworks** [comment]
This is a problem in RFTools: https://github.com/McJtyMods/RFTools/issues/1469
Not much I can do about it on my end, sorry.
