### ISSUE TITLE
Blockstate support for blockreader

### ISSUE THREAD

**Issue by goreae** [CyclopsMC/IntegratedDynamics#765]
I'm trying to automate Hearth Well with integrated dynamics, and I'm running into issues that prevent me from getting it absolutely perfect, and all of those issues are that Hearth Well rarely uses NBT data to store its data. Instead it uses lots of blockstates. Cores use blockstates to store which shard is inserted, grit vases use blockstates to store tree size, and living branches use blockstates to store liveliness. Some way to read blockstates would help a ton with automation with this mod.

**Comment by rubensworks** [comment]
The metadata aspect might help for now.

**Comment by rubensworks** [comment]
Note to self: this will probably require exposing an aspect of type operator, with as input a string, as as output _any_. Similar to how the crafting reader works.

Alternatively, just add an operator to go from block to NBT tag compound with all blockstate entries.
