### ISSUE TITLE
Apply2 Operator don't work properly

### ISSUE THREAD

**Issue by AmberArr** [CyclopsMC/IntegratedDynamics#767]
#### Issue type:

- :bug: Bug

____

#### Short description:

Using "Apply2" with operators that take 3+ arguments (e.g. "replace" and "choice") gives an operator that takes more arguments than it should. Then using "Apply"s to feed this operator with arguments that are more than it should have, the server crashes.

#### Steps to reproduce the problem:

Every name with a type signature is a variable card. The types are what I expect.

```
replace :: String -> String -> String -> String
old :: String
new :: String
tgt :: String
f1 :: String -> String      -- "String -> String -> String" in display panel
f1 = apply2 replace old new
result :: String            -- "String -> String" in display panel
result = f1 tgt
WTH :: I_DONT_KNOW_BUT_IT_JUST_TURNS_UP
WTH = result tgt            -- the game crashes when put into display panel
```
If I just use "Apply" for every argument, it works perfectly.

#### Expected behaviour:

The `result` will evaluate to the result string and `WTH` won't pass in the logic programmer.
____

#### Versions:

- This mod: 1.0.18 (IntegratedDynamics-1.12.2-1.0.18.jar)
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

[crash-reports](https://pastebin.com/5eTBSUaX)

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
