### ISSUE TITLE
[Issue] Compatibility adding the mod to WC Tech and Magic Modpack 1.0.6

### ISSUE THREAD

**Issue by Indigo02074** [CyclopsMC/IntegratedDynamics#768]
I'm not sure what is the issue, but I tried to add the mod to WC Tech and magic modpack 1.0.6 and I got this error

https://paste.dimdev.org/ayokabutid.mccrash

I hope you can fix it or at least tell me how to fix the issue, please.

**Comment by rubensworks** [comment]
Please update to the latest ID version, you are running a couple of versions behind.
