### ISSUE TITLE
Smart Pressure Plate Advancement Is Fulfilled Under Incorrect Conditions

### ISSUE THREAD

**Issue by Trainerredstone7** [CyclopsMC/IntegratedDynamics#770]
#### Issue type:

- :bug: Bug

____

#### Short description:

The Smart Pressure Plate advancement is fulfilled by simply applying an entity to the Named operator and placing it in the first slot of a Redstone Writer, despite the fact that the writer can't accept the input. Trying to complete the advancement normally, for example by piping this operator into an Equals operator with a string applied, does not result in the completion of the advancement.

#### Steps to reproduce the problem:

1. Create an Entity variable card from an Entity Reader.

2. Create a Named operator using the Entity variable card.

3. Place this card in the first slot of a Redstone Writer and observe that the Smart Pressure Plate achievement is obtained.

#### Expected behaviour:

The advancement should not be obtained by placing this card in the writer, but rather by piping this card into an Equals operator with a string applied, then placing this new card in the writer.

____

#### Versions:

- This mod: 1.12.2-1.0.17
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

N/A

**Comment by rubensworks** [comment]
Just tested, and this looks wrong indeed.
Thanks for reporting, will fix it right away!
