### ISSUE TITLE
Crash when using Ingredients.with_fluid

### ISSUE THREAD

**Issue by eadgbear** [CyclopsMC/IntegratedDynamics#772]
#### Issue type:

- :bug: Bug

____

#### Short description:

When trying to make a recipe with fluid ingredients opening the crafting menu results in a crash

#### Steps to reproduce the problem:

1. Ingredients (intentionally left blank) -> Var1
2. Integer: 1000 -> Var2
3. Fluid: Ethanol -> Var4
4. Fluid: Ethylene -> Var5
5. Ingredients.with_fluid: Var1, Var2, Var3 (blank with 1000 ethanol) -> Var6
6. Ingredients.with_fluid: Var1, Var2, Var5 (blank with 1000 ethylene -> Var7
7. Recipe.with_io: Var6, Var7

#### Expected behaviour:

A recipe that with input 1000 Ethanol and output 1000 Ethylene. This is meant to build up to multiple fluid recipes but I can't get this to work without crashing so I can validate it.

____

#### Versions:

- This mod: 1.0.18 (1.0.8 crafting, 1.0.9 terminals)
- Minecraft: 1.12
- Forge: 14.23.5.2838

#### Log file:

https://gist.github.com/slyons/f8c537f1b03de52d8df324a4fe516864

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
Probably not a bug in ID, but in ITerminals. I'll try to release a new version soon.
