### ISSUE TITLE
Breaking a Logic Cable duplicates it

### ISSUE THREAD

**Issue by LaVidaYokel** [CyclopsMC/IntegratedDynamics#78]
Breaking one Logic Cable drops two.

IntDyn 1.10.2-0.6.1
IntTun 1.10.2-1.0.0
Forge 12.18.2.2107

**Comment by rubensworks** [comment]
How are you breaking it, pickaxe, hand or wrench?
Does the cable have any other multiparts on it?

**Comment by LaVidaYokel** [comment]
I tried breaking with several different tools, items and an empty hand.  I tried breaking just the logic cable as well as logic cables attached combined with importers, interfaces and exporters from Tunnels.
