### ISSUE TITLE
Player simulator rightclicking on tree and harvesting not working?

### ISSUE THREAD

**Issue by Kuperus** [CyclopsMC/IntegratedDynamics#781]
#### Issue type:
- :question: Question
____
#### Question:

In vulcano block, i am trying to harvest Flawless and Weakened diamonds from a diamond tree using the player simulator rightclicking a sickle on that tree, the beeds in the trees do disappear (i put sickle in seperate chest) and that seems to be harvesting, only i cannot see where the diamonds are going.

they can`t go anywhere except in the chest where the sickle is, (nothing else is connected to the network. but no diamonds appear.

is there a setting or thing i need to set within the player simulator?

if the player uses the sickle, the 2 diamonds are automatically placed in the player inventory.

any suggestions or comments?

**Comment by Kuperus** [comment]
Note, q2: is there a site where all the options you can set within the machines are documented?

**Comment by rubensworks** [comment]
This sounds like something specific to the mod you are interacting with. I suggest you ask this to its mod author. Possibly they are blocking automated interaction.

All mod info can be found in the ingame book, or here https://integrateddynamics.rubensworks.net/book/

<blockquote><img src="https://integrateddynamics.rubensworks.net/book/assets/icons/integrateddynamics__cable__0.png" width="48" align="right"><div><strong><a href="https://integrateddynamics.rubensworks.net/book/">Integrated Dynamics - On the Dynamics of Integration - On the Dynamics of Integration</a></strong></div><div>Web-version of the On the Dynamics of Integration book, from the Integrated Dynamics mod for Minecraft</div></blockquote>
