### ISSUE TITLE
Tutorial Rewards are not given on server, works fine in client

### ISSUE THREAD

**Issue by Olfi01** [CyclopsMC/IntegratedDynamics#782]
#### Issue type:

- :bug: Bug

____

#### Short description:

When clicking the claim button, it turns green as it should, but I don't get the items.

#### Steps to reproduce the problem:

1. Install SkytopiaByOlfi01 on Techniclauncher
2. Finish any tutorial quest on a server
3. Attempt to claim rewards

#### Expected behaviour:

Obtaining the items that are marked as rewards

____

#### Versions:

- This mod: 0.7.14
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Log file:

https://pastebin.com/bi1ZnNP1

**Comment by rubensworks** [comment]
Sounds like a modpack issue. Could you try reproducing this without any other mods installed?
