### ISSUE TITLE
Crash with Energy Interface and RFTools Powercell

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [CyclopsMC/IntegratedDynamics#792]
#### Issue type:

- :bug: Bug

____

#### Short description:

Using an energy interface on a Powercell, then opening a Storage screen connected to it crashes the server

#### Steps to reproduce the problem:

See above

#### Expected behaviour:

Shouldnt crash

____

#### Versions:

- Mods: 
      Integrated Crafting: 1.0.8
      Integrated Dynamics: 1.1.1
      Integrated Terminals: 1.0.12
      RFTools: 7.72
- Minecraft: 1.12
- Forge: 14.23.5.2836

#### Log file:

https://paste.dimdev.org/hujuwezafo.mccrash

Edit: Forgot to say, love your mods. Never thought I'd enjoy what is essentially in-world programming. Keep being awesome

**Comment by rubensworks** [comment]
Thanks for reporting this, but this looks like an error in RFTools.
Could you report it over on their issue tracker (and link back here)?
