### ISSUE TITLE
Redstone Reader clock update question

### ISSUE THREAD

**Issue by Pultex** [CyclopsMC/IntegratedDynamics#796]
#### Issue type:

Does the redstone readers clock make redstone chunk updates all the time ?

____

#### Question:

All Redstone Readers have an internal clock set to 1 second, I am not sure if you can disable it completely by setting 0 or an negative number like -1.

I just want to not have unneeded updates to chucks happening in complex networks in chucks causing chunk errors and corrupting themselves. 

Had this happen in DW10 pack some time ago with immersive engineering's redstone system and did not realize their clock was bugged at the time.

**Comment by GreyMario** [comment]
There is a PLUS button on the Redstone Clock "aspect" of the Redstone Reader that can be used to configure it. _All_ aspects of Readers or Writers that can be _configured_ will have this same plus button.

There is no way to disable the Redstone Clock aspect. However, there is no _need_ to. The Redstone Clock aspect is only calculated when a part of the network tries to get the value from that aspect, so it will not create a _ticking tile entity_ to cause lag or force the network to chunk-load unnecessarily.

**Comment by rubensworks** [comment]
@Pultex Indeed, what @GreyMario says is correct. As long as you don't use the clock aspect anywhere, it will not be calculated, and will not cause chunk updates.

**Comment by Pultex** [comment]
Thanks
