### ISSUE TITLE
Outdated API for RefinedStorage Betas

### ISSUE THREAD

**Issue by utoc** [CyclopsMC/IntegratedDynamics#80]
Hello!

The new Refined Storage beta versions have made some changes in the API and caused a crash when I right clicked on an ID inventory reader.  

Crash here: http://pastebin.com/RjXd2Auv

Running  IntegratedDynamics-1.10.2-0.6.1, CommonCapabilities-1.9.4-1.2.0, CyclopsCore-1.9.4-0.8.0, FML 2109 and refinedstorage-1.2-beta3

**Comment by rubensworks** [comment]
@raoulvdberge, @way2muchnoise, what is the status on the RS autocrafting rework?
Is it already stable enough to update the ID compatibility?

**Comment by raoulvdberge** [comment]
@rubensworks yes! No major API changes will occur, most likely.
