### ISSUE TITLE
Advice Troubleshooting Crafting Recipe Issue

### ISSUE THREAD

**Issue by TheCowKingmoo** [CyclopsMC/IntegratedDynamics#803]
#### Issue type:

- :question: Recipe Setup T-Shoot

____

#### Question:

Getting a lot of errors in my logs from ID and ID add-ons. From what I can tell all of these items are not craftable in game. Any idea what I can do to go about fixing this? This is a rather large modpack with some other mods items being modified with crafttweaker, not nothing from ID/IT. Link to relevant part of log below. 

https://pastebin.com/KRvrewMC

**Comment by rubensworks** [comment]
These are just warnings, not errors.
They just mean that no recipe for certain items could be found for inclusion in the book.
So unless you want to modify the book yourself, these warnings can be safely ignored.
