### ISSUE TITLE
Variable card duplicating, crashing game

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedDynamics#806]
#### Issue type:

- :bug: Bug

____

#### Short description:

A piped operator to another operator causes card to enter variable store and stay in inventory. Card also causes crash when used in network.

#### Steps to reproduce the problem:

1. ... See Video: https://imgur.com/G4QLxrz. Top card is the pipe card, taking the first card from second row as first input and first card of third row as second input.  Placed all cards in variable store and then materialized the pipe. Moved original cards to chest, using materialized card in display. Attempting to apply the item card did nothing (after menu closed, did not have apply card)

#### Expected behaviour:

In game error or boolean representing greater than 32 of a given item.
____

#### Versions:

- This mod: Integrated dynamics 1.12.2-1.1.1
- Minecraft: 1.12.2
- Forge:  14.23.5.2847

**Comment by rubensworks** [comment]
Are you sure that's the original crashlog? Because I don't see a full stacktrace in there.
There only is:
```
java.lang.ArrayIndexOutOfBoundsException
```

I can't do anything with just this information unfortunately...

**Comment by Kyiki-Nasoka** [comment]
My apologies, that crash was after remaking it, which doesn't seem to include that. This is from the original crash which does have a stack https://pastebin.com/iua0UU6k

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/iua0UU6k">2 - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Thanks!
