### ISSUE TITLE
The Battery, Squeezer and Drying Basin need GUI options

### ISSUE THREAD

**Issue by KollinsPlays** [CyclopsMC/IntegratedDynamics#808]
#### Issue type:

- :heavy_plus_sign: Feature request

Since a Logic Cable attaches to the Generator, Battery, Squeezer and Drying Basin, it seems like something is missing when there is no energy movement or GUI controls related to the network. The machines don't seem to do anything special when on the network, so why does a logic cable show a connected texture?
____

#### Short description:

 A modded Minecraft machine like a TE Redstone Furnace has plain old redstone and input/output control options, but what if ID machines, like the Mechanical Squeezer, had a slot in the GUI for a variable card to control it? Why doesn't a generator automatically feed energy into the network or a squeezer automatically draw from one? With Integrated Tunnels, why not have Item busses built in?

Energy wouldn't even need full bus function, just a setting for energy channel so Generators automatically feed that channel, Batteries can store energy on different channels and the Squeezer/Basin draw energy from a channel.

Batteries should also present room for more energy if they are on the same network as another battery that has room for energy, so if you put FE into 1 battery on a network and it fills up, it will send additional FE to any other batteries that aren't full. Batteries need a similar function for energy output where if an empty battery is set to output or has some mod's extraction cable, it will always present some energy if another battery on the network has energy.

With IT installed, machines should just do Item Import and Export so you could set logic on a Squeezer or Generator to take in or send items to the network as a built in function accessible from the GUI instead of having to add busses to them. How cool would it be if an ID machine didn't need busses cluttering the sides and could function with just a logic cable adding it to a network?

**Comment by rubensworks** [comment]
> How cool would it be if an ID machine didn't need busses cluttering the sides and could function with just a logic cable adding it to a network?

This would take away the whole reason for using ID IMO.
I don't want to make GUIs too powerful in this mod, so there's still a reason for (semi-complex) making ID networks.

So I prefer not to implement this into this mod.

**Comment by KollinsPlays** [comment]
> This would take away the whole reason for using ID IMO.
> I don't want to make GUIs too powerful in this mod, so there's still a reason for (semi-complex) making ID networks.
> So I prefer not to implement this into this mod.

OK, I see your point, but it seems these blocks should be better integrated with their own mod. What about just the variable card slot for machine controls and/or the ability to set an energy channel? Literally the first thing I did when I discovered ID was turn my Squeezer into a Mechanical Squeezer, put down a Generator, Logic Cable, Battery, Logic Cable, Mechanical Squeezer and then stare at it wondering why everything looked connected but the generator wasn't sending, the battery wasn't storing and the Squeezer wasn't taking power. The knowledge that you can disable a Squeezer or make the battery auto output energy with a redstone signal is not anywhere in tooltips or the GUI and is buried in the manual so it took me a long time to find out this was even possible. I'm also frustrated that a Squeezer or Basin can only be shut off with a high redstone signal. If I set up logic so it only works if an inventory is low, but pull the wrong variable out of the store or break the wrong cable, it turns back on.  It would just be more intuitive to have a spot for a variable card to control it right in the GUI. The same with energy channels and having to isolate a battery from the rest of the network and put an Interface on it to make it store energy on another channel.

**Comment by rubensworks** [comment]
> it seems these blocks should be better integrated with their own mod. 

Feel free to send in a PRs for the parts you don't like.
