### ISSUE TITLE
RS reader or writer: server crash

### ISSUE THREAD

**Issue by demethan** [CyclopsMC/IntegratedDynamics#81]
When you have a module that give out a 'corrupted netowork' output, if you break it, il will crash the server. 

http://pastebin.com/LHYaH6cW

ver 1.10.2 -0.6.1
forge 2107

**Comment by rubensworks** [comment]
Can you give some more details on how to reproduce this?

**Comment by demethan** [comment]
Seems fixed in 0.6.2  Can't reproduce.
