### ISSUE TITLE
Pretty please make variable cards editable

### ISSUE THREAD

**Issue by FluffyDiscord** [CyclopsMC/IntegratedDynamics#810]
Hi, I am using variable card List to make a filter for items. It gets tiring quickly when you have to add each item again once you need to add one more to the filter. I have no idea how hard it might be, but editable variable cards would be awesome to have

**Comment by RandomSpaceship** [comment]
Are you talking about #357?

**Comment by rubensworks** [comment]
Yep, this sounds exactly like #357.
