### ISSUE TITLE
I hope to add variable card to Integrated Dynamics.

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedDynamics#812]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

When I add output to technology modules such as Immersive Engineering, the variable card needs to be modified again due to insufficient previous items, but I can only redo or link it with the new addition, hoping to add the content of the variable card to modify

**Comment by rubensworks** [comment]
Duplicate of #357
