### ISSUE TITLE
Visual Glitch When Reading 'On The Dynamics of Integration"

### ISSUE THREAD

**Issue by janagyjr** [CyclopsMC/IntegratedDynamics#817]
#### Issue type:

- :bug: Bug

____

#### Short description:
While reading the book a visual glitch introduces artifacts and other rendering strangeness.

#### Steps to reproduce the problem:

1. Load up 1.12.2 modpack with ID
2. Open the book
3. ???
4. Report bug

#### Expected behaviour:

I should be able to read the book without any sort of rendering artifacts.

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.1.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Screenshot
![2020-02-28_04 14 42](https://user-images.githubusercontent.com/23646259/75510126-d0928b80-59e1-11ea-836c-ce3219a2c341.png)

**Comment by rubensworks** [comment]
Can you reproduce this without any other mods installed?

Can you specify the artifacts you are seeing?

**Comment by janagyjr** [comment]
Can you not see the screenshot? I'll highlight the artifacts. I have not tried this w/o other mods installed. This is my first time ever using Integrated Dynamics in a modpack. 
![highlighted-errors_2020-02-28_04 14 42](https://user-images.githubusercontent.com/23646259/75561750-6d374680-5a3f-11ea-915f-54907b348b1a.png)

The ceiling is a complete unit, there are no holes in the floor, shouldn't be seeing nebulous water-looking shadows or unmined ores hanging through blocks. When I highlight over one of the elements in the ID book, however, the artifacts disappear as if on a toggle.

**Comment by rubensworks** [comment]
> I have not tried this w/o other mods installed.

That's what I thought, but can you try it without other mods? :-)
That will help me pinpointing the issue.

**Comment by janagyjr** [comment]
No visual glitches. Same MC, ID, Forge versions, however may be different cyclopscore and commoncapabilities versions.

![2020-02-28_16 23 19](https://user-images.githubusercontent.com/23646259/75566090-09b11700-5a47-11ea-805f-3e35672c114b.png)
![2020-02-28_16 23 48](https://user-images.githubusercontent.com/23646259/75566092-0a49ad80-5a47-11ea-934b-61500a22fc18.png)
![2020-02-28_16 25 44](https://user-images.githubusercontent.com/23646259/75566094-0ae24400-5a47-11ea-9b21-e7f0b62529ec.png)

**Comment by rubensworks** [comment]
Ok, in that case it sounds like some other mod (possibly with a block in your base) is causing the problem.

**Comment by janagyjr** [comment]
Could Optifine be the cause? I have to use optifine for large modpacks.

**Comment by janagyjr** [comment]
Removing optifine seems to have fixed things.
