### ISSUE TITLE
[Request] Disable Menril Spawn

### ISSUE THREAD

**Issue by belathus** [CyclopsMC/IntegratedDynamics#82]
I did see that we can adjust the frequency of menril spawning, but I'd like to totally disable it. I don't see the capability to do this already.

Thanks!

**Comment by rubensworks** [comment]
I thought this was already possible by setting the frequency to 0, but apparently this does not work.
I'll add this for next update.

**Comment by belathus** [comment]
Yeah, I tried -1 and 0, but both caused crashes when trying to generate a world.

**Comment by rubensworks** [comment]
Usually I always properly implement support for things like these, apparently I forgot it here :/
