### ISSUE TITLE
About Mono-Directional Connector unusable after disassembly

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedDynamics#820]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Mono-Directional Connector is normal lying when it is first placed. But when I uninstalled it, I couldn't continue to use it in the same place.
This feature may be necessary, but I think it's a bit of a problem.
![image](https://user-images.githubusercontent.com/35490649/75555651-9378d880-5a77-11ea-9d0e-49b001a5e002.png)

**Comment by rubensworks** [comment]
Can you clarify? I don't understand the problem.

**Comment by Gan-N** [comment]
1.First use, Mono-Directional Connector works fine
![image](https://user-images.githubusercontent.com/35490649/75598116-758d9100-5ad4-11ea-9b2d-dc95756a73aa.png)
2.When I uninstalled and installed the Mono-Directional Connector, it didn't work properly.
![image](https://user-images.githubusercontent.com/35490649/75598227-2005b400-5ad5-11ea-9362-81c1f1c0ff80.png)

In my understanding, as long as two Mono-Directional Connectors are facing each other, it should work.

**Comment by rubensworks** [comment]
Thanks for clarifying!
