### ISSUE TITLE
NBT list string showing as NBT

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedDynamics#822]
Looking for text in written book shows pages to contain a list of strings, but when attempting to use NBT.List_Tag (closest match) this returns empty brackets instead of a list of strings.

Recreate is make a Book and Quill with text on first page, and either drop on ground or place in item frame. Going through tags "Item" to "tag" to "pages" returns - {} and - {} instead of the expected list of strings. Image shows each step on Display, top to bottom left to right. Last item on second row is a Get with Integer one. This was done with an unsigned book as well as a signed book with same result

![NBT_List_String](https://user-images.githubusercontent.com/60371271/75631656-afd55c00-5bc2-11ea-973e-b617735a59b5.PNG)

**Comment by rubensworks** [comment]
Thanks for reporting. I'm going to merge this issue into #510.
