### ISSUE TITLE
Energy Batteries in inventory lose all power between saves

### ISSUE THREAD

**Issue by md5i** [CyclopsMC/IntegratedDynamics#823]
#### Issue type:
Bug
____

#### Short description:

Any ID Energy Battery (save for the creative version) in one's invententory will, after saving and reloading, have it's power reset to zero.

#### Steps to reproduce the problem:

To test, I started a new Minecraft instance with just ID and its dependencies.  In creative mode I granted myself eight filled batteries: two 1M, two 4M, two 16M, and two creative.  I placed one of each on the ground and kept one of each in my inventory.  I then exit/saved, then reloaded the game.  Afterward, all batteries that were in my inventory had zero power (except for the creative).  The batteries on the ground, after being picked up, still retained their energy.

#### Expected behaviour:

Batteries in inventory should keep their power between saves.
____

#### Versions:

- This mod: 1.12.2-1.1.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by md5i** [comment]
Likely caused by this commit: https://github.com/CyclopsMC/IntegratedDynamics/commit/c3c4b8b6f5116105810a746e1b9c9fd1e2f31488

**Comment by rubensworks** [comment]
Thanks for reporting! That commit does indeed seem to be the cause.
