### ISSUE TITLE
Materializing list of Crafting Recipes causes Crash

### ISSUE THREAD

**Issue by jeddings123** [CyclopsMC/IntegratedDynamics#825]
#### Issue type:

- :bug: Fatal Crash

____

#### Short description:

Trying to materialize an `Apply` with a list of recipes from the aspect `List Recipes by Input` causes a fatal crash to my game.

#### Steps to reproduce the problem:

Apply (Item("Crystallized Menril Chunk), Operator(List Recipe by Input))

#### Expected behaviour:

A normal error code or the recipes requested, not a complete crash.

____

#### Versions:

- This mod: 1.1.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

https://pastebin.com/1SvMHu1U

https://cdn.discordapp.com/attachments/386054223688630272/685118365462822992/unknown.png
https://cdn.discordapp.com/attachments/386054223688630272/685118449965596716/unknown.png

**Comment by rubensworks** [comment]
Thanks for reporting!
