### ISSUE TITLE
The omni directional connector cannot provide energy for the integrated tunnels in the lower bound after the energy consumption is turned on

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedDynamics#826]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. When energy consumption is turned on, the energy is placed in the main world (dimension 0), and the fluid importer is placed in hell (dimension-1). It will prompt for lack of energy

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.1.2、IntegratedTunnels-1.12.2-1.6.10
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2838

#### Log file:

The omni directional connector cannot provide energy for the integrated tunnels in the lower bound after the energy consumption is turned on
![image](https://user-images.githubusercontent.com/35490649/76155475-4ce64680-6127-11ea-95d5-290835d8ffda.png)
![image](https://user-images.githubusercontent.com/35490649/76155490-86b74d00-6127-11ea-9957-832a74b8baf3.png)

**Comment by rubensworks** [comment]
Is this a bug report?

If so, can you use the proper issue template and provide more information on how to reproduce the bug?

**Comment by Gan-N** [comment]
> Is this a bug report?
> 
> If so, can you use the proper issue template and provide more information on how to reproduce the bug?

I have revised the content.

**Comment by rubensworks** [comment]
Thanks!

Are you sure the energy source in the overworld is chunk-loaded somehow?

**Comment by Gan-N** [comment]
I don't quite understand what you mean. Energy is provided by Energy Battery
![image](https://user-images.githubusercontent.com/35490649/76165374-9bc8c600-6191-11ea-8f15-8d2d73a564a8.png)
![image](https://user-images.githubusercontent.com/35490649/76165381-a5522e00-6191-11ea-9060-f0492a0b1230.png)

Although there is energy in the network, it indicates that there is no energy

**Comment by rubensworks** [comment]
This energy battery is in a different dimension, right?
If so, are you certain that this dimension is loaded?
Otherwise, the network won't be able to extract energy from this unloaded battery.

**Comment by Gan-N** [comment]
Sorry, it's my fault. My chickenchunks are not working properly. I've built a world of cheating, and it's working again
