### ISSUE TITLE
[1.12.2] Squeezing recipe for White Tulip isn't right

### ISSUE THREAD

**Issue by Federsavo** [CyclopsMC/IntegratedDynamics#827]
- :bug: Bug

____

#### Short description:
The recipe for squeezing the white tulip in the mechanical squeezer is wrong. His second output should give 2 instead of 4 dyes, like similar flowers.

![2020-03-16_21 24 27](https://user-images.githubusercontent.com/29519894/76797166-38601900-67cd-11ea-85c5-ec2939b68537.png)

#### Versions:

- This mod: 1.1.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting!
