### ISSUE TITLE
Energy Battery on DDSS not outputting

### ISSUE THREAD

**Issue by Solverbolt** [CyclopsMC/IntegratedDynamics#828]
#### Issue type:

- :bug: Bug

____

#### Short description:

Attempted to use redstone signal, shift right click, about every variation of options suggested in 9 different reddit topics, as the information on the wiki is lacking
#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.1.1.jar
- Minecraft:  1.12.2
- Forge: forge-14.23.5.2847

#### Log file:

 **Pastebin is no longer free.  Last 4 attempts to use their service to upload crash logs has been met with a 10$ pay wall**

**Comment by rubensworks** [comment]
Could you provide more information on what you've tried?

Supplying a redstone signal should just work though.
