### ISSUE TITLE
Crash: java.lang.IllegalStateException: A crafting job was finished while it still has unfinished dependencies.

### ISSUE THREAD

**Issue by MitchellMarx** [CyclopsMC/IntegratedDynamics#829]
Connected an RFTools Crafter with a crafting interface and an item importer
put multiple recipes into the crafter (I was automating Mystical Agriculture)
start a crafting job
change the tick per operation on the crafting interface from 5 ticks to 1 while the crafting is in progress

- This mod: 1.12.2-1.1.2
- Minecraft:  1.12.1
- Forge: 14.23.5.2847
- Integrated Crafting: 1.12.2-1.0.8
- Integrated Tunnels: 1.12.2-1.6.10

- All The Mods Remix: 1.5.4

#### Log file:
http://pastebin.com/Fwe26JRf

**Comment by rubensworks** [comment]
> change the tick per operation on the crafting interface from 5 ticks to 1 while the crafting is in progress

This sounds like the potential cause of the problem.

Thanks for reporting!

**Comment by rubensworks** [comment]
Unfortunately, I can not reproduce this problem with the provided information.

If anyone encounters this problem and can share a description on how to reproduce the problem (without any other mods installed), please comment on this issue.
