### ISSUE TITLE
Display doesn't get updated with block reader

### ISSUE THREAD

**Issue by ZigTheHedge** [CyclopsMC/IntegratedDynamics#83]
Hello, guys!

When you assign variable to Block Reader's "Block" slot and place it in Display, it works fine until you switch the block placed in front of reader. Afterwards variable updates successfully, but Display doesn't until you remove variable card and place it back again.

Minecraft: 1.10.2, ID: v 0.6.2, Forge 2117.

**Comment by rubensworks** [comment]
It appears this bug must've existed for a long time already, thanks for reporting!
