### ISSUE TITLE
Clearing multiple interfaces/variables at the same time

### ISSUE THREAD

**Issue by Hapseleg** [CyclopsMC/IntegratedDynamics#831]
#### Issue type:

- :question: Question

____

#### Question:

Hi
Can I somehow clear multiple interfaces or variable cards at the same time? Right now I need to do it 1 by 1 which becomes quite tedious :)

Keep up the great work, love the mod!

**Comment by rubensworks** [comment]
No, that is not possible at the moment. Feel free to open a feature request with some suggestions! 🙂
