### ISSUE TITLE
List items doesn't get recognized in World Block Importer

### ISSUE THREAD

**Issue by janagyjr** [CyclopsMC/IntegratedDynamics#832]
#### Issue type:

- :bug: Bug

____

#### Short description:
When making a list of different blocks to be picked up by World Block Importer, the list is made successfully but the blocks aren't picked up.

#### Steps to reproduce the problem:

1. Set up something to be imported via World Block Importer
2. Make a list of acceptable blocks to be picked up
3. Set up test to make sure items are picked up
4. ???
5. Profit?

#### Expected behaviour:

For the World Block Importer to pick up the block if one of the blocks on the list is present on its face.

____

#### Versions:

- This mod: 1.1.2
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847

#### Log file:
Unsure if applicable.

Below image showing a survival world setup
![2020-04-02_09 38 56](https://user-images.githubusercontent.com/23646259/78250151-f75f4880-74de-11ea-9348-933a31e772cf.png)

Showing variable card in proper slot and properly set
![listbroke](https://user-images.githubusercontent.com/23646259/78250446-62108400-74df-11ea-8b61-335f6696a06a.png)

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
