### ISSUE TITLE
automating recipe usage

### ISSUE THREAD

**Issue by lmh98** [CyclopsMC/IntegratedDynamics#834]
#### Issue type:

- :question: Question

____

#### Question:

I'm very new to this mod so I hope this question isn't too stupid. How is it possible to automate the use of recipes.

For example I want to craft something having one ingredient that can be every vegetable from Pam's HC. Is it possible to add this whole list of items to the recipe? If not I'd like to use a second recipe if my first doesn't have enough ingredients (mostly the flexible slot though I'm working on that). Is there a way to have recipes only be used under certain conditions like a boolean being true?

**Comment by rubensworks** [comment]
It's definitely not a stupid question!
However, our Discord channel (link in the README) may be a better place to ask these kinds of questions.
So be sure to ask your question there again 🙂
