### ISSUE TITLE
Crash on Startup (Thaumcraft Compat)

### ISSUE THREAD

**Issue by Xaikii** [CyclopsMC/IntegratedDynamics#835]
#### Issue type:

- :bug: Bug

____

#### Short description:

My pack is crashing on startup after updating

#### Steps to reproduce the problem:

1. Download the Mods(see below)
2. Add them to any Pack
3. Start Pack

#### Expected behaviour:

Well, not to crash?
____

#### Versions:

- Mods:
  CommonCapabilities 1.12.2-2.4.6
  CyclopsCore 1.12.2-1.6.2
  IntegratedDynamics 1.12.2-1.1.3
  IntegratedCrafting 1.12.2-1.0.9
  IntegratedTunnels 1.12.2-1.6.11
  Thaumcraft 1.12.2-6.1.BETA26
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Note: 
I have included multiple Mods as it is a Compat Issue 

#### Log file:

https://pastebin.com/R2JAXWmn

**Comment by rubensworks** [comment]
Thanks for reporting.

For now, try downgrading Integrated Dynamics to the previous version. I’ll release a fix tomorrow.

**Comment by DeereJ18** [comment]
> Thanks for reporting.
> 
> For now, try downgrading Integrated Dynamics to the previous version. I’ll release a fix tomorrow.

I tried a previous version, still does not fix compat issue. Thanks for working on the issue.

**Comment by rubensworks** [comment]
Fixed in 1.1.4
