### ISSUE TITLE
Unlike other types, the Recipe type cannot be created as "empty"/"null"

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedDynamics#837]
#### Issue type:

- :bug: Bug

____

#### Short description:

The `Recipe` variable type cannot be created using a blank input (which is required in, say, Choice operators).

____

#### Versions:

- IntegratedDynamics: `1.12.2-1.1.1` (but presumably later as well; no previous issue was found)
- Minecraft: `1.12.2`
- Forge: `14.23.5.2838`

**Comment by rubensworks** [comment]
Note to self: It's possible that such a change may have some large implications down the line, as I think everything in IC assumes non-empty recipes, so things may break horribly there. So this may require a breaking change (i.e. 1.15-only).
