### ISSUE TITLE
Can not open item importer menu

### ISSUE THREAD

**Issue by SirLonestar** [CyclopsMC/IntegratedDynamics#843]
#### Issue type:

- :bug: Bug

____

#### Short description:

At my server, I can not open the item Importe menu. I only get the configuration menu.
https://ibb.co/vxVWQc0
https://ibb.co/vqsgsgr

____

#### Versions:

- This mod: 1.0.8 / 1.6.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

https://pastebin.com/EhrdpXiR

**Comment by rubensworks** [comment]
You are using an outdated version of the mod, please retry with the latest, and without any other mods.
