### ISSUE TITLE
Simple recursive loop involving a growing list crashes the game

### ISSUE THREAD

**Issue by qrss** [CyclopsMC/IntegratedDynamics#845]
#### Issue type:

- :bug: Bug

____

#### Short description:

Had a crash playing around with the Network Reader's Value aspect.
Turns out it is possible to reproduce this with a very simple setup.

#### Steps to reproduce the problem:

(The following also works with the Materializer)
1. Put a Network Reader on a Proxy and join it to the Proxy using Logic Cables.
2. Take the Value aspect from the reader.
3. Put the Value aspect into the Proxy.
4. Observe as the client and server crash.

Doing the same with a Delayer does not crash the client, although in a few seconds it generates a List long enough to freeze the server.

#### Expected behaviour:

Recursion depth seems to be (fortunately) limited to 256, so I assume the issue here is a list that grows too big. Not sure how much of a performance penalty guarding against that would entail.

____

#### Versions:

- This mod: 1.12.2-1.1.5
- Minecraft:  1.12.2
- Forge: 14.23.5.2854

#### Log file:

[crash-2020-04-25_21.36.45-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4533800/crash-2020-04-25_21.36.45-server.txt)

**Comment by rubensworks** [comment]
Hmm, stackoverflow...

Thanks for reporting!
