### ISSUE TITLE
with_MB operator

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedDynamics#846]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

exactly the same as with_size but for fluids. Please, it's so annoying to have to fill a tank with exactly the amount of fluid you need just to make a fluid card. Plus, without modded inventory-based tanks, it's downright impossible to set a fluid card for anything but 1000mb AFAIK, which is extremely limiting.

**Comment by rubensworks** [comment]
Huh, I thought this existed already. Sounds like a must-have indeed.
