### ISSUE TITLE
Using 'itemstack' on minecraft:leaves2 blocks returns items with wrong data values

### ISSUE THREAD

**Issue by qrss** [CyclopsMC/IntegratedDynamics#847]
#### Issue type:

- :bug: Bug

____

#### Short description:

If you use 'itemstack' on minecraft:leaves2 blocks (Acacia: data value 0, Dark Oak: data value 1), you 
instead get the "no decay" item versions of the blocks (data values 4 and 5 respectively).

This might seem like a trivial thing, but it can cause unexpected issues. For example, in one modpack the "no decay" versions had no oreDict entries, which caused some debugging headaches.

Note that minecraft:leaves blocks work correctly. However, if the above behavior is intended, then for consistency 'itemstack' on minecraft:leaves should be made to return  the "no decay" versions also.

#### Steps to reproduce the problem:

1. Convert a Dark Oak Leaves item (minecraft:leaves2/1) value to 'block' and then back to 'item' (using itemstack)
2. Observe that now the item has data value 5.
3. Do the same with Spruce leaves (minecraft:leaves/1)
4. Observe that the result still has data value 1.

![leaves2](https://user-images.githubusercontent.com/32312262/80316788-773fb080-8808-11ea-8daa-0c14a592bca4.gif)

____

#### Versions:

- This mod: 1.12.2-1.1.5
- Minecraft:  1.12.2
- Forge: 14.23.5.2854

**Comment by rubensworks** [comment]
Thanks for reporting!
