### ISSUE TITLE
Applying 'block' and then 'itemstack' to an empty Item Reader's 'Slot Item' aspect crashes the server

### ISSUE THREAD

**Issue by qrss** [CyclopsMC/IntegratedDynamics#848]
#### Issue type:

- :bug: Bug

____

#### Short description:

If the Item Reader's 'Slot Item' aspect is pointing to an empty inventory slot, then applying 'block' and then 'itemstack' to it crashes the server.

#### Steps to reproduce the problem:

![block_crash](https://user-images.githubusercontent.com/32312262/80318467-00f47b80-8813-11ea-8d83-3d78e86d6fb3.gif)

#### Versions:

- This mod: 1.12.2-1.1.5
- Minecraft:  1.12.2
- Forge: 14.23.5.2854

#### Log file:

[crash-2020-04-26_22.57.08-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4536382/crash-2020-04-26_22.57.08-server.txt)

**Comment by rubensworks** [comment]
Ouch, that's not good...
