### ISSUE TITLE
Read fluid level of blood magic altars

### ISSUE THREAD

**Issue by gazpachoking** [CyclopsMC/IntegratedDynamics#85]
It seems the fluid reader is not recognizing the blood magic blood altar as a valid tank. The blood altar does have an input/output tank, so I feel like this should be working.

**Comment by rubensworks** [comment]
Seems to work just fine for me:
![2016-11-26_10 32 23](https://cloud.githubusercontent.com/assets/440384/20639620/caf57ea2-b3c8-11e6-907b-e185231bfe01.png)

Note that it takes a while before the BM altar lets inserted life essence through to its internal tank, so maybe you weren't waiting long enough ;-)

**Comment by gazpachoking** [comment]
Hmm. Let me do some double checking, maybe with a few less mods installed.

> so maybe you weren't waiting long enough

I don't think that was it, as it was reporting 'is tank' as false, not just that it was empty.

**Comment by gazpachoking** [comment]
Hmm. Still having a problem. Blood Magic 2.2.0-66, and Integrated Dynamics 0.6.3 are the only mods I have installed, here is the interface for the fluid reader on a full blood altar.
![image](https://cloud.githubusercontent.com/assets/187133/20641259/3dff3da4-b3c2-11e6-9c3c-fda3155d903c.png)

**Comment by rubensworks** [comment]
Could you send me a screenshot as to how the reader is connected to the altar?
What happens if you try to pipe in/out fluids to the altar?

**Comment by gazpachoking** [comment]
![image](https://cloud.githubusercontent.com/assets/187133/20641294/dda77ba0-b3c2-11e6-87bc-3d702d951d84.png)

Those are all the ways I tried. All reading the same as my first screen shot.

**Comment by gazpachoking** [comment]
As for inputting and outputting fluids, it is working with refined storage, but couldn't get the immersive engineering pump to work either. Seeing if I can get dynamic tunnels to do it now.

**Comment by gazpachoking** [comment]
![image](https://cloud.githubusercontent.com/assets/187133/20641395/e00c9e28-b3c4-11e6-9c0f-3fe319af2267.png)

![image](https://cloud.githubusercontent.com/assets/187133/20641396/e83c6876-b3c4-11e6-8402-2498d9edda20.png)

I haven't really gotten to play with integrated tunnels without crashing yet, but I'm thinking that setup should be slowly sucking blood between the altars. I gave it about 5 minutes with no change in either blood level.

**Comment by rubensworks** [comment]
I've tried this with the latest BM dev build, which worked for me.
Could you try using this BM build and see if this works for you?: http://tehnut.info/maven/com/wayoftime/bloodmagic/BloodMagic/1.9.4-2.1.0-504-ss/BloodMagic-1.9.4-2.1.0-504-ss.jar

There might be something wrong with their fluid capabilities in the latest public version, since IE also seems to be having trouble with it.

**Comment by gazpachoking** [comment]
That was it, thanks! Sorry to waste your time, I should have expected it was something to do with blood magic after the IE pump didn't work.

**Comment by gazpachoking** [comment]
Probably related to the new/old fluid handling referenced in this ticket, for posterity. WayofTime/BloodMagic#942
