### ISSUE TITLE
Logic cables are still rendered when covered by a facade, and significantly impact the performance.

### ISSUE THREAD

**Issue by staviq** [CyclopsMC/IntegratedDynamics#853]
So generally, mods that provide facades, make it so the cables are "replaced" by the facade, and only render facades as a full block.

I case of IT, putting a facade on the logic cables makes absolutely no difference in the impact on the fps, as shown here ( LagGoogles FPS profile ):  https://i.imgur.com/lIhYGza.png

I've been trying to switch from EnderIO conduits to Integrated Dynamics / Tunnels, because it seems to have much better tps performance, but the fps impact just seems unreasonably high.

Another thing is, since logic cables are not animated and do not dislay any usefull data, why do they impact fps that much, compared to AE2 cables for example ? AE2 cables, not only are not full block, but use transparency and fancy channel display, and have soo little fps impact that they rarely even register in the performance profling.

Just for some context, here you have, in one place, from top to bottom ( LagGoogles FPS profile ):

https://i.imgur.com/MRRqS9b.png

-Enderio conduits behind facade ( chiseled redstone )
-AE2 cables all over the place in orange
-IT Logic Cables
-IT Logic Cables behind facade ( chiseled black quartz )

Not only Logic Cables are the only ones to cause trouble, facades make absolutely no diffrence.

**Comment by rubensworks** [comment]
Are you effectively seeing any impact on your FPS? Because microbenchmarking like this always have to be taken with a grain of salt.

That said, I haven't spend that much effort in optimizing for FPS (much more for TPS), so I'm sure there are things that can be done.
I just want to now how significant the problem really is, so I can assign a proper priority to this issue relative to the other open issues at the moment.

**Comment by staviq** [comment]
Impact on the fps is not game breaking, just noticeable, but i'm in the early-mid game right now (e2e).

The thing is hovewer, that if You make it more fps friendly, and i mean, simply making the facade actually remove the cable and act as a passive block, ID / IT has the potential to become The absolute best system for moded minecraft. Seriously, ID/IT is the only system so far that is able to transfer insane amounts of steam required for Mekanism reactors and turbines. It is the only system so far, capable of moving whole chests full of cobblestone in an instant for my UU-matter production.

If you optimise the fps imact, it will be a godsend for the natively shitty performance of the modded minecraft world.
