### ISSUE TITLE
Attempting to open a tunnel or reader/writer with reach messes up the player inventory until relog

### ISSUE THREAD

**Issue by hudson-jones** [CyclopsMC/IntegratedDynamics#855]
#### Issue type:

- :bug: Bug

____

#### Short description:

This is the same bug that Virgil-the-Freak attempted to report, but without the needless hassle to set up astral sorcery. The bug happens while using reach from any mod (Botania's Ring of Far Reach, Astral Sorcery's attunements, Construct's Armory's Gauntlet of Far Reach, etc.). The bug makes it so that you can't move interact with your inventory via the E menu, which is a real pain in the ass.

#### Steps to reproduce the problem:

1. Acquire reach by any method (the above methods are the only I've tested).

2. Attempt to open any tunnel or reader/writer while using reach's extended range. 

3. Experience the bug in the painful glory!

4. Fix via a relog

#### Expected behaviour:

I'd expect to open the inventory for the object, or at least have the menu flash open for a brief moment and then close. What unfortunately happens is the bug.

The bug is signaled to be active when the player inventory gets seemingly randomly jumbled up. This unequips armor and causes things to go in bizarre places like armor slots or the crafting grid. The unequipping of armor may remove flight with certain armor, but I found that it still acts as if the armor is equipped while not allowing flight.

When the bug is activated, it makes the player inventory (accessed by E) unusable by things like inventory tweaks, clicking, etc. It is fixed upon relog but for dummy thicc modpacks like ATM 3 that take a million years to open a world, it's frustrating to do that. The player inventory can be interacted with by doing things like opening a chest, using a terminal, or any other method that shows the player inventory. This does not end the bug, unfortunately. I have made a mini tutorial on the glitch in a small [video.](https://youtu.be/oDa5b9B5kzI)

#### Versions:

- This mod: 1.0.17
- Modpack: All the Mods 3
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
Thanks for reporting, merged with #842.
