### ISSUE TITLE
More Configurability of Network Energy Consumption

### ISSUE THREAD

**Issue by Trainerredstone7** [CyclopsMC/IntegratedDynamics#856]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I'm planning on assembling a personal modpack in which ID network power consumption is enabled, but I noticed that the relative energy consumption values for each network part are hard-coded. For example, I'd like to make storage terminals rather energy-hungry, but I can't do so without making variable displays require an equal amount of energy, and variable stores would require twice as much energy. It would be nice if I could manually set the relative energy consumption values for each part in the configs.

**Comment by rubensworks** [comment]
Good idea, should be easy to implement.

Not sure when I'll have time for it though, so I'm happy to accept a pull request on this.
