### ISSUE TITLE
ConcurrentModificationException in IngredientObserver:observe

### ISSUE THREAD

**Issue by GeneralMine** [CyclopsMC/IntegratedDynamics#858]
#### Issue type:

- :bug: Bug

____

#### Short description:

Trying to use a chest as a filter using a inventory reader on it, an input cable on the ender chest with the inventory reader items variable and an interface cable on a normal chest as output. After some minutes working it randomly crashes. Often after changing dimension or restarting the server.
After the restart its just not working anymore, I need to rebuild the setup.

#### Steps to reproduce the problem:

1. Place a chest with an inventory reader attached (filter chest)
2. Get the items list variable from the inventory reader
3. Place the ender chest and connect a input interface with the items list (from the inventory reader) variable inside. (input chest)
4. Place a chest and connect it with an interface. (output chest)
5. it works for some minutes and crashes then (or doesn't work after a server restart and crashes after a rebuild)

#### Expected behaviour:

All the items in the ender chest fitting the items variable list from the filter chest should be moved to the output chest. The goal is to extract the items from the ender chest to the output chest using the filter chest as a dynamic filter, which can be extended easily by putting items in there.

____

#### Versions:

- This mod: 1.1.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

https://pastebin.com/rcp6acKV

**Comment by rubensworks** [comment]
Thanks for reporting!

Until this is fixed, you can disable `ingredientNetworkObserverEnableMultithreading` to temporarily resolve the problem at the cost of reduced performance.

**Comment by rubensworks** [comment]
Should be fixed in the next release (coming soon). Please let me know should this still occur.
