### ISSUE TITLE
Crash when trying to display virtual piped function using item list from an inventory reader

### ISSUE THREAD

**Issue by nBeebz** [CyclopsMC/IntegratedDynamics#865]
#### Issue type:

- :bug: Bug

____

#### Short description:
Attempting to write an Item Predicate to import items which are not contained in a chest. Trying to display the predicate in a screen results in a crash.

#### Steps to reproduce the problem:

1) Create a network that reads the inventory from an ender chest (from EnderStorage) as `chestContents` 
2) Write the following program: `negate( pipe( Item.ToBlock(), apply( map( chestContents, Item.ToBlock() ), List.Contains() ) )` 
3) try to display program in a screen

#### Expected behaviour:

Display function signature as with other virtual functions

____

#### Versions:

- This mod: IntegratedDyanamics v1.1.1, IntegratedTunnels v1.6.10
- Minecraft: v1.12.2
- Forge: v14.23.5.2847
- Modpack: Enigmatica 2 Expert Mode v1.76a

#### Log file:
[crash-2020-05-18_12.34.53-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4646320/crash-2020-05-18_12.34.53-client.txt)

**Comment by rubensworks** [comment]
This appears to be exactly the same crash as #866. Thanks for reporting though.

I haven't seen these crashes ever before, so I strongly suspect there's another mod that is messing with things...
