### ISSUE TITLE
Redstone Writer sends a pulse when boolean is toggled

### ISSUE THREAD

**Issue by Mr-Stetson** [CyclopsMC/IntegratedDynamics#869]
#### Issue type:

- :bug: Bug

____

#### Short description:

Redstone Writer sends a pulse when the boolean is toggled both from False to True and True to False. All The Mods 3 modpack.

#### Steps to reproduce the problem:

A very short YouTube video
[https://youtu.be/mqWW3uuEMtE](https://youtu.be/mqWW3uuEMtE)

#### Expected behaviour:

Should only send pulse when bool is True.

#### Versions:

- This mod: 1.0.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2825

#### Log file:

Nothing on logs related to this.

**Comment by rubensworks** [comment]
This is intentional behaviour.

The aspect description:

> Outputs a pulse with the configured redstone value if the given value changes.
