### ISSUE TITLE
Disable the flesh to leather recipe in the drying basin

### ISSUE THREAD

**Issue by belathus** [CyclopsMC/IntegratedDynamics#87]
Using the drying basin to get leather from flesh is undesired in the modpack I'm working on. Is there any way to disable this?

**Comment by rubensworks** [comment]
Yes, you can override the drying basin convenience recipes xml file in which the leather recipe is defined: https://github.com/CyclopsMC/IntegratedDynamics/wiki/Recipe-XML

**Comment by belathus** [comment]
Aha. It appears that it didn't automatically create that folder. I'll go ahead and do so manually, then give the recipe removal a shot using the _override subdirectory, as suggested.
