### ISSUE TITLE
Empty fluid option behaviour description is confusing

### ISSUE THREAD

**Issue by robertmaxton42** [CyclopsMC/IntegratedDynamics#871]
#### Issue type:

- :bug: Bug

____

#### Short description:

Using [Choose on &lt;Redstone High&gt;: &lt;Fluid&gt; or &lt;Null&gt;] as the fluid type when attempting to export a specific fluid from a fluid interface does not disable the export on low redstone.

#### Steps to reproduce the problem:

1. Assemble, in a line: a tank of lava, a fluid importer, a logic cable, a fluid exporter, an empty tank.
2. Attach a redstone reader to one of the empty sides of the logic cable, and a lever to the reader.
3. Configure two &lt;Fluid: Lava (1000 mb)&gt; variable cards, a  variable card, and a &lt;Redstone High&gt; boolean card on the redstone reader. 
4. Place one lava card in the fluid importer, under "Export Fluid"
5. Using a logic programmer, create a Choice card: [ &lt;Redstone High&gt; ? &lt;Fluid: Lava (1000 mb)&gt; &lt;Fluid: (null)&gt; ] and place it in the fluid exporter
6. Place a variable store on the remaining side of the logic cable, and put all remaining variable cards in the store.

The lava will flow from one tank to the other no matter the setting of the lever. (As an addendum, reconstructing this setup with "Export Fluids", plural, and [List: &lt;Fluid: Lava (1000 mb)&gt;] and [List: (empty)], _does_ work.)

#### Expected behaviour:

I would have expected the exporter to export lava when the redstone is high, and the null fluid -- i.e. do nothing -- when redstone is low. 

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
If I remember correctly, there should be an aspect option on how empty fluids should be interpreted. This could be set to wildcard, which would explain this behaviour.
Could you check this?

**Comment by robertmaxton42** [comment]
... Oh, is *that* what that option does? 

In that case, I think this turns from a "behavior bug" to a "documentation bug" -- that detail isn't mentioned in the guidebook or in the tooltip, at least not that I can find. It's definitely not under Importers/Exporters or under Interfaces>Fluid, at least.

**Comment by rubensworks** [comment]
Ah, so the option does not exist for fluid importers/exporters, to be added then.

**Comment by robertmaxton42** [comment]
Ah, no, sorry if I was unclear -- the _option_ exists, it's just not clear what it does. It just says "Empty is Wildcard," and the tooltip says "If an empty value matches with everything, otherwise nothing matches" -- which in _retrospect_ tells me what I need to know, but when I was looking at it originally was confusing and didn't seem relevant to me at the time. Just replacing "value" with "filter", say, or adding a subject -- "If the exporter/importer should export/import everything when given an empty value" -- would greatly improve readability and discoverability.

**Comment by rubensworks** [comment]
Ah I see, thanks the the clarification.

Pull requests on this are definitely welcome!

**Comment by rubensworks** [comment]
I'm going to leave this as-is. I can't come up with a better description that is also sufficiently compact.
