### ISSUE TITLE
[1.15.2] Game crashes on startup with just CyclopsCore and IntegratedDynamics

### ISSUE THREAD

**Issue by 00-Steven** [CyclopsMC/IntegratedDynamics#877]
#### Issue type:

- :bug: Bug

____

#### Short description:

The game crashes on startup.

#### Steps to reproduce the problem:

1. Install the latest Forge as of writing, 1.15.2-forge-31.2.24
2. Install the latest Cyclops Core as of writing, CyclopsCore-1.15.2-1.7.0
3. Install the latest Integrated Dynamics as of writing, IntegratedDynamics-1.15.2-1.1.6
4. Boot up the game

#### Expected behaviour:

I expected the game to start.

____

#### Versions:

- This mod: IntegratedDynamics-1.15.2-1.1.6
- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.2.24

#### Log file:

Crash Log: https://pastebin.com/h9s8pmkE

**Comment by rubensworks** [comment]
You must install CommonCapabilities as well.

Looks like I forgot to mark it as a required dependency though...
