### ISSUE TITLE
[1.15.2] Meneglin trees not spawning anywhere.

### ISSUE THREAD

**Issue by NickGrease** [CyclopsMC/IntegratedDynamics#878]
#### Issue type:

- :bug: Bug

MC: 1.15.2
Forge: 31.2.20
IntegratedDynamics-1.15.2-1.1.6
CyclopsCore-1.15.2-1.7.0
CommonCapabilities-1.15.2-2.5.0
CapabilityProxy-1.15.2-2.1.6
____

#### Short description:
Let me start by saying I'm new relatively to Minecraft and mods. Since I can't believe I'm the first to notice this - I'm thinking it's on my end. Having started with close to 100 mods installed, I'm now down the 3 + related dependencies/libs and still the issue persists. JEI, Nature's Compass (to find the biome), Xaeros Minimap.

The Meneglin trees are nowhere to be found - not in the wild and not in the Meneglin biome - which only has oak trees. 
I didn't touch the config file, but didn't see anything there that may be the cause anyways. Kinda stumped.

**Comment by rubensworks** [comment]
That's weird, as I did test this quite recently.

Could you try without any other mods installed?

**Comment by NickGrease** [comment]
Will try with no mods. In the mean time I have a few logs.
[Latest.log](https://pastebin.com/Q0wSBFh1)
[Debug.log](https://pastebin.com/dgTEnP1h)

EDIT: No mods installed - still just oak trees in the Meneglin biome :(

**Comment by NickGrease** [comment]
For completeness sake, I did a fresh/clean install of Minecraft (1.15.2), Forge (31.2.20), IntegratedDynamics + its dependencies = Still just oak in the Meneglin biome and no wild trees to be found.

At any rate, I'll take this opportunity to say this mod is amazing and thanks for all you've done.

**Comment by NickGrease** [comment]
So... about the clean install I mentioned above. Steps were:

1. Zip up the original .minecraft folder (in appdata/roaming) (this included all ~100 mods in working order minus the spawning issue)
2. Delete .minecraft folder
3. Launch Minecraft launcher, which creates new .minecraft folder
4. Use Forge installer -> launch game once
5. Install your mods
6. Post comment above.

Now the issue is going back to my 'old' install (by deleting the current .minecraft folder and unzipping my original in its place) I get an error during loading that IntegratedDynamics had an error in the common setup event. Now, I was under the (self inflicted) impression that zipping the .minecraft folder was essentially an exact backup of all files related to minecraft. 

After a few hours of adding 1 mod at a time I could reliably get the error with 3 mods - Teta, Immersive Engineering, Powah + Lollipop(Lib)

The thing is, all those mods were installed before, when I first added Integrated Dynamics + Deps and things ran fine minus the not spawning trees. This led me to think it was a load order thing - Tetra,IE,Powah were installed long before I found ID. On a whim, I decided to rename the file `IntegratedDynamics-1.15.2-1.1.6.jar` to `!IntegratedDynamics-1.15.2-1.1.6.jar` and low and behold everything loaded (still no tree spawns though :P )

I'm not sure what to make of this, I'm not sure if it's something you *can* fix, I don't know what more I can add to help, so I'll leave it here.

**Comment by rubensworks** [comment]
This may be fixed in release 1.1.9.
Please let me know should this not be the case.

**Comment by NickGrease** [comment]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9
CyclopsCore-1.15.2-1.7.0
CommonCapabilities-1.15.2-2.5.0

**No other mods installed**

Trees are spawning. Drops appear to be correct. Advancements fired when getting a meneglen log. All seems good... except the spawn code could use some work :) 

![2020-06-28_12 09 01](https://user-images.githubusercontent.com/854582/85952795-a58d5980-b939-11ea-950c-e2a6d9349a9b.png)
![2020-06-28_12 08 38](https://user-images.githubusercontent.com/854582/85952796-a625f000-b939-11ea-8db5-43c782fca6a5.png)
![2020-06-28_12 08 13](https://user-images.githubusercontent.com/854582/85952797-a6be8680-b939-11ea-9a1d-4c7a37a2f344.png)
![2020-06-28_12 06 34](https://user-images.githubusercontent.com/854582/85952798-a6be8680-b939-11ea-844b-77a342870eb3.png)
![2020-06-28_12 04 03](https://user-images.githubusercontent.com/854582/85952799-a7571d00-b939-11ea-9441-3d625ac405d6.png)
![2020-06-28_12 01 57](https://user-images.githubusercontent.com/854582/85952800-a7571d00-b939-11ea-8d21-1c55afbdfe28.png)
