### ISSUE TITLE
Creative pick block on a Variable Store duplicates Variable Cards, including IDs

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#879]
#### Issue type:

- :bug: Bug

____

#### Short description:

When you middle-click (pick block) a variable store in creative mode, and there are variable cards in it, the copy will have all tags of the block including all the variable cards in it. Variable cards should not get duplicated when you pick-block a variable store however, unless it would normally keep its contents when broken. But it doesn't.

Variable cards duplicated this way, are also dangerously identical to the original ones. They even have lore warning you not to duplicate them by a middle click. While that middle click refers to middle clicking the card itself, the warning implies the mod knows identical copies are bad so it shouldn't ever copy the container contents at all.

#### Steps to reproduce the problem:

1. Enter creative mode
2. Place a variable store
3. Program a variable card so you can put it in
4. Clear hotbar so it has no variable store anymore
5. Middle click the variable store
6. Place the copy and open it
:x: Variable card is in the copy too, with same ID

#### Expected behaviour:

When you middle-click (pick block) a variable store it should always create the base item and not a copy of the picked block, but _especially_ when you don't also press CTRL, as is in-line with vanilla minecraft.

____

#### Versions:

- This mod: 1.12.2-1.1.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Log file:

(not really relevant but can provide if asked)

**Comment by rubensworks** [comment]
Sure, we should be able to improve this, as it will reduce the chance on obscure bugs.
