### ISSUE TITLE
integrateddynamicscompat requires wrong version

### ISSUE THREAD

**Issue by LlubNek** [CyclopsMC/IntegratedDynamics#880]
#### Issue type:

- :bug: Bug

____

#### Short description:
Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod integrateddynamicscompat requires integrateddynamics 1.1.6
Currently, integrateddynamics is 1.1.7

Looks like you forgot to update the version number.

#### Steps to reproduce the problem:

1. install mod
2. start minecraft

#### Expected behaviour:

Minecraft starts...

____

#### Versions:

- This mod: 1.17
- Minecraft: 1.15.2
- Forge: 31.2.22

#### Log file:
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4834902/latest.log)
![screenshot](https://user-images.githubusercontent.com/313762/85816717-22ea7b80-b73a-11ea-993b-008ba8688f89.png)

**Comment by LlubNek** [comment]
Here's another log with just integrated dynamics and it's dependencies:
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4834924/latest.log)

**Comment by rubensworks** [comment]
Oh, that's not good, thanks for reporting!
