### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by jasoninsane** [CyclopsMC/IntegratedDynamics#881]
#### Issue type:

- :crash: Server crash on startup

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics-1.15.2-1.1.8.jar
- Minecraft: 1.15.2
- Forge: minecraftforge:31.2.21

#### Log file:
https://pastebin.com/cLgyGg8f

**Comment by rubensworks** [comment]
Seems like a duplicate of #875.
