### ISSUE TITLE
[1.15.2] Meneglin Tree Spawning on Water/In Trees

### ISSUE THREAD

**Issue by NickGrease** [CyclopsMC/IntegratedDynamics#883]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9
CyclopsCore-1.15.2-1.7.0
CommonCapabilities-1.15.2-2.5.0

**No other mods installed**

Figured I'd open as a separate issue since #878 was closed. Minor.  

Trees are spawning. Drops appear to be correct. Advancements fired when getting a meneglen log. All seems good... except the spawn code could use some work :) 

![2020-06-28_12 09 01](https://user-images.githubusercontent.com/854582/85952795-a58d5980-b939-11ea-950c-e2a6d9349a9b.png)
![2020-06-28_12 08 38](https://user-images.githubusercontent.com/854582/85952796-a625f000-b939-11ea-8db5-43c782fca6a5.png)
![2020-06-28_12 08 13](https://user-images.githubusercontent.com/854582/85952797-a6be8680-b939-11ea-9a1d-4c7a37a2f344.png)
![2020-06-28_12 06 34](https://user-images.githubusercontent.com/854582/85952798-a6be8680-b939-11ea-844b-77a342870eb3.png)
![2020-06-28_12 04 03](https://user-images.githubusercontent.com/854582/85952799-a7571d00-b939-11ea-9441-3d625ac405d6.png)
![2020-06-28_12 01 57](https://user-images.githubusercontent.com/854582/85952800-a7571d00-b939-11ea-8d21-1c55afbdfe28.png)

_Originally posted by @NickGrease in https://github.com/CyclopsMC/IntegratedDynamics/issues/878#issuecomment-650788629_

**Comment by rubensworks** [comment]
Heh, that's funny...

Thanks for reporting!

**Comment by NickGrease** [comment]
I checked out IntegratedDynamics-1.15.2-1.1.9-1515 - Tree spawning is much improved. If possible I think a very slightly more robust placement check may help iron out a few outliers: maybe check that each of the 4 'root' segments is on 'solid' ground?
![2020-06-30_18 54 15](https://user-images.githubusercontent.com/854582/86185388-4c255600-bb04-11ea-8fbb-f799c5c29542.png)
![2020-06-30_18 53 50](https://user-images.githubusercontent.com/854582/86185391-4d568300-bb04-11ea-9eac-88d6ec1adb44.png)
![2020-06-30_18 52 02](https://user-images.githubusercontent.com/854582/86185394-4def1980-bb04-11ea-8202-dfb06cf910b9.png)

**Comment by rubensworks** [comment]
@NickGrease This is actually the same behaviour as in 1.12. But I guess it should be easy enough to change this. Would lead to a little less trees to spawn though.

**Comment by NickGrease** [comment]
> This is actually the same behaviour as in 1.12. But I guess it should be easy enough to change this. Would lead to a little less trees to spawn though.

Sorry, I wasn't around for 1.12. It really isn't an issue, but I thought I'd mention it in case it was a quick fix and before you pushed 1515 or later. Either way it's in a perfectly playable state so I'm happy. Thx!
