### ISSUE TITLE
Support for TerraForged world generation.

### ISSUE THREAD

**Issue by NickGrease** [CyclopsMC/IntegratedDynamics#885]
#### Issue type:

- :heavy_plus_sign: Support [TerraForged](https://www.curseforge.com/minecraft/mc-mods/terraforged) World Generation
____

#### Short description:

[Adding](https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes) your biome to [TerraForged ](https://www.curseforge.com/minecraft/mc-mods/terraforged)seems like a fairly simple one-liner. Much appreciated! 

~~Edit: from random conversations found on TerraForged discord - it seems like you might want to register the biome 'weight' with Forge (Forge Forge not TerraForged :P) otherwise the biome might appear more often since TerraForged tries to distribute modded biomes in its own way if no weights are found~~ Looks like you're doing this already

**Comment by rubensworks** [comment]
Ah, I wasn't aware of the `BiomeDictionary.Type.OVERWORLD` type. I definitely should add that.

**Comment by NickGrease** [comment]
Tested. Working. Thank you so much!
