### ISSUE TITLE
Menril torch is missing transparency

### ISSUE THREAD

**Issue by bloche1871** [CyclopsMC/IntegratedDynamics#886]
#### Issue type:

- :bug: Bug

____

#### Short description:

1) Squeezer does not auto-eject fluid (solved)
2) Menril torch texture renders without transparency

#### Steps to reproduce the problem:

1) Place Squeezer next to drying basin and process a menril log - resin does not move to basin and there is no way to retrieve it without mod pipes

2) Place a menril torch

____

#### Versions:

- This mod:  IntegratedDynamics-1.15.2-1.1.9
- Minecraft: 1.15.2
- Forge:  1.15.2-forge-31.2.27

**Comment by NickGrease** [comment]
Is the drying basin on the same level as the squeezer or a block below - I had thought it needed to be below, you know so it could 'pour' in to the top - but it actually needs to be adjacent and on the same level. That's my experience anyways. 

EDIT: The Squeezer has a 'track' - its a line that goes across the bottom whick the fluid 'flow' out of - meaning there are only 2 place to put the basin on either side of the track
![2020-07-01_10 52 07](https://user-images.githubusercontent.com/854582/86259041-8553d980-bb89-11ea-8a3b-aef8451b3058.png)

**Comment by bloche1871** [comment]
I tried both ways. It doesn't work either way.

One moment - just noticed the "track" part, will test.

**Comment by NickGrease** [comment]
Can confirm the torch issue: Both regular and Stone versions
![2020-07-01_11 29 03](https://user-images.githubusercontent.com/854582/86262859-6ad02f00-bb8e-11ea-8e6c-4cd7b11096dd.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
I'm surprised about the torch issue, as I did notice and fix this before...

**Comment by NickGrease** [comment]
Once you've squeezed a log, how do you reset the Squeezer? Is it a one time use thing? If I try to put another log 'in' - it just goes on top of the squeezer...

**Comment by bloche1871** [comment]
Ok never mind the fluid issue, things work fine if the barrel is aligned with the "channel". I was able to reset the squeezer using a redstone signal btw.

**Comment by bloche1871** [comment]
Also noticed that the Input Variable Transformer recipe seem to be missing

**Comment by rubensworks** [comment]
Please report separate issues for each problem you have.
