### ISSUE TITLE
Recipe for Input Variable Transformer missing

### ISSUE THREAD

**Issue by bloche1871** [CyclopsMC/IntegratedDynamics#887]
#### Issue type:

- :bug: Bug

____

#### Short description:

Recipe for Input Variable Transformer missing

#### Steps to reproduce the problem:

Look up recipe for Input Variable Transformer in JEI

____

#### Versions:

- This mod:  IntegratedDynamics-1.15.2-1.1.9
- Minecraft: 1.15.2
- Forge:  1.15.2-forge-31.2.29

**Comment by NickGrease** [comment]
Just to clarify, the Input Variable Transformer appears in JEI, but the recipe does not when pressing 'r' over the item. The Integrated Dynamics manual also shows:
![2020-07-01_12 27 48](https://user-images.githubusercontent.com/854582/86268814-c1da0200-bb96-11ea-9145-65e970ada035.png)
Both of which produce an Output Variable Transformer (I don't actually know what the Input recipe is but I assume one of those pages was meant to be an Input recipe)

**Comment by rubensworks** [comment]
Thanks for reporting!
