### ISSUE TITLE
[1.15.2] Trees *may* be dropping to many items.

### ISSUE THREAD

**Issue by NickGrease** [CyclopsMC/IntegratedDynamics#888]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9-1515
CyclopsCore-1.15.2-1.7.0-1090
CommonCapabilities-1.15.2-2.5.0

On average each 'normal' size tree drops 5 crystals, 5 saplings, and 15 berries. This is subjective, I know. Each Meneglin biome I've encountered has well over 50 trees, which makes it feel like once you've found a biome you can stop looking - you'll have more then enough resources to make you're own forest 5 times over. Again, this is subjective and depends on playstyle or number of players - but even in multiplayer it seems like a single biome could support a whole server.

Don't really have a solution (if one is even needed) - at best I wouldn't mind if saplings dropped 0-2 per tree, how many crystals drop doesn't really matter since a single tree has 20+ logs which is several hundred crystals per tree, and berries, despite their use in a few recipes, could probably have their drops halved and still be abundant.

Again, I don't think this has any real game play implications - this isn't a mod about finding trees, and being resource starved isn't want I'm going for either. As a relatively new player, I would take my opinion with a grain of salt :)

**Comment by NickGrease** [comment]
I'm going to close this because the more I think of it, the less I think this is an issue that needs your attention, which I'm sure is limited in supply :)

**Comment by rubensworks** [comment]
I'm going to leave this open :-)

**Comment by NickGrease** [comment]
I'll test 1520, but judging from the numbers, I expect this will be fine. Thanks again... and again... and again... 😄 

Edit: Tested in 1520 - looks good to me - reasonable item drops, wild trees are scarce but not impossible to find, biome looks great.
