### ISSUE TITLE
1.15.2 Machine Reader crash with Refined Storage

### ISSUE THREAD

**Issue by bloche1871** [CyclopsMC/IntegratedDynamics#889]
#### Issue type:

- :bug: Bug

____

#### Short description:

- Crash when opening Machine Reader GUI. Seems to be related to Refined Storage. Log included below.

#### Steps to reproduce the problem:

Open Machine Reader GUI with Refined Storage for 1.15.2 installed.

____

#### Versions:

 -  This mod: IntegratedDynamics-1.15.2-1.1.9
 -  Minecraft: 1.15.2
 -  Forge: 1.15.2-forge-31.2.29

#### Log file:
https://pastebin.com/Be3SPNhE

**Comment by NickGrease** [comment]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9
CyclopsCore-1.15.2-1.7.0
CommonCapabilities-1.15.2-2.5.0

refinedstorage-1.8.6

Can confirm. The GUI opens but hangs/freezes immediately and crashes after a few seconds. 
[crash-2020-07-01_12.58.06-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4859291/crash-2020-07-01_12.58.06-server.txt)

**Comment by rubensworks** [comment]
Did RS change their public API gain?...
I'm strongly considering throwing out RS support, given all the maintenance work it gives me.

**Comment by NickGrease** [comment]
Thanks rubensworks - All recent closed issues appear to be fixed with builds 1517/1092 - really amazing you helping us out so quick - much appreciated.
