### ISSUE TITLE
[1.15] Disabling the Megeglin Biome does not seem to work

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#890]
#### Issue type:

- :bug: Bug

____

#### Short description:

Blacklisting Meneglin from the overworld and setting biome spawn weight to 0 did not stop the Meneglin biome from spawning.

Config entries:
`meneglinBiomeDimensionBlacklist = ["minecraft:nether", "minecraft:the_end", "minecraft:overworld"]`
`spawnWeight = 0`

This was in a world generated with the mod Terraforged, in case that matters.

#### Steps to reproduce the problem:

1. Set the config with the values listed above
2. Make a new world
3. Find a Meneglin (I recommend using the mod Nature's Compass for this)

#### Expected behaviour:

I expected the biome to not appear at all.
____

#### Versions:

- This mod: IntegratedDynamics-1.15.2-1.1.11
- Minecraft: 1.15.2
- Forge: 1.15.2-31.2.30

**Comment by NickGrease** [comment]
TerraForged has a config folder with the file `biome_weights.conf`. I believe that's what your looking for.

**Comment by NielsPilgaard** [comment]
Are you sure? There's no such file in my instance. Biomes O' Plenty has a `biome_weights.toml` though.

**Comment by NickGrease** [comment]
I'm guessing its only in TerraForged-BETA2 - Been using it for a week now, stable as a beta can get. But ya, this is on TerraForged' end. Nothing InDy can do. 

Now that I think about it, maybe it's the beta that respects weights set by other mods - meaning you won't need to add anything to the file I mentioned. Not sure either way - give it a try though.

**Comment by NielsPilgaard** [comment]
Alright then, thanks a lot for the swift answer and explaination :)

**Comment by rubensworks** [comment]
Hmm, this config option should still work though. I'm going to have a look at it in any case.

**Comment by GatekeeperTDS** [comment]
Can confirm that blacklisting the overworld does not actually get rid of the biome. For comparison, I'm not using Terraforged, and blacklisting the biome results in the biome still generating, just with no trees or anything else.

**Comment by NielsPilgaard** [comment]
> blacklisting the biome results in the biome still generating, just with no trees or anything else.

More information on the lack of decoration/caves/trees here: https://github.com/NillerMedDild/Enigmatica5/issues/427

**Comment by rubensworks** [comment]
@NillerMedDild Looks related to the biome black list issue indeed. Removing the applicable dimension from the blacklist _should_ fully generate the biome though.
