### ISSUE TITLE
[1.15.2] some keys cause labelling to misfire in both programmer and labeller

### ISSUE THREAD

**Issue by WebDragon** [CyclopsMC/IntegratedDynamics#891]
#### Issue type:
- :bug: Bug

#### Short description:
it doesn't seem the labeller is fully capturing input as expected

#### Steps to reproduce the problem:
Create a variable of some sort. Insert it in the labeller. type until you get to "E" at which point the labeller closes its window and drops your variable on the floor

Or, with labeller in inventory, using the portable logic programmer, search for 'integer', create a variable, and after pressing the [E] to edit its name, typing an "R" (like you were naming the variable card 'Fred') causes the focus to shift to the search box wherein you first searched so now it reads 'integerr"

#### Expected behaviour:
I can type whatever words I want to name my variable cards, 'Threshold' instead of 'Thshhold'

#### Versions:
- This mod: IntegratedDynamics-1.15.2-1.1.11.jar
- Minecraft: 1.15.2
- Forge:  forge-31.2.31

**Comment by WebDragon** [comment]
Full installed mod list ( installed thru twitch ): https://pastebin.com/sKh5rimR

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/sKh5rimR">AkashicTome-1.3-13.jar  AppleSkin-mc1.15.2-forge-1.0.14.jar  AutoRegLib-1.5-40.j - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Thanks for reporting!
