### ISSUE TITLE
[1.12] Incorrect stored energy when crafting 2 batteries together

### ISSUE THREAD

**Issue by IndigoEU** [CyclopsMC/IntegratedDynamics#892]
#### Issue type:

- :bug: Bug

____

#### Short description:

When combining energy batteries, the resulting battery has incorrect charge.

#### Steps to reproduce the problem:

1. Craft 2 energy batteries
2. Charge one battery
3. Craft the batteries together

#### Expected behaviour:

The crafted battery should have the correct amount of energy stored (sum of the 2 batteries used in crafting).

____

#### Versions:

- Forge: 14.23.5.2847
- Integrated Dynamics: 1.1.6
- Integrated Tunnels: 1.6.11

____
![battery](https://user-images.githubusercontent.com/39650700/87254782-69074500-c485-11ea-8654-27965409fc9f.png)

**Comment by Jack-McKalling** [comment]
Instead, it looks like it starts out with 2000 per 1M battery, the max ouput per side. Maybe the wrong value used somewhere.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I tried to reproduce it in Integrated Dynamics for 1.15.2, and it did work correctly there. However, I'm not sure it's properly fixed yet.
