### ISSUE TITLE
[1.15.2] Squeezing Recipes for all vanilla minecraft flowers are out of whack 

### ISSUE THREAD

**Issue by WebDragon** [CyclopsMC/IntegratedDynamics#893]
#### Issue type:
- :bug: Bug

#### Short description:
All the vanilla minecraft flower recipes are missing the additional chance for more dyes (as seen here https://github.com/CyclopsMC/IntegratedDynamics/issues/827 in this bug's uploaded image ).

In addition, some of the recipes are wrong (red tulip), and some of the recipes are just completely missing.

#### Expected behaviour:
```
# Minecraft flowers (vanilla) that have recipes in the squeezer, but are missing secondary output:
Lilac (2x) = 8 Magenta dye
Allium = 4 Magenta Dye
Peony (2x) = 8 Pink dye
Pink Tulip = 4 Pink Dye
Orange Tulip = 4 Orange dye
Azure Bluet = 4 Light gray dye
Wither Rose = 4 black dye
Lilly of the Valley = 4 White dye
Blue Orchid = 4 Light Blue dye
Cornflower = 4 Blue Dye
Dandelion = 4 Yellow dye

# Minecraft flowers (vanilla) that have an incorrect squeezer recipe, **and** are missing secondary output:
Red Tulip = 1 Red Dye (what? should be 4 just going by other tulips as examples.)

# Minecraft flowers (vanilla) that are missing recipes in the squeezer:
Rose Bush (2x) - red x8 + ?
Sunflower (2x) - yellow x8 + ?
Poppy - red x4 + 2 (chance)
Oxeye Daisy - light gray x4 + 2 (chance)
White Tulip - white x4 + 2 (chance)
```

#### Versions:
- This mod: IntegratedDynamics-1.15.2-1.1.11.jar
- Minecraft: 1.15.2
- Forge: forge-31.2.31

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by WebDragon** [comment]
Whoops one further bumperage:

Cactus only produces 500mb water per each in the squeezers, no dyes. (should be 4x dye with 50% chance of 2 additional? plus the water). Not sure if your patch has addressed that one yet.
