### ISSUE TITLE
Energy usage not working properly

### ISSUE THREAD

**Issue by bloche1871** [CyclopsMC/IntegratedDynamics#895]
#### Issue type:

- :bug: Bug

____

#### Short description:

Batteries seem to be able to charge correctly, but the cables do not transfer energy and components like readers say "NO POWER" even when connected to a network with a charged battery, if energyConsumptionMultiplier is set to higher than zero in the config.

#### Steps to reproduce the problem:

Set energyConsumptionMultiplier from 0 to 1 in the config.
Set up a simple network with a charged battery, a cable, and a reader. Open the reader GUI.

#### Expected behaviour:

The energy should be transferred by the cables to the components that need energy. Maybe it should also be possible to use the cables to transfer FE to other mod blocks that use it? Not sure if that's intended or not though.

____

#### Versions:

- This mod: IntegratedDynamics-1.15.2-1.1.12
- Minecraft: 1.15.2
- Forge: 1.15.2 - 31.2.31

**Comment by rubensworks** [comment]
Thanks for reporting!
