### ISSUE TITLE
[1.15.2] Crash when adding Recipes to List variable in portable logic programmer

### ISSUE THREAD

**Issue by WebDragon** [CyclopsMC/IntegratedDynamics#896]
#275 ## Issue type:
- :bug: Bug

#### Short description:
 'Error: java.lang.UnsupportedOperationException: Trying to add tag of type 0 to list of 0'

#### Steps to reproduce the problem:
open Portable Logic Programmer
search for List, and choose it
use arrows to arrive at "Recipe", and click the + symbol to add one

#### Expected behaviour:
? not crashing? I dunno yet what it was supposed to do, as I was just experimenting around but presumably the answer is at the very least 'not crash' ? :)

#### Versions:
- This mod: IntegratedDynamics-1.15.2-1.1.12.jar
- Minecraft: 1.15.2
- Forge:  forge-31.2.31
 - Java: (recently updated) Java 8 update 261 (build 1.8.0_261-b12)

#### Log file:
https://pastebin.com/jfZhu6jK

**Comment by rubensworks** [comment]
Thanks for reporting!
