### ISSUE TITLE
1.12.2 Dedicated server Crash

### ISSUE THREAD

**Issue by Reginald-Halifrax** [CyclopsMC/IntegratedDynamics#898]
#### Issue type:

- :bug: Bug

____

#### Short description:

I was running a dedicated server I play with my friends that I run with a bunch of mods. after an update with Cyclops core the server now throws a null pointer exception when a player attempts to spawn in.

Unfortunately, I did try a controlled environment of only integrated dynamics and the crash did not happen. I legitimately don't know how to approach this issue, and testing every mod individually is a task. If this is a known issue with a simple answer I'm all ears

#### Steps to reproduce the problem:

1. Have my set of mods on your server

2. Load the server

3. Have a user connect to the server.

#### Expected behaviour:

User joins as normal and gameplay continues as per normal affair (punching trees and what have you)

____

Instead: the server will crash upon connection and shutdown, generating a null pointer exception crash log between Cyclops core and Integrated dynamics

#### Versions:

- This mod: 1.1.7
- Cyclops Core: 1.6.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Log file:

[Crashlog](https://github.com/CyclopsMC/IntegratedDynamics/files/4955979/crash-2020-07-21_15.30.23-server.txt)

**Comment by rubensworks** [comment]
> Unfortunately, I did try a controlled environment of only integrated dynamics and the crash did not happen.

That seems to indicate that another mod is messing with things.

Could you share the full Forge log with me after the crash has occured?

**Comment by Reginald-Halifrax** [comment]
After different tests the crash is now resolved for reasons beyond my understanding, I legitimately have no idea whats different from when that crash log was generated compared to the tests I just did. I just have to assume it was some sort of session issue I guess I am completely stumped.

I appreciate you trying to help, you can close this if you want if you think there's nothing else to be said or done.

If the issue somehow re-arises I'll be sure to report it with both a crash log and forge log (forgive me for not bringing one before, not sure why I didn't think to.)

I skimmed over some of your other works and see you are quite the busy fellow so I very much appreciate you even bother yourself working over mods for minecraft of all things. Keep up the good work out there!

**Comment by rubensworks** [comment]
Thanks! :-)

Should anyone else encounter something like this in the future, please comment here.
