### ISSUE TITLE
Crash while opening an Integrated Dynamics Display Panel

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#899]
Relayed from original issue: https://github.com/NillerMedDild/Enigmatica5/issues/435

#### Issue type:

- :bug: Bug

____

#### Short description:

Random crash while opening an Integrated Dynamics Display Panel.
Doesn't happen every time but it does somewhat often.

#### Steps to reproduce the problem:

1.Open and close the Display Panel until a crash occurs... I think.

#### Expected behaviour:

No crashing.

____

#### Versions:

- This mod: IntegratedDynamics-1.15.2-1.1.12
- Minecraft: 1.15.2
- Forge: 1.15.2-31.2.30

#### Log file:

[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4957353/latest.log)
[crash-2020-07-22_02.39.35-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4957354/crash-2020-07-22_02.39.35-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by NielsPilgaard** [comment]
Thanks for the quick fix :)
