### ISSUE TITLE
SF4 Server low tps and console errors

### ISSUE THREAD

**Issue by MatthewFMMS** [CyclopsMC/IntegratedDynamics#900]
Admin of an SF4 Server. Been having issues with very low tps. The console is getting spammed by this error. https://pastebin.com/P3wZvAQW It starts randomly and stops on its own after a while. Restarting the server fixes the issue temporarily.

The file generated by the sampler.
[Zippy lag7-25-2020.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/4976655/Zippy.lag7-25-2020.zip)

We are running Sponge Forge 7.2 with the latest version of Sky Factory 4.

**Comment by MatthewFMMS** [comment]
Update: It stopped spamming errors in the console for around 15 seconds and produced this error. 
https://pastebin.com/8HhA8Esm

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/8HhA8Esm">Console when it stopped for a second - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Looks like Sponge blocks cross-thread interactions to worlds, even though ID handles this safely.
You'll have to disable `ingredientNetworkObserverEnableMultithreading` in the ID config, which will come at a performance cost, but will make Sponge happy.
