### ISSUE TITLE
Bucket gets voided when used on a partially filled drying basin

### ISSUE THREAD

**Issue by MasterEnderman** [CyclopsMC/IntegratedDynamics#903]
#### Issue type:

- :bug: Bug

____

#### Short description:

If you use a bucket with a fluid on a partially filled drying basin with the same fluid the bucket vanishes and the fluid amount in the drying basin stays the same.

#### Steps to reproduce the problem:

1. Place a drying basin
2. put a fluid into the drying basin
3. reduce the amount of the fluid in the basin without emptying it
4. try to refill the basin using a bucket filled with the same fluid
5. the bucket gets voided and no fluid is added to the basin

#### Expected behaviour:

The bucket isn't voided but emptied an the drying basin is filled up.
____

#### Versions:

- This mod: 1.1.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting!
