### ISSUE TITLE
Substring(from,to,string) incorrectly reports end of string

### ISSUE THREAD

**Issue by dannyr-git** [CyclopsMC/IntegratedDynamics#905]
#### Issue type:

- :bug: Bug

____

#### Short description:

I have a string "foodAcornRedstone"

If I use   substring(9, len(string), newstring) ... it will error saying "from and to can't exceed string length" or whatever the error is.

If I try  substring(9, len(string)-1, newstring) ... it will give the string but truncated by the last character, or "Redston"

#### Versions:

- This mod:  1.12.2-1.1.6 (1.1.6)

**Comment by rubensworks** [comment]
Thanks for reporting!
