### ISSUE TITLE
Integrated Dynamics causes world corruption

### ISSUE THREAD

**Issue by BlackStone5677** [CyclopsMC/IntegratedDynamics#909]
So I have a lets play in Enigmatica 2 Light 1.4.2 and when I wanna add Integrated Dynamics to the mods list my lets play world gets corrupted and I get this message from forge : "This world may've been corrupted please take a backup before joining the world." I assume it's some kinda mod conflict and I tried a bunch of versions of the mod. I don't get this message when creating a new world.

**Comment by rubensworks** [comment]
Sounds like a pack issue. Could you report this to the mod pack author?

**Comment by Frikkle** [comment]
They are using a modified version of our packs with added/removed/tweaked mods. Without further information or steps to reproduce there's nothing we can do on our side.

**Comment by Frikkle** [comment]
In addition, they are using a cracked launcher. We dropped support for this case. Just a heads-up.
