### ISSUE TITLE
random crash when using the basin or looking recipes

### ISSUE THREAD

**Issue by Tsukiumy** [CyclopsMC/IntegratedDynamics#91]
the bug occours at random when looking recipes or operating the basin
https://gist.github.com/Tsukiumy/beb962bdecece95af17aa5e70f83cd67
forge 2179
cyclopscore 0.8.2
integrateddynamics 0.6.4

**Comment by rubensworks** [comment]
That crash should not be possible, I assume some coremod is messing with class internals...

Could you try the following CyclopsCore dev version?: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/cyclopscore/CyclopsCore/1.9.4-0.8.2-432/CyclopsCore-1.9.4-0.8.2-432.jar
This should give more information on the crash. Also please provide the full forge server log next to the crash, as this may contain essential information.

**Comment by rubensworks** [comment]
Should be fixed because of CyclopsMC/CyclopsCore@a6da6fd7091fe791430f4ae35302b49d342ab254
