### ISSUE TITLE
[1.15.2] Server crashed through setup which exports items into a colossal chest

### ISSUE THREAD

**Issue by 00-Steven** [CyclopsMC/IntegratedDynamics#910]
#### Issue type:

- :bug: Bug(Crash)

____

#### Short description:

I had built a setup which consists of an obsidian chest linked to a a network through an item interface, two world item importers respectively picking up full and empty mana tablets, and two item exporters exporting those mana tablets into their respective 3x3x3 obsidian colossal chests from the side of an interface positioned on the bottom layer.
When I installed the item exporters and put a mana tablet in the chest linked with an item interface, the server I was playing on crashed shortly after.
After a reboot it was functional again, and I quickly disassembled the offending device.

#### Steps to reproduce the problem:

The exact steps are unknown, see above for a general description.
Recap of setup:
- 2 3x3x3 colossal obsidian chests connected to the network using item exporters, one set to export full mana tablets and the other to empty ones.
- 2 world item importers, one set to pick up full mana tablets and the other to empty ones.
- 1 obsidian chest linked to the network using an item interface
I then put an empty mana tablet in the linked obsidian chest, shortly afterwards it crashed.

#### Expected behaviour:

I expected the item to be deposited into the colossal chest, instead the server crashed.

____

#### Versions:

- Integrated Dynamics: IntegratedDynamics-1.15.2-1.1.16
- Integrated Tunnels: IntegratedTunnels-1.15.2-1.6.13
- Cyclops Core: CyclopsCore-1.15.2-1.8.3
- Common Capabilities: CommonCapabilities-1.15.2-2.5.3
- Colossal Chests: ColossalChests-1.15.2-1.7.12
- Minecraft: 1.15.2
- Forge: 31.2.26

#### Log file:

https://pastebin.com/gLYkBbBj

**Comment by rubensworks** [comment]
Thanks for reporting!
