### ISSUE TITLE
[1.15.2] Server crashes while attempting to use Proxies and world block importers

### ISSUE THREAD

**Issue by 00-Steven** [CyclopsMC/IntegratedDynamics#911]
#### Issue type:

- :bug: Bug(Crash)

____

#### Short description:

Server crashes after a few steps are taken, I'm unsure as to what actually caused this.
I used a Proxy to create a variable linked to a list with two blocks, livingwood and livingrock, then made copies of those through crafting, and put them in world block importers. Some part of this process seemed to have crashed the server I was playing on and gotten it stuck in a loop of crashes.

#### Steps to reproduce the problem:

The network had one Proxy, one variable storage, 8 world block importers, 8 world block exporters, and one item interface connected to a regular obsidian chest.
The Proxy was pointing at a list of two blocks, livingwood and livingrock.
I then created 8 variables linked to said Proxy, and put them in the world block importers, this seemed to have caused the loop of crashes.

#### Expected behaviour:

I expected the server not to crash, and instead that either the world block importers would work, or just wouldn't work and say so.

____

#### Versions:

- Integrated Dynamics: IntegratedDynamics-1.15.2-1.1.16
- Integrated Tunnels: IntegratedTunnels-1.15.2-1.6.13
- Cyclops Core: CyclopsCore-1.15.2-1.8.3
- Common Capabilities: CommonCapabilities-1.15.2-2.5.3
- Colossal Chests: ColossalChests-1.15.2-1.7.12
- Minecraft: 1.15.2
- Forge: 31.2.26

#### Log file:

https://pastebin.com/XFnRtpWR

**Comment by rubensworks** [comment]
Thanks for reporting!
