### ISSUE TITLE
[1.12.2] Question: Is the Machine Reader, specifically the "Worker" properties, intended to work with non-Integrated Dynamics machines?

### ISSUE THREAD

**Issue by Fulmir** [CyclopsMC/IntegratedDynamics#912]
#### Issue type:

- :question: Is the Machine Reader, specifically the "Worker" properties, intended to work with non-Integrated Dynamics machines?

____

#### Question: Is the Machine Reader, specifically the "Worker" properties, intended to work with non-Integrated Dynamics machines?

Specifically the "Worker" parameters. I've tested it with Gregtech CE, Industrial Forgoing, Mekanism, and just the vanilla Furnace and the "Is Worker" property shows as "False" for everything except the Integrated Dynamics machines, which seems odd, especially since it's the first thing the Machine Reader returns.

I'm trying to use it to set up some local automation for distributing work to machines and I'm trying to figure out if I'm doing something wrong or if the feature just doesn't work how it seems it should.

**Comment by rubensworks** [comment]
The Common Capabilities mod needs to be installed for this: https://www.curseforge.com/minecraft/mc-mods/common-capabilities

Only some mods support the worker capability. Vanilla machines should be included.

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/common-capabilities">Attention Required! | Cloudflare</a></strong></div></blockquote>
