### ISSUE TITLE
CT script support didn't work

### ISSUE THREAD

**Issue by Haocen2004** [CyclopsMC/IntegratedDynamics#913]
#### Issue type:

- :bug: Bug

____

#### Short description:

MechanicalSqueezer removeRecipe Optional tag didn't work

#### Steps to reproduce the problem:

CT script ` MechanicalSqueezer.removeRecipesWithOutput(null, <liquid:lava>); `
Game didn't remove any recipes 
also when script is `removeRecipesWithOutput(<liquid:lava>); `

#### Expected behaviour:

Remove any item to lava recipes
____

#### Versions:

- This mod: 1.1.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Log file:
sorry but none

**Comment by Haocen2004** [comment]
Unknown reason can now take effect without error

**Comment by Haocen2004** [comment]
update some issue description

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you try the `removeRecipe` syntax instead? You'll have to define all recipe components in that case.
