### ISSUE TITLE
Crash while importing Thermal Expansion Machine recipes from JEI 

### ISSUE THREAD

**Issue by KrAzYGEEK32** [CyclopsMC/IntegratedDynamics#914]
#### Issue type:

- :bug: Bug

____

#### Short description:

game crashed when i tried to import a gear recipe for the multiservo press from JEI, most other Thermal machine recipes show a "too big for logic programmer recipe pattern" message when i try to pull them from JEI even though they should fit

#### Steps to reproduce the problem:

1. have thermal expansion installed as well
2. try pulling a gear recipe from JEI into the recipe datatype
3. game crashes most likely

#### Expected behaviour:

i expect to pull the recipe correctly from JEI

____

#### Versions:

- This mod: 1.1.17
-integrated Crafting:1.0.10
- Minecraft: 1.15.2
- Forge: 31.2.6
-Thermal Series-0.2.3b

#### Log file:

https://gist.github.com/KrAzYGEEK32/4291494f132109cb0395c4fc88df4eca

**Comment by rubensworks** [comment]
Thanks for reporting!
