### ISSUE TITLE
Cannot scroll Items in Storage Terminal

### ISSUE THREAD

**Issue by SysFailz** [CyclopsMC/IntegratedDynamics#915]
1.15.2
31.2.36 Forge
1.8.4 Cyclops Core

Everything in the storage terminal and system works fine, except, you cannot scroll up or down to view all of your items.
Mouse wheel doesn't work, nor does grabbing the scroll bar by hand.
Does not matter what kind of storage you use (chests. crates etc etc)

**Comment by rubensworks** [comment]
Thanks for reporting!
