### ISSUE TITLE
Accessing a machine reader via RMB causes instant server crash

### ISSUE THREAD

**Issue by Jerakl** [CyclopsMC/IntegratedDynamics#916]
I didn't see anything like this filed in issues yet so here goes.
When trying to access a machine reader (regardless of what it's attached to, I tried a handful of machines as well as no machines) I get an instantaneous server crash. I'm guessing it's an incompatibility somewhere, but I'm not really sure so I figured I'd post it up here and see if there's a solution of some sort. Google turned up nothing that helped.

If any more info is required I'll do my best to provide (assuming this isn't already fixed somehow).

Crash log attached/pastebin

https://pastebin.com/EDHpDugj
[crash-2020-09-18_21.02.55-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/5248217/crash-2020-09-18_21.02.55-server.txt)

**Comment by rubensworks** [comment]
You seem to be using IC2Classic, which is incompatible with this mod. (because they hijacked the official IC2 mod id)

**Comment by Jerakl** [comment]
> You seem to be using IC2Classic, which is incompatible with this mod. (because they hijacked the official IC2 mod id)

Thank you! I figured that's what it was.
