### ISSUE TITLE
Menril Door duplicating 1.15.2

### ISSUE THREAD

**Issue by suzuki-jessy** [CyclopsMC/IntegratedDynamics#919]
#### Issue type:

- :bug: Placing a Menril Door and then breaking it drops a door for top and bottom block broken

____

#### Steps to reproduce the problem: 

1. Place door, 
2. Break with Empty Hand or with item

#### Expected behaviour: 

single item drop
____

#### Versions:

- This mod: Integrated Dynamics 1.15.2-1.1.17
- Minecraft: 1.15.2
- Forge: forge 31.2.43

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Thanks for reporting!
