### ISSUE TITLE
Multiple blocks not corrrectly displayed on Waila

### ISSUE THREAD

**Issue by Runesmacher** [CyclopsMC/IntegratedDynamics#92]
Logic programmer only correctly displayed on waila when placed facing south
Menril leaves not correctly displayed on waila when tree is grown

forge 2116
cyclopscore 0.8.2-432
integrateddynamics 0.6.4

**Comment by rubensworks** [comment]
This is a known problem with Waila, where it doesn't correctly translate blockstates to item metadata.
Since Waila is being phased out in favor of TOP, I don't consider this a major problem, but feel free to have a look at it yourself if you feel like it.

**Comment by rubensworks** [comment]
@Runesmacher Could you try it with HWYLA (fork of WAILA)? Maybe this has been fixed already on their end.

**Comment by mrlamb** [comment]
This might be the wrong place to post this, but since this issue is still open I will. Using The One Probe, and the Battery always shows at 100.0 KRF even when empty.

**Comment by rubensworks** [comment]
@mrlamb This should have been fixed in #169, are you using version 0.6.12?

**Comment by mrlamb** [comment]
Great question, I'll check that tomorrow. Probably not, the mod pack my
friends and I use has a newer version, but I haven't seen the changeling.

**Comment by mrlamb** [comment]
Indeed, I'm on an old version. Thanks for taking the time to reply to my newbishness! Also, autocorrect on my phone is horrible. I swear I fixed "changeling" to changelog". Twice.
