### ISSUE TITLE
Squeezer x-ray 1.15.2

### ISSUE THREAD

**Issue by suzuki-jessy** [CyclopsMC/IntegratedDynamics#920]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. place squeezer against full block. Partial blocks like chests render noramlly, and anything that has partial coverage (slabs, block cutters) show the rest normally. 
2. Underground visible through Squeezer when it is not compressed.
![xray](https://user-images.githubusercontent.com/32136187/94352658-ec244a00-0035-11eb-8b3a-8b33a5f1a3df.PNG)

#### Expected behaviour:

See block face behind squeezer
____

#### Versions:

- This mod: Integrated Dynamics 1.15.2-1.1.17
- Minecraft: 1.15.2
- Forge: forge 31.2.43

**Comment by rubensworks** [comment]
Thanks for reporting!
