### ISSUE TITLE
[Compat] [Enhancement] Akashic Tome Compatibility

### ISSUE THREAD

**Issue by tomodachi94** [CyclopsMC/IntegratedDynamics#921]
Hi there,
I was playing a modpack with Integrated Dynamics and [Akashic Tome](https://www.curseforge.com/minecraft/mc-mods/akashic-tome) mods, and noticed I can't put your book into the Akashic Tome...
The [FTBWiki](https://ftb.gamepedia.com/Akashic_Tome#Configuration) says: 

> By default, all items containing `book`, `tome`, `lexicon`, `nomicon`, `manual`, `knowledge`, `pedia`, `compendium`, `guide`, `codex` or `journal` in their registry names can be added to the tome (with exception of vanilla items like the Book).

Perhaps try this?

**Comment by rubensworks** [comment]
I won't be changing the registry name of the book, that would break all existing worlds.

I would suspect the mod has a config in which you can add additional books, perhaps you could try that.
