### ISSUE TITLE
[1.15.2] Server Crash when right-clicking the block reader.

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/IntegratedDynamics#923]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Right-click the block reader.
2. Server Crash.
3. Profit.

#### Expected behaviour:

That the server doesn't crash.

#### Versions:

- This mod: [1.1.17](https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/3053851)
- Minecraft: 1.15.2
- Forge: 31.2.43

#### Log file:

Crash-report: https://gist.github.com/Gbergz/220ca8f60556a6dffcc647a494dc5aa8
Logs: [logs_2020-10-01-1.log](https://github.com/CyclopsMC/IntegratedDynamics/files/5313102/logs_2020-10-01-1.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
