### ISSUE TITLE
Generator duplicates contents

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#924]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Breaking a Generator duplicates it's contents.

#### Steps to reproduce the problem:

1. Put coal in Generator
2. Break Generator

#### Expected behaviour:

No duplication of fuel.

____

#### Versions:

- IntegratedDynamics-1.15.2-1.1.17
- Minecraft: 1.15.2
- Forge: 1.15.2-31.2.36

#### Log file:

Not applicable, I think.

**Comment by rubensworks** [comment]
Thanks for reporting!
