### ISSUE TITLE
Drying Basin continuously produces Menril Blocks

### ISSUE THREAD

**Issue by GloriousAlpaca** [CyclopsMC/IntegratedDynamics#925]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After making a menril block once, the drying basin continues to produce blocks after a short while.
This happened even after I tried breaking it and placing it again.

#### Steps to reproduce the problem:

1. Put menril wood in a crusher next to the drying basin
2. Crush the wood
3. Take the menril block out of the drying basin

#### Expected behaviour:

I believe it should not endlessly produce menril blocks for free.
____

#### Versions:

- This mod: 1.1.17
- Minecraft: 1.15.2
- Forge: 31.2.43

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I can't reproduce this myself. Perhaps Menril Resin is being piped in from elsewhere? Do you actively see Menril Resin in the Drying Basin? Can you try without any other mods installed?

**Comment by GloriousAlpaca** [comment]
The Bug only happens with the ["Performant"](https://www.curseforge.com/minecraft/mc-mods/performant) mod.

**Comment by rubensworks** [comment]
That mod is probably breaking things then, I would suggest reporting this over on their issue tracker.
