### ISSUE TITLE
Mechanical Squeezer recipe adding issues.

### ISSUE THREAD

**Issue by GlitchOG** [CyclopsMC/IntegratedDynamics#926]
Short description:

Unable to add recipes to the mechanical squeezer via craftweaker

script code:
mods.integrateddynamics.MechanicalSqueezer.addRecipe(<mekanism:oreblock>, <mekanism:dust:2> * 2, 0.50f, <mekanism:dust:2>);

error:

method found but none matches > available 4 and it gives me a list of basically how to add recipes. which i followed from the wiki

//MechanicalSqueezer.addRecipe(IItemStack inputStack, @Optional IItemStack outputStack, @Optional ILiquidStack outputFluid, @Optional(10) int duration);

Versions:

    This mod: 1.1.10
    Minecraft: 1.12.2
    Forge: 23.5.2854

**Comment by GlitchOG** [comment]
on the script code it does have the <> on the item stacks i dont know why it doesnt show when i type the code in the script code issue here.

**Comment by rubensworks** [comment]
@GlitchOG Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
From the wiki:
```
// inputStack, outputStack, outputFluid, duration
mods.integrateddynamics.MechanicalSqueezer.addRecipe(<minecraft:melon>, <minecraft:stick>, <liquid:water> * 100, 10);
```

So you seem to be using the wrong syntax. Duration and fluid params in your case must be swapped.
