### ISSUE TITLE
Entity Constant resets to "unknown"

### ISSUE THREAD

**Issue by GloriousAlpaca** [CyclopsMC/IntegratedDynamics#927]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After the Entity, used to make an entity constant, dies the constant switches to the value "unknown"

#### Steps to reproduce the problem:

1. Put an Entity Reader next to an Entity.
2. Put a variable card into the entity slot of the reader.
3. Materialize the variable card into another.
4. Kill the Entity
5. Variable Card 2 is now "unknown".

#### Expected behaviour:

The second variable card should still be of the first entity.
____

#### Versions:

- This mod: 1.1.17
- Minecraft: 1.15.2
- Forge: 31.2.43

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This is intended behaviour, as the entity var effectively binds to the entity in the world, which may die.
It sounds like you want to use the entity type instead, which you can obtain using the toString/name operator.
