### ISSUE TITLE
Items vanish while making a recipe variable on server

### ISSUE THREAD

**Issue by GloriousAlpaca** [CyclopsMC/IntegratedDynamics#928]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you click an item in your inventory while trying to make a recipe variable in the logic programmer, the item vanishes.
This only happens on a dedicated server.

#### Steps to reproduce the problem:

1. Join a server (Open on LAN does not work for this!)
2. Open the logic programmer and click on the "Recipe" operator
3. When you click an item in your inventory it vanishes until you close the programmer.

#### Expected behaviour:

The Item should not go invisible.
____

#### Versions:

- This mod: 1.1.18
- Integrated Crafting: 1.0.10
- Minecraft: 1.15.2
- Forge: 31.2.43

#### Log file:

[Message in the server console](https://pastebin.com/nNn4GKk9)

**Comment by rubensworks** [comment]
Thanks for reporting!
