### ISSUE TITLE
Client Crash: ClientChunkProvider cannot be cast to ServerChunkProvider

### ISSUE THREAD

**Issue by GloriousAlpaca** [CyclopsMC/IntegratedDynamics#929]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When connecting an Omni-Directional Connector and Item Importers/Exporters in a logic network, the game crashes.

#### Steps to reproduce the problem:

1. Make a small Storage Network out of an Omni-Directional Connector a Chest and an Item Interface
2. Connect the next Omni-Directional Connector to a Chest and an Item Exporter.
3. The game should crash after you activate the Item Exporter. (I put an Item Variable in the corresponding slot)
In our multiplayer world the crash happened after random intervals.
In my singleplayer world the game crashed immediately after activating the exporter.

#### Expected behaviour:

Obviously the game should not crash.
____

#### Versions:

- This mod: 1.1.18
- Integrated Tunnels: 1.6.14
- Integrated Terminals: 1.0.16
- Minecraft: 1.15.2
- Forge: 31.2.43

#### Log file:

[Singleplayer Crash](https://pastebin.com/fatx1VRG)
[Server Crash](https://pastebin.com/wu0FFE6Y)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by GloriousAlpaca** [comment]
I have just noticed, that the Omni-Directional Connector is irrelevant to the crash. The crash happens when a storage network is connected to an item exporter.

**Comment by GloriousAlpaca** [comment]
I'm very sorry but I believe the server crash is still happening.
