### ISSUE TITLE
When placing Readers/writers/panels etc on grass, a cable gets placed on other grass

### ISSUE THREAD

**Issue by Runesmacher** [CyclopsMC/IntegratedDynamics#93]
When placing Readers/writers/panels on grass with grass one block away, the grass will be replaced by a cable. Item gets consumed and the cable is placed and can be picked up.

forge 2116
cyclopscore 0.8.2-432
integrateddynamics 0.6.4

![2016-12-18_14 12 08](https://cloud.githubusercontent.com/assets/979451/21293680/0f636058-c52c-11e6-98eb-272085bdcb6c.png)
![2016-12-18_14 12 10](https://cloud.githubusercontent.com/assets/979451/21293679/0f60c58c-c52c-11e6-83c4-0617b6acda6e.png)

**Comment by Runesmacher** [comment]
It does give cool effect with tall grass ;)
![2016-12-18_14 17 22](https://cloud.githubusercontent.com/assets/979451/21293708/b4144cfc-c52c-11e6-8498-be14329c82ef.png)

**Comment by rubensworks** [comment]
Oh, how did you discover that?... :p
Must be an obscure edge case that is not properly being handled here: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.10/src/main/java/org/cyclops/integrateddynamics/item/ItemBlockCable.java

**Comment by Runesmacher** [comment]
When dowing stuff like this it is bound to happen ;)

![2016-12-18_14 22 43](https://cloud.githubusercontent.com/assets/979451/21293754/8076d97c-c52d-11e6-896d-f5546a55509a.png)
