### ISSUE TITLE
Server crash - "Could not find a part container"

### ISSUE THREAD

**Issue by kman3107** [CyclopsMC/IntegratedDynamics#932]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server crash happening after starting using ID. Twice. Both time with Mekanism machines.
Looks similar to #931 though we could boot the server back up and remove the ID parts no problem,
and our machines were still there.
1. Crash was an Item Exporter on a Metallurgic Infuser.
2. Crash was an Energy Importer on a Wind Turbine.

After removing ID from our machines (still in pack) we no longer have any crashes.

#### Steps to reproduce the problem:

After our two crashes we didn't feel the need to try that again. Besides it was on a server were people wanted to play.

#### Expected behaviour:

Nothing.

____

#### Versions:

- This mod: 1.1.18
- Minecraft: 1.15.2
- Forge: 31.2.36
- Mekanism: 9.10.9.422
- Modpack: Enigmatica 5 - 0.6.3

#### Log file:

https://pastebin.com/qpKYFRtr - Item Exporter on a Metallurgic Infuser from Mekanism
https://pastebin.com/X9JrB7Uf - Energy Importer on a Wind Turbine from Mekanism

#### PS:

If you want me to place this info inside the other issue, and delete this issue, I can do that.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share your full Forge log? There is some more information in there I need to debug this.

**Comment by kman3107** [comment]
I'm trying to get a hold if the log but the server is being hosted by someone I don't know and don't know how to contact.
The guy that I am playing with does know the guy (even lives right nearby to the server guy), but he doesn't seem to acknowledge
me when I ask him about the log.

I have asked 3 times over the past 2 days, the last time I even spammed a bit in the DM which we already had a conversation going. Nothing. I'll keep trying, but can't promise anything at this point.

**Comment by Iris-xii** [comment]
Having the same issue, have my log:
https://hastebin.com/ranupoyako.rust

<blockquote><div><strong><a href="https://hastebin.com/ranupoyako.rust">hastebin</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Closing this in favor of #931. (duplicate)
