### ISSUE TITLE
Item exporter cannot insert "exact amount" into multiple slots of an inventory if the slots' stack size is lower than the transferred amount

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#933]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have no idea what is happening, but my item exporter refuses to insert wither skeleton skulls into my wither builder.

It used to work just fine, I don't know what changed. Using a chest instead of the machine works fine, and moving the exporter with the wrench (preserving settings) to another location on the network attaching it to a chest, also works fine. Using the same exporter on a hopper works fine, and using a hopper to insert the items into the machine instead of using Integrated Tunnels altogether, also works fine. The other exporter for soul sand works just fine as well.

Hereby a world download, because for the life of me I don't understand why this doesn't work. I've tried everything I can think of. Please help me find what is causing this!

#### Steps to reproduce the problem:

0. Install Sky Factory 4 and the world download
1. Load the provided world
2. (assuming you spawn at world spawn) walk to the west into the grass room and find the Hunting Dimension cake (Telepatries mod) it is the middle cake in the corner. Right click to enter the other base (it is mob free and safe)
3. Step onto the white elevator block, shift to get down into the floating cellar (don't walk off the floor, I only have 3 minutes of flight at the moment, in case you inherit it)
4. Walk towards the big blue cube of "growth crystals", the wither builder is to its right
5. The faulty exporter is on the north side, with a variable card of type "Item" in it. The one on the south is for soul sand (its variable card is in my inventory)

There also is a more convenient elevator block next to the mystical essence field, next to the growth crystals.
Some tools are in the Construct's Armory toolbelt, might need to configure the hotkey.

#### Expected behaviour:

The exporter with the card for wither skeleton skulls is properly connected to the black hole controller with the items in it, but should be inserting skulls, and it isn't. As if the network has no access to the source inventory.

____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-1.1.6 and IntegratedTunnels-1.12.2-1.6.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Sky Factory modpack: 4.2.2

- Download from google Drive (423MB sorry): https://drive.google.com/file/d/11HbBJJAg9IQB5j7L4RIWUsuGOPDjSrnV/view?usp=sharing

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Insertion fails if using property settings on the exporter:
- Transfer rate: 3
- Exact amount: true
- Check stack size: true

However if I use these settings it suddenly works again:
- Transfer rate: 64
- Exact amount: false
- Check stack size: false

But the three input slots for the skulls fill instantly when not specifying the exact mount, so why can't I specify the exact amount? Can an exporter insert into multiple slots individually within the same tick?

**Comment by rubensworks** [comment]
You seem to be running behind several versions. Could you try again with the latest?

Also, I would appreciate a minimal reproducible example that doesn't involve downloading a huge modpack.
Starting from a clean new world is what I need to reproduce this.

**Comment by Jack-McKalling** [comment]
I'm sorry that I didn't provide that from the start, it was a whole day of frustration and I ran out of energy to find more details. But I will try that soon, thanks.

**Comment by Jack-McKalling** [comment]
I've reproduced the issue with these mods/versions installed:

Forge 14.23.5.2854
Common Capabilities 1.12.2-2.4.6
Cyclops Core 1.12.2-1.6.4
Ender Utilities 1.12.2-0.7.15
Hwyla 1.8.26-B41_1.12.2
Integrated Dynamics 1.12.2-1.1.6
Integrated Tunnels 1.12.2-1.6.11
jei 1.12.2-4.15.0.295

Steps to reproduce:
1. Place chest, logic cable to its right, with an Adjustable Storage Unit (Ender Utilities) next to that
2. Place Item Interface between chest and cable
3. Place Item Exporter between cable and ASU
4. Edit the properties of the exporter's "Export All Items" aspect, from default values, set Transfer Rate=3, Exact Amount=true
6. Insert a blank Variable Card into the aspect
7. Right click the ASU and set the Slots to 3 and Stack size to 1
8. Insert a stack of any item (e.g. Stone) into the chest on the left
   > notice nothing is exported, eventhough there is space for the exact amount of items (although that counts to the total inventory)

After all of this I think this might not actually be a bug, depending on what is the intentional design. However it took me a great deal of time to figure this one out. Also, sorry but I cannot update InDy to the latest version, seeing the other mod hasn't been updated to 1.15 yet, and I can only show the problem with an inventory that limits stack sizes.

The logic here I'm assuming, is that the exporter cannot export an exact amount of items if that amount doesn't fit in the first available slot, even if it owuld fit across multiple slots.

**Comment by rubensworks** [comment]
> Right click the ASU and set the Slots to 3 and Stack size to 1

Doing this will make it so that transfer between slots only happens for stack size 3.
The "spread" behaviour you want therefore won't work. You'll probably just want to set transfer rate to 1 in your case.

**Comment by Jack-McKalling** [comment]
Ok I understand, thanks for looking into it. I don't know much about the numbers in the code, the behaviour didn't look right on first glance.
