### ISSUE TITLE
crazy memory usage

### ISSUE THREAD

**Issue by donnymoonshine** [CyclopsMC/IntegratedDynamics#935]
#### Issue type:high memory load

- :snail: Performance issue 

____

#### Short description:

added this to all the mods 3 expert at the duplicating phase during foam fix the memory usages goes to 100% and constantly stays there during actual game play

#### Steps to reproduce the problem:

1. load all the mods with integrated dynamics and foam fix installed

____

#### Versions:

- This mod: integrated dynamics
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It appears you forgot to add the profiler logs as explained here: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>
