### ISSUE TITLE
Unable to read recipes

### ISSUE THREAD

**Issue by vDubs93** [CyclopsMC/IntegratedDynamics#936]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When attempting to follow the tutorial in the book, I am unable to display the ingredients for a chest dynamically.

#### Steps to reproduce the problem:

1. Attach machine reader to side of crafting table
2. Insert variable card into "Recipe by output" slot
3. Follow steps in tutorial to apply resulting operator to variable card of type ingredients with chest as list item
4. Insert ingredients and operator variable cards into variable store
5. Insert "Apply" variable card into display attached to the same network as the variable store

#### Expected behaviour:

I expected to see the ingredients for a chest in the display panel.
____

#### Versions:

- This mod: 1.1.19
- Minecraft: 1.15.2
- Forge: 31.2.45

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
![2020-10-31_14 33 49](https://user-images.githubusercontent.com/440384/97780655-372a0380-1b86-11eb-9caf-4e5536b796db.png)
Seems to work fine here.
I suggest you try again, maybe you made a mistake somewhere, or a mod is messing with recipes.

**Comment by boneskull** [comment]
Cross-referencing https://github.com/AllTheMods/ATM-6/issues/768 where you may find you are able to reproduce

**Comment by rubensworks** [comment]
@boneskull What mod+forge version are you using?
Can you reproduce this with no other mods installed?

**Comment by boneskull** [comment]
This is the latest version of the ATM6 pack .. will look up the numbers tomorrow.

**Comment by boneskull** [comment]
![image](https://user-images.githubusercontent.com/924465/103921741-b7f60600-50c7-11eb-92db-21b79a79c552.png)

Forge v35.1.29

**Comment by boneskull** [comment]
I tried the change with the new release, and it's still not working for me as I mentioned [here](https://github.com/CyclopsMC/CyclopsCore/commit/a665749ffead666db017cd66ed104c8f9861110f).  Is there some way I can provide more logs or info?

**Comment by rubensworks** [comment]
@boneskull Still working for me with all the latest mod versions.

I've noticed in your last comments that you didn't try without any other mods installed. So I suspect some other mod in your pack is messing with things, or some weird conflict is happening. I suggest taking this up with your modpack author. This will require some cross-mod or log analysis.

Feel free to come back to me if there's something I can fix in ID.

**Comment by tetious** [comment]
I think the mod [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench) is causing this. The recipe list is completely empty when looking at any machine with the machine reader. Reading the mod's description, it disables recipe support both server and client-side.

When I removed FastWorkbench from my custom pack, everything started working as expected.

**Comment by rubensworks** [comment]
@tetious That sounds very likely, thanks for looking into this!
