### ISSUE TITLE
Storage Drawers + Item Exporter

### ISSUE THREAD

**Issue by TristonWasik** [CyclopsMC/IntegratedDynamics#938]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

If you attach an item exporter to export all items into a drawer controller or a single drawer that is locked but has empty slots it causes large amounts of lag (roughly 2.8 million ur/t in the world event loop).

#### Steps to reproduce the problem:

1. Place a storage drawer that is locked but has empty slots (I tried with a empty 2x2)
2. Add an item exporter with an empty variable card that exports all items (mine was attached to my system which hard large amounts of items)

____

#### Versions:

- This mod: 1.1.10 (core), 1.6.1.3 (tunnels)
- Minecraft: 1.12.2 (FTB University Modpack)
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you include the profiling output as explained here? https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>
