### ISSUE TITLE
Item Interface And Storage Drawers

### ISSUE THREAD

**Issue by TristonWasik** [CyclopsMC/IntegratedDynamics#939]
#### Issue type:

- :question: Question 

____

#### Question:

I am generally use storage drawers extensively in my builds. In this setup I have a crafting interface (off screen) that is auto crafting polymer for the simulation chambers (deep mob learning) and stores them in that mini drawer setup. XNet is controlling the input/outputs of the simulation chambers and loot fabricators (this works fine). The issue, is that my crafting job randomly stops running keeping that drawer stocked with polymer. Sometimes it will run for an hour or 2, some times it breaks after the first recipe finishes. I have tried setting 'ignore target inventory' both true and false but neither helps. I removed the void upgrade from the drawer since I know that can bug out mods that interact with it (translocators). Thoughts/suggestions?

[Screenshot](https://imgur.com/a/pS85mpc)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Could you try this without any other mods installed?
