### ISSUE TITLE
Very Poor Event Subscriber Performance

### ISSUE THREAD

**Issue by Poisonsting** [CyclopsMC/IntegratedDynamics#940]
#### Issue type:

- :snail: Performance issue 

____

#### Steps to reproduce the problem:

1. Fill a compact machine with machines from other mods
2. Use a dedicated (internal to Compact Machine only) Integrated Dynamics network
3. Experience an Integrated Dynamics Event Subscriber Tick Delay of 389898 μs/t

____

#### Versions:

- This mod: 1.12.2-1.1.10
- Integrated Tunnels: 1.12.2-1.6.13
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2854

#### Profiler output: 
[University Sample.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/5575786/University.Sample.zip)

![Lag Goggles](https://user-images.githubusercontent.com/3866157/99843226-71a41200-2b2e-11eb-9cfe-1c64212bdd79.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Keridos** [comment]
Might this also be related to large tick times when requesting applied energistics autocrafting when said AE2 network has storage buses/interface attached to logic networks interfaces?
