### ISSUE TITLE
NBT.as_string outputs Double instead of String

### ISSUE THREAD

**Issue by spix-rayt** [CyclopsMC/IntegratedDynamics#941]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Operator NBT.as_string outputs Double instead of String

![Screenshot_3](https://user-images.githubusercontent.com/16408231/100640622-b22e3780-3347-11eb-936d-df0c365e81fa.png)

____

#### Versions:

- This mod: 1.1.19
- Minecraft: 1.15.2
- Forge: 31.2.45

**Comment by rubensworks** [comment]
Thanks for reporting!



<div align="right"><a href="https://github.com/CyclopsMC/IntegratedDynamics/actions/runs/392084001">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>
