### ISSUE TITLE
[API] How to properly invaidate variables?

### ISSUE THREAD

**Issue by LubieKakao1212** [CyclopsMC/IntegratedDynamics#942]
#### Issue type:

- :question: Question 

____

#### Question:

I was trying to make a OpenComputers compatibility addon, and encountered a problem with updating variable values. 
When I was testing and used variable card directly referencing my value it updated corectly, but when I used a variable referencing that variable card it updated its value only when I reinserting the card. 
Is calling invalidate on a variable not enough?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).



<div align="right"><a href="https://github.com/CyclopsMC/IntegratedDynamics/actions/runs/401798174">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by LubieKakao1212** [comment]
I forgot about that possibility.

**Comment by rubensworks** [comment]
@LubieKakao1212 Could you share your code? It's a bit difficult to understand what could be going on.

In any case, the variables created from proxies should be a good basis to start from in your case.

**Comment by LubieKakao1212** [comment]
I added you to my repository.
Please don't judge the cleannes of my code.
see class TIleDataBridge method setValue

**Comment by rubensworks** [comment]
@LubieKakao1212 It looks like your re-creating the variable after invalidation.
Instead, you probably want to reuse the same variable, but call `invalidate()` if its value has changed.

I recommend having a look at the source code of Integrated REST: https://github.com/CyclopsMC/IntegratedREST/
It feels very similar to what you are trying to achieve.

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedREST">CyclopsMC/IntegratedREST</a></strong></div><div>Expose Integrated Dynamics networks as a REST API. Contribute to CyclopsMC/IntegratedREST development by creating an account on GitHub.</div></blockquote>

**Comment by LubieKakao1212** [comment]
@rubensworks
Thanks, It almost works now.
