### ISSUE TITLE
[1.16] Tag Menril Berries as fruits

### ISSUE THREAD

**Issue by Lykrast** [CyclopsMC/IntegratedDynamics#944]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

*(This will only apply to a future 1.16.4 port and not any currently released version)*

Cooking mods like Simple Farming use the `forge:fruits` tags (and others) for their recipes, so tagging Menril Berries with that adds a small easy compatibility with them.

**Comment by rubensworks** [comment]
Thanks for the suggestion!



<div align="right"><a href="https://github.com/CyclopsMC/IntegratedDynamics/actions/runs/428440039">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>
