### ISSUE TITLE
Lag spikes with AE2 crafting when connected to logic network

### ISSUE THREAD

**Issue by Keridos** [CyclopsMC/IntegratedDynamics#945]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:
AE2 autocrafting lags enormously when it is connected via storage bus to a logic network interface

#### Steps to reproduce the problem:
1. Setup a modest AE2 Autocrafting setup.
2. Place some (or all of the items/fluids) on a logic network with interfaces connected to chests/tanks etc. Attach this system via logic interface/me storage bus to the AE2 System.
3. try to craft something in AE2. After clicking next in the amount window the server thread hangs for a long time

Time can be well over 30 seconds on my FTB Interactions serve

____

#### Versions:

- This mod: 1.1.9
- AE2: rv6-stable7
- Minecraft: 1.12.2
- Forge:  14.23.5.2847

#### Profiler output:

[lagspikeae2idnetwork.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/5718585/lagspikeae2idnetwork.zip)

#### Additional info:
If you want a copy of the world just tell me.

**Comment by rubensworks** [comment]
Thanks for reporting!



<div align="right"><a href="https://github.com/CyclopsMC/IntegratedDynamics/actions/runs/431587170">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by rubensworks** [comment]
I don't see a log mentioned, but I assume you're using an outdated CommonCapabilities version (a method is called that has been removed in https://github.com/CyclopsMC/CommonCapabilities/commit/43daf8f6202192b40afae748cd752139ddad92fe).
This performance issue has been fixed there a while ago: https://github.com/CyclopsMC/CommonCapabilities/commit/43daf8f6202192b40afae748cd752139ddad92fe

**Comment by drunkenQCat** [comment]
hi, @Keridos , i am playing atm10(1.21.1) with ae2 and id, and tried to connect id network to ae2 network by storage bus, but doesn't work. so i found your issue, and hope to know how it works at 1.12.2. thanks.
