### ISSUE TITLE
Cow's death/hurt sound crashes the game

### ISSUE THREAD

**Issue by Minamikaze392** [CyclopsMC/IntegratedDynamics#946]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The game crashes with a variable of deathsound created with a cow

#### Steps to reproduce the problem:

1. Read a cow Entity into a variable with a Entity Reader.
2. Use the Logic Programmer to create a deathsound or hurtsound String variable using the Entity variable.
3. Putting the String variable in various devices (eg. Materializer / Audio Writer) leads to a crash. 

#### Expected behaviour:

It should give me some mooos.
Or at least it shouldn't crashes the game even if no sound can be retrieved.
____

#### Versions:

- This mod: 1.12.2-1.1.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

#### Log file:
https://pastebin.com/FcRvHJqy

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Minamikaze392** [comment]
Wow that's fast response!
Probably it happens for other entities too, but not much meaning to test them all I think.
