### ISSUE TITLE
Crashing during 'done' phase of freezing data (interaction with elevatorid, ae2, forbidden arcanus) 1.16.4

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [CyclopsMC/IntegratedDynamics#947]
#### Issue type:

- :bug: Bug 

____

#### Short description:

During the loading phase of the game, evilcraft has some about a null Resource location, that crashes with both applied energistics 2 and openblocks elevator mod (elevator id). Also with forbidden arcanus. 

#### Steps to reproduce the problem:

1. New vanilla client with forge 35.1.15
2. add cyclopscore, evilcraft, jei, elevatorid, appliedenergistics2 8.2.beta1, forbidden_arcanus 1.0.0 1.16.4
3. Crash during final freezing of data

#### Expected behaviour:

Loading to game screen. 

____

#### Versions:

- This mod: integrated_dynamics 1.0.0 1.16.4
- Minecraft: 1.16.4
- Forge: 35.1.15

#### Log file:

https://github.com/CyclopsMC/EvilCraft/issues/808
https://paste.ee/p/dT5Wq

**Comment by rubensworks** [comment]
Thanks for reporting!
