### ISSUE TITLE
[1.16] Disabling biome generation doesn't work

### ISSUE THREAD

**Issue by Pentasis** [CyclopsMC/IntegratedDynamics#951]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have set generateInOverworld = false and am using vanilla world and/or the quark realistic presets. Meneglin biomes still generate.
The only other mod that touches biomes in my pack is Traverse reforged.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.1.20
- Minecraft: 1.16.4
- Forge: 35.1.15

**Comment by rubensworks** [comment]
Thanks for reporting!
