### ISSUE TITLE
Terrain errors with BYG worldgen

### ISSUE THREAD

**Issue by willrun4fun** [CyclopsMC/IntegratedDynamics#953]
I tried out the mod with Oh the Biome's You'll Go and got bad chunk borders and odd mixing of biomes.
I know the mod just came out in beta so just a happy thumbs up for seeing it coming to 1.16 :)
I just removed and rolled back my backup.

#### Issue type:

- :bug: Bug 

____

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Did you add this mod to an _existing_ world?
If so, chunk borders are to be expected, as worldgen and seed usage will be altered.

**Comment by willrun4fun** [comment]
yes I did.  Is the add without worldgen changes issue patched?  In that case would a person just need to bring in saplings as admin?

**Comment by rubensworks** [comment]
Ok, considering this a non-issue then.
