### ISSUE TITLE
duping menril [1.16]

### ISSUE THREAD

**Issue by Staegrin** [CyclopsMC/IntegratedDynamics#954]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Crystalized menril blocks keep appearing in the drying basin.

#### Steps to reproduce the problem:

1 Put down a squeezer and drying basin next to each other. Couldn't place menril log into the squeezer so I used a hopper. 
2 Hopped on the squeezer until finished and the fluid menril went into the drying basin.
3 Hopper underneath pulls out a block of crystalized menril
4 After the time it would take to crystalize another block another block appears. While I have not used the squeezer again. 
5 Blocks keep appearing in the drying basin until game restart or block is broken.
![2021-01-01_19 04 39](https://user-images.githubusercontent.com/8494635/103444017-fa04ef00-4c64-11eb-95f0-a3ab7c9b2c00.png)
![2021-01-01_19 04 43](https://user-images.githubusercontent.com/8494635/103444018-fc674900-4c64-11eb-9780-d5cd74edb166.png). ...

#### Expected behaviour:

One block of crystalized menril per menril log
____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.1.21
- Minecraft: minecraft 1.16.4
- Forge: 35.1.13

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Staegrin** [comment]
Graag gedaan Ruben. Een gelukkig nieuwjaar en bedankt voor je harde werk.

**Comment by Davivs69** [comment]
I faced a similar problem, while adding blood (from evilcraft) (any amount lower then 1000mb) into the drying basin. The drying basin made that amount reset to 1000mb, effectively duping blood when picking it up again.

**Comment by Staegrin** [comment]
After updating to IntegratedDynamics-1.16.4-1.1.22 and CyclopsCore-1.16.4-1.9.4 this seems to be fixed. Thanks for the quick work.

**Comment by rubensworks** [comment]
I actually didn't change anything related to this.
I'll leave this open until I can confirm myself it has been fixed :-)
