### ISSUE TITLE
World gen GUI crashes

### ISSUE THREAD

**Issue by Knito58** [CyclopsMC/IntegratedDynamics#957]
#### Issue type:

- :bug: Bug World Creation GUI crashes

#### Short description:

With the integrated series installed, the "create new world" screen shows "saving game" and crashes.
Continuing old game is possible.

#### Steps to reproduce the problem:

In my case: Throw integrated xxx into the mods folder, then try to start a new world

#### Expected behaviour:

I can see the create world GUI and generate a new world.

#### Versions:

- This mod: latest
- Minecraft: 1.16.4
- Forge: 35.1.28

#### Log file:

https://pastebin.com/aUDm9uJz

Did not find any hint in the crash log file. Took me an hour disabling this and that mod and re-enabling it when the error persisted. Only by disabling the integrated series the GUI was accessible again.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Knito58** [comment]
Wow!

**Comment by rubensworks** [comment]
I see this mentioned in the logs:

> com.telepathicgrunt.blame.main.DynamicRegistriesBlame.findUnregisteredConfiguredFeatures

Could you report this to this mod's issue tracker?
They are probably reading things in such a way that breaks the game, while this breakage does not occur without this mod reading things.

**Comment by Knito58** [comment]
Ok, I'll do so.

**Comment by Knito58** [comment]
https://github.com/owmii/Powah/issues/135
