### ISSUE TITLE
World-Gen Issue

### ISSUE THREAD

**Issue by furiousskeleton** [CyclopsMC/IntegratedDynamics#960]
#### Issue type: World-Gen

- :bug: Bug 

____

#### Steps to reproduce the problem: Install latest version of Integrated Dynamics and Forge

1. Install Forge and Integrated Dynamics into the mods folder

#### Expected behaviour:

 Load into the new world

____

#### Versions:

- This mod: Latest
- Minecraft: 1.16.4
- Forge: 35.1.29

#### Log file:

 https://pastebin.com/EZahTf6q

**Comment by rubensworks** [comment]
Thanks for reporting!
