### ISSUE TITLE
[1.16.4] Mechanical Squeezer Height

### ISSUE THREAD

**Issue by GloriousAlpaca** [CyclopsMC/IntegratedDynamics#962]
#### Issue type:

- :question: Question 

____

#### Question:

Is it intended that you need to jump from a relatively high height to use the mechanical squeezer? In past versions it was sufficient to jump directly on the squeezer, but now you need to jump from about 5 blocks high to see any progress.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Really? 5 blocks? That sounds like a bug in your pack.
In any case, I've been playing with this mod in 1.16 myself, and I'm able to jump the normal height (1 block) and get the squeezer to work just fine.

**Comment by GloriousAlpaca** [comment]
In Singleplayer the squeezer is working normally, so I believe it's a conflict with Performant. By the way #954 could be a conflict with Performant too, as I have the same bug on my server but not in Singleplayer (Performant is only installed on the server).

**Comment by rubensworks** [comment]
Oh, I heard very bad things of Performant, they apparently do some game-breaking optimizations, resulting in weird bugs like this, so I would recommend against using it.

I would suggest opening an issue on their tracker to resolve this.
