### ISSUE TITLE
the ability for the block reader to check growth state of a block

### ISSUE THREAD

**Issue by Algester** [CyclopsMC/IntegratedDynamics#964]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
this is somewhat related to astral sorcery's celestial crystal cluster being an obfuscated list when it comes to integrated dynamics

if one looks into the MC debug menu the game knows said crystal has growth states (0-4)

considering if one uses f3+I when looking at the crystal cluster this is what you get
https://pastebin.com/mY39dUpC

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Merging this issue with #765.
