### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by tobi1449** [CyclopsMC/IntegratedDynamics#966]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server log keeps getting spammed with ```[org.cyclops.cyclopscore.persist.nbt.NBTClassType:performActionForField:622]: java.lang.NoSuchFieldException: modifiers```

#### Steps to reproduce the problem:

1. No idea honestly

#### Expected behaviour:

No Exceptions getting spammed.

____

#### Versions:

Server 1.16.4
Forge 35.1.28
CyclopsCore 1.9.4
Evilcraft 1.0.4
IntegratedDynamics 1.1.22
IntegratedTerminals 1.1.0
IntegratedTunnels 1.16.14
IntegratedCrafting 1.0.10
CommonCapabilities 2.5.5
CapabilitiesProxy 2.1.8

#### Log file:

https://pastebin.com/1BGKEV6H

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> No idea honestly

Really nothing you can share that could be causing the problem to trigger?
Otherwise this will be pretty much impossible for me to reproduce.

**Comment by tobi1449** [comment]
I'll try to narrow it down, first thing: it seems to only throw the exceptions while loading a world, but often enough that the log file gets too big for MultiMC on my client. 
It also only seems to occur both on my client and my test server on my windows machine. The "real" server that runs on debian doesn't seem to get this.

**Comment by tobi1449** [comment]
I haven't had the time to do a full check but it managed to get a very similar error with a reduced setup:
Create a server with EvilCraft, CommonCapabilities, CapabilityProxy, IntegratedDynamics, Tunnels, Terminals & Crafting
Let it generate a new world and stop it
Four similar errors show up on saving:
https://pastebin.com/Ef5TxDpz

They seem to only show up when you generate a new world though.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/Ef5TxDpz">[09Jan.2021 11:22:56.650] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by tobi1449** [comment]
I found the culprit: I was using MultiMC to start Minecraft which uses my systems Java. Switching to the CurseForge launcher which uses the Java version Minecraft provides fixed the issues (and some other issues e.g. with GUIs too).

**Comment by rubensworks** [comment]
@tobi1449 That's great to hear.
Do you know what Java version was causing problems? Might help others in the future.

**Comment by tobi1449** [comment]
The Java version is (build 14.0.2+12-46)

**Comment by rubensworks** [comment]
Java 14 :O I'm surprised Forge can even run with that version.
