### ISSUE TITLE
Question about a weird glitch w/ drying basin

### ISSUE THREAD

**Issue by Lloergwaed** [CyclopsMC/IntegratedDynamics#968]
mod added to direwolf20 1.16.4 latest version of both (modpack and mod.

the dryin basin when receiving a fluid that it can transform will create the item infinitly? any idea what may be causing that? is it something anyone esle have encounter?

**Comment by Lloergwaed** [comment]
sorry for the duplicate post have no idea why it did that?

**Comment by rubensworks** [comment]
@Lloergwaed Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
