### ISSUE TITLE
1.16.4 - Tools For Obsidian achievement not registering 

### ISSUE THREAD

**Issue by Merthew** [CyclopsMC/IntegratedDynamics#969]
#### Issue type:

- :bug: Bug

____

#### Short description:

After doing what I'm supposed to for the achievement, nothing happens. I do not have the achiement.

#### Steps to reproduce the problem:

Do the things required, nothing.

#### Expected behaviour:

Get the achiement.
____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.2.0.jar
- Minecraft: 1.16.4
- Forge: 35.1.4

![image](https://user-images.githubusercontent.com/23420800/104368136-ad81a500-54e9-11eb-9bb1-1fe275fcf302.png)

![image](https://user-images.githubusercontent.com/23420800/104368117-a78bc400-54e9-11eb-91b3-891112ca4b7f.png)

![image](https://user-images.githubusercontent.com/23420800/104368162-b70b0d00-54e9-11eb-8e8a-c450e3c8fe82.png)

![image](https://user-images.githubusercontent.com/23420800/104368199-bffbde80-54e9-11eb-9aed-fa02dde1cb51.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
