### ISSUE TITLE
Right Click on Energy Battery in ATM6 crashes client and breaks connection to server

### ISSUE THREAD

**Issue by Mnementh** [CyclopsMC/IntegratedDynamics#970]
#### Issue type: 

- :bug: Bug 

____

#### Short description:

Right Click on Energy Battery in inventory on ATM6 crashes client and breaks connection to server.

Client only crashes client, client\server closes connection to server and does not allow reconnect.

#### Steps to reproduce the problem:

1. Make an Energy Battery (Mine was charged)
2. Shift-Right click while in inventory to activate export
3. crash

#### Expected behaviour:

Should just make it glow

____

#### Versions:

- This mod: 1.16.4-1.1.22
- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.29-client

Already contacted the ATM6 support, they said it looked like an issue with the ID and look here, if no issue found make a bug report

#### Log file:
https://hastebin.com/anoquwuvep.rb

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Link doesn't appear to contain anything. Could you reshare?

**Comment by FuzzyFoxe** [comment]
Since this is effecting me right now, I'll help you cut to the chase. Activating the uncharged one is fine, the fully charged one is not so fine. Here's my "latest.log" file from a fresh test.
Hope it helps.
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/5838204/latest.log)

**Comment by FuzzyFoxe** [comment]
Seems this is still happening with version 1.2.0
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/5891789/latest.log)

**Comment by rubensworks** [comment]
@FuzzyFoxe 1.2.0 is not the latest version of ID.

**Comment by FuzzyFoxe** [comment]
Oh, shoot. Sorry about that. ATM6 has yet to update this mod then. Or curseforge is being a pain again. Either way.
