### ISSUE TITLE
Append values to a list by crafting

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedDynamics#971]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

When creating or appending to lists, it would be good to be able to put on a crafting grid:
a) two or more item variable cards
b) a list variable card plus a (number of) item variable card(s)
c) Two list variable cards

Optionally add an empty variable card; then this card will be used for crafting.

The crafting result will be
a) A list of two or more items; the topmost leftmost card will be used (if there is no empty card on the table)
b) The list card will now also contain the items
c) All lists will be concatenated; the topmost leftmost card will be used (if there is no empty card on the table)

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by 7eggert** [comment]
PS: Maybe this should also work by putting other items onto the table. E.g. not put a variable card "stone" onto the table but a stack of stones.

**Comment by rubensworks** [comment]
While this would be possible, it doesn't really fit into the vision of this mod.
This would be something for the Logic Programmer (for which enhancements are definitely possible).

**Comment by 7eggert** [comment]
"Logic Programmer (for which enhancements are definitely possible"

Yes, please, it's very cumbersome to craft a "a + b" card and to materialize that or to get / cheat all the items for a task that should be simple.
