### ISSUE TITLE
Facade Top And Bottom Face Textures Oriented Improperly

### ISSUE THREAD

**Issue by Trainerredstone7** [CyclopsMC/IntegratedDynamics#974]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Specifically, the textures of the top and bottom faces of a facade are rotated 180 degrees about the z axis when placed.

#### Steps to reproduce the problem:

1. Place a stone brick facade on a logic cable.
2. Place a regular stone brick next to it.
3. Note that the textures of the top and bottom faces of the stone brick facade are rotated 180 degrees compared to the stone brick.

I've also attached an image demonstrating the problem. The center four stone bricks and center four gold ore blocks are facades - the rest are normal blocks.
![2021-01-21_22 27 34](https://user-images.githubusercontent.com/12863826/105455833-057e8100-5c39-11eb-90a3-ffab55311250.png)

I'd also like to note that the textures for the sides are all correct - they are *not* flipped or swapped.

#### Expected behaviour:

The textures of the facade should precisely match the textures of the block it mimics.

____

#### Versions:

- This mod: 1.16.4-1.3.0
- Minecraft: 1.16.4
- Forge: 35.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Trainerredstone7** [comment]
I've found and fixed the problem - mind if I submit a pull request?

**Comment by rubensworks** [comment]
Sure, PRs are always welcome!
