### ISSUE TITLE
[1.16.4] Config for prioritizing outputs of recipes using tags.

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedDynamics#976]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Integrated Dynamics uses tags to determine output of many recipes - I would like a config to prioritize which mod the output should come from, if the mod has it. This sort of config usually accepts an array of strings, where the first element has first priority, then the second and so on.
A similar config is available in Immersive Engineering, JAOPCA and Ressourceful Bees, if you're looking for inspiration :)

Thanks for reading, I hope you'll consider it.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Note to self: this is how IE does it: https://github.com/BluSunrize/ImmersiveEngineering/blob/087c55e9150cd8ce664ff67200af63453668cd84/src/main/java/blusunrize/immersiveengineering/api/IEApi.java#L98-L120

I'll try to include something like this in the next release.

<blockquote><img src="https://avatars.githubusercontent.com/u/4106382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/BluSunrize/ImmersiveEngineering">BluSunrize/ImmersiveEngineering</a></strong></div><div>Wires, transformers, high voltage! Bzzzzt! Contribute to BluSunrize/ImmersiveEngineering development by creating an account on GitHub.</div></blockquote>
