### ISSUE TITLE
Red Tulip crushing recipes are wrong

### ISSUE THREAD

**Issue by MuteTiefling** [CyclopsMC/IntegratedDynamics#977]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Red Tulips in the Mechanical Squeezer have two recipes. One would appear to be meant to accept rose bushes as the input.

![image](https://user-images.githubusercontent.com/9543430/105537249-a283fd00-5cbf-11eb-9ac8-0ce1bda5680a.png)

Similarly, in the manual Squeezer, things are a bit odd as well: 

![image](https://user-images.githubusercontent.com/9543430/105537292-b29bdc80-5cbf-11eb-8300-29a80bf4a3bb.png)

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

Roses should output the larger dye quantitiy of the tulip recipes. Tulips shouldn't squeeze down to 8 roses. :D 
____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.3.0
- Minecraft: 1.16
- Forge: 35.1.36

**Comment by rubensworks** [comment]
Thanks for reporting!
