### ISSUE TITLE
Facades of Transparent Blocks Are Not Transparent

### ISSUE THREAD

**Issue by Trainerredstone7** [CyclopsMC/IntegratedDynamics#980]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When placed, facades of transparent blocks such as glass are opaque.

![2021-01-24_22 41 57](https://user-images.githubusercontent.com/12863826/105670319-b41efd80-5e95-11eb-9267-a0abc9847e70.png)

#### Steps to reproduce the problem:

1. Place a glass facade on a logic cable.
2. Observe that the parts of the facade texture that should be transparent are instead an opaque gray.

#### Expected behaviour:

The facade should be transparent and look the same as a normal glass block.

____

#### Versions:

- This mod: 1.16.4-1.3.0
- Minecraft: 1.16.4
- Forge: 35.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!
