### ISSUE TITLE
Server crashes when trying to get the Dynamic List Filtering advancement

### ISSUE THREAD

**Issue by Olfi01** [CyclopsMC/IntegratedDynamics#981]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server crashes when trying to get the Dynamic List Filtering advancement

#### Steps to reproduce the problem:

1. Create a list of integers [1, 10, 100] (variable card)
2. Store relational equals operator on variable card
3. create integer 10 variable card and apply equals operator on it
4. store filter operator on variable card
5. use apply2 on the result of 2, the result of 3 and the list
6. put result of 5 into a display panel
7. put all the other variable cards into a variable store connected to the display panel

#### Expected behaviour:

Display panel shows 10 and I get the advancement

#### Actual behaviour:

Server crashes

____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.4.0
- Minecraft: 1.16.5
- Forge: 36.0.1

#### Log file:
https://pastebin.com/VnQMm5C0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Olfi01** [comment]
Additional Information: I tried to give myself the advancement via command, no problems there.
