### ISSUE TITLE
Menril Sapling crash Minecraft.

### ISSUE THREAD

**Issue by ChunChun-Japan** [CyclopsMC/IntegratedDynamics#985]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft crash when Menril Sapling grows with random tick.

#### Steps to reproduce the problem:

1. Plant Menril Sapling on dirt.
2. Set random tick large enough.(example:30000)
3. Minecraft crash.

When use bone meal, Menril Sapling only disappear.

#### Expected behaviour:

Sapling grows into a tree.
____

#### Versions:

- This mod: 1.16.4-1.4.1
- Minecraft: 1.16.4
- Forge: 1.16.4-35.1.37

#### Log file:

Crash Report
https://pastebin.com/kp3CZfgk

**Comment by rubensworks** [comment]
Thanks for reporting!
