### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Pentasis** [CyclopsMC/IntegratedDynamics#986]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Placing a reader will crash the server. 
It has happened a few times over the past week both in MC 1.16.4 and now 1.16.5 with block-readers and redstone-readers.
Reloading the world will solve it until the next crash.

#### Steps to reproduce the problem:

I cannot reliably reproduce it :(

#### Expected behaviour:

____

#### Versions:

- This mod: 1.4.1
- Minecraft: 1.16.4 & 1.16.5
- Forge: 36.0.10 (on .5)

Modlist:
https://pastebin.com/sj3aGuPw
Sorry for the formatting.

#### Log file:

https://paste.ee/p/SYRFE

**Comment by rubensworks** [comment]
Thanks for reporting!
