### ISSUE TITLE
Crash with facade

### ISSUE THREAD

**Issue by Pentasis** [CyclopsMC/IntegratedDynamics#987]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I made a facade with a thick pole from Engineers decor. Placing it crashed the game and loading the world also crashed it. I had to remove your mod, load the game, save, add your mod again and reload to fix it.

#### Steps to reproduce the problem:

1. combine a thick pole from Engineers decor with a facade
2. place the facade on a logic cable

#### Expected behaviour:

Either no crash, or being unable to craft the facade to prevent the crash.

____

#### Versions:

- This mod: 1.4.1
- Minecraft: 1.16.5
- Forge: 36.0.10

#### Log file:

https://paste.ee/p/QHW77

**Comment by rubensworks** [comment]
Thanks for reporting!
