### ISSUE TITLE
Compatibility with Compact Machines

### ISSUE THREAD

**Issue by LiamJTolentino** [CyclopsMC/IntegratedDynamics#988]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I've used the Compact Machines mod with other mods a lot in the past, and so far most of them work flawlessly with the mod, so I was disappointed when I found that Integrated Dynamics logic cables don't connect to the tunnels from that mod. I have, however, found that Integrated Tunnels can be used to move items in and out of the compact machine if there is a valid inventory is on the other side, but at that point you might as well just use a hopper. The only workaround I've found is just using omni-directional connectors to connect to an ID network outside, but that just takes away the fun of using Compact Machines.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Last time I heard CM had full support for generic capabilities and therefore also ID networks.
Could you open an issue for this on their issue tracker?
Last time they looked into enabling support, so it's probably something small to re-enable it.
