### ISSUE TITLE
JEI autocomplete crashes the server when using the logic programmer.

### ISSUE THREAD

**Issue by tetious** [CyclopsMC/IntegratedDynamics#989]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Reproducible server crash when using JEI to autocomplete recipe for machine readers and chests (possibly anything?) into the logic programmer. 

#### Steps to reproduce the problem:

1. Open the Logic Programmer and pick recipe.
2. Search for the Machine Reader recipe in JEI, click the +
3. Server crash. (see attached crashlog)

#### Expected behaviour:

No crash. :)

____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.4.2
- Minecraft: 1.16.5
- Forge: 36.0.10

#### Log file:

https://gist.github.com/tetious/e7f4431de517bbf94d4ba201661024ac

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed in 93a705970c197d7445a864e3d8af0d39046e6612

**Comment by tetious** [comment]
Wow, fast! Thanks! It works great!
