### ISSUE TITLE
Tag 1.16.5 on CurseForge to enable custom profiles to add the mod

### ISSUE THREAD

**Issue by paulhlschr** [CyclopsMC/IntegratedDynamics#990]
#### Issue type:

- :question: Question 

____

#### Question:

Is it possible to tag ID on CurseForge with 1.16.5, as custom profiles and modpacks are not able to include the mod using the CurseForge client, if the profile runs on Forge 1.16.5?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Done.

Note to self: Update all mods to Forge 1.16.5, to avoid having to manually change the CF deploy configs.
