### ISSUE TITLE
Crash: LazyOptional is empty or otherwise returned null

### ISSUE THREAD

**Issue by Pentasis** [CyclopsMC/IntegratedDynamics#992]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I get crashes again placing readers.

#### Steps to reproduce the problem:

1. Placing a redstone reader on a block, this crash may or may not happen.

#### Expected behaviour:

____

#### Versions:

- This mod: 1.4.3
- Minecraft: 1.16.5
- Forge: 36.0.21

#### Log file:

Happened twice in a few minutes, post them both: https://paste.ee/p/Kb99j  and https://paste.ee/p/nLtih

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Pentasis** [comment]
Not sure if it is important but I need to correct myself: the first crash happened placing a redstone **writer**, the second when placing a _logic cable_.

**Comment by rubensworks** [comment]
Looks like my fix for #986 wasn't successful.
I guess we'll have to wait for the fix in Forge (https://github.com/MinecraftForge/MinecraftForge/issues/7610)

**Comment by rubensworks** [comment]
Should be fixed in recent Forge versions.
