### ISSUE TITLE
[Request] Extend Menril Wood Variants

### ISSUE THREAD

**Issue by MuteTiefling** [CyclopsMC/IntegratedDynamics#993]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Please consider bringing the menril tree in line with other wood variants. Currently missing:
Stripped Log
Wood Block (bark texture on all sides)
Stripped Wood Block

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by MuteTiefling** [comment]
Thanks for getting this out so quick, nice work :D
