### ISSUE TITLE
1.16.5 Typo in book.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedDynamics#994]
![HqBPemLm 1](https://user-images.githubusercontent.com/10351221/107988588-f9ff4b00-6f95-11eb-8bec-e3fb2e8496aa.jpg)

**Comment by P3rf3ctXZer0** [comment]
"Cutorial"

**Comment by P3rf3ctXZer0** [comment]
1.16.5

**Comment by rubensworks** [comment]
Thanks for reporting!
