### ISSUE TITLE
Drying Basin unlimited menril when Performant is loaded

### ISSUE THREAD

**Issue by Dalgam** [CyclopsMC/IntegratedDynamics#997]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Squeezing a Menril Log and then removing the Menril Block will cause the Menril block to regenerate indefinitely until the client is restarted. Breaking and placing the basin on the same place or another place will not stop the issue.

#### Steps to reproduce the problem:

1. Have both ID and Performant installed 
2. Place and squeeze a Menril Log in the Squeezer with an adjacent Drying Basin
3. Remove the formed Menril Block and wait
4. A new Menril Block will appear.

#### Expected behaviour:

No more blocks should appear after the initial one appears.

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.5.0
- Minecraft: 1.16.5
- Forge: 36.0.39
- Performant: performant-1.16.2-4-3.30m

I was playing the Stacia Expert 1.9 modpack when I discovered the bug but were able to reproduce the issue with a custom pack created through the GDLauncher with only the aforementioned mods at the same versions.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
See #984, TL;DR, don't use Performant, it breaks mods.
