### ISSUE TITLE
[1.16.5] Dedicated server crash when using incompatible operator for input type in Lazy List Builder

### ISSUE THREAD

**Issue by karelmikie3** [CyclopsMC/IntegratedDynamics#998]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The server crashes when using an operator for the Lazy List Builder which is incompatible with the variable taken as an input.
Having looked at the code, it seems to call a client-side method for localizing the error message on the server, which in turn crashes the server as the method is not available.

I have reproduced this issue using only the offending mods.

![image](https://user-images.githubusercontent.com/3154444/109052061-82d75e80-76db-11eb-8f11-e1ddefead7cc.png)
![image](https://user-images.githubusercontent.com/3154444/109052097-88cd3f80-76db-11eb-9581-c4248517f041.png)
![image](https://user-images.githubusercontent.com/3154444/109052115-8e2a8a00-76db-11eb-90f7-4eed15a045f5.png)
After inserting the last variable card the server crashes immediately

And to be clear, this only happens when using a dedicated server, not in singleplayer with the integrated server.

#### Steps to reproduce the problem:

1. Build a system of three display panels
2. Make a variable of any type, a boolean for example
3. Make an operator that is incompatible with the type, in this case integer increment.
4. Make a 'lazybuilt' with the variable and the incompatible operator.
5. Insert the variable and operator each in to one of the display panels
6. Insert the 'lazybuilt' into the third panel and the server crashes immediately.

#### Expected behaviour:

I expected it not to crash and to display a red cross with a localized error message in the GUI (which also doesn't work when an error actually occurs in game)
____

#### Versions:

- This mod: 1.5.0
- CommonCapabilities: 2.5.6
- CyclopsCore 1.11.3
- Minecraft: 1.16.5
- Forge: 36.0.42

#### Log file:

[crash report](https://paste.ee/p/yXM5D)
[log](https://paste.ee/p/caUHO)
[debug log](https://paste.ee/p/iXlcn)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like #981 wasn't properly fixed yet.
