### ISSUE TITLE
Client crash when opening part GUI

### ISSUE THREAD

**Issue by Nonsanity** [CyclopsMC/IntegratedDynamics#999]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Client crashes when interacting with an Integrated Dynamics part. The crash report seems to suggest the problem is in rendering the GUI, if I'm interpreting it correctly. Though that could be a secondary reaction to something else. There are days when this rarely happens, and days where it happens repeatedly. I haven't been able to yet determine what actions on my part may correlate to the crash. I haven't spent enough time playing with the mod in isolation to capture a crash there.

I am also using Integrated Tunnels parts in all these automations, so the problem might be from there.

#### Steps to reproduce the problem:

In setting up several ID automations, sometimes the client would crash when I try to open the interface for a system part. Integrated Tunnels is being heavily used in these automations. 

1. ...

#### Expected behaviour:

A lack of client crashes would be greatly preferred if that option becomes available. :)

____

#### Versions:

- This mod: IntegratedDynamics-1.16.4-1.4.3
- Add-on: IntegratedTunnels-1.16.4-1.6.16
- Minecraft: 1.16.5
- Forge: 36.0.21

It has been reported by others (now with my additional comments and crash log) on the All the Mods 6 github page: issue 1123.

#### Log file:

https://controlc.com/7490aaa0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by maikotui** [comment]
I have a similar issue on IntegratedDynamics-1.16.4-1.4.3 with add-on IntegratedTunnels-1.16.4-1.6.16 on Minecraft 1.16.4 using Forge 35.1.37. Crash occurs when interacting with different GUI interfaces, such as the item importer interface. Just loading up the interface can cause the crashes. Here is my log file in case it helps with debugging.

https://controlc.com/8e72cabd

<blockquote><div><strong><a href="https://controlc.com/8e72cabd">integrated-tunnels-crash - 8e72cabd</a></strong></div><div>---- Minecraft Crash Report ----  // Shall we play a game?    Time: 2/28/21 9:54 PM  Descr - 8e72cabd</div></blockquote>
